gnuradio/gnuradio

gr-qtgui/apps/CMakeLists.txt, gr-qtgui/apps/gr_spectrogram_plot, gr-qtgui/apps/plot_form.py, gr-qtgui/apps/plot_spectrogram_base.py, gr-qtgui/include/gnuradio/qtgui/waterfall_sink_c.h, gr-qtgui/include/gnuradio/qtgui/waterfall_sink_f.h, gr-qtgui/include/gnuradio/qtgui/waterfalldisplayform.h, gr-qtgui/lib/WaterfallDisplayPlot.cc, gr-qtgui/lib/waterfall_sink_c_impl.cc, gr-qtgui/lib/waterfall_sink_c_impl.h, gr-qtgui/lib/waterfall_sink_f_impl.cc, gr-qtgui/lib/waterfall_sink_f_impl.h, gr-qtgui/lib/waterfalldisplayform.cc
Fixes for Y-Axis scaling issues in gr_spectrogram_plot_* and a new gr_spectrogram_plot script which reads detached headers and auto-fills some stuff.
=> Offlineplotfixes

gr-utils/python/modtool/CMakeLists.txt, gr-utils/python/modtool/__init__.py, gr-utils/python/modtool/modtool_rename.py
Added rename capability to gr_modtool
modtool/rename: added python block support
modtool/rename: added C++ QA code support
modtool/rename: Removed superfluous print statements
=> modtool/rename: squashed commits for pull request.

gr-digital/grc/digital_packet_headergenerator_bb.xml, gr-digital/include/gnuradio/digital/packet_headergenerator_bb.h, gr-digital/lib/packet_headergenerator_bb_impl.cc, gr-digital/lib/packet_headergenerator_bb_impl.h
Hi @jmcorgan 
I've created another new branch with the updates on packet_headergenerator of gr-digital. Could you check it?
Thanks!
Best,
Zhe
=> digital: added callback function set_header_formatter to packet_headergenerator_bb

gr-blocks/grc/blocks_probe_rate.xml, gr-blocks/lib/probe_rate_impl.cc
=> blocks: add message output port to probe_rate block

gr-zeromq/lib/pub_sink_impl.cc, gr-zeromq/lib/push_sink_impl.cc, gr-zeromq/lib/rep_sink_impl.cc
=> zmq: fix for data corruption when not using tags

gr-video-sdl/CMakeLists.txt, gr-video-sdl/grc/CMakeLists.txt, gr-video-sdl/grc/video_block_tree.xml, gr-video-sdl/grc/video_sdl_sink.xml
This is a flexible GRC block for the gr-video-sdl sink.
=> Video sink GRC block

gr-blocks/lib/throttle_impl.cc
This is a realistic scenario on 32-bit systems (more specifically, on systems where a long is 32-bits). If you are experimenting with GNUradio / the throttler and set for example the sample_rate to 1, chances are you end up with a negative value for sleep(), which won't sleep at all and leaves you confused about why the throttler is not working.
=> Warn when the throttlers sleep time variable overflows

gr-blocks/include/gnuradio/blocks/multiply_matrix_XX.h.t, gr-blocks/lib/multiply_matrix_cc_impl.cc, gr-blocks/lib/multiply_matrix_ff_impl.cc
=> blocks: Fixed static init of matrix_multiply members

CMakeLists.txt, gnuradio-runtime/lib/CMakeLists.txt, gr-analog/lib/CMakeLists.txt, gr-channels/lib/CMakeLists.txt, gr-digital/lib/CMakeLists.txt, gr-dtv/lib/CMakeLists.txt
=> Volk CMake fixes

gnuradio-runtime/include/gnuradio/hier_block2.h, gnuradio-runtime/lib/hier_block2.cc, gnuradio-runtime/lib/hier_block2_detail.cc, gnuradio-runtime/lib/hier_block2_detail.h, gnuradio-runtime/swig/hier_block2.i
The hier_block2 can now have min and max output buffer set.
Addresses: Bug #724
=> Hier buff tweak

gr-dtv/lib/atsc/atsc_sync_impl.cc, gr-dtv/lib/atsc/atsc_sync_impl.h, gr-fec/lib/cc_decoder_impl.cc, gr-fec/lib/cc_decoder_impl.h, gr-qtgui/lib/displayform.cc
a few misc fixes we found recently. commits describe the changes.
=> Misc fixes

grc/gui/Connection.py
(this the branch from gnuradio-wg-grc, can't issue a pull request from there)
=> GRC changes to maint

gnuradio-runtime/lib/top_block_impl.cc, gnuradio-runtime/lib/top_block_impl.h, gnuradio-runtime/python/gnuradio/gr/top_block.py, gnuradio-runtime/swig/top_block.i, gr-blocks/python/blocks/qa_hier_block2.py
=> fix deadlock in unlock() when called from Python - #594 (resend)

gr-qtgui/python/qtgui/range.py
This fixes the range having the wrong starting value.
=> Qtgui range start position bug fix

gr-blocks/grc/blocks_repack_bits_bb.xml, gr-blocks/lib/pdu_to_tagged_stream_impl.cc, gr-blocks/lib/repack_bits_bb_impl.cc, gr-blocks/lib/tagged_stream_mux_impl.cc, gr-digital/include/gnuradio/digital/correlate_and_sync_cc.h, gr-digital/include/gnuradio/digital/packet_header_default.h
Pulled in from Tom's packet_handler branch.
=> blocks: misc. formatting cleanups

gr-fec/grc/fec_block_tree.xml, gr-fec/grc/ldpc_decoder_def_list.xml, gr-fec/grc/ldpc_encoder_def_list.xml, gr-fec/grc/tpc_decoder_def_list.xml, gr-fec/grc/tpc_encoder_def_list.xml, gr-fec/include/gnuradio/fec/tpc_common.h, gr-fec/include/gnuradio/fec/tpc_decoder.h, gr-fec/include/gnuradio/fec/tpc_encoder.h, gr-fec/lib/CMakeLists.txt, gr-fec/lib/tpc_common.cc, gr-fec/lib/tpc_decoder.cc, gr-fec/lib/tpc_encoder.cc, gr-fec/swig/fec_swig.i
=> Adding TPC Encoder and Decoder from Kiran's work

gr-fec/lib/tpc_decoder.cc
Not really an issue, but coverity is right in this case:
[https://scan6.coverity.com:8443/reports.htm#v31371/p10336/fileInstanceId=27864390&defectInstanceId=9318152&mergedDefectId=746150](Memset fill truncated)
=> Fixing memset(..,0xCCCC,...)

gr-blocks/lib/pack_k_bits_bb_impl.h
=> removed unused d_k member

gr-qtgui/python/qtgui/range.py
Fixed several bugs/usability issues.
=> QT Range Fixes

gr-fec/include/gnuradio/fec/tpc_decoder.h, gr-fec/lib/tpc_decoder.cc
- fp never initialized but still closed in dtor; now checks if it's a valid pointer.
- whitespace cleanup.
=> fec: tpc cleanup.

docs/doxygen/Doxyfile.in
Remove any local paths, no longer pull in volk, and other minor
cleanups.
=> docs: doxyfile maintenance.

gnuradio-runtime/include/gnuradio/rpcbufferedget.h, gnuradio-runtime/include/gnuradio/rpcserver_booter_thrift.h, gnuradio-runtime/include/gnuradio/rpcserver_thrift.h, gnuradio-runtime/include/gnuradio/thrift_application_base.h, gnuradio-runtime/include/gnuradio/thrift_server_template.h, gnuradio-runtime/lib/controlport/thrift/README, gnuradio-runtime/lib/controlport/thrift/rpcserver_booter_thrift.cc, gnuradio-runtime/lib/controlport/thrift/rpcserver_thrift.cc, gnuradio-runtime/lib/controlport/thrift/thrift-codebase-shutdown-patch.diff
Some better locking and handling of thread issues and info on a suspected Thrift bug.
=> ConrolPort mutexes

gr-uhd/lib/usrp_sink_impl.cc, gr-uhd/lib/usrp_source_impl.cc
Also removed spurious code that should have gone out in the previous
refactoring.
=> uhd: Fixes for CID 1296559 and 1090067 and more

gr-digital/grc/digital_constellation.xml, gr-digital/grc/digital_constellation_rect.xml
Used work-in-progress name of function, not actual name.
Also cleans up some tab and formatting issues.
=> digital: (issue #784) fixes bug in constellation_rect GRC definition.

grc/scripts/gnuradio-companion
=> gnuradio-companion: Exit if no X server available.

gr-qtgui/grc/qtgui_waterfall_sink_x.xml, gr-qtgui/include/gnuradio/qtgui/waterfalldisplayform.h, gr-qtgui/lib/WaterfallDisplayPlot.cc, gr-qtgui/lib/waterfall_sink_c_impl.cc, gr-qtgui/lib/waterfall_sink_c_impl.h, gr-qtgui/lib/waterfalldisplayform.cc
bit of cleanup to suchsamples commit
bugfixes
... Adding a message port to work with O'Shea's such samples tools...
=> updates to waterfall for suchsamples

gnuradio-runtime/lib/buffer.cc
Looked like a race condition if two blocks are reading from the same
buffer; one block calls prune before the other one can, and then it no
longer gets its tags. This puts back in the original protections we
used when pruning with vectors, only we don't have to restart the
iterator at the beginning and can exit sooner because of the sort
order. Likely slower than the multimap erase, so we will have to
reinvestigate what kind of performance hit we take and if we can do
better.
=> runtime: fixes a problem with tag pruning.

gr-fec/lib/async_decoder_impl.cc
Need to calculate based on nbits_in*rate.
=> fec: Fixed async_decoder. Can't use nbits_out because it's 0 at this point

gr-fec/grc/variable_polar_code_configurator.xml, gr-fec/python/fec/polar/CMakeLists.txt, gr-fec/python/fec/polar/README.md, gr-fec/python/fec/polar/__init__.py, gr-fec/python/fec/polar/channel_construction.py, gr-fec/python/fec/polar/channel_construction_awgn.py, gr-fec/python/fec/polar/channel_construction_bec.py, gr-fec/python/fec/polar/channel_construction_bsc.py, gr-fec/python/fec/polar/decoder.py, gr-fec/python/fec/polar/helper_functions.py, gr-fec/python/fec/polar/polar_channel_construction
This PR fixes bugs I encountered while doing simulations.
Most notably one channel construction algorithm hinted at the wrong channel model.
Also, some calculations did some incorrect indexing.
Large channel constructions should work faster now, at least for BEC because of more NumPy vector magic.
=> Polar bugfixes

gr-uhd/include/gnuradio/uhd/usrp_source.h, gr-uhd/lib/usrp_sink_impl.cc, gr-uhd/lib/usrp_source_impl.cc, gr-uhd/lib/usrp_source_impl.h
Please cross-check with Martin Braun
=> gr-uhd enable/disable issue stream cmd on start

gr-digital/grc/digital_constellation.xml
Added already available constellation types (i.e. 16QAM) to the grc block 'constellation object' to choose from.
=> gr-digital: add more constellation types to grc constellation block

gr-blocks/include/gnuradio/blocks/vector_source_X.h.t, gr-blocks/lib/vector_source_X_impl.h.t, gr-blocks/python/blocks/qa_vector_sink_source.py
ability to set repeat to False from python after creating a vector source. QA added as customary bribe
=> Vector repeat

gnuradio-runtime/python/gnuradio/ctrlport/gr-perf-monitorx
Fixes some issues with versions of matplotlib and networkx modules.
Adds small offset to calls to log so we never take log(0).
=> Updates and fixes to gr-perf-monitorx

gr-qtgui/CMakeLists.txt, gr-qtgui/examples/c++/CMakeLists.txt, gr-qtgui/examples/c++/display_qt.cc, gr-qtgui/examples/c++/display_qt.h, gr-qtgui/include/gnuradio/qtgui/freq_sink_c.h, gr-qtgui/include/gnuradio/qtgui/freq_sink_f.h, gr-qtgui/include/gnuradio/qtgui/waterfall_sink_c.h, gr-qtgui/include/gnuradio/qtgui/waterfall_sink_f.h
Simple example showing how to do QTGUI apps directly in C++.
=> QTGUI C++ example

gr-uhd/grc/gen_uhd_usrp_blocks.py, gr-uhd/include/gnuradio/uhd/usrp_source.h, gr-uhd/lib/usrp_block_impl.h, gr-uhd/lib/usrp_sink_impl.cc, gr-uhd/lib/usrp_source_impl.cc, gr-uhd/lib/usrp_source_impl.h, gr-uhd/swig/uhd_swig.i
This commit adds additional controls and functionality to gr-uhd.
=> Added controls for importing, exporting, and sharing LOs

gnuradio-runtime/include/gnuradio/prefs.h, gnuradio-runtime/lib/prefs.cc
... new PR after rebasing what was PR'ed in #821.
=> Rewrote the prefs parser to be based on boost::program_options

gr-blocks/lib/min_XX_impl.cc.t
=> blocks: fix angry min_xx_impl warningsx

gr-channels/grc/channels_block_tree.xml, gr-channels/grc/channels_selective_fading_model2.xml, gr-channels/include/gnuradio/channels/CMakeLists.txt, gr-channels/include/gnuradio/channels/selective_fading_model2.h, gr-channels/lib/CMakeLists.txt, gr-channels/lib/fading_model_impl.cc, gr-channels/lib/flat_fader_impl.cc, gr-channels/lib/flat_fader_impl.h, gr-channels/lib/selective_fading_model2_impl.cc, gr-channels/lib/selective_fading_model2_impl.h, gr-channels/lib/selective_fading_model_impl.cc, gr-channels/swig/channels_swig.i
Improvements & Fixes in Fading Channel Model
=> Improvements & Fixes in Fading Channel Model

gnuradio-runtime/examples/mp-sched/wfm_rcv_pll_to_wav.py, gr-digital/examples/narrowband/benchmark_add_channel.py, gr-digital/examples/ofdm/benchmark_add_channel.py, gr-uhd/apps/hf_radio/radio.py
I have tested it only against next, but it looks like optfir was moved into filters long time ego.
=> filters: fix optfir import

gr-zeromq/lib/base_impl.cc, gr-zeromq/lib/pull_msg_source_impl.cc, gr-zeromq/lib/push_sink_impl.cc, gr-zeromq/lib/rep_msg_sink_impl.cc, gr-zeromq/lib/rep_sink_impl.cc, gr-zeromq/lib/req_msg_source_impl.cc, gr-zeromq/lib/sub_msg_source_impl.cc
=> gr-zmq: Fix build with gcc6.

gr-fec/python/fec/polar/polar_channel_construction, gr-filter/examples/fft_filter_ccc.py, gr-filter/examples/fir_filter_ccc.py, gr-filter/examples/fir_filter_fff.py, gr-qtgui/apps/plot_base.py, gr-utils/python/utils/gr_plot_char, gr-utils/python/utils/gr_plot_const, gr-utils/python/utils/gr_read_file_metadata, gr-utils/python/utils/plot_data.py
I'm working on more, but I'm now stuck on various bugs (few already merged, few not solved ...)
=> more OptionParser to ArgumentParser conversions

cmake/Modules/FindQwt.cmake
fixes segfault do to libgnuradio-qtgui linking against libQtGui.so.4
=> fixed the FindQwt to prefer pkgconfig for qt5-qwt

gr-blocks/lib/nlog10_ff_impl.cc, gr-blocks/lib/nlog10_ff_impl.h, gr-blocks/python/blocks/qa_nlog10.py
The inner VOLK demanded improvement of this.
Still not perfect; a volk_32f_s32f_log2_scaled kernel would be better.
=> VOLKized nlog10

gnuradio-runtime/examples/mp-sched/plot_flops.py, gr-utils/python/utils/gr_plot_const, gr-utils/python/utils/gr_read_file_metadata
=> cleanup: remove nargs=1 from ArgumentParser

README.hacking, docs/doxygen/other/doxypy.py, dtools/bin/update_fsf_address, gr-audio/doc/audio.dox, gr-audio/examples/python/audio_play.py, gr-audio/examples/python/audio_to_file.py, gr-audio/examples/python/dial_tone_daemon.py, gr-audio/examples/python/dial_tone_wav.py, gr-audio/examples/python/mono_tone.py, gr-audio/examples/python/multi_tone.py, gr-audio/examples/python/noise.py, gr-audio/examples/python/spectrum_inversion.py, gr-audio/examples/python/test_resampler.py, gr-blocks/examples/ctrlport/usrp_sink_controller.py, gr-blocks/examples/ctrlport/usrp_source_controller.py, gr-digital/examples/example_costas.py, gr-digital/examples/example_fll.py, gr-digital/examples/example_timing.py, gr-digital/examples/gen_whitener.py, gr-zeromq/examples/python/client.py, gr-zeromq/examples/python/gui.py, gr-zeromq/examples/python/server.py
Few more conversion to ArgumentParser. Remainig usage of OptionParser will be converted after fix of various bug, which cause fails during code testing.
=> convert OptionParser to ArgumentParser

gr-fcd/lib/hid/hid-libusb.c, gr-fcd/lib/hid/hidapi.h, gr-fcd/lib/hid/hidmac.c, gr-fcd/lib/hid/hidwin.c
This contains necessary fixes for Mac OS X.
=> fcd: Update hidapi to latest HEAD.

gr-audio/lib/windows/windows_source.cc, gr-audio/lib/windows/windows_source.h
#939 ... implemented windows audio source
=> gr-audio: refactored windows audio source see github #939

gr-audio/lib/windows/windows_sink.cc, gr-audio/lib/windows/windows_sink.h
The OK to block flag had no effect in the initial version, now it is implemented.
=> gr-audio: implemented blocking in windows audio sink

gnuradio-runtime/lib/controlport/rpcmanager.cc, gnuradio-runtime/lib/controlport/rpcserver_selector.cc
=> Fixed initialization order of ctrlport static variables

grc/core/utils/epy_block_io.py, grc/gui/ActionHandler.py
- fixes #1089 
- fixes minor deprecating warning introduced by #1060
=> new flowgraph gen mode

gr-uhd/apps/uhd_app.py
Enables specification of --lo-export {None, True, False} and --lo-source {None, external, internal, companion} in uhd_app applications for usage with a TwinRX.
Specification of None skips specification of LO export/source features for a channel.
=> gr-uhd: add TwinRX LO sharing arguments to uhd_app

gr-qtgui/grc/qtgui_time_sink_x.xml
Initial issue: #1124 
Initial PR: #1150 
Current Issue solved: #1185 
I am pretty sure I tested it when I submitted it. Although not sure why this happened. I have solved the problem for now.
Sorry for the inconvenience caused.
=> QT Time Sink TemplateError: Invalid Syntax solved

gr-qtgui/grc/qtgui_time_sink_x.xml
=> qtgui: Time Sink: redundant config options removed

gr-uhd/apps/uhd_app.py
This change allows to select different time/clock-sources in uhd_app for each motherboard (similar to antenna and subdev spec). 
Also it replaces all `{argument}_normalize_sel` helper functions with a generic one.
Patch applies cleanly on next.
=> gr-uhd: select time/clock-sources in uhd_app per motherboard, cleanup normalize_sel code

gr-uhd/lib/usrp_source_impl.cc
If uhd supports stream API use it to call `issue_stream_cmd` in usrp_source_impl
=> gr-uhd: use stream api for issue_stream_cmd

gnuradio-runtime/include/gnuradio/random.h, gnuradio-runtime/lib/math/random.cc
=> replaced uniform_int_distribution with uniform_int

CMakeLists.txt, cmake/Modules/GrBoost.cmake, docs/doxygen/CMakeLists.txt, docs/doxygen/other/build_guide.dox.in
This PR will probably linger a bit until we've figured out the actual versions we want.
=> Update dependency versions on next

CMakeLists.txt, cmake/Modules/GrBoost.cmake, docs/doxygen/CMakeLists.txt, docs/doxygen/other/build_guide.dox.in
- Autogen docs appropriately
- Make it easier to maintain min versions
=> cmake/docs: Move min versions into a single spot, put them all into vars

gr-blocks/grc/blocks_block_tree.xml, gr-blocks/grc/blocks_exponentiate_const_cci.xml, gr-blocks/include/gnuradio/blocks/CMakeLists.txt, gr-blocks/include/gnuradio/blocks/exponentiate_const_cci.h, gr-blocks/lib/CMakeLists.txt, gr-blocks/lib/exponentiate_const_cci_impl.cc, gr-blocks/lib/exponentiate_const_cci_impl.h, gr-blocks/python/blocks/qa_exponentiate_const_cci.py, gr-blocks/swig/blocks_swig7.i
The Complex to Complex^M block takes the M-th power of the input complex stream. The exponent parameter must be at least 1. There is also a callback function so the exponent can be changed at runtime.
=> blocks: Add exponentiate const int block

gr-digital/examples/ofdm/rx_ofdm.grc
=> digital: set rx_ofdm.grc to no_gui mode

gnuradio-runtime/lib/math/qa_fast_atan2f.cc
Try and fix the using std::isnan issue in ubuntu14.04
=> qa: fix qa_fast_atan2f

cmake/Modules/GrSwig.cmake, gr-blocks/include/gnuradio/blocks/tag_share.h
This branch will accumulate fixes for warnings created during the build process.
=> Fix warnings on master branch compile

gnuradio-runtime/include/gnuradio/rpcmanager.h, gnuradio-runtime/lib/controlport/rpcserver_selector.cc, gnuradio-runtime/lib/thread/thread_group.cc, gr-blocks/lib/tcp_server_sink_impl.h
This will accumulate fixes for warnings during build process on next branch.
=> Fix warnings on next branch

gr-blocks/python/blocks/qa_file_source_sink.py
Instead of setting a fixed file name for unit test of file_source,
rather employ the tempfile module in a with statement.
This was suggested by Johnathan in https://github.com/gnuradio/gnuradio/pull/1301
=> Use Python's tempfile module for unit test

gr-fft/lib/fft.cc
Add a lockfile for access to the fftw wisdom. 
Unfortunately in Linux the lockfile will be locked for all threads in one process so there has to be a mutex to lock other threads out as well.
I didn't test running `all` GR tests with a high job number.
=> gr-fft: add locking mechanism to fftw_wisdom

gr-uhd/apps/uhd_app.py
Before, there was an issue where things could go awry with multiple
devices and only specifying a single --spec option.
=> uhd: Properly normalized selection of options for multi-device ops

gr-qtgui/doc/qtgui.dox
Just fixed some spelling/grammar/formatting errors
=> doc: proofed/cleaned up qtgui doxygen documentation

gr-blocks/grc/blocks_file_source.xml, gr-blocks/include/gnuradio/blocks/file_source.h, gr-blocks/lib/file_source_impl.cc, gr-blocks/lib/file_source_impl.h, gr-blocks/python/blocks/qa_file_source_sink.py
- Add a configurable "file_begin" stream tag
which is especially useful in repeat mode.
- Added unit tests for new functionality
=> blocks: file_source ("file_begin" stream tag)

gr-fec/grc/variable_polar_code_configurator.xml
This should fix Issue #1385 
Added some docs and removed the auto-hide magic, which seemed to cause trouble.
=> fixed polar code configurator GRC bug

gr-digital/lib/interpolating_resampler.cc
=> gr-digital: fixed casting failure compile error with gcc 4.6

grc/scripts/freedesktop/gnuradio-grc.desktop
- Change Name to a full application name.
- Add Comment section.
=> grc: some tweaks to the desktop file

docs/doxygen/other/metadata.dox, docs/doxygen/other/operating_fg.dox, docs/doxygen/other/pmt.dox, docs/exploring-gnuradio/exploring_gnuradio.dox
=> doc: proofed sections: metadata, PMT, handling fgs, exploring gr

gr-qtgui/python/qtgui/range.py
=> Fix: Set qt-gui precision before setting value

grc/CMakeLists.txt, grc/converter/main.py, grc/core/FlowGraph.py, grc/core/generator/hier_block.py, grc/core/utils/flow_graph_complexity.py, grc/gui/Dialogs.py, grc/main.py, grc/scripts/gnuradio-companion
GRC opens on both Python 2 and 3
=> Grc: Python 2/3 bug fixes

gr-blocks/lib/vector_sink_X_impl.cc.t, gr-blocks/lib/vector_sink_X_impl.h.t
=> added a mutex to the data extraction, clear and work methods

gr-digital/examples/demod/symbol_sync_test_complex.grc, gr-digital/examples/demod/symbol_sync_test_float.grc
- Added annotations
- Reduced number of blocks, same functionality, less distraction
- Minor label changes
=> digital: Cosmetic updates to symbol sync examples

docs/exploring-gnuradio/dial_tone.py, docs/exploring-gnuradio/fm_demod.py, gnuradio-runtime/examples/mp-sched/affinity_set.py, gnuradio-runtime/python/gnuradio/gru/gnuplot_freqz.py, gr-uhd/apps/uhd_siggen_base.py, gr-utils/python/modtool/modtool_add.py, gr-utils/python/modtool/modtool_disable.py, gr-utils/python/modtool/modtool_makexml.py, gr-utils/python/modtool/modtool_newmod.py, gr-utils/python/modtool/modtool_rename.py, gr-utils/python/modtool/modtool_rm.py, gr-vocoder/examples/alaw_audio_loopback.py, gr-vocoder/examples/codec2_audio_loopback.py, gr-vocoder/examples/cvsd_audio_loopback.py, gr-vocoder/examples/g721_audio_loopback.py, gr-vocoder/examples/g723_24_audio_loopback.py, gr-vocoder/examples/g723_40_audio_loopback.py, gr-vocoder/examples/gsm_audio_loopback.py, gr-vocoder/examples/ulaw_audio_loopback.py
Removed eval() from eval(input()).
=> Fix typos from switch to Python 3

gr-blocks/grc/blocks_moving_average_xx.xml, gr-blocks/include/gnuradio/blocks/moving_average_XX.h.t, gr-blocks/lib/moving_average_XX_impl.cc.t, gr-blocks/lib/moving_average_XX_impl.h.t, gr-blocks/python/blocks/qa_moving_average.py
This allows users to average per-element.
Might be very useful for spectrum "condensing" and such.
=> Added a vector operation mode to the moving average

gr-digital/swig/digital_swig1.i
This answers
https://lists.gnu.org/archive/html/discuss-gnuradio/2017-09/msg00219.html ,
Chad Spooner's quest for GLFSR-generated FIR taps withing GRC.
=> added glfsr.h to the swig'ed files

README.building-boost
=> Removed Some Extra Blank Lines in README.building-boost.

gr-utils/python/modtool/modtool_add.py, gr-utils/python/modtool/modtool_rm.py, gr-utils/python/modtool/util_functions.py
* main advantage: better line editing
* tab-completion for gr_modtool add
=> Adding readline capabilities to gr_modtool

docs/doxygen/other/logger.dox
Updated documentation for using logging in OOT modules. Related to issue #1608.
=> logging: updated doxygen with how to use logging in OOT

gr-digital/lib/chunks_to_symbols_XX_impl.cc.t
Previously, the setters were absolutely free to rewrite and resize the
internal LUT while work() was in progress, which really is a recipe for
disaster.
=> digital: d_setlock mutex around modification of symbol LUT

gnuradio-runtime/include/gnuradio/xoroshiro128p.h, gr-analog/lib/fastnoise_source_X_impl.cc.t, gr-analog/lib/fastnoise_source_X_impl.h.t, gr-analog/python/analog/qa_fastnoise.py
Closes gnuradio/gnuradio#1542.
=> replaced thread-unsafe rand() in fastnoise_source by XOROSHIRO128+

gnuradio-runtime/include/gnuradio/py_feval.h, gnuradio-runtime/include/gnuradio/sys_pri.h
After a discussion with Maitland Bottoms of debian packaging fame, these obviously helpful fixes came up.
Closes #1659.
=> Runtime: ABI checker happiness

gr-fft/lib/fft.cc
FFTW wisdom file locking was only taking place from gr::fft::fft_complex.
Generalise lock init and also enable it from 'fft_real_fwd' and 'fft_real_rev'.
=> fft: fix FFTW wisdom file locking for fft_real_fwd and fft_real_rev

gr-utils/python/modtool/modtool_rm.py
Proposed fix for improving blocks(s) removal in modtool_rm.py
=> fix #1675: Improve check for block(s) removal

gr-digital/include/gnuradio/digital/constellation.h
=> Better documentation explaining what QPSK is doing.

grc/gui/canvas/flowgraph.py
Fixed a bug where blocks didn't show up when pasting them. I believe it works like in the `master` branch now. 
I have removed the if statement regarding epy_blocks. Looked like it was redundant, but please correct me if I'm wrong! :)
=> grc: Fixed pasting blocks from clipboard

docs/doxygen/Doxyfile.in, docs/doxygen/Doxyfile.swig_doc.in, gnuradio-runtime/lib/CMakeLists.txt, gnuradio-runtime/lib/thread/thread.cc, gr-atsc/include/gnuradio/atsc/slicer_agc_impl.h, gr-audio/lib/CMakeLists.txt, gr-audio/lib/alsa/alsa_sink.cc, gr-audio/lib/alsa/alsa_source.cc, gr-fcd/CMakeLists.txt, gr-qtgui/CMakeLists.txt, gr-qtgui/gnuradio-qtgui.pc.in, gr-utils/python/modtool/gr-newmod/docs/doxygen/Doxyfile.in, gr-utils/python/modtool/gr-newmod/docs/doxygen/Doxyfile.swig_doc.in, grc/scripts/freedesktop/gnuradio-grc.desktop
=> Merge the debian patches for 3.7

docs/doxygen/other/build_guide.dox.in
=> docs: adding zmq, sphinx to build deps, restructure optionals

gnuradio-runtime/include/gnuradio/block.h, gnuradio-runtime/lib/block.cc, gr-blocks/include/gnuradio/blocks/pdu.h, gr-blocks/lib/pdu.cc, gr-blocks/lib/pdu_filter_impl.cc, gr-blocks/lib/pdu_remove_impl.cc, gr-blocks/lib/pdu_set_impl.cc, gr-blocks/lib/pdu_to_tagged_stream_impl.cc, gr-blocks/lib/random_pdu_impl.cc, gr-blocks/lib/socket_pdu_impl.cc, gr-blocks/lib/tagged_stream_to_pdu_impl.cc, gr-blocks/lib/tcp_connection.cc, gr-blocks/lib/tuntap_pdu_impl.cc, gr-digital/lib/header_payload_demux_impl.cc, gr-digital/lib/header_payload_demux_impl.h, gr-uhd/include/gnuradio/uhd/usrp_block.h, gr-uhd/lib/usrp_block_impl.cc, gr-uhd/lib/usrp_block_impl.h, gr-uhd/lib/usrp_sink_impl.cc, gr-uhd/lib/usrp_source_impl.cc
Found thanks to #1697.
Closes #1711.
=> Fix the potential for Static Initialization Order Fiasco

gr-utils/python/modtool/modtool_add.py, gr-utils/python/modtool/modtool_base.py, gr-utils/python/modtool/modtool_disable.py, gr-utils/python/modtool/modtool_help.py, gr-utils/python/modtool/modtool_info.py, gr-utils/python/modtool/modtool_makexml.py, gr-utils/python/modtool/modtool_newmod.py, gr-utils/python/modtool/modtool_rename.py, gr-utils/python/modtool/modtool_rm.py
Fixed most of the errors generated while running modtool scripts against Pylint.
=> modtool: Pylint error fixes

gr-fft/include/gnuradio/fft/fft_vcc.h, gr-fft/include/gnuradio/fft/fft_vfc.h
=> Improved documentation for FFT block.

gr-utils/python/modtool/modtool_rm.py
Fixes #1604
Precompiled a sensible list of blocknames for autocompletion.
=> gr_modtool rm: block candidates

gr-utils/python/modtool/gr-newmod/python/build_utils.py, gr-utils/python/modtool/gr-newmod/python/build_utils_codes.py
Basic Pylint fixes in the gr-newmod scripts
=> gr-newmod: Pylint fixes in python scripts

gr-blocks/lib/float_to_complex_impl.cc
=> move declaration to case

gr-blocks/lib/float_array_to_int.cc
Replaced hardcoded MAX/MIN values with the ones defined in cstdint.
=> Removed hardcoded value

gr-digital/python/digital/qa_packet_format.py
The one time where logical statements and natural language do not agree.
=> digital: qa_packet_format fix conditionals to wait for messages

grc/blocks/options.xml, grc/core/generator/Generator.py, grc/core/generator/flow_graph.tmpl
As suggested in https://github.com/gnuradio/gnuradio/issues/1704.
=> grc: Added copyright holder to Options block

grc/gui/FileDialogs.py
This is was missing from #1495.
Saving a flowgraph to an existing file, didn't show the override confirmation dialog on my system
=> grc: set parent for file override confirmation dialog

CHANGELOG.md, docs/doxygen/other/build_guide.dox.in
In both the build guide as well as the CHANGELOG.md
=> Documented cppunit dependency removal

gr-filter/lib/fft_filter.cc, gr-filter/lib/filter_delay_fc_impl.cc
=> gr_filter: eradicate undefined behaviour through vector Out-Of-Bound access

gnuradio-runtime/swig/block.i
Resolve https://github.com/gnuradio/gnuradio/issues/1757
=> swig block.i: add void set_output_multiple(int multiple)

CHANGELOG.md, gr-filter/lib/fft_filter.cc, gr-filter/lib/filter_delay_fc_impl.cc
implements #1780 for maint-3.7
=> backport gr_filter: eradicate undefined behaviour through vector Out-Of-Bound access

gr-digital/lib/clock_recovery_mm_cc_impl.cc, gr-digital/lib/crc32_bb_impl.cc
=> Digital out of bound vector access

gr-digital/lib/clock_recovery_mm_cc_impl.cc, gr-digital/lib/crc32_bb_impl.cc
=> Backport digital out of bound vector access

grc/core/generator/flow_graph.py.mako, grc/core/generator/hier_block.py, grc/core/generator/top_block.py
Switched to YAML for hierarchical blocks
=> grc: Fix YAML hier blocks (next)

gr-audio/python/audio/__init__.py
This adresses parts of what @dl1kv noticed in #1874
=> Use proper relative imports in gr-audio's __init__.py

gr-uhd/grc/gen_uhd_usrp_blocks.py, gr-uhd/include/gnuradio/uhd/usrp_sink.h, gr-uhd/lib/usrp_sink_impl.cc, gr-uhd/lib/usrp_sink_impl.h
This adds the LO functions from the Source block to the Sink block.
=> Add functions to USRP Sink block

gr-digital/python/digital/qa_packet_format.py
=> "While !(a ready) and !(b ready)" -> "While !(a ready) or !(b ready)"

grc/gui/Application.py
Add missing action to open recently used files in grc.
See also: [#1867](https://github.com/gnuradio/gnuradio/issues/1867l)
=> Adding Action Open Recent to grc

gr-digital/grc/digital_constellation.block.yml, gr-digital/grc/digital_constellation_rect.block.yml
Fixes https://github.com/gnuradio/gnuradio/issues/2050
=> gr-digital: Un-break Constellation Object and Constellation Rect Object

grc/gui/Actions.py, grc/gui/Application.py, grc/gui/Bars.py
Fixes https://github.com/gnuradio/gnuradio/issues/2042
=> Fixed GRC's "Create New" button

gr-analog/python/analog/fm_emph.py
Duplicate of PR #2017 because I reforked GNU Radio and it screwed up that PR
=> docs- moved documentation inside docstring

gr-uhd/grc/gen_uhd_usrp_blocks.py
- Show/Hide LO settings now works the right way round
- Gain Type changed from bool to enum
- Fix Pylint warning on the YML generation code
=> uhd: Minor fixes to GRC bindings

grc/core/blocks/virtual.py, grc/core/generator/top_block.py
As discussed in https://github.com/gnuradio/gnuradio/issues/2049.
=> grc: Fix virtual blocks

gr-blocks/grc/blocks_socket_pdu.block.yml
Removing leftover code from Cheetah
=> gr-blocks: Un-break Socket PDU block

gr-blocks/include/gnuradio/blocks/integrate.h, gr-blocks/include/gnuradio/blocks/stream_to_tagged_stream.h, gr-blocks/include/gnuradio/blocks/tsb_vector_sink.h, gr-blocks/include/gnuradio/blocks/vector_sink.h, gr-blocks/include/gnuradio/blocks/vector_source.h, gr-blocks/lib/integrate_impl.cc, gr-blocks/lib/integrate_impl.h, gr-blocks/lib/stream_to_tagged_stream_impl.cc, gr-blocks/lib/stream_to_tagged_stream_impl.h, gr-blocks/lib/tsb_vector_sink_impl.cc, gr-blocks/lib/tsb_vector_sink_impl.h, gr-blocks/lib/vector_sink_impl.cc, gr-blocks/lib/vector_sink_impl.h, gr-blocks/lib/vector_source_impl.cc, gr-blocks/lib/vector_source_impl.h, gr-dtv/include/gnuradio/dtv/dvbt2_paprtr_cc.h, gr-dtv/include/gnuradio/dtv/dvbt2_pilotgenerator_cc.h, gr-dtv/lib/dvbt2/dvbt2_paprtr_cc_impl.cc, gr-dtv/lib/dvbt2/dvbt2_paprtr_cc_impl.h, gr-dtv/lib/dvbt2/dvbt2_pilotgenerator_cc_impl.cc, gr-dtv/lib/dvbt2/dvbt2_pilotgenerator_cc_impl.h, gr-qtgui/include/gnuradio/qtgui/vector_sink_f.h, gr-qtgui/lib/vector_sink_f_impl.cc, gr-qtgui/lib/vector_sink_f_impl.h
Hi, I had a look at an issue from last year's hacktoberfest which did not seem to be resolved so far. In accordance with GREP 11 I did some code cleanup on the files I touched.
=> Change vlen variables to unsigned datatype. Fixes #1459

gr-qtgui/grc/qtgui_const_sink_x.block.yml, gr-qtgui/grc/qtgui_freq_sink_x.block.yml, gr-qtgui/grc/qtgui_histogram_sink_x.block.yml, gr-qtgui/grc/qtgui_time_sink_x.block.yml, gr-qtgui/grc/qtgui_waterfall_sink_x.block.yml
This supersedes #2035.
Please, @dl1ksv, check whether this is in your spirit.
=> Rebased: #2035 Making enable/disable and parameter Spectrum width work

grc/gui/canvas/flowgraph.py
When the change was made with gio actions the context menu broke. We need to create a Gtk.Menu from the Gio.Menu to support popup.  Doing this also means that we also need to get access to a Gtk.Widget that has the action group otherwise the context menu will be shown, but the context menu will be show but the states of the menu items and the triggers will not be associated.
We do not cleanly pass down the ApplicationWindow or a parent Widget to these classes, so I had to look for the main window attached to the default application.  We already have code that relies to using the default application, so I am not too worried about it, but it would be nice to look at re-factoring this at some point, maybe even moving the context menu creation to the MainWindow.
=> grc: Restore right click menu. Fixes #2062

cmake/Modules/FindQwt.cmake
This helps with https://github.com/gnuradio/gnuradio/issues/2027.
=> CMake: Update QWT finding routines

gr-analog/include/gnuradio/analog/sig_source.h, gr-analog/lib/sig_source_impl.cc, gr-analog/lib/sig_source_impl.h
Note: This does not include GRC bindings.
Signed-off-by: Adrian Suciu <adrian.suciu@analog.com>
=> analog: sig_source: Add phase parameter

CMakeLists.txt, docs/doxygen/other/build_guide.dox.in
=> Introduce MSVC version check; bump required version to 1800 (VS15)

gr-analog/include/gnuradio/analog/random_uniform_source.h, gr-analog/include/gnuradio/analog/sig_source.h, gr-blocks/lib/vector_source_impl.cc, gr-fft/include/gnuradio/fft/fft_vcc.h, gr-qtgui/lib/freq_sink_f_impl.cc, gr-qtgui/lib/vector_sink_f_impl.cc, gr-uhd/lib/usrp_block_impl.cc, gr-uhd/lib/usrp_block_impl.h, gr-uhd/python/uhd/__init__.py, gr-uhd/swig/uhd_swig.i
These have been driving me nuts. Any commit that applies to maint-3.7 can also go there.
=> Zap a gazillion compiler warnings

gr-dtv/lib/dvb/dvb_bbscrambler_bb_impl.cc, gr-dtv/lib/dvb/dvb_bbscrambler_bb_impl.h, gr-dtv/lib/dvb/dvb_bch_bb_impl.cc, gr-dtv/lib/dvb/dvb_bch_bb_impl.h, gr-dtv/lib/dvb/dvb_ldpc_bb_impl.cc, gr-dtv/lib/dvb/dvb_ldpc_bb_impl.h, gr-dtv/lib/dvbt2/dvbt2_interleaver_bb_impl.cc, gr-dtv/lib/dvbt2/dvbt2_interleaver_bb_impl.h, gr-dtv/lib/dvbt2/dvbt2_pilotgenerator_cc_impl.cc, gr-dtv/lib/dvbt2/dvbt2_pilotgenerator_cc_impl.h
This is a combo of #1373, #1374, #1375, #1376, and #1377. For BBot purposes.
=> gr-dtv enhancements

gr-uhd/grc/gen_uhd_usrp_blocks.py
- Subdev spec wasn't being applied at all
- time/clock source, neither
- Sync wouldn't stay the same value when it was set to "don't sync"
- Bandwidth is no longer set when the value is 0, allowing for a default
behaviour
- OTW format wasn't being applied properly
Fixes #2221.
=> uhd: More fixes to GRC bindings (time/clock source, etc.)

gr-digital/python/digital/qa_header_payload_demux.py
=> digital: Fix some Pylint warnings in qa_header_payload_demux.py

gr-qtgui/grc/qtgui_freq_sink_x.block.yml, gr-qtgui/grc/qtgui_waterfall_sink_x.block.yml, gr-qtgui/include/gnuradio/qtgui/freq_sink_c.h, gr-qtgui/include/gnuradio/qtgui/freq_sink_f.h, gr-qtgui/include/gnuradio/qtgui/waterfall_sink_c.h, gr-qtgui/include/gnuradio/qtgui/waterfall_sink_f.h, gr-qtgui/lib/freq_sink_c_impl.cc, gr-qtgui/lib/freq_sink_c_impl.h, gr-qtgui/lib/freq_sink_f_impl.cc, gr-qtgui/lib/freq_sink_f_impl.h, gr-qtgui/lib/waterfall_sink_c_impl.cc, gr-qtgui/lib/waterfall_sink_c_impl.h, gr-qtgui/lib/waterfall_sink_f_impl.cc, gr-qtgui/lib/waterfall_sink_f_impl.h
This is the rebased version of #1955.
This fixes #1952.
=> Merge #1955 (jjhein's QTGui bandwidth message port)

gr-blocks/grc/blocks_complex_to_interleaved_char.block.yml, gr-blocks/grc/blocks_complex_to_interleaved_short.block.yml, gr-blocks/grc/blocks_interleaved_char_to_complex.block.yml
Following https://github.com/gnuradio/gnuradio/pull/2313/commits/ae2ccee2b63d43b497beea0cf454f6e8d8909a34
=> blocks: Fix remaining interleaved type converters

grc/core/generator/Generator.py, grc/core/generator/flow_graph.tmpl
Fixes https://github.com/gnuradio/gnuradio/issues/1923 for 3.7
=> grc: Remove generated_time from flow_graph.tmpl (maint)

grc/core/generator/cpp_templates/CMakeLists.txt.mako, grc/core/generator/cpp_templates/flow_graph.cpp.mako, grc/core/generator/cpp_templates/flow_graph.hpp.mako, grc/core/generator/flow_graph.py.mako, grc/core/generator/top_block.py
Fixes https://github.com/gnuradio/gnuradio/issues/1923
=> grc: Remove generated_time from GRC-generated files

gr-channels/examples/demo_gmsk.grc, gr-channels/examples/demo_ofdm.grc, gr-channels/examples/demo_qam.grc, gr-channels/examples/demo_quantization.grc, gr-channels/examples/demo_spec_an.grc, gr-channels/examples/demo_two_tone.grc
This commit converts the examples in `gr-channels` to the new YAML format.
This PR is part of an ongoing effort in #2285 .
=> channels: Convert GRC flowgraphs to YAML format

gr-utils/python/modtool/core/rename.py
@swap-nil7 please review this PR
=> gr_modtool: remove unused code in rename.py

grc/core/blocks/_build.py, grc/core/blocks/embedded_python.py, grc/core/blocks/virtual.py
This fixes some issues I found with build custom block classes and also cleans-up previous attempts.
This PR includes https://github.com/gnuradio/gnuradio/pull/2355 (thanks @ptrkrysik), however it supersedes https://github.com/gnuradio/gnuradio/pull/2342.
Marked WIP as the tests for this are still WIP
=> grc: fixes in epy and virtual blocks

gr-audio/lib/windows/windows_sink.cc
Master branch version of #2337.
=> gr-audio: fix windows when receiving > 1 output_multiple per work() call

grc/gui/Bars.py
Fixes https://github.com/gnuradio/gnuradio/issues/2368
=> grc: Make sure underscores are shown in "Open Recent" file list

grc/gui/Application.py
=> grc: Fix save as for existing grc file

gr-utils/python/modtool/cli/add.py, gr-utils/python/modtool/tools/scm.py
The feature for adding `copyrightholder` should be there in the `3.8 release`.
=> Modtool: Add copyright feature

gnuradio-runtime/include/gnuradio/rpcregisterhelpers.h
Add std::vector<int64_t> template specialization to rpcbasic_inserter.
#2372
=> ctrlport: Add int64_t vector to rpcbasic_inserter

gr-uhd/examples/python/freq_hopping.py
Freq_hopping example wasn't working correctly and symptom of it was that
frequency changes were happening in random moments. The reason was that
time of execution of tune commands wasn't specified and so they were
executed as non-timed commands.
In case of of full tuning (dsp_tuning == false) more changes were
needed. 'tx_freq' tag can't be executed as a timed command at all, so I
changed it to 'tx_command' with 'freq' element and also added missing
'time'.
I found out about the issue but credit of fixing it by adding 'time'
element to 'tx_command' tag value goes to Sylvain Munaut, as this change
was suggested by him.
Note: This replaces https://github.com/gnuradio/gnuradio/pull/1759
=> uhd: fix freq_hopping example - missing 'time'

gr-utils/python/modtool/core/add.py
=> modtool add: add C++ QA for both version '37', '38'

gr-vocoder/examples/CMakeLists.txt, gr-vocoder/examples/grfreedv.grc, gr-vocoder/examples/loopback-codec2.grc, gr-vocoder/grc/vocoder_codec2_decode_ps.block.yml, gr-vocoder/grc/vocoder_codec2_encode_sp.block.yml, gr-vocoder/grc/vocoder_freedv_rx_ss.block.yml, gr-vocoder/grc/vocoder_freedv_tx_ss.block.yml, gr-vocoder/include/gnuradio/vocoder/codec2.h, gr-vocoder/include/gnuradio/vocoder/freedv_api.h, gr-vocoder/include/gnuradio/vocoder/freedv_rx_ss.h, gr-vocoder/include/gnuradio/vocoder/freedv_tx_ss.h, gr-vocoder/lib/freedv_rx_ss_impl.cc, gr-vocoder/lib/freedv_rx_ss_impl.h, gr-vocoder/lib/freedv_tx_ss_impl.cc, gr-vocoder/lib/freedv_tx_ss_impl.h, gr-vocoder/swig/vocoder_swig.i
Update to add support for newer modes in codec2 0.8.1.
Fixup grc blocks yml templates, update examples.
Submitted for Maitland
=> gr-vocoder: update codec2 and freedv blocks.

docs/sphinx/source/analog_blocks.rst, docs/sphinx/source/index.rst, gnuradio-runtime/include/gnuradio/fxpt_nco.h, gr-analog/grc/analog_const_source_x.block.yml, gr-analog/grc/analog_sig_source_x.block.yml, gr-analog/include/gnuradio/analog/sig_source.h, gr-analog/lib/sig_source_impl.cc, gr-analog/python/analog/qa_sig_source.py, gr-analog/swig/analog_swig.i
Made a new pull request, with properly squashed commits. Signed CLA has been sent to FSF meanwhile.
=> gr-analog: sig source byte support mode, added qa tests #1994

gr-dtv/lib/dvb/dvb_bbscrambler_bb_impl.cc, gr-dtv/lib/dvb/dvb_bbscrambler_bb_impl.h, gr-dtv/lib/dvb/dvb_bch_bb_impl.cc, gr-dtv/lib/dvb/dvb_bch_bb_impl.h
DVB-S2X VL-SNR MEDIUM frames are not divisible by 8.
=> dtv: Fix scrambler and BCH encoder for MEDIUM size frames (3.7 backport).

gr-uhd/apps/uhd_rx_nogui
- Make Py3k compatible
- Clean up Pylint warnings
- Move to argparse
=> uhd: Update uhd_rx_nogui

gr-channels/grc/channels_selective_fading_model.block.yml, gr-channels/grc/channels_selective_fading_model2.block.yml, gr-channels/lib/selective_fading_model2_impl.cc, gr-channels/lib/selective_fading_model_impl.cc
Also, add () around the default list parameters in the yml files so that the default parameters work in grc
fixes #1974
=> Issue #1974 Reduce the history from ntaps+1 to ntaps

cmake/Modules/FindGSL.cmake
Minor syntax fix related to GSL on windows
=> cmake: fixed gsl definition add for windows

gr-blocks/examples/selector.grc, gr-blocks/grc/blocks.tree.yml, gr-blocks/grc/blocks_selector.block.yml, gr-blocks/include/gnuradio/blocks/CMakeLists.txt, gr-blocks/include/gnuradio/blocks/selector.h, gr-blocks/lib/CMakeLists.txt, gr-blocks/lib/selector_impl.cc, gr-blocks/lib/selector_impl.h, gr-blocks/python/blocks/qa_selector.py, gr-blocks/swig/blocks_swig7.i
Adds c++ implementation of selector block based on copy block and a limited set of QA tests
fixes #2460
=> Selector Block replacement 2460

grc/core/Messages.py, grc/core/platform.py, grc/gui/MainWindow.py
=> GRC: Fix for GRC crash in case of flowgraph error

gr-utils/python/modtool/core/makeyaml.py, gr-utils/python/modtool/tools/grc_yaml_generator.py
Fixes for issues in yaml generator in gr_modtool as mentioned in PR #2418.
=> gr_modtool: fix for yaml generator

gr-digital/examples/packet/example_corr_est.grc, gr-digital/examples/packet/example_corr_est_and_clock_sync.grc, gr-digital/examples/packet/example_corr_est_and_phase_sync.grc, gr-digital/examples/packet/packet_rx.grc, gr-digital/grc/digital_corr_est_cc.block.yml, gr-digital/include/gnuradio/digital/corr_est_cc.h
=> digital: Move enum tm_type from digital.core_est_cc to digital

gnuradio-runtime/python/gnuradio/ctrlport/GNURadioControlPortClient.py, gnuradio-runtime/python/gnuradio/ctrlport/GrDataPlotter.py, gnuradio-runtime/python/gnuradio/ctrlport/RPCConnectionThrift.py, gnuradio-runtime/python/gnuradio/ctrlport/gr-ctrlport-monitor, gnuradio-runtime/python/gnuradio/ctrlport/gr-perf-monitorx, gnuradio-runtime/python/gnuradio/ctrlport/monitor.py, gr-blocks/grc/blocks_ctrlport_performance.block.yml, gr-blocks/grc/blocks_ctrlport_viewer.block.yml, grc/blocks/options.block.yml, grc/core/generator/flow_graph.py.mako, grc/gui/Application.py
I guess this requires much more testing. Would appreciate if someone could give it a try.
=> runtime: port ctrlport monitor to 3.8 and qt5

grc/gui/Application.py
Fixes the bug mentioned in https://github.com/gnuradio/gnuradio/issues/2551
=> grc: Unselect all on Ctrl+F

grc/gui/ActionHandler.py
Fixed the bug mentioned in https://github.com/gnuradio/gnuradio/issues/2551
=> grc: Unselect all on Ctrl+F (3.7)

gr-utils/python/modtool/templates/templates.py
=> modtool: remove quotes for python hier block template

grc/core/FlowGraph.py, grc/gui/VariableEditor.py
Together with #2605 this fixes #2494 and KeyErrors in other variable blocks
=> KeyError patch for variable blocks 

grc/converter/xml.py, grc/core/platform.py
Fixes https://github.com/gnuradio/gnuradio/issues/2472
=> grc: Fix XML loading without lxml

CHANGELOG.md, CMakeLists.txt
This depends on the VOLK version increase being done first.
=> Release 3.8.0.0

gr-filter/python/filter/design/filter_design.py
Numpy changed their implementation detail of fft from fftpack to pocketfft in version 1.17. Therefor we should to try to import both details.
Additionally numpy as imported twice. Once as numpy and once as np. Both versions were used in the code. I removed the numpy import and left the import as np.
=> Patch gr filter design

gr-analog/grc/analog_am_demod_cf.xml
Minimal AM passband parameter check for 3.7 #2493
=> Analog AM Demod passband paramter check for 3.7

gr-qtgui/examples/c++/display_qt.cc
simple & quick fix noted here: https://github.com/gnuradio/gnuradio/commit/f7bbf2c1d8d780294f3e016aff239ca35eb6516e#commitcomment-35705995
=> qtgui: fix 2 comment typos

gnuradio-runtime/lib/block_executor.cc, gr-fec/lib/decoder_impl.cc, gr-fec/lib/depuncture_bb_impl.cc, gr-fec/lib/encoder_impl.cc, gr-fec/lib/puncture_bb_impl.cc, gr-fec/lib/puncture_ff_impl.cc
=> Change rounding method to `std::lround`

gnuradio-runtime/include/gnuradio/random.h
This patch replaces a documentation FIXME with a description of what impulse() does.
=> Documentation for the random number generator

README.md
revise install instructions to add detail and add links to Wiki and PyBOMBS
=> revise install instructions

gr-digital/lib/map_bb_impl.cc, gr-digital/lib/map_bb_impl.h
This also breaks out 0x100 to have one source of truth.
=> digital/map_bb: Fix buffer overflow

CMakeLists.txt, README.md, cmake/Modules/FindLOG4CPP.cmake, cmake/Modules/GnuradioConfig.cmake.in, cmake/Modules/GrBoost.cmake, gnuradio-runtime/include/gnuradio/random.h, gr-analog/grc/analog_agc2_xx.block.yml, gr-analog/grc/analog_agc3_xx.block.yml, gr-analog/grc/analog_agc_xx.block.yml, gr-analog/grc/analog_const_source_x.block.yml, gr-analog/grc/analog_frequency_modulator_fc.block.yml, gr-analog/grc/analog_wfm_tx.block.yml, gr-uhd/grc/gen_uhd_usrp_blocks.py, gr-utils/python/modtool/templates/templates.py, grc/core/blocks/embedded_python.py, grc/core/utils/extract_docs.py
=> More backport 3.8

gr-utils/python/modtool/cli/add.py, gr-utils/python/modtool/core/add.py
The validation of the arguments list and copyright holder should be updated to take care of the potential whitespaces. 
The check on the arguments list is currently incorrect.
=> gr-modtool: Update the validation in Modtool Add

gr-qtgui/lib/constellationdisplayform.cc, gr-qtgui/lib/freqdisplayform.cc, gr-qtgui/lib/histogramdisplayform.cc, gr-qtgui/lib/numberdisplayform.cc, gr-qtgui/lib/timerasterdisplayform.cc, gr-qtgui/lib/vectordisplayform.cc, gr-qtgui/lib/waterfalldisplayform.cc, gr-qtgui/python/qtgui/range.py.cmakein
These are the patches from #2952, from @Phil67ago. 
Fixes: https://github.com/gnuradio/gnuradio/issues/2952
=> QT: Add margin around QT widgets

docs/volk-signing-keys/README.md, docs/volk-signing-keys/volk-signing-001.pub
This is to verify VOLK releases with a known key.
=> volk: Add VOLK signify public key

gnuradio-runtime/include/gnuradio/thread/thread_body_wrapper.h, gnuradio-runtime/include/gnuradio/top_block.h, gnuradio-runtime/lib/scheduler.cc, gnuradio-runtime/lib/scheduler.h, gnuradio-runtime/lib/scheduler_tpb.cc, gnuradio-runtime/lib/scheduler_tpb.h, gnuradio-runtime/lib/top_block.cc, gnuradio-runtime/lib/top_block_impl.cc, gnuradio-runtime/lib/top_block_impl.h, gnuradio-runtime/python/gnuradio/gr/qa_uncaught_exception.py, gnuradio-runtime/python/gnuradio/gr/top_block.py, gnuradio-runtime/swig/top_block.i, grc/blocks/options.block.yml, grc/core/generator/flow_graph.py.mako, grc/core/generator/top_block.py
This required a bit of rebasing and reformating.
closes #1893
=> Merge pwick86's remove-catch thread handler PR #1893

dtools/bin/roll-tarball.sh
This eradicates the human source of error, typing in the version number
to use.
Also, abandoned `git worktree`. It's simply broken if you have
submodules.
=> roll-tarball.sh: Extract version string from CMakeLists.txt

gr-uhd/grc/gen_uhd_usrp_blocks.py
- Adds set_auto_dc_offset and set_auto_iq_balance calls to GRC bindings
Supersedes https://github.com/gnuradio/gnuradio/pull/2595, fixes an issue therein.
Closes #2595
=> uhd: Add missing function calls and rearrange USRP YAML

grc/gui/Constants.py, grc/gui/ParamWidgets.py, grc/gui/canvas/colors.py
~~I haven't even run this yet.~~
Tested and works:
=> GRC: Fix color for input boxes in parameter widget for dark themes

grc/CMakeLists.txt, grc/tests/.gitignore, grc/tests/CMakeLists.txt, grc/tests/test_compiler.py, grc/tests/test_cpp.py, grc/tests/test_expr_utils.py, grc/tests/test_generator.py
- Mark failing tests with xfail
- Fix test_extend
Closes: #2680
=> grc: Include GRC tests in CTest testing 

gr-utils/python/modtool/cli/add.py
This cherry-picks #3059 onto master.
@mbr0wn
=> modtool: ensure add_py_qa and add_cc_qa are booleans

gr-uhd/grc/gen_uhd_usrp_blocks.py
Fixes https://github.com/gnuradio/gnuradio/issues/3039
I believe I messed up the first attempt because the AGC calls don't exist in 3.7.
Someone with access to a USRP should probably test this more thoroughly to make sure it's right this time :)
=> uhd: Move AGC-related calls to fix TypeError

gr-wavelet/lib/wavelet_ff_impl.cc
=> wavelet: check for correct malloc pointer

gr-digital/lib/additive_scrambler_bb_impl.cc, gr-digital/python/digital/qa_scrambler.py
See bug report #2926 and pull request #2999.
=> Backport fix for #2926 to maint-3.7

docs/doxygen/other/releasing.dox, gr-channels/include/gnuradio/channels/selective_fading_model2.h
This will fix doxygen warnings
=> Doxygen: fix deprecation warnings, etc

gr-fft/lib/fft_vcc_fftw.cc
=> gr-fft: always true check

gr-qtgui/lib/HistogramDisplayPlot.cc
=> gr-qtgui: always true check

gr-digital/lib/correlate_access_code_bb_impl.cc, gr-digital/lib/interpolating_resampler.cc
Ready for comments, as maybe it is a mistake somehow (the first commit)
=> gr-digital: the variable is being rewritten

gr-dtv/lib/dvbt/dvbt_reference_signals_impl.cc
=> gr-dtv: add missing std::nothrow

gr-digital/lib/ofdm_cyclic_prefixer_impl.cc
A variable is used several times between two sequence points
=> gr-digital: fix undefined behaviour

gr-fft/grc/fft_logpwrfft_x.block.yml
Fixes: https://github.com/gnuradio/gnuradio/issues/3129
=> fft: fixup Log Power yml

gr-uhd/include/gnuradio/uhd/usrp_block.h, gr-uhd/lib/usrp_block_impl.cc, gr-uhd/lib/usrp_block_impl.h, gr-uhd/swig/uhd_swig.i
This is a rebased version of https://github.com/gnuradio/gnuradio/pull/2200.
=> gr-uhd: Add filter API functions to the USRP blocks

gr-uhd/include/gnuradio/uhd/usrp_block.h, gr-uhd/lib/usrp_block_impl.cc, gr-uhd/lib/usrp_block_impl.h, gr-uhd/swig/uhd_swig.i
=> backport 3.8 3052: gr-uhd: Add filter API functions to the USRP blocks

gr-qtgui/include/gnuradio/qtgui/waterfall_sink_c.h
=> Harmonize QT Waterfall Sink argument name with freq_sink_c

grc/gui/Application.py, grc/gui/MainWindow.py
New pages save using file menu or ctrl+s
fixes #3147
=> ctrl+s save works on new pages

gr-dtv/examples/dvbt_tx_2k.grc, gr-dtv/examples/dvbt_tx_8k.grc, gr-dtv/lib/dvbt/dvbt_reference_signals_impl.cc, gr-dtv/lib/dvbt/dvbt_reference_signals_impl.h
Move IFFT and normalization to Reference Signals block.
=> gr-dtv: Optimize DVB-T transmitter by consolidating blocks.

gr-filter/grc/filter_rational_resampler_xxx.block.yml
Fixes #3160 
I have added documentation for the rational resampler block.
=> Added documentation for rational resampler

gr-digital/lib/map_bb_impl.cc, gr-digital/lib/map_bb_impl.h, gr-fec/include/gnuradio/fec/cc_encoder.h, gr-fec/lib/cc_encoder_impl.cc
Backports of the following pull-requests to maint-3.7
* #3103 (fix-up for formatting included)
* #2969
=> Backports 3.7

gr-blocks/lib/file_meta_sink_impl.cc
fix bug file_meta_sink size check.
https://github.com/gnuradio/gnuradio/issues/3222
fixes #3222
=> fix bug file_meta_sink

gr-zeromq/grc/zeromq_pub_sink.block.yml, gr-zeromq/grc/zeromq_sub_source.block.yml, gr-zeromq/include/gnuradio/zeromq/pub_sink.h, gr-zeromq/include/gnuradio/zeromq/sub_source.h, gr-zeromq/lib/base_impl.cc, gr-zeromq/lib/base_impl.h, gr-zeromq/lib/pub_sink_impl.cc, gr-zeromq/lib/pub_sink_impl.h, gr-zeromq/lib/sub_source_impl.cc, gr-zeromq/lib/sub_source_impl.h, gr-zeromq/python/zeromq/qa_zeromq_pubsub.py, gr-zeromq/python/zeromq/qa_zeromq_sub.py
=> Key filter zmq (v2)

gnuradio-runtime/lib/top_block_impl.cc, gr-blocks/lib/qa_gr_top_block.cc
Fixes #3185.
I've been running with this patch for the past week and haven't observed any problems.
=> backport #3184 to 3.8

grc/CMakeLists.txt
=> grc: remove python check

docs/usage-manual/(exported from wiki) Block Thread Affinity and Priority.txt, docs/usage-manual/(exported from wiki) Configuration Files.txt, docs/usage-manual/(exported from wiki) GNURadioCompanion.txt, docs/usage-manual/(exported from wiki) Handling Flowgraphs.txt, docs/usage-manual/(exported from wiki) Logging.txt, docs/usage-manual/(exported from wiki) Message Passing.txt, docs/usage-manual/(exported from wiki) Metadata Information.txt, docs/usage-manual/(exported from wiki) Performance Counters.txt, docs/usage-manual/(exported from wiki) Polymorphic Types (PMTs).txt, docs/usage-manual/(exported from wiki) Polyphase Filterbanks.txt, docs/usage-manual/(exported from wiki) Stream Tags.txt, docs/usage-manual/(exported from wiki) Tagged Stream Blocks.txt, docs/usage-manual/(exported from wiki) Types of Blocks.txt, docs/usage-manual/(exported from wiki) VOLK Guide.txt
(these changes were automatically generated using the export script)
=> docs: updated usage manual export from wiki

gr-filter/python/filter/design/filter_design.py, gr-filter/python/filter/gui/pyqt_filter_stacked.py
- Changed numpy fftpack to fft for filter tool
- Changed scipy.arange to numpy.arange for filter design
- Changed poly1d import from scipy to numpy
- Removed scipy label from IIR filter design
This is https://github.com/gnuradio/gnuradio/pull/3259 by @wbarnha, except for master.
=> filter: Improve use of numpy and scipy in filter design tool

gr-blocks/examples/CMakeLists.txt, gr-blocks/examples/py_snippets_demo.grc, grc/blocks/grc.tree.yml, grc/blocks/snippet.block.yml, grc/core/FlowGraph.py, grc/core/base.py, grc/core/blocks/block.py, grc/core/generator/flow_graph.py.mako, grc/core/generator/top_block.py, grc/core/params/param.py
3.8 backport of the python snippets
https://github.com/gnuradio/gnuradio/pull/3169
=> grc: add python snippets to GRC - 3.8 backport

gnuradio-runtime/include/gnuradio/block_gateway.h
Backport of @mrjacobagilbert PR on master
=> runtime: add calls to python blocks to set affinity and get/set alias

gr-qtgui/python/qtgui/__init__.py, gr-qtgui/python/qtgui/distanceradar.py
refrences https://github.com/gnuradio/gnuradio/issues/3281
=> #3281 qtgui: matplotlib dependency

gnuradio-runtime/lib/pmt/pmt_unv.cc, gr-qtgui/include/gnuradio/qtgui/edit_box_msg.h, gr-qtgui/lib/edit_box_msg_impl.cc
Not quite ready for merging. I need to do proper testing with the UI etc.
Feel free to do it too.
=> remove boost::lexical_cast

gr-qtgui/python/qtgui/__init__.py
Fixes typo in azeplot in init.py under gr-qtgui
=> Fixed typo in azeplot in gr_qtgui

gr-blocks/lib/file_sink_impl.cc, gr-blocks/lib/file_sink_impl.h
Backport of PR #3357 for maint-3.8.
=> file_sink: Flush file on stop() (backport for maint-3.8)

gr-blocks/lib/file_sink_impl.cc, gr-blocks/lib/file_sink_impl.h
Backport of PR #3357 for maint-3.7.
=> file_sink: Flush file on stop() (backport for maint-3.7)

gr-blocks/grc/blocks_wavfile_sink.block.yml, gr-blocks/lib/wavfile_sink_impl.cc
I forgot a couple of changes in #3297.
=> blocks: wav: add missing changes

gr-blocks/examples/matrix_multiplexer.grc, gr-digital/examples/demod/constellation_soft_decoder.grc, gr-digital/examples/demod/symbol_sync_test_complex.grc, gr-digital/examples/demod/symbol_sync_test_float.grc, gr-qtgui/grc/qtgui_chooser.block.yml, gr-uhd/examples/grc/uhd_fft.grc, gr-uhd/examples/grc/uhd_msg_tune.grc, gr-uhd/examples/grc/uhd_siggen_gui.grc
This is a backport of #2778 and a cleanup of the affected flowgraphs
=> qtgui: Backport qtgui chooser default and related examples

gr-filter/grc/variable_band_pass_filter_taps.block.yml
Backport of PR #3392 for maint-3.8.
Signed-off-by: Ilya Tagunov <tagunil@gmail.com>
=> filter: grc: variable_band_pass_filter_taps: fix complex taps option (Backport for maint-3.8)

gnuradio-runtime/lib/pmt/pmt_serialize.cc
this preserves the behavior in a more portable way since endian.h has a variety of portability issues
Addresses #3366 and #3401 and is related to #3320, the backport has been edited to reflect boost::endian #3342
=> pmt: serialization change from htobeXX() to boost::endian

gr-qtgui/grc/qtgui_sink_x.block.yml
Hi @mormj just ran into this trying a dummy flowgraph on the pybind branch, just looks like a typo to me.
=> qtgui: Fix misplaced comma

gr-fft/grc/fft_logpwrfft_x.block.yml
Backport of PR #3130 to maint-3.8 to fix #3438
=> gr-fft: fixup Log Power yml (Backport - 3.8)

gr-trellis/include/gnuradio/trellis/encoder.h, gr-trellis/lib/encoder_impl.cc, gr-trellis/python/trellis/bindings/encoder_python.cc, gr-trellis/python/trellis/bindings/viterbi_python.cc, gr-trellis/python/trellis/qa_trellis.py
also, fix failing qa test
Fixes #3448
=> trellis: update templated python bindings

gr-blocks/lib/tuntap_pdu_impl.cc
References #3349 
Trivial fix for strncpy.
=> gr-blocks: Fixed strncpy warning in tuntap_pdu_impl.cc

gr-qtgui/python/qtgui/digitalnumbercontrol.py
Clicking on the upper or lower parts of numbers is supposed to
change the frequency when not in read-only mode.  A bug in
mousePressEvent was preventing the updates from being detected.
=> Fixed UI Issue Where Mouse Clicks Did Not Change Frequency

gr-qtgui/grc/qtgui_range.block.yml, gr-qtgui/python/qtgui/range.py.cmakein
=> qtgui: add vertical slider support

grc/core/blocks/block.py
backport for #3317 which fixes a bug in assert handling
=> grc: import block namespaces

gr-qtgui/docs/qtgui.dox, gr-qtgui/examples/qtgui_eye_sink_example.grc, gr-qtgui/grc/qtgui.tree.yml, gr-qtgui/grc/qtgui_eye_sink_x.block.yml, gr-qtgui/include/gnuradio/qtgui/CMakeLists.txt, gr-qtgui/include/gnuradio/qtgui/EyeDisplayPlot.h, gr-qtgui/include/gnuradio/qtgui/eye_sink_c.h, gr-qtgui/include/gnuradio/qtgui/eye_sink_f.h, gr-qtgui/include/gnuradio/qtgui/eyecontrolpanel.h, gr-qtgui/include/gnuradio/qtgui/eyedisplayform.h, gr-qtgui/include/gnuradio/qtgui/eyedisplaysform.h, gr-qtgui/lib/CMakeLists.txt, gr-qtgui/lib/EyeDisplayPlot.cc, gr-qtgui/lib/eye_sink_c_impl.cc, gr-qtgui/lib/eye_sink_c_impl.h, gr-qtgui/lib/eye_sink_f_impl.cc, gr-qtgui/lib/eye_sink_f_impl.h, gr-qtgui/lib/eyecontrolpanel.cc, gr-qtgui/lib/eyedisplayform.cc, gr-qtgui/lib/eyedisplaysform.cc, gr-qtgui/python/qtgui/qa_qtgui.py, gr-qtgui/swig/qtgui_swig.i
Fourth attempt to get a clean PR.
=> qtgui: Add eye sink widget

gr-uhd/grc/uhd_amsg_source.block.yml
Fixes #3491.  Hasn't been fully tested but it seems to fix the error msg when running the flowgraph.
=> uhd: fixed async usrp source grc file

grc/core/generator/flow_graph.py.mako
Fixes #3141 
Added:
~~~~
from __future__ import print_function
=> grc: Updated flow_graph.py.mako with import statement (maint-3.8)

grc/gui/canvas/flowgraph.py
previously the first hit terminated further processing
=> grc: iterate all selected blocks when changing port type (fixes #3500)

grc/gui/canvas/flowgraph.py
This is a bit more than a pure fix for #3499, but I couldn't help myself...
- also adds collision detection for pasted blocks.
- selected elements are drawn last (on top)
=> grc: some fixes and refactoring of paste

gr-digital/python/digital/soft_dec_lut_gen.py
Backport of PR #3351 for maint-3.8.
=> gr-digital/python : Updated soft_dec_lut_gen.py(Backport for maint-3.8)

gr-digital/examples/mpsk_stage6.grc, gr-qtgui/examples/Bercurve_Sink.txt, gr-qtgui/examples/Number_Sink.grc, gr-qtgui/examples/gui_sink.grc, gr-qtgui/examples/test_qtgui_msg.grc
resolves https://github.com/gnuradio/gnuradio/issues/1971
resolves https://github.com/gnuradio/gnuradio/issues/3411
=> add and revise flowgraphs for qt_gui examples

CHANGELOG.md, gr-analog/examples/sig_source_msg_ports.grc, gr-analog/grc/analog_sig_source_x.block.yml, gr-analog/lib/sig_source_impl.cc, gr-analog/lib/sig_source_impl.h, gr-analog/python/analog/qa_sig_source.py
also:
extend message functionality to include setting of phase, amplitude and offset.
Adds an example flowgraph.
Supersedes #3582
=> signal source: accept commands on cmd port, work with dicts

gr-fec/examples/fecapi_async_ldpc_encoders.grc, gr-fec/examples/fecapi_tagged_decoders.grc, gr-fec/examples/tpc_ber_curve_gen.grc, gr-network/examples/test_tcp_source_client.grc
In fec and network there were a few example files that had various issues
=> examples: fix a few that would not compile with grcc

gr-digital/examples/mpsk_stage6.grc
Corrected QPSK flowgraph.
Resolves https://github.com/gnuradio/gnuradio/issues/3599
=> correct example flowgraph

gr-analog/examples/USRP_FM_stereo.grc, gr-analog/python/analog/wfm_rcv_pll.py
resolves https://github.com/gnuradio/gnuradio/issues/3593
=> correct fm stereo heir block, add example grc

gr-analog/python/analog/nbfm_tx.py
resolves https://github.com/gnuradio/gnuradio/issues/3651
=> cast integer divide to type int

CHANGELOG.md, gr-analog/examples/sig_source_msg_ports.grc, gr-analog/grc/analog_sig_source_x.block.yml, gr-analog/lib/sig_source_impl.cc, gr-analog/lib/sig_source_impl.h, gr-analog/python/analog/qa_sig_source.py
Backport of #3588 for signal source block.
=>  analog: signal source block accepts cmd messages (Backport 3.8)

cmake/Modules/GrPython.cmake
=> cmake: Add -undefined dynamic_lookup linker flag back for macOS

gr-qtgui/grc/qtgui_const_sink_x.block.yml, gr-qtgui/grc/qtgui_freq_sink_x.block.yml, gr-qtgui/grc/qtgui_histogram_sink_x.block.yml, gr-qtgui/grc/qtgui_time_raster_x.block.yml, gr-qtgui/grc/qtgui_time_sink_x.block.yml, gr-qtgui/grc/qtgui_time_sink_x.block.yml.py, gr-qtgui/grc/qtgui_waterfall_sink_x.block.yml
=> qtgui: remove optional flag on stream ports

gr-uhd/apps/uhd_app.py, gr-uhd/apps/uhd_siggen, gr-uhd/apps/uhd_siggen_base.py, gr-uhd/apps/uhd_siggen_gui
- Fix formatting
- Fix PyLint complaints
No functional changes.
=> uhd: Clean up Python code for uhd_siggen_* and uhd_app

gr-fec/include/gnuradio/fec/polar_common.h, gr-fec/include/gnuradio/fec/polar_decoder_sc_list.h, gr-fec/lib/async_decoder_impl.cc, gr-fec/lib/async_decoder_impl.h, gr-fec/lib/async_encoder_impl.cc, gr-fec/lib/async_encoder_impl.h, gr-fec/lib/cc_decoder_impl.cc, gr-fec/lib/cc_decoder_impl.h, gr-fec/lib/polar_common.cc, gr-fec/lib/polar_decoder_sc_list.cc, gr-fec/python/fec/bindings/polar_common_python.cc, gr-fec/python/fec/bindings/polar_decoder_sc_list_python.cc
Well, not all of it.
`sc_list` is a bit hairy. I'm leaving it for now.
And there's some `volk_malloc` left. I'm mostly hunting `new`/`delete` now.
=> fec: Remove manual memory management

grc/gui/Application.py
=> grc: do not run stale flowgraph

gr-qtgui/include/gnuradio/qtgui/freqcontrolpanel.h, gr-qtgui/lib/freqcontrolpanel.cc
Well screw me sideways. Didn't check all use cases :cry:
=> fixup! qtgui: Replace firdes::window with fft::window

gr-uhd/apps/uhd_fft
This in preparation for future modifications of uhd_fft (and easier
review thereof). This is mostly:
- Whitespace cleanup
- Removal of dead code
- Breaking of long lines
PyLint is much happier and can provide more useful warnings. No
functional changes.
=> uhd: uhd_fft: Clean up Python, fix PyLint warnings

cmake/Modules/GnuradioConfig.cmake.in, gr-network/lib/CMakeLists.txt, gr-network/lib/gnuradio-network.rc.in
* Add missing Windows resource file
* Include in component list in GnuradioConfig.cmake
=> network: build fixes

grc/gui/ParamWidgets.py
subject says it all. Here's the original PR commit and my comments from debugging this issue.
=> grc: try-except around "gsettings" for when those settings do not exist

gr-blocks/lib/selector_impl.cc
Aligns the output tags using nitems_written as recommended by @rear1019 in #3572 to address the situation where tags on the input are not aligned with the output due to dropped samples
@mrjacobagilbert @rear1019 - please take a look, I believe this can supercede #3572 with less bookkeeping
Fixes #3569
=> blocks: align output tags in selector block

gr-audio/lib/alsa/alsa_impl.h, gr-audio/lib/alsa/alsa_sink.cc, gr-audio/lib/alsa/alsa_sink.h, gr-audio/lib/alsa/alsa_source.cc, gr-audio/lib/alsa/alsa_source.h
Warning: There are no unit tests. It seems to still work well for me though.
=> audio/alsa: Remove manual memory management

grc/converter/main.py, grc/core/blocks/_flags.py, grc/core/blocks/block.py, grc/core/cache.py, grc/core/generator/FlowGraphProxy.py, grc/core/generator/cpp_hier_block.py, grc/core/generator/hier_block.py, grc/core/io/yaml.py, grc/core/params/dtypes.py, grc/core/params/param.py, grc/core/platform.py, grc/core/schema_checker/block.py, grc/core/schema_checker/domain.py, grc/core/schema_checker/flow_graph.py, grc/core/schema_checker/utils.py, grc/core/schema_checker/validator.py, grc/core/utils/__init__.py, grc/core/utils/descriptors/evaluated.py, grc/core/utils/epy_block_io.py, grc/core/utils/expr_utils.py, grc/core/utils/extract_docs.py, grc/gui/Actions.py, grc/gui/BlockTreeWindow.py, grc/gui/Config.py, grc/gui/ParserErrorsDialog.py, grc/gui/PropsDialog.py, grc/gui/Utils.py, grc/gui/canvas/block.py, grc/gui/canvas/drawable.py, grc/gui/canvas/flowgraph.py
Partially resolves #3446.
#3467 seems to have stalled and now has merge conflicts, so I thought I'd take a crack at removing six myself beginning with GRC. So far GRC appears to be working normally after these changes.
=> grc: remove six

gr-utils/python/modtool/cli/add.py
Backport of PR #3340 for maint-3.8.
=> modtool: Added feature to prevent creation of multiple blocks with same name (Backport for maint-3.8)

gnuradio-runtime/lib/vmcircbuf_createfilemapping.cc, gr-audio/lib/windows/windows_sink.cc, gr-audio/lib/windows/windows_source.cc
PR #3339 introduced some compilation errors in Windows. This should fix them.
/cc @marcusmueller
=> Fix Windows logging

gr-filter/grc/filter_band_reject_filter.block.yml, gr-filter/grc/variable_band_reject_filter_taps.block.yml, gr-filter/include/gnuradio/filter/firdes.h, gr-filter/lib/firdes.cc, gr-filter/python/filter/bindings/docstrings/firdes_pydoc_template.h, gr-filter/python/filter/bindings/firdes_python.cc, gr-filter/python/filter/optfir.py
Adds three new helper functions that allow for easier creation of complex band rejection filters.
=> gr-filter: Add complex band rejection filter design helpers

gnuradio-runtime/apps/gnuradio-config-info.cc
Backport of https://github.com/gnuradio/gnuradio/pull/3885
=> utils: Added print-all to gnuradio-config-info

gr-analog/python/analog/wfm_rcv.py, gr-analog/python/analog/wfm_rcv_fmdet.py, gr-analog/python/analog/wfm_rcv_pll.py, gr-analog/python/analog/wfm_tx.py
=> analog: WFM tools: proper integer div, decimation handling

grc/gui/PropsDialog.py
For https://github.com/gnuradio/gnuradio/issues/3931
=> grc: add wiki link to properties dialog docs

gr-qtgui/include/gnuradio/qtgui/displayform.h, gr-qtgui/lib/displayform.cc, gr-qtgui/lib/spectrumdisplayform.cc, gr-qtgui/lib/spectrumdisplayform.ui
There a some problems in resizing the windows.
Fixes #3865
=> Resize the windows properly

gr-audio/lib/alsa/alsa_sink.cc, gr-audio/lib/alsa/alsa_source.cc, gr-audio/lib/alsa/gr-audio-alsa.conf
raise nperiods to 32
resolves https://github.com/gnuradio/gnuradio/issues/3798
=> audio: raise nperiods for alsa source/sink

gr-digital/include/gnuradio/digital/mpsk_snr_est_cc.h, gr-digital/include/gnuradio/digital/probe_mpsk_snr_est_c.h, gr-digital/python/digital/bindings/mpsk_snr_est_cc_python.cc, gr-digital/python/digital/bindings/probe_mpsk_snr_est_c_python.cc
I'm submitting my question about what this means and how it should be used as a documentation change. I don't know if this is correct, so the main thing to review here is if what I added is correct or not.
=> gr-digital: Update docs for MPSK SNR Estimator

gr-digital/python/digital/soft_dec_lut_gen.py
Backport of PR #3351 for maint-3.7.
=> gr-digital/python : Updated soft_dec_lut_gen.py(Backport for maint-3.7)

docs/usage-manual/(exported from wiki) QT GUI.txt, gr-filter/examples/gr_filtdes_callback.py, gr-filter/examples/gr_filtdes_live_upd.py, gr-filter/examples/gr_filtdes_restrict.py, gr-qtgui/apps/uhd_display.py, gr-qtgui/apps/usrp_display_qtgui.py, gr-qtgui/docs/qtgui.dox, gr-qtgui/examples/pyqt_waterfall_c.py, gr-qtgui/python/qtgui/range.py.cmakein, gr-utils/python/utils/gr_plot_qt, gr-utils/python/utils/pyqt_filter.py, gr-utils/python/utils/pyqt_plot.py, gr-zeromq/examples/python/fixui4py.sh, gr-zeromq/examples/python/gui.py, gr-zeromq/examples/python/main_window.ui, grc/tests/resources/file3.block.yml
Fixes: qtgui: uhd_display and usrp_display_qtgui PyQt4 dependencies #2512
This is one of my patches for Debian packaging of the maint-3.8 branch.
=> more qt4 qt5 updates

gr-qtgui/lib/FrequencyDisplayPlot.cc
=> gr-qtgui: Fix Frequency Sink max hold for half spectrum width option.

.clang-tidy, gnuradio-runtime/include/pmt/pmt.h, gnuradio-runtime/lib/block_executor.cc, gnuradio-runtime/lib/hier_block2.cc, gnuradio-runtime/lib/logger.cc, gnuradio-runtime/lib/thread/thread_group.cc, gnuradio-runtime/lib/top_block.cc, gr-analog/lib/ctcss_squelch_ff_impl.cc, gr-blocks/lib/tcp_server_sink_impl.cc, gr-blocks/lib/udp_sink_impl.cc, gr-blocks/lib/udp_source_impl.cc, gr-digital/lib/decision_feedback_equalizer_impl.cc, gr-digital/lib/fll_band_edge_cc_impl.cc, gr-digital/lib/interpolating_resampler.cc, gr-digital/lib/linear_equalizer_impl.cc, gr-digital/lib/mpsk_snr_est_cc_impl.cc, gr-digital/lib/probe_mpsk_snr_est_c_impl.cc, gr-digital/lib/timing_error_detector.cc, gr-fec/lib/polar_decoder_sc_list.cc, gr-filter/lib/dc_blocker_cc_impl.cc, gr-filter/lib/dc_blocker_ff_impl.cc, gr-filter/lib/fft_filter.cc, gr-zeromq/lib/pull_msg_source_impl.cc, gr-zeromq/lib/rep_msg_sink_impl.cc, gr-zeromq/lib/req_msg_source_impl.cc, gr-zeromq/lib/sub_msg_source_impl.cc
=> C++14: Use std::make_unique instead of boost::make_unique

gr-uhd/python/uhd/qa_uhd.py
The qa_uhd.py test has been broken for a long time. Now fixed.
=> uhd: Fix unit test

gr-digital/grc/digital_constellation.block.yml, gr-digital/python/digital/bindings/constellation_python.cc, gr-filter/lib/rational_resampler_impl.cc, gr-qtgui/grc/qtgui_number_sink.block.yml, gr-qtgui/lib/number_sink_impl.cc
digital: fix bindings and yaml for constellation
gr-qtgui number sink: Honor block setting of 'avg' in GUI
filter: update decimation after gcd calculation
=> Backport recent commits from master to 3.9

gr-blocks/lib/peak_detector2_fb_impl.cc, gr-blocks/lib/peak_detector2_fb_impl.h, gr-blocks/python/blocks/qa_peak_detector2.py
=> peak_detector2: Fix wrong average in an a edge case

grc/core/generator/flow_graph.py.mako
=> Qt shutdown - Backport to 3.9

gr-digital/examples/packet/example_corr_est.grc
"backport" of https://github.com/gnuradio/gnuradio/pull/4060 to master
In this case @mbr0wn already did cherry-pick the latest commit of that pull request on master, but he probably missed that two commits were included in that PR. This very PR adds the other commit.
=> gr-digital: Fixup example_corr_est

.github/workflows/make-test.yml
=> Add GitHub Actions workflow for 3.8

grc/gui/canvas/flowgraph.py
Fixes https://github.com/gnuradio/gnuradio/issues/4075
=> grc: Don't draw disabled and hidden blocks, even if they are selected

gr-blocks/lib/add_blk_impl.cc
Compare recent changes in the moving_average block with those templatized
`volk_add` functions instead of whole work functions being templatized.
It should now be easier to add further templates for other block types.
A volkized version for gr_complex was added.
=> blocks: Use templates more efficiently in add_blk

CMakeLists.txt, gnuradio-runtime/lib/CMakeLists.txt
=> cmake: Fixup BUILD_DATE commit.

gr-uhd/grc/gen_uhd_usrp_blocks.py
=> uhd: Add start time capability to GRC bindings

gr-blocks/lib/file_source_impl.cc
Based on original PR https://github.com/gnuradio/gnuradio/pull/3649 by esqt.
=> File Source: handle EOF for non-seekable files

gr-fft/python/fft/logpwrfft.py
Block would fail as soon as it was placed in GRC.
A couple of imports/renames were needed.
=> gr-fft: Log Power FFT Python fix

gr-digital/examples/packet/example_corr_est.grc
"backport" of https://github.com/gnuradio/gnuradio/pull/4060 to maint-3.9
=> gr-digital: Fixup example_corr_est 

gr-analog/grc/analog_wfm_rcv_pll.block.yml, gr-analog/python/analog/wfm_rcv_pll.py
=>   gr-analog: Fixed orientation of L and R audio in wfm_rcv_pll. Changed gain of multiply_const_ff blocks from 5.5 to 1.0

gr-uhd/lib/amsg_source_impl.cc, gr-uhd/lib/usrp_block_impl.cc
Supersedes https://github.com/gnuradio/gnuradio/pull/3721
=> msg_handler: Use lambdas in gr-uhd

gr-digital/python/digital/qa_ofdm_chanest_vcvc.py
=> digital: change ofdm_chanest qa test to use head

gr-analog/python/analog/wfm_rcv_pll.py
Fixes: #3921 
There seems to be an additional problem which is the modulation seems off compared to the 3.8 block implementation. If I run a tone through a pair if WBFM tx and rcv_pll it comes out very dirty with weird harmonics. An identical flowgraph in 3.8 doesn't do that. I'll see what I can find out.
=> gr-analog: Fix wfm_rcv_pll arguments

gr-filter/include/gnuradio/filter/fft_filter.h, gr-filter/python/filter/bindings/fft_filter_python.cc, gr-qtgui/lib/TimeRasterDisplayPlot.cc
=> build: Remove clang compiler warnings.

gr-filter/include/gnuradio/filter/filterbank.h, gr-filter/include/gnuradio/filter/polyphase_filterbank.h, gr-filter/python/filter/bindings/filterbank_python.cc, gr-filter/python/filter/bindings/polyphase_filterbank_python.cc
=> filterbanks: Use virtual destructor in superclasses

gnuradio-runtime/include/gnuradio/rpcserver_aggregator.h, gnuradio-runtime/lib/CMakeLists.txt, gnuradio-runtime/python/gnuradio/__init__.py, gr-qtgui/lib/TimeRasterDisplayPlot.cc
Rebased https://github.com/gnuradio/gnuradio/pull/4138
If the tests pass this time, it can go in.
=> MSVC Fixes (Rebased)

gr-qtgui/grc/qtgui_time_raster_x.block.yml, gr-qtgui/include/gnuradio/qtgui/TimeRasterDisplayPlot.h, gr-qtgui/include/gnuradio/qtgui/time_raster_sink_b.h, gr-qtgui/include/gnuradio/qtgui/time_raster_sink_f.h, gr-qtgui/include/gnuradio/qtgui/timerasterdisplayform.h, gr-qtgui/lib/TimeRasterDisplayPlot.cc, gr-qtgui/lib/time_raster_sink_b_impl.cc, gr-qtgui/lib/time_raster_sink_b_impl.h, gr-qtgui/lib/time_raster_sink_f_impl.cc, gr-qtgui/lib/time_raster_sink_f_impl.h, gr-qtgui/lib/timerasterdisplayform.cc, gr-qtgui/python/qtgui/bindings/docstrings/time_raster_sink_b_pydoc_template.h, gr-qtgui/python/qtgui/bindings/docstrings/time_raster_sink_f_pydoc_template.h, gr-qtgui/python/qtgui/bindings/time_raster_sink_b_python.cc, gr-qtgui/python/qtgui/bindings/time_raster_sink_f_python.cc
Backport https://github.com/gnuradio/gnuradio/pull/4092
=> qtgui:Added Time Raster Sink Control Axis Configuration (backport 3.9)

gr-digital/lib/glfsr_source_b_impl.h, gr-digital/lib/glfsr_source_f_impl.h
=> gr-digital: Remove clang compiler override warnings.

gnuradio-runtime/include/gnuradio/messages/msg_accepter_msgq.h, gr-qtgui/lib/TimeRasterDisplayPlot.cc, gr-qtgui/lib/time_raster_sink_b_impl.h, gr-qtgui/lib/time_raster_sink_f_impl.h
=> build: Remove more clang compiler warnings.

cmake/Modules/FindUHD.cmake
=> FindUHD: Fix find_package_handle_standard_args warning

grc/core/generator/cpp_hier_block.py, grc/core/generator/hier_block.py
Fixes https://github.com/gnuradio/gnuradio/issues/2950.
=> grc: Call connect() for hier blocks that don't have ports

gr-blocks/lib/tuntap_pdu_impl.cc
=> gr-blocks: tuntap_pdu: change char array size to fix warning on strncpy

grc/gui/Actions.py
Addresses https://github.com/gnuradio/gnuradio/issues/4202
=> Backport grc defaults

grc/gui/Actions.py
Continuing to backport to fix https://github.com/gnuradio/gnuradio/issues/4202
=> GRC: Actions with preferences now explicitly default to something (3.8 backport)

.github/workflows/make-test.yml
This test was failing, but was fixed. Now re-enabling it in the CI
pipeline.
=> github: ci: Enable qa_uhd test

.github/workflows/make-test.yml
These were fixed and now pass.
=> github: ci: Re-enable qa_uncaught_exception and qa_file_taps_loader

.github/workflows/make-test.yml
=> github: Move Docker builds to matrix strategy

gr-digital/examples/example_timing.py, gr-dtv/examples/atsc_ctrlport_monitor.py, gr-utils/plot_tools/plot_fft_base.py
This branch fix issue #4051 cannot import name 'fftpack' from 'numpy.fft' 
Fixes https://github.com/gnuradio/gnuradio/issues/4051
=> This branch fix fftpack issue

CHANGELOG.md, gr-uhd/docs/uhd.dox, gr-uhd/examples/c++/tag_sink_demo.h, gr-uhd/lib/usrp_sink_impl.cc, gr-uhd/lib/usrp_source_impl.cc, gr-uhd/lib/usrp_source_impl.h
depends on #3339
Remove 'don't merge' as soon as that's merged.
=> Better logging for UHD components.

gr-qtgui/include/gnuradio/qtgui/HistogramDisplayPlot.h, gr-qtgui/lib/HistogramDisplayPlot.cc
Signed-off-by: Thomas Habets <thomas@habets.se>
=> qtgui: Remove manual memory management from HistogramDisplayPlot

gr-qtgui/grc/qtgui_chooser.block.yml
(cherry picked from commit b50314135369220a9f70c2ee9242c75a1c645ddc)
=> qtgui: Qt Chooser: Don't replace labels that aren't blank (Squash) (backport maint-3.9)

.clang-tidy, gnuradio-runtime/include/pmt/pmt.h, gnuradio-runtime/lib/block_executor.cc, gnuradio-runtime/lib/hier_block2.cc, gnuradio-runtime/lib/logger.cc, gnuradio-runtime/lib/thread/thread_group.cc, gnuradio-runtime/lib/top_block.cc, gr-analog/lib/ctcss_squelch_ff_impl.cc, gr-blocks/lib/tcp_server_sink_impl.cc, gr-blocks/lib/udp_sink_impl.cc, gr-blocks/lib/udp_source_impl.cc, gr-digital/lib/decision_feedback_equalizer_impl.cc, gr-digital/lib/fll_band_edge_cc_impl.cc, gr-digital/lib/interpolating_resampler.cc, gr-digital/lib/linear_equalizer_impl.cc, gr-digital/lib/mpsk_snr_est_cc_impl.cc, gr-digital/lib/probe_mpsk_snr_est_c_impl.cc, gr-digital/lib/timing_error_detector.cc, gr-fec/lib/polar_decoder_sc_list.cc, gr-filter/lib/dc_blocker_cc_impl.cc, gr-filter/lib/dc_blocker_ff_impl.cc, gr-filter/lib/fft_filter.cc, gr-zeromq/lib/pull_msg_source_impl.cc, gr-zeromq/lib/rep_msg_sink_impl.cc, gr-zeromq/lib/req_msg_source_impl.cc, gr-zeromq/lib/sub_msg_source_impl.cc
Backport https://github.com/gnuradio/gnuradio/pull/4009
=> C++14: Use std::make_unique instead of boost::make_unique (backport to maint-3.9)

gr-zeromq/lib/pull_msg_source_impl.cc, gr-zeromq/lib/req_msg_source_impl.cc, gr-zeromq/lib/sub_msg_source_impl.cc, gr-zeromq/python/zeromq/qa_zeromq_req_msg_source.py, gr-zeromq/python/zeromq/qa_zeromq_sub_msg_source.py
Backport https://github.com/gnuradio/gnuradio/pull/4229
Backport https://github.com/gnuradio/gnuradio/pull/4231
=> zeromq: qa fixes (backport to maint-3.9)

CHANGELOG.md, gr-uhd/docs/uhd.dox, gr-uhd/examples/c++/tag_sink_demo.h, gr-uhd/examples/c++/tag_source_demo.h, gr-uhd/examples/c++/tags_demo.cc, gr-uhd/include/gnuradio/uhd/usrp_block.h, gr-uhd/lib/amsg_source_impl.cc, gr-uhd/lib/rfnoc_graph_impl.cc, gr-uhd/lib/rfnoc_rx_streamer_impl.cc, gr-uhd/lib/usrp_block_impl.cc, gr-uhd/lib/usrp_block_impl.h, gr-uhd/lib/usrp_sink_impl.cc, gr-uhd/lib/usrp_source_impl.cc, gr-uhd/lib/usrp_source_impl.h
Backport https://github.com/gnuradio/gnuradio/pull/4099
Backport https://github.com/gnuradio/gnuradio/pull/4165
Backport https://github.com/gnuradio/gnuradio/pull/3352
Dependencies rippled a bit. This is API compatible.
=> UHD logging and boost updates (backport to maint-3.9)

gr-uhd/python/uhd/bindings/uhd_types_python.cc
Signed-off-by: Victor Wollesen <victor.w@pervices.com>
(cherry picked from commit 34f658646b84699a96a6296336c49a34f4d9898f)
Backport https://github.com/gnuradio/gnuradio/pull/4293
=> GR-UHD: Add additional gr-uhd bindings (backport to maint-3.9)

gr-dtv/lib/dvb/dvb_ldpc_bb_impl.cc, gr-dtv/lib/dvb/dvb_ldpc_bb_impl.h
=> dtv: Remove manual memory management

gnuradio-runtime/python/gnuradio/gr_unittest.py, gr-digital/python/digital/qa_packet_headerparser_b.py
Backport https://github.com/gnuradio/gnuradio/pull/4275
=> digital: qa: Add preconditions to wait for qa_packet_headerparser_b (backport to maint-3.9)

gr-digital/lib/timing_error_detector.cc, gr-digital/lib/timing_error_detector.h
Signed-off-by: Nick Foster <bistromath@gmail.com>
(cherry picked from commit d4897cec4e011821f82d268617fb0b5ef3c516e5)
Backport https://github.com/gnuradio/gnuradio/pull/4335
=> gr-digital: Fix MSK timing error detector (issue #3678) (backport to maint-3.8)

gr-filter/grc/variable_band_pass_filter_taps.block.yml, gr-filter/grc/variable_band_reject_filter_taps.block.yml, gr-filter/grc/variable_high_pass_filter_taps.block.yml, gr-filter/grc/variable_low_pass_filter_taps.block.yml, gr-filter/grc/variable_rrc_filter_taps.block.yml
(cherry picked from commit b405ca8834d74c0a3dfcacfdb58d198a56da458b)
Backport https://github.com/gnuradio/gnuradio/pull/4329
=> gr_filter : fix variable filter taps blocks (backport to maint-3.8)

gr-digital/lib/timing_error_detector.cc, gr-digital/lib/timing_error_detector.h
Signed-off-by: Nick Foster <bistromath@gmail.com>
(cherry picked from commit d4897cec4e011821f82d268617fb0b5ef3c516e5)
Backport https://github.com/gnuradio/gnuradio/pull/4335
=> gr-digital: Fix MSK timing error detector (issue #3678) (backport to maint-3.9)

gr-filter/grc/variable_band_pass_filter_taps.block.yml, gr-filter/grc/variable_band_reject_filter_taps.block.yml, gr-filter/grc/variable_high_pass_filter_taps.block.yml, gr-filter/grc/variable_low_pass_filter_taps.block.yml, gr-filter/grc/variable_rrc_filter_taps.block.yml
(cherry picked from commit b405ca8834d74c0a3dfcacfdb58d198a56da458b)
Backport https://github.com/gnuradio/gnuradio/pull/4329
=> gr_filter : fix variable filter taps blocks (backport to maint-3.9)

gr-blocks/lib/file_source_impl.cc
Based on original PR by esqt.
(cherry picked from commit 51f72c0cf14c3d9063a741aa3835e04fb977a6a7)
Backported from commit in https://github.com/gnuradio/gnuradio/pull/4142
=> File Source: handle EOF for non-seekable files (backport to maint-3.8)

gnuradio-runtime/include/gnuradio/rpcserver_aggregator.h, gnuradio-runtime/lib/CMakeLists.txt, gr-qtgui/lib/TimeRasterDisplayPlot.cc
Backport https://github.com/gnuradio/gnuradio/pull/4159
The last commit in the PR for master was already backported as part of https://github.com/gnuradio/gnuradio/pull/4187
=> MSVC Fixes (backport to maint-3.9)

cmake/Modules/GnuradioConfig.cmake.in, cmake/Modules/GrBoost.cmake, gnuradio-runtime/include/gnuradio/logger.h, gnuradio-runtime/include/gnuradio/unittests.h, gnuradio-runtime/lib/CMakeLists.txt, gnuradio-runtime/lib/constants.cc.in, gnuradio-runtime/lib/logger.cc, gnuradio-runtime/lib/prefs.cc, gnuradio-runtime/lib/sys_paths.cc, gnuradio-runtime/lib/vmcircbuf_prefs.cc, gnuradio-runtime/python/gnuradio/gr/bindings/logger_python.cc, gr-fec/lib/CMakeLists.txt, gr-fec/lib/ldpc_decoder.cc, gr-fec/lib/ldpc_encoder_impl.cc, gr-fft/lib/CMakeLists.txt, gr-fft/lib/fft.cc
Original Author: @ZackerySpytz - https://github.com/gnuradio/gnuradio/pull/4280
Applied comments from the github conversation
=>  Replace boost::filesystem with std::filesystem (updated)

gr-digital/examples/CMakeLists.txt
=> gr-digital: Install mpsk_stage6.grc example.

gr-audio/lib/audio_registry.cc
@marcusmueller - please flag this if there is a reason this did not initially go onto master.
=> audio: reduce Windows audio priority to LOW, this prefers Portaudio o… (Forward Port 3.9--> Master)

gr-uhd/lib/usrp_sink_impl.cc
The multi_usrp behaviour is deprecated starting in UHD 4.0.
Note: For UHD 3.5.5, we use the old API because the new one did not yet
exist.
This commit also removes some usages of Boost from usrp_sink_impl that
did not have headers to go along with them.
=> uhd: Replace multi_usrp::recv_async_msg() with tx_stream version (3.8 version)

gr-uhd/lib/usrp_sink_impl.cc
The multi_usrp behaviour is deprecated.
=> uhd: Replace multi_usrp::recv_async_msg() with tx_stream version

gr-blocks/lib/correctiq_auto_impl.cc
=> gr-blocks: Fix Remove DC Spike AutoSync block.

gr-utils/modtool/cli/add.py
(cherry picked from commit c317661088fcfee3cd29cdbe99bd729ed874548a)
Backport https://github.com/gnuradio/gnuradio/pull/4401
=> gr_modtool add: Correctly handle arglist (backport to maint-3.9)

gr-utils/python/modtool/cli/add.py
(cherry picked from commit c317661088fcfee3cd29cdbe99bd729ed874548a)
Backport https://github.com/gnuradio/gnuradio/pull/4401
=> gr_modtool add: Correctly handle arglist (backport to maint-3.8)

CHANGELOG.md
=> Changelog for v3.9.1.0

CHANGELOG.md
=> Changelog for v3.8.3.0

CMakeLists.txt
=> Release v3.8.3.0-rc1

CMakeLists.txt
=> Release v3.9.1.0-rc1

gr-uhd/lib/usrp_block_impl.cc
Backporting the is_dict() disambiguation for pairs caused pair type
commands to be rejected as they no longer pass is_dict(). This
restores pair command functionality.
Fixes #4424.
=> gr-uhd: fix UHD command port for pairs

CMakeLists.txt
=> Release v3.8.3.0

CMakeLists.txt
=> Release v3.9.1.0

CMakeLists.txt
=> Change release to -git

CMakeLists.txt
=> Change release to -git.

gnuradio-runtime/include/gnuradio/xoroshiro128p.h, gnuradio-runtime/python/gnuradio/gr/bindings/random_python.cc
Used to include cstdint, which of course is C++
=> Make xoroshiro128p actually conformant C

.packaging/debian/gnuradio.install
Add gr-pdu libraries into debian install
=> pkg: add gr-pdu into debian install

grc/core/Config.py
=> GRC Fix Date String in About dialog

grc/core/Config.py
(cherry picked from commit f070efd62d08649d7628e3905a67c60c38bdca3a)
Backport https://github.com/gnuradio/gnuradio/pull/4451
=> GRC Fix Date String in About dialog (backport to maint-3.8)

CMakeLists.txt, gr-network/lib/CMakeLists.txt
=> Repair gnuradio-config-info for enabled components

gnuradio-runtime/python/gnuradio/gr/tag_utils.py
=> pmt: tag_to_pmt use from_python

gr-filter/python/filter/design/filter_design.py, gr-filter/python/filter/gui/GrFilterPlotWidget.py
File->save fails with key error, if no filter was calculated.
So disable 'save' up to a filter was calculated.
=> gr_filter_design: conditionally enable save

gr-uhd/lib/usrp_block_impl.cc, gr-uhd/lib/usrp_block_impl.h, gr-uhd/lib/usrp_sink_impl.h, gr-uhd/lib/usrp_source_impl.h
Backport of part of #4472 - test flowgraph attached there.
=> gr-uhd: fix command tuning (backport to maint-3.9)

grc/blocks/parameter.block.yml
(cherry picked from commit a9263b4a6a10aa66522a32d8a0deebb2ce205c88)
Backport https://github.com/gnuradio/gnuradio/pull/3935
=> Update parameter background colours realtime (backport to maint-3.8)

gr-filter/python/filter/design/filter_design.py
(cherry picked from commit 85a7326c934c8e94d0fc89b6b221c1f4c5307cdc)
Backport https://github.com/gnuradio/gnuradio/pull/4468
=> Bessel lp/hp filter have only one critical parameter (backport to maint-3.8)

gr-filter/python/filter/design/filter_design.py
(cherry picked from commit 85a7326c934c8e94d0fc89b6b221c1f4c5307cdc)
Backport https://github.com/gnuradio/gnuradio/pull/4468
=> Bessel lp/hp filter have only one critical parameter (backport to maint-3.9)

gr-filter/python/filter/design/filter_design.py, gr-filter/python/filter/gui/GrFilterPlotWidget.py
gr_filter_design: conditionally enable save
Disable save after saving and delete the plots
Backport https://github.com/gnuradio/gnuradio/pull/4467
=> gr_filter_design: conditionally enable save (backport to maint-3.8)

gr-filter/python/filter/design/filter_design.py, gr-filter/python/filter/gui/GrFilterPlotWidget.py
gr_filter_design: conditionally enable save
Disable save after saving and delete the plots
Backport https://github.com/gnuradio/gnuradio/pull/4467
=> gr_filter_design: conditionally enable save (backport to maint-3.9)

gr-uhd/grc/gen_uhd_usrp_blocks.py
Currently, the only options for setting the timestamp in GRC are `unknown_pps` and `pc_clock`:
- `pc_clock` sets the timestamp to the system time, but does not align these timestamps to the 1PPS input (it instead uses `set_time_now()`). 
- `unknown_pps` aligns the timestamps to the 1PPS input, but sets the timestamp to 0, rather than some form of UTC epoch time. 
This pull request seeks to add options in GRC that will set the timestamp to a value that reflects UTC epoch time, and is also aligned to the 1PPS. Two new options are considered-  `gps_time` and `pc_clock_next_pps`:
- `gps_time` obtains the integer portion of GPS time, adds one second, and sets this timestamp on the next 1PPS (similar to lines 227 - 232 of [query_gpsdo_sensors.cpp](https://github.com/EttusResearch/uhd/blob/master …
=> uhd: Add option to sync timestamp to PC Clock or GPS time on next 1PPS

README.md
Signed-off-by: duggabe <barry@dcsmail.net>
Revise GNU Radio and Python versions.
=> revise README.md Prebuilt Binaries

gr-uhd/grc/gen_uhd_usrp_blocks.py
Signed-off-by: Liu, Andrew Z <liu.andrew@vast-inc.com>
(cherry picked from commit 5547665ee92f748a7ee47d64dfbf133db77fcfce)
Backport https://github.com/gnuradio/gnuradio/pull/4415
=> uhd: Add option to sync timestamp to PC Clock or GPS time on next 1PPS (backport to maint-3.9)

grc/core/FlowGraph.py, grc/core/params/dtypes.py, grc/core/params/param.py
(cherry picked from commit 035ed74a765180c1985035e1df428f81861b431c)
Backport https://github.com/gnuradio/gnuradio/pull/4522
=> grc: update id blackist with imports (backport to maint-3.9)

gr-analog/examples/pll_freqdet_simple.grc, gr-analog/grc/analog_pll_carriertracking_cc.block.yml, gr-analog/grc/analog_pll_freqdet_cf.block.yml, gr-analog/grc/analog_pll_refout_cc.block.yml, gr-analog/lib/pll_freqdet_cf_impl.cc, gr-analog/lib/pll_freqdet_cf_impl.h
Also, minimally refactored pll_freqdet_cf_impl.h, which is a header and has no business including private method implementations.
=> analog: PLL Block: better block naming, better Parameter labels

grc/core/FlowGraph.py, grc/core/params/dtypes.py, grc/core/params/param.py
(cherry picked from commit 035ed74a765180c1985035e1df428f81861b431c)
Backport https://github.com/gnuradio/gnuradio/pull/4522
=> grc: update id blackist with imports (backport to maint-3.8)

gr-filter/grc/filter_interp_fir_filter_xxx.block.yml
Hi all,
This is my first pull request hope everything is owkey/ up to standards.
I noticed not all filter components have direct cpp export and i needed this to debug my system much easier, so based #2343 I edited the fir interp block to also directly output cpp.
=> filter: add cpp export for iir filter

gnuradio-runtime/include/gnuradio/prefs.h, gnuradio-runtime/lib/prefs.cc, gnuradio-runtime/python/gnuradio/gr/bindings/prefs_python.cc
Cleanup of the code.
Actually using the mutex.
Safer preference writing using atomic rename.
=> runtime: Prefs cleanup

gr-utils/modtool/cli/add.py, gr-utils/modtool/cli/newmod.py, gr-utils/modtool/cli/rename.py, gr-utils/modtool/core/__init__.py, gr-utils/modtool/core/add.py, gr-utils/modtool/core/base.py, gr-utils/modtool/core/newmod.py, gr-utils/modtool/core/rename.py, gr-utils/modtool/tests/test_modtool.py
... and fix some validations which checked a prefix instead of the whole name.  https://github.com/gnuradio/gnuradio/issues/3616
=> Improve the 'invalid name' error message in modtool

gr-soapy/grc/CMakeLists.txt, gr-soapy/grc/soapy.tree.yml, gr-soapy/grc/soapy_custom_sink.block.yml, gr-soapy/grc/soapy_custom_source.block.yml, gr-soapy/grc/soapy_hackrf_sink.block.yml
These yml files support the use of SDRs not defined by any of the device-specific yml files.
=> soapy: Add Custom Source/Sink yml for GRC

gr-soapy/include/gnuradio/soapy/block.h, gr-soapy/lib/block_impl.cc, gr-soapy/lib/block_impl.h, gr-soapy/python/soapy/bindings/block_python.cc, gr-soapy/python/soapy/bindings/docstrings/block_pydoc_template.h
* Partially addresses https://github.com/gnuradio/gnuradio/issues/4571
=> soapy: made majority of protected functions public

gr-filter/grc/filter_rational_resampler_xxx.block.yml
(cherry picked from commit ab3137c5fecd90a3b1c5b5c49e10c2fd81516615)
Backport https://github.com/gnuradio/gnuradio/pull/4530
=> grc: fix rational resampler yml template (backport to maint-3.8)

gr-filter/grc/filter_interp_fir_filter_xxx.block.yml
Signed-off-by: Martyn <martijnvdijke600@gmail.com>
(cherry picked from commit 52843c43bfa054c84270a9298274b0b9e4f2dae1)
Backport https://github.com/gnuradio/gnuradio/pull/4509
=> filter: Add C++ templates for Interpolating FIR filter (backport to maint-3.9)

gr-soapy/include/gnuradio/soapy/CMakeLists.txt, gr-soapy/include/gnuradio/soapy/block.h, gr-soapy/include/gnuradio/soapy/soapy_types.h, gr-soapy/lib/block_impl.cc, gr-soapy/lib/block_impl.h, gr-soapy/python/soapy/bindings/block_python.cc, gr-soapy/python/soapy/bindings/docstrings/block_pydoc_template.h, gr-soapy/python/soapy/bindings/soapy_types_python.cc, gr-soapy/python/soapy/qa_soapy_types.py
* Consistency in validate_channel() calls
=> soapy: completed API related to block's current functionality

gr-soapy/lib/block_impl.cc, gr-soapy/python/soapy/bindings/soapy_types_python.cc
* Refactored out input validation functions for later use
=> soapy: consistency in input validation in new functions

gr-soapy/include/gnuradio/soapy/block.h, gr-soapy/lib/block_impl.cc, gr-soapy/lib/block_impl.h, gr-soapy/python/soapy/bindings/CMakeLists.txt, gr-soapy/python/soapy/bindings/block_python.cc, gr-soapy/python/soapy/bindings/docstrings/block_pydoc_template.h, gr-soapy/python/soapy/bindings/soapy_common.cc, gr-soapy/python/soapy/bindings/soapy_common.h, gr-soapy/python/soapy/bindings/soapy_types_python.cc
* Refactored out pybind functions into own utility functions
=> soapy: added remaining functions that need custom pybind functions

gr-soapy/include/gnuradio/soapy/block.h, gr-soapy/lib/block_impl.cc, gr-soapy/lib/block_impl.h, gr-soapy/python/soapy/bindings/block_python.cc, gr-soapy/python/soapy/bindings/docstrings/block_pydoc_template.h
=> soapy: full SoapySDR 0.8 support (with 0.7.2 compatibility), minus messages

gr-channels/grc/channels_impairments.block.yml, gr-channels/python/channels/distortion_2_gen.py, gr-channels/python/channels/impairments.py
- Add missing label docs for the phase noise power
- Fix a bunch of Pylint issues
- Rename blocks in the hier block from their GRC auto-generated names to
something more readable
Fixes https://github.com/gnuradio/gnuradio/issues/1579
=> channels: Clean up the hardware impairments block

.packaging/debian/control, .packaging/debian/gnuradio.docs, .packaging/debian/gnuradio.install, .packaging/fedora/gnuradio.spec
Backport https://github.com/gnuradio/gnuradio/pull/4570
=> pkg: add soapy support for in-tree packaging (backport to maint-3.9)

.github/workflows/make-test.yml
=> ci: use same containers for maint-3.9 as for master

grc/tests/CMakeLists.txt, grc/tests/test_examples.py
Backport https://github.com/gnuradio/gnuradio/pull/4208
=> grc: Test all in-tree examples (backport to maint-3.9)

gr-qtgui/lib/VectorDisplayPlot.cc
Signed-off-by: 0xloem <0xloem@gmail.com>
(cherry picked from commit 04f1eb0f98682b8f3a0924273262eacec41355ea)
Backport https://github.com/gnuradio/gnuradio/pull/4676
=> Fix vector margin for non-frequency data (backport to maint-3.9)

gr-uhd/python/uhd/bindings/uhd_types_python.cc
=> gr-uhd: Adding missing Python binding for uhd::tune_request_t::policy_t.

grc/gui/ParamWidgets.py
Backport https://github.com/gnuradio/gnuradio/pull/4551
=> grc: fix dark theme on ParamWidgets

grc/core/blocks/block.py, grc/gui/canvas/block.py, grc/gui/canvas/colors.py
Backport https://github.com/gnuradio/gnuradio/pull/4543
=> GRC: Make deprecated blocks appear in orange on Canvas (backport to maint-3.9)

gr-qtgui/lib/VectorDisplayPlot.cc
Signed-off-by: 0xloem <0xloem@gmail.com>
(cherry picked from commit 04f1eb0f98682b8f3a0924273262eacec41355ea)
Backport https://github.com/gnuradio/gnuradio/pull/4676
=> Fix vector margin for non-frequency data (backport to maint-3.8)

CHANGELOG.md, CMakeLists.txt
=> v3.8.3.1-rc1

CHANGELOG.md, CMakeLists.txt
=> v3.9.2.0-rc1

grc/core/Constants.py, grc/core/cache.py, grc/core/platform.py
Backport https://github.com/gnuradio/gnuradio/pull/4671
=> GRC: Cache time- and version-sensitive (backport to maint-3.9)

grc/core/Constants.py, grc/core/cache.py, grc/core/platform.py
Manual backport based on commits
bb4c65524 e2f152dd4 9d92ffbc0 8eec6d6e3
Author: Marcus Müller <mmueller@gnuradio.org>
=> GRC: Cache time- and version-sensitive

gr-iio/grc/iio_pluto_sink.block.yml, gr-iio/python/iio/bindings/pluto_sink_python.cc
=> iio: Rename set_gain to set_attenuation in pluto_sink

gr-iio/include/gnuradio/iio/pluto_sink.h, gr-iio/python/iio/bindings/pluto_sink_python.cc, gr-soapy/include/gnuradio/soapy/block.h, gr-soapy/include/gnuradio/soapy/sink.h, gr-soapy/include/gnuradio/soapy/source.h, gr-soapy/python/soapy/bindings/block_python.cc, gr-soapy/python/soapy/bindings/sink_python.cc, gr-soapy/python/soapy/bindings/source_python.cc
=> Doxygen: Remove warnings from gr-soapy and gr-iio.

gnuradio-runtime/include/gnuradio/rpcregisterhelpers.h, gnuradio-runtime/lib/block_registry.cc, gnuradio-runtime/lib/local_sighandler.cc, gnuradio-runtime/lib/math/qa_fxpt.cc, gnuradio-runtime/lib/math/qa_fxpt_nco.cc, gnuradio-runtime/lib/math/qa_fxpt_vco.cc, gnuradio-runtime/lib/math/qa_math.cc, gnuradio-runtime/lib/pagesize.cc, gnuradio-runtime/lib/pmt/qa_pmt_prims.cc, gnuradio-runtime/lib/pmt/qa_pmt_unv.cc, gnuradio-runtime/lib/realtime_impl.cc, gnuradio-runtime/lib/sys_paths.cc, gnuradio-runtime/lib/thread/thread_body_wrapper.cc, gnuradio-runtime/lib/vmcircbuf.cc, gnuradio-runtime/lib/vmcircbuf_mmap_tmpfile.cc, gnuradio-runtime/lib/vmcircbuf_sysv_shm.cc, gnuradio-runtime/python/gnuradio/gr/bindings/rpcregisterhelpers_python.cc
Closes #4766
~Depends on #4764~
=> Remove <cstdio>

gr-qtgui/lib/EyeDisplayPlot.cc, gr-qtgui/lib/HistogramDisplayPlot.cc, gr-qtgui/lib/TimeDomainDisplayPlot.cc, gr-qtgui/lib/TimePrecisionClass.h, gr-qtgui/lib/TimeRasterDisplayPlot.cc
Compiler was complaining about it. 
Fixes #4756 
On the way there, stumbled across VOLK in unexpected places #4777
=> Have only one definition of TimePrecisionClass

gnuradio-runtime/include/gnuradio/rpcregisterhelpers.h, gnuradio-runtime/lib/block_registry.cc, gnuradio-runtime/lib/local_sighandler.cc, gnuradio-runtime/lib/math/qa_fxpt.cc, gnuradio-runtime/lib/math/qa_fxpt_nco.cc, gnuradio-runtime/lib/math/qa_fxpt_vco.cc, gnuradio-runtime/lib/math/qa_math.cc, gnuradio-runtime/lib/pagesize.cc, gnuradio-runtime/lib/pmt/qa_pmt_prims.cc, gnuradio-runtime/lib/pmt/qa_pmt_unv.cc, gnuradio-runtime/lib/realtime_impl.cc, gnuradio-runtime/lib/sys_paths.cc, gnuradio-runtime/lib/thread/thread_body_wrapper.cc, gnuradio-runtime/lib/vmcircbuf.cc, gnuradio-runtime/lib/vmcircbuf_mmap_tmpfile.cc, gnuradio-runtime/lib/vmcircbuf_sysv_shm.cc, gnuradio-runtime/python/gnuradio/gr/bindings/rpcregisterhelpers_python.cc
Backport https://github.com/willcode/gnuradio/pull/new/backport/maint-3.9/4767
with minor changes.
=> Remove <cstdio> (backport to maint-3.9)

CODE_OF_CONDUCT.md
The text is unmodified, with the exception of our coc email put in.
=> coc: Update to contributor covenant 2.0

gr-soapy/lib/block_impl.cc, gr-soapy/lib/block_impl.h, gr-soapy/lib/setting_string_conversion.h, gr-soapy/python/soapy/bindings/CMakeLists.txt, gr-soapy/python/soapy/bindings/soapy_common.cc
* Moved string <-> setting conversion to common header
* Closes https://github.com/gnuradio/gnuradio/issues/4571
=> soapy: added message support for SoapySDR 0.8 API

gr-qtgui/lib/time_sink_c_impl.cc, gr-qtgui/lib/time_sink_f_impl.cc
fixes #2775
Signed-off-by: Jason Uher <jason.uher@jhuapl.edu>
=> qtgui: bugfix - display tags on the last sample

gr-analog/grc/analog_probe_avg_mag_sqrd_x.block.yml, gr-channels/grc/channels_channel_model2.block.yml, gr-channels/grc/channels_dynamic_channel_model.block.yml, gr-channels/grc/channels_fading_model.block.yml, gr-channels/grc/channels_selective_fading_model.block.yml, gr-channels/grc/channels_selective_fading_model2.block.yml, gr-qtgui/grc/qtgui_vector_sink_f.block.yml
Also one in analog, and an overachieving set of quotes in qtgui.
Fixes https://github.com/gnuradio/gnuradio/issues/4787
=> gr-channels: fix "hide" expressions in yml files

gr-analog/grc/analog_probe_avg_mag_sqrd_x.block.yml, gr-channels/grc/channels_channel_model2.block.yml, gr-channels/grc/channels_dynamic_channel_model.block.yml, gr-channels/grc/channels_fading_model.block.yml, gr-channels/grc/channels_selective_fading_model.block.yml, gr-channels/grc/channels_selective_fading_model2.block.yml, gr-qtgui/grc/qtgui_vector_sink_f.block.yml
Also one in analog, and an overachieving set of quotes in qtgui.
(cherry picked from commit fbf2082c0e110eed210e05894c356f3582397993)
Backport https://github.com/gnuradio/gnuradio/pull/4894
=> gr-channels: fix "hide" expressions in yml files (backport to maint-3.8)

gr-analog/grc/analog_probe_avg_mag_sqrd_x.block.yml, gr-channels/grc/channels_channel_model2.block.yml, gr-channels/grc/channels_dynamic_channel_model.block.yml, gr-channels/grc/channels_fading_model.block.yml, gr-channels/grc/channels_selective_fading_model.block.yml, gr-channels/grc/channels_selective_fading_model2.block.yml, gr-qtgui/grc/qtgui_vector_sink_f.block.yml
Also one in analog, and an overachieving set of quotes in qtgui.
(cherry picked from commit fbf2082c0e110eed210e05894c356f3582397993)
Backport https://github.com/gnuradio/gnuradio/pull/4894
=> gr-channels: fix "hide" expressions in yml files (backport to maint-3.9)

gr-fec/python/fec/LDPC/Generate_LDPC_matrix_functions.py
Greetings, 
I've been using custom LDPC matrices and noticed the helper python scripts needed some tweaking to output the preprocessed matrix. The scripts were tested with python3 and the resulting preprocessed alist file works correctly with the LDPC encoder and decoder blocks.
=> Corrected spacings and updated String.split() usage

gr-blocks/lib/pack_k_bits_bb_impl.cc, gr-blocks/lib/pack_k_bits_bb_impl.h, gr-blocks/python/blocks/qa_pack_k_bits.py, gr-blocks/python/blocks/qa_unpack_k_bits.py
fixes #1111
Signed-off-by: Jason Uher <jason.uher@jhuapl.edu>
=> gr-blocks: (un)pack-k-bits tag propagation Bugfix #1111

.github/workflows/make-test.yml, cmake/Modules/GrPybind.cmake, gnuradio-runtime/CMakeLists.txt, gnuradio-runtime/lib/CMakeLists.txt, gr-analog/lib/CMakeLists.txt, gr-audio/lib/CMakeLists.txt, gr-blocks/lib/CMakeLists.txt, gr-channels/lib/CMakeLists.txt, gr-digital/lib/CMakeLists.txt, gr-dtv/lib/CMakeLists.txt, gr-fec/lib/CMakeLists.txt, gr-fft/lib/CMakeLists.txt, gr-filter/lib/CMakeLists.txt, gr-iio/lib/CMakeLists.txt, gr-network/lib/CMakeLists.txt, gr-pdu/lib/CMakeLists.txt, gr-qtgui/lib/CMakeLists.txt, gr-soapy/lib/CMakeLists.txt, gr-trellis/lib/CMakeLists.txt, gr-video-sdl/lib/CMakeLists.txt, gr-vocoder/lib/CMakeLists.txt, gr-wavelet/lib/CMakeLists.txt, gr-zeromq/lib/CMakeLists.txt
Manually rebased version of 
Use precompiled headers #4724
=> Use precompiled headers (Rebase of #4724)

gr-fec/python/fec/LDPC/Generate_LDPC_matrix_functions.py
Backport https://github.com/gnuradio/gnuradio/pull/4837
=> Corrected spacings and updated String.split() usage (backport to maint-3.9)

gr-analog/grc/analog_noise_source_x.block.yml, gr-qtgui/examples/c++/Number_Sink.grc, gr-qtgui/examples/c++/gui_sink.grc, gr-qtgui/grc/qtgui_check_box.block.yml, gr-qtgui/grc/qtgui_entry.block.yml, gr-qtgui/grc/qtgui_freq_sink_x.block.yml, gr-qtgui/grc/qtgui_label.block.yml, gr-qtgui/grc/qtgui_number_sink.block.yml, gr-qtgui/grc/qtgui_sink_x.block.yml, gr-qtgui/grc/qtgui_tab_widget.block.yml, gr-qtgui/grc/qtgui_waterfall_sink_x.block.yml, gr-qtgui/include/gnuradio/qtgui/freq_sink_c.h, gr-qtgui/include/gnuradio/qtgui/freq_sink_f.h, gr-qtgui/include/gnuradio/qtgui/number_sink.h, gr-qtgui/include/gnuradio/qtgui/sink_c.h, gr-qtgui/include/gnuradio/qtgui/sink_f.h, gr-qtgui/include/gnuradio/qtgui/waterfall_sink_c.h, gr-qtgui/include/gnuradio/qtgui/waterfall_sink_f.h, grc/core/generator/cpp_templates/flow_graph.cpp.mako, grc/core/generator/cpp_top_block.py, grc/core/params/param.py
Backport https://github.com/gnuradio/gnuradio/pull/4808/commits
=> grc: introduce gui_hint for cpp code generation (backport to maint-3.9)

gr-pdu/grc/pdu_pdu_lambda.block.yml
=> gr-pdu: Fix indentation in pdu_pdu_lambda.block.yml file.

gr-digital/lib/constellation_receiver_cb_impl.cc
Removes `tag_checker`
Improves performance
=> digital: constellation_receiver_cb rework

gr-digital/grc/digital_gfsk_mod.block.yml, gr-digital/python/digital/gfsk.py
=> gr-digital: Remove packed to unpacked gfsk mod hier block

gr-pdu/examples/pdu_lambda_chirp_demo.grc, gr-pdu/examples/pdu_lambda_example.grc, gr-pdu/examples/simple_pdu_to_stream_example.grc, gr-pdu/grc/pdu_pdu_lambda.block.yml, gr-pdu/python/pdu/pdu_lambda.py
Several flowgraphs had errors in them due to a name change during development.
Thanks @drmpeg!
=> gr-pdu: fix pdu_lambda block and examples

gr-uhd/examples/python/freq_hopping.py
Signed-off-by: Adrien Michel <adriengit@users.noreply.github.com>
=> gr-uhd: fix input filename in freq hopping examples

docs/doxygen/update_pydoc.py, gr-utils/modtool/templates/gr-newmod/docs/doxygen/update_pydoc.py
Signed-off-by: japm48 <japm48@users.noreply.github.com>
(cherry picked from commit 18488e31d4ad13077990383f7eb0e1ab7655bf23)
Backport https://github.com/gnuradio/gnuradio/pull/4965
=> pybind11: remove debug message (backport to maint-3.9)

grc/gui/Dialogs.py
(cherry picked from commit f788f65c7b5b52183a3d97fd8d3b17f9bd21c733)
Backport https://github.com/gnuradio/gnuradio/pull/3650
=> grc: Make it possible to copy error message (backport to maint-3.9)

gr-video-sdl/lib/sink_s_impl.cc, gr-video-sdl/lib/sink_uc_impl.cc
=> gr-video-sdl: Fix reversal of U and V channels on sink blocks.

gr-fft/grc/fft_logpwrfft_x.block.yml, gr-fft/python/fft/logpwrfft.py
Contributed by Marcus Leech
Closes https://github.com/gnuradio/gnuradio/issues/5000
=> gr-fft: add "shift" param to logpwrfft block

gr-digital/grc/digital_symbol_sync_xx.block.yml
Signed-off-by: Rohan Sharma <rhnsharma5113@gmail.com>
Fixes #5009
Hi @marcusmueller, how does this look?
Let me know if this needs any changes.
Thanks
=> grc: replace likelyhood with likelihood

gr-fft/grc/fft_logpwrfft_x.block.yml, gr-fft/python/fft/logpwrfft.py
Contributed by Marcus Leech
(cherry picked from commit 3b3d1ea269e9f16ed4b34636f45a9e2fc428f2ec)
Backport https://github.com/gnuradio/gnuradio/pull/5003
=> gr-fft: add "shift" param to logpwrfft block (backport to maint-3.9)

gr-fft/grc/fft_logpwrfft_x.block.yml, gr-fft/python/fft/logpwrfft.py
Contributed by Marcus Leech
(cherry picked from commit 3b3d1ea269e9f16ed4b34636f45a9e2fc428f2ec)
Backport https://github.com/gnuradio/gnuradio/pull/5003
=> gr-fft: add "shift" param to logpwrfft block (backport to maint-3.8)

gr-video-sdl/grc/video_sdl_sink.block.yml, gr-video-sdl/include/gnuradio/video_sdl/sink_s.h, gr-video-sdl/include/gnuradio/video_sdl/sink_uc.h, gr-video-sdl/lib/sink_s_impl.cc, gr-video-sdl/lib/sink_s_impl.h, gr-video-sdl/lib/sink_uc_impl.cc, gr-video-sdl/lib/sink_uc_impl.h, gr-video-sdl/python/video_sdl/bindings/sink_s_python.cc, gr-video-sdl/python/video_sdl/bindings/sink_uc_python.cc
=> gr-video-sdl: Clean up sink

grc/core/blocks/_templates.py
(cherry picked from commit 774d30d66afdab0c16d9239d84e5829187f791c4)
Backport https://github.com/gnuradio/gnuradio/pull/5016
=> grc: Add no_quotes() convenience function (callable from templates) (backport to maint-3.9)

gr-digital/lib/constellation.cc, gr-digital/python/digital/qa_constellation.py
Correct power normalization calculation.
Add a qa test for amplitude and power normalization.
Partially fixes #4892
=> gr-digital: Fix constellation normalization by average power

CMakeLists.txt, cmake/Modules/FindCodec2.cmake, cmake/Modules/FindFFTW3f.cmake, cmake/Modules/FindGMP.cmake, cmake/Modules/FindGSM.cmake, cmake/Modules/FindMPIR.cmake, cmake/Modules/FindPORTAUDIO.cmake, cmake/Modules/FindSNDFILE.cmake, cmake/Modules/FindTHRIFT.cmake, cmake/Modules/FindUHD.cmake, cmake/Modules/FindZeroMQ.cmake, gr-utils/modtool/templates/gr-newmod/CMakeLists.txt, gr-utils/modtool/templates/gr-newmod/cmake/Modules/howtoConfig.cmake
=> cmake: Use preferred method to find PkgConfig.

gr-network/lib/tuntap_pdu_impl.cc
=> gr-network: Fixup tuntap suppress warning on Debian 11.

CMakeLists.txt, cmake/Modules/FindCodec2.cmake, cmake/Modules/FindFFTW3f.cmake, cmake/Modules/FindGMP.cmake, cmake/Modules/FindGSM.cmake, cmake/Modules/FindMPIR.cmake, cmake/Modules/FindPORTAUDIO.cmake, cmake/Modules/FindSNDFILE.cmake, cmake/Modules/FindTHRIFT.cmake, cmake/Modules/FindUHD.cmake, cmake/Modules/FindZeroMQ.cmake, gr-utils/modtool/templates/gr-newmod/CMakeLists.txt, gr-utils/modtool/templates/gr-newmod/cmake/Modules/howtoConfig.cmake
(cherry picked from commit 9b096690ee2d4d13fa645f7c7e25775b04e41d04)
Backport https://github.com/gnuradio/gnuradio/pull/5043
=> cmake: Use preferred method to find PkgConfig (backport to maint-3.9)

CHANGELOG.md, CMakeLists.txt
=> Prepare for v3.8.4.0-rc1

CHANGELOG.md, CMakeLists.txt
=> Prepare for v3.9.3.0-rc1

.github/workflows/pull_request_template.md
Signed-off-by: Bernard Tyers - Sane UX Design <bernard+work@ei8fdb.org>
=> committing pull request template with DCO signing.

.github/workflows/feature_request_template.md
Signed-off-by: Bernard Tyers - Sane UX Design <bernard+work@ei8fdb.org>
=> github: Added feature request template

gr-blocks/grc/blocks_unpacked_to_packed_xx.block.yml
---
title: ''
labels: ''
assignees: ''
---
In commit 612c650, cpp support was added to the unpacked_to_packed
block. However, the cpp flag was not added. Neither was the endianness
option set correctly. This commit fixes it using packed_to_unpacked as
reference.
Prior to this PR, this the unpacked_to_packed block cannot be used to generate cpp code. The compiler will complain about `gr.GR_LSB_FIRST`. This PR fixes it using packed_to_unpacked as reference.
```
/home/swjs/Documents/test/test.cpp:37:89: error: expected primary-expression before ‘.’ token
37 |         this->blocks_unpacked_to_packed_xx_0 = blocks::unpacked_to_packed_bb::make(8, gr.GR_LSB_FIRST);
| …
```
=> gr-blocks: Fix cpp support for unpacked to packed

gr-channels/lib/flat_fader_impl.cc
---
name: channels: Fix bad initialization of RNG seeds.
about: 
title: ''
labels: ''
assignees: ''
---
Previosuly the block attempted to initialize RNGs in the constructor initializers, but this does not work.  Moved the initialization to the body of the constructor.
=> channels: Fix bad initialization of RNG seeds.

gnuradio-runtime/CMakeLists.txt
This defines NOMINMAX when compiling the common-precompiled-headers target with MSVC, much like it is defined when compiling gnuradio-runtime. This fixes compilation with MSVC because of the use of min/max functions in the precompiled headers.
The build with PCH enabled failed before this patch and passes with it over at #4410.
=> runtime: Add NOMINMAX def on common-precompiled-headers when using MSVC

grc/gui/DrawingArea.py
=> grc: Include scale factor when computing drawing area size

gr-qtgui/grc/qtgui_check_box.block.yml, gr-qtgui/grc/qtgui_chooser.block.yml, gr-qtgui/grc/qtgui_entry.block.yml, gr-qtgui/grc/qtgui_label.block.yml, gr-qtgui/grc/qtgui_msgcheckbox.block.yml, gr-qtgui/grc/qtgui_range.block.yml, gr-qtgui/grc/qtgui_tab_widget.block.yml
=> gr-qtgui: Use no_quotes function in some qtgui blocks

grc/core/FlowGraph.py, grc/gui/Application.py
(cherry picked from commit dae6e47c1858a3273bed0e7405a33f156f95ae7b)
Backport https://github.com/gnuradio/gnuradio/pull/5187
=> grc: Dependent variables sometimes fail to evaluate (backport to maint-3.9)

.github/workflows/make-test.yml
Manual backport of https://github.com/gnuradio/gnuradio/pull/5253
=> CI: enable qa_agc
