grc/python/flow_graph.tmpl
Seems some newer Qt do Xlib call right when doing the imports
which then means that doing it in the main() is too late.
Signed-off-by: Sylvain Munaut <tnt@246tNt.com>
=> grc: Move the XInitThreads to "As Early As Possible"

CMakeLists.txt, gnuradio-runtime/apps/gnuradio-config-info.cc, gnuradio-runtime/include/gnuradio/constants.h, gnuradio-runtime/lib/CMakeLists.txt, gnuradio-runtime/lib/constants.cc.in
Since this should reflect the CMake enabled components,
having the cmake variable set correctly demanded generating constants.cc after CMake has been run.
Since the autonomity of the gnuradio-runtime/CMakeLists.txt shouldn't
be reduced, this is done twice; the build-time overhead is minimal.
=> gnuradio-config-info: Added --enabled-components

gr-trellis/grc/trellis_encoder_xx.xml
Hi Johnathan, 
I made a new branch called trellisupdate and included the bug fix here. I'm trying to merge to maint. 
Could you check it ?
Thanks!
Best,
Zhe
=> trellis: bug fixed:adding a missing callback function set_K in trellis_ecoder

gr-blocks/grc/blocks_stream_to_tagged_stream.xml, gr-blocks/include/gnuradio/blocks/stream_to_tagged_stream.h, gr-blocks/lib/stream_to_tagged_stream_impl.cc, gr-blocks/lib/stream_to_tagged_stream_impl.h
Hi @jmcorgan ,
I opened this pull request for the callback functions we added to stream_to_tagged_stream. Because in our adaptive modulation/coding system, the packet length might be changed for different modulation/coding scheme. That's why we want to add callback functions for packet_len and packet_len_pmt. 
Could you review and merge it?
Thanks!
Best,
Zhe
=> blocks: added callback functions to stream_to_tagged_stream

gr-blocks/grc/blocks_repack_bits_bb.xml, gr-blocks/include/gnuradio/blocks/repack_bits_bb.h, gr-blocks/lib/repack_bits_bb_impl.cc, gr-blocks/lib/repack_bits_bb_impl.h
Hi @jmcorgan , 
In this pull request, we added a callback function set_k_and_l to update both bits per input and output bytes of repack_bits in gr-blocks to make it able to be changed dynamically. It is used in our adaptive modulation/coding system too. 
Thanks!
Best,
Zhe
=> blocks: added callback function set_k_and_l to repack bits

gr-utils/octave/write_complex_binary.m
A handy script to write Octave complex variables to GNURadio gr_complex format.
=> gr-utils: Added octave function to write fc32 format (gr_complex) 

gr-blocks/grc/blocks_tuntap_pdu.xml, gr-blocks/include/gnuradio/blocks/tuntap_pdu.h, gr-blocks/lib/tuntap_pdu_impl.cc, gr-blocks/lib/tuntap_pdu_impl.h
Made tap/tun selectable in GRC.  Fixed GRC .xml default device name of "tun0" although default flag was IFF_TAP.
=> gr-blocks: Make tap/tun configurable, fix GRC spec to be consistent with IFF_TAP

gr-qtgui/lib/time_sink_c_impl.cc, gr-qtgui/lib/time_sink_f_impl.cc
Where it could miss a tag to display every now and then.
This is probably related to bug #751 (http://gnuradio.org/redmine/issues/751), but it's hard to see since the tag has to be 1 item beyond the window we were actually looking in. I'm not entirely sure that I understand this fix, but my guess is that it's related to the fact that history = 2 for these blocks.
=> qtgui: fixed a small bug in the time sink

gnuradio-runtime/lib/block.cc
This needs a review to think if it might interact poorly with anything else, messages or streaming related.
=> runtime: possible bug fix for limited-run flowgraphs with message-only blocks

gr-blocks/include/gnuradio/blocks/peak_detector_XX.h.t, gr-blocks/lib/peak_detector_XX_impl.h.t
Sadly constitutes an API change, though the set_alpha is currently unusable.
=> blocks: the API for the peak_detector blocks incorrectly uses int instead of float for setting alpha.

gr-qtgui/grc/qtgui_block_tree.xml, gr-qtgui/grc/qtgui_push_button.xml
I added a push button widget to control the value of a variable. The variable will take on one of two user-configured values depending on whether the button is in the pushed or released state. One example use case is temporarily opening a squelch block.
=> qtgui: added a variable push button widget

gnuradio-runtime/include/gnuradio/block.h, gnuradio-runtime/include/gnuradio/buffer.h, gr-blocks/lib/qa_blocks.cc, gr-blocks/lib/qa_gr_block.cc, gr-blocks/lib/qa_gr_block.h
Addresses Issue #729.
Reintroduced qa_gr_block and added t2 tests to get input/output buffer size and base.
Need to include buffer.h, block.h, and block_detail.h when calling these in a block's work function.
=> runtime: added accessor to get base address of buffer.

gr-filter/include/gnuradio/filter/pfb_arb_resampler.h
This changes the public header file, but it's just an argument name change, which shouldn't affect the API. It's not exported directly in Python, either, so there's no chance of this causing a problem there, either.
=> filter: fixing the pfb_arb_resampler's prototype to use the correct argument order

gr-digital/grc/digital_additive_scrambler_bb.xml
Allow setting reset_tag_key from GRC. Leaving the field blank results in a blank tag key, which is equivalent to using the default constructor.
=> digital: added reset_tag_key field to additive scrambler GRC xml

gr-blocks/grc/blocks_integrate_xx.xml, gr-blocks/include/gnuradio/blocks/integrate_XX.h.t, gr-blocks/lib/integrate_XX_impl.cc.t, gr-blocks/lib/integrate_XX_impl.h.t, gr-blocks/python/blocks/qa_integrate.py
Extend integration block. Allow vector input and integrate it element-vise. Output is vector if integrated items.
=> blocks: integration supports vector input

gr-blocks/lib/message_strobe_impl.cc, gr-blocks/lib/message_strobe_impl.h
On embedded systems, this block's destructure was not getting called
in the right order and the flowgraph would hang because this block's
thread running run would never quit. Moving the start and stop
handling of this thread to the start/stop functions of the block fix
this. Also makes sure that the block is only producing messages when
the flowgraph is running.
=> blocks: message strobe shutdown fix.

docs/doxygen/other/ctrlport.dox, docs/doxygen/other/metadata.dox, docs/doxygen/other/msg_passing.dox, docs/doxygen/other/ofdm.dox, docs/doxygen/other/packet_txrx.dox, docs/doxygen/other/perf_counters.dox, docs/doxygen/other/pfb_intro.dox, docs/doxygen/other/pmt.dox, docs/doxygen/other/stream_tags.dox, docs/doxygen/other/tagged_stream_blocks.dox, gr-analog/doc/analog.dox, gr-audio/doc/audio.dox, gr-blocks/doc/blocks.dox, gr-channels/doc/channels.dox, gr-digital/doc/digital.dox, gr-fcd/doc/fcd.dox, gr-fec/doc/fec.dox, gr-fft/doc/fft.dox, gr-filter/doc/filter.dox, gr-qtgui/doc/qtgui.dox, gr-uhd/doc/uhd.dox, gr-vocoder/doc/vocoder.dox, gr-zeromq/docs/zeromq.dox
Doxygen is getting more strict with having labels for every section,
and warns when there are section name collisions. This prefixes all
section and subsection labels with the component to make them all
unique.
=> docs: fixed labels and references in manual.

gr-qtgui/lib/FrequencyDisplayPlot.cc, gr-qtgui/lib/freq_sink_c_impl.cc, gr-qtgui/lib/freq_sink_f_impl.cc
If FFT Size is set to 2048 and the half-width is selected for the
float graph type, then this would cause the x-axis display to show
-fs/2 to +fs/2 instead of the correct 0 to +fs/2. The problem was the
default numpoints was 1024, so with half 2048, the resetting of the
x-axis call was never hitting. Setting to 0 to force updates during
the first display.
Also puts protections around the allowable FFT sizes.
=> qtgui: fixes issue #767.

gr-analog/grc/analog_ctcss_squelch_ff.xml, gr-analog/include/gnuradio/analog/ctcss_squelch_ff.h, gr-analog/lib/ctcss_squelch_ff_impl.cc, gr-analog/lib/ctcss_squelch_ff_impl.h, gr-analog/lib/pwr_squelch_cc_impl.cc, gr-analog/lib/pwr_squelch_cc_impl.h, gr-analog/lib/squelch_base_cc_impl.cc
While working on a GRC graph that uses the CTCSS squelch block, I found that I was unable to change the frequency used for the CTCSS squelch at run-time (e.g., via values from a QT GUI Chooser).  This is due to the fact that this parameter is fixed when the block is created. An accessor and modifier for the frequency parameter have been introduced.
This change has been broken into three separate patches just to better articulate the rationale for the changes made.  Let me know if you want them squashed, changed, or dropped.
=> Add frequency accessor/modifier to CTCSS squelch

gr-filter/include/gnuradio/filter/iir_filter.h, gr-filter/lib/iir_filter.cc, gr-filter/lib/iir_filter_ccc_impl.cc, gr-filter/lib/iir_filter_ccc_impl.h, gr-filter/lib/iir_filter_ccd_impl.cc, gr-filter/lib/iir_filter_ccd_impl.h, gr-filter/lib/iir_filter_ccf_impl.cc, gr-filter/lib/iir_filter_ccf_impl.h, gr-filter/lib/iir_filter_ccz_impl.cc, gr-filter/lib/iir_filter_ccz_impl.h, gr-filter/lib/iir_filter_ffd_impl.cc, gr-filter/lib/iir_filter_ffd_impl.h
Adding template for filter stability of higher-precision taps.
Adds docs and exports kernels from library (FILTER_API).
=> iir filter stability

gr-uhd/include/gnuradio/uhd/usrp_source.h, gr-uhd/lib/usrp_source_impl.cc, gr-uhd/lib/usrp_source_impl.h
Added wrapper code to gr-uhd to wrap UHD method 
````c++
set_rx_iq_balance(const bool enb, size_t chan)
````
=> gr-uhd: support for IQ imbalance enable/disable

CMakeLists.txt, gnuradio-runtime/lib/CMakeLists.txt, gr-analog/lib/CMakeLists.txt, gr-blocks/lib/CMakeLists.txt, gr-channels/lib/CMakeLists.txt, gr-digital/lib/CMakeLists.txt, gr-dtv/lib/CMakeLists.txt, gr-fec/lib/CMakeLists.txt, gr-filter/lib/CMakeLists.txt, gr-qtgui/lib/CMakeLists.txt, gr-wxgui/lib/CMakeLists.txt
@n-west: test build with volk submodule:
- external pre-installed volk library from its master (to a custom location)
- use submodule to build in-tree (can this be forced?)
These patches make both cases work for me.
=> cmake: use VOLK_LIBRARIES

gr-digital/lib/clock_recovery_mm_cc_impl.cc
Currently, the upper limit for the mm value is different if a second output is used.
https://github.com/gnuradio/gnuradio/blob/master/gr-digital/lib/clock_recovery_mm_cc_impl.cc#L191
=> digital: mm clock recovery - fix clipping w/ 2nd output

gr-digital/grc/digital_chunks_to_symbols.xml, gr-digital/include/gnuradio/digital/chunks_to_symbols_XX.h.t, gr-digital/lib/chunks_to_symbols_XX_impl.cc.t, gr-digital/lib/chunks_to_symbols_XX_impl.h.t, gr-digital/python/digital/qa_chunks_to_symbols.py
Dear Johnathan, 
I'm here to submit again the pull request that you close a while ago due to lack of qa test. 
https://github.com/gnuradio/gnuradio/pull/354
I kept the previous code which you approved and added the qa test you wanted. 
I'm sorry that I didn't update the qa_test of chunks_to_symbols on time. I added two more tests to test the callback function set_chunks_symbol_table by learning from existing qa tests with callback function tests.
Could you please check it and merge it? Please let me know if there is something wrong. 
Thanks!
Best regards!
Zhe
=> digital: bug fixed in chunks_to_symbols that the callback functiion set_symbol_table didn't work with additonal qa_tests

grc/blocks/options.xml, grc/gui/ActionHandler.py, grc/gui/Bars.py, grc/gui/Dialogs.py, grc/gui/FlowGraph.py, grc/gui/MainWindow.py, grc/gui/Param.py, grc/gui/Preferences.py, grc/gui/PropsDialog.py, grc/python/Generator.py, grc/python/flow_graph.tmpl, grc/scripts/gnuradio-companion
(this the branch from gnuradio-wg-grc, can't issue a pull request from there)
- Save confirmation dialog changes (Ethan Trewhitt)
- Switch to "import" in hier blocks (#763)
- Thread-safe setters (#748)
- Minor fix-ups:
- no sheband in hier blocks code else use python*2*
- don't attempt to load deleted flowgraph from last time
- context menu clean-up (feedback: sensible?)
- set perms on generated files
- A refactored version of "gnuradio-companion"
- I forgot to mention this in the call...
- mostly clean-up
- allows to run GRC from source (if called from there)
- this is roughly what I use to develop
- still need a installed version of GR around
- hopefully makes it easier for people to test new feat.
=> GRC changes to master

gnuradio-runtime/include/gnuradio/fxpt.h, gnuradio-runtime/include/gnuradio/fxpt_vco.h, gnuradio-runtime/lib/math/qa_fxpt.cc, gr-analog/lib/frequency_modulator_fc_impl.cc, gr-atsc/include/gnuradio/atsc/field_sync_demux.h, gr-audio/lib/alsa/alsa_sink.cc, gr-audio/lib/alsa/alsa_source.cc, gr-pager/lib/flex_parse_impl.cc
Also fixes cases where types.h was included withought previous inclusion of config.h, this leads to use of "backup" definitions of gr_int* types and in cases where it is not required and thus to potential errors.
=> remove gr_int* types, #618

gnuradio-runtime/include/gnuradio/basic_block.h
message_handler_t d_message_handler variable was commented out
anyway, so obviously no longer needed.
Signed-off-by: Moritz Fischer <moritz.fischer@ettus.com>
=> runtime: cleanup: Removing leftovers.

grc/base/Block.py, grc/gui/ActionHandler.py, grc/gui/Actions.py, grc/gui/Bars.py, grc/gui/Block.py, grc/gui/Colors.py, grc/gui/FlowGraph.py, grc/gui/Param.py, grc/gui/PropsDialog.py, grc/python/Param.py
As requested, a copy of issue #780. **Note: this is on top of master_grcwg**. 
Here the original text and some screen shots.
This adds simple unformatted text comments to each block on the canvas via a param in the advanced tap (for now). These are displayed left-aligned beneath the block.
To ease entry a new param type "multiline" has been added which allows for multi-line text entry.
Feedback is appreciated:
- hide comments for disabled blocks?
- center align comments beneath blocks?
- use string param type background color for multiline entry box?
=> GRC block comments

gr-blocks/examples/vector_source_with_tags.grc, gr-blocks/grc/blocks_block_tree.xml, gr-blocks/grc/blocks_tag_object.xml
Edit boxes to set the tag's offset, key, value, and source id to make
it easier to create and use tags in a flwograph. the gr-blocks example
vector_source_with_tags.grc has been updated to use this.
=> blocks: adding a variable tag_object to help build tags.

gnuradio-runtime/include/gnuradio/hier_block2.h, gnuradio-runtime/lib/hier_block2.cc, gnuradio-runtime/lib/hier_block2_detail.cc
alongside with minor beautifications.
Fixes all compile warnings related to signed/unsigned comparison.
port now uniformly `size_t`, in/output buffer min/max int, to keep it unified with gr::block.
Changing to size_t (which would make sense for buffer sizes) might be considered API break, so it may be 3.8 material; internally would need to add flags for unlimited/unallocated buffers, where GR uses -1 right now. Would also need changes to block_executor (since return value of general work has "magical" negative values).
=> Fixed up the int/size_t handling in hb2's new max/min_output... methods

gnuradio-runtime/include/gnuradio/types.h
This also fixes posssible misuse of types.h from places where it was
included before config.h
=> runtime: remove deprecated gr_int* types #618

gr-fec/lib/async_encoder_impl.cc
needs to be u; addresses
[Printf arg type mismatch](https://scan6.coverity.com:8443/reports.htm#v31371/p10336/fileInstanceId=27864370&defectInstanceId=9318166&mergedDefectId=746152&eventId=9318166-0)
=> fixed printf("%d", size_t)

gr-dtv/lib/dvbt2/dvbt2_framemapper_cc_impl.cc
Ron says:
>Marcus,
>Looks like a copy and paste bug. I must have copied line 1149:
> `int plen = FRAME_SIZE_SHORT - NBCH_1_4;`
>from the previous function add_l1pre().
>So the fix would be to change line 1324 to:
>`int plen = FRAME_SIZE_SHORT - NBCH_1_2;`
=> Fix: out-of-bounds memset

gr-fec/lib/async_encoder_impl.cc
int for all the things, since `generic_encoder::get*size` returns `int`, not
`size_t`.
=> gr-fec: fixed signed/unsigned comparison

gr-qtgui/lib/FrequencyDisplayPlot.cc, gr-qtgui/lib/freqdisplayform.cc, gr-qtgui/lib/timedisplayform.cc
- Fixes a problem of shown min/max in legend in QWT < 6.1.
- Initializes trigger variables.
- If tag key is set, don't ask when setting tag trigger mode.
=> qtgui: time and freq plot behavior mods.

gr-qtgui/python/qtgui/range.py
qtgui: fixes the need to use memory to store the range values. Now uses linear mapping functions. The counter box now also waits for an enter or defocus.
nsteps = (max-min)/step  + 1
The number of ticks displayed are also being adjusted to either 'nsteps' or 'min_length', which ever is less.
=> qtgui: OOM fix

gr-blocks/include/gnuradio/blocks/peak_detector2_fb.h, gr-blocks/lib/peak_detector2_fb_impl.cc, gr-blocks/lib/peak_detector2_fb_impl.h
This changes the public interface from an int to a float. But the
alpha must be between 0 and 1 for it to make any sense, so if this is
being used, it's never producing the right answer. Also, it's likely
that this change will be transparent to anyone who is trying to set
it.
=> blocks: fixed problem with setting peak detector's alpha value.

gnuradio-runtime/include/gnuradio/block.h, gnuradio-runtime/lib/flat_flowgraph.cc
Warning: this affects block.h so it will force a recompile of everything.
=> runtime: better documentation for the set min/max output buffer functions.

gr-fec/examples/CMakeLists.txt, gr-fec/examples/tpc_ber_curve_gen.grc
- install example alist file
- adds LDPC and TPC code to ber_curve_gen example
- adds example showing different performance of TPC decoder styles
=> fec: support for testing FEC codes.

gr-qtgui/examples/pyqt_example_c.py, gr-qtgui/examples/pyqt_freq_c.py, gr-qtgui/examples/pyqt_time_c.py, gr-qtgui/examples/pyqt_waterfall_c.py
Look at installation prefix/share/gnuradio/themes for the location of
the dark.qss, which was moved from being in the examples directory.
=> qtgui: fixed examples using qss theme.

gr-uhd/lib/usrp_sink_impl.cc
of 0.05s relative to usrp_source, which starts streaming 0.10s after start()
being called.
This should fix underflows when RX->TXing.
@mbr0wn said this was O.K.
Reference:
http://lists.ettus.com/pipermail/usrp-users_lists.ettus.com/2015-April/013375.html
Rob said increasing the delay on the TX side solved is "L"ate packet
issues.
=> gr_uhd: give usrp_source a headstart

gr-blocks/lib/message_strobe_impl.cc
Making the message_strobe able to cope with reconfiguration.
Ref:
http://lists.gnu.org/archive/html/discuss-gnuradio/2015-04/msg00285.html
=> Moved setting of d_finished from ctor to start()

gr-uhd/examples/python/usrp_spectrum_sense.py
Useful when scanning in a way that is likely to run slowly, doubly
so when multiple passes across the band are needed.
=> Print scan rate

gnuradio-runtime/python/gnuradio/eng_option.py
This was actually buggy, but it was also never ever used in the
current tree. Let's take it out completely. Subdev checking is
UHD specific, and changes with new devices, and shouldn't be
tracked in gnuradio-runtime.
=> base: Removed subdev as specific option type

gr-fec/lib/ber_bf_impl.cc, gr-fec/lib/ber_bf_impl.h, gr-fec/python/fec/qa_ber_bf.py
This block has a test mode. In work this gets split in 2 large if-statements. They contain a lot of duplicate code. I moved some code out of the if-statement. All the other code is almost duplicate, but It has subtle differences when calling consume_each. This should be fixed, though.
I issued this pull request in order to open a debate over this.
=> fec block 'ber_bf' needs refactoring

gr-digital/grc/digital_crc32_bb.xml, gr-digital/include/gnuradio/digital/crc32_bb.h, gr-digital/lib/crc32_bb_impl.cc, gr-digital/lib/crc32_bb_impl.h, gr-digital/python/digital/qa_crc32_bb.py
Added an option to the "Stream CRC32" block that allows operation on a stream of unpacked bytes, i.e. 0s and 1s.
The default behavior remains unchanged, the GRC block now let's you choose between "Packed" and "Unpacked". I also extended the unit tests accordingly.
As there was a wild mixture of tabs and spaces in the code, I also reformatted the code and replaced the tabs with 2 spaces.
=> crc32 unpack

gr-fec/include/gnuradio/fec/dummy_encoder.h, gr-fec/lib/dummy_encoder_impl.cc, gr-fec/lib/dummy_encoder_impl.h, gr-fec/python/fec/extended_encoder.py, gr-fec/python/fec/qa_fecapi_dummy.py
This is a reissue of pull request #554 
Added QA code to dummy_encoder to be able to test get_{input/output}_conversion.
Also added QA code to test conversions.
=> fec: fixed missing 'packed_bits' handling in extended encoder

gnuradio-runtime/python/gnuradio/gr/hier_block2.py, gnuradio-runtime/python/gnuradio/gr/qa_hier_block2.py
The current implementation catches exceptions thrown by primitive_connect() and raises a generic error. The original error message is lost. 
Now, such exceptions are no longer caught which helps with debugging. If for example the item size of source and sink doesn't match you get the original error. 
In addition, in cases where errors were caught during the endpoint handling, the original error message is appended.
Also, removed double assertion of raised exception type in corresponding qa tests.
=> runtime: stop catching errors from primitive_connect in connect decorator

gr-blocks/lib/tag_debug_impl.cc
If any input stream has tags, set toprint to true. Use this as the way
to gate printing of sout.
=> blocks: Address Issue #816.

gr-fec/include/gnuradio/fec/puncture_bb.h, gr-fec/include/gnuradio/fec/puncture_ff.h
Adds some info on the default puncture pattern of '11'.
=> fec: Address issues #757.

gr-digital/examples/berawgn.py
This is one small change and can easily be cherry-picked to either maint or master, so I'll leave that up to @jmcorgan.
=> digital: Fixed berawgn example to follow recent noise power change

gr-atsc/lib/atsci_equalizer_lms2.cc
Simple issue of a missing `fclose` on an open file handle causing a memory leak.
=> Fixes Coverity Defect 1229872: Memory leak in `atsci_equalizer_lms2` DTOR

gr-blocks/grc/blocks_block_tree.xml, gr-blocks/grc/blocks_complex_to_magphase.xml, gr-blocks/grc/blocks_magphase_to_complex.xml, gr-blocks/include/gnuradio/blocks/CMakeLists.txt, gr-blocks/include/gnuradio/blocks/complex_to_magphase.h, gr-blocks/include/gnuradio/blocks/magphase_to_complex.h, gr-blocks/lib/CMakeLists.txt, gr-blocks/lib/complex_to_magphase_impl.cc, gr-blocks/lib/complex_to_magphase_impl.h, gr-blocks/lib/magphase_to_complex_impl.cc, gr-blocks/lib/magphase_to_complex_impl.h, gr-blocks/swig/blocks_swig2.i, gr-blocks/swig/blocks_swig3.i
These blocks are generally useful, but specifically they come in handy when doing amplifier linearization, crest factor reduction, and modeling.
=> Added bidirectional conversion between complex numbers and mag/phase

gr-analog/grc/analog_sig_source_x.xml, gr-analog/lib/sig_source_X_impl.cc.t, gr-analog/lib/sig_source_X_impl.h.t, gr-analog/python/analog/qa_sig_source.py
Added message port for frequency to signal_source.
It's a new feature, so the PR is against master. Hope that's correct.
It might be debatable if the other callbacks should be integrated as well or if they deserve their own message ports. In the latter case someone who needs them may integrate them at some point.
=> analog: added freq msg port to sig_source

gr-digital/python/digital/gmsk.py
This small note might save some time for someone who want to use GMSK Mod and spend before lot of time with GMSK Demod where stream of unpacked bits (one bit per byte) is used as a output.
=> digital: clarify gmsk doc

gr-analog/include/gnuradio/analog/frequency_modulator_fc.h, gr-digital/include/gnuradio/digital/crc32_bb.h
- Better description of how the frequency modulator block behaves and
how to calculate/set the sensitivity parameter.
- Added documentation for missing parameter in crc32_bb; fixes a
Doxygen warning.
=> docs: Improving documentation (freq modulator and crc32)

gr-dtv/lib/dvbt/dvbt_ofdm_sym_acquisition_impl.cc, gr-dtv/lib/dvbt/dvbt_ofdm_sym_acquisition_impl.h
* Fix indexing error in calculating bounds for correlation
* Fix search range for correlation peak
=> dtv: fix segfault in DVB-T demod OFDM symbol acquisition

gr-blocks/examples/ctrlport/usrp_sink_controller.py, gr-blocks/examples/ctrlport/usrp_source_control.grc, gr-uhd/lib/usrp_sink_impl.cc, gr-uhd/lib/usrp_sink_impl.h
Also added an example, usrp_sink_controller.py, to excercise this
feature. Fixed up the source example, too, to better manage parsing
options and setting the UHD source block alias (defaults to 'gr uhd
usrp source0', which is the default for any flowgraph with a single
UHD source block).
=> uhd: Added controlport interface for UHD sink's "command" message handler

gnuradio-runtime/lib/controlport/thrift/gnuradio.thrift
Java String class can change data from an arbitrary byte[] object. We
use the ByteBuffer class now when passing data to ControlPort's
postMessage function, which manages the underlying data properly.
=> controlport: using the 'binary' Thrift data type to work better with Java

gr-blocks/include/gnuradio/blocks/add_const_bb.h, gr-blocks/lib/add_const_bb_impl.cc, gr-blocks/lib/add_const_bb_impl.h
this is a build breaker on gcc 4.6.3 due to incorrect interchangeable use of "char" and "unsigned char" in the block and with GRCP templates in the add_const_bb block.
=> blocks: resolve char sign ambiguity causing problems with gcc 4.9.2

cmake/Modules/GrPlatform.cmake, gr-utils/python/modtool/gr-newmod/cmake/Modules/GrPlatform.cmake
GNU Radio is looking at files on the build system to determine if it should
use the lib64 directory. This doesn't work on cross builds. Do not set
REDHAT, DEBIAN, or SLACKWARE if cross compiling.
Also fix gr-newmod so modules do the right thing.
=> Fix 64 bit OpenEmbedded builds.

gr-dtv/CMakeLists.txt, gr-dtv/examples/CMakeLists.txt, gr-dtv/examples/atsc_ctrlport_monitor.py, gr-dtv/include/gnuradio/dtv/atsc_equalizer.h, gr-dtv/include/gnuradio/dtv/atsc_rs_decoder.h, gr-dtv/include/gnuradio/dtv/atsc_viterbi_decoder.h, gr-dtv/lib/atsc/atsc_equalizer_impl.cc, gr-dtv/lib/atsc/atsc_equalizer_impl.h, gr-dtv/lib/atsc/atsc_rs_decoder_impl.cc, gr-dtv/lib/atsc/atsc_rs_decoder_impl.h, gr-dtv/lib/atsc/atsc_single_viterbi.cc, gr-dtv/lib/atsc/atsc_single_viterbi.h, gr-dtv/lib/atsc/atsc_viterbi_decoder_impl.cc, gr-dtv/lib/atsc/atsc_viterbi_decoder_impl.h
This makes a few changes to the code for speeding up a few parts.
It also adds ControlPort hooks to a few of the blocks so they can emit information and statistics about their operations. An example ControlPort application produces a crude display of this information.
=> DTV ATSC updates and ControlPort Addtions

gr-filter/lib/rational_resampler_base_XXX_impl.cc.t
We changed from using set_output_multiple(interpolate) because data
would not necessarily continue to flow through properly. This meant
that we needed to check the input size in the work function because if
we cycle through the filters, we can sometimes consume more inputs
than we've been given, which messes up the consume/produce and
bookkeeping.
It's likely that we can find a better form of the forecast function
here that does not require checking both noutput_items and
ninput_items[0] in the while loop.
=> analog: Addresses issue #831.

gr-digital/lib/pfb_clock_sync_ccf_impl.cc, gr-digital/lib/pfb_clock_sync_fff_impl.cc
If the taps are all the same value, the differential taps become NaNs
during create_diff_taps. Having this type of filter doesn't make sense
in this algorithm, so there's nothing to fix. But now, we check to see
if the diff taps are NaN and throw a runtime_error if detected.
=> digital: Addresses issue #812.

gr-uhd/grc/gen_uhd_usrp_blocks.py
The Redmine resource has been turned off. http://uhd.ettus.com is the main link to the UHD manual now.
This may be more appropriate targeted to maint as there is no functional change but fixes a dead link?
=> Updated URL to UHD manual in USRP sink and source blocks

gr-blocks/include/gnuradio/blocks/vector_sink_X.h.t, gr-blocks/lib/vector_sink_X_impl.h.t
=> blocks: vector_sink.reset() now also clears tags

gr-blocks/lib/tuntap_pdu_impl.cc, gr-blocks/lib/tuntap_pdu_impl.h
Currently the MTU passed to the TUNTAP PDU xtor is only used to tell the `stream_pdu_base` parent class how much buffer space to allocate. The current behavior leaves the tun/tap device MTU at the default size of 1500, requiring the user to manually set the MTU using `ifconfig`. The new behavior is to automatically set the MTU on the tun/tap device through an `ioctl` call. This PR fixes issue/feature #853. http://gnuradio.org/redmine/issues/853
=> blocks: fixed issue #853: set MTU on tun/tap network interface in TUNTAP PDU block xtor

gr-digital/include/gnuradio/digital/constellation_receiver_cb.h, gr-digital/lib/constellation_receiver_cb_impl.cc, gr-digital/lib/constellation_receiver_cb_impl.h, gr-digital/lib/costas_loop_cc_impl.cc
The constellation receiver controlport interface was modeled after the
costas_loop_cc block, but the inheritance of the two blocks to
control_loop was different. This changes the inheritance of
constellation_reciever_cb.
It also fixes the name of the "loop_bw" parameter to be consistent
between the set and get ControlPort interfaces.
=> digital: addresses issue #876.

gnuradio-runtime/lib/block_executor.cc
Because of the data types in use here, d_ninput_items_required can
overflow and become negative, which then causes bad addressing of the
input buffer in a block's work function. Even if we were using
unsigned types, we might still have situations of overflow; it
wouldn't crash in this case but cause wrong addressing, anyways.
We might be able to catch and handle this situation better. This fix
tests for the condition and shuts down the flowgraph with an error
message. Basically, parameters that cause this effect are well out of
bounds of what we want to handle, anyways.
=> runtime: addresses issue 768.

gr-qtgui/grc/qtgui_freq_sink_x.xml
Typo caused FFT size to not show up in properties box.
=> qtgui: fixes issue #889.

gr-digital/include/gnuradio/digital/pfb_clock_sync_ccf.h, gr-digital/include/gnuradio/digital/pfb_clock_sync_fff.h, gr-digital/lib/pfb_clock_sync_ccf_impl.cc, gr-digital/lib/pfb_clock_sync_ccf_impl.h, gr-digital/lib/pfb_clock_sync_fff_impl.cc, gr-digital/lib/pfb_clock_sync_fff_impl.h, gr-digital/python/digital/qa_pfb_clock_sync.py
The set_taps was redone a while ago to better handle the differential
taps as well as the normal ones, but this made externally resetting
them impossible. Adding a new update_taps function to properly handle
this case so as to not change the API. We should fix this in 3.8.
=> digital: addresses issue #890.

gr-analog/grc/analog_block_tree.xml, gr-analog/grc/analog_random_uniform_source_x.xml
The block was filled under "analog" - only block in that cat.
Now its under "Waveform Generators" along with the other signal sources in analog
=> analog: better block category (GRC) for random uniform source

gnuradio-runtime/include/gnuradio/block_detail.h, gnuradio-runtime/include/gnuradio/buffer.h, gnuradio-runtime/lib/block_detail.cc, gnuradio-runtime/lib/flat_flowgraph.cc
When disconnecting and reconnecting, buffers can change and new
buffers will have their item counters zeroed out. Buffers held over
will keep their current item counters at some value >> 0. In the case
of the pfb_arb_resampler of issue #713, the rate update in the
scheduler was getting confusing numbers and setting the rates to
ridiculous values. Also, tags emitted from these new blocks will have
offsets meaningless to the other blocks that held on to their buffers.
This patch tells the scheduler to reset all buffer item counters (read
and write) to 0 when connections are merged. So upon a lock/unlock and
reset event, all buffers' counters are reset.
=> runtime: addresses issue #713.

gnuradio-runtime/lib/flat_flowgraph.cc, gr-blocks/python/blocks/qa_block_behavior.py, gr-filter/lib/pfb_decimator_ccf_impl.cc, gr-filter/lib/pfb_decimator_ccf_impl.h
Adds a feature where the max_noutput_items is always set for a block by the scheduler based on its own calculations, even if a user didn't explicitly call it.
Uses this new feature to pre-allocate FFT buffers in the PFB decimation filters in start instead of requiring a malloc every call to work.
=> Set max noutput items

gnuradio-runtime/include/gnuradio/block.h
Append to set_history Documentation in which way the first history samples are initialized. Otherwise its unclear and relies on testing of the user.
=> gnuradio-runtime: append docs to set_history regarding initialization

gr-analog/lib/CMakeLists.txt, gr-analog/lib/frequency_modulator_fc_impl.cc, gr-analog/lib/frequency_modulator_fc_impl.h
Change cmake file to allow ControlPort even for static library builds.
=> analog: add ControlPort interfaces to frequency_modulator block.

gr-channels/lib/fading_model_impl.cc, gr-channels/lib/flat_fader_impl.cc
If I see that correctly, the rayleigh fader
- uses only K-1 sinusoids
- and normalizes the power to K-1/K *2 instead of 1
I think that a power level of 1 is also assumed when weighing NLOS and LOS components.
=> Rayleigh fading

gr-qtgui/grc/qtgui_freq_sink_x.xml, gr-qtgui/include/gnuradio/qtgui/FrequencyDisplayPlot.h, gr-qtgui/include/gnuradio/qtgui/freq_sink_c.h, gr-qtgui/include/gnuradio/qtgui/freq_sink_f.h, gr-qtgui/include/gnuradio/qtgui/freqdisplayform.h, gr-qtgui/lib/FrequencyDisplayPlot.cc, gr-qtgui/lib/freq_sink_c_impl.cc, gr-qtgui/lib/freq_sink_c_impl.h, gr-qtgui/lib/freq_sink_f_impl.cc, gr-qtgui/lib/freq_sink_f_impl.h, gr-qtgui/lib/freqdisplayform.cc
- Useful if the input device is calibrated and one wants to display Power (dBm) rather than Relative Gain (dB)
=> qtgui: Added the ability to control the Y axis label for the freq sink

gr-utils/python/modtool/modtool_add.py, gr-utils/python/modtool/templates.py
Maybe this option would be nice to have to add one's name with gr_modtool instead manually or with sed. Since we are using templates anyway we can give an option. Fallback is current behaviour, maybe an interactive behaviour is also desirable?
=> gr-utils: modtool: add option --copyright to add author name

cmake/Modules/GrVersion.cmake
cmake: when not release and no GIT_EXECUTABLE nad not .git directory in the archive, allow external overriding of version info via GR_GIT_COUNT and GR_GIT_HASH, similar to what UHD allows.
=> cmake: allow partial version info external overriding

gr-qtgui/lib/time_sink_c_impl.cc, gr-qtgui/lib/time_sink_f_impl.cc
When this was looking at the very end of the buffer, the +1 was a
look-ahead based on history; but this would then become the 0th
element the next call to work and would double up on that tag.
=> qtgui: fixed a stray +1 that was duplicating tags.

cmake/Modules/FindThrift.cmake
Using the same logic we do for finding the native python binary.
=> cmake: cmake should get native thrift binary when cross compiling.

gr-utils/python/modtool/modtool_rename.py
The `gr_modtool rename` command attempts to move GRC XML files based on block name, however the files have the module name prefixed, and attempts to rename the wrong files. This fixes that.
=> gr_modtool: correctly rename GRC files

gr-analog/lib/sig_source_X_impl.cc.t, gr-analog/lib/sig_source_X_impl.h.t
Uses same message structure as the UHD command and the QTGUI freq and
waterfall sinks of the key:value pair where the key must be
"freq".
Also does proper type checking on the PMT.
=> analog: Adds ability to set the sig_source frequency using a key:value pair.

gr-filter/include/gnuradio/filter/firdes.h, gr-filter/lib/firdes.cc
Firdes docs (parameters) don't look so hot, so this fixes up formatting and moves some language around. Also, fixes a couple of errors in the docs (missing bt parameter for gaussian, and cutoff specificed as center or beginning of low_pass_2) .
Since I was already mucking with formatting of the docs I took some liberties with whitespace on the declarations as well.
=> Filter docs

gr-fft/lib/CMakeLists.txt, gr-fft/lib/fft.cc
Always use volk_malloc and free, never fftwf_malloc/free, because it might not be built with AVX support which will cause alignment faults when these buffers are fed in to VOLK.
=> Fft avx alignment

gnuradio-runtime/include/pmt/pmt.h
This is pretty minor, but both pmt::is_dict() and pmt::is_pair() return true for both dictionaries and pairs. This causes issues as one may believe they have a dictionary pmt and attempt to reference it's keys (which will throw an exception for a pair). This just documents this behavior.
An example demonstrating this and an in-tree example of a fix can be found here: http://lists.gnu.org/archive/html/discuss-gnuradio/2016-03/msg00269.html
=> PMT dictionary/pair type checking issue

docs/exploring-gnuradio/fm_tx.grc, gr-analog/examples/fmtest.py, gr-analog/grc/analog_fm_preemph.xml, gr-analog/grc/analog_nbfm_tx.xml, gr-analog/grc/analog_wfm_tx.xml, gr-analog/python/analog/fm_emph.py, gr-analog/python/analog/nbfm_tx.py, gr-analog/python/analog/wfm_tx.py, gr-filter/examples/synth_to_chan.py, gr-uhd/examples/python/fm_tx4.py
This change set reworks the FM deemphasis and and preemphasis IIR filters.  It should address Issue #857.
I have examined the resulting filter curves in octave and gnuradio (using a noise source and QT freq sink) and the characteristics appear to be OK.  The demphasis exactly cancels the preemphasis, except at the very high frequencies at and above the high corner frequency fh of the preemphasis filter, as expected.
I did not rigorously verify the +/- 6 dB/octave slopes, nor did I listen to actual FM audio through the filters.  There should be enough information in the comments for anyone to verify the bilinear transformation algebra.
I have added new properties to GRC blocks that may break existing FM Tx flowgraphs (potentially undefined value for the fh property in a few blocks' XML …
=> Issue #857 FM emphasis filters

gr-digital/lib/correlate_access_code_bb_ts_impl.cc, gr-digital/lib/correlate_access_code_ff_ts_impl.cc
Fixes the mask used in the correlate_access_code_XX_ts blocks to use the access_code_length least significant bits instead of most significant bits.
=> digital: fix access code mask in correlate_access_code_XX_ts

gr-blocks/include/gnuradio/blocks/head.h, gr-blocks/lib/head_impl.h
This fixes that and makes the type consistent with d_nitems (uint64_t).
=> Head block nitems setter was 'int' and fails for items larger than 2^31

gr-utils/python/modtool/gr-newmod/CMakeLists.txt, gr-utils/python/modtool/gr-newmod/cmake/Modules/GrMiscUtils.cmake
Previously template expansion failed for OOT modules due to incorrectly configured python paths. The expansion would attempt to find build_utils.py and fail. This fix adds this path to the pythonpath during build, and also makes a larger change of truly defaulting to use the in-OOT-module CMake modules in <modpath>/cmake/Modules as opposed to the default ones installed with GR.
I believe this was the intention all along due to this comment https://github.com/gnuradio/gnuradio/blob/master/gr-utils/python/modtool/gr-newmod/CMakeLists.txt#L34 however the in the process of finding the GR package (https://github.com/gnuradio/gnuradio/blob/master/gr-utils/python/modtool/gr-newmod/CMakeLists.txt#L114) the default CMake module path (<prefix>/lib/cmake/gnuradio) gets higher priority. 
This fix …
=> Updated gr_modtool CMake files to properly handle template expansion

gr-utils/python/modtool/modtool_rename.py
same changes as in #778, but in a single commit and based off `maint`
=> gr_modtool rename: fix description and alias

gr-digital/python/digital/qa_burst_shaper.py
Burst shaper QA tests previously added tailing input to compensate for incorrect forecasting when inserting zero padding and/or phasing samples at the end of a burst. Commit 3931987 fixed the forecasting behavior. The current commit removes the tailing input and properly tests full burst handling. It also adds a brief description to each QA test.
=> digital: fixes burst shaper QA tests to exercise full burst handling

gr-utils/python/modtool/gr-newmod/CMakeLists.txt
Makes the OOT module's default CMake install the module to the PyBOMBS install prefix if defined.  I found that without specifying this on the command line, the default PyBOMBS GNU Radio install won't find your OOT modules.
=> Install OOT modules to PyBOMBS prefix if defined

gr-uhd/grc/gen_uhd_usrp_blocks.py
Fixes http://gnuradio.org/redmine/issues/917
=> Set samp rate before setting time source; avoiding auto-MCR pitfall.

gr-digital/grc/digital_header_payload_demux.xml, gr-digital/include/gnuradio/digital/header_payload_demux.h, gr-digital/lib/header_payload_demux_impl.cc, gr-digital/lib/header_payload_demux_impl.h, gr-digital/python/digital/qa_header_payload_demux.py
- Added padding feature (trigger/tag can now be off by some items)
- Payload offset can also be specified
- Fixed some index counting bugs
- More and better unit tests, cleaned up the unit test file
- Cleanups:
- Consistent whitespace
- Consistent use of size_t and other types
- Used more enums where it increases readability
=> digital: Major update to header/payload demuxer (HPD)

gnuradio-runtime/lib/vmcircbuf_prefs.cc, gr-fft/lib/fft.cc
The  following error messages occurs In Windows XP/7/8
:Invalid argument
:Invalid argument
:Invalid argument
The reason  is that 
return path.string().c_str();   // return invalid pointer in Windows XP/7/8
=> runtime: fixed dangling pointer returns in vmcircbuf_prefs.cc and fft.cc

gr-uhd/lib/usrp_source_impl.cc, gr-uhd/lib/usrp_source_impl.h
@mbr0wn this is useful for allowing downstream blocks to do a sanity check that they are still on the time that they think they are on. There's some code style opinions here that you may care about.
Also, you *could* argue that this isn't entirely necessary; however, it's nice for other flowgraphs receiving samples over pub/sub zmq or UDP socket PDU  to be able to have a periodic reminder that the stream is or is not on what they think it is.
=> uhd: add command handler to add a time tag

gnuradio-runtime/apps/gnuradio-config-info.cc, gnuradio-runtime/include/gnuradio/sys_paths.h, gnuradio-runtime/lib/prefs.cc, gnuradio-runtime/lib/sys_paths.cc
To more easily debug gr::prefs issues, added
```
Program options: gnuradio-config-info [options]:
...
--userprefsdir        print GNU Radio user preferences directory
--prefs               print GNU Radio preferences
```
Also, unified setting of user conf dir
=> gr::prefs: user conf dir unified, gnuradio-config-info "--prefs"

CMakeLists.txt, cmake/Modules/GnuradioConfig.cmake.in
The projects using GnuradioConfig.cmake (by doing "find_package(Gnuradio)" in CMake) failed to detect the various GNU Radio components if GNU Radio was installed in a non-standard prefix.
This set of two commits address this issue.
Signed-off-by: Paul Cercueil <paul.cercueil@analog.com>
=> Detect GNU Radio components installed in a non-standard prefix

gr-utils/python/modtool/grc_xml_generator.py, gr-utils/python/modtool/templates.py
This adds basic support for the recently merged modules in the GRC block tree - namely decorating the root category with square brackets.
It would be nice to have a 'default GRC category' option in the CLI. But this requires to store the info between runs of modtool newmod and e.g. add, which AFAIK is not possible at the moment!?
=> modtool: add basic support for GRC modules in block tree

gnuradio-runtime/include/gnuradio/block_gateway.h
Please excuse the fact that this is far from the comprehensive wrapping check we should be doing.
Fixes the acute issue of http://stackoverflow.com/questions/37870987/gnuradio-set-minimum-input-output-buffer-size-for-a-python-block
=> added set_min_output_buffer call, as that seems to be in particular demand

gnuradio-runtime/examples/network/audio_source.py, gnuradio-runtime/examples/network/dial_tone_source.py, gnuradio-runtime/examples/network/vector_source.py
Fixes issue where the pair examples (network***sink and network***source) does not work together.
localhost might be resolve to ::1 on IPv6 enabled hosts, but the client is listening only on 0.0.0.0 (IPv4) addresses.
PS: It would be much nicer solution to honor udp_source documentation and listen on ALL interfaces when no address is specified, instead of just not listening at all. I might try to fix this latter.
=> examples: enforce IPv4 in all example addresses

gr-utils/python/modtool/modtool_add.py, gr-utils/python/modtool/templates.py
Collision of formating for template engine and local Python string formating
File "/usr/local/lib/python2.7/dist-packages/gnuradio/modtool/templates.py", line 45, in <module>
'''.format(datetime.now().year)
KeyError: 'copyrightholder'
For the second patch, function get_template() does not exists, regular solution would be rendering the template using teplate engine but this is too cumbersome.
=> modtool: fix template - copyrightholder field, and add_module

gnuradio-runtime/include/gnuradio/basic_block.h, gnuradio-runtime/include/gnuradio/tpb_detail.h, gnuradio-runtime/lib/basic_block.cc, gnuradio-runtime/lib/block.cc, gnuradio-runtime/lib/tpb_thread_body.cc, gr-blocks/lib/pdu_to_tagged_stream_impl.cc, gr-blocks/python/blocks/qa_pdu.py
This is supposed to address [Issue #797](http://gnuradio.org/redmine/issues/797), which is about shutting down run-to-completion flow graphs as used in simulations and unit tests.
The point is that the current code does not allow to stop blocks through the message port if it has at least on stream port. This policy is implemented in [block.cc](https://github.com/gnuradio/gnuradio/blob/d13de2faffc6e9c50d353e1c3567d688b326b805/gnuradio-runtime/lib/block.cc#L753). I don't know whether this was a deliberate decision, but it's at least unexpected that this is not supported.
I think it would make sense to allow at least blocks that have only message port inputs to be shut down via the message port. (Note that blocks with a stream output are only shut down if they received a *done* message and …
=> Termination of run-to-completion flow graphs

gr-filter/examples/benchmark_filters.py
Code calls filter from filter module which is not imported.
Looks like nobody used it for loooong time. I'm goign trought examples and I have suspicion lot of them is not much usefull (too complicated for start, too much examples to pick up from, not well maintained).
Any hint how to improve this?
=> filter: add missing import of filter

gr-analog/lib/fmdet_cf_impl.cc
Bug reported on-list. Current code actually results in the S1 terms simply
canceling each other, whereas the second term should be S2.
=> Fixing `Sdot` calculation in `fmdet_cf_impl` `work()`

docs/sphinx/source/blocks_blocks.rst, docs/sphinx/source/index.rst, gr-blocks/grc/blocks_block_tree.xml, gr-blocks/grc/blocks_tcp_server_sink.xml, gr-blocks/include/gnuradio/blocks/CMakeLists.txt, gr-blocks/include/gnuradio/blocks/tcp_server_sink.h, gr-blocks/lib/CMakeLists.txt, gr-blocks/lib/tcp_server_sink_impl.cc, gr-blocks/lib/tcp_server_sink_impl.h, gr-blocks/python/blocks/qa_tcp_server_sink.py, gr-blocks/swig/blocks_swig5.i
This is TCP server sink. It listen on specified port for incoming connections. It duplicates data if multiple client is connected. It have 2 modes, in blocking mode it waits and block data processing till first client connects. Non blocking mode is useful in real-time applications, it process data even when no client is connected.
Question is whatever to start blocking when last client disconnects when the TCP server is in blocking mode.
=> TCP server sink with multiple host and no-blocking capability

CMakeLists.txt, cmake/Modules/GrMiscUtils.cmake, gnuradio-runtime/CMakeLists.txt, gnuradio-runtime/include/gnuradio/CMakeLists.txt, gnuradio-runtime/include/gnuradio/logger.h, gnuradio-runtime/lib/logger.cc, gnuradio-runtime/lib/qa_logger.cc, gnuradio-runtime/lib/tpb_thread_body.cc, gnuradio-runtime/swig/CMakeLists.txt, gr-fec/lib/generic_decoder.cc, gr-fec/lib/generic_encoder.cc, gr-utils/python/modtool/gr-newmod/cmake/Modules/GrMiscUtils.cmake
This branch removes all the conditionalization around the logging features of gnuradio-runtime and enables logging permanently.  It also now makes liblog4cpp a dependency for GNU Radio.
=> Enable logging permanently and require liblog4cpp

gr-filter/grc/filter_fractional_resampler_xx.xml, gr-filter/include/gnuradio/filter/fractional_resampler_cc.h, gr-filter/include/gnuradio/filter/fractional_resampler_ff.h, gr-filter/lib/fractional_resampler_cc_impl.cc, gr-filter/lib/fractional_resampler_cc_impl.h, gr-filter/lib/fractional_resampler_ff_impl.cc, gr-filter/lib/fractional_resampler_ff_impl.h
Resulting from recent discussion on the list, I added a message port for dict messages to set parameters `resamp_ratio` and `mu` in the fractional resampler block. If wanted, other blocks can be extended in the same way.
=> filter: add msg port to set params in fractional resampler

gnuradio-runtime/include/gnuradio/basic_block.h
If these functions are supposed to be purely abstract and have to be implemented by every child class, it might be cleaner to enforce it during compile time instead of throwing exceptions during run time.
=> runtime: make abstract functions abstract

gr-uhd/apps/uhd_siggen_gui
UHD_SIGGEN_GUI is never showing if the LO is locked. It was traced down to this assignation that was leading to an Attribute error (which is avoided at the try/except at line 266).
=> uhd_siggen_gui: fix attribute error for lo_locked

gr-blocks/grc/blocks_pdu_filter.xml, gr-blocks/grc/blocks_pdu_remove.xml, gr-blocks/grc/blocks_pdu_set.xml, gr-blocks/include/gnuradio/blocks/pdu_filter.h, gr-blocks/include/gnuradio/blocks/pdu_remove.h, gr-blocks/include/gnuradio/blocks/pdu_set.h, gr-blocks/lib/pdu_filter_impl.h, gr-blocks/lib/pdu_remove_impl.h, gr-blocks/lib/pdu_set_impl.h
Added public setters for the PDU metadata manipulation blocks pdu_filter, pdu_remove, and pdu_set and callbacks in associated GRC files. Also changed 'inversion' parameter of PDU filter GRC from an enum to bool so it can be assigned to a variable in GRC.
=> Addition of PDU block setters and GRC callbacks

gr-utils/python/modtool/gr-newmod/docs/doxygen/doxyxml/doxyindex.py, gr-utils/python/modtool/gr-newmod/docs/doxygen/swig_doc.py
I noticed docstrings are created differently for in-tree and out-of-tree modules. Since the docstrings for in-tree modules are more extensive, It would be nice to also have the same structure for OOTs.
NOTE: The changed files are just copied from the global docs folder. @skoslowski stated it could be sensible to use symlinks here. Would this work or potentionally break anything?
=> modtool: update python docstring generation

cmake/msvc/config.h, gnuradio-runtime/lib/sys_paths.cc, gr-audio/lib/portaudio/portaudio_sink.cc, gr-audio/lib/portaudio/portaudio_source.cc, gr-digital/lib/pfb_clock_sync_fff_impl.cc, gr-fec/include/gnuradio/fec/polar_decoder_common.h, gr-fec/lib/polar_decoder_common.cc
Misc windows fixes and other issues when updating to v3.7.10. Comments are in the commit messages, and individual commits can easily be cherry picked if need be. The userconf_path() issue looks like it could cause some undefined behaviour. Don't let that one go.
A VC14 [PothosSDR windows installer](https://github.com/pothosware/PothosSDR/wiki/GNURadio) is available with v3.7.10 grc, gr-drm, gr-rds, gqrx, gr-osmosdr. Initial testing appears to be fine. Please let me know if there are any issues with the installer or questions about the patches. Thanks!
=> v3.7.10 win+misc fixes

gr-blocks/grc/blocks_block_tree.xml, gr-blocks/grc/blocks_message_burst_source.xml, gr-blocks/grc/blocks_message_sink.xml, gr-blocks/grc/blocks_message_source.xml, gr-blocks/include/gnuradio/blocks/message_burst_source.h, gr-blocks/include/gnuradio/blocks/message_sink.h, gr-blocks/include/gnuradio/blocks/message_source.h
Old-style message queue blocks are going to be removed in the 3.8 series as the current asynchronous messaging system is a superset of them.  This branch marks them deprecated in GRC.
=> blocks: mark old-style message queue blocks as deprecated

gr-digital/grc/digital_block_tree.xml, gr-digital/grc/digital_correlate_and_sync_cc.xml, gr-digital/include/gnuradio/digital/correlate_and_sync_cc.h
This branch deprecates the gr::digital::correlate_and_sync block, which is replaced by the corr_est block
=> digital: deprecate correlate_and_sync

gr-analog/grc/analog_block_tree.xml, gr-analog/grc/analog_cpfsk_bc.xml, gr-analog/include/gnuradio/analog/cpfsk_bc.h, gr-digital/grc/digital_block_tree.xml, gr-digital/grc/digital_dxpsk_demod.xml, gr-digital/grc/digital_dxpsk_mod.xml, gr-digital/grc/digital_mpsk_receiver_cc.xml, gr-digital/grc/digital_psk_demod.xml, gr-digital/grc/digital_psk_mod.xml, gr-digital/grc/digital_qam_demod.xml, gr-digital/grc/digital_qam_mod.xml, gr-digital/include/gnuradio/digital/mpsk_receiver_cc.h
Retrying #813 with modulation blocks only
=> Mark mod blocks for 3.8 deprecation

gr-uhd/lib/CMakeLists.txt, gr-uhd/swig/CMakeLists.txt
Boost_INCLUDE_DIRS could previously "undo" UHD_INCLUDE_DIRS if it
pointed to the same location as a UHD installation that was *not*
selected via UHD_INCLUDE_DIRS.
=> uhd: Fix order of include dirs

gr-qtgui/lib/FrequencyDisplayPlot.cc
Next to the cursor in the QT GUI Frequency Sink, the Y axis unit label (usually
dB) is shown instead of the X axis label (kHz, MHz etc).
(2nd try)
=> qtgui: Fix bug in trackerText for Frequency Sink

gr-qtgui/include/gnuradio/qtgui/freqcontrolpanel.h, gr-qtgui/lib/freqcontrolpanel.cc, gr-qtgui/lib/freqdisplayform.cc
The Axis Labels checkbox in the Control Panel for the Frequency Sink did not
synchronize its state with settings in other parts of the block, like initial
settings and center mouse button menu.
=> qtgui: Fix Axis Labels checkbox Control Panel checkbox sync issue

gr-qtgui/include/gnuradio/qtgui/freqcontrolpanel.h, gr-qtgui/lib/freqcontrolpanel.cc, gr-qtgui/lib/freqdisplayform.cc
The FFT average slider in the control panel was not updated when the FFT
average value changed in other parts of the Frequency Sink block.
=> qtgui: Fix control panel FFT average slider value sync in frequency sink

gr-uhd/lib/usrp_source_impl.cc, gr-uhd/lib/usrp_source_impl.h
For most cases, the zero-timeout call will just return empty buffers,
resulting in extra overhead.
=> uhd: Replace zero-timeout double-recv() with one recv() call

gr-qtgui/lib/VectorDisplayPlot.cc
```
[ 79%] Building CXX object gr-qtgui/lib/CMakeFiles/gnuradio-qtgui.dir/VectorDisplayPlot.cc.o
/home/koslowski/code/gnuradio_build/gr-qtgui/lib/VectorDisplayPlot.cc: In member function ‘void VectorDisplayPlot::setXAxisValues(double, double)’:
/home/koslowski/code/gnuradio_build/gr-qtgui/lib/VectorDisplayPlot.cc:301:3: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
if((start != d_x_axis_start) || (step != d_x_axis_step))
^~
/home/koslowski/code/gnuradio_build/gr-qtgui/lib/VectorDisplayPlot.cc:304:5: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’
d_x_axis_start = start;
^~~~~~~~~~~~~~
```
=> qtgui: whitespace fix (gcc warning "misleading-indentation")

gnuradio-runtime/lib/flat_flowgraph.cc, gnuradio-runtime/python/gnuradio/gr/qa_flowgraph.py
This refers to a bug reported on the [mailing list](http://lists.gnu.org/archive/html/discuss-gnuradio/2016-09/msg00136.html).
AFAIS, the problem appears when a flow graph is locked and new blocks with message ports are created before unlock(). These new message ports seem to never get connected.
This patch adds the code to connect the message ports to merge_connections(), which is called for the new flow graph instead of setup_connections().
=> runtime: connect message ports before unlock()

grc/gui/ActionHandler.py, grc/gui/Block.py, grc/gui/Constants.py, grc/gui/FlowGraph.py, grc/gui/PropsDialog.py, grc/gui/Utils.py
This is an attempt to fix the GRC flowgraph display for high DPI displays with display scaling != 1
Right now, increasing the display scaling increases the font size on the canvas, but results in all of the blocks overlapping. This scales the coordinates of blocks to match their increase in size.
The result is not perfect - arrow heads and the grid size don't get scaled. 
I consider this a bug fix, but I really want this tested thoroughly, get other people take before we go off merge it.
=> grc: respect display scaling for block positions, canvas size and props dialog

gr-filter/lib/pfb_arb_resampler_ccc_impl.cc, gr-filter/lib/pfb_arb_resampler_ccf_impl.cc, gr-filter/lib/pfb_arb_resampler_fff_impl.cc
This reverts b20df754b45db9b330c3876814b2570167aba441
The work function of theses uses the relative_rate() to predict how much
to consume/produce. And this works fine if you use the exact rate
that's configured. But you can't let the executor update it with automatic
estimations.
Signed-off-by: Sylvain Munaut <tnt@246tNt.com>
=> gr-filter: Fix pfb_arb_resampler producing more samples than allowed

gr-digital/lib/msk_timing_recovery_cc_impl.cc
Just warn and ignore. I put the warn in there to annoyingly remind us to fix the corr_est block so it doesn't do this.
=> msk_timing_recovery_cc: ignore (and warn) on time_est outside of (-1.0, 1.0)

gnuradio-runtime/lib/constants.cc.in
Support a "GR_PREFIX" env var to overload prefix() with. When this env var is specified, sysconfdir() and prefsdir() also changes to reflect this using the same directory logic specified in the top level CMakeLists.txt Behaviour is unchanged when the GR_PREFIX environment variable is not specified.
The goal is to support relocated installs, for example when using ubuntu snap packages. We currently have [packages for GQRX and GRC](https://myriadrf.org/blog/snap-packages-limesdr/) that rely on this. I was using a similar change [mentioned here](https://github.com/pothosware/gnuradio/issues/22) for the  windows installer. Let me know if this works or I can make a similar change. I would love to have a feature like this in the upstream.
=> runtime: support dynamically located gnuradio installs

cmake/Modules/FindQwt.cmake
=> FindQwt.cmake: Add search path from Qwt5 on Fedora 24.

cmake/Modules/FindQwt.cmake
For me, this fixes https://github.com/gnuradio/gnuradio/issues/1059. I think the problem is that cmake preferred qwt-qt4 over qwt-qt5.
It's not perfect since cmake doesn't assure that QT and QWT are compatible, but it should at least prefer the correct version.
=> cmake: qwt prefere correct version

gr-qtgui/python/qtgui/util.py.cmakein
With QT5, the qApp seems to be part of QtWidgets. The PY_QT_IMPORT macro is already prepared for that, but seemingly utils.py was not updated.
=> qtgui: fix stylesheet for qt5

grc/gui/ActionHandler.py, grc/gui/Block.py, grc/gui/Constants.py, grc/gui/FlowGraph.py, grc/gui/PropsDialog.py, grc/gui/Utils.py
(same as prematurely merged #1064)
This is an attempt to fix the GRC flowgraph display for high DPI displays with display scaling != 1
Right now, increasing the display scaling increases the font size on the canvas, but results in all of the blocks overlapping. This scales the coordinates of blocks to match their increase in size.
The result is not perfect - arrow heads and the grid size don't get scaled.
I consider this a bug fix, but I really want this tested thoroughly, get other people's take before we go off merge it.
=> grc: respect display scaling (reopened)

grc/gui/Param.py, grc/gui/Utils.py, grc/gui/VariableEditor.py
In addition to #1074 , some column widths (variable names, parameter names in block props, etc.) are hard-coded. This change multiplies these values with the applied scaling.
=> grc: fix column widths on dpi scalings != 1

gr-digital/lib/mpsk_receiver_cc_impl.cc
Adds a warning during constructor time when the block is used.  A previous commit has already changed the API header file and XML file for deprecation.
=> digital: add constructor warning for deprecated mpsk_receiver_cc

docs/doxygen/Doxyfile.in, docs/doxygen/Doxyfile.swig_doc.in, gr-utils/python/modtool/gr-newmod/docs/doxygen/Doxyfile.in, gr-utils/python/modtool/gr-newmod/docs/doxygen/Doxyfile.swig_doc.in
"The items XML_SCHEMA and XML_DTD are not used and there is no plan
for using them, so declared obsolete."
-- Ddoxygen commit ba31ee73aad3bdc6b3854add2db01c302c9cf19c
This patch reduces noise about obsolete settings from Doxygen.
=> docs: remove obsolete doxygen XML tags

gr-audio/lib/windows/windows_sink.cc, gr-audio/lib/windows/windows_source.cc
Windows audio sinks/source are referencing the logger type, not the d_logger object. Didn't fail because not currently using log4cpp in MSVC build, but will be in the future.
Sink fix could be put in maint, but source is only in master, so pulling in that direction.
=> gr-audio: windows audio using incorrect logger syntax

grc/core/Block.py, grc/core/utils/epy_block_io.py
@skoslowski 
Currenty, embedded Python blocks don't support vector types. For instance, if you put `in_sig=[(np.complex64, 16)]` in your Python code, the following error occurs:
```
File "/home/argilo/pybombs/lib/python2.7/dist-packages/gnuradio/grc/core/Block.py", line 465, in update_ports
for key, port_type in port_specs:
ValueError: too many values to unpack
```
This patch adds support for vector types, hopefully without breaking anything else.
=> Support vector types in embedded Python blocks.

gnuradio-runtime/lib/pmt/pmt.cc, gnuradio-runtime/lib/pmt/pmt_int.h
Made some copy paste errors in the #if guards to support the old boost version, resulting in a silent failure towards the old code.  Thanks to @bastibl for pointing this out earlier.
=> pmt: Fixing #if boost version checks in pmt_t.

gr-uhd/apps/uhd_app.py, gr-uhd/apps/uhd_fft
Currently uhd_app resolves channel indices to real channel numbers and hands them down to usrp_{source,sink}. This causes issues if one leaves out channels in between (e.g. --channels 0,2,3) or does not use channel 0 as the first channel (e.g. --channels 1).
Then usrp_{source, sink} tries to access the array of channel numbers with the already resovled channel numbers and in the mentioned cases above it will access random memory. 
This can be reproduced by calling `uhd_fft -f 1e9 --channels 1` if a two channel capable USRP is connected.
This PR modifies the use of channel numbers in uhd_app and fixes remaining issues in uhd_fft. There might be some more apps where this is used incorrectly.
=> gr-uhd: channel numbers are resolved in usrp_block, work with indices in uhd_app

grc/core/utils/epy_block_io.py
@skoslowski
This is a follow-up to https://github.com/gnuradio/gnuradio/pull/1118.
I noticed that every time I save an embedded Python block, its message ports get disconnected. This is because I was passing a vector length of `None`, which caused this comparison to fail:
https://github.com/gnuradio/gnuradio/blob/d4a3e0267c32912f234f5c59fc567982958e96e8/grc/core/Block.py#L469
I've changed that to 1 (as you had your your patch https://github.com/skoslowski/gnuradio/commit/685d0fd401b2aca9df38527dcfbacce3f0d11552), which solves the problem.
=> grc: Use vlen=1 for message blocks so they don't randomly disconnect.

gnuradio-runtime/lib/pmt/pmt.cc, gnuradio-runtime/lib/pmt/pmt_int.h
(The last pull request got closed out when I deleted the old branch to make a cleaner PR.)
=> pmt: Removing support for boost < 1.53 in ~pmt_t

cmake/Modules/GrBoost.cmake
Conditional inclusion of atomic and chrono so that they will be linked under windows, but not bump the minimum boost for other platforms. Comments left in the code to update this when the boost requirement is bumped.
* Conversation for reference: https://github.com/gnuradio/gnuradio/commit/8f590d7bfaa22a42ccb2392f9822206ed003c82a#commitcomment-20126078
=> cmake: atomic and chrono for BOOST_REQUIRED_COMPONENTS

gr-uhd/doc/uhd.dox
Following up on
https://lists.gnu.org/archive/html/discuss-gnuradio/2016-12/msg00140.html
=> example code: pmt::dict_add doesn't modify; returns new pmt_t

gr-uhd/lib/usrp_sink_impl.cc, gr-uhd/lib/usrp_source_impl.cc
This PR fixes an issue with multi-channel RX and probably TX. Where the scheduler kills the work thread while uhd still is updating the transport buffers. This can result in a bad state and crashes the application during new recv() calls in flush().
The disable_interruption object guards the recv() and send() calls from being interrupted.
=> gr-uhd: disable boost thread interrupts during send() and recv() calls in work

gnuradio-runtime/lib/hier_block2_detail.cc
This PR addresses issue #1110 by including logic to call setup_rpc() on blocks that only have message port connections. It now operates over all blocks.
This is a continuation of PR https://github.com/gnuradio/gnuradio/pull/1113, which was closed in error, not exactly sure what happened. Sorry.
=> ControlPort: Start RPC on all blocks (including those that only have message connections)

gnuradio-runtime/swig/tags.i
gnuradio-runtime/swig/tags.i -- Old code use to spit out swig operator= warning messages whenever building anything that included gnuradio.i; new code fixes that.
Attempt #2 with a proper repo base...
=> gnuradio-runtime/swig/tags.i: Fix swig operator= warning messages

grc/gui/external_editor.py
I seems tempfile.NamedTemporaryFile() can not be used under windows for our use-case. Keeping a handle around locks the file for writing. So, we close the the handle after the initial write and delete the file manually.
Also enforcing utf-8 encoding on those files.
=> grc: fix file monitor on windows (#1169)

gr-atsc/CMakeLists.txt, gr-dtv/CMakeLists.txt
Bug Fix:  adds find_package(GSL) to atsc/dtv cmake packages so GSL will be detected.  Mirrors gr-fec and gr-wavelet
=> gr-atsc/dtv: Adds missing find_package for GSL

grc/core/Port.py, grc/core/generator/Generator.py
This fixes #1166. I went ahead and did a rewrite of the type/vlen resolution code, that was planned for 3.8. Additional/new features like resolving through bypassed ports will be continued on next.
Along the way I found that the "Wildcard" setting for pad block didn't work and fixed that, too.
=> Virtual connection with multiple upstream connections (messages) and Wildcard pad

gr-blocks/lib/peak_detector2_fb_impl.cc, gr-blocks/lib/peak_detector_XX_impl.cc.t, gr-dtv/lib/dvbt/dvbt_ofdm_sym_acquisition_impl.cc
The initialization with `int val = -(int)INFINITY;` works for me on Linux, but not on my mac.
```
basti@tronn ~/sync >> cat foo.c 
#include <iostream>
#include <math.h>
int main() {
int i;
i = -(int)INFINITY;
std::cout << "value: " << i << std::endl;
return 0;
}
basti@tronn ~/sync >> g++ -o foo foo.c
basti@tronn ~/sync >> ./foo 
value: 108650432
basti@tronn ~/sync >> ./foo 
value: 44863424
basti@tronn ~/sync >> ./foo 
value: 241270720
```
This patch uses `std::numeric_limits`, which AFAIS is part of C++98.
The changes for floats are not strictly required. I think float are the special case where `float foo = -(float)INFINITY;` works, but maybe it's nicer.
=> blocks: peak detector fix initial value

gr-analog/grc/analog_probe_avg_mag_sqrd_x.xml
Allows GRC users to choose the probe average mag squared block with float output in GRC. When using the standard `probe_avg_mag_sqrd_c` and `probe_avg_mag_sqrd_f` blocks, the output port is automatically hidden and set to optional to allow for no connection. When using `probe_avg_mag_sqrd_cf`, the output port is displayed on the GRC canvas. Currently the XML parser evaluates all `<optional>` tags to `True`, so the required output connection for the `_cf` block is not enforced. However, #1200 adds cheetah template parsing for `<optional>` tags on ports, which will allow the required output connection to be enforced.
=> analog: add missing probe_avg_mag_sqrd_cf block to GRC definition

gnuradio-runtime/lib/controlport/CMakeLists.txt, gnuradio-runtime/python/gnuradio/ctrlport/CMakeLists.txt
by converting EXECUTE_COMMAND directives to add_custom_command with
well-defined OUTPUT.
This is all that was necessary to make GNU Radio build with Ninja in
place of GNU Make.
=> Helped CMake maintain a clear dependency tree

gr-uhd/lib/usrp_source_impl.cc, gr-uhd/lib/usrp_source_impl.h
This fixes two issues:
- When updating the frequency via messages, the new tags now reflect the
actual frequency
- When different channels have different center frequencies, every
channel reports its own frequency accurately
=> uhd: Always query current frequency when outputting tags

gnuradio-runtime/python/gnuradio/ctrlport/CMakeLists.txt
When 6be29ebd2a1a7619f71a737697f730c4145515ec got merged to next, the change in order of thrift dependency list did not get applied resulting in a command with no dependencies/outputs.
Cmake didn't like that and wouldn't let you build. It may be possible to work some git-fu to grab the whole original changeset. Otherwise this is the change that needs to happen.
=> runtime: move thrift dependencies before command

gr-fec/include/gnuradio/fec/polar_decoder_common.h
=> gr-fec: switch possible C++11 code from 'constexpr' to just 'const'.

cmake/Modules/UseSWIG.cmake, gr-utils/python/modtool/gr-newmod/cmake/Modules/UseSWIG.cmake
former custom command called ""; this works fine on build systems were
this is expanded by shell, but fails on some of my systems where
add_custom_command's COMMAND parameter is directly executed (because
there's no executable "").
=> Modified add_custom_command to not try to execute ""

docs/doxygen/Doxyfile.in, docs/doxygen/other/LICENSE.html, docs/doxygen/other/build_guide.dox, docs/doxygen/other/components.dox, docs/doxygen/other/ctrlport.dox, docs/doxygen/other/group_defs.dox, docs/doxygen/other/license.dox, docs/doxygen/other/logger.dox, docs/doxygen/other/main_page.dox, docs/doxygen/other/metadata.dox, docs/doxygen/other/msg_passing.dox, docs/doxygen/other/ofdm.dox, docs/doxygen/other/oot_config.dox, docs/doxygen/other/operating_fg.dox, docs/doxygen/other/packet_txrx.dox, docs/doxygen/other/perf_counters.dox, docs/doxygen/other/pfb_intro.dox, docs/doxygen/other/pmt.dox, docs/doxygen/other/prefs.dox, docs/doxygen/other/python_blocks.dox, docs/doxygen/other/stream_tags.dox, docs/doxygen/other/tagged_stream_blocks.dox, docs/doxygen/other/thread_affinity.dox, docs/doxygen/other/usage.dox, docs/doxygen/other/volk_guide.dox
Added license section on mainpage, full license text as an include, and the license header to the `*.dox` source files, on request from FSF.
=> Adding GNU FDL License to Doxygen Documentation

gr-digital/grc/variable_header_format_default.xml, gr-digital/include/gnuradio/digital/header_format_counter.h, gr-digital/include/gnuradio/digital/header_format_default.h, gr-digital/lib/header_format_counter.cc, gr-digital/lib/header_format_default.cc, gr-digital/python/digital/qa_packet_format.py
Added payload bits per symbol parameter to the header_format_default
block. This allows it to be used with payload modulations besides, for
example, BPSK.
Fixes #1162
=> digital: Add Bits per Symbol parameter to header_format_default

grc/core/Param.py
Currently the type 'id' can only be used for the actual 'id' field.
But it is useful to be able to use it for other things if you want
to reference a block from another one.
The only part where the current code doesn't work is when doing the
evaluation because it uses the type only to check for ID uniqueness.
This change uses both the type and the key. If the key is 'id' then it
must be unique from all other key 'id'. But if the key is something else,
then there must be an existing block to reference.
Signed-off-by: Sylvain Munaut <tnt@246tNt.com>
=> grc: Allow to use 'id' type for parameters

gr-uhd/swig/uhd_swig.i
for some reason, SWIG doesn't infer __eq__ from the existence of a C++ == operator, which caused unexpected behaviour. 
Since expecting `uhd.time_spec_t(0) == uhd.time_spec_t(0)` to work in Python seems reasonable, that's a bug. Here's a bugfix :)
=> added the missing == operator.

config.h.in, docs/doxygen/other/logger.dox
The commits from https://github.com/gnuradio/gnuradio/pull/1195 that are for next only.
=> Delete obsolete configs for Log4cpp from next

gr-digital/grc/digital_costas_loop_cc.xml, gr-digital/lib/costas_loop_cc_impl.cc
The costas_loop_cc block has an optional 2nd output port for the frequency estimate of the control loop.   This commit adds two additional optional output ports for the phase and error as well.  The goal was to match the output port options of fll_band_edge_cc.
=> digital: add loop var outputs to costas_loop_cc

gr-blocks/grc/blocks_block_tree.xml, gr-blocks/grc/blocks_tag_share.xml, gr-blocks/include/gnuradio/blocks/CMakeLists.txt, gr-blocks/include/gnuradio/blocks/tag_share.h, gr-blocks/lib/CMakeLists.txt, gr-blocks/lib/tag_share_impl.cc, gr-blocks/lib/tag_share_impl.h, gr-blocks/python/blocks/qa_tag_share.py, gr-blocks/swig/blocks_swig6.i
The tag share block is used to transfer or share tags from one stream to another. The block takes two inputs and one output. The Input 0 stream is propagated to Output 0. In addition, the tags from Input 1 are added to the Input 0 stream. This is useful for transferring a detection tag from a correlate_access_code_bb block to the main complex stream, for example.
This is my first pull request, so let me know if things look right. I did build and test this, so everything should work.
=> blocks: Add tag share block

cmake/Modules/GrPython.cmake, gr-utils/CMakeLists.txt, grc/blocks/variable_struct.xml.py
Fixes a few outstanding issues with the python3 cmake process.
@sdh11, please verify 3256314 fixes your issue with the prefix
@skoslowski, I touched a file in the GRC dir to fix a cmake error (something about expecting a string instead of bytes) and tested it with both py2 and py3, but please review (5815a58)
@jmcorgan, c274b4e should take care of all the outstanding GR_*_MIN_VERSION strings, as requested
=> Fix cmake issues in python3 branch

gr-zeromq/python/zeromq/probe_manager.py, gr-zeromq/python/zeromq/qa_zeromq_pub.py, gr-zeromq/python/zeromq/qa_zeromq_pubsub.py, gr-zeromq/python/zeromq/qa_zeromq_pushpull.py, gr-zeromq/python/zeromq/qa_zeromq_reqrep.py
First stab at resolving race conditions in zmq qa tests, since GR will create sender and receiver blocks at random (or your OS will) we manually have to make sure there is a receiver block listening on a port before we send data there.
=> gr-zeromq: resolve race condition in qa tests

gr-zeromq/lib/base_impl.cc, gr-zeromq/python/zeromq/qa_zeromq_sub.py
ZeroMQ sink blocks will attempt to load all parts of a multi-part message
before processing tags and outputting items. Allows senders to take
advantage of ZeroMQ's zero-copy message delivery.
Fixes #1080
=> Support receiving multi-part ZeroMQ messages

gr-audio/lib/osx/osx_impl.cc
subject says it all. From #1204 .
=> audio: fix use of 'memcpy' in OSX impl.

grc/blocks/parameter.xml, grc/core/generator/Generator.py
Adds feature requested in #1263 
Allows hiding the parameter from the hierarchical block when using it in GRC.
=> Add hide field in parameter block

gr-qtgui/lib/time_sink_c_impl.cc, gr-qtgui/lib/time_sink_f_impl.cc
When running with trigger mode set to "tag", there is
a corner case where d_start becomes -1, and the flow
graph crashes.
Somebody else should please run some regression tests.
On my side, this does at least eliminate an annoying segfault - which occurs quite often when there are MANY tags..
=> Fix a segfault issue for QT time sink

gr-digital/lib/correlate_access_code_bb_impl.cc, gr-digital/lib/correlate_access_code_bb_ts_impl.cc, gr-digital/lib/correlate_access_code_ff_ts_impl.cc, gr-digital/lib/correlate_access_code_tag_bb_impl.cc, gr-digital/lib/correlate_access_code_tag_ff_impl.cc
Replace "if(VERBOSE)" output with GR_LOG_DEBUG statements. Report errors using GR_LOG_ERROR before throwing in constructor.
=> digital: use GR_LOG for debug/error in correlate_access_code_* blocks

gnuradio-runtime/include/gnuradio/thread/thread.h, gnuradio-runtime/lib/scheduler_tpb.cc, gnuradio-runtime/lib/tpb_thread_body.cc, gnuradio-runtime/lib/tpb_thread_body.h
Juts want to see how the QA tests turn out now. Definitively not ready to merge
=> runtime: add barrier to sync block startup

CMakeLists.txt, cmake/Modules/CodeCoverage.cmake, cmake/Modules/GrBuildTypes.cmake, cmake/Modules/GrTest.cmake
This is an example how we could add a `coverage` target to cmake. 
I'm not entirely sure about the change in the toplevel cmake but I didn't find a better place for it.
This will enable generation of test coverage reports.
Requirements: 
- Installed lcov (and in $PATH)
how to run:
`cmake -DCMAKE_BUILD_TYPE=Coverage $src_dir && make && make coverage` will build GNU Radio with the required flags and run the testsuite collecting coverage data afterwards and placing results in `build/coverage`. 
Example: https://files.gnuradio.org/dev/coverage/
=> cmake: add Coverage target and CMake module to generate coverage data

config.h.in, gnuradio-runtime/include/gnuradio/logger.h.in
Subject says it all. Basically remove the logger macros from config.h.in and fix the ones in logger.h.in for the 4 possible cases; see the code for more info.
=> runtime: fix logger to work with log4cpp 1.1.2 & prior both in tree & OOT.

gr-audio/include/gnuradio/audio/osx_impl.h, gr-audio/lib/osx/osx_common.h, gr-audio/lib/osx/osx_impl.cc
Allow for internal or external specification of _OSX_*_DEBUG_ flags.
=> audio: fix osx variety to work with debug (again).

gr-blocks/lib/stream_to_tagged_stream_impl.cc, gr-blocks/lib/stream_to_tagged_stream_impl.h
Fixes #1091.
Signed-off-by: Paul Cercueil <paul.cercueil@analog.com>
=> blocks: stream_to_tagged_stream: Fix tag offset not reset after unlock()

gr-blocks/examples/ctrlport/simple_copy.grc
In Issue #1302 I mentioned how the example simple_copy.grc (located in gr-blocks/examples/ctrlport/) just doesn't work.  Maybe at one point it worked, but the reason it currently doesn't is because msg input ports that are not connected to anything are not exposed and accessible via ControlPort.  Now that may be a bug in itself, not sure, but to make a quick fix for this example I created an embedded python block that has a msg output port but doesn't actually send out any messages (think of it like a "null msg source").  Then I connected it to the Copy block, thus exposing the msg input port and allowing this example to work.  I also went ahead and added a Note block giving the user some tips for getting the example to work.  So it's an ugly fix but at least the example works now, and I …
=> gr-blocks: fixes the broken example simple_copy.grc

gr-analog/lib/agc3_cc_impl.cc
This patch only affects MSVC builds...
qa_agc3 fails on MSVC builds.  Added memory alignment to fix primary issue.
Also since VS 2015+ supports std:isfinite, changed branch to use that instead of older msvc specific syntax.
However, after all that, the test will only pass if I reduce the number of digits they must match to 2 instead of four, and give the test more time to reach stability.  It gets close but clearly has less precision than the GCC version.
=> gr-analog: added memory alignment for MSVC to agc3

gnuradio-runtime/python/gnuradio/gr/tag_utils.py
3 tests fail in MSVC build due to swig_int_ptr being referred to from the pmt.pmt_swig module, not the pmt module.
This syntax is only used in the python_to_tag function code, which is only called from qa tests.
This changes the reference to pmt.*, and those tests now pass on MSVC.  
Not tested on Linux.  It is not clear to me how the test would pass on py2.7 on Linux but not on Windows.  I could not come up with a set of PYTHONPATH directories that would enable the code to pass as is on win64, so I find that puzzling.
=> runtime: replace pmt.pmt_swig.* namespace calls with pmt.*

gr-fft/lib/fft.cc
Initially, on win32 building gr-fft will error due to missing win-specific file handling headers.
After applying first commit to fix that, then qa_fft will hang.
A new wisdom_lock object is being created in the wisdom_unlock() routine, which then throws an exception when unlock() is called because the new object isn't locked. This then aborts the make() routine without unlocking the original object or the mutex.  Then when wisdom_lock() gets called in the next test, the mutex is still locked and the application hangs. 
Fix just creates a single static wisdom_lock object and reuses it for both calls.
=> gr-fft: fix object reuse issue causing qa_fft hang on win32

gr-blocks/lib/file_meta_sink_impl.cc, gr-blocks/lib/file_meta_source_impl.cc, gr-blocks/python/blocks/qa_file_metadata.py
This fixes two minor bugs in file_metadata:
1- calling close() on the block does the final update on the pmt header, but doesn't actually close the file.  That only happens on object destruction.  So the process will keep a lock on the file until the object is actually released.  So in qa_file_metadata, there is still a lock on the file when os.remove() is called.  This is not a problem in Linux, but windows is pickier and will refuse to remove the file and this fail the test.
So the first commit moves file closure from the destructor to close().  The other change is to ensure that since close() gets called again by the destructor, that the final update only occurs if the filestream is still valid.
2- The qa_file_metadata test doesn't call close() on the file source, just the file sink. …
=> gr_blocks: file closure fixes for msvc

gr-fec/python/fec/polar/channel_construction.py
This is a 64-bit issue, not an msvc issue.
During polar channel construction, np.argmin() is called, which will return int64's on a 64-bit system.  These are appended onto an array which is supposed to be a 32-bit int array.
When this array gets passed to the polar_decoder_sc.make() function as the frozen_bit_position argument, it causes a TypeError and fails.
The fix simply specifically casts the argmin() function as int as well
=> gr-fec: specify 32bit int output when getting frozen bit indices

gr-blocks/grc/blocks_tag_gate.xml, gr-blocks/include/gnuradio/blocks/tag_gate.h, gr-blocks/lib/tag_gate_impl.cc, gr-blocks/lib/tag_gate_impl.h, gr-blocks/python/blocks/qa_tag_gate.py
- Make it possible to specify a single tag key to look for instead of all tags.
- Extended unit test for new functionality
- Actually fix a bug which made the unit test do nothing earlier
=> blocks: tag_gate (improvements)

gr-utils/python/modtool/modtool_makexml.py, gr-utils/python/modtool/modtool_rm.py
when building packages (e.g. for openSUSE Linux)
(random) filesystem order of input files
influences ordering of functions in the output,
thus without the patch, builds (in disposable VMs) would usually differ.
See https://reproducible-builds.org/ for why this matters.
such diffs affected volk-config-info volk_profile volk.h volk_typedefs.h gnuradio/xml/index.xml gnuradio/html/volk_8h_source.html etc
http://rb.zq1.de/compare.factory-20170531/gnuradio-compare.out
=> sort input files

gnuradio-runtime/include/gnuradio/rpccallbackregister_base.h, gnuradio-runtime/include/gnuradio/rpcserver_aggregator.h, gnuradio-runtime/include/gnuradio/rpcserver_base.h, gnuradio-runtime/lib/controlport/rpcserver_aggregator.cc
The RPC aggregator and friends were taking callback objects passed by
value, and then internally called, again by value, constructors which
initialized reference fields to these parameters.
This has the effect of storing references to temporary objects. Chances
are, no-one is using that code, or compiler UB saved our collective
behinds.
In any case, we might need to more carefully dissect the RPC code. There
be dragons.
=> Fixed storing references to temporary values in RPC infrastructure

gr-fft/lib/window.cc
https://github.com/gnuradio/gnuradio/issues/1348
We were doing floating point math wrong.
=> Fixed floating point math bug (#1348)

CMakeLists.txt, gr-fft/lib/fft.cc
This set of two commits fix the compilation of gnuradio-runtime and gr-fft under mingw-w64, on 32-bit and 64-bit versions of Windows.
=> Fix compilation under MinGW

gr-uhd/lib/usrp_sink_impl.cc
Fix for #1353 
rebased to maint: https://github.com/gnuradio/gnuradio/pull/1355
=> uhd: Fixed tx streamer creation in usrp_sink

gr-digital/python/grc_gnuradio/blks2/packet.py
This is a repull of #1360 to base the commit off maint. The current run() function in the _packet_encoder_thread clips the end of samples who's sample length modulo payload_length is greater than zero. The hack applied here is to append padding characters to satisfy the payload_length and allow for the remaining sample to be flushed on the next cycle. Current testing transmits a .jpg using a flow as follows: File source -> packet encoder -> dpsk mod -> dpsk demod -> packet decoder -> file sink. The input file is 37,075 bytes in size. The output file is 36,864 bytes in size. A 211 byte difference still exists from the file source / sink and is noted in #1362 .
=> gr-digital: packet.py _packet_encoder_thread run() buffer clips payload data

gr-blocks/grc/blocks_tag_gate.xml
BUGFIX: Removed extraneous ')' from grc/blocks_tag_gate.xml which was causing a syntax error in the generated Python code.
=> 	modified:   grc/blocks_tag_gate.xml

gnuradio-runtime/lib/buffer.cc
buffer::get_tags_in_range called v.resize(0) instead of v.clear() to clear out the input vector.  This causes needless memory allocation of the default value for the second argument to resize.  In applications that make heavy use of tags, this can cause significant performance problems as get_tags_in_range performs an extra allocation and deallocation.
=> fix: fixed a performance bug in buffer::get_tags_in_range.

gnuradio-runtime/include/gnuradio/types.h
Elsewhere in tree, we never check for #ifdef HAVE_STDINT_H, so this
can't make a difference here. And, we nowhere use any gr_int types, so
we don't need to drag these around.
=> Removed superfluous typedefs of gr_?int*; included stdint.h uncond. (#1378)

gr-blocks/lib/file_source_impl.cc
Add a warning to notify the user if the file passed will be fully consumed. Currently, the file source reads in d_itemsize bytes at a time. If the file size % output type size (d_itemsize) is not zero then the final few bytes of the file are never read.
=> gr-blocks: add warning to file_source if file will not be fully consumed

gr-fcd/lib/CMakeLists.txt
subject says it all. simple tweak. the MacOS FCD interface uses CoreFoundation functions, so link to the library. This extra linkage is technically only required on non-Apple compilers (e.g., GCC), but it won't hurt to have it in place for Apple compilers too.
=> fcd: add CoreFoundation library in Darwin only

grc/gui/ActionHandler.py, grc/gui/NotebookPage.py
Currently, GRC terminate button (F7) sends SIGKILL to the ongoing Python program.
This PR is an attempt to send SIGTERM signal in order to allow cleanup before termination. Also, sends SIGKILL signal to the process after 4 seconds if Python program couldn't terminate with SIGTERM.
Since, many hardware takes around 2 seconds to disconnect, 4 seconds should be more than enough for cleaning up.
=> grc: Terminate the process instead of Killing with Terminate button (F7)

gr-digital/examples/demod/symbol_sync_test_complex.grc, gr-digital/examples/demod/symbol_sync_test_float.grc, gr-digital/grc/digital_symbol_sync_xx.xml, gr-digital/include/gnuradio/digital/symbol_sync_cc.h, gr-digital/include/gnuradio/digital/symbol_sync_ff.h, gr-digital/lib/clock_tracking_loop.cc, gr-digital/lib/clock_tracking_loop.h, gr-digital/lib/symbol_sync_cc_impl.cc, gr-digital/lib/symbol_sync_cc_impl.h, gr-digital/lib/symbol_sync_ff_impl.cc, gr-digital/lib/symbol_sync_ff_impl.h
The computation of proportional (alpha) and intergal (beta) loop
gains in the symbol synchronizer blocks neglected to account for
the timing error detector gain.  Add expected timing error
detector gain as a user configurable parameter.
=> digital: Add expected TED gain for computing symbol sync loop gains

gnuradio-runtime/include/gnuradio/block_gateway.h, gr-blocks/python/blocks/qa_block_gateway.py
so that we can then have
def general_work(self, input_items, output_items):
…
self.produce(0,2)
self.produce(1,1)
return gr.WORK_CALLED_PRODUCE
Includes a unit test.
We need more unit tests. There wasn't a single general block test in
qa_block_gateway.py.
Ref: 
http://lists.gnu.org/archive/html/discuss-gnuradio/2017-07/msg00338.html
=> block python gateway: add WORK_CALLED_PRODUCE/_DONE proxy

grc/core/generator/top_block.py
Steps to reproduce:
Launch GRC, create a flowgraph and try to generate it. The generation will fail with a NameError: 'callback' is not defined.
=> grc: Fixing NameError

grc/core/blocks/block.py
Steps to reproduce:
Launch GRC, create a flowgraph with an ID in the options block. Save it, close it and open it again. The ID is gone. You can also see in the .grc file that there is no ID.
This change fixes the problem, but I'm not 110% confident that this is the appropriate fix. 
Please advise :)
=> grc: Fixing GRC not saving the options block's ID

grc/core/Param.py
This apparently fixes issue @guruofquality was having with enum opts in cheetah templates.
Reported here:  https://github.com/gnuradio/gnuradio/commit/2708f33f4531b33c212c60c3cc1fc3d3a92b5ae1#commitcomment-23327018
I can't seem to reproduce this: current maint branch, same Python version (I guess same Cheetah version too?)
I tried a simple fg with a bunch of null sinks/sources that use any vary this kind of parameter, always get correct string interpolation. 
I don't mind merging this anyway, I am curious though, why this works for me. @guruofquality, do you maybe have an example for me?
=> grc: fix attr-style enum param lookup in Cheeteh

CMakeLists.txt
After updating to cmake 3.9.1, these particular set of elses caused an error. Perhaps cmake was permissive about this in prior versions, but the code should really read elseif on subsequent cases regardless.
* Fixes configuration  error on cmake 3.9.1
=> cmake: switch cascaded elses to elseifs

gr-digital/lib/correlate_access_code_bb_impl.cc
Removed persistent logging to console present in packet decode as a result of new_flag calls in correlate_access_code_bb_impl.cc. Test flow: File source -> packet encoder -> dpsk mod -> dpsk demod -> packet decoder -> time sink.
=> BUGFIX: Removed persistent logging to console present in correlate_access_code_bb_impl.cc

gr-fec/lib/cc_encoder_impl.cc
Negative polynomials are already supported in cc_decoder. Inverting
the sign of the polynomial in a convolutional code is just a convention
to invert the output bit corresponding to that polynomial.
=> Support negative polynomials in cc_encoder

gr-digital/examples/demod/symbol_sync_test_complex.grc, gr-digital/examples/demod/symbol_sync_test_float.grc, gr-digital/examples/demod/symbol_sync_test_float_ted_gain.m
Fix some incorrectly computed integral gain readouts in the the symbol_sync_test*.grc example
flowgraphs.
Also add an example Octave script for simulating the M&M and Gardner TED, as they apply
to the symbol_sync_test_float.grc flowgraph, to compute the TED S-Curves and TED gains
in the proper units needed for the flowgraph.
Update the default expected TED gain and Loop Bandwidth in the symbol_sync_test_float.grc
flowgraph.
Tweak the TED gain slider start and step in both symbol_sync_test*.grc flowgraphs.
=> digital: Correct and Improve Symbol Sync example flowgraphs

grc/gui/Application.py
Steps to reproduce:
Launch GRC, click 'New' and choose your GUI. The GUI options of the new flowgraph will be QT regardless.
=> grc: Fixing the "generate options" chooser from the "new flowgraph" menu

gr-blocks/lib/tags_strobe_impl.cc
Fixes #1431 - nsamps setter bug that causes a bunch of extra tags to be added, because it was setting d_offset = 0 (d_offset tracks where it currently is in the input buffer).  Setting d_offset to zero should happen in the constructor, not the nsamps setter.
=> Fix tags_strobe nsamps setter bug

gr-uhd/grc/gen_uhd_usrp_blocks.py
GRC bindings for the USRP sink and source suggest some antenna names.
This adds the antenna name RX1 (TwinRX) into the list of antenna name
suggestions.
=> uhd: Add RX1 as default option

gnuradio-runtime/include/gnuradio/logger.h.in
Addresses issue #1383, where if GR and an OOT are built with logging
enabled but GR is build using log4cpp and the OOT is build without it,
then gr_block will be of different size & freeing it can result in
heap corruption.
This fix mades all of the logger_ptr typedefs an actual pointer, which
should always be the same size and hence gr_block will always be the
same size no matter what logging option is selected.
[Unlike PR #1398, which fixed a bunch of logger-related issues, this one is just for the logger_ptr issue #1383. I'm splitting off this fix from the rest, since there is a better way to handle some parts of logging along with include ordering fixes & this issue just needs to be fixed.]
=> runtime: fix logger_ptr to always be a pointer

gr-blocks/lib/socket_pdu_impl.h, gr-blocks/lib/tcp_connection.cc, gr-blocks/lib/tcp_connection.h, gr-blocks/python/blocks/qa_socket_pdu.py
Asio requires that the underlying buffer passed to `async_write()` remain valid valid until the handler was called. The previous version was allocating a vector on the stack which gets destroyed once the `send()` method returns. Added a test case for the TCP server.
I'm on the fence about the raw pointer usage for `txbuf`. I considered using `boost::shared_ptr` (though that has the overhead of a ref count). I can switch this to a `std::unique_ptr` if Gnuradio can use C++11 features.
I also discovered the interesting behavior wrt PDUs larger than the configured MTU and left a corresponding comment for developers of the future.
=> Fix invalid Asio buffer usage in tcp_connection

gr-digital/grc/digital_correlate_access_code_tag_xx.xml, gr-digital/include/gnuradio/digital/correlate_access_code_tag_bb.h, gr-digital/include/gnuradio/digital/correlate_access_code_tag_ff.h, gr-digital/lib/correlate_access_code_tag_bb_impl.cc, gr-digital/lib/correlate_access_code_tag_bb_impl.h, gr-digital/lib/correlate_access_code_tag_ff_impl.cc, gr-digital/lib/correlate_access_code_tag_ff_impl.h
Added callbacks to the correlate_access_code_tag_xx block and fixed a minor bug with the block tree for gr_digital related to the same block (it had the earlier _bb suffix in the block tree XML).
=> gr-digital: Correlate access code callbacks

CMakeLists.txt
This PR fixes an issue introduced with #1424.
volk uses the `asm` keyword which is only defined in GNU extensions and is not present in builds with `-std=c99` for older GCC versions.
@michaelld Will this break cppunit again?
=> cmake: fix build issue with introduction with -std=c99 define

CMakeLists.txt, cmake/Modules/CMakeOverloads.cmake
[This PR is clean for me on maint, master, and next. It needs to be
tested thoroughly, as it overloads a critical CMake function! - MLD]
For now, the CMakeOverloads file just overloads the CMake function
"include_directories", to make it a little smarter. When parsing the
provided directories, the overloaded macro now checks to see whether
each directory is in the SOURCE or BUILD, or neither. If so, then the
directory is added BEFORE others, and if not, then AFTER. The keywords
BEFORE and AFTER are ignored. In this manner, all internal directories
will come before external directories, which allows builds to work
even if a prior version of GNU Radio is already installed into the
CMAKE_INSTALL_PREFIX (e.g., as is often found when building from
source, such as in MacPorts).
By adding this …
=> cmake: add CMake Overloads file and use it at the top level

gr-zeromq/include/gnuradio/zeromq/pub_msg_sink.h, gr-zeromq/include/gnuradio/zeromq/pub_sink.h, gr-zeromq/include/gnuradio/zeromq/pull_msg_source.h, gr-zeromq/include/gnuradio/zeromq/pull_source.h, gr-zeromq/include/gnuradio/zeromq/push_msg_sink.h, gr-zeromq/include/gnuradio/zeromq/push_sink.h, gr-zeromq/include/gnuradio/zeromq/rep_msg_sink.h, gr-zeromq/include/gnuradio/zeromq/rep_sink.h, gr-zeromq/include/gnuradio/zeromq/req_msg_source.h, gr-zeromq/include/gnuradio/zeromq/req_source.h, gr-zeromq/include/gnuradio/zeromq/sub_msg_source.h, gr-zeromq/include/gnuradio/zeromq/sub_source.h
=> docs: fixed units of timeout param in all the zmq blocks

docs/doxygen/other/msg_passing.dox
Several changes to msg_passing.dox including:
1. Adding Python versions of message_port_register and pub commands right after the C++ versions
2. Moving examples to the bottom, to improve flow
3. There were a couple portions of redundant explanations
4. I tried to make it more clear that message_port_sub() is not something we usually call ourselves, but is internal to msg_connect(), so as to not confused new people
5. General proofing
=> doc: improved msg passing section of doxygen usage manual

grc/blocks/options.xml, grc/core/Platform.py, grc/core/generator/flow_graph.tmpl, grc/core/utils/hide_bokeh_gui_options_if_not_installed.py
This includes all modifications required in GRC to allow BokehGUI.
Major changes:
Added BokehGUI `main()` in `flow_graph.tmpl`
Added an option for BokehGUI in Options block
=> Modifications in GRC to allow BokehGUI

gr-blocks/python/blocks/qa_moving_average.py
This adresses #1461 . The unit test of the moving_average block was not sufficient. 100 random numbers between [-1, 1) were summed up and then scaled with 0.001. If the result was near 0, the case was passed, which should always be the case (even when the block is malfunctioning).
I added two test cases and implemented a pythonic MA filter to check the correct behaviour of the block.
=> [gr-blocks] improve moving_average unit test

gnuradio-runtime/lib/hier_block2_detail.cc, gr-blocks/examples/ctrlport/simple_copy.grc
This PR fixes an issue introduced by PR https://github.com/gnuradio/gnuradio/pull/1119 and referenced in issue https://github.com/gnuradio/gnuradio/issues/1302 related to how setup_rpc() is called for blocks. Originally this was done for the source and destination of each streaming connection, which excluded blocks that message only ports. PR1119 made this work for message ports but broke streaming ports.
This PR moves this to the end of the function that interprets flowgraphs and iterates explicitly over each connected block calling setup_rpc() if it is not setup already. This still does not setup RPC for blocks that are not connected to anything else, which may or may not be an issue.
This also removes the workaround for this bug in PR https://github.com/gnuradio/gnuradio/pull/1324 …
=> runtime: Fix issue where setup_rpc() is not called for all blocks in a flowgraph

gr-uhd/doc/uhd.dox, gr-uhd/lib/usrp_block_impl.cc, gr-uhd/lib/usrp_block_impl.h, gr-uhd/lib/usrp_sink_impl.cc, gr-uhd/lib/usrp_sink_impl.h, gr-uhd/lib/usrp_source_impl.cc, gr-uhd/lib/usrp_source_impl.h
This PR addresses issue #1199.
Issue Summary: Currently, UHD timed tuning commands are issued to the direction (RX or TX) corresponding to the block (Source / Sink respectively) they are issued to. In a transceiver application, this can cause tune commands to end up out-of-order as messages are asynchronous.
This change:
1. Removes the macro function definition used for message based tuning and explicitly instantiates the method in each of the source / sink blocks.
2. Adds an optional ‘direction’ command (PMT symbol ‘TX’ or ‘RX’) to the UHD message command dictionary which allows the sink block to tune the RX path or source block to tune TX path. This value is now an argument to the tuning function mentioned in 1.
3. Updates doxygen for the new ‘direction’ command.
If no ‘direction’ …
=> gr-uhd: Solution for out of order message based timed commands for transceivers

gr-uhd/include/gnuradio/uhd/usrp_source.h, gr-uhd/lib/usrp_source_impl.cc, gr-uhd/lib/usrp_source_impl.h
usrp_source currently hard-codes timeout values. For high-performance
applications, it might be desirable to control the details of the call
to uhd::rx_streamer::recv(), which is now enabled.
Defaults are unchanged.
=> uhd: Parametrize recv timeout and single-packet option

gr-digital/examples/CMakeLists.txt
Add the example symbol_sync_test_float_ted_gain.m file to the gr-digital/examples/CMakeLists.txt file for installation.  Not doing this was an oversight, when the file was first added.
=> gr-digital: Install example symbol_sync_test_float_ted_gain.m file

gr-utils/python/modtool/templates.py
Very minor; gr_modtool template uses 'numpy.float' which defaults to numpy.float64 (double) in python 2 and 3 instead of 'numpy.float32' which is single precision and what is much more common for GR.
=> gr-utils: modtool template to use float32 as default for python block signatures

README.md
This extends the readme with fancy
- Build status from our CI build
- Current version tag
=> Add CI status and current version shields to readme

gr-qtgui/grc/qtgui_time_sink_x.xml
Stem plots are available in the qt time sink already but not exposed through GRC. This adds a simple control.
I'm not sure if the control is better placed on the main tab or in config. Additionally there is a behavior difference between using this control and the middle click context menu option. The middle click both sets the plot type to stem and changes the point marker to circle. I can add the conditional behavior in the xml to override the marker type if stem is true, but since that is overriding the user's settings I wanted to ask for an opinion before doing that.
Current PR behavior:
Usual context menu result (marker overridden to circle):
=> grc: Expose qt time sink stem plot option

gr-utils/python/utils/gr_modtool
All subclasses of object have a __subclasses__ method, which gives the
subclasses. That's a lot fewer objects than what's in globals().
=> Making gr_modtool start faster by avoiding to iterate over all globals

gnuradio-runtime/include/gnuradio/block.h
See [1] for reference.
[1] [https://lists.gnu.org/archive/html/discuss-gnuradio/2017-11/msg00152.html](https://lists.gnu.org/archive/html/discuss-gnuradio/2017-11/msg00152.html)
=> docs: Add missing information on usage of produce()/consume()

gnuradio-runtime/include/gnuradio/block.h
The documentation was not updated when WORK_CALLED_PRODUCE was added.
=> block.h: update documentation on general_work return value

gnuradio-runtime/lib/math/random.cc
=> Use logf when dealing with single-precision float

gnuradio-runtime/include/gnuradio/fxpt.h, gnuradio-runtime/lib/math/fxpt.cc, gr-analog/include/gnuradio/analog/agc.h, gr-blocks/include/gnuradio/blocks/rotator.h, gr-digital/lib/kurtotic_equalizer_cc_impl.h, gr-qtgui/include/gnuradio/qtgui/form_menus.h
Complements gnuradio/gnuradio#1563, larger-scope version of
the issue gnuradio/gnuradio#1561 .
=> Use type-generic or float versions of cmath functions where appropriate.

gr-blocks/lib/socket_pdu_impl.cc, gr-blocks/lib/tcp_connection.cc
This patch addresses two problems. First tcp_connections were not being
closed, leading to a bug report about socket exhaustion [1]. Second,
socket_pdu_impl tracks tcp_connections in a vector so that it can
broadcast outgoing data to clients. Items in this vector were never
freed.
This patch does a shutdown and close on the tcp_connection when there
is a read failure (signaling a socket close). On each new accept, the
tcp_connection list in socket_pdu_impl is scanned for closed connections,
which are then removed.
Possible improvements:
- Make sure the read error is eof.
- Check sends as well as reads.
More direct signalling could be done between tcp_connection and
socket_pdu_impl, but that would require an API change. No change
is required, here.
[1] …
=> socket_pdu_impl: garbage collect closed tcp_connections

gr-fec/lib/CMakeLists.txt
These changes are required in order to build GR on macOS 10.13 with MacPorts. Also tested on Fedora 25, but further testing e.g. on Ubuntu would be sensible. If these changes are not provided, I get a linker error: `ld: library not found for -lgsl`. @bastibl hope that doesn't interfere with #1247, where you actually deleted this.
=> [gr-fec] include GSL_LDFLAGS in CMakeLists to avoid linking errors in dependent in-trees

gr-zeromq/python/zeromq/qa_zeromq_sub.py
Running zeromq QA tests in parallel can result in using the same port twice for different tests
which would show as failing tests.
=> zeromq: change ports used in zeromq_sub QA

gnuradio-runtime/swig/hier_block2.i, gnuradio-runtime/swig/top_block.i, gr-audio/lib/alsa/alsa_sink.cc, gr-audio/lib/alsa/alsa_sink.h, gr-audio/lib/alsa/alsa_source.cc, gr-audio/lib/alsa/alsa_source.h, gr-audio/lib/jack/jack_sink.cc, gr-audio/lib/jack/jack_sink.h, gr-audio/lib/jack/jack_source.cc, gr-audio/lib/jack/jack_source.h, gr-audio/lib/portaudio/portaudio_sink.cc, gr-audio/lib/portaudio/portaudio_sink.h, gr-audio/lib/portaudio/portaudio_source.cc, gr-audio/lib/portaudio/portaudio_source.h, gr-blocks/python/blocks/qa_hier_block2.py, gr-filter/include/gnuradio/filter/iir_filter.h, gr-filter/include/gnuradio/filter/pm_remez.h, gr-filter/lib/pm_remez.cc
Dynamic exception specifications are deprecated in C++11. Definining function with `noexcept()` is the way to go from C++11 on. `throw()` will be redefined to `noexecept(true)` in C++17.
We only have to define `noexcept(false)` for:
- destructors
- {default,copy,move} constructors
- {copy,move} assignment operators
- deallocation functions
Otherwise all other functions in C++ are potentially throwing by definition.
I wasn't sure about the swig templates, so I replaced throw(`something`) with noexcept(false) to give swig a hint that those functions are potentially throwing.
=> cleanup: remove dynamic exception specifications

gr-digital/lib/crc32_bb_impl.cc, gr-digital/lib/crc32_bb_impl.h, gr-digital/python/digital/qa_crc32_bb.py
This requires repacking unpacked binary data (currently only LSB) and calculating the CRC.
Previous behaviour generated a mixed packed/unpacked stream of bytes.
I added a new test for the correct behaviour and fixed a test relying on the wrong/old behaviour.
fixes #1407
=> Fix unpacked behaviour of crc32_bb fixes #1407

gnuradio-runtime/lib/pmt/pmt.cc
PMT uniform vector comparisons with pmt::equal() do not fail for different vector elements provided the vectors are the same size and type:
before:
```
>>> import pmt
>>> uv1 = pmt.init_u8vector(4,[1,2,3,4])
>>> uv2 = pmt.init_u8vector(4,[5,6,7,8])
>>> uv3 = pmt.init_u8vector(4,[5,6,7,8])
>>> pmt.equal(uv1, uv2)
True
>>> pmt.equal(uv2, uv3)
True
```
after:
```
>>> import pmt
>>> uv1 = pmt.init_u8vector(4,[1,2,3,4])
>>> uv2 = pmt.init_u8vector(4,[5,6,7,8])
>>> uv3 = pmt.init_u8vector(4,[5,6,7,8])
>>> pmt.equal(uv1, uv2)
False
>>> pmt.equal(uv2, uv3)
True
```
=> pmt: fix for error in pmt::equal() when comparing uniform vectors

gr-blocks/grc/blocks_plateau_detector_fb.xml, gr-blocks/include/gnuradio/blocks/plateau_detector_fb.h, gr-blocks/lib/plateau_detector_fb_impl.cc, gr-blocks/lib/plateau_detector_fb_impl.h, gr-digital/grc/digital_ofdm_sync_sc_cfb.xml, gr-digital/include/gnuradio/digital/ofdm_sync_sc_cfb.h, gr-digital/lib/ofdm_sync_sc_cfb_impl.cc, gr-digital/lib/ofdm_sync_sc_cfb_impl.h
Adding a threshold callback and set / get allows more dynamic use of the S&C OFDM sync block. With a default threshold of 0.9, the S&C OFDM sync block has a lower noise threshold than the header or payload (e.g., if encoded using FEC). These changes allow selection of the mid-level threshold (e.g., 0.5) such that FEC can be used with benefits. In my testing, the GRC blocks are backward compatible with the current ones, as they set default values for the threshold and otherwise change nothing.
=> Add threshold to plateau and S&C OFDM sync

gr-blocks/lib/annotator_alltoall_impl.cc, gr-blocks/lib/annotator_alltoall_impl.h
In gr-blocks/annotator_alltoall.[h/cc]: class member d_itemsize was unused. Thus, it was removed as part of code clean-up.
This fixes #1623 .
=> blocks: remove unused class member

grc/gui/ActionHandler.py, grc/gui/Dialogs.py, grc/gui/FileDialogs.py, grc/gui/FlowGraph.py, grc/gui/MainWindow.py, grc/gui/Param.py, grc/gui/PropsDialog.py
First attempt at fixing #1494. For most dialogs, the `parent` window will be the `MainWindow`, but for dialogs opened by other dialogs, the `parent` will be the dialog that opened them. The deepest example of this is the Python Block's "Open in Editor" choice dialog, which itself triggers a file selection dialog.
Please test if possible. Not sure how to do any kind of automated testing on this.
=> Added parent (aka 'transient for') references to dialogs

gr-fec/python/fec/polar/channel_construction.py
This patch fixes issues like #1545 and #1539.
Basically if a module in fec.polar requires SciPy and fails to perform `import scipy`,
it overwrites the missing function with an approximate version
=> fec: make SciPy an optional dependency

gnuradio-runtime/python/gnuradio/gr/gateway.py
This allows GRC to iterate the output signatures of epy blocks after
switching over to py_io_signature.
Fixes #1666.
=> runtime: make py_io_signature iterable, hashable

gr-filter/grc/filter_pfb_channelizer.xml, gr-filter/include/gnuradio/filter/pfb_arb_resampler.h, gr-filter/include/gnuradio/filter/pfb_arb_resampler_fff.h, gr-filter/include/gnuradio/filter/pfb_channelizer_ccf.h, gr-filter/include/gnuradio/filter/pfb_decimator_ccf.h, gr-filter/include/gnuradio/filter/pfb_interpolator_ccf.h, gr-filter/include/gnuradio/filter/polyphase_filterbank.h
This fixes some typos I noticed while reading over the Polyphase Filterbank documentation.
=> Fix typos in PFB docs.

gr-channels/grc/channels_iqbal_gen.xml, gr-channels/python/channels/iqbal_gen.py
Fixing the formula behind the IQ_imbal block to be true mathematically.
X' = (1+mag_lin)·cos(theta)·real(X) + j·((1+mag_lin)·sin(theta)·real(X) + imag(X))
is the proper equation for handling the IQ imblance purely within the Inphase component.
Previously it was:
X' = (1+mag_lin)·real(X) + j·(sin(theta)·real(X) + imag(X))
=> gr-channels: Fixing the formula behind the IQ_imbal block

gr-uhd/lib/usrp_block_impl.cc, gr-uhd/lib/usrp_block_impl.h
These constant pmt variables are not initialized when included from the header file.  I figure they can be initialized in the header file itself.  This corresponds to the bug in issue #1688.
=> fix broken gr-uhd command tags

cmake/Modules/FindGSL.cmake
Pull request #1490 breaks the windows build because GSL_LDFLAGS isn't defined in MSVC windows.  
Assuming the use of GSL_LDFLAGS is needed in Linux instead of the more common XXX_LIBRARIES pattern, this will specifically define GSL_LDFLAGS for WIN32/MSVC builds only.
That allows gr-fec/lib/CMakeText.txt to find the correct libraries and add the dependencies.
=> [gr-fec] Define GSL_LDFLAGS in MSVC build

gr-utils/python/modtool/modtool_add.py
To avoid creation of same blockname, we can check whether the corresponding block file exists in lib or python directory or not. If the corresponding file, eg: `square_ff_impl.cc` exists in the lib directory, we give a ModToolException that `The corresponding blockname already exists!`
=> Fix #1678: Avoid creation of same blockname

gnuradio-runtime/python/gnuradio/gr/CMakeLists.txt, gnuradio-runtime/python/pmt/CMakeLists.txt, gr-analog/python/analog/CMakeLists.txt, gr-atsc/python/atsc/CMakeLists.txt, gr-audio/python/audio/CMakeLists.txt, gr-blocks/python/blocks/CMakeLists.txt, gr-channels/python/channels/CMakeLists.txt, gr-comedi/python/comedi/CMakeLists.txt, gr-digital/python/digital/CMakeLists.txt, gr-dtv/python/dtv/CMakeLists.txt, gr-fcd/python/fcd/CMakeLists.txt, gr-fec/python/fec/CMakeLists.txt, gr-fft/python/fft/CMakeLists.txt, gr-filter/python/filter/CMakeLists.txt, gr-noaa/python/noaa/CMakeLists.txt, gr-pager/python/pager/CMakeLists.txt, gr-qtgui/python/qtgui/CMakeLists.txt, gr-trellis/python/trellis/CMakeLists.txt, gr-uhd/python/uhd/CMakeLists.txt, gr-video-sdl/python/video_sdl/CMakeLists.txt, gr-vocoder/python/vocoder/CMakeLists.txt, gr-wavelet/python/wavelet/CMakeLists.txt, gr-zeromq/python/zeromq/CMakeLists.txt
Running unit tests on windows has previously required running tests individually because the dependencies are not set up correctly for the build structure.
This adds the appropriate directories and allows ctest to run within the run_gr.bat environment.
Only affects test environment, and while Linux may not require the additional paths, I don't think they'll be hurt by them either.
=> Test: adds swig dirs to python tests to allow ctest to run on win builds

gr-fec/lib/polar_decoder_common.cc
VOLK kernel polarbutterfly has an updated API. This patch updates the corresponding call into VOLK.
This patch should only be applied after the next VOLK release. Or after the VOLK subrepo pointer is updated.
=> fec: update VOLK API call

grc/core/generator/Generator.py
Code which is generated from Python module/blocks in hierarchical block flow graphs will be saved at the block path, fixes #1709
=> grc: saving epy_module/epy_block code at block path if block is hierarchical

gr-analog/python/analog/qa_sig_source.py
There were no unit tests for sig_source_c for the sinusoidal case.  This pull request adds a unit test for a complex sinusoid. 
The original motivation was that I had incorrectly assumed that setting the waveform of a complex signal to GR_COS_WAVE and GR_SIN_WAVE would yield different results.  I had assumed that setting the waveform to GR_SIN_WAVE would have created a complex signal that was 3pi/2 radians phase shifted.  I reviewed the unit tests because I thought that there was something wrong; I think there should be at least a runtime note that GR_COS_WAVE and GR_SIN_WAVE produce the same behaviour in the complex case.  
My goal was to have two complex signals that were out of phase.  I may open up an issue (and potentially send a pull request) regarding setting the phase of a signal …
=> QA test for complex sinusoid

gr-blocks/lib/message_strobe_impl.cc, gr-blocks/lib/message_strobe_random_impl.cc, gr-uhd/lib/usrp_block_impl.cc
Fix regression due to https://github.com/boostorg/date_time/commit/f9f2aaf5216c.
`uhd` may be fixing these in some other way. See https://github.com/EttusResearch/uhd/pull/170#issuecomment-381749132.
=> Boost 1.67 compatibility

grc/core/Param.py
The templating for gui_hint was changed in #1418 breaking some oot modules.
=> grc: make values of param type gui_hint callable again

gr-uhd/apps/uhd_siggen_gui
`uhd_siggen_gui` had an artificial limitation in generating tones only within +- Fs/4. This lifts that to the limits of Nyquist.
=> uhd: Expand uhd_siggen_gui tuning range

gr-uhd/apps/uhd_app.py
When all LOs are externally sourced there is no primary channel to use actual tune data from.
Previously uhd_app based applications would crash as `self.lo_source_channel` would not exist.
=> UHD: Allow uhd_app to handle all LOs external

gr-blocks/lib/float_array_to_int.cc
There was an off-by-one in the MIN_INT
=> Fixing the MIN_INT to be actual MIN_INT

gnuradio-runtime/python/gnuradio/gr_unittest.py
I added the option to pass verbosity to the test runner
=> tests: added option to pass verbosity parameter (and fixed some styling)

gnuradio-runtime/include/gnuradio/logger.h.in
If logging with log4cpp is not enabled, then this variable is not used and thus causes warnings with some compilers / settings. Simple tweak to fix these warnings as well as help the code make more sense via using the already-in-place macro to declare it.
=> runtime: declare d_logger only if actually using logging with log4cpp via macros

gr-digital/python/digital/qa_packet_format.py
=> backport: digital: qa_packet_format fix conditionals to wait for messages

gr-digital/grc/digital_corr_est_cc.xml, gr-digital/include/gnuradio/digital/corr_est_cc.h, gr-digital/lib/corr_est_cc_impl.cc, gr-digital/lib/corr_est_cc_impl.h
This extends the corr_est block to take a threshold method as an argument.
* THRESHOLD_ABSOLUTE restores the previous function of this block.
* THRESHOLD_DYNAMIC provides the outlier detection algorithm that was later added.
This should resolve #1207
=> Restore ability to use absolute thresholding with corr_est

gr-digital/grc/digital_chunks_to_symbols.xml
chunks_to_symbols_XX_impl.cc.t contains code for a message sink port.  sink port for the same added in the GRC template.
=> Added template for message sink port for set_symbol_table in chunks_to_symbols

gr-audio/grc/audio_sink.block.yml, gr-audio/grc/audio_source.block.yml
This is just https://github.com/gnuradio/gnuradio/pull/1829 for YAML.
=> gr-audio: Changed KHz to kHz in block definitions

gnuradio-runtime/lib/logger.cc, gnuradio-runtime/lib/tpb_thread_body.cc, gr-fec/lib/generic_decoder.cc, gr-fec/lib/generic_encoder.cc
The log console appender looks for "stdout"/"stderr", not "cout"/"cerr".  The strings used are incorrect in various files, causing log output to often be directed to stderr even when the config file specifies stdout.
=> fix incorrect strings passed to the log console appender

gr-blocks/lib/CMakeLists.txt
My mistake by incorrectly solving a merge conflict; luckily, no harm is done: without CPPUNIT being looked for, the cmake variable resolves to nothingness without notice.
=> fix incorrect CPPUNIT inclusion

gr-digital/python/digital/qa_mpsk_snr_est.py
The test was relying on randint() to return the same integers, but since
Python 3.2 it doesn't. Now, we create bits using random.random(), which
will create reproducible bits across Python versions.
=> digital: mpsk_snr_est: Fix QA for Py2/3 compat

CHANGELOG.md, gr-analog/lib/fmdet_cf_impl.cc
To even edit this file, indents had to be sanitized a bit. Also,
commented-out code was removed. Also, 8.f is a constand and not really
longer than `d_8`.
This is the first in two changes necessary for #1817. The other would be
adding a unit test that is *slightly* more holistic than just doing a
single-tone frequency detection.
Note that there's much about this code that could be refactored,
starting with Sdot being a FIR-filtered version of the input.
=> Fixed wrong coefficient in Taylor series; cleanup (3.7 backport)

gr-blocks/lib/CMakeLists.txt, gr-uhd/examples/c++/CMakeLists.txt
Fixes "undefined reference to `pthread_condattr_setclock'"
=> Backport: Fix Boost 1.67 linking issues

gr-fec/lib/polar_common.cc
Unlike most of the other #1774-triggered fixes, this actually was an
effect of reading from unitialized memory. I'm surprised this worked as
intended!
Needs content-wise review from @jdemel!
=> polar_sc: Fix vector out of bound accesses

gr-fec/lib/polar_common.cc
Unless most of the other #1776-related fixes, this actually was an
effect of reading from unitialized memory. I'm surprised this worked as
intended!
Needs content-wise review from @jdemel!
=> backport: Fix vector out of bound accesses

gr-blocks/lib/float_to_complex_impl.cc, gr-digital/lib/clock_recovery_mm_cc_impl.cc, gr-digital/lib/crc32_bb_impl.cc, gr-digital/lib/crc32_bb_impl.h, gr-digital/python/digital/qa_crc32_bb.py, gr-fec/lib/polar_common.cc, gr-filter/lib/fft_filter.cc, gr-filter/lib/filter_delay_fc_impl.cc
On several systems, `_GLIBCXX_ASSERTIONS` leads to runtime aborts, e.g. when getting the pointer to the second output stream in a block that might be configured to only have one.
This patchset just remedies that.
=> Forward porting Out-Of-Bound access fixes to allow for more precise testing

gr-blocks/include/gnuradio/blocks/file_meta_sink.h, gr-blocks/lib/file_meta_sink_impl.cc, gr-blocks/lib/file_meta_sink_impl.h, gr-blocks/python/blocks/qa_file_metadata.py
This was necessitated by #1852
=> py3k conv: file_metadata_sink::make now accepts unserialized PMT

gr-blocks/lib/skiphead_impl.cc, gr-blocks/lib/skiphead_impl.h, gr-blocks/python/blocks/qa_skiphead.py
This PR addresses https://github.com/gnuradio/gnuradio/issues/959. In the current skiphead block, tags have incorrect offsets, this PR adjusts the offsets of all tags that pass through by the number of items skipped to ensure that tags stay correctly aligned.
=> Correctly handle tag offsets in the skiphead block

gnuradio-runtime/python/gnuradio/ctrlport/GNURadioControlPortClient.py, gnuradio-runtime/python/gnuradio/ctrlport/RPCConnection.py
It's not needed, not even with Python 2.7. It will fail with Python 3,
though.
=> ctrlport: Remove superfluous 'import exceptions'

gr-blocks/grc/blocks_multiply_const_xx.xml, gr-blocks/include/gnuradio/blocks/multiply_const_XX.h.t, gr-blocks/lib/multiply_const_XX_impl.cc.t, gr-blocks/lib/multiply_const_XX_impl.h.t
This block ignored the 'Vec Length' parameter and when trying to actually input a vector and set the 'Vec Length' accordingly it'd complain "ValueError: itemsize mismatch: multiply_const_cc0:0 using 8, complex_to_mag_squared0:0 using 8192".
=> gr-blocks: fix fast multiply block to allow vector input

gnuradio-runtime/include/gnuradio/basic_block.h
`basic_block::alias()` was not const, so I was unable to retrieve the alias of a block if I had only a const reference. This merge request fixes this. It should have no impact on any code.
=> make basic_block::alias() const

grc/core/cache.py
A previous change made GRC incompatible with Python2
If we want to only support Python3 greater or equal Python3.6 I could even revert 
the previous change since Python3 only support binary file mode for json.dump since Python3.6
=> grc: make cache dumping compatible across Py2/Py3

gnuradio-runtime/lib/math/gen_sine_table.py, gr-digital/examples/example_timing.py, gr-digital/python/digital/gmsk.py, gr-digital/python/digital/ofdm_receiver.py, gr-fec/python/fec/fec_test.py, gr-filter/python/filter/optfir.py, gr-trellis/docs/test_tcm.py, gr-trellis/examples/python/test_tcm.py
a previous change to py3k introduced syntactically incorrect
`old_div` function calls. A replacement with `//` and `/` where applicable is
more appropriate.
Eventually `from __future__ import division` needs to be added as well to have
the "real" division also for integer values in python
=> python: replace unfunctional old_div with functional code

gnuradio-runtime/swig/gnuradio.i
In Python2 numpy derives from the built-in fixed width integer type. In Py3k the integer type is variable width and thus NumPy does not derive its fixed-width types from it. 
As a result the numpy objects don't pass the PyLong_Check() necessary for conversion from Python to C/C++. 
Enabling SWIG_PYTHON_CAST_MODE enables casting by adding this code fragment: 
```
%#ifdef SWIG_PYTHON_CAST_MODE
{
int dispatch = 0;
long v = PyInt_AsLong(obj);
if (!PyErr_Occurred()) {
if (val) *val = v;
return SWIG_AddCast(SWIG_OK);
} else {
PyErr_Clear();
}
if (!dispatch) {
double d;
int res = SWIG_AddCast(SWIG_AsVal(double)(obj,&d));
if (SWIG_IsOK(res) && SWIG_CanCastAsInteger(&d, LONG_MIN, LONG_MAX)) {
if (val) *val = (long)(d);
return res;
}
}
}
%#endif
```
Withouth further investigation of sideeffects …
=> swig: fix numpy int conversion on py3k

gnuradio-runtime/include/gnuradio/pycallback_object.h, gnuradio-runtime/lib/pmt/unv_template.cc.t
adresses cases where initialization of uvec happened with empty
`std::vector`, as well as when getting the address of the first element
of an empty uvec, lead to undefined behaviour through doing `vec[0]` for
empty `vec`.
=> Fixed out-of-bound vector acces in PMT

gr-qtgui/grc/qtgui_waterfall_sink_x.block.yml
Building a waterfall sink fails with:
Generate Error: (NameError('Undefined',), ['set_frequency_range(${fc}, ${bw})', 'set_update_time(${update_time})', 'set_title(${which}, 
${title})', 'set_color(${which}, ${color})', 'set_intensity_range(${int_min}, ${int_max})'])
as there does not exist a title nor a color value entry.
=> Qt Waterfall YAML: remove setters for absent properties

gnuradio-runtime/lib/single_threaded_scheduler.cc
This was a bit of an early premerge that made its way in through an
optimization commit and removed the STS on master, which we'll only do by
merging next later.
This reverts commit 9ea30c8d94f006649ec4626cbc333e93e5c029a5.
=> Revert "gnuradio-runtime: Optimize some buffer[_reader]_sptr grabs and releases"

grc/gui/Application.py
On a parameter change of block , the block will not be updated correctly.
Example:
Open a new Flowgraph tab.
Add an  math add block. The default of the io ports is complex.
Open the property dialog and change the type of the io ports from complex to float and select OK.
Only the first input and the output port change from 'complex' to 'float'. The second input port remains 'complex'.
The only way to change the type of the second input port is to reopen the property dialog and select quit !!!!
Now the second port has the correct type.
The proposed change fixes this issue. But I'm not sure if there isn't a more elegant way to handle this issue.
=> Force to update all affected elements

grc/gui/Executor.py
If the executed script sends some ( error ) messages you get a lot of error messages like
File "/usr/local/gnuradio/lib/python3.6/dist-packages/gnuradio/grc/core/Messages.py", line 117, in send_verbose_exec
send(verbose)
File "/usr/local/gnuradio/lib/python3.6/dist-packages/gnuradio/grc/core/Messages.py", line 52, in send
messenger(_indent + message)
TypeError: must be str, not bytes
But you don't find out the reason of this error. The return type of os.read seems to have changed between python 2.7 and python 3.
The decode function fixes this issue and you get valuable messages.
=> Executor.py: decode stdout as UTF-8

gr-digital/examples/CMakeLists.txt
This fixes what 2345321 missed (remove the mpsk_demod from the installation
list)
=> remove deleted mpsk_demod.grc from install list

gr-uhd/lib/usrp_sink_impl.cc
This commit is intended to fix issue #1944, where superfluous
call to UHD's 'send' function causes problems with beginning
of bursty transmission.
Care is needed during the review as I changed some part
that seemed a bit strange (more in #1944) - so there is slight possibility
that maybe I didn't understand intention of the author.
Similar change will be needed also in the usrp_sink_impl::stop
function. However there it will be a bit more complicated as when stop
is called in the middle of the burst, the empty message ending the
transmission should actually be sent.
=> gr-uhd: fix first bursts transmitted by usrp_sink

cmake/msvc/sys/time.h
and is of unknown origin and quality.
Closes #1594.
=> Get rid of MSVC impl of gettimeofday that's used nowhere

gnuradio-runtime/include/gnuradio/basic_block.h, gnuradio-runtime/include/gnuradio/block.h, gnuradio-runtime/include/gnuradio/flowgraph.h, gnuradio-runtime/lib/block.cc, gnuradio-runtime/lib/flat_flowgraph.cc
Add identifier() calls to flowgraph components to return a string with a human
readable string to reuse in both: the std::ostream overload and the logging system.
=> runtime: replace compile-time debugging option by GR_LOG_DEBUG()

gr-qtgui/grc/qtgui_const_sink_x.block.yml, gr-qtgui/grc/qtgui_histogram_sink_x.block.yml, gr-qtgui/grc/qtgui_time_raster_x.block.yml, gr-qtgui/grc/qtgui_time_sink_x.block.yml, gr-qtgui/grc/qtgui_vector_sink_f.block.yml
This is really just https://github.com/gnuradio/gnuradio/pull/1969 for the remaining QT sinks that have this problem.
=> qtgui: Remove remaining problematic callbacks from sinks (next)

grc/gui/Actions.py, grc/gui/Config.py
If `~/.gnuradio/grc.conf` is not present when GRC starts, it will open in a tiny window:
Once that window is expanded, the block tree panel and console panel are hidden:
In this PR, I've changed the defaults so that a new user would begin with the GUI in a more usable state:
=> Give the GRC GUI a better default configuration.

grc/core/utils/extract_docs.py
If the worker process in extract_docs.py dies (which it currently does on my machine due to a segfault that occurs when `gnuradio.qtgui` is imported), its parent process doesn't realize that and enters into an infinite loop attempting to read its output. This causes 100% CPU utilization and makes GRC very sluggish.
In this PR, I've added a check which raises an `IOError` in the event that the worker process dies. After the change, extract_docs.py works as expected, relaunching the worker process in the event of crash, and eventually giving up after too many crashes occur.
=> Fix infinite loop when extract_docs worker dies.

grc/gui/ParamWidgets.py, grc/gui/canvas/param.py
Following the discussion in https://github.com/gnuradio/gnuradio/pull/1849, this PR introduces a switch widget for bool typed parameters. This is intended to replace enums with `True` and `False` options.
=> grc: Added switch widget for bool typed params

gr-blocks/include/gnuradio/blocks/CMakeLists.txt, gr-filter/include/gnuradio/filter/CMakeLists.txt
Some header files are not being installed, seems they were forgotten during gengen replacement, here: https://github.com/gnuradio/gnuradio/commit/1043222e0de551f00683a1cc9060f194adc4fc85 and https://github.com/gnuradio/gnuradio/commit/7588f103b9e75eea56d241868d161d0f04f3fd79
Perhaps @noc0lour will be able to tell quickly if this is correct.
I noticed this when fixing gqrx to compile against latest master.
=> gengen replacement: fix for not installed header files

gnuradio-runtime/examples/mp-sched/affinity_set.py, gr-audio/examples/python/spectrum_inversion.py, gr-digital/examples/narrowband/digital_bert_rx.py, gr-digital/examples/narrowband/digital_bert_tx.py, gr-digital/examples/ofdm/receive_path.py
Scanning Python code for deprecation warnings turned up a bunch of "Sorry: TabError: inconsistent use of tabs and spaces in indentation" and a couple "SyntaxError: EOL while scanning string literal". I've fixed those here. Together with #2047 this fixes all the deprecation warnings and errors identified by the following command:
```
find . -name "*.py" | grep -v "^./build/" | grep -v "^./volk/" | xargs python3 -Wd -m py_compile
```
=> Convert tabs to spaces and fix syntax errors.

cmake/Modules/GrSwig.cmake
We had a hack for working around a bug in old SWIG, but old SWIG is no
longer supported. We now require SWIG 3.0 and the bug only happened in
pre-3.0.
=> cmake: Remove superfluous code for old SWIG

grc/converter/flow_graph.py
This reverts a renaming experiment.
Due to conflicting naming of ports, connections couldn't be made.
This patch was done based on 100% pure Koslowski wisdom and under his
adult supervision.
This fixes #2023.
=> GRC: loading flow graphs now leads to connections, again

grc/blocks/grc.tree.yml
Fixes #2040.
Currently the Python Block doesn't appear in in the block tree panel. This adds it to the Misc category.
/cc @haakov
=> grc: add python block to misc category

gr-qtgui/include/gnuradio/qtgui/displayform.h, gr-qtgui/include/gnuradio/qtgui/form_menus.h, gr-qtgui/include/gnuradio/qtgui/waterfalldisplayform.h, gr-qtgui/lib/displayform.cc, gr-qtgui/lib/waterfalldisplayform.cc
In 1f857d30d5d73576070d70ad785cba3d505b2a73 no Qt signals were changed to the new unsigned indices so no GUI elements work...
=> qtgui: Change the signals and slots to unsigned as well

README.md, docs/doxygen/other/main_page.dox, docs/doxygen/other/usage.dox, gr-digital/examples/packet/README, gr-trellis/examples/python/README, grc/core/Config.py
Since the canonical website address is now https://www.gnuradio.org/ I've updated all the links, adding `www.` where necessary and upgrading `http` to `https`.
=> Update links to https://www.gnuradio.org

grc/gui/VariableEditor.py
The "Id" column in GRC's variable editor is a bit too narrow. I've increased the default width so that the `samp_rate` variable is fully visible in a new flowgraph.
Before:
After:
=> Widen the id column in the variable editor.

grc/gui/Bars.py
The GRC toolbar has a useless "Open a recently used flowgraph" button. It's greyed out and can't be clicked:
I've removed this button from the toolbar. This puts the recent files drop-down next to the open button, like it was in GNU Radio 3.7.
=> Remove "open recent" button from toolbar.

docs/doxygen/other/doxypy.py, docs/sphinx/hieroglyph/test/test_comments.py, gnuradio-runtime/python/gnuradio/ctrlport/monitor.py, gr-blocks/python/blocks/qa_cpp_py_binding.py, gr-blocks/python/blocks/qa_cpp_py_binding_set.py, gr-blocks/python/blocks/qa_ctrlport_probes.py, gr-digital/python/digital/qam_constellations.py, gr-filter/python/filter/design/filter_design.py, gr-utils/python/modtool/cmakefile_editor.py, gr-utils/python/modtool/modtool_disable.py, gr-utils/python/modtool/parser_cc_block.py, gr-utils/python/modtool/templates.py, grc/converter/cheetah_converter.py, tools/template_convert.py
Python produces the following warning when processing many of GNU Radio's .py files:
> DeprecationWarning: invalid escape sequence
I've fixed all these, mostly by using raw strings. In a couple cases, it was simpler to stick with an ordinary string and replace `\` with `\\`.
I compared the strings in Python before & after, so these changes shouldn't break anything.
=> Fix invalid escape sequences.

grc/core/utils/extract_docs.py
When GRC is started, a "subprocess is still running" warning appears, and a zombie process remains. This happens because `run_worker` terminates its subprocess, but does not call `wait()`.
https://github.com/gnuradio/gnuradio/blob/007923c64d2505b37dffb8e11cb1e3ecf4e489eb/grc/core/utils/extract_docs.py#L169
Adding a `wait()` call reveals further warnings because `run_worker` does not close the file handles it uses to communicate with the subprocess.
In this PR, I've added `close()` and `wait()` calls to eliminate the warnings.
The issue can also be reproduced by running `extract_docs.py` directly:
```
python3 -Wd grc/core/utils/extract_docs.py
```
=> Clean up resources allocated by run_worker.

grc/gui/Application.py
grc fails to open the source of an grc generated block with object has no attribute 'grc_source' due to an parameter error.
This is fixed here.
=> Make grc opening hierachal block source

gr-qtgui/grc/qtgui_time_raster_x.block.yml
Without these defaults set the block errors out when you run the flowgraph
=> gr-qtgui: 3.8- time raster sink: set default values for ncols and nrows

gr-analog/grc/analog_random_source_x.block.yml, gr-fec/grc/ldpc_decoder_def_list.block.yml, gr-fec/grc/ldpc_encoder_def_list.block.yml, gr-fec/grc/tpc_decoder_def_list.block.yml, gr-fec/grc/tpc_encoder_def_list.block.yml, gr-fec/grc/variable_cc_decoder_def_list.block.yml, gr-fec/grc/variable_cc_encoder_def_list.block.yml, gr-fec/grc/variable_ccsds_encoder_def_list.block.yml, gr-fec/grc/variable_dummy_decoder_def_list.block.yml, gr-fec/grc/variable_dummy_encoder_def_list.block.yml, gr-fec/grc/variable_ldpc_bit_flip_decoder.block.yml, gr-fec/grc/variable_ldpc_encoder_G.block.yml, gr-fec/grc/variable_ldpc_encoder_H.block.yml, gr-fec/grc/variable_polar_decoder_sc.block.yml, gr-fec/grc/variable_polar_decoder_sc_list.block.yml, gr-fec/grc/variable_polar_decoder_sc_systematic.block.yml, gr-fec/grc/variable_polar_encoder.block.yml, gr-fec/grc/variable_polar_encoder_systematic.block.yml, gr-fec/grc/variable_repetition_decoder_def_list.block.yml, gr-fec/grc/variable_repetition_encoder_def_list.block.yml, gr-fec/python/fec/qa_fecapi_dummy.py
Map now returns a generator in python3 instead of a list.
vector_source_x_make expects a list or tuple.
http://python3porting.com/differences.html#map
=> Wrap map with list for in various block yml files. Fixes #2036

gr-digital/lib/additive_scrambler_bb_impl.cc
There was a stray semicolon (line #103) on the closing brace of an if-block. Just an extra null statement after the if, so not a functional change.
=> Cosmetic change to additive_scrambler_bb_impl.cc

gr-blocks/grc/blocks_keep_m_in_n.block.yml, gr-blocks/lib/keep_m_in_n_impl.cc, gr-blocks/python/blocks/qa_keep_m_in_n.py
Currently the Keep M in N block requires the offset to be less than or equal to N-M. I've often found this restriction annoying, so I decided to remove it.
I also added a bounds check to ensure that the offset is >= 0, and made some improvements to the tests.
=> Allow the full range of offsets in Keep M in N

grc/core/schema_checker/block.py
Fixes https://github.com/gnuradio/gnuradio/issues/2101
=> grc: Add missing keys to schema checker to avoid warnings

grc/core/FlowGraph.py
imp module is deprecated as of Python 3.4 but in Python3 we can
use the ModuleType to create a new module.
=> grc: Remove deprecated use of imp module

.gitignore
This is a convenience edit, so that one can have multiple separate build
directories in one source tree, for example to test Py2 and Py3 in
parallel and compare build results.
=> .gitignore: ignore build*/ instead of just build/

gr-analog/grc/analog_random_source_x.block.yml
A bug was introduced in recently merged PR #2095, the ending parenthesis was put in the wrong spot.  I also added a little bit of documentation while I was at it, making sure people know this block isn't really a block but is a wrapper for Vector Source. 
If anyone has some time (@btashton perhaps), it might be worth checking the other files modified in #2095 to see if any other ending parenthesis were put in the wrong spot.
=> gr-analog: fixed analog_random_source bug

grc/core/FlowGraph.py
Turns out we can use types.ModuleType in python2 as well so we can remove all of the logic using the imp module.  Based on conversation at #2135
=> grc: Simplify py2/3 logic for new_module

gr-trellis/include/gnuradio/trellis/interleaver.h, gr-uhd/lib/gr_uhd_common.h
Includes in files depending on these headers will
be reordered after reformatting.
This change adds the missing includes before that
happens.
=> Add missing includes which will fail after reformat

gnuradio-runtime/swig/CMakeLists.txt, gr-analog/include/gnuradio/analog/CMakeLists.txt, gr-digital/include/gnuradio/digital/CMakeLists.txt
These subsequently appeared twice in install_manifest.txt, which lead to
warnings/errors on deinstallation.
=> CMake: remove duplicately installed files

cmake/Modules/GrSwig.cmake, gr-analog/python/analog/fm_emph.py
Resolves #2121 DeprecationWarning: invalid escape sequence /
=> Use raw strings for regexp and docstrings that have desired backslashes

docs/sphinx/source/index.rst, docs/sphinx/source/video_sdl_blocks.rst
Probably other stuff that needs to be cleaned up in the sphinx rst files (e.g. blocks missing), but at least now the sphinx docs will build.  Addresses issue #2118
=> docs: sphinx: removed video_sdl blocks so sphinx builds

grc/gui/Executor.py
In Py3k a string decode might trigger an error because it is already a unicode string. This is not the case in Py2k land. Thus, add a check.
This should fix #2078 .
=> GRC: fix failing thread run

gnuradio-runtime/lib/qa_buffer.cc, gr-digital/lib/timing_error_detector.cc
1) Remove uncessary BOOST_CHECK for bounds on ran1()
2) Pass an actual array to map_to_points() function in TED
=> Fix a few coverity issues

gr-blocks/lib/nlog10_ff_impl.cc, gr-blocks/lib/nlog10_ff_impl.h
This results in an order of magnitude improvement for the throughput.
Reviewed-By: Marcus Müller <marcus@hostalia.de>
Reviewed-By: Martin Braun <martin.braun@ettus.com>
=> gr-blocks: use libvolk to speed up nlog10_ff block

gr-fec/lib/viterbi/CMakeLists.txt, gr-fec/lib/viterbi/metrics.c
As `erf` is required in <cmath> since C++11
=> gr-fec: remove erf redefinition in metrics.c

cmake/Modules/FindQwt.cmake
The only way to be sure that FindQwt.cmake is finding the Qt5 version
of Qwt is to either
- limit the name to qwt-qt5 or
- have the user specify it when running CMake.
The latter is unimpeded by this change. However, by default, it'll now
skip libqwt.so on Fedora and Ubuntu systems, which is actually only
a valid library when using Qt4, not Qt5.
Fixes #2027.
=> cmake: qwt: Only allow qwt-qt5 as a library name

gnuradio-runtime/examples/mp-sched/wfm_rcv_pll_to_wav.py, gnuradio-runtime/python/gnuradio/ctrlport/GNURadioControlPortClient.py, gnuradio-runtime/python/gnuradio/ctrlport/monitor.py, gnuradio-runtime/python/gnuradio/eng_arg.py, gnuradio-runtime/python/gnuradio/eng_notation.py, gnuradio-runtime/python/gnuradio/eng_option.py, gnuradio-runtime/python/pmt/pmt_to_python.py, gr-dtv/examples/atsc_ctrlport_monitor.py, gr-fec/python/fec/LDPC/Generate_LDPC_matrix_functions.py, gr-filter/python/filter/qa_fft_filter.py, gr-qtgui/apps/uhd_display.py, gr-uhd/apps/uhd_app.py, gr-uhd/python/uhd/__init__.py, grc/converter/flow_graph.py, grc/core/FlowGraph.py, grc/core/blocks/block.py, grc/core/generator/hier_block.py, grc/core/generator/top_block.py, grc/core/params/param.py, grc/gui/Config.py, grc/gui/Dialogs.py, grc/gui/canvas/block.py, grc/main.py
This specifies actual exception types instead of just leaving them as:
```
except:
pass
```
There is also some very old unused threading code for py23 and py24 that is removed.  The changes around uhd will need a closer look, in some cases it is not clear what the expected Exception that is being passes is (hence why this issue is important).
=> python: Do not use bare except, specify exception instead

gnuradio-runtime/lib/buffer.cc
+ the former was augmented by the latter in Boost 1.58.0;
+ they do the same computation;
+ the former is being deprecated as of Boost 1.66.0, and recommends moving to the latter;
+ GR supports Boost 1.54.0 and newer, so we need to be able to support both APIs for now.
=> runtime: fix use of boost::math::gcd and boost::integer::gcd

grc/gui/Application.py
grc does not initialize the visibility of disabled blocks.
This  sometimes leads to stranges effects.
Toggling the visibility does not update the flowgraph. So this takes effect not until a change
to the flowgraph is made that forces an update of the flowgraph.
=> grc: Correctly toggle the visibility of blocks

CMakeLists.txt, gr-utils/python/modtool/gr-newmod/CMakeLists.txt
... and expand from just GNU to both GNU and Clang, since they work comparably for the flags being tested.
=> cmake: replace 'CMAKE_COMPILER_IS_GNUCXX' with CMAKE_CXX_COMPILER_ID

.clang-format
Similar the previous of  @mbr0wn . This time import the default llvm style and add already modified values. Now comment on values/discuss what we would like to change compared to the default.
It's possible these list is not complete, in this case please add more flags to the discussion.
Information about possible values and meaning can be found here: 
http://releases.llvm.org/3.9.0/tools/clang/docs/ClangFormatStyleOptions.html
=> formatting: Import clang-format -style=llvm -dump-config & add agreed on values

gr-blocks/grc/blocks_add_const_vxx.block.yml, gr-blocks/grc/blocks_multiply_const_vxx.block.yml
The 'add' and 'multiply' const blocks have different implementations in
C++ for vector- and scalar use cases. In GRC, there was only one type of
bindings. This commit fixes the switching between the vector- and scalar
versions. It also fixes the assertion error that would require users to
specify scalars as vectors of length one.
=> blocks: Fix add and multiply const blocks GRC bindings

gr-channels/grc/channels_channel_model.block.yml, gr-fft/grc/fft_fft_vxx.block.yml
- 'hide' attribute for fftshift was supposed to default to on for real
mode. It now really does.
- The actual FFT block doesn't have a vlen parameter, and it was causing
havok in the GRC bindings. It's now removed.
=> fft: Fix GRC bindings

gr-blocks/lib/integrate_impl.cc, gr-blocks/lib/vector_sink_impl.cc, gr-digital/lib/crc32_bb_impl.cc, gr-digital/lib/crc32_bb_impl.h, gr-dtv/lib/dvbt2/dvbt2_pilotgenerator_cc_impl.cc, gr-fec/lib/polar_common.cc, gr-qtgui/lib/time_sink_c_impl.cc, gr-qtgui/lib/time_sink_f_impl.cc, gr-trellis/lib/interleaver.cc
See #2120
Fixing compiler warnings, excluding volk. In submodule volk there exist more warnings.
=> Fix compiler warnings about unsigned / signed comparisons

gnuradio-runtime/lib/block_executor.cc
During the fix for long long on 32bit architectures a bug was introduced
which lead to offset being multiplied by (mp_rrate + one_half).
The correct solution is to multiply with mp_rrate and then add one_half.
Fixes #2201
=> runtime: Fix tag propagation

gr-blocks/python/blocks/qa_udp_source_sink.py
Running unit tests the sender socket could be created before the receiver socket
was ready. Try to avoid that by adding a sleep in between the receiver socket
creation and the sender socket creation.
=> udp: wait a short time after creating starting the receiver

gr-digital/include/gnuradio/digital/constellation.h, gr-digital/lib/constellation.cc
This is needed for QAM constellations which are used, _e.g._, on HF and have max(abs(points))<=1.
If such QAM constellations are normalized to have average magnitude 1, the channel equalizer gets disturbed when switching from 8-PSK to QAM modulation and vice versa.
=> rescale constellation points only if max(abs(points))>1

gr-trellis/include/gnuradio/trellis/interleaver.h, gr-trellis/lib/interleaver.cc
This complements the excellent work of #2198.
This is part of the ongoing effort to avoid signedness confusion.
It completes df4e7a85263eb523395ce6bef0b2e7769bd63465 in that it at
least strives to handle sizes consistently in interleaver.cc.
Of course, the returned vectors still contain signed ints where there
should be unsigned ints, but the trellis core_algorithms.cc code is
convoluted enough to warrant carefulness when touching, so this part of
the API was kept.
=> trellis interleaver: made table size unsigned int

gr-blocks/python/blocks/qa_udp_source_sink.py
Provide one unit test for the source and sink with the raw python
socket module.
Fix the tests on IPv4 only to avoid mismatched connections on IPv4 &
IPv6.
Fixes #2210.
=> blocks: fix the udp_source_sink test flakiness

gr-zeromq/lib/base_impl.cc, gr-zeromq/lib/pub_msg_sink_impl.h, gr-zeromq/lib/pull_msg_source_impl.h, gr-zeromq/lib/push_msg_sink_impl.h, gr-zeromq/lib/rep_msg_sink_impl.h, gr-zeromq/lib/req_msg_source_impl.h, gr-zeromq/lib/sub_msg_source_impl.h
The zeromq code as a whole code repeats itself a lot, but changing that would mean creating some new base classes and doing quite a bit of restructuring that I am not very comfortable doing.   This should remove the variable length array that is not allowed by MSVC.
=> gr-zeromq: Remove VLA from last_endpoint()

CMakeLists.txt
This will work on Ubuntu 16.04.
=> cmake: Bump minimum version of CMake to 3.5.1

gr-uhd/grc/CMakeLists.txt, gr-uhd/grc/gen_uhd_usrp_blocks.py
The YML file generated during CMake was simply not correct. Frequency,
gain, etc. weren't propagated properly to the underlying C++ object.
Fixes #2221.
=> uhd: Fix GRC bindings (gain, freq...)

gr-digital/python/digital/qa_ofdm_sync_sc_cfb.py
- Used a fixed random seed
- Removed messages that declare that failures aren't a big deal
- Removed some usage of channel.channel_model
- Fixed some Pylint warnings
- Factored out the creation of test vectors
Note: The SNR value for test_003_multiburst was slightly decreased, but
it's still high and given the fixed seed, it also won't matter.
Fixes #971.
=> digital: Fix ofdm_sync_sc_cfb QA flakiness

tools/clang_format.py
Imported the tools used by MongoDB developers to clean up their tree with some tweaks already for the GR source tree.
Using #1662 as base it will format all (.h|cc|c) files according to the `.clang-format` defined it the root directory of the source tree.
I'm not yet happy with the commandline interface and some intermediate functions have to be improved to pass my arbitrary "I can live with
that type of Python" standard.
I want to show in which direction repo tooling can go and get you guys involved/informed early.
=> Add clang_format_tool to tools/

gr-uhd/grc/gen_uhd_usrp_blocks.py
- The callback for gain would always use normalized gain, which would
cause errors since the non-normalized gain range would cause
exceptions
- The "Show Command Port" menu was removed, it didn't work, but no other
block has this.
Finally fixes #2221.
=> uhd: Fix even more GRC binding issues

gr-blocks/python/blocks/qa_keep_m_in_n.py, gr-blocks/python/blocks/qa_pack_k_bits.py, gr-blocks/python/blocks/qa_packed_to_unpacked.py, gr-blocks/python/blocks/qa_repack_bits_bb.py, gr-blocks/python/blocks/qa_socket_pdu.py, gr-blocks/python/blocks/qa_unpack_k_bits.py, gr-digital/python/digital/qa_binary_slicer_fb.py, gr-digital/python/digital/qa_clock_recovery_mm.py, gr-digital/python/digital/qa_constellation.py, gr-digital/python/digital/qa_constellation_receiver.py, gr-digital/python/digital/qa_constellation_soft_decoder_cf.py, gr-digital/python/digital/qa_costas_loop_cc.py, gr-digital/python/digital/qa_crc32.py, gr-digital/python/digital/qa_diff_encoder.py, gr-digital/python/digital/qa_fll_band_edge.py, gr-digital/python/digital/qa_ofdm_chanest_vcvc.py, gr-digital/python/digital/qa_ofdm_txrx.py, gr-digital/python/digital/qa_packet_headerparser_b.py, gr-digital/python/digital/qa_pfb_clock_sync.py, gr-filter/python/filter/qa_fft_filter.py, gr-filter/python/filter/qa_filterbank.py
This affects all Python-based unit tests which use the Python random
module. If they do, this change adds random.seed(0) to every setUp()
call, so that all QA runs are reproducible.
=> qa: Use random.seed(0) everywhere import random is used

gnuradio-runtime/lib/pmt/pmt_unv.cc, gr-audio/lib/windows/windows_sink.cc, gr-audio/lib/windows/windows_source.cc
This is a minor change towards slowly replacing Boost with newer std::
functionality.
=> C++11: Convert boost::lexical_cast to std::to_string

gr-fec/grc/variable_polar_encoder.block.yml
See https://github.com/gnuradio/gnuradio/issues/2260.
=> gr-fec: Fix the POLAR Encoder Definition block

CMakeLists.txt
The grc subdir was parsed last, making ENABLE_GRC appear false in all
components, thus disabling blocks.
Fixes #2259.
=> fixup! cmake: Only go into grc/ subdirs when ENABLE_GRC=ON

CMakeLists.txt
GR 3.8 requires CMake 3.5.1 but it contained a workaround for CMake < 3.1 in its root `CMakeList.txt` file which is now obsolete. Thus, this patch removes the now obsolete workaround.
=> cmake: remove obsolete code

grc/core/platform.py
Following the discussion from https://github.com/gnuradio/gnuradio/issues/2229. 
For the time being, GRC discards empty parameters when generating the `.grc` file. This PR alters this behaviour. I haven't tested if this creates any problems yet, but can't think of any off the top of my head. 
It will result in more cluttered `.grc` files though. @skoslowski what are your thoughts on this?
=> grc: Make GRC save blank parameters

gr-uhd/grc/gen_uhd_usrp_blocks.py
For some attributes in the GRC bindings, we'd skip the setters at make()
time when no value was given. This also adds this behaviour for the
antenna.
=> uhd: grc: Don't set antenna if no value is given

grc/core/generator/flow_graph.py.mako
eng_float params, e.g. "2.45G", are not recognized by Python and need to
be rendered as strings (with additional quotes). This is not true for
string types, which already have quotes, or regular floats and ints,
which do not need them.
=> grc: Fix rendering of eng_float params

gr-vocoder/python/vocoder/qa_codec2_vocoder.py
previously the encoder & decoder pair was tested for a known input to produce a
precomputed output. Which can change with improvements in the codec2 library.
A similar test for the decoder needs to be implemented
=> codec2: only check length of encoded messages in unit test

gr-filter/examples/channelizer_demo.grc, gr-filter/examples/filter_taps.grc, gr-filter/examples/resampler_demo.grc, gr-filter/grc/variable_band_pass_filter_taps.block.yml
This commit converts the examples in `gr-filter` to the new YAML format.
Also, in order to make all examples work, the YAML block definition for
the *band_pass_filter_taps* is updated.
=> filter: Convert GRC examples to YAML format

gr-zeromq/examples/zeromq_pubsub.grc, gr-zeromq/examples/zeromq_pushpull.grc, gr-zeromq/examples/zeromq_reqrep.grc, gr-zeromq/examples/zmq_msg.grc, gr-zeromq/examples/zmq_stream.grc
This commit converts the examples in `gr-zeromq` to the new YAML format.
=> zeromq: Convert GRC examples to YAML format

gr-blocks/examples/ctrlport/comparing_resamplers.grc, gr-blocks/examples/ctrlport/pfb_sync_test.grc, gr-blocks/examples/ctrlport/simple_copy.grc, gr-blocks/examples/ctrlport/usrp_source_control.grc, gr-blocks/examples/matrix_multiplexer.grc, gr-blocks/examples/metadata/file_metadata_sink.grc, gr-blocks/examples/metadata/file_metadata_source.grc, gr-blocks/examples/metadata/file_metadata_vector_sink.grc, gr-blocks/examples/metadata/file_metadata_vector_source.grc, gr-blocks/examples/msg_passing/hier/test_msg_hier.grc, gr-blocks/examples/msg_passing/hier/test_msg_hier_topblock.grc, gr-blocks/examples/msg_passing/strobe.grc, gr-blocks/examples/peak_detector2.grc, gr-blocks/examples/tags/test_tag_prop.grc, gr-blocks/examples/test_stream_mux_tags.grc, gr-blocks/examples/vector_source_with_tags.grc, gr-blocks/grc/blocks_file_meta_sink.block.yml, gr-blocks/grc/blocks_multiply_matrix_xx.block.yml
This commit converts the examples in `gr-blocks` to the new YAML format.
The assertion in `grc/blocks_multiply_matrix_xx.block.yml` to check if
the selected tag propagation policy and the given matrix are compatible
is disabled. This might be an issue with `dtype: enum` and its
resolution in Mako.
Change `Extra Dict.` dtype in `File Meta Sink` to `raw`. Also, put
`pmt.make_dict()` as argument. Otherwise these flowgraphs fail due to a
type error.
The example file `simple_copy_controller.py` seems to fail with Py3k. It
fails on a `postMessage` call. Though, this seems like another bug.
The flowgraphs in `examples/msg_passing/hier` are converted as well,
though hier block generations seems to be broken. In order to load
`test_msg_hier_topblock.grc` it is …
=>  blocks: Convert GRC examples to YAML format

CMakeLists.txt, grc/CMakeLists.txt
Two minor fixes for 3.8 to build on windows.
First just sets a compiler version, will error out later if the variable is empty
Second deals with the 8191 character limitation for command lines on windows by doing in 3 commands what could be otherwise done in one.
=> CMake: MSVC fixes for 3.8

gr-digital/examples/burst_shaper.grc, gr-digital/examples/demod/constellation_soft_decoder.grc, gr-digital/examples/demod/digital_freq_lock.grc, gr-digital/examples/demod/pam_sync.grc, gr-digital/examples/demod/pam_timing.grc, gr-digital/examples/demod/test_corr_est.grc
This commit converts the examples in `gr-digital` to the new YAML format.
Only the flowgraphs in `examples` and `examples/demod` are updated. Some
flowgraphs can't be opened due to some 'id' error.
=> digital: Convert GRC examples to YAML format

gr-qtgui/examples/qtgui_message_inputs.grc, gr-qtgui/examples/qtgui_multi_input.grc, gr-qtgui/examples/qtgui_tags_viewing.grc, gr-qtgui/examples/qtgui_vector_sink_example.grc, gr-qtgui/examples/test_qtgui_msg.grc
This commit converts the examples in `gr-qtgui` to the new YAML format.
=> qtgui: Convert GRC examples to YAML format

gr-audio/lib/windows/windows_sink.cc
So the windows audio sink was garbled when played from WAV files, but worked with other sources.  The flaw was my overlooking the details of "set_output_multiple()", which clearly indicates more than one chunk of data may be sent.  So the work() function was blindly overflowing, much to my (now) chagrin.
Easy fix... fill up one buffer at a time, and if no buffer is available, block if possible until one is.
The patch only affects windows audio, and can also be merged w/ master for 3.8
=> gr-audio: fix windows audio when receiving > 1 output_multiple per call

grc/gui/Actions.py, grc/gui/DrawingArea.py, grc/gui/canvas/block.py
PR for Issue #2346  
Currently, none of the hotkeys worked, which is fixed in this PR except for the two of them,
'Up': Actions.BLOCK_DEC_TYPE,
'Down': Actions.BLOCK_INC_TYPE.
I got the following error while fixing them
```
File "/home/aruroxx31/GNURadioGsoc/gsoc/lib/python3.6/dist-packages/gnuradio/grc/gui/Application.py", line 427, in _handle_action
if flow_graph.type_controller_modify_selected(-1):
File "/home/aruroxx31/GNURadioGsoc/gsoc/lib/python3.6/dist-packages/gnuradio/grc/gui/canvas/flowgraph.py", line 319, in type_controller_modify_selected
return any(sb.type_controller_modify(direction) for sb in self.selected_blocks())
File "/home/aruroxx31/GNURadioGsoc/gsoc/lib/python3.6/dist-packages/gnuradio/grc/gui/canvas/flowgraph.py", line 319, in <genexpr>
return …
```
=> grc: fix for GRC's block hotkeys

grc/core/generator/cpp_top_block.py
Without this fix, GRC isn't able to generate C++ flowgraphs.
I thought I did this in https://github.com/gnuradio/gnuradio/pull/2314. Apparently, I didn't :)
=> grc: Add missing GRC version to cpp_top_block.py

gr-utils/python/modtool/cli/update.py, gr-utils/python/modtool/core/update.py
When using the converter with gr-ieee802-15-4 (its modtool name is ieee802_15_4) the converter splits the file names of the GRC bindings after the first underscore. The change should split after the first underscore following the module name.
Also, I think `block_candidates` are not assigned when giving the block name directly on the command line.
=> Modtool Converter: support mod names w/ underscores

gr-utils/python/modtool/templates/templates.py
As mentioned by @drmpeg the category needs to be in quotes in the generated `.yml` file. 
The other changes are  just visual improvements on the generated files.
=> Modtool: Fix .yml template for grc bindings

grc/core/blocks/dummy.py
I accidentally merged an older version of PR https://github.com/gnuradio/gnuradio/pull/2278 while fixing a typo. This fixup brings in the correct changes to dummy.py
I wanted to get a second set of eyes to prevent a second mistake.
=> fixup! Modifying dummy block and error messages

cmake/Modules/UseSWIG.cmake
This is mainly beauty. It does come in handy when one fiddles with the
SWIGs too much and needs to figure out which .i broke.
=> SWIG: Output SWIG source being parsed file during build

gr-digital/examples/ofdm/ofdm_loopback.grc, gr-digital/examples/ofdm/rx_ofdm.grc, gr-digital/examples/ofdm/tx_ofdm.grc, gr-digital/examples/packet/burst_tagger.grc, gr-digital/examples/packet/example_corr_est.grc, gr-digital/examples/packet/example_corr_est_and_clock_sync.grc, gr-digital/examples/packet/example_corr_est_and_phase_sync.grc, gr-digital/examples/packet/formatter_crc.grc, gr-digital/examples/packet/formatter_ofdm.grc, gr-digital/examples/packet/packet_loopback_hier.grc, gr-digital/examples/packet/packet_rx.grc, gr-digital/examples/packet/packet_tx.grc, gr-digital/examples/packet/simple_bpsk_tx.grc, gr-digital/examples/packet/tx_stage0.grc, gr-digital/examples/packet/tx_stage1.grc, gr-digital/examples/packet/tx_stage2.grc, gr-digital/examples/packet/uhd_packet_rx.grc, gr-digital/examples/packet/uhd_packet_rx_tun.grc, gr-digital/examples/packet/uhd_packet_tx.grc, gr-digital/examples/packet/uhd_packet_tx_tun.grc, gr-digital/grc/digital_header_payload_demux.block.yml, gr-digital/grc/digital_ofdm_carrier_allocator_cvc.block.yml, gr-digital/grc/digital_ofdm_chanest_vcvc.block.yml, gr-digital/grc/digital_ofdm_frame_equalizer_vcvc.block.yml, gr-digital/grc/digital_ofdm_serializer_vcc.block.yml
This commit converts the examples in  `gr-digital/ofdm` and `gr-digital/packet` to the new YAML format.
=> digital/[ofdm/packet]: Convert GRC examples to YAML format

gr-utils/python/modtool/cli/add.py, gr-utils/python/modtool/core/info.py
cli `input()` replaced by `click.prompt()`, and parameters are now asked to be given in new line, thus fixing text wrap.
=> gr_modtool: Fix for parameter wrap in cli inputs

gr-utils/python/modtool/templates/templates.py
Update templates for Python blocks and Python QA code. Previously, these
templates created broken import statements. Also, a deprecated call to
`gr_unittest.run(...)` is updated to not include a filename argument
anymore. Finally, the python block signature generator was updated.
=> modtool: Update Python templates

gr-dtv/lib/dvb/dvb_bbscrambler_bb_impl.cc, gr-dtv/lib/dvb/dvb_bbscrambler_bb_impl.h, gr-dtv/lib/dvb/dvb_bch_bb_impl.cc, gr-dtv/lib/dvb/dvb_bch_bb_impl.h
DVB-S2X VL-SNR MEDIUM size frames are not divisible by 8.
=> dtv: Fix scrambler and BCH encoder for MEDIUM size frames.

grc/core/generator/flow_graph.py.mako, grc/gui/Dialogs.py, grc/gui/ParamWidgets.py
setStyleSheetFromFile requires a string as parameter.
While generating the python code the quotes are missing.
See #2439
=> Add missing quotes in themes parameter of option block and fix some depreciation warnings

gr-utils/python/modtool/templates/gr-newmod/CMakeLists.txt
Allows OOT's to compile with gcc 5.4 (Ubuntu 16.04).
=> modtool: Set C/C++ standard to 11 for OOT's.

gnuradio-runtime/lib/pmt/CMakeLists.txt
subject says it all. simple tweak, needed at least by OSX; should be required by -any- OS for correct linking of libpmt. Addresses #2450 .
=> pmt: needs to link with Boost::thread

gr-audio/lib/osx/osx_impl.cc, gr-audio/lib/osx/osx_sink.cc, gr-audio/lib/osx/osx_source.cc
subject says it all. simple tweak. Verified on OSX 10.14, but this will fix any OSX audio building. Addresses #2453 .
=> audio: fix build on OSX

gr-utils/octave/read_cshort_binary.m
Hi,
I was trying to read rather large complex<int16> recordings with **gr-utils/octave/read_cshort_binary.m** under _Ubuntu 18.04.2 LTS_ with a version of Octave 6.0.0 built from sources just today (18MAR2019) (_HG ID for this build is "1771bed38482"_), on a computer with:  _MemTotal: 32694812 kB_.
I kept getting memory overflows and Octave was quitting with the error message: 'octave exited with signal 6'.
I realized that, on the contrary, **gr-utils/octave/read_short_binary.m** _was_ able to read the same data which allowed me to play with the data, and I eventually managed to reduce the memory highest-water mark in the '...cshort...' function when compared to the peak usage induced by current code:
`cv = v(1:2:end)+v(2:2:end)*j;`
I'm copying a few logs below to give a more accurate …
=> Reduce peak memory usage of Octave function read_cshort_binary

CMakeLists.txt, gr-utils/python/modtool/templates/gr-newmod/CMakeLists.txt
When CMAKE_EXPORT_COMPILE_COMMANDS is ON, a file compile_commands.json
will be created in the build directory that enables code completion
engines to find all include directories and provide a very comprehensive
auto completion experience without any manual IDE configuration.
A nice example for this is the VS Code extension cpptools that is
developed by Microsoft. Of course this is not limited to VS Code and
works with other engines such as YouCompleteMe as well.
=> cmake: Enable CMAKE_EXPORT_COMPILE_COMMANDS

gr-blocks/grc/blocks_add_const_vxx.block.yml
The previous GRC yml description did not contain an entry for operation on
bytes.
Closes #2461, Closes #2354
=> blocks: add byte option to add_const_v in GRC

gr-analog/python/analog/fm_emph.py
An automatic conversion for python3 mangled the source and introduced a bug.
This commit fixes the conversion bug in fm_preemph. Changeset that lead to this
bug still has to be analyzed further.
Fixes #2286
=> analog: correct errors of automatic conversion script in fm_preemph

gnuradio-runtime/swig/CMakeLists.txt
This destination matches that from GrMiscUtils. Nice and simple tweak.
=> runtime swig: correct the destination for runtime_swigTargets.cmake

gr-blocks/python/blocks/CMakeLists.txt
Related to https://github.com/gnuradio/gnuradio/pull/1728 , but this one fixes just the conditions for CTRLPORT tests removal, and nothing more. Nice and simple!
=> blocks: QA: correct conditions for CTRLPORT tests removal

gr-blocks/lib/socket_pdu_impl.cc
NOTE: There have been multiple fixes proposed, such as https://github.com/gnuradio/gnuradio/pull/2451 . This one is the simplest and most compatible; it comes from < https://svnweb.freebsd.org/ports/head/comms/gnuradio/files/patch-gr-blocks_lib_socket__pdu__impl.cc?view=markup&pathrev=499093 >. With this fix, GR GIT master builds with Boost 1.70.0.
Fixes #2452
=> blocks: simple fix for Boost 1.70.0 in socket_pdu

gr-qtgui/grc/qtgui_entry.block.yml
Was calling toAscii on the text edit which was removed in QT5
=> qtgui: fix QT Gui Entry emitting signal when changed

gr-digital/grc/variable_header_format_default.block.yml
Since the first argument of the header_format_default object
is a uint64 but the template argument is a string, there is
some confusion and addition of unnecessary quotes
Fix by stripping the quotes with eval() in the var_make
Fixes #2052
=> digital: default header format object template issues

grc/blocks/variable_function_probe.block.yml, grc/core/Constants.py, grc/core/params/dtypes.py, grc/core/params/param.py
The inherent problem is that extra quotes are added when generating the python file - not sure if this is the best solution, but it wasn't clear how to make some string dtypes handled differently than others.  The 'block_id' can be handled as an 'id' dtype because it references another block.  The function name is slightly different, so I added a 'name' dtype with less restrictions than the 'id' dtype.  Please recommend a different solution if this is not preferable.
Due to the way stringify_flag is called, the block_id,
function_name and function_args are all given extra
quotes which cause issues when generating the python source
change/add new dtypes for function_probe
Fixes #1783
=> grc: function_probe_block extra quotes with block_id

gr-video-sdl/lib/CMakeLists.txt
Fixes minor typo in cmake file that only impacts MSVC
=> gr-video-sdl: Fixed typo in cmake (MSVC only)

gr-uhd/examples/c++/tag_source_demo.h
Replacing 'not' with '!' for msvc compatibility
=> gr-uhd: Replaced not with !

gr-blocks/lib/file_source_impl.cc
Adds some macros for compatibility w/ msvc.  The S_ISREF msvc macro is borrowed from curl.
I swear I saw someone else submit this patch for MSVC 2017 (it affects 2015 as well), but I can't find it so submitting again... but still possibly a duplicate.
=> gr-blocks: added fstat macros for msvc

gr-uhd/apps/uhd_fft
--update-rate is really a period, not a rate, from what I can tell.  Instead of changing the variable name, I just edited the argparse note to mention that the units are in seconds.
=> gr-uhd: fixed argparse note for uhd_fft --update-rate

cmake/Modules/GrPython.cmake
If both debug/release versions are present, cmake will failed with an error about the "optimized" keyword, essentially we have to pick a version when using the INTERFACE_LINK_LIBRARIES property.
So this does a quick check for that case, and links to Debug if Debug, and Release if anything else.
=> CMake: Fixes error when both debug and release python libs installed

gr-utils/python/modtool/core/info.py
Add version information detection to the part of the code being called by gr_modtool info
fixes #2403
=> modtool: add 3.8 version for info command

gr-zeromq/lib/base_impl.cc, gr-zeromq/lib/base_impl.h, gr-zeromq/lib/pull_msg_source_impl.cc, gr-zeromq/lib/pull_msg_source_impl.h, gr-zeromq/lib/rep_msg_sink_impl.cc, gr-zeromq/lib/rep_msg_sink_impl.h, gr-zeromq/lib/rep_sink_impl.cc, gr-zeromq/lib/req_msg_source_impl.cc, gr-zeromq/lib/req_msg_source_impl.h, gr-zeromq/lib/sub_msg_source_impl.cc, gr-zeromq/lib/sub_msg_source_impl.h, gr-zeromq/lib/zmq_common_impl.h
ZMQ deprecated some prototypes of "recv" and "send" in some version prior to 4.3.1. The "recv" one has been removed in 4.3.1 and thus generates an error since no valid prototype exists in the way we're trying to call "recv". This fix updates our usage of both calls to work with the "new" and "old" ways, depending on the ZMQ version. Move the ZMQ inclusion and a macro determine which version to use into a common header.
I'm not 100% sure this is the correct solution, but it works (for me on OSX) and is relatively straight forward to understand.
=> zeromq: fixes to allow building using CPPZMQ 4.3.1 as well as prior

gnuradio-runtime/lib/prefs.cc
This comes from helping a user on the mailing list (hi there, Gary),
who's been having severe problems with the Windows audio source; told
him to configure GNU Radio to use portaudio instead. He did - but GR
ignored his config file. Turned out that the hardcoded path to the
system config dir (set at built) doesn't match how it was installed on
Windows, and that prefs don't even try the user confs if they can't find
that directory. Fixed that.
=> runtime: prefs: parse user config even if sys conf dir isn't a directory

gnuradio-runtime/include/gnuradio/rpcmanager.h, gnuradio-runtime/include/gnuradio/rpcregisterhelpers.h
When building OOTs using GR, the compiler will complain about unused variables in the RPC headers. This PR "uses" those unused variables to make the compiler happy. We could do this by commenting out the variable in the prototype, or doing `(void) var;` ... in past discussions folks have preferred the latter.
=> RPC: "use" unused variables to make compilers happy

gr-blocks/grc/blocks_copy.block.yml, gr-digital/grc/digital_constellation_receiver_cb.block.yml, gr-qtgui/grc/qtgui_freq_sink_x.block.yml, gr-qtgui/grc/qtgui_sink_x.block.yml, gr-qtgui/grc/qtgui_vector_sink_f.block.yml, gr-qtgui/grc/qtgui_waterfall_sink_x.block.yml
The slider for 'Show Msg Port' worked the wrong way around. As it actually triggers a 'hide' in the Yaml, I've changed it to 'Hide Msg Port', so the behaviour and default value actually matches what is shown by the slider.
=> QtGui: fix 'Show Msg Port' slider

gr-utils/python/modtool/CMakeLists.txt
Previously cmake did not check if click is installed as it is a runtime
requirement. If CMAKE_CROSSCOMPILING is set the module checking is
skipped.
Closes #2292
=> cmake: check for python module click as dependency of modtool

gr-uhd/docs/uhd.dox
io_type_t was removed a while ago, but there was a reference to it in
the documentation which is now removed.
=> uhd: docs: Removed spurious reference to io_type_t

grc/gui/MainWindow.py
The existence of a gnuradio ( theme ) icon is checked, but if found not set.
So try to load the icon and if found set it.
=> Use gnuradio icon if available

grc/gui/Dialogs.py
log is undefined in Dialog.py. Use Messages.send instead.
This fixes the Name error described in @ #2536 and now a Message window will be displayed.
=> Fixing Name error in Dialog.py

README.md
When manually building from source:
CMake Error at CMakeLists.txt:420 (message):
VOLK required but not found.
=> Fix CMake Error "VOLK required but not found."

gr-uhd/include/gnuradio/uhd/usrp_block.h, gr-uhd/lib/usrp_block_impl.cc, gr-uhd/lib/usrp_block_impl.h, gr-uhd/swig/uhd_swig.i
This extends 87af011b, where we removed other deprecated types.
clock_config_t should have been removed then (same reason: It's
deprecated forever in UHD, and no longer available in the upcoming UHD 4.0).
=> uhd: Remove references to clock_config_t

gr-vocoder/examples/grfreedv.grc, gr-vocoder/examples/loopback-gsmfr.grc
Minor updates to the vocoder examples, namely swapping out the selector
block, but also enabling audio source instead of wav file
fixes #2531
=> vocoder: clean up examples for 3.8

gr-dtv/lib/dvbt/dvbt_inner_coder_impl.cc
Also remove assert that was failing for 7/8 rate on debug builds.
=> dtv: Remove superfluous set_relative_rate() in DVB-T inner coder.

gr-dtv/lib/dvbt/dvbt_inner_coder_impl.cc
Also remove assert that was failing for 7/8 rate on debug builds.
=> dtv: Remove superfluous set_relative_rate() in DVB-T inner coder (3.7).

grc/gui/MainWindow.py
A missing freedesktop icon is  not correctly handled.
Now check if icon exists before trying to load it.
This fixes #2586
=> grc: Load builtin icon if no freedesktop icon is found

gr-utils/python/modtool/CMakeLists.txt
It was hard to determine from the cmake output what python module was
missing. Let the error output be more exact.
=> Check seperately for click-plugins missing

grc/blocks/options.block.yml
If a flowgraph without  a gui is generated, this piece of code is generated
https://github.com/gnuradio/gnuradio/blob/cff05c36dfc3908c3933773ac789959050fae45e/grc/core/generator/flow_graph.py.mako#L417
But at the moment sys only will be imported if qt_gui is selected
=> grc: Generating a flowgraph with no gui requires to import sys, too

docs/usage-manual/COPYING
Fixes licensing bug where GFDL wasn't provided for usage-manual exported from wiki.
@777arc
=> Adding GNU Free Doc License to wiki-exported docs

gr-blocks/grc/blocks_null_sink.block.yml, gr-blocks/grc/blocks_null_source.block.yml, gr-fec/examples/ber_curve_gen.grc, gr-fec/grc/tpc_decoder_def_list.block.yml, gr-fec/grc/variable_cc_decoder_def_list.block.yml, gr-fec/grc/variable_cc_encoder_def_list.block.yml, gr-fec/grc/variable_dummy_decoder_def_list.block.yml, gr-fec/grc/variable_dummy_encoder_def_list.block.yml, gr-qtgui/grc/qtgui_ber_sink_b.block.yml, grc/blocks/grc.tree.yml, grc/core/FlowGraph.py, grc/core/blocks/block.py, grc/core/generator/cpp_top_block.py, grc/core/generator/top_block.py, grc/core/ports/port.py, grc/gui/Application.py, grc/gui/canvas/block.py, grc/gui/canvas/connection.py, grc/gui/canvas/flowgraph.py, grc/gui/canvas/port.py
@mormj work, just rebased onto origin/master.
<hr>
Bus ports had not been added back in since the refactor of grc
Hopefully this fully enables busports though there are still some
issues with the gr-fec flowgraphs
Fixes #2277
=> rebased #2598: grc: add busports back into 3.8

gr-uhd/include/gnuradio/uhd/CMakeLists.txt, gr-uhd/include/gnuradio/uhd/clock_config.hpp, gr-uhd/include/gnuradio/uhd/io_type.hpp, gr-uhd/include/gnuradio/uhd/usrp_block.h, gr-uhd/lib/usrp_block_impl.cc, gr-uhd/swig/uhd_swig.i
clock_config_t and io_type_t are UHD types that have been flagged as
deprecated, in some cases since 2012. UHD 4.0 will finally remove those
types.
In order to stay compatible with future versions of UHD without breaking
the GNU Radio APIs on this API-stable branch, we add the types directly
into GNU Radio. The implementation is such that the UHD version will be
used if available, and the GNU Radio version will be used otherwise.
=> uhd: Create compatibility layer for future UHD versions

CMakeLists.txt, grc/00-grc-docs.conf.in, grc/CMakeLists.txt, grc/gui/Config.py, grc/gui/PropsDialog.py
Here's an example of what it looks like.  Note that it's NOT a hyperlink, unfortunately adding a link to a Gtk TextView isn't straightforward, you have to create a tag within the text, then attach an event to that tag, and create the mouse click event.  For now the user will just have to copy/paste the URL (leaves less room for vulnerabilities anyway). 
<a href="https://ibb.co/L5sXJY3"><img src="https://i.ibb.co/X8Gr3jq/Screenshot-from-2019-07-15-15-34-39.png" alt="Screenshot-from-2019-07-15-15-34-39" border="0" /></a>
=> grc: added url to wiki page for each block in docs tab

gr-blocks/grc/blocks_random_pdu.block.yml, gr-blocks/include/gnuradio/blocks/random_pdu.h, gr-blocks/lib/random_pdu_impl.cc, gr-blocks/lib/random_pdu_impl.h
The use of chr() in the grc file for the mask
creates an invalid input to the random_pdu make
function
1) Change the inputs to unsigned char since this is a mask
2) Remove the chr() from the grc yml
I'm not entirely sure what the purpose of the chr(mask) in
the make function was, but it created invalid input
Instead just pass the bitmask directly
fixes #2557
=> blocks: random_pdu mask parameter fails under python3

gr-digital/examples/packet/uhd_packet_rx.grc, gr-digital/examples/packet/uhd_packet_rx_tun.grc
The example grc files have an incorrect parameter for framebits in the dec_hdr block. This is correct in packet_loopback_hier.grc. The files uhd_packet_rx.grc and uhd_packet_rx_tun.grc both contained this error since creation. This error causes the blocks to get in sort of a deadlock when receiving the header with the dummy FEC. I tested the blocks replacing the uhd blocks with a ZMQ block and running the TX and RX flowgraphs separately.
=>  Corrected framebits in dec_hdr block.

gnuradio-runtime/swig/CMakeLists.txt
subject says it all. simple and easy. Toby will have to figure out how to work around this change!
=> cmake: fix install dir of runtime_swig

grc/gui/canvas/flowgraph.py
Restores the gnuradio 3.7 copy/paste behavior where the variable name is
changed to x_# of the copied block if the name is in conflict.  The
issue in 3.8 was that blocks always got copied as variable_# even when
there was no conflict in naming
Fixes #2614
=> grc: restore copy/paste behavior

cmake/Modules/GrTest.cmake, gr-utils/python/modtool/templates/gr-newmod/docs/doxygen/Doxyfile.in, gr-utils/python/modtool/templates/gr-newmod/docs/doxygen/Doxyfile.swig_doc.in
Adds quotes to paths to prevent issues when the
user has a space in their OOT shell paths
Slight change to #2560 which should prevent CI from
broadly failing
Fixes #2443
=> modtool: put proper quotes when unescaped shell paths

grc/core/generator/cpp_top_block.py
Corrects the following bug:
GRC generates the C++ files in one directory above the desired path. So if you save your flowgraph to `~/grc/someflowgraph.grc`, you want your C++ files to end up in `~/grc/someflowgraph/someflowgraph.cpp` etc but they will end up in `~/someflowgraph/someflowgraph.cpp`.
=> grc/cppgen: Fix a bug where GRC would write to the wrong path

gr-blocks/lib/pdu_to_tagged_stream_impl.cc
Fixes https://github.com/gnuradio/gnuradio/issues/2120 except warnings in `volk` using gcc 8.3.0 on 64-bit linux.
=> Fix sign-compare warning in pdu_t_tagged_stream_impl.

grc/core/generator/cpp_top_block.py, grc/tests/test_yaml_checker.py
yaml.load() has been deprecated: https://msg.pyyaml.org/load
This PR gets rid of the following warning:
`YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.`
=> grc: Use yaml.safe_load() instead of yaml.load()

grc/core/blocks/block.py, grc/core/ports/port.py
Couple of leftover todos from the copy of busports code from 3.7
Add error checking into the port __init__ that is called when a busport is created
=> grc: clean up todos from busports

grc/blocks/options.block.yml
Hide the option to generate statically linked C++ code until building GNU Radio with - DENABLE_STATIC_LIBS=ON works again. (Unless someone already fixed it, unfortunately I didn't have time to test it)
=> grc/cppgen: Hide linking parameter

grc/CMakeLists.txt
Message about minimal python3 version said : 
python3 >= 3.6.5
but in grc/CMAkeLists.txt requirement variable is set to 3.6.6 if sys.version_info.major >= 3.
This patch fix this typo.
=> grc:CMakeLists: fix python3.6 min version

gr-channels/examples/channel_tone_response.grc, gr-digital/examples/demod/symbol_sync_test_complex.grc, gr-digital/examples/demod/symbol_sync_test_float.grc, gr-digital/examples/packet/packet_rx.grc, gr-digital/examples/packet/transmitter_sim_hier.grc, gr-digital/examples/packet/tx_stage3.grc, gr-digital/examples/packet/tx_stage4.grc, gr-digital/examples/packet/tx_stage5.grc, gr-digital/examples/packet/tx_stage6.grc, gr-digital/examples/packet/tx_stage6a.grc, gr-qtgui/apps/grc_qt_example.grc, gr-uhd/examples/grc/uhd_const_wave.grc, gr-uhd/examples/grc/uhd_fft.grc, gr-uhd/examples/grc/uhd_msg_tune.grc, gr-uhd/examples/grc/uhd_normalized_gain.grc, gr-uhd/examples/grc/uhd_siggen_gui.grc, gr-uhd/examples/grc/uhd_two_tone_loopback.grc, gr-uhd/examples/grc/uhd_wbfm_receive.grc
This PR should make some progress on #2228 .
Although, this does reveal some problems.
- Some examples in `gr-fec` are still not fixed because of bus ports. 
- `gr-fec/examples/fecapi_tagged_decoders.grc` causes GRC to throw an error. 
- `gr-trellis` examples rely on a removed block `blks2_rate_error`.
The only examples that are not converted yet should be in `gr-fec` and `gr-trellis`. All other examples should be done now.
GRC did not open some files in `gr-digital` because it threw an error.
> Error: (ValueError("invalid literal for int() with base 10:
> 'digital.packet_utils.default_access_code'",), '% if
> int(eval(access_code))==0:\nself.${id} = ${id} =
> digital.header_format_default(digital.packet_utils.default_access_code,\\\n${threshold},
> ${bps})\n% else:\nself.${id} = ${id} = …
=> xml2yaml: convert more GRC examples to YAML format

CMakeLists.txt
The current code fails when using the Ninja build system on Windows due to "/MP" and "/bigobj" being added to the compile definitions. They really are compilation options, and adding them as such in the CMakeLists.txt fixes the build error.
See the [Windows build for my in-development gnuradio conda-forge feedstock](https://dev.azure.com/rvolz/feedstock-builds/_build/results?buildId=50) for an example of the error.
=> Change /MP and /bigobj to compile_options for Ninja compatibility.

gr-analog/python/analog/fm_emph.py
In 3.8.0.0-rc2, the following error occurs when the FM Preemphasis block is used:
```
File "/home/argilo/Desktop/top_block.py", line 183, in <module>
main()
File "/home/argilo/Desktop/top_block.py", line 161, in main
tb = top_block_cls()
File "/home/argilo/Desktop/top_block.py", line 127, in __init__
self.analog_fm_preemph_0 = analog.fm_preemph(fs=samp_rate, tau=75e-6, fh=-1.0)
File "/home/argilo/prefix_next/lib/python3.6/dist-packages/gnuradio/analog/fm_emph.py", line 292, in __init__
g =        abs(1.0 - p1 * cmath.rect(1.0 / -w_0dB)) \
ZeroDivisionError: float division by zero
```
This happens because of a typo; `cmath.rect(1.0 / -w_0dB)` should be `cmath.rect(1.0, -w_0dB)`.
Related PR: #2480
=> Fix division by zero in fm_preemph

grc/core/FlowGraph.py, grc/core/default_flow_graph.grc, grc/core/params/dtypes.py, grc/gui/Application.py
Defaults as described in: https://github.com/gnuradio/gnuradio/issues/2558
**Bug warning:**
If you
1. create a new flow graph
2. save it without changing the ID (So that the ID is replaced by the file name)
3. open any block's parameter dialog
4. press "Cancel"
the Options block's ID will be reset to `default` again, and you will have to manually change the ID to be allowed to generate code from GRC.
I haven't had time to investigate why, but I believe this bug to be out of scope for this PR and perhaps related to https://github.com/gnuradio/gnuradio/issues/2061
=> grc: Introduce sensible defaults

gr-analog/python/analog/qa_fm_emph.py
The bug in #2674 could easily have been caught with a test. Here I've added some very basic tests for `analog.fm_preemph` and `analog.fm_deemph`. The first test is failing for now, but will pass once #2674 is merged.
=> Add basic tests for FM preemphasis and deemphasis

gr-qtgui/lib/freqdisplayform.cc
Running gr-filter/examples/filter_taps.grc
leads to
QObject::connect: No such signal FFTSizeMenu::whichTrigger(unsigned int)
This proposed change fixes this issue
=> Using correct signal in freqdisplayform.cc

grc/core/generator/cpp_templates/CMakeLists.txt.mako, grc/core/generator/cpp_top_block.py
In other words, use `-DKEY1=VAL1 -DKEY2=VAL2` instead of `KEY1=VAL1; KEY2=VAL2` for the CMake options parameter.
Mentioned here: https://github.com/gnuradio/gnuradio/issues/2613
=> grc/cppgen: Use cli-style CMake options

gr-qtgui/grc/qtgui_time_sink_x.block.yml, gr-qtgui/grc/qtgui_time_sink_x.block.yml.py
Somewhere along the line, the QT Gui Time sink lost enums in .grc going to yml.  Also some of the 3.8 color and marker defaults were not ideal, though probably need for discussion here - resets to 3.7 color/marker defaults.  The enums I think are necessary for usability.
- moves the line style parameters to the Config Tab
- fixes issue with green becoming the second color
=> qtgui: restore enums/defaults for QT GUI Time Sink

gr-fec/examples/ber_curve_gen_ldpc.grc, gr-fec/examples/polar_ber_curve_gen.grc, gr-fec/examples/tpc_ber_curve_gen.grc, gr-fec/grc/ldpc_decoder_def_list.block.yml, gr-fec/grc/ldpc_encoder_def_list.block.yml, gr-fec/grc/tpc_encoder_def_list.block.yml, gr-fec/grc/variable_cc_decoder_def_list.block.yml, gr-fec/grc/variable_ccsds_encoder_def_list.block.yml, gr-fec/grc/variable_dummy_decoder_def_list.block.yml, gr-fec/grc/variable_dummy_encoder_def_list.block.yml, gr-fec/grc/variable_ldpc_bit_flip_decoder.block.yml, gr-fec/grc/variable_ldpc_encoder_G.block.yml, gr-fec/grc/variable_ldpc_encoder_H.block.yml, gr-fec/grc/variable_polar_decoder_sc.block.yml, gr-fec/grc/variable_polar_decoder_sc_list.block.yml, gr-fec/grc/variable_polar_decoder_sc_systematic.block.yml, gr-fec/grc/variable_polar_encoder.block.yml, gr-fec/grc/variable_polar_encoder_systematic.block.yml, gr-fec/grc/variable_repetition_decoder_def_list.block.yml, gr-fec/grc/variable_repetition_encoder_def_list.block.yml
add list() around nested map expressions in yml
Without the extra list expressions, grc passes map objects
into the BER curve gen hier blocks, instead of lists
of the enc/dec objects, which is what it is expecting
The examples still will not work without the busports code, which is included in this PR
=>  fec: grc code generation for encoder/decode objects

gr-digital/grc/digital_constellation.block.yml
value parameter field has invalid reference to constellation_type
Cleaned up the yml, but probably needs some insight into the
yml generator
fixes #2494
=> digital: constellation object yml error

gr-utils/python/modtool/templates/templates.py, grc/core/platform.py
Moves the yaml file load inside the try block as recommended by @haakov 
Allows grc to open up when there is a bad yml file in an OOT
Fixes #2668
=> grc: prevent yaml parser errors from crashing grc

gr-blocks/lib/multiply_matrix_cc_impl.cc
The multiply_matrix_cc block was converting the values from the set
matrix to double when new_A matrix was expecting complex. Convert the
PMT to complex instead.
Without this fix, sending complex matrices to the multiply matrix block results in an exception
Backport to 3.7
=> blocks: fix multiply matrix complex set_A (3.7)

gr-blocks/lib/multiply_matrix_impl.cc
The multiply_matrix_cc block was converting the values from the set
matrix to double when new_A matrix was expecting complex.  Convert the
PMT to complex instead.
Without this fix, sending complex matrices to the multiply matrix block results in an exception
=> blocks: fix multiply matrix complex set_A

gr-qtgui/lib/CMakeLists.txt
The package is named **Qwt** not QWT.
So find_package(Qwt REQUIRED)  leads to
CMake Error at /usr/share/cmake-3.13/Modules/CMakeFindDependencyMacro.cmake:48 (find_package):
By not providing "FindQWT.cmake" in CMAKE_MODULE_PATH this project has
asked CMake to find a package configuration file provided by "QWT", but
CMake did not find one.
Could not find a package configuration file provided by "QWT" with any of
the following names:
QWTConfig.cmake
qwt-config.cmake
As the module is named FindQwt.cmake in gnuradio/cmake/Modules this patch fixes this issue.
=> Fix wrong package name

gr-uhd/apps/uhd_fft, gr-uhd/apps/uhd_siggen_gui
There are cases when the Qt-based apps in gr-uhd would crash because Qt
would try and load previous geometry settings which didn't exist. This
disables applying previous geometry if the setting is empty.
=> uhd: Skip restoreGeometry() when no previous settings exist

gr-utils/python/modtool/core/rm.py
Add import for cli_input as the cli is called in rm.py
I suspect that this should be pulled out into cli/rm.py but we'll stick
with the low risk fix for now, to be refactored later
Fixes #2652
=> modtool: restore rm functionality

grc/gui/DrawingArea.py
GRC was scrolling to the top of the canvas when clicking into the console or search tree then back into the canvas. The view reset to the top left.
Commented out one line in _handle_mouse_button_press in DrawingArea.py -
makes the problem go away.  Need some additional testing to verify this won't cause any other negative side effects.  
Fixes #2660
=> grc: prevent scrolling to top of canvas

gr-utils/CMakeLists.txt, gr-utils/python/modtool/CMakeLists.txt
Fix for https://github.com/gnuradio/gnuradio/issues/2646: Modtool is simply disabled if `click` and `click-plugins` can't be found. With this fix, modtool can also be enabled and disabled with `-DENABLE_GR_MODTOOL=ON/OFF` like the top-level modules. Looks like it works to me, but I don't know if this is the best way to do it. @noc0lour thoughts?
=> cmake: Don't abort everything when modtool can't find click

gnuradio-runtime/lib/block_detail.cc, gnuradio-runtime/lib/prefs.cc, gr-uhd/lib/usrp_block_impl.cc
Exceptions should be thrown by value and caught by reference.
Closes #2708
=> clang-tidy: Throw exceptions by value, catch by reference

gr-filter/grc/filter_pfb_channelizer.block.yml
When a Polyphase Channelizer is used in GRC, the generated Python code fails with the following error:
```
File "./channelizer.py", line 83
self.pfb_channelizer_ccf_0.set_channel_map([])\nself.pfb_channelizer_ccf_0.declare_sample_delay(0)
^
SyntaxError: unexpected character after line continuation character
```
This is due to a typo in the YAML file. I've replaced `\n` with an actual carriage return to fix it.
=> gr-filter: Fix a typo in the YAML for Polyphase Channelizer

gnuradio-runtime/include/gnuradio/block_gateway.h, gr-blocks/python/blocks/qa_python_message_passing.py
I looked into #2207. I'm not 100% sure what's going on under the hood, but it looks wrong to access member variables of a block in a different thread and wait for some random time in the hope that the block finishes.
I think with the 3.8 scheduler it should be possible to shutdown the flowgraph cleanly, i.e., the producer sends a `done` message to the system port of the consumer once it finishes.
With the current implementation that didn't work, since the consumer is Python block and the block gateway shadowed the system port. (It only checked the Python message handlers.)
I was not able to trigger the bug locally, but I think if the QA is still flaky, we might have an actual problem.
=> Fix system port for python blocks

gr-utils/python/modtool/templates/gr-newmod/CMakeLists.txt
It would be advantageous to not hard-code this, but that requires the
templates to be CMake-time configured.
=> 3.9. OOT needs to rely on 3.9

gr-utils/python/modtool/cli/base.py, gr-utils/python/modtool/tools/util_functions.py
This only applies to maint-3.8. Thankfully, 3.9 won't be Py2-compatible.
=> modtool: Py2 `input` means `eval`; use `raw_input` instead.

gr-blocks/lib/mute_impl.cc, gr-digital/lib/burst_shaper_impl.cc, gr-filter/lib/fir_filter.cc, gr-filter/lib/fir_filter_with_buffer.cc, gr-filter/lib/pfb_synthesizer_ccf_impl.cc, gr-filter/lib/qa_fir_filter_with_buffer.cc, gr-qtgui/lib/freq_sink_c_impl.cc, gr-qtgui/lib/time_sink_c_impl.cc, gr-qtgui/lib/waterfall_sink_c_impl.cc
Fixes #2743 by casting pointers passed to `memset` to `void*`.
=> Fix memset clearing non-trivial type gr_complex warnings in gcc-8

gnuradio-runtime/include/gnuradio/pycallback_object.h, gr-blocks/python/blocks/qa_cpp_py_binding.py, gr-blocks/python/blocks/qa_cpp_py_binding_set.py, gr-blocks/python/blocks/qa_ctrlport_probes.py
I forgot to port the ControlPort QA test to the new API.
I also noticed that the tests throw an exception with Python3 as RPC calls for strings use Python2 string conversion. This patch would switch to Python3 conversion but breaks Python2 compatibility. Not sure if there is a better solution... On the other hand `RPC_get_string` is only used in unit tests, so maybe it's *good enough*?
=> ControlPort QA

gnuradio-runtime/include/gnuradio/basic_block.h, gnuradio-runtime/include/gnuradio/pycallback_object.h
introduced in https://github.com/gnuradio/gnuradio/commit/c6cb3bbc35153a9635d69eddab0d252f7441b854
Since `d_rpc_vars` is of type `std::vector<boost::any>` the sptr was not constructed as before.
=> runtime: fixup errors from clang-tidy changes

gr-qtgui/grc/qtgui_tab_widget.block.yml
To make meaningfull use of the QTab_Widget it's necessary to make the id visible and changeable
=> Make Id visible in Tab_widget

gr-utils/python/modtool/templates/templates.py
This pull request adds a couple of improvements to the GRC YAML template in gr-modtool:
- Adds a missing "outputs:" key
- Removes redundant documentation
- Removes a couple of trailing whitespaces
=> modtool: Improve GRC YAML template

gr-qtgui/grc/qtgui_time_sink_x.block.yml, gr-qtgui/grc/qtgui_time_sink_x.block.yml.py
In 3.8, the config options for float message input on qt gui time sink
disappeared.  This updates the .py file that generates the yml for this
block to always have 1 channel of config options for float message and 2
channels of config options for complex message.
The auto-generated .yml code is not the prettiest, but imo it is better than having
special case for line1, then special case for line2, etc. in the generation script
Fixes #2796
=> qtgui: time sink config options for float message

gr-qtgui/grc/qtgui_edit_box_msg.block.yml
Although is_pair ( or is_static) is set to false the assertion always  fails if no key is set.
=> edit_msg_box not useable without setting an unneeded key.

grc/core/blocks/block.py
Fix a bug that left the type of some of multi-port (the cloned ports) unchanged when incrementing or decrementing block type.
=> update cloned port's dtype

gr-dtv/lib/dvb/dvb_ldpc_bb_impl.cc, gr-dtv/lib/dvb/dvb_ldpc_bb_impl.h
* use `uint16_t` instead of `int` for tables
* half the storage: should increase cache locality significantly
* prefer unsigned types for unsigned jobs (here: indexing)
* convert humongous macro to template function
* type safety
* found and eliminated unused variables
* cleaner code
* better compiler warnings
NB: This class came without ANY tests.
=> DTV: LDPC encoder: refactoring

gr-analog/python/analog/fm_demod.py, gr-uhd/apps/uhd_fft, gr-uhd/apps/uhd_rx_cfile, gr-uhd/apps/uhd_rx_nogui
I noticed a few bugs in gr-uhd's Python apps:
1. uhd_rx_cfile doesn't work at all in Python 3 because it uses the old `print` syntax in some places.
1. uhd_fft's "Scope" tab displays the channel names as `Re{Channel 0}` and `Im{Channel 0.5}` in Python 3 because of the change to the `/` operator.
1. Massive clipping occurs in uhd_rx_nogui's WFM receiver because it requests an audio gain of 20 (instead of the default of 1).
I've fixed these problems, and also cleaned up the whitespace in uhd_rx_nogui, which previously used a mixture of tabs and spaces.
=> gr-uhd: fix Python apps

grc/gui/Application.py
If you close a dialog without make a change, it restores the flow graph from the cache, but a new page has no cache so the flow graph disappears.
Here is where it loads from the cache:
https://github.com/gnuradio/gnuradio/blob/55c55fe3e17d556484ed9139e8e941a0da00f9c4/grc/gui/Application.py#L559
This fix saves the new page to the cache so it can be loaded from the cache in the future.
fixes #2762
=> Save the new duplicate page to the cache

grc/gui/ParamWidgets.py, grc/gui/canvas/param.py
This reverts commit 007923c64d2505b37dffb8e11cb1e3ecf4e489eb.
I like the convenience that these switch buttons introduced, however, they have raised the issue #2683. For the lack of better ideas on how to solve this, I suggest removing the switch buttons.
=> grc: revert "Added switch button for bool types"

gr-uhd/grc/gen_uhd_usrp_blocks.py
Due to the way the template interprets the stream_chans value as string,
it always returns True and the '[]' from stream chans was used as the
channels parameter.
With this change, channels in the case where stream chans is empty,
chans populates as before, which is range(num_chans)
Fixes #2789
Fixes #2612
=> gr-uhd: multichannel uhd object not populating channels

grc/core/params/dtypes.py
committing the fix suggested by @haakov 
Make gui_hint collisions show up as validation errors
As shown in #2287, when there are gui hint collisions, there are a flurry of error messages, whereas with this fix, the collisions are flagged in grc:
Fixes #2287
=> grc: validate gui hints

grc/core/FlowGraph.py
Was getting lots of evaluation error prints when using gr-digital
examples because the nested variables were not updated until rewrite()
and evaluate were called over and over
Seems to fix the issue to update the flowgraph namespace variable after
each variable block is evaluated
I believe this also removes a previous issue (#2634) where rewrite
had to be called twice when data was being imported
Here is a situation that created the ugly printout:
would print out
```
[ERROR] Failed to evaluate variable block rxmod (FlowGraph.py:233)
File "/share/gnuradio/grdev/src/gnuradio/grc/core/FlowGraph.py", line 227, in renew_namespace
value = eval(variable_block.value, namespace, variable_block.namespace)
File "<string>", line 1, in <module>
AttributeError: …
```
=> grc: update namespace properly for nested variables

grc/gui/canvas/block.py, grc/gui/canvas/flowgraph.py
previously the extent (upper left und lower right bounding points)
only included blocks, ports and connections.
fix for #2854
=> grc: include comments in flowgraph extent calculation (fixes #2854)

gr-vocoder/include/gnuradio/vocoder/freedv_api.h
add support for the development branch (master) of codec2 but still
maintaining compatibility with version 0.8.1.
The unique way that I know to enable or disable `extern "C"` is to
check codec2 version but the version bump was not synchronized with
the implementation therefore you should always use the latest commit.
This fix should also be merged into `maint-3.8`.
=> codec2: development (master) branch support

gr-blocks/grc/blocks_transcendental.block.yml
The default is complex_double, or float. The former is rarely used in
GNU Radio, hence, it is not a good default.
=> blocks: transcendental: Default to complex_float in GRC bindings

grc/tests/test_block_flags.py
Since sets are unordered, checking the string representation character-wise fails randomly. 
Partially addresses #2678.
=> GRC: testing: can't rely on set ordering; sets are unordered

CMakeLists.txt, gr-qtgui/CMakeLists.txt
There was an unneeded find_package(PythonLibs 2) in the gr-qtgui
CMakeLists.txt that was occasionally causing issues building the
demo when python3 was targeted.  We should just be using the
GrPython module anyway that was already included.
Signed-off-by: Brennan Ashton <bashton@brennanashton.com>
=> cmake: Remove find package for pythonlibs in gr-qtgui

grc/blocks/variable_config.block.yml
This porblem has been mentioned in #2782. `ConfigParser` was replaced by `configparser` in Python 3 and therefore "Variable Config" block doesn't work. Renaming the import fixes it.
=> grc: fix importing configparser in variable config block

gnuradio-runtime/include/gnuradio/block_gateway.h
Just a small change to let you call set_max_output_buffer from pure Python blocks
=> add set_max_output_buffer to block gateway

grc/core/blocks/embedded_python.py
grc: embedded python parameter values disappear
fixes #2765
=> grc: embedded python parameter values disappear

grc/core/generator/flow_graph.py.mako
I finished porting bokehgui to the 3.8 and python3.
The previous version imported the bokeh_layout module under an alias but I couldn't reproduce it, so I removed the alias and put the actual module name in its place.
I've tested it with python3 but not python2. I'm not sure if it would change something.
There was a previous PR for that but I mistakenly deleted the related branch, leaving the commit orphan and untestable
=> Module name correction for bokehgui (redone with proper branch)

gr-uhd/grc/gen_uhd_usrp_blocks.py
In the 3.8 gen_uhd_usrp_blocks.py generated an invalid statement for the
set_gain callbacks, so they were never rendered to the output py.
Fixes #2791
=> qtgui: usrp source gain callbacks not rendered

grc/core/blocks/embedded_python.py
It is necessary to have access to the show_id flag for a python module
in grc to be able to access it elsewhere.  This adds the flag when the
module object is created in the block library.
=> grc: embedded python module show_id flag

grc/core/utils/extract_docs.py
The _encoding_ argument in _json.loads_ is ignored and deprecated since Python 3.1 and will be removed in Python 3.9 [[ref.](https://docs.python.org/3/library/json.html#json.loads)]. Hence, GRC built from master is throwing a lot of warnings currently about that when using Python 3.8.
https://github.com/gnuradio/gnuradio/blob/0bb482acbecb722f227e257606589b0395a32706/grc/core/utils/extract_docs.py#L201
https://github.com/gnuradio/gnuradio/blob/c750d104d938cc6f3c09417022f132676f6646e4/grc/core/utils/extract_docs.py#L271
=> grc: remove deprecated encoding argument from json.loads

gr-qtgui/grc/qtgui_chooser.block.yml
In gnuradio 3.7 it was possible to select an option as default option.
In 3.8 /3.9 the default option is always option 0.
This pr enables to choose a default option different from option 0
=> Reintroduce default setting in qtgui_chooser

gr-utils/python/modtool/core/add.py, gr-utils/python/modtool/core/disable.py, gr-utils/python/modtool/core/rm.py, gr-utils/python/modtool/templates/templates.py
Fixes `gr-modtool add` so that it adds C++ QA files based on the qa_cpp_boostutf (Boost UTF) templates and not qa_cpp (CppUnit) in GR 3.8 projects.
Fixes #2722
=> modtool: Use Boost UTF templates for GR 3.8

CMakeLists.txt, cmake/Modules/GnuradioConfig.cmake.in, cmake/Modules/GrBoost.cmake
Functions provided by boost unit_test_framework are only used when ENABLE_TESTING is set. Otherwise this library is not used.
This patch add unit_test_framework only if it's mandatory, and adds an option set ton ON by default to avoid wrong detection.
=> cmake: add boost unit_test_framework required only when ENABLE_TESTING=ON

grc/core/Messages.py, grc/core/platform.py
closes #2900 
As mentioned in the issue, use `flowgraph.get_error_messages()` to print a nice error summary when loading a flowgraph in `grcc` raises an exception. I wanted to add the functionality of the `_flowgraph_error_report` function to the `Element` class for child classes to use, but the Messages module is not imported in `Element`.
**Normal output:**
```
$ python3 ~/gnuradio/grc/scripts/grcc -o /tmp/grtest ~/gr-tutorial/examples/tutorial2/grc_files/tutorial_two_2.grc
Running from source tree
<<< Welcome to GNU Radio Companion Compiler 3.9.0.0-git >>>
Block paths:
/usr/local/share/gnuradio/grc/blocks
>>> Loading: /home/kvothe/gr-tutorial/examples/tutorial2/grc_files/tutorial_two_2.grc
>>> Generating: /tmp/grtest/tutorial_two_2.py
```
**Error Output after disconnecting some …
=> grc: report flowgraph loading errors nicely in grcc

cmake/Modules/FindLOG4CPP.cmake
This bug breaks `gr-iio` build in Arch Linux.
This was partially fixed in 23bf13685faabe40fed4314534ae71936cdbeece.
Apparently, proper capitalization is hard :)
=> Fix Log4Cpp cmake dependency

cmake/Modules/GrBoost.cmake
Tested Boost 1.71 against the master branch.  All tests pass.
Also, Boost_ADDITIONAL_VERSIONS is an input to FindBoost, so should come before calling it.
=> cmake: add boost 1.71 as acceptable version

cmake/Modules/GrPython.cmake
Fixes #2006
This is exactly the same logic as is used in volk. Also the same logic
used for the GR_PYTHON_RELATIVE just below ... so if it works for those
on all OSes/config, no reasons it won't work here.
Signed-off-by: Sylvain Munaut <tnt@246tNt.com>
=> cmake: Use standard way of getting python prefix

gnuradio-runtime/lib/math/gen_sine_table.py
Fixes commit 48d535e9d9d95524b2c8ed35b44c7eda541aea68
=> runtime: fix python math script generating wrong sine table

gnuradio-runtime/lib/logger.cc
gr.logger.add_file_appender offered use of the truncation flag but did not use it in the creation of log4cpp::FileAppender. Added the bool append as an argument.
closes #2989
see: http://log4cpp.sourceforge.net/api/classlog4cpp_1_1FileAppender.html
```
Script started on 2020-01-01 14:11:37-06:00 [TERM="xterm-256color" TTY="/dev/pts/0" COLUMNS="130" LINES="32"]
❯ echo "TEST\nTEST\nTEST" >> /tmp/logfile.log
❯ cat /tmp/logfile.log
TEST
TEST
TEST
❯ python3
Python 3.7.3 (default, Apr  3 2019, 05:39:12)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from gnuradio import gr
>>> log = gr.logger('log')
>>> log.set_level("DEBUG")
>>> log.add_file_appender('/tmp/logfile.log', True, "%r :%p: %c{1} - %m%n")
>>> log.debug('This should append')
gr::log …
```
=> gr: enable truncation option with add_file_appender

gr-audio/lib/portaudio/portaudio_source.cc
This is also part of https://github.com/gnuradio/gnuradio/pull/2976, but maybe cleaner to merge this PR on its own, as it's easier to review.
=> gr-audio/portaudio_source: Fix lock acquisition

gnuradio-runtime/python/gnuradio/gr_unittest.py, gr-analog/python/analog/qa_sig_source.py
This is related to https://github.com/gnuradio/gnuradio/pull/2897 (just noticed that the fix might apply to master as well - I'll leave the other PR open as well. Either merging both or backporting this yields to same results)
The call inside this assert was using a generator inside the standard all(),
which was always returning False, and silently passing the test, instead of
actually asserting in fail. Changing to list comprehension for assertion raising
Fixes #2883
=> runtime: fix gr_unittest floatAlmostEqual

grc/scripts/freedesktop/CMakeLists.txt
A compliant desktop will always look in the hicolor theme:
https://specifications.freedesktop.org/icon-theme-spec/latest/ar01s03.html
=> cmake: don't install a duplicate set of icons into the gnome theme

cmake/Modules/GrPython.cmake
Feeding CMake strings directly into Python strings can cause errors when the CMake strings contain unintentional escape sequences that then get interpreted by Python. This bit me when building on Windows where native paths use backslashes and I was unlucky enough to have a "\U" interpreted as a missing unicode character.
This patch makes the Python strings where this happens into raw strings so that the escape sequences are not unintentionally interpreted.
=> Use raw strings for paths substituted directly into python strings.

gr-filter/include/gnuradio/filter/fft_filter.h, gr-filter/lib/fft_filter.cc, gr-filter/lib/fft_filter_ccc_impl.cc, gr-filter/lib/fft_filter_ccc_impl.h, gr-filter/lib/fft_filter_ccf_impl.cc, gr-filter/lib/fft_filter_ccf_impl.h, gr-filter/lib/fft_filter_fff_impl.cc, gr-filter/lib/fft_filter_fff_impl.h
This reduces amount of code, and risk of dangling pointers and memory leaks.
I thought I'd do this one to get opinions. It takes a while (especially with custom deleter), so don't expect me to do all of it at least at this point. :-)
=> gr-filter/fft_filter: Use smart instead of raw pointers

cmake/Modules/targetConfig.cmake.in
If GNU Radio is compiled with Thrift, cmake fails in OOTs in all but the first run. AFAIS, Thirft libraries and paths are cached but not the target (not sure if this is possible at all). So cmake fails with
```
CMake Error at lib/CMakeLists.txt:36 (add_library):
Target "gnuradio-foo" links to target "Thrift::thrift" but the target was
not found.  Perhaps a find_package() call is missing for an IMPORTED
target, or an ALIAS target is missing?
```
=> cmake: don't cache thrift found

gnuradio-runtime/include/gnuradio/random.h, gnuradio-runtime/lib/math/random.cc, gr-blocks/lib/message_strobe_random_impl.cc, gr-blocks/lib/message_strobe_random_impl.h, gr-blocks/lib/random_pdu_impl.cc, gr-blocks/lib/random_pdu_impl.h, gr-channels/grc/channels_fading_model.block.yml, gr-channels/grc/channels_selective_fading_model.block.yml, gr-channels/grc/channels_selective_fading_model2.block.yml, gr-channels/include/gnuradio/channels/fading_model.h, gr-channels/include/gnuradio/channels/selective_fading_model2.h, gr-channels/lib/fading_model_impl.cc, gr-channels/lib/fading_model_impl.h, gr-channels/lib/flat_fader_impl.cc, gr-channels/lib/flat_fader_impl.h, gr-channels/lib/selective_fading_model2_impl.cc, gr-channels/lib/selective_fading_model2_impl.h, gr-channels/lib/selective_fading_model_impl.cc, gr-channels/lib/selective_fading_model_impl.h
C++11 offers all the random variates that we used from boost, but with a far less awkward interface.
In the course of this, a lot of unused includes were found.
Since this not only changes API in gr-channels, but might also have subtle consequences on the random sequences generated, this is **not** backportable to maint-3.8
=> Deboostify random

gnuradio-runtime/examples/volk_benchmark/volk_math.py, gnuradio-runtime/examples/volk_benchmark/volk_plot.py, gnuradio-runtime/examples/volk_benchmark/volk_types.py
I tested this as much as I know how, but I'm not that familiar with gnuradio so I can't cover all the cases. Unit tests seem to be unaffected for me, but let me know if I'm missing any additional testing I can make.
Part of #1466
=> volk: Replace star imports with explicit imports

grc/blocks/variable_function_probe.block.yml, grc/core/params/dtypes.py
The block_id parameter for the block being probed was being validated as
a block_id.  But there is a use case where this can be blank to call a
function on the flowgraph object itself.
Changed the block_id dtype to "name" just like function_name.  Could
have just changed it to raw and done no validation, but that doesn't get
displayed very nicely in the grc block
Fixes #2966
=> grc: loosen the validation of block in function probe

gr-digital/lib/additive_scrambler_bb_impl.cc, gr-digital/python/digital/qa_scrambler.py
See commit messages. Consider to ignore whitespace changes (``git diff -w``) when viewing the diff.
=> Fix for #2926: Additive scrambler reset by count

gr-utils/python/modtool/core/add.py
Currently tagged stream blocks are not implemented
for python in modtool.  There is a nasty exception
that happens, so this is intended to validate
and throw the appropriate exception before
trying to generate the block
Addresses #2489
=> modtool: prevent tagged_stream under python

gr-blocks/grc/xmlrpc_server.block.yml
The **XML RPC Server** block will not work in a python3-based GNU Radio installation, because of this:
> **Note** The SimpleXMLRPCServer module has been merged into xmlrpc.server in Python 3.
> (Source: https://docs.python.org/2/library/simplexmlrpcserver.html)
This PR fixes the issue and works correctly in Python 3.
NB: This should probably also make its way into maint-3.8, but I'm new to the party... please let me know if I should resubmit in a different way to achieve this.
=> gr-blocks: SimpleXMLRPCServer was moved in Python3

CHANGELOG.md, gr-digital/lib/ofdm_mapper_bcv_impl.cc, gr-digital/lib/ofdm_mapper_bcv_impl.h, gr-digital/lib/qa_header_format.cc, gr-trellis/lib/interleaver.cc
Continuation of https://github.com/gnuradio/gnuradio/pull/2594/commits.
To quote @rear1019:
This is the last pull request to fix issue #1841. Changes in gr-digital and gr-trellis can be considered as API changes: User-visible behavior is modified. However, no code modifications in GNU Radio or OOT modules are required (as far as I can tell).
=> Replace rand() by gr::random() (maint-3.7 branch)

grc/blocks/grc.tree.yml
I noticed that GRC was outputting the following error upon opening the Options block's properties dialog:
```python
File "/usr/local/lib/python3.8/dist-packages/gnuradio/grc/gui/PropsDialog.py", line 210, in update_gui
self._update_docs_page()
File "/usr/local/lib/python3.8/dist-packages/gnuradio/grc/gui/PropsDialog.py", line 220, in _update_docs_page
if self._block.category[0] == "Core":
IndexError: list index out of range
```
This happens because the Options block's category is just an empty list. 
A side effect of this PR is that the Options block now shows up in the right-hand block list. However, when trying to add another Options block to the flowgraph, the original block is just moved. In other words, no duplicate is created.
Investigate: 
- …
=> grc: Add Options block to (Core) Misc category

gr-fec/lib/async_decoder_impl.cc
When using async_decoder with a CC decoder with k = 7 and no input byte packing, the frame size of the underlying FEC decoder is set incorrectly to a too large value. This causes out of bounds accesses which corrupt the heap.
The context of this bug is as follows. When using the FECAPI Async Decoder with a CC Decoder to perform Viterbi decoding of frames with r=1/2, k=7 terminated CC, no input byte padding and unpacked output, for some frame sizes the heap is quickly corrupted by the decoder, causing a segmentation fault. The flowgraph [here](https://gist.github.com/daniestevez/98d397a3076decd8243677f31ae014c1) reproduces this bug. It will segfault under maint-3.8 (and most likely GNU Radio 3.7 and `master`), and doesn't segfault with this patch applied.
This is a longstanding issue. I …
=> FECAPI Fix heap corruption bug in async_decoder

gr-fec/lib/async_decoder_impl.cc
When using async_decoder with a CC decoder with k = 7 and no input byte packing,
the frame size of the underlying FEC decoder is set incorrectly to a too large
value. This causes out of bounds accesses which corrupt the heap.
=> apply: Fix heap corruption bug in async_decoder

gr-digital/include/gnuradio/digital/pfb_clock_sync_ccf.h, gr-digital/include/gnuradio/digital/pfb_clock_sync_fff.h, gr-digital/lib/pfb_clock_sync_ccf_impl.h, gr-digital/lib/pfb_clock_sync_fff_impl.h
This API call was deprecated a long time ago and contained a warning
that it will be removed, so we're now being true to our promise.
This also fixes a compiler error in SWIG *if* you have old headers
installed that SWIG will find (instead of the ones in the source tree).
Note: I saw this compiler bug and it drove me crazy. SWIG shouldn't be using installed headers :anger:
=> digital: pfb clock sync: Remove deprecated set_taps() API call

gr-fec/python/fec/qa_fecapi_cc_buffer_overflow.py
Adds a QA test that tries to detect the kind of buffer overflows in the CC decoder that were fixed in #2965.
The decoder is run with different frame lengths, and several frames are tried to be decoded for each frame length. The test is considered successful if it doesn't segfault or abort.
=> gr-fec: Add QA test for buffer overflow in CC decoder

gnuradio-runtime/lib/prefs.cc, gnuradio-runtime/lib/sys_paths.cc, gnuradio-runtime/python/gnuradio/gr/qa_prefs.py, grc/gui/Config.py
When looking for the config file, allow the env variable
GR_PREFS_PATH to be searched so that multiple installations
of GR each with its own prefs can be used, similar to what
is currently done in GRC
There is much more work to be done in redesigning the prefs module
but just adding a env variable to point the user generated conf 
file to a different location seems like a low hanging fruit to allow better
usage with multiple installations on one machine.  This change can also
be backported to 3.8 perhaps
=> runtime: add GR_PREFS_PATH env variable search

grc/scripts/freedesktop/CMakeLists.txt
At the moment an install script for the freedesktop icons is generated but not executed, so the icons are missing. This sometimes leads to missing icons or even errors . ( See #2536 )
Executing the generated freedesktop installaition script will fix this problem.
=> Execute generated freedesktop install script

gnuradio-runtime/python/gnuradio/gr/qa_uncaught_exception.py
Prior to this, the unit test was flaky, especially when running the test
suite concurrently, as test setup could take more than 0.5 s.
=> Exception Handling QA: increase wait time to ensure error could've occured

gr-blocks/examples/tags/tagged_file_sink.grc
Simple flowgraph to start and stop via a checkbox the saving of a file
to the tagged file sink block
Just needed a simple flowgraph to test another PR, so why not include it as an example of how to use the tagged stream file sink:
=> blocks: add example flowgraph for tagged_file_sink

gnuradio-runtime/include/gnuradio/logger.h
Oldie but a goldie:
Macro containing
logger << "something " << msg << "\n";
will happily break code in hard-to-understand ways, since `<<` has
higher precedence than binary, comparison and logical operators.
I wouldn't have opened this PR if this hadn't cost me 10 precious minutes
before....
=> logging: (msg) to avoid logged statement taken apart by operator precedence

CMakeLists.txt, grc/scripts/freedesktop/CMakeLists.txt
This option allows disabling post-install tasks. Currently, there is one
such task: The execution of `grc_setup_freedesktop install`.
For developers building from source, this is very convenient to do
during installation. However, for package maintainers, this is not
desired and should be executed separately. Maintainers of packages can
thus provide ENABLE_POSTINSTALL=OFF to avoid permission errors.
This continues bc0592b6, which defaulted to always running the script.
See the discussion in https://github.com/gnuradio/gnuradio/pull/2580/files.
=> cmake: grc: Provide ENABLE_POSTINSTALL option

gnuradio-runtime/lib/buffer.cc
Previously, stream tags would be lost (not propagated downstream) when a block has a tag delay set and it is called with a number of input samples that is less than the delay. Since this happens depending on the scheduler and the number of samples provided, tags might mostly work or seemingly randomly disappear. The problem occurs because a wrong correction is included for underflows in unsigned arithmetic that limits the tags propagated to a smaller sample window than desired. Correctly detecting the underflow and setting the value to 0 rather than abs_start or abs_end fixes the problem.
For a real example, let the `d_attr_delay=209`, `abs_start=0`, and `abs_end=200` with a tag at input sample `0`. Then tags from `min(abs_start, abs_start - d_attr_delay) == 0` to `min(abs_end, abs_end - …
=> runtime: Fix get_tags_in_range for (end - start) > delay.

gnuradio-runtime/include/gnuradio/attributes.h
Relatively simple change, which should help MSC builds when using Clang.
1) put clang before GNUC, to keep their settings separate, because some clang defines GNUC.
2) change from clang to "clang but not MSC", because MSC attributes are covered in a later clause.
Related to: https://github.com/gnuradio/volk/commit/7abdaa5da2ab236ed8acfe361d04021050146778#commitcomment-36709586 and https://github.com/gnuradio/volk/pull/325
=> runtime: fixup attributes for Clang, GNUC, and MSC

gr-digital/examples/ofdm/tx_ofdm.grc, gr-digital/grc/digital_ofdm_cyclic_prefixer.block.yml, gr-digital/include/gnuradio/digital/ofdm_cyclic_prefixer.h, gr-digital/lib/ofdm_cyclic_prefixer_impl.cc, gr-digital/lib/ofdm_cyclic_prefixer_impl.h, gr-digital/python/digital/qa_ofdm_cyclic_prefixer.py
This allows to specify multiple CP lengths that can be used one
after another, for example for LTE modulators.
- Improve sanity checking
- Maintains old API
Continuation of https://github.com/gnuradio/gnuradio/pull/1748.
=> digital: ofdm: Allow multiple CP lengths for cyclic prefixer

gr-digital/lib/costas_loop_cc_impl.cc
Use `std::norm(z)` instead of `(z*std::conj(z)).real()`. This should be faster (except for compiler optimizations) as the imaginary part is not computed and it is also easier to read.
The only downside is that the poorly named `std::norm` can lead to confusion.
This is based on fdb80ea8d32497a358b8787f47f1c70bcf18bb21.
=> gr-digital/costas_loop: use std::norm for |z|^2

gr-utils/python/modtool/cli/add.py
When I attempt to create a Python block with `gr_modtool` in GNU Radio 3.8, I get the following error:
```
$ gr_modtool add
GNU Radio module name identified: foo
('sink', 'source', 'sync', 'decimator', 'interpolator', 'general', 'tagged_stream', 'hier', 'noblock')
Enter block type: sink
Language (python/cpp): python
Language: Python
Enter name of block/code (without module name prefix): bar
Block/code identifier: bar
Please specify the copyright holder: Clayton Smith
Enter valid argument list, including default arguments: 
Add Python QA code? [Y/n] 
File "/home/argilo/prefix_next/bin/gr_modtool", line 30, in <module>
cli()
File "/home/argilo/.local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
return self.main(*args, **kwargs)
File …
```
=> modtool: ensure add_py_qa and add_cc_qa are booleans

gr-qtgui/python/qtgui/range.py.cmakein
The warning shows up in Python 3.8:
```python
/usr/local/lib/python3.8/site-packages/gnuradio/qtgui/range.py:41: SyntaxWarning: "is not" with a literal. Did you mean "!="?
precision = len(temp) if temp is not '0' else 
```
=> qtgui: Replace "is not" with "!=" to get rid of warning

gr-utils/python/modtool/templates/gr-newmod/CMakeLists.txt
https://github.com/gnuradio/gnuradio/pull/2624 accidentally left the version information misaligned in modtool. This PR fixes the spacing to line up the components again.
This fix should be applied to the master branch as well.
=> modtool: fix alignment of version info

gr-blocks/lib/rotator_cc_impl.cc
Fixes https://github.com/gnuradio/gnuradio/issues/2748.
Replaces https://github.com/gnuradio/gnuradio/pull/3056.
Since GNU Radio 3.8 appears to be stuck with VOLK 2.0.0's broken rotator implementation, I propose to work around the problem by not using VOLK in the rotator block. It seems to me that it's better to have a slow rotator block than one that doesn't work at all.
This workaround is not needed on the master branch, since it already uses VOLK 2.1.0, which has a functioning rotator kernel.
@mbr0wn @michaelld @devnulling
=> gr-blocks: work around broken rotator in VOLK 2.0.0

gnuradio-runtime/include/pmt/pmt.h
Class with misspelling comperator had been replaced with the proper
spelling comparator and a note to remove in 3.8.  Removing it here
=> pmt: remove dead typo code

CMakeLists.txt
Fixes:
```
Install the project...
-- Install configuration: "Release"
-- Installing: /home/user/sdr/installs/v3.15.0.0_filter_examples/share/doc/gnuradio-3.9.0.0-git/README.md
CMake Error at cmake_install.cmake:41 (file):
file INSTALL cannot find
"/home/user/sdr/installs/v3.15.0.0_filter_examples/src/gnuradio/README.hacking":
No such file or directory.
Makefile:128: recipe for target 'install' failed
make: *** [install] Error 1
```
From: https://github.com/gnuradio/gnuradio/commit/14779d119ae0abc06814724d513de78a0b5b5f87
=> cmake: fix toplevel cmake for CONTRIBUTING

gr-dtv/lib/atsc/atsc_equalizer_impl.h
The 'true' and 'false' values are implicitly cast to the integer type.
See atsc_equalizer_impl.cc
=> gr-dtv: atsc_equalizer_impl: bool not int

gr-audio/lib/alsa/alsa_sink.cc
It is int snd_pcm_nonblock(snd_pcm_t *pcm, int nonblock)
=> alsa_sink: fix always true check

gr-filter/examples/CMakeLists.txt, gr-filter/examples/polyphase_channelizer_demo.grc
- Fixes up cmake for `gr-filters/examples` to install a few files that were missing
- Renames `channelizer_demo.grc` to be `polyphase_channelizer_demo.grc`
Minor tweaks to `polyphase_channelizer_demo.grc`:
- Sets QT layout for Freq sinks
- Adds `Noise Source` and `Throttle Block`
- Adds Labels to each of the Freq sinks
- Disables Autoscaling on the Ch2 Freq sink block
=> examples: fixup filters cmake and polyphase channelizer demo

gr-blocks/examples/matrix_multiplexer.grc, gr-digital/examples/demod/constellation_soft_decoder.grc, gr-digital/examples/demod/symbol_sync_test_complex.grc, gr-digital/examples/demod/symbol_sync_test_float.grc, gr-dtv/examples/uhd_rx_atsc.grc, gr-uhd/examples/grc/uhd_fft.grc, gr-uhd/examples/grc/uhd_msg_tune.grc, gr-uhd/examples/grc/uhd_siggen_gui.grc
After the way the default value was configured for QT GUI Chooser, this did not propagate correctly in flowgraphs that use it.  
The new "default" value was set to whatever open 0 was set to, then option 0 was set to "0"
This fixes the example flowgraphs only, not the underlying problem that made the new behavior not update automatically
Fixes #3027
=> Chooser default value change in example flowgraphs

gr-filter/lib/freq_xlating_fir_filter_impl.cc, gr-filter/lib/freq_xlating_fir_filter_impl.h
Re-ordered work call to let rotate take advantage of volk.  Rather than rotating individually with each for, the rotate happens after with a rotateN to use the volk version for the data.  Removed decimation() function stack push/pop with each loop iteration.
=> Filter: Improve Performance in xlating FIR Filter

gr-blocks/examples/CMakeLists.txt, gr-blocks/examples/ctrlport/CMakeLists.txt, gr-blocks/examples/msg_passing/CMakeLists.txt, gr-blocks/examples/tags/CMakeLists.txt, gr-channels/examples/CMakeLists.txt, gr-digital/examples/CMakeLists.txt, gr-dtv/examples/CMakeLists.txt, gr-fec/examples/CMakeLists.txt, gr-filter/examples/CMakeLists.txt, gr-qtgui/examples/CMakeLists.txt, gr-trellis/examples/grc/CMakeLists.txt, gr-uhd/examples/grc/CMakeLists.txt, gr-vocoder/examples/CMakeLists.txt
- Adds a few missing examples to cmake to be installed
- Reorders install lists to be mostly alphabetical for easier auditing
=> examples: fixup cmake files to include all examples

gr-filter/examples/filter_taps_loader.grc
Follow up PR for: https://github.com/gnuradio/gnuradio/pull/3095#issuecomment-576033781
This adds an import block with:
`import subprocess`
And sets the file path to be:
`subprocess.getoutput("gnuradio-config-info --prefix") + "/share/gnuradio/examples/filter/filter_taps_example_complex_bandpass_taps"`
=> examples: fixup filter_tap_loader with subprocess path trick

grc/gui/PropsDialog.py
Check that the category list is not empty before accessing its first
element. Some OOT modules does not have category key and documentation
tab is left empty because of this missing check.
```
File "/usr/local/lib64/python3.7/site-packages/gnuradio/grc/gui/PropsDialog.py", line 210, in update_gui
self._update_docs_page()
File "/usr/local/lib64/python3.7/site-packages/gnuradio/grc/gui/PropsDialog.py", line 220, in _update_docs_page
if self._block.category[0] == "Core":
IndexError: list index out of range
```
=> grc: Display documentation for blocks without category key

gr-fft/lib/qa_fft_shift.cc
gr-fft mixes in Boost 1.59 dependency, but we only guarantee 1.53
Addresses https://github.com/gnuradio/gnuradio/issues/2685
=> fft_shift: use unit test macros that exist in Boost 1.53

gr-digital/python/digital/qa_header_payload_demux.py
Tests nees to run until both payload_sink and header_sink recive the
specified amount of data or the time limit is reached and should not
stop when only one of the sinks has received enough data.
This should fix the sporadic tests failures.
Fixes #2215
=> qa: Fix the stop condition in qa_header_payload_demux

gr-fec/lib/reed-solomon/init_rs.c
=> gr-fec:  reed-solomon: check for null calloc

gr-fft/lib/fft.cc
In c++11 the static_assert takes two parameters while in c++17 a version
with only one parameter was added
https://en.cppreference.com/w/cpp/language/static_assert
Compilation on CentOS 7 with gcc 4.8.5 [fails with](https://ci.gnuradio.org/buildbot/#/builders/59/builds/439/steps/7/logs/stdio)
gr-fft/lib/fft.cc:164:62: error: expected ',' before ')' token
static_assert(sizeof(fftwf_complex) == sizeof(gr_complex));
=> fft: Add message to static_assert

gr-utils/python/blocktool/cli.py, gr-utils/python/blocktool/core/base.py, gr-utils/python/blocktool/core/parseheader.py
My setup here is Ubuntu 19.10 with gcc-9 which may come into play as to why these changes were needed
1) pygccxml was throwing "invalid constraint in asm" related to boost
to resolve this had to add the define BOOST_ATOMIC_DETAIL_EXTRA_BACKEND_GENERIC
without this you get a bunch of:
```
/usr/include/boost/atomic/detail/extra_ops_gcc_x86.hpp:56:50: error: invalid output constraint '=@ccc' in asm
: [storage] "+m" (storage), [result] "=@ccc" (res)
^
/usr/include/boost/atomic/detail/extra_ops_gcc_x86.hpp:80:50: error: invalid output constraint '=@ccc' in asm
: [storage] "+m" (storage), [result] "=@ccc" (res)
```
also had to add -std=c++11, which without that you get
```
/usr/include/c++/9/bits/stl_function.h:418:6: error: use of undeclared identifier '__builtin_is_constant_evaluated'
if …
```
=> blocktool: minor convenience changes and resolve some parsing errors

gr-blocks/grc/blocks_freqshift_cc.block.yml
This yml adds a convenience-wrapper block to provide volk-accelerated frequency shifting based on the rotator block that doesn't require the user to "import math" and code the "2*Pi*freq/samp_rate" as the phase increment.  I don't think newbies know a rotator with a phase increment results in a frequency shift (I didn't for the longest time) and may be relying on less CPU-efficient means such as a signal source/multiply or a frequency xlating fir filter (the latter one-sample-at-a-time rotates as it decimates rather than leveraging volk to do a block).
=> Rotator-based Freq Shift Convenience Wrapper

gr-blocks/grc/blocks_probe_signal_vx.block.yml, gr-blocks/grc/blocks_probe_signal_x.block.yml
Continuing the discussion from https://github.com/gnuradio/gnuradio/issues/2766, this PR makes the ID visible for the Probe Signal and Probe Signal Vector blocks, as suggested by @ThomasHabets: https://github.com/gnuradio/gnuradio/issues/2766#issuecomment-550528435
=> blocks: Add show_id flag to Probe Signal (and Vector)

gr-digital/grc/digital_constellation_modulator.block.yml, gr-digital/python/digital/generic_mod_demod.py, grc/gui/Dialogs.py
The generic mod implementation is a convenience hier block to modulate
bits to symbols and apply an RRC filter.  One downside is the output is
delayed by the length of the RRC filter (which is specified inside the
block).  This adds an option to truncate the output according to the
length of the filter response such that the start of output is aligned to the first symbol.
For instance, with the following flowgraph:
the output bursts are not aligned:
But when the truncation flag is set, the pulses are now aligned because the filter response was sent through a skip head:
And we get aligned bursts of 00001111 as we would expect
Fixes #2920
=> digital: add filter response truncation to generic mod

gr-fec/python/fec/LDPC/Generate_LDPC_matrix_functions.py
read_alist_file is not an LDPC_matrix method.
=> Properly read AList in LDPC_matrix

gr-filter/grc/CMakeLists.txt, gr-filter/grc/filter_fft_root_raised_cosine_filter.block.yml
This new convenience wrapper takes advantage of the performance
gains of using an FFT-Based rather than a FIR-based filter for
Root Raised Cosine filters.  The RRC taps are generated just like
the FIR-Based RRC but passed to an FFT filter instead.
=> Add FFT-based Root Raised Cosine Convenience Wrapper

gr-digital/grc/digital.tree.yml
Previously the block wasn't part of any category and thus it was
only possible to find it by searching for it using some
filter string, not by clicking trough the categories.
All credits for finding and describing this bug to Johannes Wegener
aka @hpfmn.
=> gr-digital: Fix typo in block tree for 'Correlate Access Code - Tag'

gr-fec/include/gnuradio/fec/cc_encoder.h, gr-fec/lib/cc_encoder_impl.cc
The first commit should fix #2344. The second improves the documenation about the way the generator polynomials are represented. Someone should carefully proofread this. Confusion over the polynomials seems to be a known issue [1][2][3].
[1] https://lists.gnu.org/archive/html/discuss-gnuradio/2015-09/msg00001.html
[2] https://web.archive.org/web/20160407002340/https://gnuradio.org/redmine/issues/841
[3] https://lists.nongnu.org/archive/html/discuss-gnuradio/2017-03/msg00250.html
=> Fix CC Encoder for K > 8 and improve documentation

gr-analog/grc/analog_quadrature_demod_cf.block.yml
A default gain value of `samp_rate/(2*math.pi*fsk_deviation_hz/8.0)` was added to the Quadrature Demod block in f06367bcf0c2b414295e8ef46c4b8dda1bbe559e. The division by 8.0 causes the output value to vary between -8 and +8, which is inconvenient because the convention in GNU Radio is to work with signal that vary between -1 and +1. Therefore, I propose to remove it.
=> gr-analog: fix default gain in quadrature demod

gr-analog/examples/fm_rx.grc, gr-analog/examples/fm_tx.grc, gr-analog/examples/noise_power.grc
I've converted the fm_tx and fm_rx examples to YML, and also made a few
corrections so that the flow graphs work properly:
* increased the output sample rate from 200k to 400k to fix distortion
* added missing deemphasis to fm_rx
* removed superfluous division by 8.0 from quadrature demod in fm_rx
* increased output volume in fm_rx from 0.2 to 1.0
After these changes, a dial tone is heard when running fm_tx followed
by fm_rx.
I also lined up the blocks in the noise_power flow graph.
=> gr-analog: clean up examples

grc/core/utils/expr_utils.py
This fixes the failing test, but I haven't had time to investigate if this causes any side effects yet.
Cause:
None is less than everything in Python 2, but not in Python 3: https://docs.python.org/3/whatsnew/3.0.html#ordering-comparisons
=> grc: Attempt to fix test_expr_utils

gr-blocks/lib/throttle_impl.cc, gr-blocks/lib/throttle_impl.h, gr-blocks/python/blocks/qa_throttle.py
To ensure that the Throttle block operates normally even if the system clock changes, I've switched it to use `std::chrono::steady_clock`, which is a monotonic clock.
Prior to this change, setting the system clock back would stop the throttle, and setting it ahead would allow a large burst of samples to pass through the throttle.
This change also rids the Throttle block of Boost.
=> gr-blocks: use monotonic clock for throttle

gr-dtv/examples/uhd_atsc_capture.grc, gr-dtv/examples/uhd_atsc_tx.grc, gr-dtv/examples/uhd_rx_atsc.grc, gr-dtv/lib/atsc/atsc_fpll_impl.cc
The ATSC RX flowgraph has been fixed to allow for proper decoding.
The original flowgraph had rate mismatches between the RX filter
and the FPLL block that prevented proper decoding. This version
also has a number of performance enhancements that ultimately allow
the stream to be watched in real-time.  These changes capitalize
on new PRs for GR master branch.  The ATSC RX filter was broken
into its 2 respective parts (an RRC block and a resampler).  The
RRC block now uses the faster FFT RRC convenience wrapper, and the
PFB arb resampler was crushing performance.  So the sampling rate
was adjusted to match the ATSC symbol rate.  This removed the need
for the arb resampler in favor of a simpler rational resampler.
Processor core affinity based on a GRCon17 presentation was also
applied to …
=> Fix ATSC Flowgraphs and Allow Realtime Viewing

gr-utils/python/modtool/cli/base.py
gr_modtool catches and discards import errors. This change displays import errors to the user.
fixes #2801
=> Display import errors in gr_modtool

gr-digital/include/gnuradio/digital/glfsr.h
gr-digital glfsr.h include boost/cstdint.hpp to have uintxx_t.
These types are in boost namespace but nor using namespace xxx, nor boost:: are used.
The result is : 
In file included from /home/buildroot/autobuild/instance-0/output-1/build/gnuradio-3.8.0.0/gr-digital/lib/glfsr.cc:23:
/home/buildroot/autobuild/instance-0/output-1/build/gnuradio-3.8.0.0/gr-digital/lib/../include/gnuradio/digital/glfsr.h:42:5: error: 'uint32_t' does not name a type; did you mean 'u_int32_t'?
uint32_t d_shift_register;
^~~~~~~~
u_int32_t
see:
- http://autobuild.buildroot.net/results/14015f499e58fee530877ac052878bbe2f799942/
- http://autobuild.buildroot.net/results/53239f98dd5e03d4dc1bb4eb91ed765f77dbf0ec/
This patch append all uintxx_t by boost::  to fix this issue
=> gr-digital:glfsr.h: fix missing boost namespace

gnuradio-runtime/lib/top_block_impl.cc, gr-blocks/lib/qa_gr_top_block.cc
GNU Radio uses shared pointers to keep track of blocks, so that they are automatically destroyed when they are no longer referenced. While investigating an issue in Gqrx, I noticed a bug in this system: in certain circumstances, a block that is added to a flowgraph continues to be referenced even after it is removed from the flowgraph.
This happens because `top_block_impl` keeps a flattened copy of the flowgraph:
https://github.com/gnuradio/gnuradio/blob/c3333eb0d7238c82442d1d901df03d5199557213/gnuradio-runtime/lib/top_block_impl.h#L67
The flattened copy is calculated in `top_block_impl::start` (and updated in `top_block_impl::restart` if the flowgraph is updated while it is running), but it is not discarded in `top_block_impl::stop`. As a result, `top_block_impl` keeps blocks alive even …
=> runtime: release the flattened flowgraph after stopping

gr-utils/python/modtool/templates/gr-newmod/MANIFEST.md
Cgran was extended to display supported GNU Radio versions of OOTs. To
leverage this feature, a `gr_supported_version` key needs to be provided
by the OOT's MANIFEST. This commit extends gr-newmod's MAIFEST by this
key. This solves #3177 .
=> gr-newmod: Update MANIFEST with `gr_supported_version`

gr-blocks/lib/rotator_cc_impl.cc, gr-fec/include/gnuradio/fec/cc_encoder.h, gr-fec/lib/cc_encoder_impl.cc
Backport of #3103 to maint-3.8. Fix-up for formating is included.
=> Cc enc fixes 3.8

CMakeLists.txt
The previous CMake would only set the C/C++ standard to 11 for gcc,
clang, and MSVC. This has two issues:
1) It prevents non-common compilers to properly function. We might hit
the else() clause for a compiler, which then goes to C++98, which
then doesn't work.
2) The compiler check is not necessary for setting the C/C++ standard
and originates from an era where we had to set different compiler
flags per compiler. Now, we're trying to beat CMake at its own game
by assuming that it can't handle CMAKE_CXX_STANDARD properly.
This removes the compiler type check, and fully gives control to CMake
to set the C/C++ standard.
=> cmake: Make cmake_c*_standard unconditionally set to 11

grc/gui/Application.py
ctrl+a now selects all search text if search box in focus
fixes #2552 
Previously if you have the search box in focus, ctrl+a would select everything in the flow graph. Now if you have the search box in focus, ctrl+a will select all the search text to allow for easy clearing of the text (ctrl+a,backspace) that is consistent with other applications.
=> grc: ctrl+a now selects all text if search box in focus

gnuradio-runtime/include/pmt/pmt.h, gnuradio-runtime/lib/pmt/pmt.cc, gnuradio-runtime/swig/gr_extras.i, gr-blocks/python/blocks/qa_hier_block2.py, gr-blocks/python/blocks/qa_vector_sink_source.py, gr-digital/python/digital/qa_ofdm_carrier_allocator_cvc.py, gr-digital/python/digital/qa_ofdm_serializer_vcc.py, gr-filter/python/filter/qa_pfb_channelizer.py
Python3 now has a RuntimeError that's thrown during the pmt to_python function.
Instead of throwing this error, SWIG has been updated to throw a TypeError.
This allows us to keep the same behavior whereby we iterate over PMT types until the proper conversion is found
Resolves #2961
=> pmt: Fix RuntimeError in pmt_to_python

gr-uhd/examples/grc/uhd_wbfm_receive.grc
Fixes: https://github.com/gnuradio/gnuradio/issues/3106
Includes a bunch of misc changes to this flow graph.
- Removes most param blocks to variable blocks to avoid https://github.com/gnuradio/gnuradio/issues/3107
- Changes the structure of how `tun_freq` is handled. Instead of `freq/1e6` and adding an offset from another slider (`tun_fine`), the specific freq is provided. 
- Sets the `tun_freq` value to step in `100e3` steps (so the `tun_fine` is not needed)
- Sets `tun_gain` to use a `Normalized` gain value
- Changes audio multiplier (volume) to range from `0.0` to `1.0` in `0.1` steps instead of `0.0` to `10.0`
- Adds QT Chooser for Antenna selector
=> examples: fixup UHD WBFM example

gr-fec/lib/cc_encoder_impl.cc, gr-fec/lib/cc_encoder_impl.h
The change to cc_encoder_impl.h fixes the following warning:
```
/home/argilo/prefix_39/src/gnuradio/gr-fec/lib/cc_encoder_impl.cc: In constructor ‘gr::fec::code::cc_encoder_impl::cc_encoder_impl(int, int, int, std::vector<int>, int, cc_mode_t, bool)’:
/home/argilo/prefix_39/src/gnuradio/gr-fec/lib/cc_encoder_impl.cc:71:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
if (d_start_state >= (1u << (d_k - 1))) {
~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
```
I also explicitly wrote out `unsigned int` in cc_encoder_impl.cc for clarity.
=> gr-fec: fix compiler warning

gr-blocks/examples/CMakeLists.txt, gr-blocks/examples/py_snippets_demo.grc, grc/blocks/grc.tree.yml, grc/blocks/snippet.block.yml, grc/core/FlowGraph.py, grc/core/base.py, grc/core/blocks/block.py, grc/core/generator/flow_graph.py.mako, grc/core/generator/top_block.py, grc/core/params/param.py
This feature adds the ability to insert arbitrary code into the python
flowgraph.  It gives a little more low-level flexibility for quickly
modifying flowgraphs and adding custom bits of code rather than having
to go and edit the generated py file
One example is synchronizing multiple USRP objects - sometimes you want
different sync than what is offered in the multi-usrp object, so you can
put a bit of code in the snippet block to do the custom synchronization
-----------------------------------
This supercedes #2779 and #2814 - hopefully the issues identified on those PRs have been sufficiently resolved, as the details of last iteration were worked out with @dkozel and @marcusmueller at the ESA hackfest.
- Went back to a single snippet block.  This way they can be easily arranged and …
=> grc: add python snippets to GRC

gr-dtv/examples/CMakeLists.txt, gr-dtv/examples/uhd_atsc_rx.grc
- Renamed `uhd_rx_atsc.grc` to `uhd_atsc_rx.grc`
- Add QT GUI Chooser populated with NA ATSC channels 2-36, plus CATV 58 (429 MHz)
- The Frequency values are the lower edge (center_freq-3e6)
- 3e6 is added to the `channel` value within `center_freq`
- Leaves `center_freq` as a Entry widget in case someone wants to hard set a freq
- Switch `gain` to use Normalized values in UHD Source
- Switch QT GUI Frequency sink to have 2 inputs => RX Spectrum and post RRC Filter
- Update FFT RRC Filter to use 50 taps instead of 18
- See @drmpeg's post here: https://github.com/gnuradio/gnuradio/pull/3154#issuecomment-582143764
- I've observed improved performance with 50 taps too
- Updated the QT grid layout for the widgets
=> dtv: enhance ATSC RX example

gr-analog/lib/pll_carriertracking_cc_impl.cc, gr-analog/lib/pll_carriertracking_cc_impl.h, gr-analog/lib/pll_freqdet_cf_impl.cc, gr-analog/lib/pll_freqdet_cf_impl.h, gr-analog/lib/pll_refout_cc_impl.cc, gr-analog/lib/pll_refout_cc_impl.h, gr-digital/lib/clock_recovery_mm_cc_impl.cc, gr-digital/lib/clock_recovery_mm_cc_impl.h, gr-digital/lib/clock_recovery_mm_ff_impl.cc, gr-digital/lib/clock_recovery_mm_ff_impl.h, gr-digital/lib/clock_tracking_loop.cc, gr-digital/lib/clock_tracking_loop.h, gr-dtv/lib/atsc/atsc_fpll_impl.cc
These updates incorporate the same inlining of loop functions and
the newly pushed fast_cc_multiply function to ensure
consistent performance improvements across systems that do not
support the cx-limited-range compiler parameter (Macs and Windows).
=> gr-digital: Improve PLL Loops and Clock Recovery

CMakeLists.txt, gr-blocks/lib/rotator_cc_impl.cc
In https://github.com/gnuradio/gnuradio/pull/3062, VOLK was disabled in the rotator block to work around a bug in VOLK 2.0.0. The workaround is unconditionally applied, so the block's performance suffers even when VOLK 2.1.0 or later is used. (Debian, for one, has already moved to 2.1.0.) To solve this, I've implemented @michaelld's [suggestion](https://github.com/gnuradio/gnuradio/pull/3062#pullrequestreview-341541758) to detect the VOLK version and only apply the workaround for VOLK 2.0.0.
If an external VOLK is used, then `find_package(Volk)` will set `Volk_VERSION`. If an internal VOLK is used, then the version number is extracted from `.lastrelease`, if present. This file was added in VOLK 2.1.0. If `.lastrelease` is missing, then the VOLK version is assumed to be 2.0.0. If the …
=> gr-blocks: only apply rotator workaround to VOLK 2.0.0

grc/core/generator/flow_graph.py.mako
The `import` of `eng_notation` was removed from `flow_graph.py.mako` in 678a7c2ad, and so float parameter blocks were leading to flowgraph compilation error.
Since `eng_notation` is still ultimately imported in the generated python script, we can put the call to `num_to_str` in the generated script, instead of calling it during script generation.
The second commit of this PR simply removes a definition that seems to be unused and which also contains a call to `eng_notation.num_to_str`.
=> grc: Fix eng_float default on argparse template

gr-blocks/examples/CMakeLists.txt, gr-blocks/examples/msg_to_var.grc, gr-blocks/examples/var_to_msg.grc, gr-blocks/grc/blocks.tree.yml, gr-blocks/grc/blocks_meta_to_pair.block.yml, gr-blocks/grc/blocks_msg_pair_to_var.block.yml, gr-blocks/grc/blocks_var_to_msg.block.yml, gr-blocks/python/blocks/CMakeLists.txt, gr-blocks/python/blocks/__init__.py, gr-blocks/python/blocks/msg_meta_to_pair.py, gr-blocks/python/blocks/msg_pair_to_var.py, gr-blocks/python/blocks/var_to_msg.py
These 3 new blocks provide the missing glue to move between messages
and variables in the same flowgraph.  There are 3 variants here:
1. Monitor a variable and produce a user-specified message (pair)
when the variable changes.  Useful bridging standard GUI controls
to message-based blocks.
2. When an inbound message (pair) is received, update a specified
variable.
3. When an inbound message (dict) is received, extract a single
dictionary entry and produce a message pair (useful if you have a
multi-value dictionary but you just want to pull off a single
attribute such as frequency or gain without modifying the upstream
block. This can be paired with (2) if necessary to move from a
dictionary item to a variable.
=> gr-blocks: Add Msg to Var and Var to Msg Conversion Blocks

gr-blocks/grc/blocks.tree.yml, gr-blocks/grc/blocks_correctiq.block.yml, gr-blocks/grc/blocks_correctiq_auto.block.yml, gr-blocks/grc/blocks_correctiq_man.block.yml, gr-blocks/grc/blocks_correctiq_swapiq.block.yml, gr-blocks/include/gnuradio/blocks/CMakeLists.txt, gr-blocks/include/gnuradio/blocks/correctiq.h, gr-blocks/include/gnuradio/blocks/correctiq_auto.h, gr-blocks/include/gnuradio/blocks/correctiq_man.h, gr-blocks/include/gnuradio/blocks/correctiq_swapiq.h, gr-blocks/lib/CMakeLists.txt, gr-blocks/lib/correctiq_auto_impl.cc, gr-blocks/lib/correctiq_auto_impl.h, gr-blocks/lib/correctiq_impl.cc, gr-blocks/lib/correctiq_impl.h, gr-blocks/lib/correctiq_man_impl.cc, gr-blocks/lib/correctiq_man_impl.h, gr-blocks/lib/correctiq_swapiq_impl.cc, gr-blocks/lib/correctiq_swapiq_impl.h, gr-blocks/swig/blocks_swig0.i
This block incorporates the OOT modules in correctiq that provide
3 different techniques to remove the DC spike inherent in IQ sampling.
The first technique mirrors SDR GUI receivers with an IIR filter
approach, the second provides a time-limited IIR approach where after
a user-configurable number of seconds locks into a basic offset
correction to eliminate the effect of the filter on the signal while
maintaining the correction, and the last is manual I and Q
configurable offsets.  The Swap IQ block is a drop-in block to help
correct for inverted spectrums and just swaps I<->Q.
=> Blocks: Add DC Spike Removal and IQ Swap Native Blocks

gr-blocks/include/gnuradio/blocks/tag_debug.h, gr-blocks/lib/tag_debug_impl.cc, gr-blocks/lib/tag_debug_impl.h
For testing, it is often useful to check all tags ever received, rather than
solely the tags from the last call to the Tag Debug's work function. This patch
adds this option and a public method for activating it.
This is more appropriate for controlled test environments, where the vector of
tags is known not to grown indefinitely. Hence, the option is not exposed as a
block parameter.
=> blocks: support saving of all tags on tag debug

gr-filter/examples/test_ichar_decim.grc, gr-filter/grc/CMakeLists.txt, gr-filter/grc/filter.tree.yml, gr-filter/grc/filter_ival_decimator.block.yml, gr-filter/include/gnuradio/filter/CMakeLists.txt, gr-filter/include/gnuradio/filter/ival_decimator.h, gr-filter/lib/CMakeLists.txt, gr-filter/lib/ival_decimator_impl.cc, gr-filter/lib/ival_decimator_impl.h, gr-filter/swig/CMakeLists.txt, gr-filter/swig/filter_swig.i
Current resamplers do not support ichar as an input type.  However,
when processing high-speed wide bandwidth streaming ichar 
data from external sources (such as the ATA), decimation in 
native ichar would be faster than converting
to another data type then decimating.  This block provides the ability
to decimate the ichar stream directly.
=> gr-filter: Add ichar and ishort decimator

gr-blocks/examples/ctrlport/simple_copy_controller.py, gr-blocks/examples/ctrlport/usrp_sink_controller.py, gr-blocks/examples/ctrlport/usrp_source_controller.py
`GNURadioControlPortClient` changed its constructor interface in cb044a4c4b2c6657876f996617a24a44d1ac3b5d.
This updates the examples accordingly. I could not test the USRP examples as I don't have the hardware.
=> ctrlport: fix examples

gr-zeromq/lib/pull_msg_source_impl.cc, gr-zeromq/lib/req_msg_source_impl.cc, gr-zeromq/lib/sub_msg_source_impl.cc, gr-zeromq/python/zeromq/qa_zeromq_pull_msg_source.py, gr-zeromq/python/zeromq/qa_zeromq_req_msg_source.py, gr-zeromq/python/zeromq/qa_zeromq_sub_msg_source.py
Handle the PMT exceptions when deserializing the received ZMQ messages,
log an error message and continue the execution.
Previously the unhandled exceptions were aborting the process: #3217
terminate called after throwing an instance of 'pmt::exception'
what():  pmt::deserialize: malformed input stream, tag value = : 50
Aborted (core dumped)
=> zmq: Handle the PMT exceptions

grc/core/blocks/block.py
Re-created previously-closed pull request after making requested edits
After a recent merge fixing some C++ code generation issues (merge request #2797), GRC now fails to load a flowgraph if it has any missing blocks.
=> Allow grc to load flowgraphs with missing blocks

gr-utils/octave/cic_comp_taps.m, gr-utils/octave/plot_cic_decimator_response.m, gr-utils/octave/plot_freq_response.m, gr-utils/octave/plot_freq_response_db.m, gr-utils/octave/plot_freq_response_phase.m, gr-utils/octave/single_pole_iir.m, gr-utils/octave/write_float_binary.m, gr-utils/octave/write_short_binary.m
Fixes #3195 
In gr-utils/octave, replaced every '#' by '%' in matlab as Octave supports either of them for commenting while Matlab supports only '%'.This expands usability of code.
=> gr-utils: '#'replaced by '%' for commenting in codes.

gr-utils/python/modtool/core/add.py, gr-utils/python/modtool/core/disable.py, gr-utils/python/modtool/core/rm.py
Backport merge request #2723
Fixes issue mentioned on mailing list as well 
https://www.mail-archive.com/discuss-gnuradio@gnu.org/msg70053.html
where we see:
```
Can't add C++ QA files.
```
when adding a new block with cpp unit test.
The third commit in the original pull request for master was already on maint-3.8.
=> modtool: Backport PR #2723 to maint-3.8

grc/core/blocks/block.py
The underlying issue is that the built in blocks all end up getting the
'cpp' flag, which is not valid for the embedded python blocks
To fix this some work needs to be done in the "Flags" class, as all the
flags added to classes that get accumulated in the build_ins list get
added to all the classes
See register_build_in decorator
Fixes #3260 for now, though a more thorough solution is needed going forward
=> grc: workaround to allow epy blocks/modules to load

gr-blocks/lib/qa_rotator.cc, gr-blocks/lib/udp_sink_impl.cc, gr-blocks/lib/udp_sink_impl.h, gr-blocks/lib/udp_source_impl.cc, gr-blocks/lib/udp_source_impl.h
The remaining one is `tcp_server_sink`, which is a bit trickier, so leaving it for a future PR.
=> Remove almost all manual memory management from gr-blocks

gr-qtgui/python/qtgui/range.py.cmakein
Small fix to the CounterSlider widget to avoid double change notifications.
=> RangeWidget: avoid double-changes

gr-blocks/grc/blocks_delay.block.yml, gr-blocks/lib/delay_impl.cc, gr-blocks/lib/delay_impl.h
These updates add the ability to set the block delay value with
an asynchronous message.  In this manner, blocks doing calculations
such as those for DoA or antenna arrays can provide delay updates
only when needed.
=> gr-blocks: Add Msg Port to Delay Block

gr-blocks/examples/msg_passing/hier/test_msg_hier.grc, gr-digital/examples/packet/packet_tx.grc
Fixes #3282 and partly fixes unresolved notes in #2285
Backport of https://github.com/gnuradio/gnuradio/pull/3286 maint-3.8 fix onto master.
The docs change is not needed on master as it seems that has been fixed and moved to gr-analog.
=> Fixup some grc example files in; blocks and digital

docs/exploring-gnuradio/fm_rx.grc, docs/exploring-gnuradio/fm_tx.grc, gr-blocks/examples/msg_passing/hier/test_msg_hier.grc, gr-digital/examples/packet/packet_tx.grc
Fixes https://github.com/gnuradio/gnuradio/issues/3282 and partly fixes unresolved notes in https://github.com/gnuradio/gnuradio/issues/2285
There are some grc blocks that can not open correctly because of the connections between the blocks does not seem to have an number suffix if there is only one port.
See for example `test_msg_hier.grc`.
If the "Num Streams" are set to 1 the single input port is called "in", if there are multiple they are suffixed with a number, as in "in0", "in1"...
=> Fixup some grc example files in; blocks, docs and digital

gr-filter/python/filter/design/filter_design.py, gr-filter/python/filter/gui/pyqt_filter_stacked.py
Sorry for making a mess with my previous pull requests. Hopefully you will find this to be much more organized. For convenience, here are my previous notes:
Referring back to #3100, it seems that the only way for the Filter Design Tool to run correctly run is to update `numpy.fft.fftpack` to `numpy.fft` and run `pip3 install git+https://github.com/pyqtgraph/pyqtgraph@develop`. It seems that only the development build of `pyqtgraph` works with the filter tool. Should the development version be added as a dependency?
I changed the label from `IIR(scipy)` to `IIR` in `pyqt_filter_stacked.py`, since scipy is being abandoned in the future. I also set up `filter_design.py` to call `poly1d` from `numpy` rather than `scipy`, since there's a consensus that GNU Radio needs to abandon its dependency …
=> fix(filter_design): Change numpy.fft.fftpack to numpy.fft and increase dependency on Numpy instead of Scipy

grc/gui/Application.py, grc/gui/MainWindow.py
This is just a simple UX papercut fix: avoid showing the "unsaved changes" dialog when a new flowgraph is created and then closed without changes; in particular, I find it a bit irritating that it appears when I open and close grc without doing anything at all.
Hopefully, this change doesn't break any other behaviour.
=> grc: disable save prompt on new blank pages

CMakeLists.txt, cmake/Modules/GrPython.cmake
Yeah, I hate dependencies. But let's not kid ourselves, numpy was always a dependency of GNU Radio. Might as well treat it as such. Should then obviate #3280.
=> cmake: Make numpy a first-class dependency for Python

gr-blocks/grc/blocks.tree.yml, gr-blocks/grc/blocks_phase_shift.block.yml, gr-blocks/include/gnuradio/blocks/CMakeLists.txt, gr-blocks/include/gnuradio/blocks/phase_shift.h, gr-blocks/lib/CMakeLists.txt, gr-blocks/lib/phase_shift_impl.cc, gr-blocks/lib/phase_shift_impl.h, gr-blocks/swig/blocks_swig10.i
This new block provides a native ability to phase shift signals
based on radians for solutions such as DoA and array-based projects.
The block supports both variable and message based updates such that
other blocks can provide the appropriate calculations for shifting
and only send message-based updates when necessary.
=> gr-blocks: Add Phase Shift Block with Msg Capabilities

gr-utils/python/modtool/cli/newmod.py, gr-utils/python/modtool/core/newmod.py
Putting this up here for discussion - though I don't see the downsides to this change just yet.
When a prefix gets installed, the [modtool] section in prefs hardcodes
the path to the templates in the newly installed prefix as a global path
for all modtools.  This creates major problems when bouncing between
prefixes, especially when newmod changes between releases
Why not just use the prefix as the root of where to look for the
templates
This potentially contributed to issues such as #2812 and #2873
=> modtool: use prefix path for modtool instead of prefs

gr-digital/examples/demod/test_corr_est.grc
Previous version missed something in the transition to yaml, namely
parenthesis around the lengths list in the stream mux.
Now the example runs out of the box
=> digital: test_corr_est example - missing parenthesis

gr-digital/examples/demod/test_corr_est.grc
Previous version missed something in the transition to yaml, namely
parenthesis around the lengths list in the stream mux.
Now the example runs out of the box
=> digital: test_corr_est example 3.8 - missing parenthesis

grc/gui/MainWindow.py, grc/gui/Notebook.py
This is a backport of #3303. Fixes #3294.
I have tested thus with a python2 build as well.
=> grc: show file path as tooltip in tab label

CMakeLists.txt, gr-audio/lib/osx/osx_common.h, gr-blocks/lib/wavfile.cc
This uses cmake's TEST_BIG_ENDIAN instead of Boost.
Note that current use of `boost/detail/endian.hpp` is deprecated:
```The use of BOOST_*_ENDIAN and BOOST_BYTE_ORDER is deprecated. Please include <boost/predef/other/endian.h> and use BOOST_ENDIAN_*_BYTE instead```
Also, I am not sure if GNU Radio works on any of the remaining big-endian platforms.
=> replace boost endian check with cmake

gr-blocks/include/gnuradio/blocks/rotator.h, gr-blocks/lib/rotator_cc_impl.cc
Fixes https://github.com/gnuradio/gnuradio/issues/3308.
Related pull requests: https://github.com/gnuradio/gnuradio/pull/3062 https://github.com/gnuradio/gnuradio/pull/3205
Since `rotateN` is part of the GNU Radio API, it should get the workaround for VOLK 2.0.0's rotator bug.
=> blocks: move rotator workaround up into rotateN

gnuradio-runtime/include/gnuradio/block_gateway.h
Both `set_block_alias()` and `set_processor_affinity()` exist as GUI settable fields for all blocks, but for python blocks these are not exposed causing runtime exceptions if used the way GRC does (can only be used via `blockname.to_basic_block().set_block_alias()`). This PR adds both to block_gateway objects, and allows python blocks to use `self.alias()` to return their alias.
=> Block gateway add alias affinity

CMakeLists.txt, gr-audio/lib/osx/osx_common.h, gr-blocks/lib/wavfile.cc
This is a backport of PR #3299.
=> [backport-3.8] replace boost endian check with cmake

grc/core/generator/flow_graph.py.mako
This is the backport for https://github.com/gnuradio/gnuradio/pull/2728 in maint-3.8.
=> Module name correction for bokehgui, backport

grc/gui/ParamWidgets.py, grc/gui/canvas/param.py
Cherry pick of 3411bf5 onto maint-3.8 as this causes problems on that branch also, see https://github.com/gnuradio/gnuradio/pull/2816
Related to https://github.com/gnuradio/gnuradio/issues/2683 and https://github.com/gnuradio/gnuradio/issues/3167
=> GRC: Revert "Added switch button for bool types" on maint-3.8

CHANGELOG.md
Contributors
------------
-  Alba Mendez me@alba.sh
-  alekhgupta1441 alekhgupta1441@gmail.com
-  Anders Kalør anders@kaloer.com
-  Artem Pisarenko artem.k.pisarenko@gmail.com
-  Bastian Bloessl mail@bastibl.net
-  Brennan Ashton bashton@brennanashton.com
-  Chris christopher.donohue@gmail.com
-  Clayton Smith argilo@gmail.com
-  CMorin barthy42@laposte.net
-  Daniel Estévez daniel@destevez.net
-  Davide Gerhard rainbow@irh.it
-  Derek Kozel derek.kozel@gmail.com
-  duggabe
-  Glenn Richardson glenn.richardson@live.com
-  Grant Cox grant.cox@deepspaceamps.com
-  Gwenhael Goavec-Merou gwenhael.goavec-merou@trabucayre.com
-  Håkon Vågsether haakonsv@gmail.com
-  Igor Freire igor.auad@gmail.com
-  Jacob Gilbert mrjacobagilbert@gmail.com
-  Jan Kraemer kraemer.jn@gmail.com
-  japm48
- …
=> Release 3.8.1.0

gr-qtgui/python/qtgui/range.py.cmakein
This is a small addition to the RangeWidget. An input field `Eng` that accepts numbers in Engineering notation (as used by `gnuradio.eng_notation`) and a combo `EngSlider` that is similar to `CounterSlider` but constructed out of `Eng` and `Slider` instead of `Counter` and `Slider`,
=> RangeWidget: implement Eng & EngSlider

grc/gui/Actions.py, grc/gui/Dialogs.py
Adds the following GRC hotkeys:
<ctrl><shift>C = clear console
<ctrl><shift>P = save the console to file
<ctrl><shift>L = toggle console scroll lock
Debatable if these are the best bindings, but specifically clearing the console is very helpful to have a hotkey for. Copying console to clipboard would be awesome too but that was not immediately apparent and I do not know much about how to implement that....
=> grc: add hotkeys to clear/save console, and to toggle autoscroll

gnuradio-runtime/include/gnuradio/random.h, gnuradio-runtime/lib/math/random.cc, gr-analog/lib/fastnoise_source_impl.cc
This is what gnuradio currently documents seeding will do, but it's
not what C++ defaults to.
See C++11 26.5.3.2, paragraph 3. Default for mersenne twister is
constexpr 5489.
Or easier, the bottom of
https://en.cppreference.com/w/cpp/numeric/random/mersenne_twister_engine
=> runtime: Make random seed default to current time, as documented

gr-zeromq/grc/zeromq_pub_msg_sink.block.yml, gr-zeromq/grc/zeromq_pull_msg_source.block.yml, gr-zeromq/grc/zeromq_push_msg_sink.block.yml, gr-zeromq/grc/zeromq_rep_msg_sink.block.yml, gr-zeromq/grc/zeromq_req_msg_source.block.yml, gr-zeromq/grc/zeromq_sub_msg_source.block.yml, gr-zeromq/include/gnuradio/zeromq/pub_msg_sink.h, gr-zeromq/include/gnuradio/zeromq/pull_msg_source.h, gr-zeromq/include/gnuradio/zeromq/push_msg_sink.h, gr-zeromq/include/gnuradio/zeromq/rep_msg_sink.h, gr-zeromq/include/gnuradio/zeromq/req_msg_source.h, gr-zeromq/include/gnuradio/zeromq/sub_msg_source.h, gr-zeromq/lib/pub_msg_sink_impl.cc, gr-zeromq/lib/pub_msg_sink_impl.h, gr-zeromq/lib/pull_msg_source_impl.cc, gr-zeromq/lib/pull_msg_source_impl.h, gr-zeromq/lib/push_msg_sink_impl.cc, gr-zeromq/lib/push_msg_sink_impl.h, gr-zeromq/lib/rep_msg_sink_impl.cc, gr-zeromq/lib/rep_msg_sink_impl.h, gr-zeromq/lib/req_msg_source_impl.cc, gr-zeromq/lib/req_msg_source_impl.h, gr-zeromq/lib/sub_msg_source_impl.cc, gr-zeromq/lib/sub_msg_source_impl.h
Current ZMQ blocks only support 1:N, which makes sense for streaming blocks but message blocks should support N:1 also to completely implement ZMQ patterns.
=> zeromq: add bind argument for message based zeromq blocks

gnuradio-runtime/include/gnuradio/buffer.h, gnuradio-runtime/include/gnuradio/hier_block2.h, gnuradio-runtime/include/gnuradio/logger.h, gnuradio-runtime/include/gnuradio/message.h, gnuradio-runtime/include/gnuradio/thread/thread_group.h, gnuradio-runtime/include/gnuradio/top_block.h, gnuradio-runtime/lib/block_executor.cc, gnuradio-runtime/lib/block_executor.h, gnuradio-runtime/lib/buffer.cc, gnuradio-runtime/lib/hier_block2.cc, gnuradio-runtime/lib/logger.cc, gnuradio-runtime/lib/math/qa_fxpt_nco.cc, gnuradio-runtime/lib/math/qa_fxpt_vco.cc, gnuradio-runtime/lib/message.cc, gnuradio-runtime/lib/thread/thread_group.cc, gnuradio-runtime/lib/top_block.cc, gnuradio-runtime/lib/vmcircbuf.cc
The remaining ones:
* `pmt_pool.cc`, which is a memory allocator so that makes sense
* the tricky and aptly named `sptr_magic.cc`.
=> runtime: Remove most manual memory management

gnuradio-runtime/lib/pmt/pmt_serialize.cc
This PR substantially improves serialization speed for PMTs, which was done primarily to facilitate movement of large PDUs over ZMQ.
U8 PDU speedup: ~1.8x
F32 PDU speedup: ~2.1x
C32 PDU Speedup: ~2.2x
Needs review, especially for non-x86-linux platforms as this has not been extensively tested on anything but...
=> pmt: speed up serialization

gr-utils/modtool/cli/add.py
Fixes: #3270 
It raises ModTool Exception if same name block exists in module.
Screenshot
=> modtool: Added feature to prevent creation of multiple blocks with same name.

gnuradio-runtime/include/gnuradio/CMakeLists.txt, gnuradio-runtime/include/gnuradio/integer_math.h, gnuradio-runtime/lib/buffer.cc, gr-digital/lib/symbol_sync_cc_impl.cc, gr-digital/lib/symbol_sync_ff_impl.cc
Another little spring clean patch.
Remove deprecation warning and prefer using `std::{lcm,gcd}` to Boost.
Fixes #2712.
I'm not sure if `gnuradio-runtime` is the best place to put the new header.
=> boost: fix deprecated use of math/common_factor.hpp

cmake/Modules/GrSwig.cmake
SWIG complains about "Deprecated command line option: -modern. This
option is now always on.".
As traditional with SWIG, policy changes don't appear in any
documentation; with a bit of git blaming, I found the change to have
been introduced after SWIG 3.0.12.
=> CMake/SWIG: Remove SWIG flag superfluous since 3.0.12, suppress warning

gnuradio-runtime/lib/realtime_impl.cc
This came up while working through logging stuff.
I didn't want it to go to waste.
=> realtime_impl: rint/rintf: use appropriate math function for float

gr-filter/grc/filter_low_pass_filter.block.yml, gr-filter/grc/filter_pfb_arb_resampler.block.yml, gr-filter/grc/filter_pfb_synthesizer.block.yml, gr-filter/grc/filter_rational_resampler_xxx.block.yml, gr-filter/python/filter/pfb.py, gr-filter/python/filter/rational_resampler.py
- This enables C++ support for some filter blocks.
- Re-factored taps generation in pfb.py to allow c++ code to leverage
default taps values.
This is https://github.com/gnuradio/gnuradio/pull/2898 by @seeAppRun, rebased onto master, re-PR'd for updated CI results. 
It has been reviewed by @haakov and @michaelld already. I am OK merging this if CI passes.
=> filter: Fix YAML files for C++ generation [PR for CI]

gr-digital/python/digital/soft_dec_lut_gen.py
Fixes: #3268 
In soft_dec_lut_gen.py, npts is a float and is used as third parameter of numpy.linspace which should be int according to [numpy's documentation](https://numpy.org/devdocs/reference/generated/numpy.linspace.html). This PR removes the warnings.
=> gr-digital/python : Updated soft_dec_lut_gen.py to avoid depreciation warnings.

CMakeLists.txt
This attempts to fix the CI build issue.
Getting the latest and greatest VOLK in CI is a problem separate from managing
minimum versions, I'd say, for now. However, it's of course desirable that the
BB-included versions of VOLK do reflect the latest VOLK release.
=> VOLK: notch down the minimum required version to 2.1.0

CMakeLists.txt
I'm not proud of this workaround, but this should keep the GNU Radio
builds afloat, until we can fix the [issue](https://github.com/gnuradio/volk/issues/377) upstream.
=> CMake: warn about VOLK versions not setting version, but try with them

gr-trellis/lib/fsm.cc
This arose during reworking the logging conversion
=> trellis/fsm: error handling and logging replaces printf debugging

gnuradio-runtime/python/pmt/qa_pmt.py
fixes #3326
After reports of @drmpeg that qa_pmt assumes sizeof(long)>4, I circumvented the test that do.
However, this is a fundamental architectural flaw: On @drmpegs 32-bit ARM, a long is 4 Bytes.
On my machine, it's 8.
This yields different deserializability of serialized PMTs.
PMT is supposed to be a portable serialization format.
It's not.
I'd try to change PMT, but it's too busy eating crayons.
=> pmt: conditionalize testing of long > 2³² on sizeof(long)

gr-blocks/lib/file_sink_impl.cc, gr-blocks/lib/file_sink_impl.h
Make sure that data passed to the file sink is written to the disk when
the flowgraph is stopped. Before this change this only happened
implicitly due to a fclose() in the base class destructor. This in turn
means that data was written delayed after stopping the flowgraph [1].
This fixes #2590.
[1] https://github.com/gnuradio/gnuradio/issues/2590
=> file_sink: Flush file on stop()

gnuradio-runtime/include/gnuradio/basic_block.h, gnuradio-runtime/include/gnuradio/block.h, gnuradio-runtime/lib/basic_block.cc, gnuradio-runtime/lib/block.cc
No reason to assume only `general_work`-containing blocks would want to
log.
This enables us especially to log in `basic_block` itself.
This will lead to a lot more restructuring – there's a lot block-owned loggers that shouldn't exist. Partly my fault.
=> runtime: move loggers from gr::block to gr::basic_block

grc/gui/Actions.py, grc/gui/Dialogs.py, grc/gui/Utils.py
implements support for the Meta key on macOS.
Others platforms continue to use Ctrl.
if you like, I also have the patch for maint-3.8
=> gnuradio-companion: add Meta modifier key for macOS

gr-utils/modtool/cli/add.py, gr-utils/modtool/cli/base.py, gr-utils/modtool/cli/newmod.py, gr-utils/modtool/core/add.py, gr-utils/modtool/core/base.py, gr-utils/modtool/core/disable.py, gr-utils/modtool/core/info.py, gr-utils/modtool/core/makeyaml.py, gr-utils/modtool/core/newmod.py, gr-utils/modtool/core/rename.py, gr-utils/modtool/core/rm.py, gr-utils/modtool/core/update.py, gr-utils/modtool/templates/templates.py, gr-utils/modtool/tools/cmakefile_editor.py, gr-utils/modtool/tools/grc_yaml_generator.py
Use of **Python f'strings** or "Literal String Interpolation" makes code clearer and much more readable.
They are also faster than str.format() and %-formatting due to run time evaluation.
For more details check this: https://hackernoon.com/a-closer-look-at-how-python-f-strings-work-f197736b3bdb
Replaced all **str.format()** by **Python f'strings** except a few due to formatting of variable which falls into exception category for Python f'strings as they can format only **string literal**.
Check this:https://stackoverflow.com/questions/54351740/how-can-i-use-f-string-with-a-variable-not-with-a-string-literal
Also I have tested the modtool using testsuite and it passes the tests.
Screenshot:
=> modtool: Replaced str.format() by Python f'strings in all codes

grc/gui/ParamWidgets.py
is_dark_theme() should not throw an exception gsettings is not found (can happen in Windows).
=> grc: do not assume gsettings exists

grc/core/blocks/_templates.py
When generating a flowgraph, you will get the following error if there is a typo (usually a misspelled parameter) in the block's template:
`Generate Error: (NameError('Undefined'), 'fft.ctrlport_probe_psd(${nam}, ${desc}, ${len})')`
This isn't very helpful, at least not for blocks with large multi-line templates. 
With this fix, Mako will specify the name of the undefined variable:
`Generate Error: (NameError("'nam' is not defined"), 'fft.ctrlport_probe_psd(${nam}, ${desc}, ${len})')`
https://docs.makotemplates.org/en/latest/runtime.html#context-variables
Should this be backported to maint-3.8?
=> grc: Enable strict_undefined to ease Mako template debugging

gr-filter/grc/variable_band_pass_filter_taps.block.yml
In the case of complex taps, firdes.complex_band_pass should be used instead of firdes.band_pass.
=> filter: grc: variable_band_pass_filter_taps: fix complex taps option

gr-filter/lib/firdes.cc, gr-filter/python/filter/qa_firdes.py
`firdes.root_raised_cosine()` does not normalize the coefficients correctly when `alpha == 1` due to a bug in special-case handling for that specific value of `alpha`. Fixed in this PR along with new unit test.
To reproduce (annotated):
```
In [1]: from gnuradio.filter import firdes
In [2]: h = firdes.root_raised_cosine(1, 4, 1, 0.99, 128)                                                                           
In [3]: np.sum(h)                                                                                                                   
Out[3]: 1.0000000041691237
In [4]: h = firdes.root_raised_cosine(1, 4, 1, 1.0, 128)                                                                            
In [5]: np.sum(h) …
```
=> filter: Fix firdes RRC filter gain for alpha == 1

gr-filter/lib/firdes.cc, gr-filter/python/filter/qa_firdes.py
* Fix gain of firdes.root_raised_cosine() when alpha is set to 1.0. Was
2x the expected gain for alpha==1.0 previously.
* Adds corresponding unit test.
=> filter: Fix firdes RRC filter gain for alpha == 1 (backport for maint-3.8)

gr-filter/lib/firdes.cc, gr-filter/python/filter/qa_firdes.py
* Fix gain of firdes.root_raised_cosine() when alpha is set to 1.0. Was
2x the expected gain for alpha==1.0 previously.
* Adds corresponding unit test.
=> filter: Fix firdes RRC filter gain for alpha == 1 (backport for maint-3.7)

gr-fft/include/gnuradio/fft/window.h, gr-fft/lib/window.cc
Adds Tukey window generation.
Sanity check:
```
>>> from gnuradio import fft
>>> from matplotlib import pyplot as plt
>>> plt.plot(fft.window.hann(17), '-o');
[<matplotlib.lines.Line2D object at 0x7f0a64b49748>]
>>> plt.plot(fft.window.tukey(33, .5), '-o'); plt.show()
[<matplotlib.lines.Line2D object at 0x7f0a64b49828>]
>>> plt.show()
```
=> gr-fft: added tukey and gaussian windows

grc/gui/Dialogs.py
Simple GUI fix.
Previously the context menu showed `gtk-clear` and `gtk-save`.
=> grc: use correct labels in log window context menu

grc/gui/Executor.py, grc/gui/Utils.py
Allow the use of predictable relative paths.
This also includes changes on cmake compilation.
=> grc: start process on flowgraph folder

grc/core/blocks/_templates.py
Backport of https://github.com/gnuradio/gnuradio/pull/3394
=> grc: Enable strict_undefined to ease Mako template debugging (maint-3.8)

grc/gui/Dialogs.py
Previously 'gtk-clear' and 'gtk-save' were shown.
Gtk.STOCK_* constants are deprecated in favor of translated strings.
But grc is English-only, so it makes sense to stick to the simple
hardcoded solution.
=> grc: use correct labels in log window context menu (Backport 3.8)

grc/core/Config.py
GRC reads paths from various sources, including the GRC_BLOCKS_PATH
environment variable. It can happen that paths appear twice in the list,
causing warnings about findings blocks twice.
This deduplicates the paths in the config object.
=> grc: Deduplicate block paths

gnuradio-runtime/include/gnuradio/attributes.h
gcc 4 has been a requirement for many years now, so we can remove the
check for gcc 3.
=> runtime: attributes: Remove check for gcc 3

grc/gui/Actions.py
This is a reduced backport of #3431 to 3.8.
It only touches the "show block comments" setting to default to True
=> GRC: default to showing of block comments

gnuradio-runtime/include/pmt/pmt.h, gnuradio-runtime/lib/pmt/pmt.cc, gnuradio-runtime/lib/pmt/pmt_int.h, gnuradio-runtime/lib/pmt/pmt_serialize.cc, gnuradio-runtime/lib/pmt/qa_pmt_prims.cc, gnuradio-runtime/python/pmt/qa_pmt.py, gnuradio-runtime/swig/pmt_swig.i
This modification attempts to resolve the persistent [bug identified by @mbr0wn back in 2016](https://github.com/gnuradio/gnuradio/issues/965) in which PMT objects have no built in tests between dicts and pairs which can be frustrating and causes clumbsy workarounds when working with PMT data structures such as PDUs. This fix is not necessarily ideal, but is relatively low risk and should retain all existing functionality and be API compatible.
This adds a new class `pmt_dict` that is essentially identical to `pmt_pair`, however the built in base class `is_dict()` returns true. The public `is_dict()` function has been updated to call the underlying objects `is_dict()` function instead of checking if it is a pair. Thus, dicts are still a special case of pair and tests accordingly, but all …
=> PMT: Provide inherent differentiation between PMT dictionaries and pairs

gr-uhd/grc/gen_uhd_usrp_blocks.py
Fixes https://github.com/gnuradio/gnuradio/issues/3437.
I'll make a PR for master too if this one gets approved.
=> uhd: Properly ignore len_tag_name in USRP source (3.8)

gr-uhd/apps/uhd_fft, gr-uhd/apps/uhd_siggen_gui
This moves the `import sip` statements in uhd_fft and uhd_siggen_gui
below the import for Qt, without which import errors can occur on
platforms such as Fedora 31.
=> uhd: Change import order for sip and Qt modules

gr-qtgui/grc/qtgui_chooser.block.yml
After updating to latest git version of gnuradio and  Ubuntu 20.04
trying to build a chooser block fails with Generate Error: (NameError("'i' is not defined")
This is correct
https://github.com/gnuradio/gnuradio/blob/aa8f15d6408b0a2b70b6a012c53b8cf0bd955b9c/gr-qtgui/grc/qtgui_chooser.block.yml#L132
i is not defined at this point. No idea why it worked before.
Creating the labels list the same way as the options list fixes this issue
=> qtgui_chooser.block.yml fails to build

grc/core/blocks/block.py
Currently GRC will not evaluate asserts that contain objects from imported modules, because the assert check is performed without using the parent flowgraph namespace and the objects do not exist there. This is not a significant in-tree issue, but it is an issue for several OOTs and I believe one check that was commented out [here](https://github.com/gnuradio/gnuradio/blob/master/gr-blocks/grc/blocks_multiply_matrix_xx.block.yml#L40):
This fix explicitly uses the parent flowgraph namespace and allows for checks using module objects.
Credit: Peter Knee
=> allow GRC to use module specific variables in assert statements

gr-blocks/grc/blocks_file_meta_sink.block.yml
File meta sink has invalid default value of "" when it expects an empty dict PMT
Just changed the yml to give it the same value that is in the example files for this block
backport of #3475
=> blocks: default value for file_meta_sink in yml (backport 3.8)

gr-blocks/grc/blocks_file_meta_sink.block.yml
File meta sink has invalid default value of "" when it expects an empty dict PMT
Just changed the yml to give it the same value that is in the example files for this block
=> blocks: default value for file_meta_sink in yml

grc/gui/Constants.py, grc/gui/ParamWidgets.py, grc/gui/canvas/colors.py
Cherry pick of #3017 back to maint-3.8
Authored-By: Arpit Gupta <guptarpit1997@gmail.com> Martin Braun <martin@gnuradio.org>
=> GRC: Fix color for input boxes in parameter widget for dark themes (Backport 3.8)

gr-qtgui/lib/FrequencyDisplayPlot.cc
The mouse hover feature of the frequency sink now respects the unit that
was set in the API.
Example: Here, I changed the unit to dBFS (default remains dB).
=> qtgui: Apply unit of frequency sink to mouseover

grc/core/generator/flow_graph.py.mako
Fixes #3506.
Fixes #3141.
The change in #3442 put the `from __future__ import print_function` into a Mako Python block instead of the generated flowgraph. This broke GRC, at least on Python 3.
To fix this I reverted #3442 and moved `from __future__ import print_function` to the correct place. I also put it in a Mako `% if` block so it's only generated in Python 2.
=> grc: fix broken flow_graph template

gr-qtgui/include/gnuradio/qtgui/plot_raster.h, gr-qtgui/include/gnuradio/qtgui/plot_waterfall.h, gr-qtgui/lib/DisplayPlot.cc, gr-qtgui/lib/TimeRasterDisplayPlot.cc, gr-qtgui/lib/WaterfallDisplayPlot.cc, gr-qtgui/lib/displayform.cc, gr-qtgui/lib/edit_box_msg_impl.cc, gr-qtgui/lib/numberdisplayform.cc
Related bug: #3349.
This replaces obsolete API calls (most of the newer alternatives are present on Qt 5.0).
=> qtgui: remove qt warnings

grc/core/generator/Generator.py
`Generator.py` compiles `flow_graph.py.mako` but then never uses it.
It looks like this happened in 7f7fa2f91467fdb2b11312be8562e7b51fdeb199 when some of the code from `Generator.py` was split into `top_block.py`, which now handles compilation of `flow_graph.py.mako`.
Since `flow_graph_template` is never used, it should be safe to remove this code. I didn't encounter any problems in GRC after making this change.
=> grc: remove dead code

grc/blocks/variable_function_probe.block.yml
The function probe block creates a new worker thread to do it's thing, this means that the callback to update the value of the block is executed in that separate thread.
The bokeh framework doesn't allow that, so using a probe block value in a BokehGUI block causes a crash.
This PR solves it by giving the callback function to the bokeh framework so it can execute it in its own thread.
I did not know how to check whether QT or bokeh is active from the yaml file, so I made a nested try.
This can be backported to maint-3.8.
=> grc: Fix crash when using function probe with BokehGUI

grc/gui/canvas/flowgraph.py
previously the first hit terminated further processing
backport of #3501
=> grc: iterate all selected blocks when changing port type (fixes #3500)

grc/core/generator/flow_graph.py.mako
Just moved the if for hier block down so the python_version is always populated since it is used for both hier and non-hier blocks
Fixes #3527
=> grc: always perform version check in flow_graph.py.mako

gr-blocks/grc/xmlrpc_client.block.yml
The XMLRPC Client block is currently broken because it tries to import 
the Python 2 XMLRPC module, and because the "addr" and "callback" 
parameters are inserted as quoted strings. To fix these problems, I've 
switched to the Python 3 version of the XMLRPC module, and changed the 
data types of the problematic parameters to "raw".
I tested this with the following flowgraphs:
Server:
Client:
I'll open a separate pull request to fix this in GNU Radio 3.8, which needs to support both Python 2 and Python 3.
=> blocks: Fix XMLRPC Client block templates

gr-qtgui/lib/time_sink_f_impl.cc, gr-qtgui/lib/time_sink_f_impl.h
previously this logic was only in the complex-message time sink and tags were not displayed if present
=> qtgui: enable item tags for float-message time sink

gr-blocks/lib/moving_average_impl.cc, gr-blocks/lib/moving_average_impl.h, gr-blocks/python/blocks/qa_moving_average.py
This improves performance of moving average for me by about 4-5x.
My test is [here](https://github.com/ThomasHabets/radiostuff/blob/master/amateur/listen_70cm.grc), which processes 10MHz to find the strongest signal.
Without this PR I see `moving_average` in `top` taking about 89.4-94%
CPU. With this patch it's ~20.4-23.7%. Since without this patch it's
that high, I don't know that it's not even better.
Test measured on a Libremv2 with Intel Core i7-6500U @ 2.5GHz.
The memory access pattern is probably worse with this patch, but at
least on my hardware on my workload this seems to be dwarfed by the
gain of using volk. It can be hard to reason about memory access patterns, so benchmarks overrule theory.
The test only actually uses float averaging.
More benchmarking may be required. …
=> blocks/moving_average: use vector functions

cmake/Modules/GrTest.cmake
This quotes the SHELL variable in the resulting
shell scripts for execute the tests in the correct
environment and allows paths with spaces.
Thanks to Daniel Estévez for reporting this and providing the
correct fix.
Closes #3560
=> cmake: Add quotation marks around $PATH in GrTest.cmake

gnuradio-runtime/python/gnuradio/gr/bindings/CMakeLists.txt, gnuradio-runtime/python/gnuradio/gr/bindings/python_bindings.cc
This solves the issue of gr.enable_realtime_scheduling() failing because
rt_status_t wasn't wrapped without.
=> pybind: include and enable realtime_impl wrapping

gr-uhd/lib/usrp_block_impl.cc
Previously, `pmt::is_dict` would return `true` for pairs and vice versa.
This assumption was built into gr-uhd command handling. With this
commit, a new check `if(pmt::is_pair(...))` is introduced to convert
pairs to dicts for further processing.
This behavior is [documented here](https://www.gnuradio.org/doc/doxygen/namespacepmt.html#a2b5a9b0e21ac7a90078ce5033182104e) but apparently, it does not hold anymore.
The new behavior looks like this:
```cpp
pmt::is_pair(pmt::make_dict()); //return false.
pmt::is_dict(pmt::cons(pmt::intern("key), pmt::intern("val))); //return false.
```
When did that change?
=> gr-uhd: Fix assumption that pmt pair passes is_dict

CMakeLists.txt
removed if(POLICY CMP0026), if(POLICY CMP0043), if(POLICY CMP0045),
> if(POLICY CMP0046)). Compiles cleanly using Ubuntu 18.04.4 LTS
> with both CMake version 3.8 and 3.13.4.
=> issue 1687: resolution:

gr-utils/blocktool/core/parseheader.py, gr-utils/blocktool/core/parseheader_generic.py, gr-utils/blocktool/tests/test_blocktool.py
pygccxml tries to import time.clock, which was deprecated since Py3.3,
and removed in Py3.8
Thus, for these platforms:
time.clock = time.perf_counter
=> blocktool: Monkeypatch time module for pygccxml to work under Python>=3.8

gr-blocks/grc/xmlrpc_client.block.yml, gr-blocks/grc/xmlrpc_server.block.yml
The XMLRPC Client block is currently broken because it tries to import 
the Python 2 XMLRPC module, and because the "addr" and "callback" 
parameters are inserted as quoted strings. To fix these problems, I've 
switched to the Python 3 version of the XMLRPC module with a fallback to 
the Python 2 version, and changed the data types of the problematic 
parameters to "raw".
The XMLRPC Server block is currently broken because it tries to import 
the Python 2 XMLRPC module. To fix this problem, I've switched to the 
Python 3 version of the XMLRPC module with a fallback to the Python 2 
version.
I tested this with the following flowgraphs:
Server:
Client:
=> blocks: Fix XMLRPC Client and Server block templates

gr-uhd/grc/gen_uhd_usrp_blocks.py
With pybind11 `uhd.time_spec()` doesn't work anymore because default
values are not defined.
=> uhd: Add default value to uhd.time_spec call

grc/core/generator/flow_graph.py.mako
GRC used `gr.io_signaturev` to generate hierarchical block signatures.
This was only a SWIG alias to `gr.io_signature.makev`. Now, the
generator calls `gr.io_signature.makev` directly.
=> grc: Fix hier block io_signature generation

gr-uhd/python/uhd/bindings/uhd_types_python.cc
In the python bindings add the appropriate default values
=> uhd: add default values for time_spec_t constructor

gr-uhd/python/uhd/__init__.py
There is no need to have the dependence on uhd python bindings as the
types that are used in gr-uhd are wrapped separately
This especially causes issues when using the PPA packages, since uhd doesn't by default package their python bindings, so this unnecessary line will cause an exception
=> uhd: remove import from uhd

gr-qtgui/grc/qtgui_const_sink_x.block.yml, gr-qtgui/grc/qtgui_eye_sink_x.block.yml, gr-qtgui/grc/qtgui_freq_sink_x.block.yml, gr-qtgui/grc/qtgui_histogram_sink_x.block.yml, gr-qtgui/grc/qtgui_time_raster_x.block.yml, gr-qtgui/grc/qtgui_time_sink_x.block.yml, gr-qtgui/grc/qtgui_time_sink_x.block.yml.py, gr-qtgui/grc/qtgui_waterfall_sink_x.block.yml
The qtgui blocks are all labeled as optional on their input ports, which is only appropriate for message blocks.  This PR puts a conditional flag on the optional parameter for the input ports
Fixes #3036
=> qtgui: remove optional flag on stream ports

gr-filter/python/filter/design/filter_design.py
When using certain sample rate values (e.g. 320001), the Filter Design 
Tool fails with "ValueError: operands could not be broadcast together 
with shapes (9999,) (10000,)". This occurs because the self.freq array 
in the get_fft function has one too many values. The self.freq array is 
generated using numpy.arange. Its documentation warns: "When using a 
non-integer step, such as 0.1, the results will often not be consistent. 
It is better to use numpy.linspace for these cases."
As recommended, I've switched this code to use numpy.linspace, which is 
guaranteed to produce the correct number of values.
=> filter: fix FFT frequency range calculation

CMakeLists.txt, gr-utils/modtool/core/add.py, gr-utils/modtool/core/newmod.py
Forked off of https://github.com/gnuradio/gnuradio/pull/3377 since that was left unreviewed to the point where it could not be salvaged.
=> modtool: Run all generated C++ code through clang-format
