gnuradio/gnuradio

grc/core/Constants.py, grc/core/params/param.py, grc/gui/ParamWidgets.py, grc/gui/canvas/param.py
This commit adds a new parameter type to GNURadio Companion that allows
you to select directories using a gui. This functionality is
very similar to that of the previously available "file_open" and
"file_save" parameter types, and mainly differs by calling GTKs file
chooser with FileChooserAction.SELECT_FOLDER.
Example:
=> grc: Add dir_select parameter type

gr-qtgui/lib/eye_sink_c_impl.cc, gr-qtgui/lib/eye_sink_f_impl.cc
1) convert boost::bind to lambda functions
2) ~~add missing method on python bindings~~
3) ~~make function needs extra None~~
see #3655
=> qtgui: eye_sink - add lambda functions for message handling and other pybind11 related fixes

gnuradio-runtime/lib/controlport/rpcserver_aggregator.cc
I'm building master in my Gentoo system and I need to `#include <algorithm>` whenever `std::for_each()` is used, since otherwise it won't build. I believe that this is the correct way to fix this problem, but since I'm not so savvy about C++, please correct me if I'm not right.
=> controlport: include <algorithm> when using std::for_each()

gr-uhd/grc/gen_uhd_usrp_blocks.py
A USRP block offers the option to set a `clock_rate` which in turn sets
`master_clock_rate` in UHD. There were some common options
(153.6MHz, 125MHz, 122.88MHz) missing for N310s. Now these options are added.
Instead of a separate call to `set_clock_rate`, `master_clock_rate` is
now set as part of the device address string. This behavior makes it
more consistent with UHD examples. Flowgraphs that set MCR as part of
their `device_args` option, are currently overruled if clock rate is set
too. This behavior may easily be reversed.
According to the UHD manual, X300s don't support
`set_master_clock_rate`, thus in this case it is strictly necessary to
set MCR as part of the device address string.
=> uhd: Update possible master_clock_rate:s

gr-digital/lib/map_bb_impl.cc
This fixes #3670 and possibly #3014.
Which C++ revision is used on master? As far as I know, this patch shouldn’t be required with C++17 (and shouldn’t hurt either).
=> digital/map_bb: Add missing definition for a static class member

gr-uhd/include/gnuradio/uhd/usrp_block.h, gr-uhd/include/gnuradio/uhd/usrp_sink.h, gr-uhd/include/gnuradio/uhd/usrp_source.h, gr-uhd/python/uhd/bindings/docstrings/usrp_block_pydoc_template.h, gr-uhd/python/uhd/bindings/docstrings/usrp_sink_pydoc_template.h, gr-uhd/python/uhd/bindings/docstrings/usrp_source_pydoc_template.h, gr-uhd/python/uhd/bindings/usrp_block_python.cc, gr-uhd/python/uhd/bindings/usrp_sink_python.cc, gr-uhd/python/uhd/bindings/usrp_source_python.cc
- Move get_usrp_info() to usrp_block
- Casts the return value to std::map so PyBind11 can turn it into
a dictionary in Python
This fixes an issue where get_usrp_info() would cause an Exception with
PyBind11.
My version of https://github.com/gnuradio/gnuradio/pull/3611/files
=> uhd: wrap get_usrp_info to compatible return type

gr-fft/include/gnuradio/fft/window.h, gr-fft/python/fft/bindings/window_python.cc
fft::window is slated to replace firdes::window, we add the missing
WIN_NONE for consistency between the two.
=> fft: window: Add WIN_NONE

gr-channels/lib/selective_fading_model2_impl.cc, gr-channels/lib/selective_fading_model2_impl.h, gr-channels/lib/selective_fading_model_impl.cc, gr-channels/lib/selective_fading_model_impl.h, gr-channels/lib/sro_model_impl.cc, gr-channels/lib/sro_model_impl.h
There are some `new` statements left, but they are immediately casted to shared pointers (`rpcbasic_sptr`), so should not be a problem. And a `make_shared` solution is a separate decision, and is probably best done with some `sed` magic refactoring instead.
=> channels: Remove manual memory management

gr-fec/python/fec/bindings/CMakeLists.txt
Only adds in sources that require gsl and links gsl if gsl is found in gr-fec
Fixes #3587
=> fec: make gsl optional for python bindings

gr-fft/include/gnuradio/fft/window.h, gr-fft/lib/window.cc, gr-fft/python/fft/bindings/window_python.cc, gr-fft/python/fft/qa_window.py
```
commit f960615febe49a5cc68d3359c090a8c8b0068de1 (HEAD -> norm-win, mb/norm-win)
Author: Martin Braun <martin.braun@ettus.com>
Date:   Thu Aug 13 17:06:36 2020 +0200
fft: window: Allow normalizing windows
In some applications, it is useful to generate windows that have unit
power. The boxcar window (rectangle) is always of unit power, but the
other windows are not, leading to apple-to-oranges comparisons, e.g.,
when switching between window types in a live spectrum estimation
application.
commit 56d4ad1d69eafe299880b4aad407f5717c5933d1
Author: Martin Braun <martin.braun@ettus.com>
Date:   Thu Aug 13 15:08:08 2020 +0200
fft: window: Provide default value for beta param on window::build
The API call fft::window::build() takes a third parameter, beta, that
only applies for the Kaiser …
```
=> fft: window: Allow normalizing windows

gr-blocks/lib/message_strobe_impl.cc, gr-blocks/lib/message_strobe_impl.h, gr-blocks/lib/message_strobe_random_impl.cc, gr-blocks/lib/message_strobe_random_impl.h, gr-blocks/lib/socket_pdu_impl.cc, gr-blocks/lib/tcp_connection.cc, gr-blocks/lib/tcp_connection.h, gr-blocks/lib/tcp_server_sink_impl.cc, gr-blocks/lib/tcp_server_sink_impl.h
Remove manual memory management in gr-blocks.
Now there's only one `new`, and there's no good way to work around it. But on the other hand it's fine. It's readable still.
=> blocks: Remove manual memory management

gnuradio-runtime/python/gnuradio/gr/__init__.py
These were previously aliased in the swig io_signature.i file but did not get ported in when swig was removed
=> runtime: add alias for io_signature{v,3,2}

gr-qtgui/include/gnuradio/qtgui/form_menus.h, gr-qtgui/include/gnuradio/qtgui/freq_sink_c.h, gr-qtgui/include/gnuradio/qtgui/freq_sink_f.h, gr-qtgui/include/gnuradio/qtgui/freqdisplayform.h, gr-qtgui/include/gnuradio/qtgui/waterfall_sink_c.h, gr-qtgui/include/gnuradio/qtgui/waterfall_sink_f.h, gr-qtgui/include/gnuradio/qtgui/waterfalldisplayform.h, gr-qtgui/lib/freq_sink_c_impl.cc, gr-qtgui/lib/freq_sink_c_impl.h, gr-qtgui/lib/freq_sink_f_impl.cc, gr-qtgui/lib/freq_sink_f_impl.h, gr-qtgui/lib/freqdisplayform.cc, gr-qtgui/lib/waterfall_sink_c_impl.cc, gr-qtgui/lib/waterfall_sink_c_impl.h, gr-qtgui/lib/waterfall_sink_f_impl.cc, gr-qtgui/lib/waterfall_sink_f_impl.h, gr-qtgui/lib/waterfalldisplayform.cc
The former has been declared deprecated, hence the shift.
=> qtgui: Replace firdes::window with fft::window

grc/gui/Application.py
When something bad happens in the rendering of a flowgraph, usually due to a mako generation failure, the previously rendered flowgraph with the same name is run.  This can be particularly confusing and mask the underlying error.
Fixes #3580
=> grc: do not run stale flowgraph

gr-qtgui/grc/qtgui_freq_sink_x.block.yml, gr-qtgui/include/gnuradio/qtgui/freq_sink_c.h, gr-qtgui/include/gnuradio/qtgui/freq_sink_f.h, gr-qtgui/lib/freq_sink_c_impl.cc, gr-qtgui/lib/freq_sink_c_impl.h, gr-qtgui/lib/freq_sink_f_impl.cc, gr-qtgui/lib/freq_sink_f_impl.h, gr-qtgui/python/qtgui/bindings/docstrings/freq_sink_c_pydoc_template.h, gr-qtgui/python/qtgui/bindings/docstrings/freq_sink_f_pydoc_template.h, gr-qtgui/python/qtgui/bindings/freq_sink_c_python.cc, gr-qtgui/python/qtgui/bindings/freq_sink_f_python.cc
When switching between window functions in a live FFT GUI session, the
difference in power of the window functions is notable. This allows
asserting the 'normalize' argument of fft::window::build() by setting a
bit in the window type during construction,, or by calling a new API
call: set_fft_window_normalized().
Note: The choice to use an unused bit to set the normalization comes
from an attempt to keep the API backward compatible. Adding a new
argument to the make call would require reordering the make arguments.
This feature allows changing window types without signal power varying
due to window power differences.
Note that this does not affect scalloping loss, or processing loss from
the window. For example, the peak value of a sine tone will still vary
for different windows, because …
=> qtgui: freq_sink: Allow normalization of window functions

CMakeLists.txt
PR #3369 incorporated boost/endian, which does not appear until Boost 1.58
Either more conditional includes need to be added or we bump up the min boost version (losing support for Centos7)
=> boost: increase minimum version to 1.58 for boost/endian

grc/gui/Application.py, grc/gui/DrawingArea.py, grc/gui/Notebook.py
Fixes #2610.
Fixes #3507.
A confluence of bugs introduced while updating GRC to Python 3 results in keystrokes being sent to the drawing area while typing in the block search box.
First, the drawing area needs to be placed in a Viewport before being added into a ScrolledWindow. Fixing this allows the drawing area to grab focus as intended when it is clicked.
Second, the drawing area needs to unselect all blocks when it loses focus so that the relevant keystroke actions can be disabled. This functionality was commented out during the transition to Python 3, and I've restored it here.
The partial workaround implemented in #2574 is no longer needed, so I removed it.
=> grc: prevent search keystrokes from modifying flowgraph 

grc/gui/DrawingArea.py
This pull request resolves the residual issue I noted in https://github.com/gnuradio/gnuradio/pull/3710#issuecomment-676538092.
After blocks are unselected, it's necessary to trigger an `Action` so that keystroke action handlers will be updated in `Application._handle_action`. In my previous pull request, I achieved this by replacing a `FlowGraph.update_selected()` call with a `FlowGraph.update_selected_elements()` call, since the latter happens to trigger an `Action`. However, this does not occur in all cases, because `FlowGraph.update_selected_elements()` can return early.
To fix the issue, I've reverted that change and changed the `DrawingArea`'s `focus-out-event` handler to explicitly trigger `Actions.ELEMENT_SELECT()`.
After this change, blocks appear to be unselect in all cases when …
=> grc: prevent search keystrokes from modifying flowgraph, take two

grc/gui/Application.py, grc/gui/DrawingArea.py, grc/gui/Notebook.py
This backports #3710 to GNU Radio 3.8. I've tested and this works as in 3.9.
=> grc: prevent search keystrokes from modifying flowgraph

gr-blocks/lib/packed_to_unpacked_impl.cc
This fixes a typo in the assert of packed_to_unpacked that was leftover an a naming conversion from d_log2 to log2.
This prevents the ubuntu packages from building - not sure why it passes CI
=> blocks: fix typo, artifact of log2_l_type renaming

gr-uhd/docs/uhd.dox, gr-uhd/grc/gen_uhd_usrp_blocks.py, gr-uhd/include/gnuradio/uhd/usrp_block.h, gr-uhd/lib/usrp_block_impl.cc, gr-uhd/lib/usrp_block_impl.h, gr-uhd/lib/usrp_sink_impl.cc, gr-uhd/lib/usrp_sink_impl.h, gr-uhd/lib/usrp_source_impl.cc, gr-uhd/lib/usrp_source_impl.h, gr-uhd/python/uhd/bindings/docstrings/usrp_block_pydoc_template.h, gr-uhd/python/uhd/bindings/usrp_block_python.cc
UHD 4.0 is introducing a power reference level API, which will now
become available in GNU Radio. Its availability is conditionally
compiled into GNU Radio based on whether or not the feature is available
in the UHD version GNU Radio was compiled against.
USRP source and sink blocks receive the following new APIs:
- has_power_reference()
- set_power_reference()
- get_power_reference()
The command interface now understands a new `power_dbm` dictionary key.
The GRC bindings can now switch between absolute gain, normalized gain,
and absolute power settings.
=> uhd: Add power reference APIs

gr-fec/include/gnuradio/fec/cc_common.h, gr-fec/include/gnuradio/fec/polar_decoder_sc.h, gr-fec/include/gnuradio/fec/polar_decoder_sc_systematic.h, gr-fec/include/gnuradio/fec/polar_encoder.h, gr-fec/include/gnuradio/fec/polar_encoder_systematic.h, gr-fec/lib/cc_decoder_impl.cc, gr-fec/lib/cc_decoder_impl.h, gr-fec/lib/polar_decoder_sc.cc, gr-fec/lib/polar_decoder_sc_systematic.cc, gr-fec/lib/polar_encoder.cc, gr-fec/lib/polar_encoder_systematic.cc, gr-fec/lib/scl_list.h, gr-fec/python/fec/bindings/polar_decoder_sc_python.cc, gr-fec/python/fec/bindings/polar_decoder_sc_systematic_python.cc, gr-fec/python/fec/bindings/polar_encoder_python.cc, gr-fec/python/fec/bindings/polar_encoder_systematic_python.cc
This removes almost all manual memory management in gr-fec/.
`scl_list` is a bit of magic, so requires more thinking.
=> fec: Remove manual memory management

gr-uhd/apps/uhd_app.py, gr-uhd/apps/uhd_fft, gr-uhd/apps/uhd_siggen_base.py, gr-uhd/apps/uhd_siggen_gui
Note: This requires a USRP with power API enabled.
Summary of changes:
- uhd_app now provides the --power argument and applies it as
a reference power level. It clashes with --gain. UHDApp now has two
'modes' for setting the power: Via gain (the previous, standard way)
or by setting a power. UHDApp calls all the right APIs for each use
case.
- uhd_siggen_base is now aware of these settings and will make sure the
output power is correct by combining the requested power and the
requested amplitude (meaning, it sets a ref power that is at the
correct level above the requested power level).
- The GUI can now set either power or gain, depending on command line
arguments. When changing the amplitude in power mode, the ref power is
also changed so the output power (in dBm) stays the same when …
=> uhd: Update uhd_siggen_gui to allow setting absolute power

gr-uhd/apps/uhd_fft
This enables absolute power support for uhd_fft. For example:
uhd_fft --power -20 --args [...]
will run uhd_fft with all the usual settings, but will set the gain such
that the reference power level is -20 dBm. The y-axis will be labeled
differently ("RX Power Level (dBm)") and the gain slider will be
replaced by a power reference level slider.
Reading the actual received power from the display requires some DSP
knowledge. First, the choice of window will move energy into sidelobes,
and of course, scalloping loss plays a role. By choosing a boxcar window,
and moving the signal close to the center of a bin, it is possible to
measure the power of a single tone, assuming the USRP has been
previously calibrated.
The y-axis scaling is achieved by throwing in a multiplier that moves
a …
=> uhd: uhd_fft: Add support for --power argument

gr-blocks/lib/selector_impl.cc
Fixes #3762 
The selector block was forecasting that input samples were needed on all inputs rather than the active input, which caused the scheduler to stop calling the work() function when samples weren't being presented to the inactive input
=> blocks: selector: update to only forecast active input

gr-blocks/lib/selector_impl.cc
=> backport-3.8: blocks: selector: update to only forecast active input

gr-zeromq/lib/base_impl.cc, gr-zeromq/lib/base_impl.h, gr-zeromq/lib/pub_msg_sink_impl.cc, gr-zeromq/lib/pub_msg_sink_impl.h, gr-zeromq/lib/pull_msg_source_impl.cc, gr-zeromq/lib/pull_msg_source_impl.h, gr-zeromq/lib/push_msg_sink_impl.cc, gr-zeromq/lib/push_msg_sink_impl.h, gr-zeromq/lib/push_sink_impl.cc, gr-zeromq/lib/rep_msg_sink_impl.cc, gr-zeromq/lib/rep_msg_sink_impl.h, gr-zeromq/lib/rep_sink_impl.cc, gr-zeromq/lib/req_msg_source_impl.cc, gr-zeromq/lib/req_msg_source_impl.h, gr-zeromq/lib/req_source_impl.cc, gr-zeromq/lib/sub_msg_source_impl.cc, gr-zeromq/lib/sub_msg_source_impl.h, gr-zeromq/lib/sub_source_impl.cc
I believe this fixes a memory leak, as the thread objects were never deleted.
=> zeromq: Remove manual memory management

gr-blocks/lib/wavfile_sink_impl.cc, gr-blocks/lib/wavfile_sink_impl.h, gr-blocks/lib/wavfile_source_impl.cc, gr-blocks/lib/wavfile_source_impl.h
Calling libsndfile sf_read/write_float() for every sample created
too much overhead. sf_read/write_float() now called every 1024 samples.
=> gr-blocks: Fix wavfile sink and source block performance issues.

gnuradio-runtime/lib/basic_block.cc, gnuradio-runtime/lib/block.cc, gnuradio-runtime/lib/block_registry.cc
This addresses #3521 by ~~creating a new class object that contains an identifier that does not fail block lookup when messages are published to a block.~~ conducting early notification of message blocks by their `symbol_name` instead of their `alias`.
~~This is a crutch though,  a more desirable solution would be to unify the various ways blocks are addressed, mapped, and/or registered with runtime fixtures.~~
=> runtime: fix latency issue caused by setting block alias on message blocks

grc/core/Config.py
`os.path.sep` is unreliable in Windows (`\` in official python, `/` in MSYS2)
With this change, `os.pathsep` is used instead to get the path separator:
`:` (*nix) or `;` (Windows)
=> grc: use os.pathsep (Windows)

gr-audio/lib/osx/osx_sink.cc
Closes #3758 (supersedes those changes).
=> gr-audio: osx: Fix compilation and logging from static method.

gnuradio-runtime/lib/io_signature.cc, gr-fec/include/gnuradio/fec/fec_mtrx.h, gr-fec/include/gnuradio/fec/ldpc_G_matrix.h, gr-fec/include/gnuradio/fec/ldpc_H_matrix.h, gr-fec/lib/polar_common.cc, gr-fec/python/fec/bindings/fec_mtrx_python.cc, gr-fec/python/fec/bindings/ldpc_G_matrix_python.cc, gr-fec/python/fec/bindings/ldpc_H_matrix_python.cc
This adds some missing `<algorithm>` and `<string>` headers that are used but not explicitly included (presumably included somewhere else so it hasn't been a problem). This fixes compilation with MSVC on conda-forge, although why this wasn't needed earlier is a mystery.
=> lib, include: Add missing headers.

grc/gui/Dialogs.py
The Help -> Get Involved dialog in GRC is out of date: the "Get Involved" link is broken, and it still references Slack. I've refreshed it here.
Before:
After:
=> grc: update the "Get Involved" dialog

cmake/Modules/GrPybind.cmake, docs/doxygen/CMakeLists.txt
This fixes all of these commands on Windows (for at least my conda package) and wherever "python3" is not available. The CMake-found PYTHON_EXECUTABLE will always work or error out earlier if python is not found.
=> cmake: pybind: Use "${PYTHON_EXECUTABLE}" instead of "python3".

gr-digital/python/digital/bindings/header_buffer_python.cc, gr-qtgui/python/qtgui/bindings/ber_sink_b_python.cc, gr-qtgui/python/qtgui/bindings/const_sink_c_python.cc, gr-qtgui/python/qtgui/bindings/edit_box_msg_python.cc, gr-qtgui/python/qtgui/bindings/eye_sink_c_python.cc, gr-qtgui/python/qtgui/bindings/eye_sink_f_python.cc, gr-qtgui/python/qtgui/bindings/freq_sink_c_python.cc, gr-qtgui/python/qtgui/bindings/freq_sink_f_python.cc, gr-qtgui/python/qtgui/bindings/histogram_sink_f_python.cc, gr-qtgui/python/qtgui/bindings/number_sink_python.cc, gr-qtgui/python/qtgui/bindings/sink_f_python.cc, gr-qtgui/python/qtgui/bindings/time_raster_sink_b_python.cc, gr-qtgui/python/qtgui/bindings/time_raster_sink_f_python.cc, gr-qtgui/python/qtgui/bindings/time_sink_c_python.cc, gr-qtgui/python/qtgui/bindings/time_sink_f_python.cc, gr-qtgui/python/qtgui/bindings/vector_sink_f_python.cc, gr-qtgui/python/qtgui/bindings/waterfall_sink_c_python.cc, gr-qtgui/python/qtgui/bindings/waterfall_sink_f_python.cc
This is a compilation fix for MSVC.
=> python: bindings: Use nullptr instead of nonstandard __null.

gr-uhd/examples/grc/uhd_normalized_gain.grc, gr-uhd/grc/gen_uhd_usrp_blocks.py
Gain type hiding was inverted: It was supposed to hide gain type for
default (absolute/dB), and not hide for normalized and absoulute/dBm.
Fixed by this commit.
Also fixes an issue in uhd_normalized_gain.grc, where the gain type was
set to absolute/dB.
This was broken by one of the recent power API commits.
The example now looks like this:
Note that the gain type is not hidden (it says "Normalized"). The example was tested and works.
=> uhd: Fix gain type hiding, fix uhd_normalized_gain.grc

gnuradio-runtime/include/gnuradio/block_gateway.h
Fixes an incorrectly named Doxygen parameter.
=> runtime: gateway: Fix Doxygen warning

gnuradio-runtime/python/pmt/bindings/pmt_python.cc
per 3.8 behavior, and the GR wiki, the `__repr__` function of a PMT object should be overloaded to call `pmt::write_string`. This is currently not bound so this adds this binding.
Current master branch behavior:
```bash
jacob@ubuntu:/opt/gnuradio-master$ python3
Python 3.8.2 (default, Jul 16 2020, 14:00:26) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pdu_utils
>>> import pmt
>>> s=pdu_utils.PMTCONSTSTR__msg()
>>> s
<pmt.pmt_python.pmt_base object at 0x7f8ecefbf3f0>
>>> pmt.symbol_to_string(s)
'msg'
```
New behavior (matches 3.8):
```bash
jacob@ubuntu:/opt/gnuradio$ python3
Python 3.8.2 (default, Jul 16 2020, 14:00:26) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pdu_utils …
```
=> pmt: add binding for __repr__ function

gr-utils/modtool/cli/bind.py, gr-utils/modtool/core/bind.py
gr_modtool bind fails if the module references external packages like qt.
In such a case you see something like:
INFO Parsing source file "/home/schroer/gnuradiocomponents/gr-display/include/display/display_text_msg.h" ... 
/home/schroer/gnuradiocomponents/gr-display/include/display/display_text_msg.h:33:10: fatal error: 
'qapplication.h' file not found
#include <qapplication.h>
^~~~~~~~~~~~~~~~
1 error generated.
Error occurred while running CASTXML:  status:1
So I propose to add an optional parameter --addl_includes to gr_modtool bind to tell where to find the required includes.
This addresses #3759
=> Adding optional parameter addl_includes to gr_modtool bind

gnuradio-runtime/python/pmt/qa_pmt.py
currently there is nothing to check the absolute accuracy of PMT serialization, and it is easy for changes to break this provided serialize_str() and deserialize_str() are inverse functions. this provides some absolute reference PMT strings to ensure compatibility is retained.
Note: this version accounts for the serialization compatibility breakage i introduced in #3320. I will backport this onto 3.8 and will use the old serialization strings.
~~Note2: #3389 breaks this again, as dicts now need a different identifier from pairs. as soon as that is pulled in-tree, i will force-push a change to this to update accordingly.~~
Ready to merge.
=> pmt: add absolute pmt serialization QA

gr-digital/python/digital/modulation_utils.py, grc/core/utils/epy_block_io.py
Embedded python modules give the following warning:
```
/share/gnuradio/grdev/lib/python3/dist-packages/gnuradio/grc/core/utils/epy_block_io.py:55: DeprecationWarning: inspect.getargspec() is deprecated since Python 3.0, use inspect.signature() or inspect.getfullargspec()
```
Replacement of getargspec with getfullargspec is a straightforward swap
Fixes #3676
=> Replace deprecated getargspec function

gr-vocoder/lib/freedv_tx_ss_impl.cc, gr-vocoder/lib/freedv_tx_ss_impl.h
Fixes #2928.
Partially resolves #2875.
Replaces #3443.
The get_next_tx_char callback in the FreeDV modulator block is one of 
the last places where snprintf is used. I've eliminated it by using C++ 
string methods instead. This also removes the 79-character limit.
This change also fixes a bug where the last character of the message was 
not transmitted.
Lastly, I refactored the callback to be a static member function, 
eliminating the need for a separate structure to hold the callback 
state.
=> vocoder: refactor get_next_tx_char callback

gnuradio-runtime/lib/CMakeLists.txt, gnuradio-runtime/lib/pmt/CMakeLists.txt
INTERFACE_INCLUDE_DIRECTORIES in gnuradio-runtimeTargets.cmake and gnuradio-pmtTargets.cmake
is set by using CMAKE_INSTALL_PREFIX.
In some cross build system where install is relative this imply OOT build failure by using host system.
For example with gr-osmosdr the build fails with:
arm-linux-gnueabihf-g++: ERROR: unsafe header/library path used in cross-compilation: '-isystem' '/usr/include'
if INTERFACE_INCLUDE_DIRECTORIES is set like
$<INSTALL_INTERFACE:include>
the resulting file contains
INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
=> gnuradio-runtime, pmt: dont use CMAKE_INSTALL_PREFIX for target INSTALL_INTERFACE

gr-qtgui/python/qtgui/CMakeLists.txt
If running on Linux, the `DISPLAY` environment variable is not set and xvfb-run is present then run the Qt tests with xvfb-run. This would allows running the Qt test in the gnuradio's CI.
=> qa: Run qtgui tests with xvfb-run when needed

gr-digital/lib/correlate_access_code_bb_ts_impl.cc, gr-digital/lib/correlate_access_code_bb_ts_impl.h, gr-digital/lib/correlate_access_code_ff_ts_impl.cc, gr-digital/lib/correlate_access_code_ff_ts_impl.h, gr-digital/lib/correlate_access_code_tag_bb_impl.cc, gr-digital/lib/correlate_access_code_tag_bb_impl.h, gr-digital/lib/correlate_access_code_tag_ff_impl.cc, gr-digital/lib/correlate_access_code_tag_ff_impl.h, gr-digital/python/digital/qa_correlate_access_code_XX_ts.py, gr-digital/python/digital/qa_correlate_access_code_tag.py
Leftover data from last time CAC triggered, or just leading zeroes
being ignored.
This commit prevents these by assuring that we've processed at least
as many bits as the code is, before allowing a trigger.
This PR is an alternative to https://github.com/gnuradio/gnuradio/pull/3682
=> digital/correlate_access_code: Prevent false triggers

gr-vocoder/grc/CMakeLists.txt
Fixes https://github.com/gnuradio/gnuradio/issues/3836
=> gr-vocoder: Install missing block tree file.

gr-vocoder/include/gnuradio/vocoder/freedv_tx_ss.h, gr-vocoder/lib/freedv_tx_ss_impl.cc, gr-vocoder/lib/freedv_tx_ss_impl.h, gr-vocoder/python/vocoder/bindings/freedv_tx_ss_python.cc
Fixes #2932.
The input & output rates of the FreeDV modulator aren't necessarily the same. In particular, the 2400A and 2400B modes have an input rate of 8000 sps and an output rate of 48000 sps. To allow for arbitrary input & output rates, I've changed `freedv_tx_ss` from `sync_block` to `block`.
=> vocoder: allow input & output rates to differ

docs/doxygen/doxyxml/generated/compoundsuper.py, docs/doxygen/doxyxml/generated/indexsuper.py, gr-utils/modtool/templates/gr-newmod/docs/doxygen/doxyxml/generated/compoundsuper.py, gr-utils/modtool/templates/gr-newmod/docs/doxygen/doxyxml/generated/indexsuper.py
Partially resolves #3446.
I'm not quite sure how these docs work, but the dependency on six can be easily removed so I've done so here.
The headers suggest these files were auto-generated, but they've been subsequently edited by hand.
Together with #3808 and #3809 the dependency on six will be removed, after which the cmake references can be removed:
https://github.com/gnuradio/gnuradio/blob/4b402404e152ede29cfaa5c0648bdfb5d327038b/CMakeLists.txt#L322
https://github.com/gnuradio/gnuradio/blob/4b402404e152ede29cfaa5c0648bdfb5d327038b/CMakeLists.txt#L347-L352
=> docs: remove six

gr-digital/python/digital/packet_utils.py, gr-digital/python/digital/qa_packet_format.py
Partially resolves #3446.
gr-digital still had a few usages of `six.b`. They were only needed because bytes were incorrectly stored in stings. I've updated the code to use bytes where appropriate.
=> digital: remove six

gnuradio-runtime/python/gnuradio/eng_notation.py
Partially resolves #3446.
This change removes the last usage of six from the runtime component.
=> runtime: remove six

CMakeLists.txt
Resolves #3446.
Depends on #3808, #3809, and #3811.
Once the pull requests above are merged, GNU Radio will have no dependence on the six module, so we no longer need to check for it in cmake.
=> cmake: remove check for six module

gnuradio-runtime/lib/pmt/pmt_unv.cc, gnuradio-runtime/lib/pmt/qa_pmt_unv.cc
Partially resolves #2875.
This removes the last usage of `snprintf` from gnuradio-runtime. I also added tests to verify that the behaviour of `string_ref` is the same before & after the change.
=> runtime: remove snprintf

gnuradio-runtime/ConfigChecks.cmake
The last reference to `HAVE_SNPRINTF` was removed in a75f0c40fe0912535fe102792f27c13d01df8e3e so it should now be safe to remove it.
Together with #3817 and #3832, this resolves #2875.
=> runtime: remove unused HAVE_SNPRINTF macro

gnuradio-runtime/python/gnuradio/gru/mathmisc.py, gr-audio/examples/python/test_resampler.py
While working on #3809, I noticed that `gnuradio.digital.packet_utils.make_packet` is broken because `gnuradio.gru.lcm` returns a float instead of an integer. I've fixed that here, and `make_packet` now executes.
I also checked where `lcm` is used, and found that test_resampler.py was also broken; the LCM calculations were broken in https://github.com/gnuradio/gnuradio/commit/9e625c4821f4c63421b3d3747c0c4f358fef6c5f#diff-da129366a03c0bb69563f36127facf1d. I've restored them to their previous form here, except using Python 3's integer division operator `//`. After this change, test_resampler.py works again.
=> audio: fix lcm calculation

gr-filter/python/filter/qa_freq_xlating_fft_filter.py
a4b7a48f71a059c7410ee3e97aa682361cf22799 removed all references to `__future__` except this one.
=> filter: remove the last reference to __future__

gr-utils/bindtool/templates/generic_python_cc.mako
The mako template creates code fo PyObject * that must be hand edited.
For instance see the comments for qtgui widgets:
// .def("pyqwidget",&sink_f::pyqwidget,
//     D(sink_f,pyqwidget)
// )
// For the sip conversion to python to work, the widget object
// needs to be explicitly converted to long long.
This modification does this cast for PyObject *  . So no more hand editing is needed
=> Modify template to cast Python pointer correctly

docs/doxygen/Doxyfile.in
Moving newmod templates to a new directory in the modtool overhaul caused the files now to be visible to Doxygen. Fixed that.
=> docs: Exclude gr-newmod from Doxygen

gr-network/lib/tcp_sink_impl.cc, gr-network/lib/udp_sink_impl.cc
This includes using functions from the standard library to sleep instead of `usleep`, and a weird error where MSVC barfed on the variable name `s_host`.
=> network: lib: Fixes to get network to compile with MSVC

cmake/Modules/GrPybind.cmake
-Wall is not set for MSVC, and -Wno-unused-variable doesn't exist, so put it behind an if statement.
=> cmake: Fix pybind11 compiler definitions with MSVC.

gr-blocks/lib/stream_mux_impl.cc, gr-blocks/lib/stream_mux_impl.h
- replace C-style cast with reinterpret_cast<>
- make some variables const
- prefer in-class initializers for static data
- avoid copies in for loop by using a reference
These changes stem from review comments made on the new block Stream Demux (PR #3754) which apply to Stream Mux as well.
=> gr-blocks: Stream Mux C++ improvements

gr-utils/modtool/cli/add.py
This updates the logic of the modtool checking for duplicate block names to be consistent with what is on maint-3.8 (#3387 - which was a more recent PR and got updated with feedback). 
There is no functional change here, just a cleanup of the code by @alekhgupta1441 to be consistent with the 3.8 branch.
=> modtool: update of cli block name checking

gr-vocoder/examples/grfreedv.grc, gr-vocoder/grc/vocoder_freedv_rx_ss.block.yml, gr-vocoder/lib/freedv_rx_ss_impl.cc, gr-vocoder/lib/freedv_rx_ss_impl.h
Fixes #2929.
The FreeDV protocol includes a low bit rate text stream which is used to 
transmit information such as call sign and location. GNU Radio's FreeDV 
demodulator block sets up a callback to receive this text data, but the 
callback currently does nothing.
Here I've added an optional message output to the block. It collects 
characters until a carriage return is encountered, then outputs a 
string. I've updated the sample flow graph to print these messages using 
the Message Debug block.
=> vocoder: add text message output to FreeDV demodulator

cmake/Modules/GnuradioConfig.cmake.in
GrPython.cmake now sets the default correctly thanks to #2939
Closes #3729
=> Remove hardcoded GR_PYTHON_DIR

gr-vocoder/python/vocoder/bindings/CMakeLists.txt
This helps prevent current and future headaches by making sure improvements to the pybind11 CMake don't also need to be added specifically for gr-vocoder.
(I noticed that a change similar to #3788 would be needed for gr-vocoder as well, but this fixes it instead by not duplicating the CMake code that needs to be fixed.)
=> vocoder: cmake: Use pybind macros to manage bindings.

gr-blocks/python/blocks/parse_file_metadata.py
The utility gr_read_file_metadata uses parse_file_metadata.parse_header()
from gr-blocks to parse and print headers in a metadata file. Currently,
the rx_time field is printed with us precision. However, the rx_time is
stored as the integer seconds of the UNIX timestamp in an uint64_t plus
a double storing the fraction of a second, so the rx_time has more
precision.
A precision on the order of 1ns is necessary for many ranging applications,
since 1us is approximately 300m of range.
This modifies parse_file_metadata.parse_header() to print the full
fractional part as stored in the double. Aditionally, it adds
"rx_time_secs" and "rx_time_fracs" fields to the dict() return value of
parse_header(), in case they are ever needed. The "rx_time" field in this
dict() is a double, and as such it is …
=> blocks: prevent losing rx_time precision in gr_read_file_metadata

gr-utils/modtool/templates/gr-newmod/python/__init__.py, gr-utils/modtool/templates/gr-newmod/python/bindings/CMakeLists.txt
Python-only modules were not skipping out on the binding compilation causing build errors.  This copies the breakout code previously from the swig directory
Fixes #3782
=> modtool: leave out bindings for python only modules

gr-blocks/grc/blocks_message_debug.block.yml, gr-blocks/include/gnuradio/blocks/message_debug.h, gr-blocks/lib/message_debug_impl.cc, gr-blocks/lib/message_debug_impl.h, gr-blocks/python/blocks/bindings/docstrings/message_debug_pydoc_template.h, gr-blocks/python/blocks/bindings/message_debug_python.cc
aggregates the data to be printed into a stringstream so that it is printed at the same time reducing debug information becoming muddled between competing cout statements. this change also provides an argument to this block to disable the printing of PDU uniform vectors which are often not needed for debug purposes
I also moved the constructor and destructor to be more consistent with other blocks
=> blocks: improvements to the message_debug block

gr-utils/modtool/templates/templates.py, gr-utils/modtool/tools/grc_yaml_generator.py
Two minor cleanups in makeyaml
1) There was a missing `f` in the recent f-string conversion
2) The new comments int the default grc template caused the makeyaml parsing to create 2 inputs and 2 outputs
To test, create a simple OOT and then run `gr_modtool makeyaml blockname` and look at the generated grc yaml file
=> modtool: minor cleanup makeyaml

grc/scripts/freedesktop/CMakeLists.txt, grc/scripts/freedesktop/README, grc/scripts/freedesktop/org.gnuradio.grc.metainfo.xml
This might warrant a backport to maint-3.8, too.
=> Add a metainfo/appstream file for GRC, so that distro appstores find us

cmake/Modules/GrPybind.cmake, gr-utils/bindtool/core/generator.py, gr-utils/blocktool/core/parseheader_generic.py, gr-utils/modtool/cli/bind.py, gr-utils/modtool/core/bind.py, gr-utils/modtool/templates/gr-newmod/python/bindings/bind_oot_file.py
At the moment neither gr_modtool bind nor the GR_PYBIND_MAKE_OOT macro consider additional ( required ) includes like QWidgets or consider defines like ENABLE_PYTHON.
So bind may fail or generate wrong bind code.
This pr fixes this issue and includes #3629
=> Make additional includes and defines available in the bind process

cmake/Modules/GrPybind.cmake
This permits an OOT to override the hash checking
putting a 0 for BINDTOOL_HEADER_FILE_HASH will ignore the hash checking.
This would:
1) Not be the default behavior
2) only for OOTs
3) Use at your own risk
/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(foo.h) …
=> cmake: manual override to ignore pybind hash checking

gr-zeromq/lib/base_impl.cc
Re: #1132 the default value of ZMQ_Linger was incorrect in the ZMQ docs, and is currently -1, which causes sockets with pending messages to block indefinitely during tear down, causing flow graphs to lock up indefinitely during top_block.stop() if outbound data is pending on the ZMQ socket.
It's challenging to reliably reproduce this condition so I don't have code for that, but in my code that uses ZMQ pub/sub sinks/sources to pass data around, it regularly locks up at least once about every 8 hours in top_block.stop()
It might make more sense for ZMQ_Linger to be configurable, but that is beyond my C++ abilities, and I think a ZMQ_LINGER of 0 is sensible since it really only effects data during tear down.
=> Add ZMQ_Linger of 1000ms to ZMQ socket creation to prevent infinite block in top_block.stop()

gr-digital/include/gnuradio/digital/ofdm_equalizer_simpledfe.h, gr-digital/lib/ofdm_equalizer_simpledfe.cc, gr-digital/python/digital/bindings/ofdm_equalizer_simpledfe_python.cc, gr-digital/python/digital/qa_ofdm_frame_equalizer_vcvc.py
This should solve a limitation in [`ofdm_equalizer_simpledfe`](https://www.gnuradio.org/doc/doxygen/classgr_1_1digital_1_1ofdm__equalizer__simpledfe.html):
> Note that the equalized symbols are exact points on the constellation. This means soft information of the modulation symbols is lost after the equalization, which is suboptimal for channel codes that use soft decision.
Hopefully, this simple fix has no downsides... (it seemed *too* obvious to me)
Here is a grc flowgraph based upon the rx_ofdm example: https://gist.github.com/japm48/4ce310709702bb84d12c980cc0ed2330
I can add this to the examples folder, or maybe create a testbench (but I'm not really sure how properly do that in this case).
Here is the relevant result:
=> digital: ofdm_equalizer_simpledfe: add output_exact_syms option

gr-analog/python/analog/bindings/cpm_python.cc, gr-analog/python/analog/bindings/noise_type_python.cc, gr-analog/python/analog/bindings/sig_source_waveform_python.cc, gr-blocks/python/blocks/bindings/file_meta_sink_python.cc, gr-blocks/python/blocks/bindings/message_strobe_random_python.cc, gr-blocks/python/blocks/bindings/pdu_python.cc, gr-blocks/python/blocks/bindings/wavfile_python.cc, gr-digital/python/digital/bindings/adaptive_algorithm_python.cc, gr-digital/python/digital/bindings/corr_est_cc_python.cc, gr-digital/python/digital/bindings/interpolating_resampler_type_python.cc, gr-digital/python/digital/bindings/meas_evm_cc_python.cc, gr-digital/python/digital/bindings/metric_type_python.cc, gr-digital/python/digital/bindings/mpsk_snr_est_python.cc, gr-digital/python/digital/bindings/timing_error_detector_type_python.cc, gr-dtv/python/dtv/bindings/catv_config_python.cc, gr-dtv/python/dtv/bindings/dvb_config_python.cc, gr-dtv/python/dtv/bindings/dvbs2_config_python.cc, gr-dtv/python/dtv/bindings/dvbt2_config_python.cc, gr-dtv/python/dtv/bindings/dvbt_config_python.cc, gr-fec/python/fec/bindings/cc_common_python.cc, gr-fft/python/fft/bindings/window_python.cc, gr-filter/python/filter/bindings/firdes_python.cc, gr-qtgui/python/qtgui/bindings/qtgui_types_python.cc, gr-qtgui/python/qtgui/bindings/trigger_mode_python.cc, gr-trellis/python/trellis/bindings/siso_type_python.cc, gr-utils/bindtool/templates/generic_python_cc.mako, gr-vocoder/python/vocoder/bindings/codec2_python.cc, gr-vocoder/python/vocoder/bindings/freedv_api_python.cc
With swig, there was an automatic conversion from int to enum, so ints could be passed through the python bindings.  This reenables that functionality with pybind11 ~~- if this looks acceptable, I'll do this for all the modules and it as an automatic step in binding enums.~~
UPDATE: propagated for all enums used in block parameters
Also, added to the bindtool so that `modtool bind` will add the implicit conversions
=> pybind: add implicit conversion from int to enum

gnuradio-runtime/lib/pmt/pmt.cc
Some of libpmt's features and behaviors have been a bit of a sore spot over the years; the hashtable being one of them. While replacing PMT with another serialization library is on the roadmap, we are stuck with them for now, so we might as well make them work for us.
Two annoying things I have noticed are the custom hash algorithm, and the small hash table size; I view both of these changes as suggestions for discussion. While this PR addresses both, they are separate changes and can be split up if necessary.
---
The hashing algorithm has been updated to use `std::hash<std::string>` which is very slightly faster (~3% on my ubuntu system), but more importantly not a homebrew undocumented algorithm. I did verify uniformity of the output of both algorithms:
The hash table size is a more …
=> PMT: replace custom hash implementation with std::hash and increase hash table size

gnuradio-runtime/lib/basic_block.cc, gnuradio-runtime/lib/block.cc, gnuradio-runtime/lib/block_registry.cc
This is a direct backport of #3536; resolution of the 3.8 backport will in my mind address #3521. While this does affect 3.7 I am not sure it is a big enough issue to justify a 3.7-backport.
This changes how the blocks are identified when they need to be notified that they have messages waiting. It also clarifies the name the block is registered with explicitly, and adds exceptions for looking up blocks that do not exist.
=> runtime backport-3.8: fix latency issue caused by setting block alias on message blocks

gr-audio/lib/windows/windows_sink.cc, gr-audio/lib/windows/windows_source.cc
Previously the header must have been pulled in by one of the Boost includes, because with a newer Boost version (1.74.0) I had build errors. This makes the include explicit so std::isdigit is guaranteed to be declared.
=> audio: lib: windows: Add <cctype> header for std::isdigit.

gnuradio-runtime/apps/gnuradio-config-info.cc
Signed-off-by: Derek Kozel <derek@bitstovolts.com>
A small usability addition to print most of the config info easily. This doesn't change the existing behaviors or formatting. I think the formatting could be improved, but am not sure if anyone is using the raw strings and we'd break their scripts. Possibly something to introduce early in the 3.10 development to give lots of advance warning.
=> utils: Added print-all to gnuradio-config-info

gnuradio-runtime/examples/mp-sched/wfm_rcv_pll_to_wav.py, gr-audio/examples/python/dial_tone_wav.py
The recent libsndfile transition in #3600 changed the API of the `wavfile_sink` block, so the two examples that use it need to be updated.
=> Fix examples that use wavfile_sink

gnuradio-runtime/examples/mp-sched/wfm_rcv_pll_to_wav.py, gr-digital/python/digital/crc.py
This is a continuation of the gru cleanup (#1591).
Neither of these files use the gru module anymore. I've tested that they work correctly after removing the unused imports.
=> Remove unused gru imports

gr-uhd/python/uhd/bindings/docstrings/usrp_block_pydoc_template.h, gr-uhd/python/uhd/bindings/usrp_block_python.cc
When I try to fix the problem in https://github.com/gnuradio/gnuradio/pull/3887, I found that it seems missing cmd_power_key python binding.
=> usrp_block: pybind: add missing bind for cmd_power_key

gr-audio/lib/windows/windows_sink.cc, gr-audio/lib/windows/windows_source.cc
Previously the header must have been pulled in by one of the Boost includes, because with a newer Boost version I had build errors. This makes the include explicit so std::isdigit is guaranteed to be declared.
=> backport-38: audio: lib: windows: Add <cctype> header for std::isdigit.

CMakeLists.txt, grc/core/Config.py, grc/core/generator/cpp_templates/CMakeLists.txt.mako, grc/core/generator/cpp_templates/flow_graph.cpp.mako, grc/core/generator/cpp_templates/flow_graph.hpp.mako, grc/core/generator/cpp_top_block.py
I'd appreciate some testing and feedback on this.
A few comments:
- I was originally planning on using the `link` field in the blocks' `cpp_templates` to figure out what components to include in the `find_package` call, but this isn't as straightforward as one might think, since some of the components depend on others and `find_package` doesn't follow these dependencies. This could work, but one would need to hard code the dependencies somewhere. In this PR, the find_package call enables **all available components** instead (all components that GR has been built with).
- I put the file/append call in the top-level `CMakeLists.txt` because `grc/CMakeLists.txt` doesn't know what components are enabled. This seems a little untidy, so I wouldn't mind any comments on other ways to let GRC know …
=> cppgen: Update to modern CMake

cmake/Modules/FindTHRIFT.cmake, gnuradio-runtime/include/gnuradio/CMakeLists.txt, gnuradio-runtime/include/gnuradio/rpc_shared_ptr_selection.h, gnuradio-runtime/include/gnuradio/rpcmanager_base.h, gnuradio-runtime/include/gnuradio/rpcserver_base.h, gnuradio-runtime/include/gnuradio/rpcserver_booter_aggregator.h, gnuradio-runtime/include/gnuradio/thrift_server_template.h
supersedes #2739.
The reason to do it this way instead of going @michaelld's route (sorry!) is that it removes the need to export the Thrift version that was used at build time. Since I guess that thrift will still be a source of version-specific joy in the future, having code that we can reuse directly on master to that allows compile-time checking of a numerical Thrift version will probably come in handy too, and this can be more or less directly cherry-picked onto master.
=> RPC: fixes to allow using Thrift 0.9 through 0.12

gr-qtgui/include/gnuradio/qtgui/CMakeLists.txt
That CMakeLists.txt does not belong installed under /usr/include/...
This is for the maint-3.8 branch.
Just like 3946 for master.
=> fix header file install

cmake/Modules/GnuradioConfig.cmake.in
Fixes: GNU Radio 3.8 installed with a package manager
hard codes GR_PYTHON_DIR #2856
=> allow oot override of gr python dir

gr-digital/examples/demod/constellation_encode_decode.grc, gr-digital/grc/digital.tree.yml, gr-digital/grc/digital_constellation_encoder_bc.block.yml, gr-digital/include/gnuradio/digital/CMakeLists.txt, gr-digital/include/gnuradio/digital/constellation_decoder_cb.h, gr-digital/include/gnuradio/digital/constellation_encoder_bc.h, gr-digital/lib/CMakeLists.txt, gr-digital/lib/constellation_encoder_bc_impl.cc, gr-digital/lib/constellation_encoder_bc_impl.h, gr-digital/python/digital/bindings/CMakeLists.txt, gr-digital/python/digital/bindings/constellation_encoder_bc_python.cc, gr-digital/python/digital/bindings/docstrings/constellation_encoder_bc_pydoc_template.h, gr-digital/python/digital/bindings/python_bindings.cc, gr-digital/python/digital/qa_constellation_encoder_bc.py
Add a new block that is the reverse of constellation decoder, to allow more flexibility in making modulation flowgraphs (not requiring chunks to symbols, constellation modulator, etc.)
Fixes #1801
=> digital: add constellation_encoder block

gr-qtgui/grc/qtgui_compass.block.yml
there are parameters in the 'documentation' section of the yml file which do not match the implementation
=> gr-qtgui: remove erroneous parameters in compass.block.yml

gr-blocks/include/gnuradio/blocks/rotator.h, gr-blocks/python/blocks/bindings/rotator_python.cc, gr-filter/lib/freq_xlating_fir_filter_impl.cc, gr-filter/lib/freq_xlating_fir_filter_impl.h, gr-filter/python/filter/qa_freq_xlating_fir_filter.py
Retuning the freq_xlating_fir_filter result in arbitrary phase jumps, which can affect phase-sensitive demodulators.
https://github.com/gnuradio/gnuradio/issues/3877
This PR
- adds rotator::phase() to allow access to the internal state of a rotator object
- adjusts the rotator used by the xlating filter to keep phase constant during retune
The algorithm here works for FIR filters with a constant phase delay over the passband, and having an odd number of taps.
It is unlikely that anyone depends on the current behavior (arbitrary phase jump).
Tested using https://gist.github.com/willcode/f32e905bc268eeebd0cf4cb95bb4b4f1.
=> Phase continuity for freq_xlating_fir_filter

CMakeLists.txt, cmake/Modules/GrBoost.cmake
Boost will be disabled even all required components besides unit_test_framework are available.
It would suffice to  disable testing.
=> Do not disable boost, if only the unit_test_framework is missing

gr-fec/python/fec/bindings/polar_decoder_sc_list_python.cc
The definition of the "polar" submodule in the pybind code was conflicting with the python polar submodule.
=> fec: remove stray pybind submodule definition for polar

gr-zeromq/lib/base_impl.cc
=> zeromq: Backport to 3.8: Add ZMQ_LINGER value to prevent infinite block

CONTRIBUTING.md, DCO.txt
Going forward, we will be requiring contributors to sign the DCO. This
commit adds the DCO text itself and updates the contribution guidelines.
=> Update the repository to reflect the requirement to sign the DCO

grc/gui/Application.py
When the modify parameters dialog block is constructed, the instance of
the block to be modified, is passed in. When the apply button is clicked
there is an extraenous flowgraph.import_data() call that re-creates all
blocks in the flowgraph. The consequence is that the block instance
passed to the dialog box is no longer the one in the flowgraph, and so
subsequent Applies have no effect. This change simply removes this call.
Fixes: #3914
=> grc: Fix multiple 'Apply' in modify block parameters dialog box

grc/gui/Executor.py
When running a "No GUI" flowgraph from GRC, it gives the following deprecation warning:
```
Option “-e” is deprecated and might be removed in a later version of gnome-terminal.
Use “-- ” to terminate the options and put the command line to execute after it.
```
This follows the suggested fix to update the deprecation
=> grc: fix gnome-terminal deprecation warning

grc/blocks/parameter.block.yml
If you change the type of a variable in the Properties Parameter editor the background colour of the parameter value is not updated.
You have to reload the editor for this parameter block to see the background colour according to the parameter type.
Fixes #3487 
This happens because the value box is evaluated before the type box.
Changing the order of the entries to type before value in the parameter.block.yml file fixes this issue.
=> Update parameter background colours realtime

grc/core/blocks/block.py
update_bus_logic() is called when disabling a bus, it doesn't check if it's been previously enabled. This causes it to restore port.hidden with a None which ultimately is converted to False. So it never hides the ports.
Also, filter message ports from buses.
Fixes: #3816
=> grc: Fix port show/hide problem due to bus logic update

gr-utils/modtool/templates/gr-newmod/python/__init__.py
Change the pass on exception to pass only on ModuleNotFoundError, not any ImportError
This should make the behavior as follows:
1) Python only module should import without error (by passing at ModuleNotFoundError)
2) C++ module with missing symbol should be caught and displayed
Tested 2) by creating a block with a dummy function in the header with no implementation.  Then call that implementation from another function.  Compiles ok, but will cause undefined symbol error at import.
Fixes #3884
=> modtool: Change handled exception to ModuleNotFoundError

grc/gui/PropsDialog.py, grc/gui/canvas/block.py
Prior to 3.8 block IDs were shown in the properties dialogue for every block as these are important for function of some GR features. #2795 brought this back as an option for 3.8+, however it forces the `hide` value to effectively be `none` instead of `part` (not visible on the block canvas but visible in the properties dialogue) for all blocks. This changes this back to the pre-3.8 behavior where the ID value is not shown on the canvas but is shown in the properties dialogue.
I realize this was a deliberate change by @mormj but most block IDs add little value on the canvas and the exceptions to this are explicit in their yaml files (e.g.: variables). I also realize that the change to the PropsDialog.py does not actually change anything, but it matches the intention.
=> grc: restore pre-3.8 block id behavior

gr-utils/modtool/templates/gr-newmod/CMakeLists.txt
The gr_modtool utility should respect the `-DENABLE_PYTHON=OFF` setting to allow modules to be built without python support. This also does not install any GRC files even though it is possible to use GRC to generate flowgraphs without runtime python; however, this disabling python _and_ using GRC for C++ generation is a very advanced feature so the included note should be sufficient to inform anyone using in this way.
It should be possible to automatically install blocks that have `cpp_template`s defined at some point in the future should that become a necessary feature; for now even C++ only OOT's is a fairly niche need.
=> modtool: CMake template should allow building OOT modules without python if desired

gr-fft/python/fft/bindings/window_python.cc, gr-fft/python/fft/qa_window.py, gr-uhd/apps/uhd_fft
In 3.8 the window enums were placed under fft.window, but in the pybind transition, these got wrapped as fft.win_type.WIN_*
This is an unnecessary departure from the 3.8 API, and this restores the 3.8 API.
This is a subset of #3996 as this is the more critical part of that PR
=> FFT window type enums

gr-qtgui/gnuradio-qtgui.pc.in
Variable interpolation is done with configure_file(... @ONLY), so use @VAR@ and not ${VAR}.
I do not have a great way to test this, but I'm pretty sure the way it is now is wrong.
Fixes #3969.
=> cmake: Fix variable substitution in pkg-config

grc/core/generator/flow_graph.py.mako
This fixes flowgraph generation when using connection templates with
multiple lines. Previously it would only indent the first line and
subsequent lines would have no indentation, causing a python error.
=> grc: indent multiline connections in py flowgraph generation

gr-blocks/lib/file_source_impl.cc
Fixes https://github.com/gnuradio/gnuradio/issues/3971
=> gr-blocks: Fix file source block large file handling for Windows.

gr-fec/lib/reed-solomon/decode_rs.h, gr-fec/lib/reed-solomon/decode_rs_ccsds.c, gr-fec/lib/reed-solomon/encode_rs.h, gr-fec/lib/reed-solomon/encode_rs_ccsds.c
This fixes building with MSVC. Since these files first get built into an object that is *not* a shared library, `FEC_API` was resolving to `__declspec(dllimport)`, which should never be used for function definitions. Warnings still occur about inconsistent dll linkage because the `gr_fec_rs` target is built into an object library that doesn't define `gnuradio_fec_EXPORTS`, but the end result works. These warnings have always existed previously.
=> fec: lib: Remove use of FEC_API for function definitions.

gr-uhd/grc/gen_uhd_usrp_blocks.py
Backport of #3667 from @jdemel - any reason for this to not go on maint-3.8?
A USRP block offers the option to set a `clock_rate` which in turn sets
`master_clock_rate` in UHD. There were some common options
(153.6MHz, 125MHz, 122.88MHz) missing for N310s. Now these options are added.
Instead of a separate call to `set_clock_rate`, `master_clock_rate` is
now set as part of the device address string. This behavior makes it
more consistent with UHD examples. Flowgraphs that set MCR as part of
their `device_args` option, are currently overruled if clock rate is set
too. This behavior may easily be reversed.
According to the UHD manual, X300s don't support
`set_master_clock_rate`, thus in this case it is strictly necessary to
set MCR as part of the device address string.
=> Backport 3.8: uhd: Update possible master_clock_rate

gr-digital/grc/digital_constellation.block.yml, gr-digital/include/gnuradio/digital/constellation.h, gr-digital/lib/constellation.cc, gr-digital/python/digital/bindings/constellation_python.cc
This allows to easily create signals with normalized power and makes it consistent with the 16-QAM constellation (which is also normalized for mean square magnitude = 1).
=> Normalize the constellation points so that the mean square magnitude is 1 (instead of the non-squared magnitude).

gr-uhd/lib/usrp_block_impl.cc, gr-uhd/lib/usrp_block_impl.h, gr-uhd/lib/usrp_source_impl.cc
When using boost>=1.73 and compile with uhd, it always have errors.
This patch fix the compile error when using uhd and gcc10: error: ‘_1’ was not declared.
Bug: https://bugs.gentoo.org/751259
Log(xz format): https://bugs.gentoo.org/attachment.cgi?id=668564
I've test and it seems works under my environment.
=> gr-uhd/lib/usrp_block_impl.cc: fix compile error using boost>=1.73

CMakeLists.txt
The version parsing in [`GrVersion.cmake`](https://github.com/gnuradio/gnuradio/blob/master/cmake/Modules/GrVersion.cmake#L51-L79) expects exactly the string "git" as either the `MINOR_VERSION` or `MAINT_VERSION` in order to set the dependent variables correctly. Without this fix, Windows builds will fail because `RC_MAINT_VERSION` contains an invalid string.
=> cmake: Set VERSION_PATH to be only "git", fixing RC_MAINT_VERSION.

gr-digital/include/gnuradio/digital/ofdm_chanest_vcvc.h, gr-digital/python/digital/bindings/ofdm_chanest_vcvc_python.cc, gr-digital/python/digital/qa_ofdm_chanest_vcvc.py
Both the C++ and Python files have really weird whitespace issues,
making them hard to read. This makes the whitespace usage for consistent
with usual formatting, and fixes some Doxygen issues.
=> digital: ofdm: Fix whitespace in OFDM chanest block

cmake/Modules/FindTHRIFT.cmake, config.h.in, gnuradio-runtime/include/gnuradio/rpcserver_thrift.h, gnuradio-runtime/include/gnuradio/thrift_server_template.h, gnuradio-runtime/lib/controlport/thrift/rpcserver_thrift.cc
Adds ability for master to build with newer Thrift versions
by checking availability of thrift include files.
(Also spelling fix: Thift -> Thrift)
And fix up logging for rpcserver_thrift class.
=> RPC fixes to allow using Thrift-0.13

cmake/Modules/Findlibunwind.cmake, gnuradio-runtime/lib/CMakeLists.txt, gnuradio-runtime/lib/terminate_handler.cc, gnuradio-runtime/lib/terminate_handler.h, gnuradio-runtime/lib/top_block_impl.cc, gnuradio-runtime/python/gnuradio/gr/top_block.py
```
This consists of the following changes:
1. Add a top_block parameter to control exception handling
This restores past behavior where the scheduler catches exceptions
raised in block threads, allowing flowgraphs to continue running after
the failure of an individual block. It also adds optional new behavior,
selected by setting catch_exceptions=False to the top block, which causes
exceptions to not be caught. In this mode of operation, a std::terminate
handler can be installed to print a stack trace before the flowgraph exits.
2. Add terminate_handler to top_block_impl
This adds a terminate_handler function that prints information
about any uncaught exceptions and also attempts to print a backtrace
for said exception after which it calls std::abort. The backtrace is
printed via …
```
=> runtime: Add terminate handling

gnuradio-runtime/lib/pmt/pmt_unv.cc
The current method of converting pmt char values to strings results in non-unicode characters - looks like it was using the pointer value in the string reference.  This just uses std::to_string on the char values
Fixes #3398
=> pmt: use to_string for char string_refs

gr-uhd/lib/usrp_block_impl.cc, gr-uhd/lib/usrp_block_impl.h, gr-uhd/lib/usrp_source_impl.cc
When using boost>=1.73 and compile with uhd, it always have errors.
Fix the compile error when using uhd and gcc10: error: ‘_1’ was not declared
Bug: https://bugs.gentoo.org/751259
usrp_source_impl.cc: use lambdas instead of boost::bind
usrp_block_impl.cc:use lambdas instead of boost::bind
usrp_block_impl.h: Switch from boost::function to std::function
https://github.com/gnuradio/gnuradio/pull/3441
https://github.com/gnuradio/gnuradio/pull/3887
usrp_source_impl: fix parameter bug of original code
The usrp_block_impl::register_msg_cmd_handler uses cmd_handler_t as
handler type, but it have 3 parameters.
Fix the parameter mismatch bug and change the signature as cmd_handler_t
Signed-off-by: Huang Rui <vowstar@gmail.com>
=> [Backport] gr-uhd/lib/usrp_block_impl.cc: fix compile error using boost>=1.73

gr-qtgui/grc/qtgui_number_sink.block.yml, gr-qtgui/lib/number_sink_impl.cc
GUI was overriding block parameter (setting to 0) at init.
- Use block parameter for 'avg'
- Add callback for 'avg' to yml
It is still possible to set the avg from the GUI middle click. The menu
value is not updated when avg is set from a block parameter (there is no
slot in the widget to do this). If the user creates a GRC file with a
widget (e.g., entry) to set avg, and also sets it via the menu, the
values shown will not match. However, the value can be successfully set
either way.
Fixes https://github.com/gnuradio/gnuradio/issues/4034
Should be backported to 3.9 and 3.8.
=> gr-qtgui number sink: Honor block setting of 'avg' in GUI

gr-qtgui/python/qtgui/toggleswitch.py
Fixes #3939.
Toggle switch was left==on, now right==on.
=> qtgui: toggle switch was reversed

gr-filter/python/filter/pfb.py
When create_taps() was moved to a static function, a _self reference
tagged along. Use function parameter as intended.
=> pfb.py: fix variable in static function

gr-filter/lib/rational_resampler_impl.cc
When interp/decim was calculated in python, the d_decimation value could be set in the constructor.  Now it needs to be set after the calculation in the constructor.
=> filter: update decimation after gcd calculation

gr-qtgui/python/qtgui/toggleswitch.py
Toggle switch was left==on, now right==on.
Fixes #3939.
=> QTGUI: Toggle switch was reversed. 

cmake/Modules/GnuradioConfig.cmake.in
This was fixed on master a long time ago and should also have gone in a backport for 3.8 at least. Meantime another attempt to address the issue with installing OOT's to a custom install prefix was made in https://github.com/gnuradio/gnuradio/pull/3944, but this is an improper fix as it requires the user to specify yet another variable at configure time.
This pull request backports the original pull request from master https://github.com/gnuradio/gnuradio/pull/3730 to maint-3.8. This is also available in maint-3.9.
=> Backport Remove hardcoded GR_PYTHON_DIR 

gr-digital/grc/digital_constellation.block.yml, gr-digital/python/digital/bindings/constellation_python.cc
Adds implicit conversion to the enum type
Cleans up the binding code a bit (remove some dead code)
Change the dropdown from int to enum (as in other places)
Fixes #4007
=> digital: fix yaml and bindings for constellation

gnuradio-runtime/lib/terminate_handler.cc, gnuradio-runtime/lib/terminate_handler.h
Two simple commits here to fix compiling terminate_handler.cc with MSVC, one correcting the location for the GR_RUNTIME_API macro and one correcting for a non-existent header with MSVC. I think these would have been fixed by #4012 and/or #4013, but it's hard to tell in the current state. Anyway, this gets it compiling for me.
This was needed to get MSVC compilation to work for my [3.9.0.0-rc2 conda package](https://github.com/conda-forge/gnuradio-feedstock/runs/1669068304).
It will also need a backport to 3.9 that I can push when approved.
=> runtime: lib: Fix terminate_handler compilation with MSVC

gnuradio-runtime/lib/terminate_handler.cc, gnuradio-runtime/lib/terminate_handler.h
Backport of #4056 to maint-3.9.
=> Backport to 3.9: runtime: lib: Fix terminate_handler compilation with MSVC

grc/converter/xml.py, grc/tests/test_xml_parser.py
Fixes `test_xml_parser.py` failing if lxml is not installed.
**Disclaimer**: Personally, I think the `test_flow_graph_converter_with_fp()` test should be removed, it does not seem like the `from_xml` functions (`load_stdlib()` and `load_lxml()`) are called with file pointer arguments anywhere (please correct me if I'm wrong) and they also do not state clearly that they accept both filenames and file pointers.
https://github.com/gnuradio/gnuradio/blob/0f1ec604f758e28d788ad71283236928d2d82300/grc/tests/test_xml_parser.py#L21-L27
https://github.com/gnuradio/gnuradio/blob/0f1ec604f758e28d788ad71283236928d2d82300/grc/converter/xml.py#L50-L67
Error:
```python
_________________________________________________________________ test_flow_graph_converter_with_fp …
```
=> grc: Accept file pointer in load_stdlib() (converter/xml.py)

gr-blocks/lib/file_meta_sink_impl.cc
Some fseek() calls were not being checked for failure.
=> gr-blocks: Check fseek() for failure

gr-filter/include/gnuradio/filter/fft_filter.h, gr-filter/include/gnuradio/filter/polyphase_filterbank.h, gr-filter/python/filter/bindings/fft_filter_python.cc, gr-filter/python/filter/bindings/polyphase_filterbank_python.cc
Because of the deleted copy constructor (previously implicit, now made explicit in this commit to match fir_filter.h), polyphase_filterbank.cc fails to compile with MSVC trying to use the fft_filter_ccf copy constructor. Explicitly declaring a default move constructor fixes this by allowing it to use the move constuctor instead, which is the behavior we want. It's a mystery why MSVC requires this and other compilers don't, but it works.
See #3892 for similar discussion and change for other filter classes. (This one wasn't caught there because changes from other PRs came in parallel.)
This was needed to get MSVC compilation to work for my [3.9.0.0-rc2 conda package](https://github.com/conda-forge/gnuradio-feedstock/runs/1669068304).
It will also need a backport to 3.9 that I can push when …
=> filter: Fix polyphase_filterbank for MSVC, w/ default move constructor.

grc/tests/test_expr_utils.py
The tests are xfail-marked, but the marked error was fixed in https://github.com/gnuradio/gnuradio/pull/2679. 
Another error remains, `test_simple()` randomly passes or fails with the error shown below. It also appears that `sort_objects2()` is not used anywhere. `sort_objects()`is used instead, and should be tested.
Note: I also had to rearrange the two first elements of the `expected` list but from what I can see the order of these two elements are unimportant to the correctness of the function
@skoslowski Should `sort_objects2()` be removed?
Error:
```python
____________________________________________________________________________ test_simple _____________________________________________________________________________
def test_simple():
objects = [
['c', '2 * a + b'],
['a', '1'], …
```
=> grc: Clean up test_expr_utils.py

gr-blocks/grc/blocks_stream_demux.block.yml, gr-blocks/grc/blocks_stream_mux.block.yml
fix default parameter 'Length' in Stream Mux block. Cannot connect in the flowgraph otherwise. Stream mux block example is OK as it uses '[3, 2]'.
=> Fix default parameters in Stream_Mux block

gnuradio-runtime/include/gnuradio/tag_checker.h, gnuradio-runtime/python/gnuradio/gr/bindings/tag_checker_python.cc, gr-trellis/include/gnuradio/trellis/fsm.h, gr-trellis/python/trellis/bindings/fsm_python.cc
Updating to MSVC 2019 and GNURadio 3.9. So far several minor build issues have come up. This pull fixes missing includes in public header files and an interesting bug with gr-filter and copy assign. The commits are separated to make them easy to cherry-pick.
=> MSVC 2019 fixes

gr-filter/include/gnuradio/filter/fft_filter.h, gr-filter/include/gnuradio/filter/polyphase_filterbank.h, gr-filter/python/filter/bindings/fft_filter_python.cc, gr-filter/python/filter/bindings/polyphase_filterbank_python.cc
Backport of #4055 to maint-3.9.
=> Backport to 3.9: filter: Fix polyphase_filterbank for MSVC, w/ default move constructor.

grc/tests/test_generator.py
Fixes the failing test (Issue: https://github.com/gnuradio/gnuradio/issues/2678). 
It fails because no blocks are found, since no block paths are supplied to the platform. This test requires blocks from grc and gr-blocks.
=> grc: Let test_generator.py know where to find blocks

gr-uhd/grc/gen_uhd_usrp_blocks.py
Fixing: https://github.com/gnuradio/gnuradio/pull/3486
Currently, `set_start_time` cannot be set in GRC.
When this is needed, the python file has to be changed manually which is overwritten when saving the next time.
This patch adds `set_start_time` to USRP Source/Sink.
It only shows up when it is set. Normally, it is set to `Default` which results in identical behavior than now. It can be set to an arbitrary float value indicating a time to start in seconds.
=> gr-uhd: Add set_start_time for grc in 3.7 (Update)

grc/core/platform.py, grc/main.py
This is an update for PR #2424. The extra debug output from GRC was
being generated by another logger instance in grc/core/platform that
did not respect the command line arguments.
This removes the extra logger and sets the logger level in main to
whatever is requested from the command line. See grc/main.py:43 for more
detail.
=> grc: Remove extra logger in grc/core/platform

grc/gui/Dialogs.py
Hey folks.
So, I have this proposal: error messages displayed in the `Errors and Warnings` dialog are quite long sometimes. As I user I would like to be able to copy it to buffer, so I can web search it or post somewhere, e.g. forum, GitHub issue, IRC, etc.
I have made a quick proof of concept where the error message is copied to the buffer on right mouse click. The UI mechanism can be reworked, e.g. we can have a menu with the 'Copy' item showing up or whatever.
Please let me know what you think of this idea. Thank you.
=> PROPOSAL: grc: Make it possible to copy error message to buffer

grc/gui/Application.py, grc/gui/Bars.py, grc/gui/MainWindow.py
Saves the grc prefs before executing a flowgraph to avoid losing them if
anything goes wrong and grc needs to be forcibly closed.
Also fixes recent files sub-menu refresh. When a file is opened, opened
from recent, or saved as, the recent files sub-menu is now updated.
Fixes: #3894
=> grc: Save config before execution and update recent file sub-menu.

grc/core/generator/flow_graph.py.mako
So originally I introduced the aboutToQuit() stuff in the hope to cleanly shutdown the flow graph, including the Qt widgets blocks before the Qt stuff is torn down.
Turns out that in aboutToQuit some stuff is already invalid, especially in OpenGL and so causes SegFault on exit.
Instead this patch modify the logic so that we stop the flow graph before Qt even begin disabling things.
The two shutdown path that exits are :
- The sig_handler in case we get TERM or INT signals
- The closeEvent() of the main window
This makes sure that both path call tb.stop() tb.wait() and also any snippet 'main_after_stop'.
=> Qt shutdown cleanup

gr-digital/examples/packet/example_corr_est.grc
In example_corr_est switch to dynamic threshold instead of absolute.
This make the example do something at start up instead of just
flatlining and it seems like the example becomes more interesting.
The tab control were missing a proper GUI hint and was just plced in
the bottom corner.
Add GUI hint to it and adjust the amount of rows the other time sink
consumes to let the sliders not consume that much screen real estate.
Slightly align blocks to look nicer.
---
This fix is very likely applicable on maint-3.9 and master as well. I have not verified it though.
=> gr-digital: Fixup example_corr_est

cmake/Modules/FindTHRIFT.cmake, config.h.in, gnuradio-runtime/include/gnuradio/rpc_shared_ptr_selection.h, gnuradio-runtime/include/gnuradio/thrift_server_template.h
Adds ability for maint-3.8 to build with newer Thrift versions
by checking availability of thrift include files.
(Also spelling fix: Thift -> Thrift)
=> RPC: fixes to allow using Thrift 0.13

gr-blocks/python/blocks/qa_peak_detector2.py
Compare of tuple vs list was failing.
Fixes issue noted after merge of https://github.com/gnuradio/gnuradio/pull/3356
=> gr-blocks qa for peak_detector2: fix result type in test5

gr-blocks/grc/blocks_stream_demux.block.yml, gr-blocks/grc/blocks_stream_mux.block.yml, grc/converter/xml.py, grc/tests/test_expr_utils.py, grc/tests/test_generator.py, grc/tests/test_xml_parser.py
Changes:
71bece9b9 (Adrien Michel, 6 days ago)
gr-blocks: fix default length with list in Stream Mux and Demux yml
Signed-off-by: Adrien Michel <adriengit@users.noreply.github.com>
0f90c7309 (Håkon Vågsether, 8 days ago)
grc: Accept file pointer in load_stdlib() (converter/xml.py)
Fixes test_xml_parser.py failing in the absence of lxml
4e2ef66f0 (Håkon Vågsether, 8 days ago)
grc: Clean up test_expr_utils.py
d0da6fe02 (Håkon Vågsether, 8 days ago)
grc: Let test_generator.py know where to find blocks
=> Backports to 3.9

gr-digital/grc/digital_modulate_vector.block.yml
Fixes cosmetic issue in https://github.com/gnuradio/gnuradio/issues/4036
No functional changes.
=> gr-digital: Fix typo in digital_modulate_vector block

grc/gui/Constants.py
This resolves an exception thrown when performing a drag and drop from the block list to the flow graph on macOS.
See discussion in #2727 in which @eblot proposed this patch more than a year ago, but as far as I know was not put forward as a pull request.
The patch has already been in use for the last 6 months when installing GNU Radio on macOS via conda.
=> grc: Fix drag n' drop issue with Quartz (macOS) backend

cmake/Modules/GrPybind.cmake, cmake/Modules/GrPython.cmake, gnuradio-runtime/lib/CMakeLists.txt, gr-qtgui/lib/CMakeLists.txt
I've been using this for a little while in my conda packages, and it's about time some version of it got upstream. In light of possibly requiring CMake 3.16 for 3.10 development, this could probably be simplified. (By requiring CMake 3.16+, it would be possible to use the `Python::Python` and `Python::Module` targets defined by the builtin CMake FindPython module that was added for 3.12 and drop that part of GrPython.cmake.) But I'd rather trigger a discussion before going off and changing things, and at least maint-3.9 would require something closer to this. I can send that PR once this has had a few eyes on it.
So the description of the fix:
This fixes a segmentation fault with the Pybind11 bindings when trying to load any Python module on OSX with a different interpreter than was used …
=> cmake: python: Fix linking when runtime py interpreter != build time.

CMakeLists.txt
i.e. version - commit number from last tag - last commit hash.
=> cmake: Update VERSION_PATCH so that correct versioning is enabled.

gr-uhd/apps/uhd_app.py, gr-uhd/lib/usrp_block_impl.cc, gr-uhd/lib/usrp_block_impl.h
This is a [long overdue] fix for #1814 which adds a class member bool which will force a tune to occur if the 'direction' key is provided, and the value of that key is a symbol.
This PR also includes a commit fixing some misspellings in gr-uhd.
This should be backported all the way back to 3.7 in my opinion, but first I would like to see if this is acceptable.
=>  gr-uhd: fix directional tune commands being dropped when TX and RX are the same frequency

gr-uhd/lib/usrp_block_impl.cc, gr-uhd/lib/usrp_block_impl.h
This is used if a 'direction' key is provided with the tune command.
This fixes an issue when the 'TX' and 'RX' directions are tuned
explicitly to the same frequency; prior to this fix the second tune
request is dropped.
=> gr-uhd: adding a bool to force tune request

gr-uhd/docs/uhd.dox, gr-uhd/include/gnuradio/uhd/usrp_block.h, gr-uhd/lib/usrp_block_impl.cc, gr-uhd/lib/usrp_block_impl.h
This allows toggling GPIOs via messages.
Forward port of #3633.
=> uhd: Add GPIO handlers for messages

gr-fft/python/fft/logpwrfft.py
Block would fail as soon as it was placed in GRC.
A couple of imports/renames were needed.
=> gr-fft: Log Power FFT Python fix (backport 3.9)

grc/gui/canvas/flowgraph.py
Fixes https://github.com/gnuradio/gnuradio/issues/4075
Original PR: https://github.com/gnuradio/gnuradio/pull/4079
=> grc: Don't draw disabled and hidden blocks, even if they are selected (Backport-3.9)

cmake/Modules/GrPybind.cmake, cmake/Modules/GrPython.cmake, gnuradio-runtime/lib/CMakeLists.txt, gr-qtgui/lib/CMakeLists.txt
Backport of #4057 to maint-3.9.
=> Backport to 3.9: cmake: python: Fix linking when runtime py interpreter != build time.

CMakeLists.txt
This is the minimum we'll do anyways.
Bumping to C++17 seems relatively well-discussed, will be done in a separate commit, nevertheless.
=> Bump dependency versions to match these of 3.9; might increase further

gr-uhd/docs/uhd.dox, gr-uhd/include/gnuradio/uhd/usrp_block.h, gr-uhd/lib/usrp_block_impl.cc, gr-uhd/lib/usrp_block_impl.h
This command implements uhd::tune_request_t completely (and not just a
subset). Also includes updates to the manual.
Supersedes https://github.com/gnuradio/gnuradio/pull/3485
=> gr-uhd: Add command uhd handler for mtune ("manual tune")

gr-qtgui/grc/qtgui_time_raster_x.block.yml, gr-qtgui/include/gnuradio/qtgui/TimeRasterDisplayPlot.h, gr-qtgui/include/gnuradio/qtgui/time_raster_sink_b.h, gr-qtgui/include/gnuradio/qtgui/time_raster_sink_f.h, gr-qtgui/include/gnuradio/qtgui/timerasterdisplayform.h, gr-qtgui/lib/TimeRasterDisplayPlot.cc, gr-qtgui/lib/time_raster_sink_b_impl.cc, gr-qtgui/lib/time_raster_sink_b_impl.h, gr-qtgui/lib/time_raster_sink_f_impl.cc, gr-qtgui/lib/time_raster_sink_f_impl.h, gr-qtgui/lib/timerasterdisplayform.cc, gr-qtgui/python/qtgui/bindings/docstrings/time_raster_sink_b_pydoc_template.h, gr-qtgui/python/qtgui/bindings/docstrings/time_raster_sink_f_pydoc_template.h, gr-qtgui/python/qtgui/bindings/time_raster_sink_b_python.cc, gr-qtgui/python/qtgui/bindings/time_raster_sink_f_python.cc
This update allows a time raster sink's axis minimum, maximum,
and label to now be specified in the block configuration options.
This allows the block to be formatted to match a waterfall plot
in terms of having frequency on the lower axis.
Based on PR from ghostop14 <ghostop14@gmail.com>
=> qtgui:Added Time Raster Sink Control Axis Configuration

gr-utils/bindtool/scripts/binding-hash-hotfixer.zsh
DO NOT USE THIS TOOL IF ADDING OR REMOVING ANY FUNCTIONALITY FROM A
HEADER.
This tool allows to quickly update the hash in a binding file
(*/python/*/binding/something.cc).
WARNING: This script updates header hashes without checking whether the
underlying functionality changed. If you added or removed any python-bound
function in the header to this binding file THIS IS NOT THE TOOL YOU SHOULD BE
USING. Use bindtool instead to generate correct binding code.
=> Pybind: Adding header hash hotfixer

gr-qtgui/grc/qtgui_chooser.block.yml
Fixes https://github.com/gnuradio/gnuradio/issues/4031
Should be tested extensively, I can't guarantee that the `value in options` assert (which is a small enhancement unrelated to the original bug) does not collide with some existing flow graphs.
=> qtgui: Fix QT chooser labels

.github/workflows/make-test.yml, gnuradio-runtime/lib/constants.cc.in
```
commit 7b380c37ee182336d1214ee196f1eed8089ece43 (HEAD -> clang-format-cc-in, mb/clang-format-cc-in)
Author: Martin Braun <martin@gnuradio.org>
Date:   Wed Jan 20 15:35:52 2021 +0100
lib: Clang-format constants.cc.in
Because we always used globs to find the files we re-format, this
slipped under the clang-format-radar.
commit 19e29abc868becb9f493a08bdd29b28428ab4048
Author: Martin Braun <martin@gnuradio.org>
Date:   Wed Jan 20 15:35:03 2021 +0100
GitHub Actions: Also check .cc.in files
These files are templates that get expanded to C++ during CMake time.
They also need to follow our .clang-format, so let's check for them
during CI.
```
=> clang-format .cc.in

cmake/Modules/FindLOG4CPP.cmake, cmake/Modules/FindQwt.cmake
VCPkg uses the orocos log4cpp package as it is maintained, so this allows vcpkg compatibility
=> Cmake: accept orocos-log4cpp as acceptable alternative name 

CMakeLists.txt, gnuradio-runtime/lib/CMakeLists.txt, gnuradio-runtime/lib/constants.cc.in
This replaces the path constants for the prefix, system configuration, and preferences directories with a runtime prefix lookup based on the gnuradio-runtime library location and relative paths from that. Boost >= 1.61 is required, but this is now compatible with the minimum version required by GNU Radio overall.
I'm still using `boost::filesystem` here since that's currently what is used elsewhere, but with C++17 there is no reason that this and elsewhere couldn't be `std::filesystem` with the `<filesystem>` header.
Also use cmake-style paths instead of native paths for substitution to avoid unescaped character problems. Windows is able to use the forward-slash paths just fine, and this also has external benefits (e.g. conda will do path replacement during installation and it substitutes …
=> runtime: lib: Don't use hard-coded absolute path constants.

gr-qtgui/lib/eyedisplaysform.cc
Use QWidget::grab() instead (which was introduced in Qt 5).
=> gr-qtgui: Fix deprecated use of QPixmap::grabWidget()

CMakeLists.txt
Currently by default in a Win64 build, SYSCONFDIR is set to the absolute path.  This results in the installers retaining a reference to whatever path was used to build the installer, which is now irrelevant.  So applied the same logic from "isusr" when it's an MSVC build.  For those building themselves with MSVC to use vs. create an installer, it still works fine as well.
Then later the scripts change those paths to native paths instead of cmake.  This changes the slashes to backslashes on windows, which is fine outside of cmake, but unfortunately other GNURadio components reference these values using cmake, and so the back slashes cause build issues.  Since windows can natively handles slashes in either direction, there really is no value is switching to backslash so might as well just …
=> cmake: use certain relative paths in Win64 and stick to cmake paths

gr-fec/include/gnuradio/fec/fec_mtrx.h, gr-trellis/include/gnuradio/trellis/fsm.h
MSVC is looking for <string> to be included to get needed std::string namespace items
The fsm.h change also applies to maint-3.9
=> gr-fec / trellis: include <string> to allow windows to build

gr-qtgui/lib/eyedisplaysform.cc
This is a backport of #4120 to 3.9.
=> gr-qtgui: Fix deprecated use of QPixmap::grabWidget() (3.9)

gr-uhd/include/gnuradio/uhd/usrp_block.h, gr-uhd/lib/usrp_block_impl.cc, gr-uhd/lib/usrp_block_impl.h, gr-uhd/lib/usrp_sink_impl.cc, gr-uhd/lib/usrp_sink_impl.h, gr-uhd/lib/usrp_source_impl.cc, gr-uhd/lib/usrp_source_impl.h, gr-uhd/python/uhd/bindings/usrp_block_python.cc
It implements the ability to control frequency and gain in both
directions (Tx and Rx) with use of a single UHD source or sink - in the
same moment. It is possible to do that in separate moments with current
UHD blocks but this way it is not possible to change both Rx and Tx
settings for the same burst. Now, a single message can do that.
Note that there is a bit of an oddity here: The GNU Radio USRP blocks
are either Rx or Tx (source or sink). However, they all encapsulate an
underlying multi_usrp object. That means that under the hood, a USRP
source or a USRP sink potentially has access to the "other" direction.
This is made use in this patch.
To use this feature, add a direction key to the message dictionary going
to the block.
*note:* This is a new PR for …
=> uhd: Control of frequency and gain in both directions at the same moment

CMakeLists.txt, docs/CMakeLists.txt, docs/man/CMakeLists.txt, docs/man/dial_tone.1.in, docs/man/display_qt.1.in, docs/man/gnuradio-companion.1.in, docs/man/gnuradio-config-info.1.in, docs/man/gr-ctrlport-monitor.1.in, docs/man/gr-perf-monitorx.1.in, docs/man/gr_filter_design.1.in, docs/man/gr_modtool.1.in, docs/man/gr_plot_const.1.in, docs/man/gr_plot_fft.1.in, docs/man/gr_plot_iq.1.in, docs/man/gr_plot_psd.1.in, docs/man/gr_plot_qt.1.in, docs/man/gr_plot_time.1.in, docs/man/gr_read_file_metadata.1.in, docs/man/grcc.1.in, docs/man/polar_channel_construction.1.in, docs/man/tags_demo.1.in, docs/man/uhd_fft.1.in, docs/man/uhd_rx_cfile.1.in, docs/man/uhd_rx_nogui.1.in, docs/man/uhd_siggen.1.in, docs/man/uhd_siggen_gui.1.in, gnuradio-runtime/lib/CMakeLists.txt
Attempt to bring man pages in tree from gnuradio/pkg-gnuradio.
- Created docs/man with man pages
- Changed cmake to integrate MAN dir, build and install
- Added a sed to replace VERSION in man pages
- Started registering man pages as a GrComponent (similar to doxgen)
=> Bring man pages in-tree

.github/workflows/make-test.yml, CMakeLists.txt, gnuradio-runtime/lib/CMakeLists.txt, gnuradio-runtime/lib/constants.cc.in
Backport of #4129 and #4127 to maint-3.9.
=> [backport 3.9] runtime: lib: Don't use hard-coded absolute path constants and clang-format .cc.in

gr-digital/grc/digital_chunks_to_symbols.block.yml
Type was flagged as 'real_vector', which would mean vector<double>. We
want vector<float>, thus this fix.
This would cause an error when creating CPP code from GRC.
Signed-off-by: Terry May <terrydmay@gmail.com>
Same as https://github.com/gnuradio/gnuradio/pull/4136, but with fixed history.
=> digital: Fix output type in GRC bindings of chunks_to_symbols

gr-fft/include/gnuradio/fft/window.h, gr-fft/lib/window.cc, gr-fft/python/fft/bindings/docstrings/window_pydoc_template.h, gr-fft/python/fft/bindings/window_python.cc, gr-filter/include/gnuradio/filter/firdes.h, gr-filter/include/gnuradio/filter/hilbert_fc.h, gr-filter/lib/firdes.cc, gr-filter/lib/hilbert_fc_impl.cc, gr-filter/lib/hilbert_fc_impl.h, gr-filter/python/filter/bindings/firdes_python.cc, gr-filter/python/filter/bindings/hilbert_fc_python.cc
This addresses most of #3409 to allow use of all of the various windows that are included in GR now. Additionally bindings for the gaussian and Tukey windows, recent additions, have been added. Use of `beta` which is specific to the Kaiser filter has been replaced by `param` as a general parameter for the new kernels that also require a parameter for construction.
I think the C++ modernization aspect of the issue "Windowing code needs const and the like for more effective compiler optimization consistent with the rest of GR." would benefit from a look over by @ThomasHabets, please share any thoughts.
=> gr-fft: Expand window enum, fix a few other minor things

.gitattributes
In GNURadio 3.9, pybind11 compares hash values of headers and source files against knowns values.  Conversion of values to CRLF on checkout break those checks so keep LF values when files are subject to said checks.
I only saw code doing hashing for C source and header files.  Are there any other file types where this is used I didn't see?
Also, does these hash checks serve additional purposes after build that we need to be aware of?
=> Prevent Windows CRLF conversion for files subject to pybind hash comparisons

gr-fft/include/gnuradio/fft/window.h, gr-fft/lib/window.cc, gr-fft/python/fft/bindings/docstrings/window_pydoc_template.h, gr-fft/python/fft/bindings/window_python.cc
These have been deprecated for over 6 years in b2e6c0f247784ba4119cd6aa32998e7fcfa43f77, looks like Tom intended to have them removed in 3.8.
This is a misspelling of Nuttall / Blackman-Nuttall which are of course still in the code.
=> gr-fft: window cleanup - remove nuttal (sic) windows

gr-filter/include/gnuradio/filter/filterbank.h, gr-filter/include/gnuradio/filter/polyphase_filterbank.h, gr-filter/python/filter/bindings/filterbank_python.cc, gr-filter/python/filter/bindings/polyphase_filterbank_python.cc
Makes compilation less warning intense, too.
=> filterbanks: Use virtual destructor in superclasses

gr-qtgui/lib/DisplayPlot.cc, gr-qtgui/lib/TimeRasterDisplayPlot.cc, gr-qtgui/lib/WaterfallDisplayPlot.cc, gr-qtgui/lib/displayform.cc, gr-qtgui/lib/eyedisplaysform.cc, gr-qtgui/lib/numberdisplayform.cc
This requires >= Qt5.5, which is available everywhere.
=> Get rid of Qt compilation deprecation warnings

gr-utils/modtool/templates/gr-newmod/python/bindings/python_bindings.cc
Occurs if -Wall is enabled in OOT.
=> modtool: Remove -Wcomment warnings in python_bindings.cc template.

gr-utils/modtool/cli/base.py
If an import error happens in get_command(), the error is now logged.
=> utils: modtool: Improve exception handling for import error

grc/core/blocks/embedded_python.py, grc/core/generator/hier_block.py, grc/core/generator/top_block.py
fixes issues mentioned in #3618
* embedded modules are placed next to hier_block
* remove ".py" from block wrapper filename
* prefix generated modules with flowgraph id (to avoid clashes)
=> grc: save epy blocks/modules to hier_block_dir

grc/core/generator/cpp_templates/CMakeLists.txt.mako
Looks like config.version changed at some point.
Fixes following error:
```
CMake Error at CMakeLists.txt:13 (find_package):
find_package called with invalid argument "v3.10"
```
caused by
```
find_package(Gnuradio "v3.10" COMPONENTS
```
=> cppgen: Use correct required version in CMakeLists

grc/blocks/options.block.yml, grc/core/generator/flow_graph.py.mako
gr-bokehgui previously used a deprecated way to do its event loop and it was removed in bokeh 2.0, so we have changed it to be more inline with best practices, and this impacts the gnuradio interface.
I took the opportunity to move as much as possible of the code inside of gr-bokehgui itself to reduce the need for subsequent PRs (but no promises).
In the process, I added a new option to set the display size of the bokeh interface in the browser and to properly support parameters (so it supersedes [this previous PR](https://github.com/gnuradio/gnuradio/pull/3300)). Tell me if you prefer me to split this into several PRs.
To try this, use the [3.8-bokeh-2](https://github.com/gnuradio/gr-bokehgui/tree/3.8-bokeh-2)  branch. I'm waiting for this PR before merging to bokehgui's maint-3.8.
All …
=> grc 3.8: new bokehgui event loop

gr-uhd/python/uhd/bindings/usrp_block_python.cc
This is a patch to prevent the following issue, when using GNU Radio (master) to configure USRP LO sharing.
```
File "/home/user/n321_rx.py", line 125, in __init__
self.uhd_usrp_source_0.set_lo_source('external', uhd.ALL_LOS, 0)
AttributeError: module 'gnuradio.uhd' has no attribute 'ALL_LOS'
```
=> gr-uhd: ALL_LOS binding

gr-uhd/examples/c++/tag_source_demo.h, gr-uhd/examples/c++/tags_demo.cc, gr-uhd/include/gnuradio/uhd/usrp_block.h, gr-uhd/lib/amsg_source_impl.cc, gr-uhd/lib/rfnoc_graph_impl.cc, gr-uhd/lib/rfnoc_rx_streamer_impl.cc, gr-uhd/lib/usrp_block_impl.cc, gr-uhd/lib/usrp_block_impl.h, gr-uhd/lib/usrp_sink_impl.cc, gr-uhd/lib/usrp_source_impl.cc, gr-uhd/lib/usrp_source_impl.h
The following usages of Boost remain:
- boost::format
- boost::program_options for the examples
- Boost thread interruption directives to interact with GNU Radio
runtime
Note: The async message queue is currently non-functional in GRC and
I will do something about that later.
=> uhd: Remove (almost all) occurrences of Boost

gr-blocks/lib/nop_impl.cc, gr-fec/lib/depuncture_bb_impl.cc, gr-fec/lib/puncture_bb_impl.cc, gr-fec/lib/puncture_ff_impl.cc
Building gnuradio claims
In Datei, eingebunden von /usr/include/boost/bind.hpp:30,
von /home/schroer/gnuradiocomponents/gnuradio/gr-blocks/lib/nop_impl.cc:17:
/usr/include/boost/bind.hpp:36:1: Anmerkung: »#pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.«
36 | BOOST_PRAGMA_MESSAGE( ......
and some more .
This patch fixes these warnings
=> Remove unneeded boost includes and avoid boost depreciated warnings

gr-fec/python/fec/__init__.py, gr-fec/python/fec/bindings/CMakeLists.txt, gr-fec/python/fec/bindings/python_bindings.cc
If gnuradio was build without GSL test  105 -117 fail with 
from gnuradio import gr, gr_unittest, blocks, fec
File "/home/schroer/gnuradiocomponents/gnuradio-volker/gr-fec/python/fec/__init__.py", line 21, in <module>
from .fec_python import *
ImportError: /home/schroer/gnuradiocomponents/gnuradio-volker/build/gr-fec/python/fec/bindings/fec_python.cpython-39-x86_64-linux-gnu.so: undefined symbol: _Z18bind_ldpc_G_matrixRN8pybind117module_E
Some modules depend on GSL_FOUND. So they should be excluded in the python bindings, if GSL was not found.
Other way to check than running the tests:
Run in python 
from gnuradio import fec
=> If GSL not found exclude modules requiring GSL from python bindings

gr-utils/modtool/templates/gr-newmod/.gitignore
Every time I create a new OOT, have to remember to not check in the build dir and create a .gitignore
This adds a .gitignore to remove that step from the process
=> modtool: add default .gitignore

gr-filter/CMakeLists.txt
Both are dependencies for the filter design tool, but are otherwise not
build dependencies. We thus warn during CMake.
=> filter: cmake: Warn if scipy or pyqtgraph are unavailable

gr-fec/grc/CMakeLists.txt
Some fec require GSL and are not build, if GSL is missing.
In this case, the corresponding yml files should be removed from grc, too. 
=> fec: If GSL is missing, remove those yml files that require GSL

gr-audio/lib/portaudio/portaudio_sink.cc
Note this classic (which I didn't do in ALSA back in the day, 'doh):
If you don't assign your future coming from std::async to something, its
destructor is instantly called, leading to the call effectively being
blocking.
=> portaudio: fix unintentionally synchronous std::async

gr-filter/lib/fft_filter_ccc_impl.cc, gr-filter/lib/fft_filter_ccf_impl.cc, gr-filter/lib/fft_filter_fff_impl.cc, gr-filter/lib/pfb_decimator_ccf_impl.cc, gr-filter/lib/pfb_synthesizer_ccf_impl.cc
since d_history is set to 1 in gr::block, these statements are
unnecessary
=> filter: remove unnecessary set_history(1)

CMakeLists.txt, grc/CMakeLists.txt
GRC has its own check for Python modules, and Python itself. It
shouldn't be enforcing its own versions though. Therefore, we change the
CMake to use the same Mako and Python min versions for GRC and the rest
of GNU Radio.
This has the side effect of modifing GR_MAKO_MIN_VERSION, which seems
counter to what we may do within the 3.8 release cycle. However, GRC had
already snuck in the new Mako requirement a long time ago, therefore
we're now adapting CMake to the reality.
=> grc/cmake: Align Python and Mako versions (3.8)

.github/workflows/make-test.yml, gnuradio-runtime/lib/pagesize.cc
Ubuntu 18 and 20 on maint-3.9 are now warning-free. We will add -Werror
to the CI builds to keep it that way.
=> github: Add -Werror for Ubuntu workers

gr-digital/lib/symbol_sync_cc_impl.cc, gr-digital/lib/symbol_sync_ff_impl.cc
"Interpolations" was misspelled.  Also, there was a missing
space after the word "symbol".
=> gr-digital: Fix errors in logging messages

gr-blocks/lib/message_debug_impl.cc
No message received on this port should cause the block to crash, currently a non-pair message will.
Fixes #4191
This is not a backport as this is not an issue in 3.9/3.10
=> gr-blocks: Sanitize the Print PDU input of the message_debug block

gr-blocks/lib/message_debug_impl.cc
Currently non PDU messages get silently dropped. This can mask connection issues; given this is a debug block a WARNing messages seems appropriate. 
Suggestion from #4191
Not sure this should be backported to 3.9 or not; it does slightly change the conditions under which data is dropped - let me know.
=> gr-blocks: Update message debug error handling on Print PDU port

.github/workflows/make-test.yml, gr-digital/python/digital/qa_header_payload_demux.py
The HeaderToMessageBlock adapter assumed it would receive a complete
header in work(). Also, forecast() is not currently working for Python
blocks, so a local buffer was required in the adapter.
Two asserts needed list().
=> gr-digital: qa_header_payload_demux fix

gr-zeromq/lib/base_impl.cc, gr-zeromq/lib/pull_msg_source_impl.cc, gr-zeromq/lib/rep_msg_sink_impl.cc, gr-zeromq/lib/rep_sink_impl.cc, gr-zeromq/lib/req_msg_source_impl.cc, gr-zeromq/lib/sub_msg_source_impl.cc, gr-zeromq/python/zeromq/qa_zeromq_pull_msg_source.py
The recv() call on a ZMQ socket produces a warning if the return value
is not stored. We follow the advice and check the return value, just in
case.
=> zeromq: Fix warnings with recv()

gr-utils/blocktool/core/parseheader.py, gr-utils/blocktool/core/parseheader_generic.py
When binding blocks using `gr_modtool bind` if a file is missing a fairly useless error is now printed that 'file does not exist'. This actually prints the file that was attempted to be accessed.
This should also be backported to maint-3.9.
=> gr-utils: improve usefulness of blocktool exceptions

gr-digital/python/digital/bindings/constellation_receiver_cb_python.cc, gr-digital/python/digital/bindings/costas_loop_cc_python.cc, gr-digital/python/digital/bindings/fll_band_edge_cc_python.cc, gr-digital/python/digital/bindings/python_bindings.cc
costas_loop_cc, fll_band_edge_cc, and constellation_receiver_cb all
inherit from gr::blocks::control_loop. Add the class to the bindings so
the control loop methods are available in Python.
Signed-off-by: Jeppe Ledet-Pedersen <jlp@satlab.com>
=> digital: include control_loop class in child class bindings

gr-zeromq/python/zeromq/qa_zeromq_req_msg_source.py, gr-zeromq/python/zeromq/qa_zeromq_sub_msg_source.py
The chosen timeout of 100ms was too short for some cases. Increase to
max 2000ms, but check every 200ms.
=> zeromq: qa: Increase timeout for msg source tests

gr-filter/python/filter/design/filter_design.py, gr-filter/python/filter/design/fir_design.py
bessel bandpass calculation always fails as a wrong str to float
conversion is used. Using the same conversion as in lowpass calculation
fixes this problem.
StandardError is not valid in python 3. It was replaced by Exception.
=> gr_filter_sign: bessel bandpass calculation always fails

gnuradio-runtime/gnuradio-runtime.conf.in, gnuradio-runtime/lib/flat_flowgraph.cc
Currently block output buffers are limited to 32768 bytes in size, although smaller buffers can be configured using `set_max_output_buffer` functionality. This patch allows increasing the 32768 byte limitation from the configuration file. Increasing the buffer size is useful in rare cases and this patch greatly simplifies doing so. Or at least it simplifies experimenting with different buffer sizes.
https://github.com/gnuradio/gnuradio/blob/63cd1cd0570b387d5b0ccdfbbf92a093a6494fc1/gnuradio-runtime/lib/flat_flowgraph.cc#L28
This patch was originally proposed in [discuss-gnuradio](https://lists.gnu.org/archive/html/discuss-gnuradio/2016-02/msg00404.html) by @marcusmueller. I found it useful.
=> gnuradio-runtime: configurable buffer size

gr-uhd/lib/usrp_block_impl.cc, gr-uhd/lib/usrp_sink_impl.cc, gr-uhd/lib/usrp_source_impl.cc
GNU Radio now requires UHD 3.9.7. This obviates the need for certain
ifdefs to check for older features.
This fixes one bug in particular: Newer versions of UHD no longer define
INCLUDED_UHD_UTILS_MSG_TASK_HPP, which would lead UHD 4.0 + GNU Radio
using deprecated APIs within UHD.
Closes  #3956
=> uhd: Remove ifdefs for older UHD versions

gnuradio-runtime/ConfigChecks.cmake, gr-blocks/lib/ConfigChecks.cmake
PR'ing this intentionally separately from the MSVC header cleanups, where it used to be, since it addresses a separate issue.
=> CMake: remove unused compile/header checks

gnuradio-runtime/lib/block_executor.cc
Clean up includes on the way.
This rescues a reasonable change from #4152.
=> block_executor: invalid states log errors without debug build

CHANGELOG.md, dtools/bin/run-clang-tidy-on-codebase.zsh
Requires ZSH to run, comes with -h option to describe options.
I use this tool whenever I add a check to the .clang-tidy file.
=> dtools: tool to run clang-tidy on codebase, update bindtool hashes

gr-blocks/lib/packed_to_unpacked_impl.cc, gr-blocks/lib/unpacked_to_packed_impl.cc
also, get rid of impossible asserts(), throw exceptions instead of
assert(0)-aborting, as we now have facilities to handle failed
block::work().
This saves a reasonable change from #4152
=> digital: packed<->unpacked: check for chunk sizes, even outside of debug build

gr-digital/lib/simple_correlator_impl.cc, gr-digital/lib/simple_correlator_impl.h
This rescues a sensible change from #4152.
=> digital: Simple correlator debug not based on writing to file but logger

gnuradio-runtime/python/gnuradio/gr/bindings/block_python.cc, gnuradio-runtime/python/gnuradio/gr/bindings/sync_block_python.cc, gnuradio-runtime/python/gnuradio/gr/bindings/sync_decimator_python.cc, gnuradio-runtime/python/gnuradio/gr/bindings/sync_interpolator_python.cc, gnuradio-runtime/python/gnuradio/gr/bindings/tagged_stream_block_python.cc, gr-fec/python/fec/bindings/decoder_python.cc, gr-fec/python/fec/bindings/encoder_python.cc
There is no scenario that a block or app should be calling forecast over
the python interface.  This is only called by the scheduler, and for
python blocks would pass through the gateway interface.
There may be more we want to remove from the pybind interface at the block level as well
=> pybind: remove forecast from python bindings

CMakeLists.txt, cmake/Modules/FindTHRIFT.cmake, gnuradio-runtime/lib/CMakeLists.txt
- Modifies top-level CMake to set the min Thrift version
- Modifies FindThrift.cmake to use a version argument
Closes https://github.com/gnuradio/gnuradio/issues/3920
=> cmake: Thrift min version is set at top level, raise min Thrift to 0.13

gr-uhd/lib/usrp_source_impl.cc
Call set_center_freq() rather _dev->set_rx_freq() so that _tag_now is set on the change.
The end result is that the tags are generated as needed when changes are directed from the message port. set_center_freq() performs the same functionality as the original code with the addition of properly setting the _tag_now flag.
Signed-off-by: Steve Lunsford <seldad8@gmail.com>
fixes #1357 
fixes #4204.
=> gr-uhd: Generate tags when frequency changed from message port.

gr-uhd/include/gnuradio/uhd/usrp_block.h, gr-uhd/lib/usrp_block_impl.cc, gr-uhd/lib/usrp_block_impl.h, gr-uhd/lib/usrp_sink_impl.cc, gr-uhd/lib/usrp_sink_impl.h, gr-uhd/lib/usrp_source_impl.cc, gr-uhd/lib/usrp_source_impl.h, gr-uhd/python/uhd/bindings/usrp_block_python.cc
9cdfe5141a exposed a bug in gr-uhd: The filter API was incorrectly
implemented. However, the #ifdef to check for the existence of the
filter API also had a typo, and therefore, the filter API was never
compiled in.
This is an API change, b/c the existing gr-uhd code was actually never
compatible to UHD's filter API. This tells us no one's actually been
using it, so the API change is low-risk.
The change is to adapt gr-uhd's filter API to that in UHD.
=> uhd: Fix filter API

gr-qtgui/include/gnuradio/qtgui/eyecontrolpanel.h, gr-qtgui/include/gnuradio/qtgui/freqcontrolpanel.h, gr-qtgui/include/gnuradio/qtgui/timecontrolpanel.h, gr-qtgui/lib/eyecontrolpanel.cc, gr-qtgui/lib/freqcontrolpanel.cc, gr-qtgui/lib/timecontrolpanel.cc
Makes two changes:
- First, toggle the label of the 'stop' button depending on the state in
the same way the context menu does
- Second, adds a visual 'play' or 'stop' icon based on the action
Signed-off-by: Jason Uher <jason.uher@jhuapl.edu>
=> qtgui: toggle label&icon on plot play/stop button

gr-blocks/grc/blocks_file_source.block.yml
`"${file[1:-1]}"` results in the file name becoming `NotImplemented`. This seems to be the only place where such indexing is being tried. Otherwise, `${file}` is used everywhere (file sink etc). This patch makes the code across all such blocks consistent and fixes the `NotImplemented` issue for file source block (when generating C++ output).
However, the original issue, which I believe was being targeted by indexing and double quotes, is still not solved. When simply using `${file}`, the file name is passed to C++ code in single quotes, which results in an error. A solution to that is to enclose the file name in double quotes in the respective GRC block, for example.
=> gr-blocks: remove indexing in file source cpp template

gr-uhd/grc/gen_uhd_usrp_blocks.py
This commit adds functionality to the cpp template to set the start time for streaming (like in Python template). Also reorders initialization slightly to match Python template (this order seems to be more robust for time synchronization).
=> gr-uhd: add start time capability to cpp template

gr-blocks/include/gnuradio/blocks/message_debug.h, gr-blocks/lib/message_debug_impl.cc, gr-blocks/lib/message_debug_impl.h, gr-blocks/python/blocks/bindings/message_debug_python.cc
Having two print ports on this block has confused a number of people, most recently issue #4191, and combining them is straightforward and should make this block easier to use. This PR also updates some out of date documentation in the public header file.
Potentially breaks existing usage of this block so no backport.
=> gr-blocks: combine the print and print_pdu port of the message_debug block

gr-blocks/lib/control_loop.cc
Backport https://github.com/gnuradio/gnuradio/pull/4212 to maint-3.8.
Signed-off-by: David Pi <david.pinho@gmail.com>
(cherry picked from commit 369cec2383df5f4d18c0be8bd26ed7ad553ada0a)
=> gr-blocks: Fix control loop set_frequency() bounds check. (backport maint-3.8)

gr-digital/examples/example_timing.py, gr-dtv/examples/atsc_ctrlport_monitor.py, gr-utils/python/utils/plot_fft_base.py
Backport https://github.com/gnuradio/gnuradio/pull/4245 to maint-3.8.
=> numpy: Fix fftpack references (backport maint-3.8)

gr-blocks/grc/blocks_file_source.block.yml
file[1:-1] results in file name becoming NotImplemented
Signed-off-by: karel <5636152+karel@users.noreply.github.com>
(cherry picked from commit f3b05ac8e79c20908685f283835f6a2728940b62)
=> gr-blocks: remove indexing in file source cpp template (backport to maint-3.9)

gnuradio-runtime/python/gnuradio/gr/bindings/block_python.cc, gnuradio-runtime/python/gnuradio/gr/bindings/sync_block_python.cc, gnuradio-runtime/python/gnuradio/gr/bindings/sync_decimator_python.cc, gnuradio-runtime/python/gnuradio/gr/bindings/sync_interpolator_python.cc, gnuradio-runtime/python/gnuradio/gr/bindings/tagged_stream_block_python.cc, gr-fec/python/fec/bindings/decoder_python.cc, gr-fec/python/fec/bindings/encoder_python.cc
There is no scenario that a block or app should be calling forecast over
the python interface.  This is only called by the scheduler, and for
python blocks would pass through the gateway interface.
(cherry picked from commit 4e48bc34a30f6671197294c99a259f1fcbc0bf8f)
Backport https://github.com/gnuradio/gnuradio/pull/4234
=> pybind: remove forecast from python bindings (backport to maint-3.9)

gr-digital/examples/example_timing.py, gr-dtv/examples/atsc_ctrlport_monitor.py, gr-utils/plot_tools/plot_fft_base.py
(cherry picked from commit 80d96134f29bd90eaa9df62989365d095bbfc302)
Backport https://github.com/gnuradio/gnuradio/pull/4245.
=> numpy: Fix fftpack references (backport to maint-3.9)

gr-qtgui/include/gnuradio/qtgui/FrequencyDisplayPlot.h, gr-qtgui/lib/FrequencyDisplayPlot.cc
qtgui is tricker to fix than the other sections, as it juggles pointers around with less clear ownership. That plus the fact that QT does some pointer ownership magic with lots of foot-guns.
So I'm doing the low hanging fruit that aren't juggled buffers and QT objects first.
=> qtgui: Remove manual memory management from FrequencyDisplayPlot

gr-uhd/lib/usrp_block_impl.cc, gr-uhd/lib/usrp_sink_impl.cc, gr-uhd/lib/usrp_source_impl.cc
GNU Radio now requires UHD 3.9.7. This obviates the need for certain
ifdefs to check for older features.
This fixes one bug in particular: Newer versions of UHD no longer define
INCLUDED_UHD_UTILS_MSG_TASK_HPP, which would lead UHD 4.0 + GNU Radio
using deprecated APIs within UHD.
(cherry picked from commit 9cdfe5141a7aad1cf9c4c81167761cc291913fb0)
Backport https://github.com/gnuradio/gnuradio/pull/4232
=> uhd: Remove ifdefs for older UHD versions (backport to maint-3.9)

gr-zeromq/lib/base_impl.cc, gr-zeromq/lib/pull_msg_source_impl.cc, gr-zeromq/lib/rep_msg_sink_impl.cc, gr-zeromq/lib/rep_sink_impl.cc, gr-zeromq/lib/req_msg_source_impl.cc, gr-zeromq/lib/sub_msg_source_impl.cc, gr-zeromq/python/zeromq/qa_zeromq_pull_msg_source.py
The recv() call on a ZMQ socket produces a warning if the return value
is not stored. We follow the advice and check the return value, just in
case.
(cherry picked from commit ec3d116546aa9710b324b1713cea058d80c906a8)
Backport https://github.com/gnuradio/gnuradio/pull/4215
=> zeromq: Fix warnings with recv() (backport to maint-3.9)

gr-blocks/lib/file_meta_sink_impl.cc
Manual backport https://github.com/gnuradio/gnuradio/pull/3223
=> fix bug file_meta_sink (backport to maint-3.8)

gr-filter/python/filter/design/filter_design.py, gr-filter/python/filter/design/fir_design.py
bessel bandpass calculation alwas fails as a wrong str to float
conversion is used. Using the same conversion as in lowpass calculation
fixes this problem.
StandardError is not valid in python 3. It was replaced by Exception.
(cherry picked from commit b2fcf61bb600568be2be6db83e8d5e3b1d5bc2eb)
Backport https://github.com/gnuradio/gnuradio/pull/4222.
=> gr_filter_sign: bessel bandpass calculation always fails (backport to maint-3.9)

gnuradio-runtime/gnuradio-runtime.conf.in, gnuradio-runtime/lib/flat_flowgraph.cc
Backport https://github.com/gnuradio/gnuradio/pull/4244.
Low risk and could be useful.
=> gnuradio-runtime: configurable buffer size (backport to maint-3.9)

gr-uhd/python/uhd/bindings/uhd_types_python.cc
Add support for stream_mode_t, partially fixing #4177.
This may be invoked within python using something along the lines of;
```
cmd = uhd.stream_cmd_t(uhd.stream_mode_t.STREAM_MODE_NUM_SAMPS_AND_DONE)
cmd.num_samps = frame[1]
cmd.stream_now = False
cmd.time_spec = uhd.time_spec(frame[0])
csrc.issue_stream_cmd(cmd)
```
This behaviour is slightly different than what was in place with previous (swig) versions of gnuradio. When using pybind, the result we replace old instances of  "uhd.stream_cmd_t" with "uhd.stream_mode_t".
This has been tested on hardware.
Still pending a fix for "tune_request_t::policy_t".
=> GR-UHD: Support for stream_mode_t 

.github/workflows/make-test.yml, CMakeLists.txt
This fix enables back 'testing-support' component which has been
disabled by a regression introduced on a3061b8f.
Signed-off-by: Vasilis Tsiligiannis <acinonyx@openwrt.gr>
=> cmake: Fix Boost unit test framework component availability variable

gnuradio-runtime/lib/block_executor.cc
Clean up includes on the way.
(cherry picked from commit cedc95ad7d7aa983b2047650c3eebdf4eedda043)
Backport https://github.com/gnuradio/gnuradio/pull/4254
Minor merge conflict on include files.
=> block_executor: invalid states log errors without debug build (backport to maint-3.9)

.github/workflows/make-test.yml, CMakeLists.txt
This fix enables back 'testing-support' component which has been
disabled by a regression introduced on a3061b8f. It also removes a
variable override included in 'Make Test' GitHub workflow to workaround
this issue.
Signed-off-by: Vasilis Tsiligiannis <acinonyx@openwrt.gr>
(cherry picked from commit 129a17a01fa12c3b65fc14c54bb08ea5c6817217)
Backport https://github.com/gnuradio/gnuradio/pull/4287
=> cmake: Fix Boost unit test framework component availability variable (backport to maint-3.9)

grc/core/generator/cpp_templates/CMakeLists.txt.mako
This allows out-of-tree modules to be linked, as those will not link with the prefix. In-tree modules link still. Or are there some cases where the in-tree modules will not link with this approach?
=> grc: remove gnuradio prefix from linked libraries

gnuradio-runtime/python/gnuradio/gr_unittest.py, gr-digital/python/digital/qa_packet_headerparser_b.py
This is an attempt to avoid QA failures due to messages not being
delivered before wait() concludes.
=> digital: qa: Add preconditions to wait for qa_packet_headerparser_b

gr-uhd/grc/gen_uhd_usrp_blocks.py
also reorder USRP initialization to match Python template
Signed-off-by: karel <5636152+karel@users.noreply.github.com>
(cherry picked from commit 1f5dc898e902fdec5afb2d60f3083320e50e34f8)
Backport https://github.com/gnuradio/gnuradio/pull/4276
=> gr-uhd: add start time capability to cpp template (backport to maint-3.9)

grc/tests/.gitignore
When `make test` is run from the build dir, `grc/tests/resources/top_block.py` is created in tree.
=> grc: add tests/resources/top_block.py to .gitignore

gr-dtv/grc/dtv_atsc_deinterleaver.block.yml, gr-dtv/grc/dtv_atsc_depad.block.yml, gr-dtv/grc/dtv_atsc_derandomizer.block.yml, gr-dtv/grc/dtv_atsc_equalizer.block.yml, gr-dtv/grc/dtv_atsc_fs_checker.block.yml, gr-dtv/grc/dtv_atsc_rs_decoder.block.yml, gr-dtv/grc/dtv_atsc_sync.block.yml, gr-dtv/grc/dtv_atsc_viterbi_decoder.block.yml, gr-dtv/include/gnuradio/dtv/CMakeLists.txt, gr-dtv/include/gnuradio/dtv/atsc_plinfo.h, gr-dtv/lib/CMakeLists.txt, gr-dtv/lib/atsc/atsc_deinterleaver_impl.cc, gr-dtv/lib/atsc/atsc_depad_impl.cc, gr-dtv/lib/atsc/atsc_derandomizer_impl.cc, gr-dtv/lib/atsc/atsc_equalizer_impl.cc, gr-dtv/lib/atsc/atsc_field_sync_mux_impl.cc, gr-dtv/lib/atsc/atsc_fpll_impl.cc, gr-dtv/lib/atsc/atsc_fs_checker_impl.cc, gr-dtv/lib/atsc/atsc_fs_checker_impl.h, gr-dtv/lib/atsc/atsc_interleaver_impl.cc, gr-dtv/lib/atsc/atsc_plinfo.cc, gr-dtv/lib/atsc/atsc_randomize.cc, gr-dtv/lib/atsc/atsc_randomize.h, gr-dtv/lib/atsc/atsc_rs_decoder_impl.cc, gr-dtv/lib/atsc/atsc_rs_decoder_impl.h, gr-dtv/lib/atsc/atsc_sync_impl.cc, gr-dtv/lib/atsc/atsc_trellis_encoder_impl.cc, gr-dtv/lib/atsc/atsc_types.h, gr-dtv/lib/atsc/atsc_viterbi_decoder_impl.cc
ATSC implementation is old, and I don't know the entire history of it. But it seems to be the only module that uses structs to pass data between blocks.  This causes the grc blocks to be very special purpose and only have byte vectors as the interface (which many are floats).
The other reasoning behind this is also trying to keep packet data in contiguous memory so that hardware accelerators can be used more easily on larger buffer sizes
=> dtv/atsc: replace structs with streams and tags

gr-dtv/lib/atsc/atsc_viterbi_decoder_impl.cc
There was an extra factor of 12 in the output copy of viterbi decoder
when the noutput_items was > 1 (which doesn't happen all the time)
leading to a glitch in the output video.
Also, replaced the hardcoded 832 with the appropriate enum
Addresses the glitch introduced and discussed in #4243
=> dtv/atsc: fix arithmetic error / replace magic num

gnuradio-runtime/include/pmt/pmt.h, gnuradio-runtime/lib/pmt/pmt.cc, gnuradio-runtime/lib/pmt/pmt_int.h, gnuradio-runtime/lib/pmt/pmt_serialize.cc, gnuradio-runtime/lib/pmt/qa_pmt_prims.cc, gnuradio-runtime/python/pmt/qa_pmt.py, gnuradio-runtime/swig/pmt_swig.i
create a new derived class for pmt dicts so they can be distinguished without complicated try/catch logic, updated QA with a few additional checks. also added an is_pdu() method which returns true if the pmt is a pair of a dict-type PMT and a uniform-vector type, otherwise false
(cherry picked from commit 941c6c895a5724c142cfb0a32220885062373d57)
Backport https://github.com/gnuradio/gnuradio/pull/3389
=> pmt: stop treating all pairs like they are dicts (backport to maint-3.8)

grc/tests/.gitignore
(cherry picked from commit 08f188579761aa5300457ad2083405833174b223)
Backport https://github.com/gnuradio/gnuradio/pull/4309
=> grc: add top_block.py to .gitignore (backport to maint-3.9)

gr-utils/bindtool/scripts/binding-hash-hotfixer.zsh
DO NOT USE THIS TOOL IF ADDING OR REMOVING ANY FUNCTIONALITY FROM A
HEADER.
This tool allows to quickly update the hash in a binding file
(*/python/*/binding/something.cc).
WARNING: This script updates header hashes without checking whether the
underlying functionality changed. If you added or removed any python-bound
function in the header to this binding file THIS IS NOT THE TOOL YOU SHOULD BE
USING. Use bindtool instead to generate correct binding code.
(cherry picked from commit a9a6ae3dcefd1577276f05ee078236b2cbeadb60)
Backport https://github.com/gnuradio/gnuradio/pull/4118
=> Pybind: Adding header hash hotfixer (backport to maint-3.9)

grc/gui/PropsDialog.py, grc/gui/canvas/block.py
This reverts commit 1fbf9ba89c643f478024d6af797e0a0dbbdf5ba3.
It resolves https://github.com/gnuradio/gnuradio/issues/4251 but also reverts behavior back to the uglier 3.8 behavior where the canvas is littered with block IDs when that option is checked.
=> Revert " grc: restore pre-3.8 block id behavior"

gr-filter/grc/variable_band_pass_filter_taps.block.yml, gr-filter/grc/variable_band_reject_filter_taps.block.yml, gr-filter/grc/variable_high_pass_filter_taps.block.yml, gr-filter/grc/variable_low_pass_filter_taps.block.yml, gr-filter/grc/variable_rrc_filter_taps.block.yml
This partly fix an issue reported in [discuss gnuradio](https://lists.gnu.org/archive/html/discuss-gnuradio/2021-03/msg00008.html) and in #4317
It appears that the following variable taps blocks do not had callbacks : 
- /gnuradio/gr-filter/grc/variable_band_pass_filter_taps.block.yml
- /gnuradio/gr-filter/grc/variable_band_reject_filter_taps.block.yml
- /gnuradio/gr-filter/grc/variable_high_pass_filter_taps.block.yml
- /gnuradio/gr-filter/grc/variable_low_pass_filter_taps.block.yml
- /gnuradio/gr-filter/grc/variable_rrc_filter_taps.block.yml 
The fix has been tested under GR 3.8.2 and 3.9 using flowgraph 
[filter_taps_test.grc.txt](https://github.com/gnuradio/gnuradio/files/6100586/filter_taps_test.grc.txt). 
However, …
=> gr_filter : fix variable filter taps blocks

gr-digital/lib/timing_error_detector.cc, gr-digital/lib/timing_error_detector.h
This fixes #3678 (MSK timing error detector) for the "MSK Gen TED". The fix can be cherry-picked onto maint-3.8 and maint-3.9 as it is not an API change.
It does not change the "GMSK TED", which should be deprecated as it is redundant and does not work for its intended application, confusing users.
=> Fix for #3678

grc/gui/PropsDialog.py, grc/gui/canvas/block.py
This reverts commit 1fbf9ba89c643f478024d6af797e0a0dbbdf5ba3.
(cherry picked from commit 8ba9c53d8ec95c9453cb92ab81a19bde9b03c719)
Backport https://github.com/gnuradio/gnuradio/pull/4327
=> Revert " grc: restore pre-3.8 block id behavior" (backport to maint-3.9)

grc/core/generator/top_block.py, grc/core/params/param.py
(cherry picked from commit 9a25928a621081fae49b81ed4b2eb221cded9d1b)
grc: validate gui hints
(cherry picked from commit a53bb7a76047414eeae611f9d1fdcca4c6e2fa53)
grc: validate gui hints
(cherry picked from commit f45c82436c2a19fa1e5ff15177fbc4cc591017cb)
grc: fix widget whitout GUI_hint may  superpose to other
(cherry picked from commit 21b4eb156fa9a5dd85668c0ca019a1cf7882e6e0)
Backport https://github.com/gnuradio/gnuradio/pull/4271
=> grc: order blocks with GUI Hint first (backport to maint-3.9)

grc/core/generator/top_block.py, grc/core/params/param.py
(cherry picked from commit 9a25928a621081fae49b81ed4b2eb221cded9d1b)
grc: validate gui hints
(cherry picked from commit a53bb7a76047414eeae611f9d1fdcca4c6e2fa53)
grc: validate gui hints
(cherry picked from commit f45c82436c2a19fa1e5ff15177fbc4cc591017cb)
grc: fix widget whitout GUI_hint may  superpose to other
(cherry picked from commit 21b4eb156fa9a5dd85668c0ca019a1cf7882e6e0)
Backport https://github.com/gnuradio/gnuradio/pull/4271
=> grc: order blocks with GUI Hint first (backport to maint-3.8)

gr-uhd/grc/gen_uhd_usrp_blocks.py
(cherry picked from commit c4b33434853e5f5648d08e80d6f65d628f1f17b0)
Backport https://github.com/gnuradio/gnuradio/pull/4090
=> uhd: Add start time capability to GRC bindings (backport to maint-3.9)

gr-uhd/docs/uhd.dox, gr-uhd/include/gnuradio/uhd/usrp_block.h, gr-uhd/lib/usrp_block_impl.cc, gr-uhd/lib/usrp_block_impl.h
This allows toggling GPIOs via messages.
(cherry picked from commit 9aac44a5d4af07254b446c5e77237e8707325cb6)
Backport https://github.com/gnuradio/gnuradio/pull/4088
API addition.
=> uhd: Add GPIO handlers for messages (backport to maint-3.9)

gr-digital/include/gnuradio/digital/corr_est_cc.h, gr-digital/python/digital/bindings/corr_est_cc_python.cc
Signed-off-by: Ipsit <mmkipsit@gmail.com>
(cherry picked from commit 51fcd60d3f170ee992b960c4623797c945fadc0d)
Backport https://github.com/gnuradio/gnuradio/pull/4274
=> digital: Fix documentation for corr_est 'threshold' paramter (backport to maint-3.9)

gr-uhd/docs/uhd.dox, gr-uhd/include/gnuradio/uhd/usrp_block.h, gr-uhd/lib/usrp_block_impl.cc, gr-uhd/lib/usrp_block_impl.h
This command implements uhd::tune_request_t completely (and not just a
subset). Also includes updates to the manual.
(cherry picked from commit efc9ca261a68bd67f8cac1ef976fdabdf6d16ad4)
Backport https://github.com/gnuradio/gnuradio/pull/4091
API Addition
=> gr-uhd: Add command uhd handler for mtune ("manual tune") (backport to maint-3.9)

CMakeLists.txt
This is in master, but part of multiple commits, so just copying.
Backport https://github.com/gnuradio/gnuradio/pull/4089 and others.
=> cmake: add BUILD_DATE to CMakeLists.txt (backport to maint-3.9)

gnuradio-runtime/ConfigChecks.cmake, gr-blocks/lib/ConfigChecks.cmake
(cherry picked from commit 6c93722c546a25bd1e310497a38af410f973c3f1)
Backport https://github.com/gnuradio/gnuradio/pull/4256
=> CMake: remove unused compile/header checks (backport to maint-3.9)

gnuradio-runtime/python/gnuradio/gru/mathmisc.py, gr-audio/examples/python/test_resampler.py
(cherry picked from commit a613e6def09729c47cdfc9d2037a7c40b4ffb0c8)
Backport https://github.com/gnuradio/gnuradio/pull/3810
=> audio: fix lcm calculation (backport to maint-3.8)

gnuradio-runtime/lib/sys_paths.cc, gnuradio-runtime/python/gnuradio/gr/qa_prefs.py, grc/gui/Config.py
When looking for the config file, allow the env variable
GR_PREFS_PATH to be searched so that multiple installations
of GR each with its own prefs can be used, similar to what
is currently done in GRC
(cherry picked from commit 72b8a8068bff145c5f16a1d56ec852f87569145e)
Backport https://github.com/gnuradio/gnuradio/pull/2835
=> runtime: add GR_PREFS_PATH env variable search (backport to maint-3.8)

gr-uhd/grc/gen_uhd_usrp_blocks.py
The DC offset and IQ balance functions were incorrectly implemented in
the GRC blocks: It was possible to force-enable, but not force-disable
them. Also, the underlying Python/C++ API allowed changing the actual
correction value, but the GRC did not.
Now, there are four options for IQ and DC:
- Default: Whatever UHD does by default
- Auto: Enable auto-correction
- Disabled: No correction
- Manual: Allows setting the correction value separately
=> uhd: Fix generation of FE correction functions

gr-uhd/include/gnuradio/uhd/usrp_block.h, gr-uhd/lib/usrp_block_impl.cc, gr-uhd/lib/usrp_block_impl.h, gr-uhd/lib/usrp_sink_impl.cc, gr-uhd/lib/usrp_sink_impl.h, gr-uhd/lib/usrp_source_impl.cc, gr-uhd/lib/usrp_source_impl.h, gr-uhd/python/uhd/bindings/usrp_block_python.cc
It implements the ability to control frequency and gain in both
directions (Tx and Rx) with use of a single UHD source or sink - in the
same moment. It is possible to do that in separate moments with current
UHD blocks but this way it is not possible to change both Rx and Tx
settings for the same burst. Now, a single message can do that.
Note that there is a bit of an oddity here: The GNU Radio USRP blocks
are either Rx or Tx (source or sink). However, they all encapsulate an
underlying multi_usrp object. That means that under the hood, a USRP
source or a USRP sink potentially has access to the "other" direction.
This is made use in this patch.
To use this feature, add a direction key to the message dictionary going
to the block.
(cherry …
=> uhd: Control of frequency and gain in both directions at the same moment (backport to maint-3.9)

gr-uhd/grc/gen_uhd_usrp_blocks.py
The DC offset and IQ balance functions were incorrectly implemented in
the GRC blocks: It was possible to force-enable, but not force-disable
them. Also, the underlying Python/C++ API allowed changing the actual
correction value, but the GRC did not.
Now, there are four options for IQ and DC:
- Default: Whatever UHD does by default
- Auto: Enable auto-correction
- Disabled: No correction
- Manual: Allows setting the correction value separately
(cherry picked from commit ffc11b931ce769d6cdeacca69e829142d5c462f9)
Backport https://github.com/gnuradio/gnuradio/pull/4333
=> uhd: Fix generation of FE correction functions (backport to maint-3.9)

CMakeLists.txt, gr-utils/modtool/templates/gr-newmod/CMakeLists.txt
GNU Radio builds done with conda do path subsitution to replace the build prefix with the installed prefix, but it struggles when multiple path separator styles are used in the same file. This makes it so that all of the paths that would be subsitituted use the same style (forward slash separators) so that build prefix replacement happens correctly.
Using this in conda-forge now after https://github.com/conda-forge/gnuradio-feedstock/pull/45. The fix allowed us to get OOTs (in this case, gr-satellites) compiling against GR 3.9 where it was unknowingly broken before.
=> cmake: Format numpy include path in CMake style for consistency.

CMakeLists.txt, gr-utils/modtool/templates/gr-newmod/CMakeLists.txt
GNU Radio builds done with conda do path subsitution to replace the
build prefix with the installed prefix, but it struggles when multiple
path separator styles are used in the same file. This makes it so that
all of the paths that would be subsitituted use the same style (forward
slash separators) so that build prefix replacement happens correctly.
(cherry picked from commit 8793effe5d6013c95b44f52551ba0d660157b263)
Backport https://github.com/gnuradio/gnuradio/pull/4336
=> cmake: Format numpy include path in CMake style for consistency (backport to maint-3.9)

gr-zeromq/lib/pull_msg_source_impl.cc, gr-zeromq/lib/req_msg_source_impl.cc, gr-zeromq/lib/sub_msg_source_impl.cc
Handle the PMT exceptions when deserializing the received ZMQ messages,
log an error message and continue the execution.
Previously the unhandled exceptions were aborting the process:
terminate called after throwing an instance of 'pmt::exception'
what():  pmt::deserialize: malformed input stream, tag value = : 50
Aborted (core dumped)
Original Author: Vasil Velichkov
(cherry picked from commit ff9b489dee9293e1837910990bd2f2b60f5e7fde)
Backport https://github.com/gnuradio/gnuradio/pull/3230
QA code (a565c806ef3a5e8e057a7eb4257721f4b88ab62f) omitted because `int.from_bytes()` is not Python2-friendly.
Avoiding a crash on an invalid PMT over ZMQ is worth foregoing the QA code.
=> zmq: Handle the PMT exceptions (backport to maint-3.8)

gr-digital/lib/correlate_access_code_bb_ts_impl.cc, gr-digital/lib/correlate_access_code_bb_ts_impl.h, gr-digital/lib/correlate_access_code_ff_ts_impl.cc, gr-digital/lib/correlate_access_code_ff_ts_impl.h, gr-digital/lib/correlate_access_code_tag_bb_impl.cc, gr-digital/lib/correlate_access_code_tag_bb_impl.h, gr-digital/lib/correlate_access_code_tag_ff_impl.cc, gr-digital/lib/correlate_access_code_tag_ff_impl.h, gr-digital/python/digital/qa_correlate_access_code_XX_ts.py, gr-digital/python/digital/qa_correlate_access_code_tag.py
Leftover data from last time CAC triggered, or just leading zeroes
being ignored.
This commit prevents these by assuring that we've processed at least
as many bits as the code is, before allowing a trigger.
Original Author: Thomas Habets
(cherry picked from commit cc4cd94e326d6348228bd7d6763d99b8777124e6)
Backport https://github.com/gnuradio/gnuradio/pull/3692
=> digital/correlate_access_code: Prevent false triggers (backport to maint-3.8)

gr-uhd/include/gnuradio/uhd/usrp_block.h, gr-uhd/lib/usrp_block_impl.cc, gr-uhd/lib/usrp_block_impl.h, gr-uhd/lib/usrp_sink_impl.cc, gr-uhd/lib/usrp_sink_impl.h, gr-uhd/lib/usrp_source_impl.cc, gr-uhd/lib/usrp_source_impl.h, gr-uhd/python/uhd/bindings/usrp_block_python.cc
9cdfe5141a exposed a bug in gr-uhd: The filter API was incorrectly
implemented for UHD (multi_usrp had an API change in UHD 4.0).
This is an API change, b/c the existing gr-uhd code was actually never
compatible to UHD 4.0's filter API.
The change is to adapt gr-uhd's filter API to that in UHD.
(cherry picked from commit 8e6f348288e3ba9f2f25e46d3614b376110963df)
Backport to https://github.com/gnuradio/gnuradio/pull/4258
=> uhd: Fix filter API (backport to maint-3.9)

dtools/bin/run-clang-tidy-on-codebase.zsh
Requires ZSH to run, comes with -h option to describe options.
I use this tool whenever I add a check to the .clang-tidy file.
(cherry picked from commit b4eb9a263d0b250bed93a1e2afdf2bb07a67f33a)
CHANGELOG.md dropped from backport
Backport https://github.com/gnuradio/gnuradio/pull/4252
=> dtools: tool to run clang-tidy on codebase, update bindtool hashes (backport to maint-3.9)

gr-qtgui/include/gnuradio/qtgui/eyecontrolpanel.h, gr-qtgui/include/gnuradio/qtgui/freqcontrolpanel.h, gr-qtgui/include/gnuradio/qtgui/timecontrolpanel.h, gr-qtgui/lib/eyecontrolpanel.cc, gr-qtgui/lib/freqcontrolpanel.cc, gr-qtgui/lib/timecontrolpanel.cc
Makes two changes:
- First, toggle the label of the 'stop' button depending on the state in
the same way the context menu does
- Second, adds a visual 'play' or 'stop' icon based on the action
Signed-off-by: Jason Uher <jason.uher@jhuapl.edu>
(cherry picked from commit 7d9c4159ff4481dfcbcdb07ca94426a94b0dafba)
re-clang
Signed-off-by: Jason Uher <jason.uher@jhuapl.edu>
(cherry picked from commit cbc9344475873034096acd308d91cda994dfbfa9)
Backport https://github.com/gnuradio/gnuradio/pull/4260
=> qtgui: toggle label&icon on plot play/stop button (backport to maint-3.9)

gr-digital/lib/simple_correlator_impl.cc, gr-digital/lib/simple_correlator_impl.h
(cherry picked from commit 15c86a13d974e673903ea0c6bac02157aeb9f50a)
Backport https://github.com/gnuradio/gnuradio/pull/4253
Minor, but we don't need blocks writing debug to files.
=> digital: Simple correlator debug not based on writing to file but logger (backport to maint-3.9)

grc/core/generator/cpp_templates/CMakeLists.txt.mako
this allows OOT modules to be linked, as those will not link with the prefix
Signed-off-by: karel <5636152+karel@users.noreply.github.com>
(cherry picked from commit 78dc0d8b5b289b108deebce3567b69902d65d202)
Backport https://github.com/gnuradio/gnuradio/pull/4263
=> grc: remove gnuradio prefix from linked libraries (backport to maint-3.9)

gr-utils/modtool/templates/gr-newmod/cmake/Modules/howtoConfig.cmake
…newmod
(cherry picked from commit 4605af69fa8b1a366d49c6c4aea2f4a80bb611f5)
Backport https://github.com/gnuradio/gnuradio/pull/4125/commits
=> modtool: Fix find_package_handle_standard_args warning in gr_modtool … (backport to maint-3.9)

gr-digital/examples/CMakeLists.txt
(cherry picked from commit 356ecd5e3ae840a655812523c540241cd852e3bb)
Backport https://github.com/gnuradio/gnuradio/pull/4371
=> gr-digital: Install mpsk_stage6.grc example (backport to maint-3.9)

gr-filter/python/filter/design/filter_design.py, gr-filter/python/filter/design/fir_design.py
bessel bandpass calculation alwas fails as a wrong str to float
conversion is used. Using the same conversion as in lowpass calculation
fixes this problem.
StandardError is not valid in python 3. It was replaced by Exception.
(cherry picked from commit b2fcf61bb600568be2be6db83e8d5e3b1d5bc2eb)
Backport https://github.com/gnuradio/gnuradio/pull/4222
=> gr_filter_sign: bessel bandpass calculation always fails (backport to maint-3.8)

gr-utils/python/modtool/cli/newmod.py, gr-utils/python/modtool/core/newmod.py
When a prefix gets installed, the [modtool] section in prefs hardcodes
the path to the templates in the newly installed prefix as a global path
for all modtools.  This creates major problems when bouncing between
prefixes, especially when newmod changes between releases
Why not just use the prefix as the root of where to look for the
templates
(cherry picked from commit 82262753a56d15cfa6343044c726cf0035c38d9c)
Backport https://github.com/gnuradio/gnuradio/pull/3266
Old one we missed.
=> modtool: use prefix path for modtool instead of prefs (backport to maint-3.8)

gr-dtv/examples/uhd_atsc_rx.grc, gr-dtv/grc/dtv_atsc_deinterleaver.block.yml, gr-dtv/grc/dtv_atsc_derandomizer.block.yml, gr-dtv/grc/dtv_atsc_equalizer.block.yml, gr-dtv/grc/dtv_atsc_fs_checker.block.yml, gr-dtv/grc/dtv_atsc_rs_decoder.block.yml, gr-dtv/grc/dtv_atsc_viterbi_decoder.block.yml, gr-dtv/include/gnuradio/dtv/atsc_plinfo.h, gr-dtv/lib/atsc/atsc_deinterleaver_impl.cc, gr-dtv/lib/atsc/atsc_derandomizer_impl.cc, gr-dtv/lib/atsc/atsc_equalizer_impl.cc, gr-dtv/lib/atsc/atsc_equalizer_impl.h, gr-dtv/lib/atsc/atsc_fs_checker_impl.cc, gr-dtv/lib/atsc/atsc_plinfo.cc, gr-dtv/lib/atsc/atsc_rs_decoder_impl.cc, gr-dtv/lib/atsc/atsc_viterbi_decoder_impl.cc, gr-dtv/python/dtv/atsc_rx.py
Rather than adding/searching for tags, just put plinfo on its own
streaming port.  This should be more efficient than putting tags on
every item and easier to inspect/debug.
So now, the receive chain looks like this:
=> dtv/atsc: create separate plinfo stream ports

gr-uhd/apps/uhd_fft, gr-uhd/apps/uhd_siggen_gui
uhd_fft and uhd_siggen_gui are standalone apps that, a long time ago,
were spun off from GRC apps. In the last years, there were some fixes to
Qt apps that haven't yet made it into these two UHD apps:
- 0cc238fb: Better terminate handling
- 40f5e6cd: XInitThreads() as early as possible. This was accidentally
moved downwards as part of refactoring in 77871a9b.
=> uhd: Fix Qt apps (XInitThreads call order, terminate handling)

gr-qtgui/lib/time_sink_c_impl.cc, gr-qtgui/lib/waterfall_sink_c_impl.cc, gr-qtgui/lib/waterfall_sink_c_impl.h, gr-qtgui/lib/waterfall_sink_f_impl.cc, gr-qtgui/lib/waterfall_sink_f_impl.h
Problem introduced in 4b7006db76b570e4d916e263301333d2f4d2a2df.
It appears to be the only instance of this mistake in that commit.
Fixes: #4396 
Signed-off-by: Thomas Habets <habets@google.com>
=> qtgui: Fix segfaulting overflow

gr-utils/modtool/cli/add.py
See discussion in #4384 
gr_modtool add : no argument-list specified : ask user 
gr_modtool add --argument-list 'Some string' : use this string as arglist
special case : empty string -> empty arglist
Fixes #4324
=> gr_modtool add: Correctly handle arglist

gr-fft/include/gnuradio/fft/window.h, gr-fft/lib/window.cc, gr-fft/python/fft/bindings/docstrings/window_pydoc_template.h, gr-fft/python/fft/bindings/window_python.cc, gr-filter/include/gnuradio/filter/firdes.h, gr-filter/include/gnuradio/filter/hilbert_fc.h, gr-filter/lib/firdes.cc, gr-filter/lib/hilbert_fc_impl.cc, gr-filter/lib/hilbert_fc_impl.h, gr-filter/python/filter/bindings/firdes_python.cc, gr-filter/python/filter/bindings/hilbert_fc_python.cc
This is a backport of most of #4139 however the API has been modified to be compatible with 3.9. This essentially means all public methods continue to use the term `beta` (which is syntactically specific to the existing kaiser window) instead of the more generic `param` that is in 3.10. Internally, the code makes use of 'param'. Despite that, this is feature-complete and allows the use of these new windows.
=> gr-fft: Expand window enum - backport 3.9

gr-uhd/apps/uhd_fft
The phase-relations plot didn't specify a handle for the Qt parent,
which used to be OK (it would default to None) but no longer is.
=> uhd: Fix phase relations plot (Qt issue)

gr-uhd/apps/uhd_fft
The phase-relations plot didn't specify a handle for the Qt parent,
which used to be OK (it would default to None) but no longer is.
(cherry picked from commit f6fe5280edf78e668f918f6b38f7d59eef7c0a9a)
Backport https://github.com/gnuradio/gnuradio/pull/4400
=> uhd: Fix phase relations plot (Qt issue) (backport to maint-3.9)

gr-uhd/apps/uhd_fft, gr-uhd/apps/uhd_siggen_gui
uhd_fft and uhd_siggen_gui are standalone apps that, a long time ago,
were spun off from GRC apps. In the last years, there were some fixes to
Qt apps that haven't yet made it into these two UHD apps:
- 0cc238fb: Better terminate handling
- 40f5e6cd: XInitThreads() as early as possible. This was accidentally
moved downwards as part of refactoring in 77871a9b.
(cherry picked from commit cb9fe59e3abe58e97f1408f1d57885aef22814fe)
Signed-off-by: Jeff Long <willcode4@gmail.com>https://github.com/gnuradio/gnuradio/pull/4389
Backport https://github.com/gnuradio/gnuradio/pull/4389
=> uhd: Fix Qt apps (XInitThreads call order, terminate handling) (backport to maint-3.9)

gr-blocks/lib/correctiq_auto_impl.cc
(cherry picked from commit a1a3d860ecb8ffef9f2baccc2721d2d39071ba1c)
Backport https://github.com/gnuradio/gnuradio/pull/4386
=> gr-blocks: Fix Remove DC Spike AutoSync block (backport to maint-3.9)

gnuradio-runtime/include/gnuradio/thrift_application_base.h, gnuradio-runtime/python/gnuradio/gr/bindings/thrift_application_base_python.cc, gr-blocks/lib/message_strobe_impl.cc, gr-blocks/lib/message_strobe_random_impl.cc, gr-network/lib/socket_pdu_impl.cc, gr-network/lib/stream_pdu_base.cc, gr-network/lib/tcp_sink_impl.cc, gr-zeromq/lib/pull_msg_source_impl.cc, gr-zeromq/lib/rep_msg_sink_impl.cc, gr-zeromq/lib/req_msg_source_impl.cc, gr-zeromq/lib/sub_msg_source_impl.cc
That being everywhere where boost::asio isn't involved.
The boost::asio error placeholders for some reason don't play nicely with lambdas, I can't really figure out what's going wrong there, so let's leave it at this for now. This leaves boost::bind in place where boost::asio is used.
=> Remove boost::bind where trivial

CHANGELOG.md
Added note to CHANGELOG.md in maint-3.9
=> uhd: deprecate control via pairs/tuples, require dicts in v3.10

gr-blocks/lib/packed_to_unpacked_impl.cc, gr-blocks/lib/packed_to_unpacked_impl.h, gr-blocks/lib/unpacked_to_packed_impl.cc, gr-blocks/lib/unpacked_to_packed_impl.h
Also, get rid of impossible asserts(), and throw exceptions instead of
assert(0)-aborting, as we now have facilities to handle failed
block::work().
(cherry picked from commit c5a1be2e93186df3c20ed2c0512dfd2e1ce7799e)
Backport https://github.com/gnuradio/gnuradio/pull/4255
=> digital: packed<->unpacked: check chunk sizes, incl. NDBEBUG builds (backport to maint-3.9)

gr-filter/python/filter/design/filter_design.py
For  FIR filters:
loading a saved csv file fails with
File "/usr/local/gnuradio/lib64/python3.9/site-packages/gnuradio/filter/filter_design.py", line 2052, in action_open_dialog
self.gui.filterDesignTypeComboBox.setCurrentIndex(int(params["wintype"]))
ValueError: invalid literal for int() with base 10: 'win_type.WIN_HAMMING'
File "/usr/local/gnuradio/lib64/python3.9/site-packages/gnuradio/filter/filter_design.py", line 2052, in action_open_dialog
self.gui.filterDesignTypeComboBox.setCurrentIndex(int(params["wintype"]))
ValueError: invalid literal for int() with base 10: 'win_type.WIN_HANN'
depending on the used window.
Saving and loading IIR filters work.
This pr fixes this issue.
Signed-off-by: Volker Schroer …
=> gr_filter_design fails to load previously saved csv files

gr-blocks/include/gnuradio/blocks/message_debug.h, gr-blocks/lib/message_debug_impl.cc, gr-blocks/lib/message_debug_impl.h, gr-blocks/python/blocks/bindings/message_debug_python.cc
Only needs a mutex. This was found while trying to figure out the headerparser mystery #4348.
On the way, use the native `size_t` for messgae index handling.
Backport: 3.7-3.9, only the mutexing in 4464766fa .
=> Make message_debug::store/num_messages thread-safe

gr-blocks/lib/message_debug_impl.cc
Manual backport of mutex portion only
Original author: Marcus Müller mmueller@gnuradio.org
Backport part of https://github.com/gnuradio/gnuradio/pull/4418
=> blocks: message_debug: mutex getting the stored message count (backport to maint-3.8)

gr-blocks/lib/message_debug_impl.cc
(cherry picked from commit 3e4e7feffb29f54364b370594ee953d1c2d53327)
Backported mutex-related hunk only.
Backport part of https://github.com/gnuradio/gnuradio/pull/4418
=> blocks: message_debug: mutex getting the stored message count (backport to maint-3.9)

gr-filter/python/filter/design/filter_design.py
revert Calculate checkbox index from wintype string
This reverts commit 96d590b12ebe22f088eec205806d738af51122b3.
=> filter: revert Calculate checkbox index

gnuradio-runtime/python/gnuradio/gr/bindings/rpcserver_aggregator_python.cc, gnuradio-runtime/python/gnuradio/gr/bindings/thrift_application_base_python.cc
70db8842c1c7d39787792c7caae83ed5b238fa6a introduced changes into thrift binding headers, and since I didn't rerun CMake from scratch, that went unnoticed.
Sadly, the CI doesn't seem to try and build thrift bindings, so this wasn't caught. Sorry :(
=> runtime: update thrift binding header hashes

gr-filter/python/filter/design/filter_design.py
@mormj  The conversion to has to be done. Otherwise we can't load the saved file. See discussion in #4439
=> gr_filter_design: save wintype as int instead of str

gr-filter/python/filter/design/filter_design.py
Original author: Volker Schroer
Manually backported - just adding an int()
Backport https://github.com/gnuradio/gnuradio/pull/4444
=> gr_filter_design: save wintype as int instead of str (backport to maint-3.9)

grc/core/Config.py
(cherry picked from commit f070efd62d08649d7628e3905a67c60c38bdca3a)
Backport https://github.com/gnuradio/gnuradio/pull/4451
=> GRC Fix Date String in About dialog (backport to maint-3.9)

gnuradio-runtime/lib/vmcircbuf.h, gnuradio-runtime/lib/vmcircbuf_createfilemapping.cc, gnuradio-runtime/lib/vmcircbuf_createfilemapping.h, gnuradio-runtime/lib/vmcircbuf_mmap_shm_open.cc, gnuradio-runtime/lib/vmcircbuf_mmap_shm_open.h, gnuradio-runtime/lib/vmcircbuf_mmap_tmpfile.cc, gnuradio-runtime/lib/vmcircbuf_mmap_tmpfile.h, gnuradio-runtime/lib/vmcircbuf_sysv_shm.cc, gnuradio-runtime/lib/vmcircbuf_sysv_shm.h
Addresses the issue where large buffer size requests get converted back
and forth to signed/unsigned and can cause an overflow and the buffer
allocation to fail
Addresses #1541
=> runtime: buffer factories use size_t

gr-audio/lib/windows/windows_sink.cc
CreateEvent() should be checked for failure.  An access violation
could occur if it is not.
=> gr-audio: Check CreateEvent() for failure

CHANGELOG.md, gr-analog/include/gnuradio/analog/fastnoise_source.h, gr-analog/lib/fastnoise_source_impl.cc, gr-analog/lib/fastnoise_source_impl.h, gr-analog/python/analog/bindings/fastnoise_source_python.cc
During an ambulatory encounter with a simulation flowgraph, I benchmarked and found `fastnoise_source` to be surprisingly stuck (ca 15% of time of a 20s execution, which included pool generation!) in the `div` instruction, plus surroundings that also contributed significantly to runtime.
When the pool is power-of-2-sized, index generation can be done using a
simple bitmask. So I did that.
On my private machine, the stats are:
Prior this patch: Standardnormal random variables
* `fastnoise_source`, pool size 2²⁰: 93.5 MS/s
* `noise_source`: 9.7 MS/s (just for comparison)
After the patch:
* `fastnoise_source`, pool size 2²⁰: 251 MS/s
* `fastnoise_source`, pool size 2²⁰-1: 91 MS/s
Since there's usually no reason to use anything but power-of-two sizes for the pool of random numbers that …
=> Fastnoise_source: when picking indices from random pool, avoid modulo operation when possible

gr-filter/python/filter/design/filter_design.py
Bessel Lp / Hp filters have only one critcal parameter. If you modify the critical point 2 in a Bessel Lp filter,you get the same filter coefficients.
So remove the critical point 2 entry in the gui in case of calclating a bessel Lp / Hp filter 
=> Bessel lp/hp filter have only one critical parameter

gnuradio-runtime/include/gnuradio/basic_block.h, gnuradio-runtime/lib/basic_block.cc, gnuradio-runtime/python/gnuradio/gr/bindings/basic_block_python.cc
5197311dd22744b784ff9ae2cd965a26ef04f4a4 removed the blocking wait, which utilized this. Time for this to go.
=> runtime: remove ready message receiver queue remnant from basic_block

gr-uhd/include/gnuradio/uhd/usrp_block.h, gr-uhd/lib/usrp_block_impl.cc, gr-uhd/lib/usrp_block_impl.h, gr-uhd/lib/usrp_sink_impl.cc, gr-uhd/lib/usrp_sink_impl.h, gr-uhd/lib/usrp_source_impl.cc, gr-uhd/lib/usrp_source_impl.h, gr-uhd/python/uhd/bindings/docstrings/usrp_block_pydoc_template.h, gr-uhd/python/uhd/bindings/usrp_block_python.cc
Command tuning has seen several updates recently and incomplete regression testing. One issue introduced is that when tuning without a direction key will result in the tune applied in the TX direction instead of the block direction (intended). This fixes that by adding member getters for block direction as well as a number of minor updates to how this logic is handled internally.
Here is a flowgraph to test tuning: [usrp_cmd_tuning.grc.txt](https://github.com/gnuradio/gnuradio/files/6224941/usrp_cmd_tuning.grc.txt)
=> gr-uhd: fix command tuning

gnuradio-runtime/include/gnuradio/basic_block.h, gnuradio-runtime/lib/basic_block.cc, gnuradio-runtime/python/gnuradio/gr/bindings/basic_block_python.cc
runtime: remove ready message receiver queue remnant from basic_block
runtime: don't do two lookups to verify existence and get msg handler
Backport https://github.com/gnuradio/gnuradio/pull/4426
=> runtime: remove ready message receiver queue remnant from basic_block (backport to maint-3.9)

gnuradio-runtime/python/gnuradio/gr/tag_utils.py
(cherry picked from commit da3d208956f165c54ed86351ecede88fdd6a4c05)
Backport https://github.com/gnuradio/gnuradio/pull/4459
=> pmt: remove tag_to_pmt method (unused) (backport to maint-3.8)

gnuradio-runtime/python/gnuradio/gr/tag_utils.py
(cherry picked from commit da3d208956f165c54ed86351ecede88fdd6a4c05)
Backport https://github.com/gnuradio/gnuradio/pull/4459
=> pmt: remove tag_to_pmt method (unused) (backport to maint-3.9)

gr-audio/lib/windows/windows_sink.cc
CreateEvent() should be checked for failure.  An access violation
could occur if it is not.
(cherry picked from commit eb444b21b1022a2c7de346af24f8c457a184a7de)
Backport https://github.com/gnuradio/gnuradio/pull/4457
=> gr-audio: Check CreateEvent() for failure (backport to maint-3.8)

gr-audio/lib/windows/windows_sink.cc
CreateEvent() should be checked for failure.  An access violation
could occur if it is not.
(cherry picked from commit eb444b21b1022a2c7de346af24f8c457a184a7de)
Backport https://github.com/gnuradio/gnuradio/pull/4457
=> gr-audio: Check CreateEvent() for failure (backport to maint-3.9)

CMakeLists.txt, gr-network/lib/CMakeLists.txt
cmake: Repair gnuradio-config-info for --enabled-components.
gr-network: Clean up lib/CMakeLists.txt.
Backport https://github.com/gnuradio/gnuradio/pull/4453
=> Repair gnuradio-config-info for enabled components (backport to maint-3.9)

grc/gui/Utils.py, grc/gui/canvas/flowgraph.py
This fixes #4178 
Tested on GR 3.8.2 
If ever a block have been saved with negative coordinate, coordinates are sanitized when opening the flowgraph
This can be backported to maint-3.8 and maint 3.9 
As compared to Derek proposal, the coordinate sanitizing is made inside `scale(coor, reverse=False):` method which is only called in https://github.com/gnuradio/gnuradio/blob/master/grc/gui/canvas/block.py#L61
=> gui : fix block can move outside top and left boundary

CHANGELOG.md, gnuradio-runtime/include/gnuradio/random.h, gnuradio-runtime/lib/math/random.cc, gnuradio-runtime/python/gnuradio/gr/bindings/docstrings/random_pydoc_template.h, gnuradio-runtime/python/gnuradio/gr/bindings/random_python.cc, gnuradio-runtime/python/gnuradio/gr/qa_random.py
Seeding being inconsistent between gr::random and things like fastnoise
source is an outstanding issue (#1559).
Fix that by fixing the API, and pivoting to our built-in XOROSHIRO128+,
which is also substantially faster than MT19937.
For that purpose, introduce, and python-bind, a wrapper class that can
be used with STL distribution shapers.
Add a unit test for the (P)RNG.
=> runtime: fix gr::random API to be fixed-width 64 bit, use XOROSHIRO128+ (manual rebase)

grc/gui/canvas/flowgraph.py
* gui : fix block can move outside top and left boundary
Co-authored-by: Sebastian Koslowski <sebastian.koslowski@gmail.com>
(cherry picked from commit 42349ff2855c1bb0148c8191339189b0a4cee675)
Backport https://github.com/gnuradio/gnuradio/pull/4334/files
=> grc : fix block can move outside top and left boundary (backport to maint-3.9)

grc/gui/canvas/flowgraph.py
* gui : fix block can move outside top and left boundary
Co-authored-by: Sebastian Koslowski <sebastian.koslowski@gmail.com>
(cherry picked from commit 42349ff2855c1bb0148c8191339189b0a4cee675)
Backport https://github.com/gnuradio/gnuradio/pull/4334
=> grc : fix block can move outside top and left boundary (backport to maint-3.8)

gr-qtgui/include/gnuradio/qtgui/ConstellationDisplayPlot.h, gr-qtgui/include/gnuradio/qtgui/EyeDisplayPlot.h, gr-qtgui/include/gnuradio/qtgui/SpectrumGUIClass.h, gr-qtgui/include/gnuradio/qtgui/TimeDomainDisplayPlot.h, gr-qtgui/include/gnuradio/qtgui/VectorDisplayPlot.h, gr-qtgui/include/gnuradio/qtgui/spectrumdisplayform.h, gr-qtgui/include/gnuradio/qtgui/timeRasterGlobalData.h, gr-qtgui/include/gnuradio/qtgui/waterfallGlobalData.h, gr-qtgui/lib/ConstellationDisplayPlot.cc, gr-qtgui/lib/EyeDisplayPlot.cc, gr-qtgui/lib/SpectrumGUIClass.cc, gr-qtgui/lib/TimeDomainDisplayPlot.cc, gr-qtgui/lib/VectorDisplayPlot.cc, gr-qtgui/lib/spectrumdisplayform.cc, gr-qtgui/lib/timeRasterGlobalData.cc, gr-qtgui/lib/waterfallGlobalData.cc
I want to do some more testing today.
I'm not sure why `EyeDisplayPlot` was only freeing the `d_curve_index` `d_ydata`. Was that a mistake, or am I missing something?
=> qtgui: Remove more manual memory management

grc/core/Connection.py
At the moment grc treats a connection int -> float as valid as the itemsizes match. See #4475 
This patch checks the dtype of a port. Connections are only valid if the dtype's match
=> grc: Check connection types, whether they match

grc/core/Connection.py
(cherry picked from commit d44ee73deeaab86a7cc5820ef62688f291331b88)
Backport https://github.com/gnuradio/gnuradio/pull/4483
=> grc: Check connection types, whether they match (backport to maint-3.8)

grc/core/Connection.py
(cherry picked from commit d44ee73deeaab86a7cc5820ef62688f291331b88)
Backport https://github.com/gnuradio/gnuradio/pull/4483
=> grc: Check connection types, whether they match (backport to maint-3.9)

grc/core/Connection.py, grc/core/Constants.py
A recent fix to validate connections by type, rather than by sizeof(type), exposed the fact that GRC did not
handle type aliases.
Fixes https://github.com/gnuradio/gnuradio/issues/4514
=> grc: match data type aliases as well as types

grc/core/Connection.py, grc/core/Constants.py
A recent fix to validate connections by type, rather than by sizeof(type), exposed the fact that GRC did not
handle type aliases.
Fixes #4514
Backport https://github.com/gnuradio/gnuradio/pull/4516
=> grc: match data type aliases as well as types (backport to maint-3.8)

grc/core/Connection.py, grc/core/Constants.py
A recent fix to validate connections by type, rather than by sizeof(type), exposed the fact that GRC did not
handle type aliases.
Fixes #4514
Signed-off-by: Jeff Long willcode4@gmail.com
Backport #4516
=> grc: match data type aliases as well as types (backport to maint-3.9)

cmake/Modules/GnuradioConfig.cmake.in
If gr-iio is part of gnuradio, the module should be mentioned here.
=> gr-iio: add iio GnuradioConfig.cmake.in

grc/core/FlowGraph.py, grc/core/params/dtypes.py, grc/core/params/param.py
This is an alternative solution for #4480 
It uses the import statements to update the blacklist for id's.
That is: If you don't
from gnuradio import audio
you can use audio as id. Otherwise it is blacklisted
=> grc: update id blackist with imports

gr-blocks/grc/blocks_rotator_cc.block.yml, gr-blocks/include/gnuradio/blocks/rotator_cc.h, gr-blocks/lib/rotator_cc_impl.cc, gr-blocks/lib/rotator_cc_impl.h, gr-blocks/python/blocks/bindings/rotator_cc_python.cc, gr-blocks/python/blocks/qa_rotator_cc.py
Often receivers estimate the frequency offset on a block that is downstream with
respect to the frequency correction NCO. In such architectures, typically the
frequency offset estimator feeds the estimation back to the NCO.
This patch adds a message port to the rotator block that makes this architecture
feasible using the rotator as NCO. With that, a downstream block can estimate
frequency offset and send a message to the rotator in order to update its
rotating frequency (i.e. its phase increment).
The input message port receives a PMT pair containing both the new desired phase
increment as well as the absolute index of the rotator's output sample where
this new phase increment should start to take effect.
The rationale of scheduling the phase increment update to a specific absolute
index …
=> Add msg port to control rotator's phase increment

cmake/Modules/FindCodec2.cmake, cmake/Modules/FindMPIR.cmake
Tweak the CMake find modules for codec2 and MPIR so that they work on Windows (at least when using conda packages). Previously it was necessary to specify paths to these libraries/headers with the cmake command so that they could be used.
=> cmake: Fix codec2 and MPIR find modules for Windows (conda).

CMakeLists.txt, gnuradio-runtime/lib/CMakeLists.txt
I think every target affected by the top-level add_definitions links to gnuradio-runtime, so functionally this should be the same. Besides being a more modern CMake style, this has the benefit of propagating the public definitions to any consumers of the gnuradio-runtime library, which includes OOT modules that imported their targets through CMake. For example, OOT modules would previously have to know to define "NOMINMAX" on MSVC, but now that happens transitively. This should make it a little more friendly to build OOT modules, on Windows at least.
This also takes the opportunity to rearrange `gnuradio-runtime/lib/CMakeLists.txt` to what I find is a more logical order, but I can back that out if the diff is deemed too messy.
=> cmake: Move swath of add_definitions to gnuradio-runtime target.

gr-blocks/grc/blocks_rotator_cc.block.yml, gr-blocks/include/gnuradio/blocks/rotator_cc.h, gr-blocks/lib/rotator_cc_impl.cc, gr-blocks/lib/rotator_cc_impl.h, gr-blocks/python/blocks/bindings/rotator_cc_python.cc, gr-blocks/python/blocks/qa_rotator_cc.py
Receivers commonly estimate the frequency offset on a block that is
downstream relative to the frequency correction NCO. In such
architectures, typically the frequency offset estimator feeds the
estimation back to the NCO. Until now, this was not possible if using
the rotator block as the NCO.
This patch adds a message port to the rotator block such that the
referred feedback architecture becomes feasible. A downstream block can
estimate the frequency offset and send a message to the rotator block to
update its rotating frequency (i.e., its phase increment).
The requesting block can schedule the phase increment update to a
specific absolute sample index. This feature is useful for receivers
that rely on a frame structure and pilot-aided frequency offset
estimation. If the true frequency …
=> blocks: Add msg port to set rotator's phase inc (backport to maint-3.9)

gr-analog/examples/pll_freqdet_simple.grc, gr-analog/grc/analog_pll_carriertracking_cc.block.yml, gr-analog/grc/analog_pll_freqdet_cf.block.yml, gr-analog/grc/analog_pll_refout_cc.block.yml, gr-analog/lib/pll_freqdet_cf_impl.cc, gr-analog/lib/pll_freqdet_cf_impl.h
analog: Add example for PLL Frequency Detector
(cherry picked from commit fb281aa2e4aa21be43adc3fb9b80114c75864776)
analog: PLL GRC blocks: better naming, parameter labels
(cherry picked from commit a9e4368866a650f767b88e9ad3e22097b5374141)
analog: PLL Freq Det: refactor (implementation in .cc, not .h)
(cherry picked from commit 39a173fe78a127e57019600e52173e02e492827d)
Backport https://github.com/gnuradio/gnuradio/pull/4513
=> analog: PLL Block: better block naming, better Parameter labels (backport to maint-3.9)

cmake/Modules/FindCodec2.cmake, cmake/Modules/FindMPIR.cmake
(cherry picked from commit c6cf6f99329bed4160f2273563f529852365f799)
Backport https://github.com/gnuradio/gnuradio/pull/4476
=> cmake: Fix codec2 and MPIR find modules for Windows (conda). (backport to maint-3.9)

CMakeLists.txt, gnuradio-runtime/lib/CMakeLists.txt
Besides being a more modern CMake style, this has the benefit of
propagating the public definitions to any consumers of the
gnuradio-runtime library, which includes OOT modules. For example, OOT
modules would previously have to know to define "NOMINMAX" on MSVC, but
now that happens transitively.
Patch pulled directly from ryanvolz tree.
Backport https://github.com/gnuradio/gnuradio/pull/4477
=> cmake: Move swath of add_definitions to gnuradio-runtime target. (backport to maint-3.9)

gr-filter/grc/filter_rational_resampler_xxx.block.yml
Hi
I reported an issue on the mailing list for this flowgraph  [test_fbw.grc.txt](https://github.com/gnuradio/gnuradio/files/6316290/test_fbw.grc.txt)
used in GR 3.8 and 3.9. This flowgraph is only used to demonstrate the issue.
The issue appears when I'm defining a fractional bandwidth (fbw) as "1/sps" calculated from a variable instead of a float value.
during making the template, this error is raised
```
Generating: '/home/seguinot/desktop/test_grc/test_fbw.py'
Generate Error: (ValueError("could not convert string to float: '1/sps'"), 'filter.rational_resampler_${type}(\n        interpolation=${interp},\n        decimation=${decim},\n% if taps:\n        taps=${taps},\n% else:\n        taps=None,\n% endif\n% if float(fbw) != 0:\n        fractional_bw=${fbw})\n% else:\n …
```
=> Fix rational resampler yml

grc/core/blocks/_build.py
Run the `option_attributes` validation routine on the extended dictionary, i.e., after inheriting the properties from the `base_key` parameter. By doing so, if the `dtype` property is inherited, the `_validate_option_attributes` still sees it and does not throw a key error.
For example, the following would break without this patch:
```
-   id: param1
label: label
dtype: enum
options: ...
option_labels: ...
option_attributes:
key: ...
-   id: param2
base_key: param1
options: ...
option_labels: ...
option_attributes:
key: ...
```
@haakov Does this make sense? I see the validation was added in 99b8ef09b954c69492be95b68989d6d75b0446ee.
=> grc: Fix option_attributes check on inherited type

gr-filter/include/gnuradio/filter/filter_delay_fc.h, gr-filter/python/filter/bindings/filter_delay_fc_python.cc
This clarifies that the block does not, indeed, construct a
delay-compensating all-pass, but just takes half the length of the
passed taps vector and uses that as delay.
This bit a student of mine; seeing she's rather capable on her own, this
indicated a need for improved documentation.
=> filter: filter_delay_fc documentation used to be unclear about delay

gnuradio-runtime/include/gnuradio/CMakeLists.txt
As of eb91fb0 this is required for anything linking against gr::random
which broke at least one OOT (gr-pdu_utils)
=> runtime: install xoroshiro128p.h

cmake/Modules/Findlibad9361.cmake
Fix wrong hint for inlcude dirs
=> gr-iio: Fix wrong hint for include dir

grc/core/blocks/block.py
update_bus_logic() is called when disabling a bus, it doesn't check if
it's been previously enabled. This causes it to restore port.hidden with
a None which ultimately is converted to False. So it never hides the
message ports.
Also, filter message ports from buses.
(cherry picked from commit 176e86980b3eeb9795c7a217fba9eb205c7a5adf)
Backport https://github.com/gnuradio/gnuradio/pull/3934
=> grc: Fix message port show/hide problem due to bus logic update (backport to maint-3.8)

gr-soapy/lib/block_impl.cc
=> soapy: interpret some PMT values as doubles to avoid precision errors

gr-filter/grc/filter_rational_resampler_xxx.block.yml
(cherry picked from commit ab3137c5fecd90a3b1c5b5c49e10c2fd81516615)
Backport https://github.com/gnuradio/gnuradio/pull/4530
=> grc: fix rational resampler yml template (backport to maint-3.9)

grc/core/blocks/_build.py
Run the option_attributes validation routine on the extended dictionary,
i.e., after inheriting the properties from the base_key parameter. By
doing so, if the dtype property is inherited, the
_validate_option_attributes still sees it and does not throw a key
error.
(cherry picked from commit 0b3dc1b157b709fcd64a80f13ec604bda3f86e66)
Backport https://github.com/gnuradio/gnuradio/pull/4520
=> grc: Fix option_attributes check on inherited type (backport to maint-3.8)

grc/core/blocks/_build.py
Run the option_attributes validation routine on the extended dictionary,
i.e., after inheriting the properties from the base_key parameter. By
doing so, if the dtype property is inherited, the
_validate_option_attributes still sees it and does not throw a key
error.
(cherry picked from commit 0b3dc1b157b709fcd64a80f13ec604bda3f86e66)
Backport https://github.com/gnuradio/gnuradio/pull/4520
=> grc: Fix option_attributes check on inherited type (backport to maint-3.9)

gr-filter/include/gnuradio/filter/filter_delay_fc.h, gr-filter/python/filter/bindings/filter_delay_fc_python.cc
This clarifies that the block does not, indeed, construct a
delay-compensating all-pass, but just takes half the length of the
passed taps vector and uses that as delay.
(cherry picked from commit 8f9c66bf0b4099cd824745bbbdcde2285db78cf9)
Backport https://github.com/gnuradio/gnuradio/pull/4542
=> filter: filter_delay_fc documentation used to be unclear about delay (backport to maint-3.9)

gr-utils/modtool/cli/add.py, gr-utils/modtool/cli/newmod.py, gr-utils/modtool/cli/rename.py, gr-utils/modtool/core/__init__.py, gr-utils/modtool/core/add.py, gr-utils/modtool/core/base.py, gr-utils/modtool/core/newmod.py, gr-utils/modtool/core/rename.py, gr-utils/modtool/tests/test_modtool.py
also fix some validations which checked a prefix instead of the whole name
Signed-off-by: Ferenc Gerlits <fgerlits@gmail.com>
(cherry picked from commit faf786d57f48bc516c530bfd76e478b3748cd582)
Backport https://github.com/gnuradio/gnuradio/pull/4555
=> modtool: improve the 'invalid name' error message (backport to maint-3.9)

gnuradio-runtime/python/gnuradio/__init__.py, gr-soapy/python/soapy/bindings/CMakeLists.txt, gr-soapy/python/soapy/bindings/python_bindings.cc, gr-soapy/python/soapy/bindings/soapy_types_python.cc, gr-soapy/python/soapy/qa_soapy_types.py
* Fixed gr-soapy Python import
* Partially addresses https://github.com/gnuradio/gnuradio/issues/4571
=> soapy: added Python support for Soapy types needed for full API support

gr-blocks/include/gnuradio/blocks/count_bits.h, gr-blocks/lib/count_bits.cc, gr-blocks/python/blocks/bindings/count_bits_python.cc
* Changed count_bits64 input parameter type to uint64_t
(cherry picked from commit e1dfa8c62b31661d249f3d0f6a0395b01a2e21f9)
Backport https://github.com/gnuradio/gnuradio/pull/4569
=> blocks: use VOLK popcnt implementations for count_bits (backport to maint-3.9)

gr-qtgui/python/qtgui/dialcontrol.py, gr-qtgui/python/qtgui/digitalnumbercontrol.py, gr-qtgui/python/qtgui/msgcheckbox.py, gr-qtgui/python/qtgui/msgpushbutton.py, gr-qtgui/python/qtgui/togglebutton.py, gr-qtgui/python/qtgui/toggleswitch.py
Messages should be constructed using double values instead of float
to avoid loss of precision.
Related to (but does not fix) https://github.com/gnuradio/gnuradio/issues/4562
=> qtgui: Use pmt.from_double() instead of pmt.from_float()

gr-qtgui/python/qtgui/dialcontrol.py, gr-qtgui/python/qtgui/digitalnumbercontrol.py, gr-qtgui/python/qtgui/msgcheckbox.py, gr-qtgui/python/qtgui/msgpushbutton.py, gr-qtgui/python/qtgui/togglebutton.py, gr-qtgui/python/qtgui/toggleswitch.py
Messages should be constructed using double values instead of float
to avoid loss of precision.
(cherry picked from commit 9e32ef0ffab29efe4c52f2e574016cd3d6453484)
Backport https://github.com/gnuradio/gnuradio/pull/4567
=> qtgui: Use pmt.from_double() instead of pmt.from_float() (backport to maint-3.9)

grc/core/blocks/embedded_python.py, grc/core/params/dtypes.py
I refer to the mailing list thread on May 8 2021 regarding "Embedded
Python Block Tutorial Param ID Error".
The bug is caused by #4522 as names of embedded python blocks
such as `epy_block_0` are blacklisted because of "blocks" in the
argument `black_listed_ids`. It affects both embedded python blocks and
modules. This commit fixes the bug by granting exemption for these two
types of blocks from id validation.
=> [v7] grc: Make exception for epy in blacklist id

grc/core/blocks/embedded_python.py, grc/core/params/dtypes.py
I refer to the mailing list thread on May 8 2021 regarding "Embedded
Python Block Tutorial Param ID Error".
The bug is caused by #4522 as names of embedded python blocks
such as `epy_block_0` are blacklisted because of "blocks" in the
argument `black_listed_ids`. It affects both embedded python blocks and
modules. This commit fixes the bug by granting exemption for these two
types of blocks from id validation.
This commit makes the regex more strictly follow the naming convention
of epy blocks and modules so that only these will be fast-tracked
through the id validation. The naming convention appears to be a "epy"
prefix, followed by "block" or "module", and a number suffix.
This regex also takes into account the user copying-and-pasting the epy
blocks resulting in id names like …
=> grc: Make exception for epy in blacklist id (backport to maint-3.9)

grc/core/blocks/embedded_python.py, grc/core/params/dtypes.py
I refer to the mailing list thread on May 8 2021 regarding "Embedded
Python Block Tutorial Param ID Error".
The bug is caused by #4522 as names of embedded python blocks
such as `epy_block_0` are blacklisted because of "blocks" in the
argument `black_listed_ids`. It affects both embedded python blocks and
modules. This commit fixes the bug by granting exemption for these two
types of blocks from id validation.
This commit makes the regex more strictly follow the naming convention
of epy blocks and modules so that only these will be fast-tracked
through the id validation. The naming convention appears to be a "epy"
prefix, followed by "block" or "module", and a number suffix.
This regex also takes into account the user copying-and-pasting the epy
blocks resulting in id names like …
=> grc: Make exception for epy in blacklist id (backport to maint-3.8)

gr-digital/examples/mpsk_stage6.grc
In commit 65bd288, the `digital_cma_equalizer_cc` block was removed.
However, it is still left in the MPSK example flowgraph. This commit
replaces the deprecated cma equalizer with a linear equalizer and an
adaptive algorithm as those are indicated in the gnuradio wiki to be the
appropriate replacements. I have kept the parameters between the two
sets as similar as possible by ensuring the parameters with the same ids
have the same values.
=> gr-digital: Replace CMA Equalizer in MPSK Example

gnuradio-runtime/include/pmt/pmt.h, gnuradio-runtime/python/pmt/bindings/docstrings/pmt_pydoc_template.h, gnuradio-runtime/python/pmt/bindings/pmt_python.cc
Fixes https://github.com/gnuradio/gnuradio/issues/4619
=> pmt: remove extra, mis-named pmt::pmt_ functions

gr-soapy/lib/block_impl.cc
Tried to save a few characters, but matching uhd is a better goal.
=> soapy: use "bandwidth" and "antenna" instead of "bw" and "ant" msgs

gr-digital/examples/mpsk_stage6.grc
In commit 65bd288, the `digital_cma_equalizer_cc` block was removed.
However, it is still left in the MPSK example flowgraph. This commit
replaces the deprecated cma equalizer with a linear equalizer and an
adaptive algorithm as those are indicated in the gnuradio wiki to be the
appropriate replacements. I have kept the parameters between the two
sets as similar as possible by ensuring the parameters with the same ids
have the same values. The only difference is `Modulus`.
Amended `Modulus` from 1 to 4. A note was also added to indicate the
change from the CMA Equalizer to the Linear Equalizer.
(cherry picked from commit 5cdb832ed4ca7840e1d1c9efc70e55d2647654c4)
Backport …
=> gr-digital: Replace CMA Equalizer in MPSK Example (backport to maint-3.9)

gnuradio-runtime/include/pmt/pmt.h, gnuradio-runtime/python/pmt/bindings/docstrings/pmt_pydoc_template.h, gnuradio-runtime/python/pmt/bindings/pmt_python.cc
(cherry picked from commit 91ccd28abae6727509e88ff60032057483ac1b90)
Backport https://github.com/gnuradio/gnuradio/pull/4623
=> pmt: remove extra, mis-named pmt::pmt_ functions (backport to maint-3.9)

grc/core/blocks/block.py, grc/gui/Application.py
This commit resolves Issue #4634 by forcing the flowgraph to reimport
the data it exports.
=> grc: Fix vector length bug

grc/core/blocks/block.py, grc/gui/Application.py
Make all ports follow the `vlen` of their master port the same way it is
for `dtype`. Fixes #4634.
(cherry picked from commit 6f5803963c56d454564ba2ee2e5f2607689b3c43)
Backport https://github.com/gnuradio/gnuradio/pull/4637
=> grc: Fix vector length bug (backport to maint-3.8)

grc/core/blocks/block.py, grc/gui/Application.py
Make all ports follow the `vlen` of their master port the same way it is
for `dtype`. Fixes #4634.
(cherry picked from commit 6f5803963c56d454564ba2ee2e5f2607689b3c43)
Backport https://github.com/gnuradio/gnuradio/pull/4637
=> grc: Fix vector length bug (backport to maint-3.9)

gr-soapy/grc/soapy_custom_sink.block.yml, gr-soapy/grc/soapy_custom_source.block.yml
Fixes https://github.com/gnuradio/gnuradio/issues/4656
=> soapy: custom source/sink freq defaults must be quoted

gr-soapy/grc/soapy_custom_sink.block.yml, gr-soapy/grc/soapy_custom_source.block.yml
(cherry picked from commit e881a24e8c191f782dab902fb453ed4c10a53a2d)
Backport https://github.com/gnuradio/gnuradio/pull/4662
=> soapy: custom source/sink freq defaults must be quoted (backport to maint-3.9)

gr-soapy/grc/soapy_airspyhf_source.block.yml, gr-soapy/grc/soapy_bladerf_sink.block.yml, gr-soapy/grc/soapy_bladerf_source.block.yml, gr-soapy/grc/soapy_custom_sink.block.yml, gr-soapy/grc/soapy_custom_source.block.yml, gr-soapy/grc/soapy_hackrf_sink.block.yml, gr-soapy/grc/soapy_hackrf_source.block.yml, gr-soapy/grc/soapy_limesdr_sink.block.yml, gr-soapy/grc/soapy_limesdr_source.block.yml, gr-soapy/grc/soapy_plutosdr_sink.block.yml, gr-soapy/grc/soapy_plutosdr_source.block.yml, gr-soapy/grc/soapy_rtlsdr_source.block.yml, gr-soapy/grc/soapy_sdrplay_source.block.yml
Also made defaults quoted to be consistent, but this turned out not to be the problem.
Actually fixes https://github.com/gnuradio/gnuradio/issues/4656
=> soapy: yaml - use always-valid defaults for second channel

gr-soapy/grc/soapy_airspyhf_source.block.yml, gr-soapy/grc/soapy_bladerf_sink.block.yml, gr-soapy/grc/soapy_bladerf_source.block.yml, gr-soapy/grc/soapy_custom_sink.block.yml, gr-soapy/grc/soapy_custom_source.block.yml, gr-soapy/grc/soapy_hackrf_sink.block.yml, gr-soapy/grc/soapy_hackrf_source.block.yml, gr-soapy/grc/soapy_limesdr_sink.block.yml, gr-soapy/grc/soapy_limesdr_source.block.yml, gr-soapy/grc/soapy_plutosdr_sink.block.yml, gr-soapy/grc/soapy_plutosdr_source.block.yml, gr-soapy/grc/soapy_rtlsdr_source.block.yml, gr-soapy/grc/soapy_sdrplay_source.block.yml
Also made defaults quoted to be consistent, but this turned out not
to be the problem.
(cherry picked from commit 44152d6c3fb19ab56ef6f839f63fbfb26650b46a)
Backport https://github.com/gnuradio/gnuradio/pull/4664
=> soapy: yaml - use always-valid defaults for second channel (backport to maint-3.9)

gr-qtgui/lib/VectorDisplayPlot.cc
This is why I was running into #4675 .  My data was on the range 0.0-0.01 and was invisible with a total hardcoded margin of 20.
It looks like the margin of 10 on either side might have been unreviewed code copied from the gui frequency sink.  This change updates the margin to be 1% of the range of the data.
=> Fix qt gui vector margin for non-frequency data

gr-qtgui/lib/edit_box_msg_impl.cc, gr-qtgui/lib/number_sink_impl.cc
Closing an flowgraph that contains an qt edit_box_msg or  a number_sink fails with a core dump
free() invaldi pointer.
This pr fixes these issues and fixes #4679 
=> gr-qtgui: fix invalid pointer

grc/core/platform.py
While we mull over #4502 or a better fix that has yet to appear, I thought it would be good to pull out this commit and submit it separately.
This raises an RuntimeError describing that GRC could not find the built-in blocks rather than raising a KeyError on "options", which left users with little to go on. This error has come up in various situations involving an incorrect blocks path (due to mixing GR versions causing the configuration files to point to the wrong installation) or simply the blocks not being installed.
=> grc: Be more informative when missing "options" block.

gnuradio-runtime/lib/prefs.cc
Noticed and and tested over at #4410.
=> runtime: Explicitly convert path to string to fix MSVC build

grc/gui/ParamWidgets.py
Fix `gtk-application-prefer-dark-theme` not affecting the color displayed.
For example, when you have a `~/.config/gtk-3.0/settings.ini` like this, the background color of the input box will still be white.
```
gtk-application-prefer-dark-theme=true
gtk-theme-name=Breeze
```
This also fixes #2374.
=> grc: fix dark theme on ParamWidgets

grc/core/blocks/block.py, grc/gui/canvas/block.py, grc/gui/canvas/colors.py
To make it clear that a block is deprecated, blocks appear with an orange
border on the canvas, and, if enabled, with a light warm yellow background.
I hope this reduces the effort needed to spot problems in flow graphs.
For this to work, I gave the core block (not the GUI block) a property
"deprecated". For now, this just searches (case-normalized) categories for the
string "deprecated", but in case we'd want to make that a tag (like
"throttling/hardware"), separating logic from rendering seemed wise.
=> GRC: Make deprecated blocks appear in orange on Canvas

grc/core/generator/top_block.py
This fix #4557 
I tested it under GR 3.9.1 using different flowgraph combining widgets with/without GUI_hint positioned Inside /outside tabs. 
Note: I =was not able to reproduce errror  in  #4557 first message ( https://github.com/bastibl/gr-rds/blob/3a80121f0858adf4ebd2f5f9f36ff1e4bb18b7a4/examples/rds_rx.grc (maint-3.9 branch) 
Thank to @kaushiksv for proposing this fix
=> grc: fix Wrong order in the generated .py caused by uncorrect function without_gui_hint(block)

grc/core/base.py, grc/core/ports/port.py, grc/gui/VariableEditor.py
At the moment grc does not validate variables, as they are of type raw.
So they are always treated as valid, which leads to some problems, see: #4519.
A approach to fix #4519 is #4531.
This approach improves the situation, but has still some problems.
param.py provides a validator function for dtype raw, but this is not used, as dtypes.py provides no validator function for dtype raw.
This fix introduces a validator function in dtypes.py which calls the corresponding function in param.py.
In addition this makes it possible, to make the code in VariableEditor.py smoother.
The error messages are kept on switching the different tabs in VariableEditor.
=> grc: add validation for variables of type raw

grc/core/platform.py
This raises an RuntimeError describing that GRC could not find the
built-in blocks rather than raising a KeyError on "options", which
left users with little to go on. This error has come up in various
situations involving an incorrect blocks path (due to mixing GR
versions causing the configuration files to point to the wrong
installation) or simply the blocks not being installed.
(cherry picked from commit 6a8fc29d0a6244a1c4624500e853fb23d17ceb86)
Backport https://github.com/gnuradio/gnuradio/pull/4683
=> grc: Be more informative when missing "options" block. (backport to maint-3.9)

grc/core/generator/top_block.py
…n without_gui_hint(block)
grc: fix Wrong order in the generated .py caused by uncorrect function without_gui_hint(block)
(cherry picked from commit d3dc106719fa01f6432b3bafc839dc455f61d695)
Backport https://github.com/gnuradio/gnuradio/pull/4609
=> grc: fix Wrong order in the generated .py caused by uncorrect function (backport to maint-3.9)

grc/core/generator/top_block.py
…n without_gui_hint(block)
grc: fix Wrong order in the generated .py caused by uncorrect function without_gui_hint(block)
(cherry picked from commit d3dc106719fa01f6432b3bafc839dc455f61d695)
Backport https://github.com/gnuradio/gnuradio/pull/4609
=> grc: fix Wrong order in the generated .py caused by uncorrect function (backport to maint-3.8)

grc/core/base.py, grc/core/ports/port.py, grc/gui/VariableEditor.py
At the moment grc does not validate variables, as they are of type raw.
So they are always treated as valid, which leads to some problems, see: #4519.
A approach to fix #4519 is #4531.
This approach improves the situation, but has still some problems.
param.py provides a validator function for dtype raw, but this is not used, as dtypes.py provides no validator function for dtype raw.
This fix clears the error messages in base.rewrite not in base.elements.validate, so the error messages are kept.
In addition this makes it possible, to make the code in VariableEditor.py smoother.
The error messages are kept on switching the different tabs in VariableEditor.
(cherry picked from commit …
=> grc: handle variables of type raw correctly (backport to maint-3.9)

grc/core/base.py, grc/core/ports/port.py, grc/gui/VariableEditor.py
At the moment grc does not validate variables, as they are of type raw.
So they are always treated as valid, which leads to some problems, see: #4519.
A approach to fix #4519 is #4531.
This approach improves the situation, but has still some problems.
param.py provides a validator function for dtype raw, but this is not used, as dtypes.py provides no validator function for dtype raw.
This fix clears the error messages in base.rewrite not in base.elements.validate, so the error messages are kept.
In addition this makes it possible, to make the code in VariableEditor.py smoother.
The error messages are kept on switching the different tabs in VariableEditor.
(cherry picked from commit …
=> grc: handle variables of type raw correctly (backport to maint-3.8)

gr-uhd/python/uhd/bindings/uhd_types_python.cc
Backport https://github.com/gnuradio/gnuradio/pull/4641
=> gr-uhd: Adding missing Python binding for uhd::tune_request_t::policy_t (backport to maint-3.9)

gr-qtgui/lib/edit_box_msg_impl.cc, gr-qtgui/lib/number_sink_impl.cc
(cherry picked from commit ac9eb756cc1d9dd414dbd166a99f1488f14385f2)
Backport https://github.com/gnuradio/gnuradio/pull/4685
=> gr-qtgui: fix invalid pointer (backport to maint-3.9)

gr-qtgui/lib/edit_box_msg_impl.cc, gr-qtgui/lib/number_sink_impl.cc
(cherry picked from commit ac9eb756cc1d9dd414dbd166a99f1488f14385f2)
Backport https://github.com/gnuradio/gnuradio/pull/4685
=> gr-qtgui: fix invalid pointer (backport to maint-3.8)

gr-blocks/python/blocks/bindings/python_bindings.cc
=> gr-blocks: Add missing pybind11 binding for Phase Shift block.

gr-blocks/python/blocks/bindings/python_bindings.cc
(cherry picked from commit 885f9587d22e5f294e1012be56402601831d369a)
Backport https://github.com/gnuradio/gnuradio/pull/4708
=> gr-blocks: Add missing pybind11 binding for Phase Shift block. (backport to maint-3.9)

grc/core/cache.py
Forgot we are still supporting Python 2 on 3.8!
=> Remove Python 3 f-strings from previous backport

gr-iio/CMakeLists.txt, gr-iio/include/gnuradio/iio/CMakeLists.txt, gr-iio/lib/CMakeLists.txt
Hopefully, we can later on absorb that in a version check, so that it's sensible to check this in CMakeLists instead of Findad9361
Fixes #4715
=> iio: detect not only ad9361.h presence, but suitability

gr-fft/lib/CMakeLists.txt
Fixes the following warning (Arch Linux, CMake 3.20.3):
```
CMake Warning (dev) at cmake/Modules/GrTest.cmake:151 (add_executable):
Policy CMP0115 is not set: Source file extensions must be explicit.  Run
"cmake --help-policy CMP0115" for policy details.  Use the cmake_policy
command to set the policy and suppress this warning.
File:
/home/hkon/gnuradio/gr-fft/lib/qa_fft_shift.cc
Call Stack (most recent call first):
gr-fft/lib/CMakeLists.txt:68 (GR_ADD_CPP_TEST)
This warning is for project developers.  Use -Wno-dev to suppress it.
```
=> fft: Use explicit extension when adding test

gr-blocks/python/blocks/msg_pair_to_var.py, gr-blocks/python/blocks/var_to_msg.py
Fixes #4702 where a user was feeding a dictionary into the msg_to_var
block which was then setting the variable to 'None' causing unexpected
behavior. This improves input sanitization for both blocks and adds
some extra info to the docstrings.
=> gr-blocks: improvements to input handling in var/msg blocks

gr-blocks/python/blocks/msg_pair_to_var.py, gr-blocks/python/blocks/var_to_msg.py
Fixes an issue where a user was feeding a dictionary into the msg_to_var
block which was then setting the variable to 'None' causing unexpected
behavior. This improves input sanitization for both blocks and adds
some extra info to the docstrings.
Signed-off-by: Jacob Gilbert <jacob.gilbert@protonmail.com>
(cherry picked from commit ab1e21c114465fa03d7fb1b56b3d5f8c9f56671e)
Backport https://github.com/gnuradio/gnuradio/pull/4704
=> blocks: improvements to var/msg blocks (backport to maint-3.9)

gr-blocks/lib/CMakeLists.txt
Similar to #4539, we now need to make sure that `HAVE_WINDOWS_H` is defined for the `gnuradio-blocks` target. See discussion in #4159, patch taken from what @willcode posted there and fixed to use `gnuradio-blocks` instead of `gnuradio-network`.
=> blocks: Windows defines required (maint-3.9)

cmake/Modules/GrPybind.cmake
Stumbled across this while working on precompiled headers. Probably has not
been a problem since Pybind11 tends towards "boring" install locations.
=> cmake: lowercase pkg-config module requires lowercase pybind11_INCLUDE_DIR

CHANGELOG.md, cmake/Modules/GrPybind.cmake
(cherry picked from commit 0705a715dea306c4d53301095f93b0f7077c4a61)
Backport https://github.com/gnuradio/gnuradio/pull/4729
=> cmake: lowercase pkg-config module requires lowercase pybind11_INCLUDE_DIR (backport to maint-3.9)

gr-fft/lib/CMakeLists.txt
(cherry picked from commit d84df80edaf1e8491a1b4fc208b407b7e5c5198c)
Backport https://github.com/gnuradio/gnuradio/pull/4719
=> fft: Use explicit extension when adding test (backport to maint-3.8)

gr-fft/lib/CMakeLists.txt
(cherry picked from commit d84df80edaf1e8491a1b4fc208b407b7e5c5198c)
Backport https://github.com/gnuradio/gnuradio/pull/4719
=> fft: Use explicit extension when adding test (backport to maint-3.9)

gr-soapy/python/soapy/bindings/soapy_common.cc
Soapy has its own way of casting strings to bools, and it special-cases
"0" and "0.0" and misses out on the opportunity to be consistent with
many other ways of specifying 0 as number.
I'm trying to upstream the same change to SoapSDR, in order to keep
things consistent. But this is worth having in GNU Radio, either way,
since GNU Radio has its own user expectations, which might even differ a
bit from these of SoapySDR users.
Fixes #4742
References https://github.com/pothosware/SoapySDR/pull/313
=> soapy: less surprising bool cast

gr-soapy/python/soapy/bindings/soapy_common.cc
Soapy has its own way of casting strings to bools, and it special-cases
"0" and "0.0" and misses out on the opportunity to be consistent with
many other ways of specifying 0 as number.
I'm trying to upstream the same change to SoapSDR, in order to keep
things consistent. But this is worth having in GNU Radio, either way,
since GNU Radio has its own user expectations, which might even differ a
bit from these of SoapySDR users.
(cherry picked from commit 16d1b0215d59c52009b09867fbfce0b4c3585add)
Backport https://github.com/gnuradio/gnuradio/pull/4743
=> soapy: less surprising bool cast (backport to maint-3.9)

gr-digital/grc/digital_diff_decoder_bb.block.yml, gr-digital/grc/digital_diff_encoder_bb.block.yml, gr-digital/include/gnuradio/digital/CMakeLists.txt, gr-digital/include/gnuradio/digital/diff_coding_type.h, gr-digital/include/gnuradio/digital/diff_decoder_bb.h, gr-digital/include/gnuradio/digital/diff_encoder_bb.h, gr-digital/lib/diff_decoder_bb_impl.cc, gr-digital/lib/diff_decoder_bb_impl.h, gr-digital/lib/diff_encoder_bb_impl.cc, gr-digital/lib/diff_encoder_bb_impl.h, gr-digital/python/digital/bindings/CMakeLists.txt, gr-digital/python/digital/bindings/diff_coding_type_python.cc, gr-digital/python/digital/bindings/diff_decoder_bb_python.cc, gr-digital/python/digital/bindings/docstrings/diff_coding_type_pydoc_template.h, gr-digital/python/digital/bindings/python_bindings.cc, gr-digital/python/digital/qa_diff_encoder.py, gr-digital/python/digital/qa_diff_encoder_nrzi.py
```
This adds NRZI encoder and decoder blocks. The blocks are similar
to a Differential encoder / decoder with a modulus of 2, but there
is an extra inversion. Having dedicated NRZI blocks saves the user
from having to add a Not block to handle the inversion. NRZI is
used in AX.25 and other protocols as a differential coding method.
The NRZI blocks have been taken and adapted from the gr-satellites
OOT as described in #3637.
Signed-off-by: Daniel Estévez <daniel@destevez.net>
```
**Note:** I have kept my name in the copyright statements in the header of the new files. I've browsed recent commits to see if there was a consistent approach to this after the exit from the FSF, but I didn't arrive to any conclusion. If required, I can change the copyright statements.
=> digital: Add NRZI blocks

gnuradio-runtime/lib/constants.cc.in
Signed-off-by: Ed Beroset <beroset@ieee.org>
=> Fix gnuradio/gnuradio#4639 by dereferencing symlink in gr::prefix().

gr-utils/modtool/core/bind.py, gr-utils/modtool/core/rm.py, gr-utils/modtool/tools/util_functions.py
Fixes #4682 and fixes #4281, a bug triggered in the `rm` and `bind` commands when the
block name (or regex) is entered as stdin rather than an argument.
=> modtool: Fix `TypeError`

grc/gui/Application.py
Fixes #4781. When a variable is controlled by another variable,
updating the latter does not update the former in the flowgraph when
`Ok` is pressed. Caused by commit c4f46bf. This commit patches the bug.
=> grc: Update flowgraph vars controlled by vars

gnuradio-runtime/python/gnuradio/gr/CMakeLists.txt, gnuradio-runtime/python/gnuradio/gr/qa_flowgraph.py, gnuradio-runtime/python/gnuradio/gr/qa_hier_block2.py, gr-blocks/python/blocks/__init__.py, gr-pdu/python/pdu/qa_pdu.py
This included shifting of the PDU test from runtime to gr-pdu, and
making the tests that actually require blocks conditional on whether
there's going to be gr-blocks. Also, don't use gr-analog just because
you need data.
=> testing: rm dependencies from disabled components in blocks/runtime tests

gr-digital/examples/packet/formatter_crc_header_payload_demux.grc
This commit adds a simple example combining the header/payload block
with the formatter_crc example. Its purpose is to show a simpler, more
beginner friendly example for the header/payload block compared to the
current ofdm hier block used as an example.
=> gr-digital: Simple header payload demux example

gr-digital/grc/digital_diff_decoder_bb.block.yml, gr-digital/grc/digital_diff_encoder_bb.block.yml, gr-digital/include/gnuradio/digital/CMakeLists.txt, gr-digital/include/gnuradio/digital/diff_coding_type.h, gr-digital/include/gnuradio/digital/diff_decoder_bb.h, gr-digital/include/gnuradio/digital/diff_encoder_bb.h, gr-digital/lib/diff_decoder_bb_impl.cc, gr-digital/lib/diff_decoder_bb_impl.h, gr-digital/lib/diff_encoder_bb_impl.cc, gr-digital/lib/diff_encoder_bb_impl.h, gr-digital/python/digital/bindings/CMakeLists.txt, gr-digital/python/digital/bindings/diff_coding_type_python.cc, gr-digital/python/digital/bindings/diff_decoder_bb_python.cc, gr-digital/python/digital/bindings/docstrings/diff_coding_type_pydoc_template.h, gr-digital/python/digital/bindings/python_bindings.cc, gr-digital/python/digital/qa_diff_encoder.py, gr-digital/python/digital/qa_diff_encoder_nrzi.py
This adds NRZI encoder and decoder blocks. The blocks are similar
to a Differential encoder / decoder with a modulus of 2, but there
is an extra inversion. Having dedicated NRZI blocks saves the user
from having to add a Not block to handle the inversion. NRZI is
used in AX.25 and other protocols as a differential coding method.
The NRZI blocks have been taken and adapted from the gr-satellites
OOT as described in #3637.
Signed-off-by: Daniel Estévez <daniel@destevez.net>
(cherry picked from commits 51c504ebb, 222d95124)
Backport https://github.com/gnuradio/gnuradio/pull/4687
=> digital: Add NRZI blocks (backport to maint-3.9)

gr-utils/modtool/core/bind.py, gr-utils/modtool/core/rm.py, gr-utils/modtool/tools/util_functions.py
Fixes #4682, a bug triggered in the `rm` and `bind` commands when the
block name (or regex) is entered as stdin rather than an argument.
(cherry picked from commit b285dc3dbd8369805e2c2e612dbf88983faf1353)
Backport https://github.com/gnuradio/gnuradio/pull/4686
=> modtool: Fix TypeError (backport to maint-3.9)

grc/gui/Application.py
Fixes #4781. When a variable is controlled by another variable,
updating the latter does not update the former in the flowgraph when
`Ok` is pressed. Caused by commit c4f46bf. This commit patches the bug.
(cherry picked from commit bfb5e3baa88763adb9e40ae3c511e317695fedb5)
Backport https://github.com/gnuradio/gnuradio/pull/4784
=> grc: Update flowgraph vars controlled by vars (backport to maint-3.9)

gr-soapy/include/gnuradio/soapy/block.h, gr-soapy/include/gnuradio/soapy/sink.h, gr-soapy/include/gnuradio/soapy/source.h, gr-soapy/python/soapy/bindings/block_python.cc, gr-soapy/python/soapy/bindings/sink_python.cc, gr-soapy/python/soapy/bindings/source_python.cc
(cherry picked from commit 3fe76f88d5585b62a286180265718beac5b1fb9b)
Backport https://github.com/gnuradio/gnuradio/pull/4774
=> Doxygen: Remove warnings from gr-soapy and gr-iio. (backport to maint-3.9)

gr-qtgui/lib/EyeDisplayPlot.cc, gr-qtgui/lib/HistogramDisplayPlot.cc, gr-qtgui/lib/TimeDomainDisplayPlot.cc, gr-qtgui/lib/TimePrecisionClass.h, gr-qtgui/lib/TimeRasterDisplayPlot.cc
(cherry picked from commit e1b633a95047fce266e575cbc66a314d31c24491)
Backport https://github.com/gnuradio/gnuradio/pull/4776
=> qtgui: only one definition of (internal) TimePrecisionClass (backport to maint-3.9)

gr-utils/modtool/core/disable.py, gr-utils/modtool/core/makeyaml.py, gr-utils/modtool/core/rename.py, gr-utils/modtool/core/rm.py
Fixes #2672 
When a block name is entered as an argument to a modtool command, (e.g. `gr_modtool rm my_block`), the user expects _only_ that specific block (ie `my_block`) to be acted upon. Issue #2672 is caused when similarly named block names are also acted upon (e.g. `my_block_1` or `temp_my_block`). This issue affects the four commands stated in the title. PR fixes said issue.
Edit:
PR also fixes two other seemingly unreported issues:
1. A minor AttributeError affecting the `disable` command OOT version 38 due to what I believe is a spelling error: `self._info` should be `self.info`. 
2. Failure of the `rename` command to rename the binding function in `python_bindings.cc`.
=> modtool: Fix #2672 for `rm`, `disable`, `rename` and `makeyml`

CMakeLists.txt, cmake/Modules/Findlibunwind.cmake, cmake/Modules/GrPybind.cmake, cmake/Modules/GrPython.cmake, gnuradio-runtime/lib/CMakeLists.txt, gr-utils/modtool/templates/gr-newmod/CMakeLists.txt
This transitions to using `Python::NumPy`, `pybind11::pybind11`, and `libunwind::libunwind` targets for building with the include directories/libraries of NumPy, pybind11, and libunwind. The Python::NumPy target matches what is available with the FindPython module in CMake 3.14+ (and can be transitioned to such when the minimum CMake version is past that). These changes have the effect of cleaning up the include_directory paths added to the gnuradio-runtime target so that no absolute paths are used, which is helpful for relocatable installations (e.g. conda).
Part of this change involves moving some link targets to PRIVATE since they are not actually part of the public interface. In the case of the python bindings, these are not exported and have no public interface for consumption by …
=> cmake: Remove absolute paths and private links from exported targets.

gr-iio/grc/iio_device_sink.block.yml, gr-iio/grc/iio_device_source.block.yml, gr-iio/grc/iio_fmcomms2_sink.block.yml, gr-iio/grc/iio_fmcomms5_sink.block.yml, gr-iio/grc/iio_fmcomms5_source.block.yml, gr-iio/grc/iio_pluto_sink.block.yml, gr-iio/grc/iio_pluto_source.block.yml
This commit fixes the flags for hardware connected blocks to include
"throttle", which prevents the following warning from being emitted
erroneously:
>>> Warning: This flow graph may not have flow control: no audio or RF
hardware blocks found. Add a Misc->Throttle block to your flow graph to
avoid CPU congestion.
Additionally, the python flag is added to all blocks for consistency.
=> gr-iio: grc: Fix source/sink throttle/python flags

cmake/Modules/GrPython.cmake
GRC already does a few GR_PYTHON_INSTALLs with extra FILES_MATCHING
REGEX arguments, so this will actually pass these through.
This was necessary in an earlier version of #4671, but isn't anymore and has thus been moved to a separate PR.
=> cmake: Pass extra arguments to GR_PYTHON_INSTALL to install command.

grc/gui/Constants.py
(cherry picked from commit 518dc7eda3a2575292dc67374cad62c887f83d12)
Backport https://github.com/gnuradio/gnuradio/pull/3980
=> Fix drag n' drop issue with Quartz (macOS) backend (backport to maint-3.8)

gr-utils/modtool/core/disable.py, gr-utils/modtool/core/makeyaml.py, gr-utils/modtool/core/rename.py, gr-utils/modtool/core/rm.py
* modtool: Fix issue #2672 for `rm`
In the event that the user specifies only one specific block to delete,
this PR ensures that the files for said block is not confused with files
of similarly named blocks.
* modtool: Fix issue #2672 for `rename` and more
This commit fixes the following for the `rename` command.
1. Issue #2672 that also affects `rename`
2. Fixes errorneous replacement of similarly named blocks in CMakeLists
3. Replaced the file search in `_run_file_rename` from `file.find` to
`re.search` so that block names will not be confused with names with one
or two prefix characters (e.g. "decoder" vs "adecoder").
4. Renames the bind function in `python_bindings.cc` as well.
Signed-off-by: Solomon Tan …
=> modtool: Fix `rm`, `disable`, `rename` and `makeyml` similar naming (backport to maint-3.9)

cmake/Modules/GrPython.cmake
GRC already does a few GR_PYTHON_INSTALLs with extra FILES_MATCHING
REGEX arguments, so this will actually pass these through.
(cherry picked from commit 655e232a6998a221141cc10d6675603656caff4c)
Backport https://github.com/gnuradio/gnuradio/pull/4717
=> cmake: Pass extra arguments to GR_PYTHON_INSTALL to install command. (backport to maint-3.9)

CMakeLists.txt, cmake/Modules/Findlibunwind.cmake, cmake/Modules/GrPybind.cmake, cmake/Modules/GrPython.cmake, gnuradio-runtime/lib/CMakeLists.txt, gr-utils/modtool/templates/gr-newmod/CMakeLists.txt
This transitions to using Python::NumPy, pybind11::pybind11, and
libunwind::libunwind targets for building with the include
directories/libraries of NumPy, pybind11, and libunwind. The
Python::NumPy target matches what is available with the FindPython
module in CMake 3.14+ (and can be transitioned to such when the minimum
CMake version is past that). These changes have the effect of cleaning
up the include_directory paths added to the gnuradio-runtime target so
that no absolute paths are used, which is helpful for relocatable
installations (e.g. conda).
Part of this change involves moving some link targets to PRIVATE since
they are not actually part of the public interface. In the case of the
python bindings, these are not exported and have no public interface for
consumption by other C++ …
=> cmake: Remove absolute paths and private links from exported targets. (backport to maint-3.9)

gr-channels/grc/channels_impairments.block.yml, gr-channels/python/channels/distortion_2_gen.py, gr-channels/python/channels/impairments.py
- Add missing label docs for the phase noise power
- Fix a bunch of Pylint issues
- Rename blocks in the hier block from their GRC auto-generated names to
something more readable
(cherry picked from commit b6851218337aca35ace7e9fe80b92a942b7a5c27)
Backport https://github.com/gnuradio/gnuradio/pull/4616
=> channels: Clean up the hardware impairments block (backport to maint-3.9)

gr-blocks/grc/blocks_head.block.yml, gr-blocks/include/gnuradio/blocks/head.h, gr-blocks/lib/head_impl.cc, gr-blocks/python/blocks/bindings/head_python.cc
If you don't want to test a stream with an exact number of input, but
just want your flow graph to terminate after a given number of items,
having a head block without an output enables you to do that without
copying the data from Head's in- to its output.
=> blocks: zero-output, zero-copy Head mode

gr-iio/lib/gnuradio-iio.rc.in
=> iio: lib: Add missing gnuradio-iio.rc.in Windows DLL resource file

gnuradio-runtime/include/gnuradio/tag_checker.h, gnuradio-runtime/include/gnuradio/tags.h, gnuradio-runtime/python/gnuradio/gr/bindings/tag_checker_python.cc, gnuradio-runtime/python/gnuradio/gr/bindings/tags_python.cc, gnuradio-runtime/python/gnuradio/gr/qa_tag_utils.py, gnuradio-runtime/python/gnuradio/gr/tag_utils.py, gr-digital/python/digital/qa_burst_shaper.py
runtime: tags can be compared with < instead of offset_compare    
(cherry picked from commit ae586c92d7ccb945fb994c29571c257d02e5f6ee)
runtime: use < instead of compare_offset, remove Python comparison class
Since the introduction of the comparison operator obsoletes the comparison class, remove it.
(cherry picked from commit 078d40ddeab957fcc91060131a4b3a1dfe9df676)
Backport https://github.com/gnuradio/gnuradio/pull/4760
=> runtime: tags can be compared with < instead of offset_compare (backport to maint-3.9)

gnuradio-runtime/include/gnuradio/logger.h, gnuradio-runtime/lib/logger.cc, gnuradio-runtime/python/gnuradio/gr/bindings/logger_python.cc, gr-fec/lib/generic_decoder.cc, gr-fec/lib/generic_encoder.cc, gr-iio/lib/attr_sink_impl.cc, gr-iio/lib/attr_source_impl.cc, gr-iio/lib/attr_source_impl.h, gr-iio/lib/dds_control_impl.cc, gr-iio/lib/device_sink_impl.cc, gr-iio/lib/device_sink_impl.h, gr-iio/lib/device_source_impl.cc, gr-iio/lib/device_source_impl.h, gr-iio/lib/fmcomms2_sink_impl.cc, gr-iio/lib/fmcomms2_source_impl.cc, gr-iio/lib/fmcomms5_sink_impl.cc, gr-iio/lib/fmcomms5_source_impl.cc, gr-iio/lib/pluto_source_impl.cc
This commit cleans up unused headers (cstdio) and replaces all instances
of std::cout and std::cerr with the corresponding GR_LOG_* invocation.
Additionally, a helper is added to gr/lib/logger.cc to facilitate the
allocation of loggers which are automatically configured according to the
gnuradio configuration settings.
(I had some issues getting the logger to work in static contexts (As such no access to d_logger), so i created a new helper that does the logger configuration for me. I'm still not sure if that should be something global, but it is certainly not very iio specific.)
=> iio: Remove cstdio/iostream and log using GR_LOG

gr-soapy/lib/block_impl.cc
Manual rebase of #4741 
Second change in that PR was made obsolete by 16d1b0215d59c52009b09867fbfce0b4c3585add
* use empty() on antenna vector
=> clang-tidy: run-clang-tidy with default checks on gr-soapy (Manual Rebase)

gr-soapy/lib/block_impl.cc
* use empty() on antenna vector
(cherry picked from commit 7b21032dea9d4d8ead09178fa2fa99fb37d7f9a2)
Backport https://github.com/gnuradio/gnuradio/pull/4831
=> clang-tidy: run-clang-tidy with default checks on gr-soapy (backport to maint-3.9)

grc/gui/canvas/flowgraph.py
This commit fixes what's basically a broken numerical integration in
the block dragging code, leading to a position desynchronization between
mouse pointer and block.
This issue in action: https://www.youtube.com/watch?v=bSp7UshDsRM
=> grc: Fix desync when dragging block

gr-utils/modtool/templates/gr-newmod/CMakeLists.txt
This avoids creating multiple copies of the .so file
(each with a different git tag) during development.
The ldconfig command doesn't necessarily set the symlink
properly and the old .so can get loaded after an update.
This can be very confusing for developers and this patch
suppresses that behavior by always creating the .so with
the same name.
=> gr-newmod: Set OOT module VERSION_PATCH to 0 instead of git.

grc/gui/canvas/flowgraph.py
This commit fixes what's basically a broken numerical integration in
the block dragging code, leading to a position desynchronization between
mouse pointer and block.
Signed-off-by: David Winter <david.winter@analog.com>
(cherry picked from commit b6f2120e84b3b541a636420ac2af8d2d86f091ac)
Backport https://github.com/gnuradio/gnuradio/pull/4843
=> grc: Fix desync when dragging block (backport to maint-3.8)

grc/gui/canvas/flowgraph.py
This commit fixes what's basically a broken numerical integration in
the block dragging code, leading to a position desynchronization between
mouse pointer and block.
Signed-off-by: David Winter <david.winter@analog.com>
(cherry picked from commit b6f2120e84b3b541a636420ac2af8d2d86f091ac)
Backport https://github.com/gnuradio/gnuradio/pull/4843
=> grc: Fix desync when dragging block (backport to maint-3.9)

gr-utils/python/modtool/templates/gr-newmod/CMakeLists.txt
This avoids creating multiple copies of the .so file
(each with a different git tag) during development.
The ldconfig command doesn't necessarily set the symlink
properly and the old .so can get loaded after an update.
This can be very confusing for developers and this patch
suppresses that behavior by always creating the .so with
the same name.
(cherry picked from commit 6c36e38ce843476f214b716b25e001e96336fc58)
Backport https://github.com/gnuradio/gnuradio/pull/4839
=> gr-newmod: Set OOT module VERSION_PATCH to 0 instead of git. (backport to maint-3.8)

gr-utils/modtool/templates/gr-newmod/CMakeLists.txt
This avoids creating multiple copies of the .so file
(each with a different git tag) during development.
The ldconfig command doesn't necessarily set the symlink
properly and the old .so can get loaded after an update.
This can be very confusing for developers and this patch
suppresses that behavior by always creating the .so with
the same name.
(cherry picked from commit 6c36e38ce843476f214b716b25e001e96336fc58)
Backport https://github.com/gnuradio/gnuradio/pull/4839
=> gr-newmod: Set OOT module VERSION_PATCH to 0 instead of git. (backport to maint-3.9)

gr-soapy/lib/block_impl.cc, gr-soapy/lib/block_impl.h, gr-soapy/lib/setting_string_conversion.h, gr-soapy/python/soapy/bindings/CMakeLists.txt, gr-soapy/python/soapy/bindings/soapy_common.cc
* Moved string <-> setting conversion to common header
* Closes https://github.com/gnuradio/gnuradio/issues/4571
(cherry picked from commit a152662f8536a1f389f7f799f588a0e4623a7bea)
Backport https://github.com/gnuradio/gnuradio/pull/4835
=> soapy: added message support for SoapySDR 0.8 API (backport to maint-3.9)

gr-uhd/lib/usrp_block_impl.cc
Before, a zero literal was being passed in for a pmt::pmt_t parameter.
This resulted in an implicit cast to a null shared_ptr, rather than
a PMT respresenting zero as intended.
=> usrp_block: fix using 0 as pmt::dict_ref "not_found" parameter

gr-uhd/lib/usrp_block_impl.cc
Before, a zero literal was being passed in for a pmt::pmt_t parameter.
This resulted in an implicit cast to a null shared_ptr, rather than
a PMT respresenting zero as intended.
(cherry picked from commit 188bf4d1ff87146bd8f24fa055fc531479705448)
Backport https://github.com/gnuradio/gnuradio/pull/4849
=> usrp_block: fix using 0 as pmt::dict_ref "not_found" parameter (backport to maint-3.9)

CODE_OF_CONDUCT.md
(cherry picked from commit a65cdb644622f738dcbb84f90274dfe5e00ced99)
Backport https://github.com/gnuradio/gnuradio/pull/4870
=> CoC: Updated Title and link to gr-governance instead of wiki (backport to maint-3.8)

CODE_OF_CONDUCT.md
(cherry picked from commit a65cdb644622f738dcbb84f90274dfe5e00ced99)
Backport https://github.com/gnuradio/gnuradio/pull/4870
=> CoC: Updated Title and link to gr-governance instead of wiki (backport to maint-3.9)

gr-qtgui/lib/time_sink_c_impl.cc, gr-qtgui/lib/time_sink_f_impl.cc
3.9 backport of https://github.com/gnuradio/gnuradio/pull/4873
=> qtgui: bugfix - display tags on the last sample (backport to maint-3.9)

gr-qtgui/lib/time_sink_c_impl.cc, gr-qtgui/lib/time_sink_f_impl.cc
3.8 backport of https://github.com/gnuradio/gnuradio/pull/4873
=> qtgui: display tags on the last sample fixes #2775 (backport to maint-3.8)

gr-qtgui/include/gnuradio/qtgui/utils.h
`check_set_qss` is part of the public qtgui headers, but hasn't been
declared part of the public API as of now. This is unfortunate, because
when bootstrapping a Qt application, this function should be called to
apply a qt gui stylesheet as defined in the config.
This commit adds that function to the public api to allow external Qt
GUI widgets to behave in a manner that's compatible with the in-tree
widgets.
=> qtgui: Make check_set_qss public

gnuradio-runtime/lib/constants.cc.in
=> runtime: dereference symlink in gr::prefix() (backport to maint-3.9) (V2)

gr-utils/modtool/templates/templates.py
Was "value:", should be "default:".
Fixes https://github.com/gnuradio/gnuradio/issues/4521
=> modtool: fix field name in template

gr-utils/modtool/templates/templates.py
Was "value:", should be "default:".
(cherry picked from commit c9c33f98f1d96f149f710086f11be845e5100942)
Backport https://github.com/gnuradio/gnuradio/pull/4895
=> modtool: fix field name in template (backport to maint-3.9)

gnuradio-runtime/lib/constants.cc.in
Backport 311a983 (manual)
Backport https://github.com/gnuradio/gnuradio/pull/4739
This is not super important, but make the code more readable.
=> runtime: constants: modernized #include, structure (backport to maint-3.9)

grc/core/FlowGraph.py
If we want disabled blocks to be updated properly,
we have to consider all blocks when updating the fg not only the enabled.
This does the patch of Flowgraph.py and fixes #4788.
But a problem remains.
If you use the example in #4788 and disable the symbol_rate block,
only the samp_rate block 'turns to red'.
The other blocks don't change.
Only if you open and close arbitrary block, the other blocks are updated.
This is fixed by the patch of Application.py.
=> grc: update disabled blocks if they depend on others

gr-blocks/examples/CMakeLists.txt, gr-blocks/examples/matrix_interleaver.grc, gr-blocks/grc/blocks.tree.yml, gr-blocks/grc/blocks_matrix_interleaver.block.yml, gr-blocks/python/blocks/CMakeLists.txt, gr-blocks/python/blocks/__init__.py, gr-blocks/python/blocks/matrix_interleaver.py, gr-blocks/python/blocks/qa_matrix_interleaver.py
This is the GR 3.9 equivalent of PR #4860.
The matrix interleaver is a hierarchical block that pairs a base
deinterleave block that effectively writes samples into "rows" (1 block of
samples per output) and a base interleave block that outputs samples
iteratively from each input like  "columns".
Signed-off-by: Jared Dulmage <jared.dulmage@caliola.com>
Add grc file and update blocks.tree.yml.
Fix module for matrix interleaver example
Signed-off-by: Jared Dulmage <jared.dulmage@caliola.com>
=> Matrix Interleaver block

gr-blocks/lib/tagged_file_sink_impl.cc, gr-digital/lib/burst_shaper_impl.cc, gr-digital/lib/header_payload_demux_impl.cc, gr-digital/lib/symbol_sync_cc_impl.cc, gr-digital/lib/symbol_sync_ff_impl.cc, gr-uhd/lib/usrp_sink_impl.cc
this is mostly a reminder from a time long gone, when tags didn't come out of `get_tags_in_range` sorted.
=> Remove sorting of tag vectors where already sorted

gr-analog/grc/analog_noise_source_x.block.yml, gr-qtgui/examples/c++/Number_Sink.grc, gr-qtgui/examples/c++/gui_sink.grc, gr-qtgui/grc/qtgui_check_box.block.yml, gr-qtgui/grc/qtgui_entry.block.yml, gr-qtgui/grc/qtgui_freq_sink_x.block.yml, gr-qtgui/grc/qtgui_label.block.yml, gr-qtgui/grc/qtgui_number_sink.block.yml, gr-qtgui/grc/qtgui_sink_x.block.yml, gr-qtgui/grc/qtgui_tab_widget.block.yml, gr-qtgui/grc/qtgui_waterfall_sink_x.block.yml, gr-qtgui/include/gnuradio/qtgui/freq_sink_c.h, gr-qtgui/include/gnuradio/qtgui/freq_sink_f.h, gr-qtgui/include/gnuradio/qtgui/number_sink.h, gr-qtgui/include/gnuradio/qtgui/sink_c.h, gr-qtgui/include/gnuradio/qtgui/sink_f.h, gr-qtgui/include/gnuradio/qtgui/waterfall_sink_c.h, gr-qtgui/include/gnuradio/qtgui/waterfall_sink_f.h, grc/core/generator/cpp_templates/flow_graph.cpp.mako, grc/core/generator/cpp_top_block.py, grc/core/params/param.py
At the moment some qtgui windows do support only very simple gui hints, as
the parse_gui_hint in param.py generates only python code independently of the output language.
This is fixed here, so the gui_hint() can be used in cpp code generation.
To test more complex gui hints the qtgui_tab_widget was extended to cpp.
After that compiling the generated cpp code for some examples led to
```
/usr/include/python3.9/object.h:206:23: Fehler: expected unqualified-id before »;« token
206 |     PyType_Slot *slots; /* terminated by slot==0. */
```
This is a known error and can be fixed by
```
#ifdef ENABLE_PYTHON
#pragma push_macro("slots")
#undef slots
#include "Python.h"
#pragma pop_macro("slots")
#endif
```
instead of simply
```
#ifdef ENABLE_PYTHON
#include "Python.h"
#endif
```
which was …
=> grc: introduce gui_hint for cpp code generation

gr-blocks/grc/blocks_throttle.block.yml, gr-blocks/include/gnuradio/blocks/throttle.h, gr-blocks/lib/throttle_impl.cc, gr-blocks/python/blocks/bindings/throttle_python.cc
When throttling a sample flow, it's not necessary to produce items at
the desired average rate - consuming them at a limited rate suffices to
slow down the processing of the whole flow graph just as well, and
avoids a copy.
=> blocks: Throttle consume-only mode

.github/workflows/make-test.yml, .github/workflows/pkg-debian.yml, .github/workflows/pkg-fedora.yml, gnuradio-runtime/include/gnuradio/tag_checker.h, gnuradio-runtime/python/gnuradio/gr/bindings/tag_checker_python.cc
`tag_checker` used to be meant for cases where you've gotten an unsorted
tag vector (mostly, from `get_tags_in_range`), which you then had to go
through in parallel to your samples, to check which tag applies at what
sample.
For that it sorts the tags; the tags coming from the `get_tags*` functions
are sorted already
The checking pattern (which `chunks_to_symbols` is the last consumer of)
is inefficient: instead of taking the index of the first unprocessed tag
and processing all samples up to that index, a check is performed on
every sample, which includes calls and multiple indirections.
So, since very likely nobody uses this, and because it's a design
anti-pattern, deprecating this.
Together with the actual removal, addresses #4898.
Backport …
=> runtime: deprecate tag_checker (removal in 3.10)

grc/core/FlowGraph.py
If we want disabled blocks to be updated properly,
we have to consider all blocks when updating the fg not only the enabled.
This does the patch of Flowgraph.py and fixes #4788.
But a problem remains.
If you use the example in #4788 and disable the symbol_rate block,
only the samp_rate block 'turns to red'.
The other blocks don't change.
Only if you open and close an arbitrary block, the other blocks are updated.
This is fixed by clearing the namespace in renew_namespace in FlowGraph.py.
grc: update disabled blocks
(cherry picked from commit fbab6c383d6f86ab0de42a90a9182d22637a5b96)
Backport …
=> grc: update disabled blocks if they depend on others (backport to maint-3.9)

grc/core/FlowGraph.py
If we want disabled blocks to be updated properly,
we have to consider all blocks when updating the fg not only the enabled.
This does the patch of Flowgraph.py and fixes #4788.
But a problem remains.
If you use the example in #4788 and disable the symbol_rate block,
only the samp_rate block 'turns to red'.
The other blocks don't change.
Only if you open and close an arbitrary block, the other blocks are updated.
This is fixed by clearing the namespace in renew_namespace in FlowGraph.py.
grc: update disabled blocks
(cherry picked from commit fbab6c383d6f86ab0de42a90a9182d22637a5b96)
Backport …
=> grc: update disabled blocks if they depend on others (backport to maint-3.8)

gr-blocks/lib/pack_k_bits_bb_impl.cc, gr-blocks/lib/pack_k_bits_bb_impl.h, gr-blocks/python/blocks/qa_pack_k_bits.py, gr-blocks/python/blocks/qa_unpack_k_bits.py
backport to 3.9 from https://github.com/gnuradio/gnuradio/pull/4863
=> gr-blocks: (un)pack-k-bits tag propagation Bugfix #1111 (backport to maint-3.9)

gr-utils/CMakeLists.txt, grc/CMakeLists.txt
A string-based '>=" only works for single digit version numbers. It turns out that there is already a macro set up to do correct version checking - it was just not being used.
Fixes https://github.com/gnuradio/gnuradio/issues/4727
=> cmake: correct minimum version checking for Mako

gr-analog/grc/analog_const_source_x.block.yml, grc/core/Constants.py, grc/core/params/param.py
Add short and byte to valid param type names and param value handler. Also replace stray bad type in const_source yml.
Fixes https://github.com/gnuradio/gnuradio/issues/4868
=> grc: allow short and byte as valid types in an enum

gr-blocks/examples/CMakeLists.txt, gr-blocks/examples/matrix_interleaver.grc, gr-blocks/grc/blocks.tree.yml, gr-blocks/grc/blocks_matrix_interleaver.block.yml, gr-blocks/python/blocks/CMakeLists.txt, gr-blocks/python/blocks/__init__.py, gr-blocks/python/blocks/matrix_interleaver.py, gr-blocks/python/blocks/qa_matrix_interleaver.py
* blocks: add matrix interleaver block
Matrix interleaver including qa test and example
The matrix interleaver is a hierarchical block that pairs a base
deinterleave block that effectively writes samples into "rows" (1 block of
samples per output) and a base interleave block that outputs samples
iteratively from each input like  "columns".
Signed-off-by: Jared Dulmage <jared.dulmage@caliola.com>
Add grc file and update blocks.tree.yml.
Fix module for matrix interleaver example
Signed-off-by: Jared Dulmage <jared.dulmage@caliola.com>
* Update py file docs and license block
Co-authored-by: Jared Dulmage <jared.dulmage@caliola.com>
(cherry picked from commit 15a8cce4dadaa895081d1d9816f37e65117cffb5)
Backport …
=> blocks: add matrix interleaver block (backport to maint-3.9)

gr-blocks/lib/tagged_file_sink_impl.cc, gr-digital/lib/burst_shaper_impl.cc, gr-digital/lib/header_payload_demux_impl.cc, gr-digital/lib/symbol_sync_cc_impl.cc, gr-digital/lib/symbol_sync_ff_impl.cc, gr-uhd/lib/usrp_sink_impl.cc
Backport https://github.com/gnuradio/gnuradio/pull/4915
=> Remove sorting of tag vectors where already sorted (backport to maint-3.9)

gr-analog/grc/analog_const_source_x.block.yml, grc/core/Constants.py, grc/core/params/param.py
(cherry picked from commit 256953bebab151c50fd9a32156f75d2aabc14c17)
Backport https://github.com/gnuradio/gnuradio/pull/4876
=> grc: allow short and byte as valid types in an enum (backport to maint-3.8)

gr-analog/grc/analog_const_source_x.block.yml, grc/core/Constants.py, grc/core/params/param.py
(cherry picked from commit 256953bebab151c50fd9a32156f75d2aabc14c17)
Backport https://github.com/gnuradio/gnuradio/pull/4876
=> grc: allow short and byte as valid types in an enum (backport to maint-3.9)

gr-blocks/grc/blocks_throttle.block.yml, gr-blocks/include/gnuradio/blocks/throttle.h, gr-blocks/lib/throttle_impl.cc, gr-blocks/python/blocks/bindings/throttle_python.cc
Backport https://github.com/gnuradio/gnuradio/pull/4793
=> blocks: Throttle consume-only mode (backport to maint-3.9)

gr-utils/CMakeLists.txt, grc/CMakeLists.txt
A string-based '>=" only works for single digit version numbers.
(cherry picked from commit 8dc130ab8f2a617071adada9192aeba807f31565)
Backport https://github.com/gnuradio/gnuradio/pull/4880
=> cmake: correct minimum version checking for Mako (backport to maint-3.9)

cmake/Modules/Findlibunwind.cmake
The `libfind_process macro` expects `<lib>_PROCESS_INCLUDES` to be set to the names of variables containing the include paths, not the include paths themselves. This was causing `find_package(libunwind)` to always fail, even when the necessary files were correctly found by `find_path` and `find_library`.
It looks like this typo has existed since libunwind support was first added in #3051. As such, it is likely that not too many people have exercised the libunwind code, and fixing this may surface other issues. It does compile and successfully links libunwind. I'll go crash some stuff and let you know what I see.
=> cmake: Fix finding libunwind

gr-utils/python/modtool/templates/gr-newmod/python/__init__.py
Backport 08cd88d but maintain compatibility with Python2.
Backport https://github.com/gnuradio/gnuradio/pull/3926
Fixes https://github.com/gnuradio/gnuradio/issues/4761 for v3.8
=> modtool: Change handled exception to ModuleNotFoundError (backport to maint-3.8)

cmake/Modules/Findlibunwind.cmake
The libfind_process macro expects <lib>_PROCESS_INCLUDES to be set to
the names of variables containing the include paths, not the include
paths themselves.  This was causing find_package(libunwind) to always
fail, even when the necessary files were correctly found by find_path
and find_library.
Signed-off-by: Pavon <pavon@protonmail.com>
(cherry picked from commit cd4a47de989ca83e31a48661673b1e12ca417502)
Backport https://github.com/gnuradio/gnuradio/pull/4904
=> cmake: Fix finding libunwind (backport to maint-3.9)

gr-digital/lib/constellation_receiver_cb_impl.cc
Removes tag_checker
Improves performance
(cherry picked from commit 52b05f80176eb108c62a517e27e4ae6471d5e2b8)
Backport https://github.com/gnuradio/gnuradio/pull/4911
=> digital: constellation_receiver_cb rework (backport to maint-3.9)

gr-digital/grc/digital_gfsk_mod.block.yml, gr-digital/python/digital/gfsk.py
Provide the option to not use the packed_to_unpacked block in the gfsk
mod hier block so that the latter can be used to modulate
non-byte-aligned bit stream.
The option enables packed_to_unpacked by default for backward
compatibility.
(cherry picked from commit 9c388da6571ca7605b78f519c23778b0d604abfc)
Backport https://github.com/gnuradio/gnuradio/pull/4940
=> gfsk: Make packed_to_unpacked optional (backport to maint-3.9)

gr-blocks/examples/CMakeLists.txt, gr-blocks/examples/matrix_interleaver.grc, gr-blocks/grc/blocks.tree.yml, gr-blocks/grc/blocks_matrix_interleaver.block.yml, gr-blocks/python/blocks/CMakeLists.txt, gr-blocks/python/blocks/__init__.py, gr-blocks/python/blocks/matrix_interleaver.py, gr-blocks/python/blocks/qa_matrix_interleaver.py
This PR is with respect to the matrix interleaver block discussed in [Issue 3637](https://github.com/gnuradio/gnuradio/issues/3637#issuecomment-841628354).
This matrix interleaver is a python hierarchical block that uses the base deinterleaver and interleaver blocks internally, so it's quasi-c++. This is also 3.8-specific, again perhaps easily ported to 3.9 due to being hierarchical.
The PR also includes an example grc and simple test case.
Backport https://github.com/gnuradio/gnuradio/pull/4861
=> Matrix Interleaver block (backport to maint-3.8)

gr-digital/python/digital/generic_mod_demod.py
Skiphead requires an integer number of samples, but was being called
with a float parameter.
Fixes https://github.com/gnuradio/gnuradio/issues/4908
=> digital: add int() cast where required

gr-digital/python/digital/generic_mod_demod.py
Skiphead requires an integer number of samples, but was being called
with a float parameter.
(cherry picked from commit 11255ca436e6e3eff56fcc995e1b72cff289c90b)
Backport https://github.com/gnuradio/gnuradio/pull/4953
=> digital: add int() cast where required (backport to maint-3.9)

gr-analog/grc/analog_fastnoise_source_x.block.yml, gr-blocks/grc/blocks_ctrlport_probe2_c.block.yml, gr-blocks/grc/blocks_ctrlport_probe2_x.block.yml, gr-blocks/grc/blocks_packed_to_unpacked_xx.block.yml, gr-blocks/grc/blocks_repack_bits_bb.block.yml, gr-digital/grc/digital_corr_est_cc.block.yml, gr-digital/grc/digital_cpmmod_bc.block.yml, gr-digital/grc/digital_diff_decoder_bb.block.yml, gr-digital/grc/digital_diff_encoder_bb.block.yml, gr-digital/grc/digital_symbol_sync_xx.block.yml, gr-fft/grc/fft_fft_vxx.block.yml, gr-pdu/grc/pdu_pdu_to_tagged_stream.block.yml
Translations are a regex, so "." needs to be escaped. Fix the
remaining unescaped strings.
Fixes https://github.com/gnuradio/gnuradio/issues/4754
=> c++ generation: escape "." in translations

gr-analog/grc/analog_fastnoise_source_x.block.yml, gr-blocks/grc/blocks_ctrlport_probe2_c.block.yml, gr-blocks/grc/blocks_ctrlport_probe2_x.block.yml, gr-blocks/grc/blocks_packed_to_unpacked_xx.block.yml, gr-blocks/grc/blocks_pdu_to_tagged_stream.block.yml, gr-blocks/grc/blocks_repack_bits_bb.block.yml, gr-digital/grc/digital_corr_est_cc.block.yml, gr-digital/grc/digital_cpmmod_bc.block.yml, gr-digital/grc/digital_diff_decoder_bb.block.yml, gr-digital/grc/digital_diff_encoder_bb.block.yml, gr-digital/grc/digital_symbol_sync_xx.block.yml, gr-fft/grc/fft_fft_vxx.block.yml
Translations are a regex, so "." needs to be escaped. Fix the
remaining unescaped strings.
(cherry picked from commit 7a9f2f5ce7071f7863d615143a2568e5b892e250)
Backport https://github.com/gnuradio/gnuradio/pull/4954
=> c++ generation: escape "." in translations (backport to maint-3.9)

gr-qtgui/grc/qtgui_check_box.block.yml, gr-qtgui/grc/qtgui_freq_sink_x.block.yml, gr-qtgui/grc/qtgui_number_sink.block.yml, gr-qtgui/grc/qtgui_sink_x.block.yml, gr-qtgui/grc/qtgui_waterfall_sink_x.block.yml
This is required for compatibility with Ubuntu 18.04 LTS.
=> gr-qtgui: Add double quotes to cpp_opts keys with colons.

gr-digital/grc/digital_chunks_to_symbols.block.yml
Before:
After:
The block doesn't have a message output port.
=> digital: remove non-existing msg output from chunks_to_symbols block yaml

gr-digital/include/gnuradio/digital/chunks_to_symbols.h, gr-digital/lib/chunks_to_symbols_impl.cc, gr-digital/lib/chunks_to_symbols_impl.h, gr-digital/python/digital/bindings/chunks_to_symbols_python.cc, gr-digital/python/digital/qa_chunks_to_symbols.py, gr-digital/python/digital/qa_constellation.py
The block formerly took the tags from `get_tags_in_range` (which are sorted),
gave them to `tag_checker`, which sorted them, and then went through every
input sample, checking its index against the next tag.
Removed the tag_checker; that saves us a sorting of a sorted vector per work call.
The other optimization is to not dispatch any tag encountered to the own
message handler; instead, the handler is called directly.
Found #4898 while doing this.
=> digital/chunks to symbols: be less inefficient

gr-iio/lib/device_source_impl.cc, gr-iio/lib/fmcomms2_sink_impl.cc, gr-iio/lib/fmcomms2_source_impl.cc
pluto source / sink fails to set hardwaregain with
gr::log :WARN: iio::device::set_params - Unable to write attribute in_voltage0_hardwaregain: -22
gr::log :WARN: iio::device::set_params - Unable to write attribute out_voltage0_hardwaregain: -22
gain values are treated as double. The conversion std::to_string() uses the locale setting.
So in the US std::to_string(10.) leads to "10.0" while in Germany the result is "10,0" which the pluto handles as error.
Forcing LC_NUMERIC to "C" fixes this issue.
=> gr-iio: pluto source /sink fails to set paramter if german locale is used

gr-digital/grc/digital_chunks_to_symbols.block.yml
digital: remove non-existing msg output from chunks_to_symbols block yaml
(cherry picked from commit 3a1e6e689bccb6016e5129cd1a3c8f6da6b11424)
Backport https://github.com/gnuradio/gnuradio/pull/4903
=> digital: remove non-existing msg output from chunks_to_symbols block yaml (backport to maint-3.8)

gr-digital/grc/digital_chunks_to_symbols.block.yml
digital: remove non-existing msg output from chunks_to_symbols block yaml
(cherry picked from commit 3a1e6e689bccb6016e5129cd1a3c8f6da6b11424)
Backport https://github.com/gnuradio/gnuradio/pull/4903
=> digital: remove non-existing msg output from chunks_to_symbols block yaml (backport to maint-3.9)

gr-qtgui/grc/qtgui_check_box.block.yml, gr-qtgui/grc/qtgui_freq_sink_x.block.yml, gr-qtgui/grc/qtgui_number_sink.block.yml, gr-qtgui/grc/qtgui_sink_x.block.yml, gr-qtgui/grc/qtgui_waterfall_sink_x.block.yml
This is required for compatibility with Ubuntu 18.04 LTS.
(cherry picked from commit 0855db230e389c97ce9703b90cf97c2c2e45da9f)
Backport https://github.com/gnuradio/gnuradio/pull/4938
=> gr-qtgui: Add double quotes to cpp_opts keys with colons. (backport to maint-3.9)

docs/doxygen/update_pydoc.py, gr-utils/modtool/templates/gr-newmod/docs/doxygen/update_pydoc.py
Remove the annoying 'output docstrings to {path}' message.
Hopefully, this is no longer needed, otherwise, I'll try to make a 'verbose' compile-time option.
=> pybind11: remove debug message

gr-uhd/examples/python/freq_hopping.py
Signed-off-by: Adrien Michel <adriengit@users.noreply.github.com>
(cherry picked from commit b538984ef32c20825a88a10e388039984abeaaa2)
Backport #4980
=> gr-uhd: fix input filename in freq hopping examples (backport to maint-3.8)

gr-uhd/examples/python/freq_hopping.py
Signed-off-by: Adrien Michel <adriengit@users.noreply.github.com>
(cherry picked from commit b538984ef32c20825a88a10e388039984abeaaa2)
Backport https://github.com/gnuradio/gnuradio/pull/4980
=> gr-uhd: fix input filename in freq hopping examples (backport to maint-3.9)

gnuradio-runtime/include/gnuradio/logger.h, gnuradio-runtime/python/gnuradio/gr/bindings/logger_python.cc
Based on email discussion with Boris Marjanovic.
Logging is being overhauled on master branch, so this is being introduced directly to maint-3.9.
The logging macros always pass the "msg" param to the logger (currently
log4cpp). In the macros, "msg" can be an expression and it will be
evaluated, even if the log message would not be printed (based on log
level).
This commit adds checks to each macro to check whether the message will be
logged. Since this check is also done internally to log4cpp, some
duplication results, but it should be far less effort than evaluating
an arbitrary "msg".
=> runtime: logging performance improvement

grc/core/FlowGraph.py, grc/gui/Application.py
The gr-digital/examples/tx_ofdm.grc fails to evaluate the
header_formater variable.
Fixes #4937
=> grc: Sometimes the evaluation of a variable fails

grc/core/FlowGraph.py, grc/gui/Application.py
The gr-digital/examples/tx_ofdm.grc fails to evaluate the
header_formater variable.
This pr fixes #4937
(cherry picked from commit 1f1733eb4489b48fb73509e7806df19e1c738092)
Backport https://github.com/gnuradio/gnuradio/pull/4949
=> grc: fix the evaluation of interdependent variables (backport to maint-3.9)

grc/core/FlowGraph.py, grc/gui/Application.py
The gr-digital/examples/tx_ofdm.grc fails to evaluate the
header_formater variable.
This pr fixes #4937
(cherry picked from commit 1f1733eb4489b48fb73509e7806df19e1c738092)
Backport https://github.com/gnuradio/gnuradio/pull/4949
=> grc: fix the evaluation of interdependent variables (backport to maint-3.8)

grc/core/platform.py, grc/main.py
This is an update for PR #2424. The extra debug output from GRC was
being generated by another logger instance in grc/core/platform that
did not respect the command line arguments.
This removes the extra logger and sets the logger level in main to
whatever is requested from the command line. See grc/main.py:43 for more
detail.
(cherry picked from commit 43eac48b42c781c66b56279ff76e1b3d401f2753)
Backport https://github.com/gnuradio/gnuradio/pull/3767
=> grc: Remove extra logger in grc/core/platform (backport to maint-3.9)

gr-filter/grc/filter_root_raised_cosine_filter.block.yml
The rrc block has no parameter type.fcn, which is wrongly  used in cpp code generation
but not in python code generation.
=> gr-filter: cpp code genration fails for root raised cosine filter

gr-blocks/tests/benchmark_nco.cc, gr-blocks/tests/benchmark_vco.cc
Fix provided by Gisle Vanem (@gvanem)
Fixes https://github.com/gnuradio/gnuradio/issues/4995
=> gr-blocks: use correct namespace for nco and vco in benchmarks

gr-digital/grc/digital_gmsk_mod.block.yml, gr-digital/python/digital/gmsk.py
Allow the unpack option to be disabled for custom, non-byte-aligned bit
streams in gmsk mod, just like how it was done for gfsk in #4940.
=> gr-digital: Make unpack optional for gmsk mod hier block

.packaging/debian/control
I've just tried to run `gnuradio-companion` from GR 3.9.2 installed via binary package from `ppa:gnuradio/gnuradio-releases`. I tried it on a Docker environment and ran into the following error:
```
> gnuradio-companion
File "/usr/bin/gnuradio-companion", line 49, in check_gtk
gi.require_version('Gtk', '3.0')
File "/usr/lib/python3/dist-packages/gi/__init__.py", line 129, in require_version
raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gtk not available
During handling of the above exception, another exception occurred:
File "/usr/bin/gnuradio-companion", line 90, in <module>
check_gtk()
File "/usr/bin/gnuradio-companion", line 57, in check_gtk
die(err, "Failed to initialize GTK. If …
```
=> pkg: Add gir1.2-gtk-3.0 to the Debian list of runtime dependencies

gr-filter/grc/filter_root_raised_cosine_filter.block.yml
The rrc block has no parameter type.fcn, which is wrongly  used in cpp code generation
but not in python code generation.
(cherry picked from commit 7b10a9ebf5b5bace7f2fedaabf7e8999ceb3d519)
Backport https://github.com/gnuradio/gnuradio/pull/4967
=> gr-filter: cpp code genration fails for root raised cosine filter (backport to maint-3.9)

CMakeLists.txt, grc/CMakeLists.txt
The check checked for one version and reported another.
=> grc/cmake: Improve pyyaml check (forward port from 3.9)

grc/core/generator/cpp_hier_block.py
The following issues are fixed for the cpp hier block parameter yaml
template generation.
1. The key of the `data` dictionary containing the parameters should be
`parameters` instead of `param`.
2. Fix the yaml template for the parameter to generate `${param}`
instead of `$param` in the yaml file.
Changes made as part of the effort for #4944 .
=> grc: Fix cpp hier param yaml template

.packaging/debian/control
It seems that package gir1.2-gtk-3.0 is a required runtime dependency
for running gnuradio-companion. Add it to the Debian package's list of
runtime dependencies.
(cherry picked from commit fd504fa26f71662ce4ddd4c8608722748e9beb86)
Backport https://github.com/gnuradio/gnuradio/pull/5015
=> pkg: Add gir1.2-gtk-3.0 as deb runtime dependency (backport to maint-3.9)

grc/core/generator/cpp_hier_block.py
The following issues are fixed for the cpp hier block parameter yaml
template generation.
1. The key of the `data` dictionary containing the parameters should be
`parameters` instead of `param`.
2. Fix the yaml template for the parameter to generate `${param}`
instead of `$param` in the yaml file.
(cherry picked from commit a6fbb06a18a3ce0253dd8c9d714f5e96aa9e4c4e)
Backport https://github.com/gnuradio/gnuradio/pull/4951
=> grc: Fix cpp hier param yaml template (backport to maint-3.9)

gr-video-sdl/lib/sink_s_impl.cc, gr-video-sdl/lib/sink_uc_impl.cc
(backported from 314a870085)
Backport https://github.com/gnuradio/gnuradio/pull/4992
=> gr-video-sdl: Fix reversal of U and V channels on sink blocks (backport to maint-3.8)

gr-video-sdl/lib/sink_s_impl.cc, gr-video-sdl/lib/sink_uc_impl.cc
(cherry picked from commit 314a87008559a04b911d9ed8fc77cb0c35d6f383)
Backport https://github.com/gnuradio/gnuradio/pull/4992
=> gr-video-sdl: Fix reversal of U and V channels on sink blocks (backport to maint-3.9)

gr-audio/lib/jack/jack_sink.cc, gr-audio/lib/jack/jack_source.cc
(cherry picked from commit 883315208853121a8dfa68ae9c2f74400acd5ac5)
Backport https://github.com/gnuradio/gnuradio/pull/5010
=> audio/jack: to_string is no longer part of boost:: NS, instead use std:: (backport to maint-3.8)

gr-audio/lib/jack/jack_sink.cc, gr-audio/lib/jack/jack_source.cc
(cherry picked from commit 883315208853121a8dfa68ae9c2f74400acd5ac5)
Backport https://github.com/gnuradio/gnuradio/pull/5010
=> audio/jack: to_string is no longer part of boost:: NS, instead use std:: (backport to maint-3.9)

gr-blocks/tests/benchmark_nco.cc, gr-blocks/tests/benchmark_vco.cc
Fix provided by Gisle Vanem (@gvanem)
(cherry picked from commit bfde34493e9e4216b6096cadda8236573cf36f0d)
Backport https://github.com/gnuradio/gnuradio/pull/4997/files
=> gr-blocks: use correct namespace for nco and vco in benchmarks (backport to maint-3.9)

gr-digital/grc/digital_gfsk_demod.block.yml, gr-digital/grc/digital_gmsk_demod.block.yml, gr-digital/python/digital/gfsk.py, gr-digital/python/digital/gmsk.py
Fixes #4962. However, I have no idea what kind of test would prove that its performance is the same as the Clock Recovery MM block.
As Clock Recovery MM is deprecated, this commit replaces them
in the hier blocks, gmfsk demod and gfsk demod, with Andy Wall's Symbol
Sync block. Backward compatibility is maintained by keeping the
parameters unchanged, and converting the two gain values to the
corresponding loop bandwidth value that Symbol Sync requires.
**Note:** This means the `mu` parameter is no longer needed. Should I leave it in or take it out? I left it in for backward compatibility, but any value entered in the block will have no impact on the demod block.
My derivation:
=> gr-digital: replace clk recovery MM in hier blks

grc/core/blocks/_build.py, grc/core/generator/FlowGraphProxy.py, grc/core/generator/cpp_templates/CMakeLists.txt.mako, grc/core/generator/cpp_top_block.py, grc/core/schema_checker/block.py
Flowgraphs may use oot modules. When generating cpp code an oot module
may require a package that is not provided by gnuradio.
So I propose to add an additional entry parameters in the cpp template
to provide a list of package names and add the corresponding find package calls to CMakeLists.txt
=> grc cpp generation: Establish the possibility to add find packages

grc/core/generator/cpp_templates/flow_graph.hpp.mako
gnuradio >= 3.9 uses std::shared_ptr instead of boost::shared_ptr
This is fixed here. See discussion in #4951 , too
=> grc: generate cpp hier code switch to std::shared_ptr

grc/core/generator/cpp_templates/flow_graph.hpp.mako
gnuradio >= 3.9 uses std::shared_ptr instead of boost::shared_ptr
This is fixed here. See too: #4951
(cherry picked from commit ed4cc57c043741d43dfa071770bdf3b78821ba54)
Backport https://github.com/gnuradio/gnuradio/pull/5036
=> grc: generate cpp hier code switch to std::shared_ptr (backport to maint-3.9)

grc/core/blocks/_build.py, grc/core/generator/FlowGraphProxy.py, grc/core/generator/cpp_templates/CMakeLists.txt.mako, grc/core/generator/cpp_top_block.py, grc/core/schema_checker/block.py
Flowgraphs may use oot modules. When generating cpp code an oot module
may require a package that is not provided by gnuradio.
So I propose to add an additional entry parameters in the cpp template
to provide a list of package names.
(cherry picked from commit b417716a0a6e686d189596ffdaab1e4b8e9679b7)
Backport https://github.com/gnuradio/gnuradio/pull/4972
=> grc cpp generation: Establish the possibility to add find packages (backport to maint-3.9)

gr-digital/grc/digital_gfsk_demod.block.yml, gr-digital/grc/digital_gmsk_demod.block.yml, gr-digital/python/digital/gfsk.py, gr-digital/python/digital/gmsk.py
As Clock Recovery MM is deprecated, this commit replaces them
in the hier blocks, gmfsk demod and gfsk demod, with Andy Wall's Symbol
Sync block. Backward compatibility is maintained by keeping the
parameters unchanged, and converting the two gain values to the
corresponding loop bandwidth value that Symbol Sync requires.
Note: This means the mu parameter is no longer needed.
Backport https://github.com/gnuradio/gnuradio/pull/4969/commits
=> gr-digital: replace clk recovery MM in hier blks (backport to maint-3.9)

gr-filter/lib/pfb_arb_resampler_ccc_impl.cc, gr-filter/lib/pfb_arb_resampler_ccf_impl.cc, gr-filter/lib/pfb_arb_resampler_fff_impl.cc
When interpolating, the resampler was taking up a full cpu even
at very low rates. This is due to polling when no input items are
available.
For interpolation, this change sets the output multiple to the greater
of the relative rate and the number of pfb filter arms. This is fairly
arbitrary, but results in usable output multiples and good performance.
The output multiple can only be set effectively in the block constructor.
This means that it will not change if the relative rate is set
dynamically. For widely varying rates, this could be a problem. For
rates that vary around 1.0, if the rate is initially set to 0.9 and
then changed to 1.1, performance will be as before (bad) when the rate
goes above 1.0. For this reason, and in hopes that the user will start
with 1.0 in such a case, the …
=> filter: use output multiple for pfb arbitrary resampler (backport to maint-3.9)

grc/core/blocks/_templates.py
Lots of C++-enabled blocks (especially in gr-digital and gr-filter) do a substring operation in order to get rid of quotes, like the FIR Filter block:
https://github.com/gnuradio/gnuradio/blob/1f1733eb4489b48fb73509e7806df19e1c738092/gr-filter/grc/filter_fir_filter_xxx.block.yml#L55
It's neither pretty nor robust, and they would benefit from having the quotes-stripping operation available as a function. It would be easier to just do `std::vector<gr_complex> taps = {${no_quotes(taps)}}; `
This PR adds such a function to the Mako template namespace, so that it can be used from all templates. This will also be useful for the XMLRPC block: https://github.com/gnuradio/gnuradio/pull/5008
=> grc: Add no_quotes() convenience function (callable from templates)

grc/core/blocks/_templates.py
(cherry picked from commit 774d30d66afdab0c16d9239d84e5829187f791c4)
Backport https://github.com/gnuradio/gnuradio/pull/5016
=> grc: Add no_quotes() convenience function (callable from templates) (backport to maint-3.8)

gr-network/lib/tuntap_pdu_impl.cc
with -Werror, this became a problem (stopped builds under Debian 11).
Since we're setting the last byte to zero in the caller of this function, the truncation happens, if at all, there, not here.
=> network: tuntap knows what it's doing when it uses strncpy, suppress warning

grc/core/blocks/_templates.py
Not compatible with Python2 - missed that one.
Reverts gnuradio/gnuradio#5046
=> Revert "grc: Add no_quotes() convenience function (callable from templates) (backport to maint-3.8)"

gr-digital/lib/constellation.cc, gr-digital/python/digital/qa_constellation.py
Correct power normalization calculation.
Add a qa test for amplitude and power normalization.
Signed-off-by: David Pi <david.pinho@gmail.com>
(cherry picked from commit 0a4225dc9dd9e4d3c5ad58d40570d40d59f5670f)
Backport https://github.com/gnuradio/gnuradio/pull/4909
=> gr-digital: Fix constellation normalization by average power (backport to maint-3.9)

gr-blocks/lib/tuntap_pdu_impl.cc
(cherry picked from commit 4c6ae3a386ec19698a8c01144c4e8a52fc113404)
Backport https://github.com/gnuradio/gnuradio/pull/5011
=> network: tuntap knows what it's doing when it uses strncpy, suppress warning (backport to maint-3.9)

gr-digital/grc/digital_symbol_sync_xx.block.yml
Signed-off-by: Rohan Sharma <rhnsharma5113@gmail.com>
(cherry picked from commit 18689424bcb3581f29c5b18f85cd45107c6827b7)
Backport https://github.com/gnuradio/gnuradio/pull/5014
=> digital: replace likelyhood with likelihood (backport to maint-3.9)

gr-digital/grc/digital_symbol_sync_xx.block.yml
Signed-off-by: Rohan Sharma <rhnsharma5113@gmail.com>
(cherry picked from commit 18689424bcb3581f29c5b18f85cd45107c6827b7)
Backport https://github.com/gnuradio/gnuradio/pull/5014
=> digital: replace likelyhood with likelihood (backport to maint-3.8)

gr-digital/lib/chunks_to_symbols_impl.cc, gr-digital/lib/chunks_to_symbols_impl.h, gr-digital/python/digital/qa_chunks_to_symbols.py, gr-digital/python/digital/qa_constellation.py
This is essentially an exact replication of the patchset from #4901, but does not change the exported signature in the public header.
=> digital/chunks to symbols: be less inefficient (backport to maint-3.9)

CMakeLists.txt
Fix provided in issue by jwmelto
Fixes https://github.com/gnuradio/gnuradio/issues/5054
=> cmake: include GrBoost after (was before) version restriction

.github/workflows/make-test.yml
Since autobuild was disabled for Docker Hub and free plans, this ties in
more easily with the GitHub integration.
=> github: Use GH container registry instead of Docker Hub

.github/workflows/make-test.yml, .github/workflows/pkg-fedora.yml
this has the main advantage of bringing UHD4, so we can test more of gr-uhd.
Replaces https://github.com/gnuradio/gnuradio/pull/4935, which I accidentally auto-closed.
=> CI: Update the Fedora Container to F34

.github/workflows/make-test.yml, .github/workflows/pkg-debian.yml, .github/workflows/pkg-fedora.yml
This is to keep in lockstep with maint-3.9; this allows to run with
in-tree `[[deprecated]]`-marked functionality, and with current ZMQ,
which otherwise makes Fedora fail.
=> Github CI: enable -Werror on fedora, but don't error on deprecations

gnuradio-runtime/include/gnuradio/pdu.h, gnuradio-runtime/lib/pdu.cc, gnuradio-runtime/python/gnuradio/gr/bindings/docstrings/pdu_pydoc_template.h, gnuradio-runtime/python/gnuradio/gr/bindings/pdu_python.cc, gr-pdu/lib/tags_to_pdu_impl.cc
This was omitted accidentally, but is necessary in general for correct processing of PDU data
=> pdu: add samp_rate key

.github/workflows/make-test.yml
This makes the ctest args configurable per-container. The Debian 11
ctest args now disable qa_polar_decoder_sc_systematic because it seems
the VOLK version shipped therein has an issue.
=> ci: Allow per-container ctest args

gr-qtgui/grc/qtgui_number_sink.block.yml
Number Sink takes a size, rather than a type, and does not support int32.
It assumes items of size 4 are floats.
Stopgap fix for https://github.com/gnuradio/gnuradio/issues/5056
=> qtgui: remove int type from number_sink block yaml

grc/core/params/param.py
Fixes #5032 .
Issue 5032 results from an unfilled parameter erroneously indicated as
filled with a default value of 0. This PR makes grc indicate an error
when there is an unfilled parameter by returning None.
=> grc: Raise error for unfilled parameters

grc/compiler.py, grc/core/generator/Generator.py, grc/core/generator/cpp_top_block.py, grc/core/generator/hier_block.py, grc/core/generator/top_block.py, grc/core/platform.py
Reference Issue #2799.
This commit adjusts some logic and code to enable the --output switch
for grcc. Prior to this commit, grcc would only output to the GRC_HIER_PATH.
The commit adjusts the various Generators in grc/core/generator to
consistently use output_dir for the output directory.
If output_dir is None, then take from the platform.config.hier_block_lib_dir
attribute which can be set via the GRC_HIER_PATH env var.
The cpp_top_block generator was also modified to remote its __init__ function
which appeared identical to its base TopBlockGenerator.
I did not test c++ GRC output.
=> Implement grcc --output switch for hierarchical blocks

gnuradio-runtime/python/gnuradio/gr/bindings/block_gateway_python.cc, gr-blocks/python/blocks/qa_block_gateway.py
Fix issue where get_tags_in_window was bound to and consequently had the
same behavior as get_tags_in_range
Fixes #5005
Signed-off-by: Josh Morman <jmorman@peratonlabs.com>
get_tags_in_window in the python bindings was bound to the wrong method
Fixes #5005 
All python blocks that use get_tags_in_window
=> runtime: fix pybind of get_tags_in_window

grc/gui/BlockTreeWindow.py
Category and module tooltips have been broken since GNU Radio 3.8. The `_format_cat_tooltip` function expects a tuple representing the module & category hierarchy, but a single string is passed in. As a result, everyhing is treated as a category, and only the last letter of the category or module name is displayed. I've fixed the problem by passing in the full tuple instead.
Before:
After:
=> grc: Fix category and module tooltips

gr-qtgui/lib/freq_sink_f_impl.cc
Signed-off-by: Josh Morman <jmorman@peratonlabs.com>
When the fft object is instantiated in qt gui freq sink (float), there is a `true` parameter that is interpreted as nthreads, but is really left over when the object was instantiated with bool as the forward rather than templated
This shouldn't affect any functionality, but is just a minor cleanup of the instantiation of this one object to remove confusion.
Verified that qt gui freq sink still works
=> qtgui: remove vestigal parameter in fft cotr

grc/core/Constants.py
When type checking was added for GRC connections, the valid connections between a block with the "sc16" type (e.g. UHD blocks) and a block with the "short" type and a vector length of 2 (e.g. ishort->complex) now fail. Adding these aliases fixes that as a stop-gap until a better solution can be found.
Fixes #4998. See further discussion on this subject in #5001.
=> grc: Add aliases for "sc16==short" and "sc8==byte"

gnuradio-runtime/include/gnuradio/buffer_double_mapped.h, gnuradio-runtime/include/gnuradio/buffer_single_mapped.h, gnuradio-runtime/include/gnuradio/host_buffer.h
=> gnuradio-runtime: Remove Doxygen warnings from custom buffers

README.md
It does not appear like the buildbot at ci.gnuradio.org is avialable
anymore. The README.md rendering looks odd with broken image and links.
Therefore I think we can just remove it as I think buildbot has been
ditched a long time ago by now in favor of Github Actions.
This then adds the Github workflow status badge with a link to the
status page.
Signed-off-by: Nick Østergaard <oe.nick@gmail.com>
(cherry picked from commit eab2ea6102fd7c84c9fd507b983698aa187df83b)
Backport https://github.com/gnuradio/gnuradio/pull/5245
=> Remove broken buildbot links in README badge line (backport to maint-3.9)

cmake/Modules/GrVersion.cmake
After the recent change to use `string(REGEX REPLACE ...)` to ensure
that only numeric values are used for RC_*_VERSION, an unset
VERSION_PATCH now results in a cmake failure when it didn't previously.
While we should expect all 4 version fields to be set (except when one
of the values is "git"), we should also avoid failing here when it
worked before. At least one OOT (gr-satellites) doesn't set the
VERSION_PATCH field for releases, so this fixes the build in that case
without requiring OOT changes. Now an unset VERSION_PATCH defaults to
"0".
(cherry picked from commit e79cc19b87a9976d1cb44a4c315b59cc90ebdbf8)
Backport https://github.com/gnuradio/gnuradio/pull/5146
=> cmake: Fix cmake failure with unset VERSION_PATCH (backport to maint-3.9)

gnuradio-runtime/include/gnuradio/buffer.h, gnuradio-runtime/include/gnuradio/buffer_double_mapped.h, gnuradio-runtime/include/gnuradio/buffer_single_mapped.h, gnuradio-runtime/include/gnuradio/host_buffer.h, gnuradio-runtime/python/gnuradio/gr/bindings/buffer_python.cc
found with 
```
run-clang-tidy -header-filter='.*' -checks='-*,misc-throw-by-value-catch-by-reference,misc-static-assert,readability-container-size-empty,modernize-use-override,modernize-make-unique,modernize-deprecated-headers,misc-unused-using-decls,misc-redundant-expression' -fix
```
runtime, buffers - the whole codebase
CI should be sufficient
=> runtime: mark buffer methods as override

CMakeLists.txt, gr-utils/blocktool/core/parseheader_generic.py
Updates the call to pygccxml that is invoked when `gr_modtool bind` is called to use -std c++17
Has minimum version check on pygccxml since the tool is now useless anything below 2.0.0 because we use c++17
Fixes #5281
gr_modtool
rebuilt the gnuradio codebase with and without pygccxml installed
created an oot module with a block and ran gr_modtool bind
=> modtool: update pygccxml to c++17 std, add pygccxml version check

CMakeLists.txt, gr-utils/blocktool/core/parseheader_generic.py
Backport https://github.com/gnuradio/gnuradio/pull/5288. Adjust versions for v3.9.
=> modtool: update pygccxml to c++14 std, add pygccxml version check (backport to maint-3.9 with changes)

gnuradio-runtime/python/gnuradio/gr/hier_block2.py
gnuradio-runtime: hier_block2.py __getattr__ recursive loop bug fix #5072
Signed-off-by: Matt Mills <mmills@2bn.net>
(cherry picked from commit 4457eb145b8078614da1d4b64add6282e4ab8d5d)
Backport https://github.com/gnuradio/gnuradio/pull/5153
=> gr-runtime: Change hier_block2.py __getattr__ to avoid recursive loop in exception (backport to maint-3.8)

grc/gui/canvas/block.py
font size was being imported incorrectly resulting in the default font size always being used for comments (#5088)
Signed-off-by: chris <christopher.donohue@gmail.com>
(cherry picked from commit cda1e63d9b1c136e43993075c00bb11925fa3c36)
Backport https://github.com/gnuradio/gnuradio/pull/5088
=> grc: block comment font size incorrect, ignoring config file (backport to maint-3.8)

README.md
It does not appear like the buildbot at ci.gnuradio.org is avialable
anymore. The README.md rendering looks odd with broken image and links.
Therefore I think we can just remove it as I think buildbot has been
ditched a long time ago by now in favor of Github Actions.
This then adds the Github workflow status badge with a link to the
status page.
Signed-off-by: Nick Østergaard <oe.nick@gmail.com>
(cherry picked from commit eab2ea6102fd7c84c9fd507b983698aa187df83b)
Backport https://github.com/gnuradio/gnuradio/pull/5245
=> Remove broken buildbot links in README badge line (backport to maint-3.8)

gr-analog/python/analog/qa_agc.py
The number of input elements needs to be disivible by volk_alignment, which it wasn't
for machines with 512-bit registers.
Signed-off-by: John Sallay <jasallay@gmail.com>
(cherry picked from commit 39e88e44607fe750fc6cba456554213adf9b862a)
Backport https://github.com/gnuradio/gnuradio/pull/5244
=> CI: fix qa_agc Assertion Error (backport to maint-3.8)

gnuradio-runtime/include/gnuradio/thread/thread_group.h, gnuradio-runtime/include/pmt/pmt.h, gnuradio-runtime/lib/block_registry.cc, gnuradio-runtime/lib/pmt/pmt.cc, gnuradio-runtime/lib/pmt/pmt_int.h, gnuradio-runtime/lib/pmt/qa_pmt_prims.cc, gnuradio-runtime/python/pmt/__init__.py, gr-digital/include/gnuradio/digital/constellation.h, gr-digital/lib/constellation_receiver_cb_impl.cc, gr-digital/python/digital/bindings/constellation_python.cc
This reverts commit ccd28dfbb1504fdc29db267acd8aa3354fe10cd2.
Decision made to not include std::any with the 3.10 release as it forces OOTs to compile with c++17 via the changes to the public headers.  
We will defer the change to std::any as it prevents OOTs between 3.9 and 3.10 from being compatible without changing to c++17 - and there is not necessarily a good reason to enforce this
all OOTs
Created a new OOT, left it at C++14 and compiled.
=> Revert "Replace boost::any with std::any"

cmake/Modules/GnuradioConfig.cmake.in
See related issue. This change allows OPTIONAL_COMPONENTS in a `find_package` call: It'll include the component if the CMake config exists (i.e. it's been enabled during compilation), otherwise it won't.
Fixes #5309 
CMake config
Tested OPTIONAL_COMPONENTS with this change and they are correctly included when available, otherwise they are silently passed over.
=> cmake: handle optional components in `find_package`

gnuradio-runtime/python/gnuradio/gr/hier_block2.py
Reverts gnuradio/gnuradio#5303
Not compatible with Python2
=> Revert "gr-runtime: Change hier_block2.py __getattr__ to avoid recursive loop in exception (backport to maint-3.8)"

cmake/Modules/GnuradioConfig.cmake.in
Signed-off-by: Christoph Koehler <christoph@zerodeviation.net>
(cherry picked from commit f9a693d7af02b6ce88fb0e4f3fad78390980c968)
Backport https://github.com/gnuradio/gnuradio/pull/5310
=> cmake: handle optional components in `find_package` (backport to maint-3.9)

gr-qtgui/include/gnuradio/qtgui/DisplayPlot.h, gr-qtgui/include/gnuradio/qtgui/TimeRasterDisplayPlot.h, gr-qtgui/include/gnuradio/qtgui/WaterfallDisplayPlot.h, gr-qtgui/include/gnuradio/qtgui/plot_raster.h, gr-qtgui/include/gnuradio/qtgui/plot_waterfall.h, gr-qtgui/include/gnuradio/qtgui/qtgui_types.h, gr-qtgui/include/gnuradio/qtgui/timeRasterGlobalData.h, gr-qtgui/include/gnuradio/qtgui/waterfallGlobalData.h, gr-qtgui/lib/ConstellationDisplayPlot.cc, gr-qtgui/lib/plot_raster.cc, gr-qtgui/lib/plot_waterfall.cc, gr-qtgui/lib/timeRasterGlobalData.cc, gr-qtgui/lib/waterfallGlobalData.cc
Adds the typedefs and includes needed to build with Qwt 6.2.
Signed-off-by: Bill Muzika <bill.muzika@outlook.com>
(cherry picked from commit 14d30f134cd402a35f46911342eb4d519e2ad7aa)
Backport https://github.com/gnuradio/gnuradio/pull/5302
=> qt-gui: enables use of Qwt 6.2 (backport to maint-3.9)

gr-qtgui/include/gnuradio/qtgui/DisplayPlot.h, gr-qtgui/include/gnuradio/qtgui/TimeRasterDisplayPlot.h, gr-qtgui/include/gnuradio/qtgui/WaterfallDisplayPlot.h, gr-qtgui/include/gnuradio/qtgui/plot_raster.h, gr-qtgui/include/gnuradio/qtgui/plot_waterfall.h, gr-qtgui/include/gnuradio/qtgui/qtgui_types.h, gr-qtgui/include/gnuradio/qtgui/timeRasterGlobalData.h, gr-qtgui/include/gnuradio/qtgui/waterfallGlobalData.h, gr-qtgui/lib/ConstellationDisplayPlot.cc, gr-qtgui/lib/plot_raster.cc, gr-qtgui/lib/plot_waterfall.cc, gr-qtgui/lib/timeRasterGlobalData.cc, gr-qtgui/lib/waterfallGlobalData.cc
Adds the typedefs and includes needed to build with Qwt 6.2.
Signed-off-by: Bill Muzika <bill.muzika@outlook.com>
(cherry picked from commit 14d30f134cd402a35f46911342eb4d519e2ad7aa)
Backport https://github.com/gnuradio/gnuradio/pull/5302
=> qt-gui: enables use of Qwt 6.2 (backport to maint-3.8)

gr-filter/examples/reconstruction.py
The reconstruction.py example in the filters module pointed at an old digital.bpsk_mod block which no longer exists. I just changed it to point at the current digital.psk_mod block.
None
Example in gr-filters
I tested the corrected script and it now works.
=> filter: Minisule change to fix reconstruction.py example

cmake/Modules/GrTest.cmake, gr-utils/modtool/templates/gr-newmod/python/CMakeLists.txt
Updated:
This change creates a module directory inside the build tree (`build/test_modules/modulename`). It consists of the build artifacts from `build/python/bindings` and `python/*`. `GrTest` then adds `build/test_modules` to the PYTHONPATH.
Old description:
This change makes CTest look for locally-built modules (i.e. during development, in the build directory) before installed ones.
Also adjust test module name in the template, though that's not ideal. I _think_ we could remove the `_python` suffix from the module in this line, but not quite sure about that: https://github.com/gnuradio/gnuradio/blob/master/cmake/Modules/GrPybind.cmake#L9
If we can, existing modules should just work with the GrTest.cmake (and GrPybind.cmake) changes (i.e. a new GR version).
I think it takes care of …
=> modtool,cmake: make module dir for tests 

gr-filter/examples/reconstruction.py
Signed-off-by: Nicholas Bruce <saltair93+github@gmail.com>
(cherry picked from commit ed7f128355770a1b82673b42919617ca260693e2)
Backport https://github.com/gnuradio/gnuradio/pull/5321
=> gr-filter: Corrects reconstruction filter bank example to point at existing psk block (backport to maint-3.9)

cmake/Modules/GrTest.cmake, gr-utils/modtool/templates/gr-newmod/python/CMakeLists.txt
Creates a python module in the build tree for tests to import.
Addresses #3999 and #4825
Signed-off-by: Christoph Koehler <christoph@zerodeviation.net>
(cherry picked from commit c7390f29c7047ed00df3831e83998ccf3a72a8bb)
Backport https://github.com/gnuradio/gnuradio/pull/5279
=> modtool,cmake: make module dir for tests (backport to maint-3.9)

gr-utils/modtool/templates/gr-newmod/python/CMakeLists.txt, gr-utils/modtool/templates/gr-newmod/python/bindings/CMakeLists.txt
Signed-off-by: shwhiti <shwhiti@sandia.gov>
This pull request allows a python-only module to build without error. All new OOT modules built with gr_modtool currently
will fail in the `make` step.
The `python/CmakeLists.txt` file is now only in charge of copying python source files into `build/test-module/module-name/` where previously it copied in anything in the `python` source directory as well as the pybind `.so` file from the `/build/python/bindings/` directory.
The `bindings/CmakeLists.txt` file is now in charge of copying the `build/python/bindings/` `.so` file into the test module directory. This is only done when there is `c++` code to be added to the module.
These changes make the python package in `build` match more closely to what is actually installed by not copying over …
=> modtool,cmake: fix python-only QA, clean up build directory

gr-digital/grc/digital_symbol_sync_xx.block.yml
---
Simple change to `gr-digital/grc/digital_symbol_sync_xx.block.yml` to put umlaut where the ue was used.  Has been noted in #3209 that this seems to have been resolved with python3 (and it works fine on my machine)
#3209
Seems to just be the symbol sync block yml 
Loaded it up in GRC
=> digital: use umlauts in yml

gr-utils/modtool/templates/gr-newmod/python/CMakeLists.txt, gr-utils/modtool/templates/gr-newmod/python/bindings/CMakeLists.txt
Signed-off-by: shwhiti <shwhiti@sandia.gov>
(cherry picked from commit d4df6a14db8864eb123de8d9b18865210540e904)
Backport https://github.com/gnuradio/gnuradio/pull/5335
=> modtool,cmake: fix python-only QA, bindings copy handled in bindings cmake file (backport to maint-3.9)

gr-filter/python/filter/design/filter_design.py, gr-filter/python/filter/gui/banditems.py
---
Filter designer wasn't working at all on Ubuntu 20.04 because it used Qt4 syntax.  
Need to also remove PyQwt from various places
Need to verify minimum specified QT version
#1634
gr_filter_design
limited to this point.  Just enough to launch filter_design
=> filter: remove pyqwt and qt4 from various places

gnuradio-runtime/python/gnuradio/gr/bindings/logger_python.cc
changes the python binding of the logging levels (warn, trace, debug, etc.) from `gr.level_enum` to `gr.log_levels`
=> runtime: change name of level_enum in py binding

gr-qtgui/python/qtgui/range.py.cmakein
Author: Chris Vine <vine35792468@gmail.com>
Python 3.10 sees setRange( non-int-value ) as an error. Reported by Chris Vine.
Fixes #5341 
qtgui/range
=> qtgui range: setRange() requires int

.github/workflows/make-test.yml, CMakeLists.txt
---
For the 3.10 release we will support the latest LTS releases from major distributions.  The major bottleneck here in terms of dependencies is Ubuntu 3.10.
Fixes #2719
top level CMake
None
--> Needs to be updated before merging
=> Bump Major Dependency Versions for 3.10

gnuradio-runtime/include/gnuradio/buffer.h, gnuradio-runtime/include/gnuradio/buffer_reader.h, gnuradio-runtime/include/gnuradio/buffer_reader_sm.h, gnuradio-runtime/python/gnuradio/gr/bindings/buffer_python.cc, gnuradio-runtime/python/gnuradio/gr/bindings/buffer_reader_python.cc
Found some unused includes
... so I removed them
None
trying builds.
=> runtime: remove unused includes from buffer headers

gnuradio-runtime/include/gnuradio/buffer_single_mapped.h, gnuradio-runtime/include/gnuradio/host_buffer.h
Fix two alloc dealoc mismatch errors
In `host_buffer::do_allocate_buffer(...) the memory for `d_buffer` and `d_device_buf` is allocated using `new char[]` but it is de-allocated using  `delete` as both members are defined as `std::unique_ptr<char>`. Mixing `new[]` with `delete` is considered UB.
To reproduce the error compile with `-fsanitize=address -fsanitize=undefined` and execute `ctest -R runtime_qa_host_buffer.cc --output-on-failure`
```
ERROR: AddressSanitizer: alloc-dealloc-mismatch (operator new [] vs operator delete) on 0x631000014800
#0 0x7ffbdc10f9d7 in operator delete(void*, unsigned long) (/lib64/libasan.so.6+0xad9d7)
#1 0x7ffbd8a6646f in std::default_delete<char>::operator()(char*) const /usr/include/c++/10/bits/unique_ptr.h:85
#2 0x7ffbd8a6646f in std::unique_ptr<char, …
```
=> runtime: Fix two alloc dealloc mismatch errors

gr-blocks/python/blocks/__init__.py, gr-blocks/python/blocks/qa_file_metadata.py, gr-blocks/python/blocks/qa_matrix_interleaver.py, gr-blocks/python/blocks/qa_nlog10.py
* qa_nlog10.py: Update test to check for equal with one less decimal place.
On the qemu machines built with OpenEmbedded, this test failed if
the check was 5 decimal places. Relaxing to 4 lets the test pass.
The volk routines used in the implementation pass QA already.
* Update QA tests to import helper routines from blocks.
The file metadata QA installs a file in blocks, but imported it
directly. Updated init.py to import via blocks. matrix interleaver
imported some routines from a py file that was available via blocks.
These cretaed issues when you install the qa tests in images to run
them outside the build area.
* python formatting …
=> qa: update tests to work with OpenEmbedded (backport to maint-3.9)

gr-filter/grc/variable_band_reject_filter_taps.block.yml
GRC YML filter for band reject filter variable contained a typo in the set_taps() callback. Resulting generated code cause did not run.
Callback was added in b405ca8, but using the logic for the band pass taps block which has multiple types. Band reject only supports float.
Fixes #5368
Band-reject Filter Taps
=> fix typo in band reject taps variable block set_taps() (maint-3.8)

gnuradio-runtime/include/gnuradio/logger.h, gnuradio-runtime/python/gnuradio/gr/bindings/logger_python.cc, gr-utils/blocktool/core/parseheader_generic.py
after the changes introduced in logger.h, pygccxml does not play well with the spdlog
headers which are implicitly included in every block.  This caused `gr_modtool bind`
to crash 
Fixes #5364 
Any OOT using gr_modtool bind
Created a new OOT with a few blocks and then ran `gr_modtool bind`
- N/A I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.
=> Modtool bind with spdlog complication

gr-network/lib/tcp_sink_impl.cc, gr-network/lib/tcp_sink_impl.h, gr-network/lib/udp_sink_impl.cc, gr-network/lib/udp_sink_impl.h, gr-network/lib/udp_source_impl.cc, gr-network/lib/udp_source_impl.h, gr-network/python/network/qa_tcp_sink.py, gr-network/python/network/qa_udp_sink.py, gr-network/python/network/qa_udp_source.py
The TCP and UDP blocks segfault if `start()` is called after `stop()`, because `stop()` frees resources that are not re-allocated by `start()`. To fix this, I've moved resource allocation for these blocks from the constructor to `start()`.
Fixes #5112.
Also fixes the Gqrx crash noted in https://github.com/gqrx-sdr/gqrx/pull/982.
* TCP Sink
* UDP Sink
* UDP Source
I've added regression tests. All of them fail with segfaults before the changes, and pass afterwards.
In addition, I've verified that UDP output in Gqrx works with this change applied.
=> network: fix segfaults when TCP & UDP blocks are restarted

gr-network/lib/tcp_sink_impl.cc, gr-network/lib/tcp_sink_impl.h, gr-network/lib/udp_sink_impl.cc, gr-network/lib/udp_sink_impl.h, gr-network/lib/udp_source_impl.cc, gr-network/lib/udp_source_impl.h, gr-network/python/network/qa_tcp_sink.py, gr-network/python/network/qa_udp_sink.py, gr-network/python/network/qa_udp_source.py
The TCP and UDP blocks segfault if start() is called after stop(),
because stop() frees resources that are not re-allocated by start(). To
fix this, I've moved resource allocation for these blocks from the
constructor to start().
(cherry picked from commit 35a242f1cd4b724be0c4708d8690f82c804aafd8)
Backport https://github.com/gnuradio/gnuradio/pull/5372
=> network: fix segfaults when TCP & UDP blocks are restarted (backport to maint-3.9)

.ci_support/linux_64_numpy1.19python3.9.____cpython.yaml, .ci_support/osx_64_numpy1.19python3.9.____cpython.yaml, .ci_support/win_64_numpy1.19python3.9.____cpython.yaml, .conda-forge.yml, .github/workflows/conda-build.yml, .packaging/conda_recipe/meta.yaml, .packaging/conda_recipe/yum_requirements.txt, .scripts/build_steps.sh, .scripts/run_osx_build.sh, gnuradio-runtime/include/gnuradio/logger.h, gnuradio-runtime/python/gnuradio/gr/bindings/logger_python.cc, gr-audio/lib/osx/osx_impl.cc
Regardless of how spdlog was built (with/without `SPDLOG_FMT_EXTERNAL`), this ensures that the proper fmt headers are included. This makes it so that fmt is not a required dependency when spdlog is built with `SPDLOG_FMT_EXTERNAL=OFF`.
Fixes #5349. Gets the conda CI running against spdlog.
=> runtime: Use <spdlog/fmt/fmt.h> header handling SPDLOG_FMT_EXTERNAL

.github/workflows/make-test.yml
~Boost 1.69, though available in CentOS 8 EPEL installs differently and is a bit unwieldy to use.  Instead, let's just keep with the same boost version that is in 3.9~
Removing CentOS 8 from the list of containers
It is too problematic to track and not worth changing our min versions over
=> ci: Remove CentOS 8 from list of containers

gr-analog/include/gnuradio/analog/pwr_squelch_cc.h, gr-analog/include/gnuradio/analog/pwr_squelch_ff.h, gr-analog/python/analog/bindings/pwr_squelch_cc_python.cc, gr-analog/python/analog/bindings/pwr_squelch_ff_python.cc
gnuradio documentation automatically generated for [pwr_squelch_ff](https://www.gnuradio.org/doc/doxygen/classgr_1_1analog_1_1pwr__squelch__ff.html) and [pwr_squelch_cc](https://www.gnuradio.org/doc/doxygen/classgr_1_1analog_1_1pwr__squelch__cc.html) states:
> The block will emit a tag with the key pmt::intern("squelch_sob") with the value of pmt::PMT_NIL on the first item it passes, and with the key pmt::intern("squelch:eob") on the last item it passes.
Based on squelch_base_ff and squelch_base_cc, it should be `pmt::intern("squelch_eob")`, not `pmt::intern("squelch:eob")`.
https://github.com/gnuradio/gnuradio/blob/1a0be2e6b54496a8136a64d86e372ab219c6559b/gr-analog/lib/squelch_base_ff_impl.cc#L28
https://github.com/gnuradio/gnuradio/blob/1a0be2e6b54496a8136a64d86e372ab219c6559b/gr-analog/ …
=> Squelch_eob typo in comments propagates to online documentation.

gnuradio-runtime/include/gnuradio/block.h, gnuradio-runtime/lib/block.cc, gnuradio-runtime/lib/tpb_thread_body.cc, gnuradio-runtime/python/gnuradio/gr/bindings/block_python.cc, gnuradio-runtime/python/gnuradio/gr/bindings/docstrings/block_pydoc_template.h
The fixed setting in the scheduler of 250ms when the input is blocked to retry running the thread is arbitrary and in some blocks with blocking implementations, this timeout can be troublesome and give some weird interaction with the scheduler and the block getting samples from hardware.  For these scenarios, make the value configurable so the user can set what this timeout should be.
Mainly blocks that poll for samples to be ready from some other source.  If the block returns immediately hoping the scheduler will call the work function again, that 250ms timeout could cause problems.
=> runtime: configurable blkd_input timer

CMakeLists.txt, cmake/Modules/GrCompilerSettings.cmake, cmake/Modules/GrMinReq.cmake, gr-utils/modtool/templates/gr-newmod/CMakeLists.txt
---
At the moment compiler settings for cmake are maintained at several points,
- the main CMakeLists.txt
- the template file ./gr-utils/modtool/templates/gr-newmod/CMakeLists.txt
- each oot module.
So changing some settings may be cumbersome and error-prone.
Put the minimum dependency versions for central dependencies in one cmake file and the compiler requirements in an another one, so these settings can be maintained at one place and reused.
Built gnuradio from scratch and some of my oot's
=> cmake: Maintain compiler settings at one point.

gr-network/grc/network_tcp_sink.block.yml, gr-network/grc/network_tcp_source.block.yml
Signed-off-by: Aditya Thomas <sepia_tone@protonmail.com>
A throttle flag is added to the network blocks - TCP source and TCP sink. This prevents a warning about the lack of rate limiting.
Fixes #5094 
network
Tested on Ubuntu 20.04
=> Addition of a throttle flag to the network blocks

cmake/Modules/FindLOG4CPP.cmake
The patch adds `/usr/lib/x86_64-linux-gnu` as a default search path when looking for the log4cpp lib.
There is no related issue it seems but it does fail on Ubuntu 20.04 when installing the dependency and then trying to build.
=> findlog4cpp: extend PATH hints to include default x86_64 lib path

gr-dtv/lib/dvbs2/dvbs2_modulator_bc_impl.cc
Signed-off-by: maswx <masw@masw.tech>
(cherry picked from commit 19864fc6ede818b169259607bb85bd5931013e02)
Backport https://github.com/gnuradio/gnuradio/pull/5391
=> gr-dtv: Add energy normalization for DVB-S2X constellations (backport to maint-3.9)

gr-dtv/lib/dvbs2/dvbs2_modulator_bc_impl.cc
Signed-off-by: maswx <masw@masw.tech>
(cherry picked from commit 19864fc6ede818b169259607bb85bd5931013e02)
Backport https://github.com/gnuradio/gnuradio/pull/5391
=> gr-dtv: Add energy normalization for DVB-S2X constellations (backport to maint-3.8)

gr-qtgui/lib/freqcontrolpanel.cc
The QT GUI Frequency Sink block segfaults if a large (e.g. 8192) or small (e.g. 17) FFT size is specified, and the Control Panel is subsequently opened. This happens because there are no bounds checks on the index computed here:
https://github.com/gnuradio/gnuradio/blob/19864fc6ede818b169259607bb85bd5931013e02/gr-qtgui/lib/freqcontrolpanel.cc#L243-L247
It looks like this bug has been around since the control panel was added in https://github.com/gnuradio/gnuradio/pull/459, so GNU Radio 3.7.7+ would be affected.
* QT GUI Frequency Sink
I used this flow graph to test:
After starting the flow graph, middle click on the Frequency Sink and click "Control Panel". Prior to this change, a segfault will occur. Same if the FFT size is changed to 17.
=> qtgui: add bounds checks to calculation of d_fft_size_combo index

.packaging/conda_recipe/meta.yaml, CMakeLists.txt, cmake/Modules/GrPython.cmake, grc/core/generator/flow_graph.py.mako, grc/gui/Dialogs.py, grc/gui/Executor.py, grc/gui/canvas/flowgraph.py, tools/clang_format.py
---
With the upcoming python 3.10 ( for example in fedora 35 ) the package distutils is marked as depreciated and will be removed in 3.12.
Python provides replacements for the distutils functions.
Only distutils.sysconfig.get_python_lib() has no direct counterpart,.
grc, grc generated flowgraphs
Building gnuradio from scratch on fedora 33 and 35
=> gnuradio: replace deprecated distutils

gr-qtgui/include/gnuradio/qtgui/freqdisplayform.h, gr-qtgui/lib/freqcontrolpanel.cc, gr-qtgui/lib/freqdisplayform.cc
Add fftsize 8192 in freqcontrolpanel
remove unused variable d_num_real_data_points in freqdisplayform.
---
Fixes #5399 
frequency sink
Run example in #5399
=> gr-qtgui: add missing fftsize entry in freqcontrolpanel

gr-iio/grc/iio_fmcomms2_sink.block.yml, gr-iio/grc/iio_fmcomms2_source.block.yml, gr-iio/grc/iio_fmcomms5_sink.block.yml, gr-iio/grc/iio_fmcomms5_source.block.yml, gr-iio/grc/iio_pluto_sink.block.yml, gr-iio/grc/iio_pluto_source.block.yml
When the fields are hidden, and the expected global variable is
undefined, the flow graph becomes unsynthesizable.
I've only found this pattern with IIO blocks.
Sadly, we *have* to put defaults here, in order to have valid arguments
to the (useless) `set_filter_params` call in the non-Design filter mode.
Since the fpass and fstop fields, however, aren't used, the actual value
used there doesn't matter – so, 0 it is.
Simply replaces all occurences of `samp_rate/x` in hidden defaults by 0
#5414
IIO's GRC bindings
Prior, deleting the `samp_rate` variable from a flow graph made it impossible to generate the python. Now, it's possible. 
Have *not* tested whether this works at runtime – no hardware right now.
=> iio: GRC bindings: remove global variable from hidden defaults

gr-vocoder/swig/vocoder_swig.i
`_Complex` (actual C99 keyword) is not supported by SWIG, `complex` is.
It is not unlikely this will break later on when SWIG starts behaving
standards-compliant.
This became an error when codec2 1.0.1 started exposing API with
_Complex.
Signed-off-by: Marcus Müller <marcus@hostalia.de-
#5411  
Vocoder SWIG  build only on maint-3.8, sadly might lead to incompatibilities in the future
None, since no build machine at hand
=> Vocoder: SWIG needs a workaround for dealing with C99 keyword _Complex

gr-filter/lib/mmse_fir_interpolator_cc.cc, gr-filter/lib/mmse_fir_interpolator_ff.cc, gr-filter/lib/mmse_interp_differentiator_cc.cc, gr-filter/lib/mmse_interp_differentiator_ff.cc, gr-filter/lib/pfb_arb_resampler.cc, gr-filter/lib/pfb_synthesizer_ccf_impl.cc, gr-filter/lib/polyphase_filterbank.cc
---
name: Optimize filter setup a bit using the power of move
about: Minor speed increase and cleanup
title: ''
labels: ''
assignees: ''
---
Optimize filter setup a bit using the power of move.
Note that this PR will clash a bit with PR #5422. Probably should merge that first, and I'll sort out any conflict.
`gr-filter`. Minor speedup by avoiding copies.
WIP: Running tests now locally, and expecting this PR to trigger more testing.
=> filter: Optimize filter setup a bit using the power of move

gr-iio/lib/attr_sink_impl.cc, gr-iio/lib/attr_sink_impl.h, gr-iio/lib/attr_source_impl.cc, gr-iio/lib/attr_source_impl.h, gr-iio/lib/attr_updater_impl.h
Silence a compiler warning.
attr_sink/source, attr_updater
=> iio: remove unused members

grc/core/Constants.py, grc/core/params/dtypes.py, grc/gui/Application.py
This is a stopgap fix to help with the UX by reverting to the old behavior where the flowgraph is titled "top_block" (but doesn't really matter) - but it is not immediately in a state of error.  
There is likely a better UX solution for naming and saving flowgraphs, but hopefully this removes some of the frustration to a newly created flowgraph. 
Definitely open to ideas for doing something different here, but want to get *something* into 3.10.
#5415
grc
Opened new flowgraph and ran without having to change the name or the block being red.
=> grc: change default flowgraph id

gr-qtgui/grc/qtgui_freq_sink_x.block.yml, gr-qtgui/grc/qtgui_sink_x.block.yml, gr-qtgui/grc/qtgui_waterfall_sink_x.block.yml, gr-qtgui/include/gnuradio/qtgui/form_menus.h, gr-qtgui/include/gnuradio/qtgui/freqdisplayform.h, gr-qtgui/include/gnuradio/qtgui/waterfalldisplayform.h, gr-qtgui/lib/freq_sink_c_impl.cc, gr-qtgui/lib/freq_sink_f_impl.cc, gr-qtgui/lib/freqcontrolpanel.cc, gr-qtgui/lib/freqdisplayform.cc, gr-qtgui/lib/waterfalldisplayform.cc
---
With #5405 the segfault of freq_sink_c was fixed, but
if you enable the control panel and change the FFT size to 8192
while the flow graph is running, the whole flowgraph freezes.
This patch:
- fixes the freeze
- extends the fftsize to 32768 for freq_sink_c and freq_sink_f
- changes the entry for fftsize in the corresponding yml files from integer to enum
and provides a drop down menu with those values that are provided by the gui
in the running flowgraph.
The code provides code for setting the fftsize in form_menus.h and in freqcontrolpanel.cc
If you change some signal and slots you can do without the code from form_menus.h.
So this part is removed.
freq_sink_c, freq_sink_f
Flowgraph:
signal source -> freq_sink 
->gui_sink
While running, change fftsize to each availabe size. No …
=> gr-qtgui: Frequency sink freezes the running flowgraph

gr-qtgui/include/gnuradio/qtgui/HistogramDisplayPlot.h
A regression was reported in QT GUI histogram block, where x autoscale was not happening.  This brings the behavior back to match how it was in 3.9
NOTE: autoscale X doesn't seem to work in 3.9 or here, but prior to this PR - NOT autoscaling doesn't work (lots of double negatives).  This just matches the 3.9 behavior.
QT GUI Histogram 
Ran flowgraph with histogram block, verified behavior was same in 3.9/
- N/A [ ] I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.
- N/A [ ] I have added tests to cover my changes, and all previous tests pass.
=> qtgui: initial value of autoscalex defined

gr-qtgui/grc/qtgui_freq_sink_x.block.yml, gr-qtgui/grc/qtgui_sink_x.block.yml, gr-qtgui/grc/qtgui_waterfall_sink_x.block.yml, gr-qtgui/include/gnuradio/qtgui/SpectrumGUIClass.h, gr-qtgui/lib/SpectrumGUIClass.cc, gr-qtgui/lib/sink_c_impl.cc, gr-qtgui/lib/sink_f_impl.cc
fftsize starts in the runtime gui of the f/c sink with 512.
Adjust it to 32 , as in freq_sink_f/c
Introduce fft range check to the sink_x and the waterfall_sink_x block.
Check inside the sink_(f/c) blcok, if the fftsize is valid, to avoid core dump.
---
fftsize starts in the runtime gui of the f/c sink with 512.
Adjust it to 32 , as in it's yml file and in freq_sink_f/c
Introduce fft range check to the sink_x and the waterfall_sink_x block.
Check inside the sink_(f/c) blcok, if the fftsize is valid, to avoid core dump.
Adds range checks for sink_x and waterfall_sink_x
Completes #5442
=> grc: Follow up to #5442

grc/core/Constants.py, grc/core/params/dtypes.py, grc/gui/Application.py
(cherry picked from commit ad843023c65dc35aed73b7a4e4a78afbc7347f5d)
Backport https://github.com/gnuradio/gnuradio/pull/5421
=> grc: don't blacklist default fg id (backport to maint-3.8)

gnuradio-runtime/include/gnuradio/flowgraph.h, gnuradio-runtime/include/gnuradio/pycallback_object.h, gnuradio-runtime/lib/block.cc, gnuradio-runtime/lib/flat_flowgraph.cc, gnuradio-runtime/lib/flat_flowgraph.h, gnuradio-runtime/lib/flowgraph.cc, gnuradio-runtime/lib/hier_block2_detail.cc, gnuradio-runtime/lib/hier_block2_detail.h, gnuradio-runtime/lib/logger.cc, gnuradio-runtime/python/gnuradio/gr/bindings/flowgraph_python.cc, gr-audio/lib/alsa/alsa_impl.cc, gr-audio/lib/osx/osx_source.cc, gr-blocks/lib/check_lfsr_32k_s_impl.cc, gr-digital/lib/constellation_receiver_cb_impl.cc, gr-digital/lib/fll_band_edge_cc_impl.cc, gr-fec/lib/async_encoder_impl.cc
This commit replaces many uses of std::c{out,err} and printf with the
appropriate GR_LOG_* directives.
Signed-off-by: David Winter <david.winter@analog.com>
(cherry picked from commit db01027fd99c882cf8b3a7dad854606499778e3b)
Removed mods to gr-blocks/lib/qa_block_tags.cc due to differences
in logging code.
Backport #5105
=> global: Replace stdio logging with logger (backport to maint-3.9)

gr-uhd/lib/usrp_source_impl.cc
The first overflow count that the USRP source prints is bogus, because `_overflow_count` is uninitialized.
> usrp_source :error: In the last 13041 ms, 6881380 overflows occurred.
Valgrind also complains that uninitialized memory was read:
```
==130286== Thread 16 usrp_source56:
==130286== Use of uninitialised value of size 8
==130286==    at 0x6A9A10B: ??? (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.28)
==130286==    by 0x6A9A7AD: std::ostreambuf_iterator<char, std::char_traits<char> > std::num_put<char, std::ostreambuf_iterator<char, std::char_traits<char> > >::_M_insert_int<unsigned long>(std::ostreambuf_iterator<char, std::char_traits<char> >, std::ios_base&, char, unsigned long) const (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.28)
==130286==    by 0x6AA900E: std::ostream& …
```
=> Initialize _overflow_count to zero

gr-uhd/lib/usrp_source_impl.cc
(cherry picked from commit 0975b99f70a31d57bc3a7af9b4a585c54ab9745f)
Backport https://github.com/gnuradio/gnuradio/pull/5475
=> uhd: Initialize _overflow_count to zero (backport to maint-3.9)

gr-uhd/lib/usrp_source_impl.cc
(cherry picked from commit 0975b99f70a31d57bc3a7af9b4a585c54ab9745f)
Backport https://github.com/gnuradio/gnuradio/pull/5475
=> uhd: Initialize _overflow_count to zero (backport to maint-3.10)

.conda-forge.yml, .github/ISSUE_TEMPLATE/bug_report.yml, .github/pull_request_template.md, .github/workflows/conda-build.yml, .github/workflows/make-test.yml, .github/workflows/pkg-debian.yml, .github/workflows/pkg-fedora.yml, README.md, tools/clang_format.py
In the change of default branch naming, some things in the code that explicitly refers to `master` that needs to be changed to `main`
Fixes #4963 
Mostly just docs and CI configurations
=> global: cleanup name change master to main

gr-utils/bindtool/templates/generic_python_cc.mako
Strongly typed enums require the enum name to access its values.
This doesn't affect old-style enums because value access works also
with prepended enum name.
---
title: 'pybind: support enum class handling'
labels: ''
assignees: ''
---
=> pybind: support enum class handling

gr-utils/modtool/tools/grc_yaml_generator.py
---
title: ''
labels: ''
Using `gr_modtool makeyaml` in gr 3.10 creates the old style import for the module
This updates to `from gnuradio import mymodule` in the make template in the generated yaml
Ideally this would do the check of gr39/gr310, but it is not readily availble at this point, so since makeyaml is an experimental feature, sticking with the broadest use case
gr_modtool maintained blocks using gr_modtool makeyaml
=> modtool: makeyaml update import to from gnuradio

gr-analog/grc/analog_random_uniform_source_x.block.yml
Signed-off-by: Thomas Habets <habets@google.com>
(cherry picked from commit 79f95a3d8e9da27981377e08f7f66942b6999a84)
Backport https://github.com/gnuradio/gnuradio/pull/5491
=> analog: Fix C++ code generation for random_uniform_source (backport to maint-3.10)

gr-uhd/grc/uhd_fpga_ddc.block.yml, gr-uhd/grc/uhd_fpga_duc.block.yml
Upstream changed names in
https://github.com/EttusResearch/uhd/commit/72e833e7bb71b2b2891ef5b07ada5aaf856a266a.
(cherry picked from commit 2ea2750bcb98f21d0f6a065ceb5d69a61a505213)
Backport https://github.com/gnuradio/gnuradio/pull/5493
=> uhd: Fix ddc/duc block descriptor names

gr-iio/grc/iio_fmcomms2_sink.block.yml, gr-iio/grc/iio_fmcomms2_source.block.yml, gr-iio/lib/device_sink_impl.cc, gr-iio/lib/device_sink_impl.h, gr-iio/lib/device_source_impl.cc, gr-iio/lib/device_source_impl.h, gr-iio/lib/fmcomms2_sink_impl.cc, gr-iio/lib/fmcomms2_source_impl.cc
PR fixes #5476 for both the FMComms234 source and sink blocks.
The fixes update the GRC files to use the correct APIs for 1RX/2RX 1TX/2TX configurations that interface with AD9361/AD9363/AD9364 based systems using the IIO drivers. The core iio_device_{source/sink} blocks have been updated to allow inherited blocks to better define tags to be generated/processed when using the packet_len APIs. Unrelated to #5476 was the incorrect behavior of the incorrect number of channels being processed for these tags. All of these have been addressed and tested.
#5476 
- fmcomms2_source (PlutoSDR, FMComms 2/3/4)
- fmcomms2_sink (PlutoSDR, FMComms 2/3/4)
- iio_device_source
- iio_device_sink
Flowgraphs have been generated and run without error for device combinations with source and sink blocks:
- …
=> FMComms234 Source/Sink fixes

gnuradio-runtime/lib/hier_block2_detail.cc, gnuradio-runtime/lib/hier_block2_detail.h, gr-blocks/lib/CMakeLists.txt, gr-blocks/lib/qa_gr_hier_block2_derived.cc, gr-blocks/python/blocks/qa_hier_block2.py
Signed-off-by: Vladisslav P <vladisslav@inbox.ru>
Fix freeze on hier_block2::lock() when hier_block2 is just created.
Fix freeze on hier_block2::lock() when was disconnected from another block
and disconnect(hier_block...) is the last operation before  hier_block2::lock()
1. Check for top_block correctly with dynamic_cast
2. Use weak_ptr to track parent block
3. Maintain reference counter and clear d_parent when all ports get disconnected
4. Clear d_parent on disconnect_all
5. Add tests
6. Limit test run time to 30 seconds to make it fail in predictable time (blocks only)
Close https://github.com/gnuradio/gnuradio/issues/5436
hier_block2
C++ test `main.cpp`:
```
#include <iostream>
#include <gnuradio/blocks/null_sink.h>
#include <gnuradio/blocks/null_source.h>
#include …
```
=> hier_block2: prevent crash/freeze after disconnection

gr-iio/grc/iio_fmcomms2_sink.block.yml, gr-iio/grc/iio_fmcomms2_source.block.yml, gr-iio/lib/device_sink_impl.cc, gr-iio/lib/device_sink_impl.h, gr-iio/lib/device_source_impl.cc, gr-iio/lib/device_source_impl.h, gr-iio/lib/fmcomms2_sink_impl.cc, gr-iio/lib/fmcomms2_source_impl.cc
* Fix FMComms234 Source GRC file
Add len_tag_key parameter, fix enables, and selectively use gain sets
based on channels.
Signed-off-by: Travis F. Collins <travis.collins@analog.com>
* Fix FMComms4 checks for fmcomms2_source
Signed-off-by: Travis F. Collins <travis.collins@analog.com>
* Fix iio source blocks packet_len marker
Packet length (start of buffer) tags were broken on FMComms234 but
functioning on Pluto. It was also not generating tagged streams for all
output channels, only odd channels. The main issue came from the nested
work calls where the channels known by the iio_device_source class was
different than what the parent block (fmcomm2_source) was actually
outputting. This fix adds an override mechanism to tell the
iio_device_source the true number of output channels. This …
=> gr-iio: FMComms234 Source/Sink fixes (backport to maint-3.10)

gr-digital/python/digital/__init__.py
Had gotten lost in the autopep8 formatting
Thanks to @drmpeg for finding and bisecting as part of #5188
=> digital: put back import of packet_utils

gr-blocks/grc/blocks.tree.yml, gr-blocks/grc/blocks_sigmf_sink_minimal.block.yml, gr-blocks/grc/blocks_sigmf_source_minimal.block.yml, gr-blocks/grc/sigmf_source_minimal.block.yml, gr-blocks/python/blocks/CMakeLists.txt, gr-blocks/python/blocks/__init__.py, gr-blocks/python/blocks/sigmf_sink_minimal.py
A first cut of the two minimal SigMF blocks that have been discussed in #SigMF within Matrix.  The motivation here is to improve adoption of SigMF, by having at least basic ability to save and read SigMF files within GNU Radio, in Ubuntu 22 specifically, as the freeze is happening soon and gr-sigmf isn't ready.  These blocks are immediately being set to "deprecated" as you can see, they will be removed when gr-sigmf is ready to use.
The SigMF Sink is just a wrapper around File Sink that produces the .sigmf-meta file based on params fed into the block.  The idea was to keep it extremely simple.  
The SigMF Source is literally just a File Source with some extra documentation explaining how to use it to read in SigMF files, so this is targeted at newer folks, and the most important part of …
=> SigMF Minimal Blocks

gr-qtgui/include/gnuradio/qtgui/SpectrumGUIClass.h
Valgrind shows that the `_updateTime` member variable is read before it is initialized when a GT GUI Sink is constructed:
```
==221466== Conditional jump or move depends on uninitialised value(s)
==221466==    at 0x491F722: SpectrumGUIClass::updateWindow(bool, float const*, unsigned long, float const*, unsigned long, float const*, unsigned long, long long, bool) (SpectrumGUIClass.cc:241)
==221466==    by 0x491F9E9: SpectrumGUIClass::openSpectrumWindow(QWidget*, bool, bool, bool, bool) (SpectrumGUIClass.cc:90)
==221466==    by 0x49287F5: gr::qtgui::sink_c_impl::initialize() (sink_c_impl.cc:129)
==221466==    by 0x4928E3F: gr::qtgui::sink_c_impl::sink_c_impl(int, int, double, double, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, bool, bool, …
```
=> qtgui: Initialize _updateTime variable

grc/core/blocks/block.py
The orange coloring of a deprecated block currently is only based on a block being in the "Deprecated" category - but some blocks such as the new SigMF placeholder blocks are not.  This expands the orange coloring to blocks that have the deprecated flag in their yaml
Tried it in GRC
=> grc: use block deprecated flag for visual indication

gr-digital/python/digital/__init__.py
Had gotten lost in the autopep8 formatting
(cherry picked from commit b42996b1569722d34dad2057406e4a6c3de99366)
Backport https://github.com/gnuradio/gnuradio/pull/5506
=> digital: put back import of packet_utils (backport to maint-3.10)

grc/core/blocks/block.py
(cherry picked from commit 942aff023d2c8152623aacb433ba2ce9a99ad3df)
Backport https://github.com/gnuradio/gnuradio/pull/5515
=> grc: use block deprecated flag for visual indication (backport to maint-3.10)

gr-filter/grc/filter_pfb_channelizer.block.yml, gr-filter/grc/filter_pfb_synthesizer.block.yml
(cherry picked from commit f626980888e8346b915d10c689ff3280df43dbd4)
Backport https://github.com/gnuradio/gnuradio/pull/5502
=> filter: use compatible names for bus parameters (backport to maint-3.10)

gr-filter/grc/filter_pfb_channelizer.block.yml, gr-filter/grc/filter_pfb_synthesizer.block.yml, grc/blocks/snippet.block.yml
Backport simple YAML fixes.
Backport #5464 
Default value for Priority parameter in Python Snippet block
Backport #5502 
filter: use compatible names for bus parameters
=> Backport 5464 5502 to maint-3.8

gnuradio-runtime/lib/flat_flowgraph.cc
The calculation of buffer sizes for downstream blocks was changed in the custom buffer implementation - the reason for the change related to history is still unclear.
Fixes #5542 
All blocks 
Ran the example flowgraph that was broken as described in #5542.  Needs testing of
=> runtime: downstream buffer size calculation back to 3.9 value

gnuradio-runtime/lib/flat_flowgraph.cc
(cherry picked from commit 120268de56dbf1a1ab01e27c601cd7d1342afaf7)
Backport https://github.com/gnuradio/gnuradio/pull/5543
=> runtime: downstream buffer size calculation back to 3.9 value (backport to maint-3.10)

gnuradio-runtime/CMakeLists.txt
The backport of #5444 copied a reference to spdlog into GNU Radio 3.9. LOG4CPP should be referenced instead.
=> cmake: fix incorrect backporting of #5444

gr-digital/grc/digital.tree.yml
Currently the "EVM Measurement" block shows up in its own "Equalizers" module in GRC instead of the "Equalizers" category in the Core module. Adding it to the tree file fixes that.
Before:
After:
* EVM Measurement
=> digital: move EVM Measurement block into the Core tree

CMakeLists.txt, gr-utils/modtool/templates/gr-newmod/CMakeLists.txt
Calling project() sets the default value for `CMAKE_BUILD_TYPE`. For most generators this results in a null value so that any later check acting on an unset `CMAKE_BUILD_TYPE` will proceed. However, on Windows the default value is set to Debug, so the existing attempts to detect an unset `CMAKE_BUILD_TYPE` and set it to Release fail to do the job on Windows.
This commit sets `CMAKE_BUILD_TYPE` to Release before the project() call so that the generator-dependent default is avoided. Because `CMAKE_BUILD_TYPE` is set as a `CACHE` variable, this set command will not overwrite any existing cached value for `CMAKE_BUILD_TYPE`, thus still allowing users to override the setting from the CMake command line.
Fixes reported errors from mailing list and Matrix chat in running OOTs built with default …
=> cmake: Initialize `CMAKE_BUILD_TYPE` to Release before project() call.

gr-utils/blocktool/core/parseheader_generic.py
---
title: 'blocktool: fix binding generation for uhd rfnoc blocks'
labels: ''
assignees: ''
---
This fixes
```
File "/home/USER/gnuradio/gr-uhd/python/uhd/../../../gr-utils/bindtool/scripts/bind_intree_file.py", line 60, in <module>
bg.gen_file_binding(args.filename)
File "/usr/lib/python3.10/site-packages/gnuradio/bindtool/core/generator.py", line 197, in gen_file_binding
raise(e)
File "/usr/lib/python3.10/site-packages/gnuradio/bindtool/core/generator.py", line 184, in gen_file_binding
header_info = parser.get_header_info(self.namespace)
File …
```
=> blocktool: fix binding generation for uhd rfnoc blocks

gr-qtgui/grc/qtgui_vector_sink_f.block.yml, gr-qtgui/include/gnuradio/qtgui/vector_sink_f.h, gr-qtgui/lib/vector_sink_f_impl.cc, gr-qtgui/lib/vector_sink_f_impl.h, gr-qtgui/python/qtgui/bindings/docstrings/vector_sink_f_pydoc_template.h, gr-qtgui/python/qtgui/bindings/vector_sink_f_python.cc
---
Adds a disabled_legend option to the vector sink.
Other sinks like Constellation/Eye/Frequency/Histogram/Waterfall sink already offer this option
Fixes #5489 
qtgui_vector_sink_f
=> gr-qtgui: Vector sink add disable_legend

gr-blocks/grc/blocks_matrix_interleaver.block.yml
Removed co-author's name from yml doc
---
name: Jared Dulmage
about: Removes name from documentation
title: 'Remove name from GRC documentation'
labels: 'GRC Documentation'
assignees: ''
---
Remove co-author's name from matrix_interleaver GRC documentation
Removed co-author name from documentation in GRC yml file for matrix_interleaver.
None
blocks:matrix_interleaver
N/A no changes to code
- [X ] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md).
=> Remove co-author's name from documentation

gr-filter/lib/rational_resampler_impl.cc, gr-filter/lib/rational_resampler_impl.h, gr-filter/python/filter/qa_rational_resampler.py
If the Interpolation and Decimation factors of a Rational Resampler block have common factor, and taps are manually specified, then the block segfaults when it is launched.
This happens because the block declares its own `d_logger` pointer but does not initialize it before use:
https://github.com/gnuradio/gnuradio/blob/3349d483a1f7e5db0eea042815d237810373857b/gr-filter/lib/rational_resampler_impl.h#L33
https://github.com/gnuradio/gnuradio/blob/3349d483a1f7e5db0eea042815d237810373857b/gr-filter/lib/rational_resampler_impl.cc#L124-L130
The `basic_block` class already provides a logger, so there is no need to override it. I've switched to using the provided logger here.
It looks like this bug was introduced in #3952. I've confirmed that it's present in 3.9 and 3.10.
* Rational Resampler
I …
=> filter: Fix crash in Rational Resampler logging

grc/core/FlowGraph.py, grc/core/schema_checker/flow_graph.py
Saving a flowgraph does not save the grc version
as it this info is not part of the schema.
This pr adds grc_version to the schema definition and
saves the grc version string when the fg is saved.
Possibly
fixes #5521
(cherry picked from commit b0d3304e1b82821b60027858eb220bc513e2cf6f)
Backport https://github.com/gnuradio/gnuradio/pull/5553
=> grc: store grc version info in metadata (backport to maint-3.9)

CMakeLists.txt, gnuradio-runtime/lib/CMakeLists.txt, gr-utils/modtool/templates/gr-newmod/CMakeLists.txt
Backport #5545 - Set target_compile_features to cxx_std_17
Backport #5544 - Initialize CMAKE_BUILD_TYPE to Release before project() call
=> cmake updates #5544 #5545 (backport to maint-3.10)

gr-qtgui/grc/qtgui_vector_sink_f.block.yml, gr-qtgui/include/gnuradio/qtgui/vector_sink_f.h, gr-qtgui/lib/vector_sink_f_impl.cc, gr-qtgui/lib/vector_sink_f_impl.h, gr-qtgui/python/qtgui/bindings/docstrings/vector_sink_f_pydoc_template.h, gr-qtgui/python/qtgui/bindings/vector_sink_f_python.cc
Adds a disabled_legend option to the vector sink.
(cherry picked from commit 2910458586ee3e5d34b23f36de510fe05fe9ec7b)
Backport https://github.com/gnuradio/gnuradio/pull/5540
=> gr-qtgui: Vector sink add disable_legend (backport to maint-3.10)

gr-qtgui/include/gnuradio/qtgui/eyedisplayform.h, gr-qtgui/lib/eyedisplayform.cc
Fixes #5487
Removes unneeded PopupMenu d_tr_level_act and tr_delay_act
and corresponding functions.
(cherry picked from commit 09c3c4fa4bfb1a02caac74cb5334dfe065391e3b)
Backport https://github.com/gnuradio/gnuradio/pull/5577
=> gr-qtgui: Eye Sink remove unnecessary request for trigger value (backport to maint-3.10)

gr-filter/lib/rational_resampler_impl.cc, gr-filter/lib/rational_resampler_impl.h, gr-filter/python/filter/qa_rational_resampler.py
(cherry picked from commit 95ee7221f8d72d5021c92595e1779719eb9c8fbb)
Backport https://github.com/gnuradio/gnuradio/pull/5569
=> filter: Fix crash in Rational Resampler logging (backport to maint-3.9)

gr-qtgui/grc/qtgui_vector_sink_f.block.yml, gr-qtgui/include/gnuradio/qtgui/vector_sink_f.h, gr-qtgui/lib/vector_sink_f_impl.cc, gr-qtgui/lib/vector_sink_f_impl.h, gr-qtgui/python/qtgui/bindings/docstrings/vector_sink_f_pydoc_template.h, gr-qtgui/python/qtgui/bindings/vector_sink_f_python.cc
Adds a disabled_legend option to the vector sink.
(cherry picked from commit 2910458586ee3e5d34b23f36de510fe05fe9ec7b)
Backport https://github.com/gnuradio/gnuradio/pull/5540
=> gr-qtgui: Vector sink add disable_legend (backport to maint-3.9)

gr-filter/lib/rational_resampler_impl.cc, gr-filter/lib/rational_resampler_impl.h, gr-filter/python/filter/qa_rational_resampler.py
(cherry picked from commit 95ee7221f8d72d5021c92595e1779719eb9c8fbb)
Backport https://github.com/gnuradio/gnuradio/pull/5569
=> filter: Fix crash in Rational Resampler logging (backport to maint-3.10)

CMakeLists.txt, gr-utils/modtool/templates/gr-newmod/CMakeLists.txt
Calling project() sets the default value for `CMAKE_BUILD_TYPE`. For
most generators this results in a null value so that any later check
acting on an unset `CMAKE_BUILD_TYPE` will proceed. However, on Windows
the default value is set to Debug, so the existing attempts to detect an
unset `CMAKE_BUILD_TYPE` and set it to Release fail to do the job on
Windows.
This commit sets `CMAKE_BUILD_TYPE` to Release before the project() call
so that the generator-dependent default is avoided. Because
`CMAKE_BUILD_TYPE` is set as a `CACHE` variable, this set command will
not overwrite any existing cached value for `CMAKE_BUILD_TYPE`, thus
still allowing users to override the setting from the CMake
command line.
(cherry picked from commit …
=> cmake: Initialize `CMAKE_BUILD_TYPE` to Release before project() call (backport to maint-3.9)

gr-dtv/CMakeLists.txt, gr-dtv/lib/atsc/atsc_fs_checker_impl.cc, gr-dtv/lib/atsc/atsc_interleaver_impl.cc, gr-dtv/lib/atsc/atsc_rs_decoder_impl.cc, gr-dtv/lib/dvb/dvb_bbheader_bb_impl.cc, gr-dtv/lib/dvbs2/dvbs2_physical_cc_impl.cc, gr-dtv/lib/dvbt/dvbt_bit_inner_deinterleaver_impl.cc, gr-dtv/lib/dvbt/dvbt_bit_inner_interleaver_impl.cc, gr-dtv/lib/dvbt/dvbt_energy_dispersal_impl.cc, gr-dtv/lib/dvbt/dvbt_reed_solomon_dec_impl.cc, gr-dtv/lib/dvbt/dvbt_reed_solomon_enc_impl.cc, gr-dtv/lib/dvbt2/dvbt2_cellinterleaver_cc_impl.cc, gr-dtv/lib/dvbt2/dvbt2_framemapper_cc_impl.cc
This continues the work started in #5270. Here I've updated gr-dtv to use modern logging, which has also removed the module's last dependence on Boost.
* #5270
* ATSC Field Sync Checker
* ATSC Interleaver
* ATSC Reed-Solomon Decoder
* DVB BBheader
* DVB-S2 Physical Layer Framer
* DVB-T Bit Inner Deinterleaver
* DVB-T Bit Inner Interleaver
* DVB-T Energy Dispersal
* DVB-T Reed-Solomon Decoder
* DVB-T Reed-Solomon Encoder
* DVB-T2 Cell/Time Interleaver
* DVB-T2 Frame Mapper
So far I haven't done any testing. I'd appreciate help from folks familiar with gr-dtv.
=> dtv: Convert to modern logging

gr-utils/modtool/core/info.py
fix the variable used to get modname string
Without this fix the following error arise with `gr_modtool info` and a new OOT module (with `gr_modtool newmod`)
```
File "/opt/local/bin/gr_modtool", line 18, in <module>
cli()
File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
return self.main(*args, **kwargs)
File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1053, in main
rv = self.invoke(ctx)
File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File …
```
=> gr-utils/modtool: info.py fix modname variable

grc/core/generator/flow_graph.py.mako
---
name: "Code" for advanced block params in generated file
about: Allows script parameters so set advanced block parameters upon python script initialization in auto-generated code
title: Code instead of constants for advanced block parameters in generated python files
labels: ''
assignees: ''
---
This will allow script parameters/arguments to define buffer sizes and process affinity.  I can't think of any unintended negative impacts as changes to any variables used to define affinity and buffer sizes would not be propagated through to affinity or buffer changes after initialization.
This allows script parameters of the generated python file to set processor affinity, minimum output buffer size, and maximum output buffer size.
An example from a [test …
=> Use `to_code()` in advanced block params fields

gr-blocks/lib/file_source_impl.cc
If a non-seekable file like /dev/zero is opened in the File Source block, the following warning appears:
`file_source :warning: file size is not a multiple of item size
(9223372036854775807 ≠ N·8)`
This happens because non-seekable files are treated as if their size is INT64_MAX, which is almost never a multiple of the item size.
https://github.com/gnuradio/gnuradio/blob/3349d483a1f7e5db0eea042815d237810373857b/gr-blocks/lib/file_source_impl.cc#L151-L180
To solve the problem, I propose to simply skip the alignment check for non-seekable files.
* File Source
* Open `/dev/zero` in a File Source block (Output Type = complex) and verify that no warning is printed.
* Open a 1024-byte file in a File Source block and verify that no warning is printed.
* Open a 1023-byte file in a File Source …
=> blocks: Skip alignment check when the input file is not seekable

grc/core/generator/flow_graph.py.mako
This will allow script parameters/arguments to define buffer sizes and process affinity.  I can't think of any unintended negative impacts as changes to any variables used to define affinity and buffer sizes would not be propagated through to affinity or buffer changes after initialization.
Signed-off-by: Campbell <campbell.mcdiarmid@icloud.com>
(cherry picked from commit 341e8c8e3f072675d39e53a807fee098aa1a75a6)
Backport https://github.com/gnuradio/gnuradio/pull/5468
=> Code for advanced block params (backport to maint-3.10)

grc/core/generator/flow_graph.py.mako
This will allow script parameters/arguments to define buffer sizes and process affinity.  I can't think of any unintended negative impacts as changes to any variables used to define affinity and buffer sizes would not be propagated through to affinity or buffer changes after initialization.
Signed-off-by: Campbell <campbell.mcdiarmid@icloud.com>
(cherry picked from commit 341e8c8e3f072675d39e53a807fee098aa1a75a6)
Backport https://github.com/gnuradio/gnuradio/pull/5468
=> Code for advanced block params (backport to maint-3.9)

gr-blocks/lib/file_source_impl.cc
If a non-seekable file like /dev/zero is opened in the File Source block,
the following warning appears:
file_source :warning: file size is not a multiple of item size
(9223372036854775807 ≠ N·8)
This happens because non-seekable files are treated as if their size is
INT64_MAX, which is almost never a multiple of the item size. To solve
the problem, I propose to simply skip the alignment check for non-
seekable files.
(cherry picked from commit 72311c0763ca9f8953a5e0a303140a54da322c3e)
Backport https://github.com/gnuradio/gnuradio/pull/5583
=> blocks: Skip alignment check when the input file is not seekable (backport to maint-3.10)

gr-blocks/lib/file_source_impl.cc
If a non-seekable file like /dev/zero is opened in the File Source block,
the following warning appears:
file_source :warning: file size is not a multiple of item size
(9223372036854775807 ≠ N·8)
This happens because non-seekable files are treated as if their size is
INT64_MAX, which is almost never a multiple of the item size. To solve
the problem, I propose to simply skip the alignment check for non-
seekable files.
(cherry picked from commit 72311c0763ca9f8953a5e0a303140a54da322c3e)
Backport https://github.com/gnuradio/gnuradio/pull/5583
=> blocks: Skip alignment check when the input file is not seekable (backport to maint-3.9)

gr-iio/CMakeLists.txt, gr-iio/include/gnuradio/iio/iio_types.h, gr-iio/lib/attr_sink_impl.cc, gr-iio/lib/attr_source_impl.cc, gr-iio/lib/attr_updater_impl.cc, gr-iio/lib/dds_control_impl.cc, gr-iio/lib/device_sink_impl.cc, gr-iio/lib/iio_types.cc, gr-iio/lib/pluto_utils.cc, gr-iio/python/iio/bindings/iio_types_python.cc
gr-iio only uses Boost in a few places. I've replaced each with standard C++, thereby removing the dependence on Boost.
* DDS Control
* IIO Attribute Sink
* IIO Attribute Source
* IIO Attribute Updater
* IIO Device Sink
* PlutoSDR Sink
* PlutoSDR Source
With some simple flow graphs, I verified that PlutoSDR Sink & Source are still working.
I also verified that parameter parsing still works:
```
>>> gnuradio.iio.iio_param_t("a")
File "<stdin>", line 1, in <module>
ValueError: invalid parameter string: a
>>> gnuradio.iio.iio_param_t("a=b")
<gnuradio.iio.iio_python.iio_param_t object at 0x7fd8864f6af0>
>>> gnuradio.iio.iio_param_t("a=b=c")
File "<stdin>", line 1, in <module>
ValueError: invalid parameter string: a=b=c
>>> …
```
=> iio: Replace Boost with standard C++

gnuradio-runtime/python/gnuradio/gr/top_block.py, gr-blocks/python/blocks/qa_message.py, gr-digital/python/digital/qa_ofdm_chanest_vcvc.py, gr-fec/python/fec/polar/common.py, gr-fec/python/fec/polar/helper_functions.py
---
18/243 Testing: qa_hier_block2
gnuradio-runtime/python/gnuradio/gr/top_block.py:48: DeprecationWarning: setDaemon() is deprecated, set the daemon attribute instead
58/243 Testing: qa_message
gr-blocks/python/blocks/qa_message.py:44: DeprecationWarning: Please use assertEqual instead.
self.assertEquals(0, msg.type())
205/243 Testing: qa_ofdm_chanest_vcvc
...../usr/lib64/python3.10/random.py:370: DeprecationWarning: non-integer arguments to randrange() have been deprecated since Python 3.10 and will be removed in a subsequent version
return self.randrange(a, b+1)
114/243 Testing: qa_polar_decoder_sc
gnuradio/fec/polar/common.py:30: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`
Deprecated in NumPy 1.20; for more details and guidance: …
=> gnuradio: make test fix a lot of depreciation warnings

gr-soapy/CMakeLists.txt, gr-soapy/lib/block_impl.cc, gr-soapy/lib/sink_impl.cc, gr-soapy/lib/source_impl.cc
This continues the work started in #5270. Here I've updated gr-soapy to use modern logging, which has also removed the module's last dependence on Boost.
* #5270
* Soapy Sink
* Soapy Source
So far I haven't done any testing. I'd appreciate help from folks familiar with gr-soapy.
=> soapy: Convert to modern logging

gr-network/lib/socket_pdu_impl.cc, gr-network/lib/stream_pdu_base.cc, gr-network/lib/tcp_sink_impl.cc, gr-network/lib/tuntap_pdu_impl.cc, gr-network/lib/udp_sink_impl.cc, gr-network/lib/udp_source_impl.cc
This continues the work started in #5270. Here I've updated gr-network to use modern logging, which has also removed the module's dependence on Boost.Format.
* #5270
* Socket PDU
* TCP Sink
* TUNTAP PDU
* UDP Sink
* UDP Source
I haven't done much testing yet. I'd appreciate help from someone more familiar with gr-network.
=> network: Convert to modern logging

gnuradio-runtime/include/gnuradio/logger.h, gnuradio-runtime/python/gnuradio/gr/bindings/logger_python.cc, gr-uhd/examples/c++/tag_sink_demo.h, gr-uhd/examples/c++/tags_demo.cc, gr-uhd/lib/gr_uhd_common.h, gr-uhd/lib/rfnoc_rx_streamer_impl.cc, gr-uhd/lib/rfnoc_tx_streamer_impl.cc, gr-uhd/lib/usrp_block_impl.cc, gr-uhd/lib/usrp_sink_impl.cc, gr-uhd/lib/usrp_source_impl.cc
This continues the work started in #5270. Here I've updated gr-uhd to use modern logging, and removed all usage of Boost.Format.
* #5270
* Tags demo
* RFNoC Rx Streamer
* RFNoC Tx Streamer
* USRP Sink
* USRP Source
So far:
* Tested Gqrx with a UHD source. (Overflow logs appeared as before.)
* Tested gr-nrsc5 with a UHD sink.
* Ran `tags_demo --help`. (Help message displayed correctly.)
Additional testing help would be appreciated.
=> uhd: Remove boost::format and modernize logging

gnuradio-runtime/apps/gnuradio-config-info.cc, gnuradio-runtime/include/gnuradio/pycallback_object.h, gnuradio-runtime/lib/block.cc, gnuradio-runtime/lib/buffer_double_mapped.cc, gnuradio-runtime/lib/controlport/thrift/rpcserver_booter_thrift.cc, gnuradio-runtime/lib/local_sighandler.cc, gnuradio-runtime/lib/pagesize.cc, gnuradio-runtime/lib/pmt/qa_pmt_prims.cc, gnuradio-runtime/lib/realtime_impl.cc, gnuradio-runtime/lib/tagged_stream_block.cc, gnuradio-runtime/lib/thread/thread.cc, gnuradio-runtime/lib/thread/thread_body_wrapper.cc, gnuradio-runtime/lib/tpb_thread_body.cc, gnuradio-runtime/lib/vmcircbuf.cc, gnuradio-runtime/lib/vmcircbuf_createfilemapping.cc, gnuradio-runtime/lib/vmcircbuf_mmap_shm_open.cc, gnuradio-runtime/lib/vmcircbuf_mmap_tmpfile.cc, gnuradio-runtime/lib/vmcircbuf_prefs.cc, gnuradio-runtime/lib/vmcircbuf_sysv_shm.cc
This continues the work started in #5270. Here I've updated parts of gnuradio-runtime to use modern logging, and removed some usage of Boost.Format.
* #5270
* gnuradio-config-info executable
* double-mapped buffers
* blocks
* threads
* tagged stream block
I have verified that Gqrx and gr-nrsc5 still work correctly when using this branch.
=> runtime: Remove boost::format and modernize logging

gr-utils/modtool/core/info.py
Signed-off-by: Davide Gerhard <rainbow@irh.it>
(cherry picked from commit 1cf09ff12f02e699b058dee4a2c4bbf4fb74c3d5)
Backport https://github.com/gnuradio/gnuradio/pull/5565
=> gr-utils/modtool: info.py fix modname variable (backport to maint-3.10)

gr-qtgui/lib/ber_sink_b_impl.cc, gr-qtgui/lib/edit_box_msg_impl.cc, gr-qtgui/lib/eye_sink_c_impl.cc, gr-qtgui/lib/eye_sink_f_impl.cc, gr-qtgui/lib/freq_sink_c_impl.cc, gr-qtgui/lib/freq_sink_f_impl.cc, gr-qtgui/lib/sink_c_impl.cc, gr-qtgui/lib/sink_f_impl.cc, gr-qtgui/lib/time_sink_c_impl.cc, gr-qtgui/lib/time_sink_f_impl.cc, gr-qtgui/lib/timerasterdisplayform.cc, gr-qtgui/lib/vector_sink_f_impl.cc
This continues the work started in #5270. Here I've updated gr-qtgui to use modern logging, and removed all usage of Boost.Format.
In addition, I noticed a couple bugs along the way:
1. The complex Eye Sink prints incorrect values in its error message: https://github.com/gnuradio/gnuradio/blob/3349d483a1f7e5db0eea042815d237810373857b/gr-qtgui/lib/eye_sink_c_impl.cc#L279-L282
2. The floating point Time Sink incorrectly sets its trigger point to the end of the range rather than the midpoint when it is out of range: https://github.com/gnuradio/gnuradio/blob/3349d483a1f7e5db0eea042815d237810373857b/gr-qtgui/lib/time_sink_f_impl.cc#L277-L282
I fixed each of these bugs in its own commit.
* #5270
* QT GUI Bercurve Sink
* QT GUI Message Edit Box
* QT GUI Eye Sink
* QT GUI Frequency Sink
* QT GUI …
=> qtgui: Remove boost::format, modernize logging, and fix bugs

gr-fec/include/gnuradio/fec/generic_decoder.h, gr-fec/lib/async_encoder_impl.cc, gr-fec/lib/ber_bf_impl.cc, gr-fec/lib/cc_decoder_impl.cc, gr-fec/lib/cc_encoder_impl.cc, gr-fec/lib/ccsds_encoder_impl.cc, gr-fec/lib/conv_bit_corr_bb_impl.cc, gr-fec/lib/depuncture_bb_impl.cc, gr-fec/lib/dummy_decoder_impl.cc, gr-fec/lib/dummy_encoder_impl.cc, gr-fec/lib/generic_encoder.cc, gr-fec/lib/ldpc_G_matrix_impl.cc, gr-fec/lib/ldpc_bit_flip_decoder_impl.cc, gr-fec/lib/ldpc_decoder.cc, gr-fec/lib/ldpc_gen_mtrx_encoder_impl.cc, gr-fec/lib/ldpc_par_mtrx_encoder_impl.cc, gr-fec/lib/puncture_bb_impl.cc, gr-fec/lib/puncture_ff_impl.cc, gr-fec/lib/repetition_decoder_impl.cc, gr-fec/lib/repetition_encoder_impl.cc, gr-fec/lib/tagged_decoder_impl.cc, gr-fec/lib/tagged_encoder_impl.cc, gr-fec/python/fec/bindings/generic_decoder_python.cc
This continues the work started in https://github.com/gnuradio/gnuradio/pull/5270. Here I've updated gr-fec to use modern logging, and removed all usage of Boost.Format.
* #5270
Many FEC encoders and decoders.
None yet. I'd appreciate help from people familiar with gr-fec.
=> fec: Remove boost::format and modernize logging

gnuradio-runtime/include/gnuradio/logger.h, gnuradio-runtime/python/gnuradio/gr/bindings/logger_python.cc, gr-analog/lib/sig_source_impl.cc, gr-fft/lib/ctrlport_probe_psd_impl.cc, gr-filter/lib/fft_filter.cc, gr-filter/lib/pm_remez.cc, gr-video-sdl/lib/sink_s_impl.cc, gr-video-sdl/lib/sink_uc_impl.cc, gr-zeromq/lib/base_impl.cc, gr-zeromq/lib/pull_msg_source_impl.cc, gr-zeromq/lib/rep_msg_sink_impl.cc, gr-zeromq/lib/rep_sink_impl.cc, gr-zeromq/lib/req_msg_source_impl.cc, gr-zeromq/lib/sub_msg_source_impl.cc
This continues the work started in #5270. Here I've updated several modules (gr-analog, gr-fft, gr-filter, gr-video-sdl, and gr-zeromq), each of which has only a small amount of logging code to be updated.
I pulled in the `#include <spdlog/fmt/ostr.h>` change from #5601 here, since it's needed to log a PMT in gr-analog/lib/sig_source_impl.cc.
* #5270
* Signal Source
* Ctrlport Probe PSD
* FFT Filter
* Video SDL Sink
* ZMQ PULL Message Source
* ZMQ REP Message Sink
* ZMQ REP Sink
* ZMQ REQ Message Source
* ZMQ SUB Message Source
None yet.
I'd appreciate help from people familiar with these blocks.
=> Modernize logging in analog, fft, filter, video-sdl and zeromq

gr-pdu/python/pdu/qa_add_system_time.py, gr-pdu/python/pdu/qa_time_delta.py
`qa_add_system_time`/`test_002_timing` and `qa_time_delta`/`test_002_normal` routinely fail CI, usually on Windows. Some recent failed runs:
https://github.com/gnuradio/gnuradio/runs/5429110249?check_suite_focus=true
https://github.com/gnuradio/gnuradio/runs/5439304121?check_suite_focus=true
In both cases, the tests fail because the error tolerance is set too low.
None; this is a CI-only change.
I ran these test locally to verify that they run correctly, and fail if the `delta` value are set very low.
=> pdu: Fix flaky tests

gr-zeromq/CMakeLists.txt, gr-zeromq/lib/CMakeLists.txt, gr-zeromq/lib/pull_msg_source_impl.cc, gr-zeromq/lib/pull_msg_source_impl.h, gr-zeromq/lib/rep_msg_sink_impl.cc, gr-zeromq/lib/rep_msg_sink_impl.h, gr-zeromq/lib/req_msg_source_impl.cc, gr-zeromq/lib/req_msg_source_impl.h, gr-zeromq/lib/sub_msg_source_impl.cc, gr-zeromq/lib/sub_msg_source_impl.h
gr-zeromq's only remaining usage of Boost is `boost::thread`. It should be possible to switch this to `std::thread`, thereby removing the module's dependence on Boost.
* ZMQ PULL Message Source
* ZMQ REP Message Sink
* ZMQ REQ Message Source
* ZMQ SUB Message Source
None yet. I'd appreciate help from someone familiar with ZeroMQ.
=> zeromq: Replace boost::thread with std::thread

gr-qtgui/lib/edit_box_msg_impl.cc, gr-qtgui/python/qtgui/digitalnumbercontrol.py
At the moment, edit_box_msg sends the message if the widget looses it's focus
or if return was pressed.
This patch restricts sending to the return key press.
In addition some unneeded delete calls were removed, that caused segfaults
when the flowgraph was closed.
Replace signal editingFinished by signal returnPressed
Fixes #3423
Fixes #5412
Tested with
https://github.com/gnuradio/gnuradio/blob/master/gr-qtgui/examples/test_digitalnumcontrol.grc
https://github.com/gnuradio/gnuradio/blob/master/gr-qtgui/examples/test_qtgui_msg.grc
=> gr-qtgui: edit_box_msg, send message, only if return was pressed

gr-pdu/lib/add_system_time_impl.cc, gr-pdu/lib/pdu_split_impl.cc, gr-pdu/lib/pdu_to_stream_impl.cc, gr-pdu/lib/tags_to_pdu_impl.cc, gr-pdu/lib/take_skip_to_pdu_impl.cc, gr-pdu/lib/time_delta_impl.cc
This continues the work started in https://github.com/gnuradio/gnuradio/pull/5270. Here I've updated gr-pdu to use modern logging, and removed all usage of Boost.Format.
* #5270
* Add System Time
* PDU Split
* PDU To Stream
* Tags To PDU
* Take/Skip To PDU
* Time Delta
None yet. I'd appreciate help from people familiar with gr-pdu.
=> pdu: Remove boost::format and modernize logging

gr-digital/lib/burst_shaper_impl.cc, gr-digital/lib/clock_recovery_mm_cc_impl.cc, gr-digital/lib/constellation_receiver_cb_impl.cc, gr-digital/lib/corr_est_cc_impl.cc, gr-digital/lib/correlate_access_code_bb_impl.cc, gr-digital/lib/correlate_access_code_bb_ts_impl.cc, gr-digital/lib/correlate_access_code_ff_ts_impl.cc, gr-digital/lib/correlate_access_code_tag_bb_impl.cc, gr-digital/lib/correlate_access_code_tag_ff_impl.cc, gr-digital/lib/fll_band_edge_cc_impl.cc, gr-digital/lib/framer_sink_1_impl.cc, gr-digital/lib/header_payload_demux_impl.cc, gr-digital/lib/msk_timing_recovery_cc_impl.cc, gr-digital/lib/ofdm_cyclic_prefixer_impl.cc, gr-digital/lib/packet_headergenerator_bb_impl.cc, gr-digital/lib/packet_headerparser_b_impl.cc, gr-digital/lib/packet_sink_impl.cc, gr-digital/lib/protocol_formatter_bb_impl.cc, gr-digital/lib/symbol_sync_cc_impl.cc, gr-digital/lib/symbol_sync_ff_impl.cc
This continues the work started in https://github.com/gnuradio/gnuradio/pull/5270. Here I've updated gr-digital to use modern logging, and removed all usage of Boost.Format.
* #5270
* Burst Shaper
* Clock Recovery MM
* Correlation Estimator
* Correlate Access Code - Tag
* Correlate Access Code - Tag Stream
* FLL Band-Edge
* Framer Sink 1
* Header/Payload Demux
* MSK Timing Recovery
* OFDM Cyclic Prefixer
* Packet Header Generator
* Packet Header Parser
* Packet Sink
* Protocol Formatter
* Symbol Sync
So far I've only tested the Symbol Sync blocks. I'd appreciate help from people familiar with gr-digital.
=> digital: Remove boost::format and modernize logging

gr-audio/lib/alsa/alsa_impl.cc, gr-audio/lib/alsa/alsa_sink.cc, gr-audio/lib/alsa/alsa_source.cc, gr-audio/lib/audio_registry.cc, gr-audio/lib/jack/jack_sink.cc, gr-audio/lib/jack/jack_source.cc, gr-audio/lib/oss/oss_sink.cc, gr-audio/lib/oss/oss_source.cc, gr-audio/lib/osx/circular_buffer.h, gr-audio/lib/osx/osx_common.h, gr-audio/lib/osx/osx_impl.cc, gr-audio/lib/osx/osx_sink.cc, gr-audio/lib/osx/osx_source.cc, gr-audio/lib/portaudio/portaudio_sink.cc, gr-audio/lib/portaudio/portaudio_source.cc, gr-audio/lib/windows/windows_sink.cc, gr-audio/lib/windows/windows_source.cc
This continues the work started in https://github.com/gnuradio/gnuradio/pull/5270. Here I've updated gr-audio to use modern logging, and removed all usage of Boost.Format.
* #5270
* Audio Sink
* Audio Source
None yet. I'd appreciate help from people familiar with gr-audio.
=> audio: Remove boost::format and modernize logging

gr-fec/CMakeLists.txt, gr-fec/include/gnuradio/fec/decoder.h, gr-fec/include/gnuradio/fec/tagged_decoder.h, gr-fec/python/fec/bindings/decoder_python.cc, gr-fec/python/fec/bindings/tagged_decoder_python.cc
gr-fec references `boost::shared_array` in two places, but never uses it. (The last usage was removed in https://github.com/gnuradio/gnuradio/commit/2e26269d32a357688f6fea652137d9a1900c3a29). We can therefore remove these references, and thereby rid gr-fec of Boost completely.
* FEC Decoder
* FEC Tagged Decoder
None yet.
=> fec: Remove the last references to Boost

gr-qtgui/python/qtgui/range.py.cmakein
QEngValidator in range.py.cmakein incorrectly overwrites default background color to white on successful validation. White may not be the correct color given the default qss of the user. Fix changes it to default coloring instead of white.
Fixes #5623
QT GUI Range
Tested on osmocom_fft on kali linux OS.
=> qtgui: Fixes #5623 - QEngValidator in range.py.cmakein incorrectly overwrites default background color

gr-network/lib/socket_pdu_impl.cc, gr-network/lib/tcp_connection.cc, gr-network/lib/tcp_connection.h, gr-network/lib/tcp_sink_impl.cc, gr-network/lib/tcp_sink_impl.h, gr-network/lib/udp_sink_impl.cc, gr-network/lib/udp_sink_impl.h
Here I've removed some Boost from gr-network:
* Replaced `boost::bind` with lambda expressions
* Replaced `boost::array` with `std::array`
* Replaced `boost::thread` with `std::thread`
* Removed an unused instance of `boost::mutex`
* Socket PDU
* TCP Sink
* UDP Sink
I tested Gqrx's UDP output, which uses GNU Radio's UDP Sink block. I'd appreciate help testing the other blocks.
=> network: Replace some Boost with standard C++

gnuradio-runtime/lib/buffer_reader.cc, gnuradio-runtime/lib/buffer_single_mapped.cc
of block history
Signed-off-by: David Sorber <david.sorber@blacklynx.tech>
Correct `single_mapped_buffer` handling of block history to prevent stalling due to being unable to execute the output blocked callback.  This change ensures that a gap of history - 1 is left between the write and read pointers to allow room for the callback to execute. 
Fixes #5634.
`single_mapped_buffer` specifically, and therefore all custom buffers using it
- Ran through case described in #5634 to verify that the flowgraph no longer gets stuck.  Also added memcpy to test block to ensure that output is correctly aligned.
- Ran through test suite with buffer type set to `host_buffer`. Noticed an issue with `qa_hier_block2::test_035_lock_after_disconnect`
=> runtime: correct single_mapped_buffer's output blocked callback handling

gnuradio-runtime/include/gnuradio/logger.h, gnuradio-runtime/python/gnuradio/gr/bindings/logger_python.cc
Now that `boost::format` has been removed from all GNU Radio modules (in #5626 and others), it should no longer be necessary to support `boost::format` in the logger.
* logging
I build GNU Radio and tested a few flow graphs with the log levels set to `trace`. Everything still worked as before.
=> runtime: Remove boost::format support from the logger

gnuradio-runtime/python/gnuradio/gr/top_block.py, gr-blocks/python/blocks/qa_message.py, gr-digital/python/digital/qa_ofdm_chanest_vcvc.py, gr-fec/python/fec/polar/common.py, gr-fec/python/fec/polar/helper_functions.py
18/243 Testing: qa_hier_block2
gnuradio-runtime/python/gnuradio/gr/top_block.py:48: DeprecationWarning: setDaemon() is deprecated, set the daemon attribute instead
58/243 Testing: qa_message
gr-blocks/python/blocks/qa_message.py:44: DeprecationWarning: Please use assertEqual instead.
self.assertEquals(0, msg.type())
205/243 Testing: qa_ofdm_chanest_vcvc
...../usr/lib64/python3.10/random.py:370: DeprecationWarning: non-integer arguments to randrange() have been deprecated since Python 3.10 and will be removed in a subsequent version
return self.randrange(a, b+1)
114/243 Testing: qa_polar_decoder_sc
gnuradio/fec/polar/common.py:30: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`
Deprecated in NumPy 1.20; for more details and guidance: …
=> gnuradio: make test fix a lot of depreciation warnings (backport to maint-3.10)

gr-digital/examples/packet/example_corr_est_and_clock_sync.grc, gr-digital/examples/packet/example_corr_est_and_phase_sync.grc
https://github.com/gnuradio/gnuradio/blob/main/gr-digital/examples/packet/example_corr_est_and_clock_sync.grc
https://github.com/gnuradio/gnuradio/blob/main/gr-digital/examples/packet/example_corr_est_and_phase_sync.grc
produce now output signals.
This is due to improper threshold settings.
Fixes #5528
(cherry picked from commit 614681baf404ea893843e7903e93b3fa5a81833a)
Backport https://github.com/gnuradio/gnuradio/pull/5600
=> gr-digital/examples: Fix some improper parameter settings (backport to maint-3.10)

grc/blocks/grc.tree.yml, grc/blocks/json_config.block.yml, grc/blocks/yaml_config.block.yml
* Add in json and yaml config blocks
Signed-off-by: John Sallay <jasallay@gmail.com>
(cherry picked from commit b98599b78ee061b61a354ea17d63ff8a3feb396d)
Backport https://github.com/gnuradio/gnuradio/pull/5611
=> grc: Add in json/yml config blocks with validation (backport to maint-3.10)

gnuradio-runtime/lib/buffer_reader.cc, gnuradio-runtime/lib/buffer_single_mapped.cc
of block history
Signed-off-by: David Sorber <david.sorber@blacklynx.tech>
(cherry picked from commit 931ae5ff228d91ec9367393c5366aaa8be7e8485)
Backport https://github.com/gnuradio/gnuradio/pull/5637
=> runtime: correct single_mapped_buffer's output blocked callback handling (backport to maint-3.10)

grc/scripts/freedesktop/org.gnuradio.grc.metainfo.xml
Closes #5614.
Also move the tag to a better position (where most other apps have their launchable tags) in the file.
Without this, AppStream is not able to match the correct desktop file leading to missing icon and other issues in metadata.
=> grc: add .desktop suffix to the desktop launchable, other metainfo fixes

gr-blocks/grc/blocks_message_strobe_random.block.yml, gr-blocks/include/gnuradio/blocks/message_strobe_random.h, gr-blocks/lib/message_strobe_random_impl.cc, gr-blocks/lib/message_strobe_random_impl.h, gr-blocks/python/blocks/bindings/message_strobe_random_python.cc, gr-zeromq/examples/zmq_msg.grc
The Message Strobe Random-Delay block currently has three options for the distribution of the delays between messages:
* Poisson (default in GRC)
* Gaussian
* Uniform
Poisson is a strange choice, that distribution measures the number of events that occur during a fixed time interval in a Poisson process, not the time delays between them (which follow an Exponential distribution). I think the Exponential distribution would be much more useful as a default choice, and I suspect it's what was intended when this block was created.
To preserve backwards compatibility, I left the Poisson distribution in place and added Exponential as a fourth choice, which will be the default for a newly instantiated block.
I also updated the block's YAML file so that the "standard deviation" parameter is …
=> blocks: Add exponential distribution to Message Strobe Random-Delay

gr-blocks/grc/blocks_message_strobe_random.block.yml, gr-blocks/include/gnuradio/blocks/message_strobe_random.h, gr-blocks/lib/message_strobe_random_impl.cc, gr-blocks/lib/message_strobe_random_impl.h, gr-blocks/python/blocks/bindings/message_strobe_random_python.cc, gr-zeromq/examples/zmq_msg.grc
(cherry picked from commit bb554fae5f69616b7e7bc047154a57e3b9f39d9f)
Backport https://github.com/gnuradio/gnuradio/pull/5669
=> blocks: Add exponential distribution to Message Strobe Random-Delay (backport to maint-3.10)

grc/scripts/freedesktop/org.gnuradio.grc.metainfo.xml
Backport https://github.com/gnuradio/gnuradio/pull/5615
=> grc: add .desktop suffix to the desktop launchable, other metainfo fixes (backport to maint-3.10)

gr-trellis/python/trellis/bindings/viterbi_combined_python.cc, gr-trellis/python/trellis/qa_trellis.py
Add missing python bindings for trellis viterbi_combined
This adds missing python bindings for trellis code, especially viterbi_combinedxx, which seem not to have been introduced after the project conversion from 3.8 (swig) to 3.9 (pybind11)
Fixes #5666
gr-trellis, in particular all trellis.viterbi_combinedxx python bindings that weren't implemented since porting gnuradio from 3.8 (swig) to 3.9 (pybind11)
Recompiled gnuradio, made a demo block and tested for the python binding to work
=> Add python bindings and qa test for viterbi combined functions

gr-digital/grc/digital.tree.yml
Currently the "EVM Measurement" block shows up in its own "Equalizers"
module in GRC instead of the "Equalizers" category in the Core module.
Adding it to the tree file fixes that.
(cherry picked from commit cecde9b314b6440429e7519e81e562fdc911c039)
Backport https://github.com/gnuradio/gnuradio/pull/5560
=> digital: move EVM Measurement block into the Core tree (backport to maint-3.9)

gr-blocks/grc/blocks_matrix_interleaver.block.yml
Removed co-author's name from yml doc
(cherry picked from commit 141c0da0349703a483d0c5931d01ed207dcdd3b6)
Backport https://github.com/gnuradio/gnuradio/pull/5550
=> Remove co-author's name from documentation (backport to maint-3.9)

gnuradio-runtime/python/gnuradio/gr/top_block.py, gr-blocks/python/blocks/qa_message.py, gr-digital/python/digital/qa_ofdm_chanest_vcvc.py, gr-fec/python/fec/polar/common.py, gr-fec/python/fec/polar/helper_functions.py
18/243 Testing: qa_hier_block2
gnuradio-runtime/python/gnuradio/gr/top_block.py:48: DeprecationWarning: setDaemon() is deprecated, set the daemon attribute instead
58/243 Testing: qa_message
gr-blocks/python/blocks/qa_message.py:44: DeprecationWarning: Please use assertEqual instead.
self.assertEquals(0, msg.type())
205/243 Testing: qa_ofdm_chanest_vcvc
...../usr/lib64/python3.10/random.py:370: DeprecationWarning: non-integer arguments to randrange() have been deprecated since Python 3.10 and will be removed in a subsequent version
return self.randrange(a, b+1)
114/243 Testing: qa_polar_decoder_sc
gnuradio/fec/polar/common.py:30: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`
Deprecated in NumPy 1.20; for more details and guidance: …
=> gnuradio: make test fix a lot of depreciation warnings (backport to maint-3.9)

grc/blocks/grc.tree.yml, grc/blocks/json_config.block.yml, grc/blocks/yaml_config.block.yml
* Add in json and yaml config blocks
Signed-off-by: John Sallay <jasallay@gmail.com>
(cherry picked from commit b98599b78ee061b61a354ea17d63ff8a3feb396d)
Backport https://github.com/gnuradio/gnuradio/pull/5611
=> grc: Add in json/yml config blocks with validation (backport to maint-3.9)
