gnuradio/gnuradio

grc/core/FlowGraph.py, grc/gui/Application.py
(cherry picked from commit dae6e47c1858a3273bed0e7405a33f156f95ae7b)
Backport https://github.com/gnuradio/gnuradio/pull/5187
=> grc: Dependent variables sometimes fail to evaluate (backport to maint-3.8)

gr-qtgui/include/gnuradio/qtgui/DisplayPlot.h, gr-qtgui/include/gnuradio/qtgui/TimeRasterDisplayPlot.h, gr-qtgui/include/gnuradio/qtgui/WaterfallDisplayPlot.h, gr-qtgui/include/gnuradio/qtgui/plot_raster.h, gr-qtgui/include/gnuradio/qtgui/plot_waterfall.h, gr-qtgui/include/gnuradio/qtgui/qtgui_types.h, gr-qtgui/include/gnuradio/qtgui/timeRasterGlobalData.h, gr-qtgui/include/gnuradio/qtgui/waterfallGlobalData.h, gr-qtgui/lib/ConstellationDisplayPlot.cc, gr-qtgui/lib/plot_raster.cc, gr-qtgui/lib/plot_waterfall.cc, gr-qtgui/lib/timeRasterGlobalData.cc, gr-qtgui/lib/waterfallGlobalData.cc
This PR enables support for Qwt 6.2 (without breaking support for older versions) and cleans up some uses of the Qwt5 compatibility header. 
Fixes #4956
qt-gui
Tested on Ubuntu 20.04, Fedora 34, and openSUSE Tumbleweed using a signal source, throttle, and QT GUI block.
=> qt-gui: enables use of Qwt 6.2

.packaging/conda_recipe/build.sh, .packaging/conda_recipe/meta.yaml, .scripts/build_steps.sh, .scripts/run_docker_build.sh
=> CI: Update conda build + test for Qwt 6.2, +`qa_agc`, -`qa_message_*` on macOS

gr-filter/python/filter/design/filter_design.py, gr-filter/python/filter/gui/banditems.py
(cherry picked from commit 1fb203afd0dc3ab5681210c94bfbefe26c8e22f5)
Backport https://github.com/gnuradio/gnuradio/pull/5276
=> filter: remove pyqwt and qt4 from filter_design (backport to maint-3.9)

gr-qtgui/python/qtgui/range.py.cmakein
Author: Chris Vine <vine35792468@gmail.com>
(cherry picked from commit 6a4eef30b0ff16006ec31a901937619ff136737a)
Backport https://github.com/gnuradio/gnuradio/pull/5287
=> qtgui range: setRange() requires int (backport to maint-3.9)

CHANGELOG.md, CMakeLists.txt
Increment the version number in the build to prepare for RC1
=> Release Candidate 3.10.0.0-rc1

gr-qtgui/python/qtgui/range.py.cmakein
Author: Chris Vine <vine35792468@gmail.com>
(cherry picked from commit 6a4eef30b0ff16006ec31a901937619ff136737a)
Backport https://github.com/gnuradio/gnuradio/pull/5287
=> qtgui range: setRange() requires int (backport to maint-3.8)

.github/workflows/make-test.yml
Fedora 33 is EOL, so move testing forward a release.
=> ci: test F34/35 instead of F33/34

cmake/Modules/GrTest.cmake
=> cmake: Remove warnings from GrTest.cmake

gr-filter/python/filter/design/filter_design.py, gr-filter/python/filter/gui/banditems.py
(cherry picked from commit 1fb203afd0dc3ab5681210c94bfbefe26c8e22f5)
Backport https://github.com/gnuradio/gnuradio/pull/5276
=> filter: remove pyqwt and qt4 from filter_design (backport to maint-3.8)

grc/blocks/options.block.yml, grc/core/generator/flow_graph.py.mako
This is a redo of the [PR](https://github.com/gnuradio/gnuradio/pull/3726) that was merged last year on 3.8.
The goal and changes are the same as before, just for 3.9 and master.
I've merged the commits and added the DCO signature that wasn't there at the time.
Changes the top_block generation template when bokeh GUI is selected.
=> grc: modify and cleanup bokeh server loop

grc/blocks/options.block.yml, grc/core/generator/flow_graph.py.mako
Remake of the commits proposed to maint-3.8 to support the latest versions of bokeh.
Signed-off-by: Cyrille Morin <barthy42@laposte.net>
(cherry picked from commit bbd98d195dc1f300fb4fc34ed94941da2854dd9e)
Backport https://github.com/gnuradio/gnuradio/pull/5346
=> grc: modify and cleanup bokeh server loop (backport to maint-3.9)

gr-network/grc/network_tcp_sink.block.yml, gr-network/grc/network_tcp_source.block.yml
Signed-off-by: Aditya Thomas <sepia_tone@protonmail.com>
(cherry picked from commit d1060b771ada5e0bc51e43c7c8c21ae64d739bbf)
Backport https://github.com/gnuradio/gnuradio/pull/5314
=> network: addition of a throttle flag to the tcp source and sink blocks (backport to maint-3.9)

gr-analog/include/gnuradio/analog/pwr_squelch_cc.h, gr-analog/include/gnuradio/analog/pwr_squelch_ff.h, gr-analog/python/analog/bindings/pwr_squelch_cc_python.cc, gr-analog/python/analog/bindings/pwr_squelch_ff_python.cc
Backport https://github.com/gnuradio/gnuradio/pull/5384
=> Correct message key for squelch_eob in Power Squelch (backport to maint-3.9)

gr-dtv/lib/dvbs2/dvbs2_modulator_bc_impl.cc
---
name: s2x constellation energy normalization
about: DVB-S2X.
title: 's2x constellation energy normalization'
labels: 'DVB-S2X'
assignees: ''
---
=> s2x constell energy normalization

docs/doxygen/Doxyfile.in, gr-utils/modtool/templates/gr-newmod/docs/doxygen/Doxyfile.in, gr-utils/modtool/templates/gr-newmod/docs/doxygen/other/doxypy.py
Backport https://github.com/gnuradio/gnuradio/pull/5381
Fixes #5407
=> doxygen: Remove obsolete COLS_IN_ALPHA_INDEX for doxygen 1.9 and later (backport to maint-3.9)

CHANGELOG.md, CMakeLists.txt
=> Release Candidate v3.8.5.0-rc1

CHANGELOG.md, CMakeLists.txt
=> Release Candidate v3.9.5.0-rc1

gr-blocks/include/gnuradio/blocks/transcendental.h, gr-blocks/python/blocks/bindings/transcendental_python.cc
Transcendental's documentation was useless if the user wasn't familiar with libc's math.h.
Fixed that.
Docs, and regenerated py bindings
blocks::transcendental
doxgen builds and looks better
=> blocks: document the supported operations in transcendental

CHANGELOG.md, CMakeLists.txt
Update to CHANGELOG and version number
=> Release v3.10.0.0-rc3

gr-utils/bindtool/templates/generic_python_cc.mako
---
title: 'pybind: fix rfnoc_block binding generation'
labels: ''
assignees: ''
---
Expand python bindings through all the parent classes of `gr::uhd::rfnoc_block`.
It was discovered in https://github.com/gnuradio/gnuradio/pull/5291#pullrequestreview-811554342.
=> pybind: fix rfnoc_block binding generation

CHANGELOG.md, CMakeLists.txt
Updated Changelog and patch
Hopefully this is it!
=> Release v3.10.0.0-rc4

CHANGELOG.md, CMakeLists.txt
Update the CHANGELOG for 3.10
Merge changelogs from maint-3.9 and maint-3.8
Get rid of -rc designation
=> Release v3.10.0.0

gr-qtgui/grc/qtgui_freq_sink_x.block.yml, gr-qtgui/grc/qtgui_sink_x.block.yml, gr-qtgui/grc/qtgui_waterfall_sink_x.block.yml, gr-qtgui/include/gnuradio/qtgui/SpectrumGUIClass.h, gr-qtgui/include/gnuradio/qtgui/form_menus.h, gr-qtgui/include/gnuradio/qtgui/freqdisplayform.h, gr-qtgui/include/gnuradio/qtgui/waterfalldisplayform.h, gr-qtgui/lib/SpectrumGUIClass.cc, gr-qtgui/lib/freq_sink_c_impl.cc, gr-qtgui/lib/freq_sink_f_impl.cc, gr-qtgui/lib/freqcontrolpanel.cc, gr-qtgui/lib/freqdisplayform.cc, gr-qtgui/lib/sink_c_impl.cc, gr-qtgui/lib/sink_f_impl.cc, gr-qtgui/lib/waterfalldisplayform.cc
Frequency sink FFT size selection PRs.
Backport #5400
Backport #5405
Backport #5442
Backport #5452
=> qtgui: frequency sink fft work (backport to maint-3.9)

grc/core/Constants.py, grc/core/params/dtypes.py, grc/gui/Application.py
(cherry picked from commit ad843023c65dc35aed73b7a4e4a78afbc7347f5d)
Backport https://github.com/gnuradio/gnuradio/pull/5421
=> grc: don't blacklist default fg id

gr-filter/lib/mmse_fir_interpolator_cc.cc, gr-filter/lib/mmse_fir_interpolator_ff.cc, gr-filter/lib/mmse_interp_differentiator_cc.cc, gr-filter/lib/mmse_interp_differentiator_ff.cc, gr-filter/lib/pfb_arb_resampler.cc, gr-filter/lib/pfb_synthesizer_ccf_impl.cc, gr-filter/lib/polyphase_filterbank.cc
Backport https://github.com/gnuradio/gnuradio/pull/5425
=> filter: Optimize filter setup a bit using the power of move (backport to maint-3.9)

gr-utils/blocktool/core/parseheader.py, gr-utils/blocktool/core/parseheader_generic.py, gr-utils/blocktool/tests/test_blocktool.py
Upstream fixed the issue in version 2.0.0,
the minimal version gnuradio depends on.
---
title: 'Remove pygccxml hack'
labels: ''
assignees: ''
---
=> Remove pygccxml hack

grc/blocks/snippet.block.yml
Default value for Priority parameter for Python Snippet block added in order to avoiding None value for it that leads to block parameter error
Signed-off-by: Armin Ghani <ghani.armin@gmail.com>
---
name: Default value for Priority parameter in Python Snippet block
about: Default value for Priority parameter for Python Snippet block added in order to avoiding None value for it that leads to block parameter error
title: 'Default value for Priority parameter in Python Snippet block'
labels: ''
assignees: ''
---
=> Default value for Priority parameter in Python Snippet block

README.md
Text to redirect users of the master branch over to main
=> docs: redirect master branch

gr-analog/grc/analog_random_uniform_source_x.block.yml
---
name: Fix C++ code generation
about: 
title: ''
labels: ''
assignees: ''
---
Code generation didn't work. No member variable created, and the construction had Python syntax.
Built and installed from scratch. Seems to work fine.
=> analog: Fix C++ code generation for random_uniform_source

cmake/Modules/GrPybind.cmake, gr-utils/bindtool/scripts/bind_intree_file.py, gr-utils/modtool/templates/gr-newmod/python/howto/bindings/bind_oot_file.py
---
title: 'pybind: remove unused command line argument'
labels: ''
assignees: ''
---
=> pybind: remove unused command line argument

grc/blocks/snippet.block.yml
Signed-off-by: Armin Ghani <ghani.armin@gmail.com>
(cherry picked from commit b2c9623cbd548bd86250759007b80b61bd4a2a06)
Backport https://github.com/gnuradio/gnuradio/pull/5464
=> python snippet: add default value for priority (backport to maint-3.10)

gr-uhd/grc/uhd_fpga_ddc.block.yml, gr-uhd/grc/uhd_fpga_duc.block.yml
Upstream changed names in
https://github.com/EttusResearch/uhd/commit/72e833e7bb71b2b2891ef5b07ada5aaf856a266a.
---
title: 'uhd: Fix ddc/duc block descriptor names'
labels: ''
assignees: ''
---
Upstream changed names in https://github.com/EttusResearch/uhd/commit/72e833e7bb71b2b2891ef5b07ada5aaf856a266a (included in UHD 4.0.0).
=> uhd: Fix ddc/duc block descriptor names

gnuradio-runtime/lib/hier_block2_detail.cc, gnuradio-runtime/lib/hier_block2_detail.h, gr-blocks/lib/CMakeLists.txt, gr-blocks/lib/qa_gr_hier_block2_derived.cc, gr-blocks/python/blocks/qa_hier_block2.py
Backport https://github.com/gnuradio/gnuradio/pull/5488
=> hier_block2: prevent crash/freeze after disconnection (backport to maint-3.10)

gr-blocks/grc/blocks.tree.yml, gr-blocks/grc/blocks_sigmf_sink_minimal.block.yml, gr-blocks/grc/blocks_sigmf_source_minimal.block.yml, gr-blocks/python/blocks/CMakeLists.txt, gr-blocks/python/blocks/__init__.py, gr-blocks/python/blocks/sigmf_sink_minimal.py
SigMF Minimal Blocks
Signed-off-by: Jacob Gilbert <jacob.gilbert@protonmail.com>
Co-authored-by: Johannes Demel <johannes@demels.de>
(cherry picked from commit 3069ff289ce9bac442215ab016dd3488b5206cbd)
Backport https://github.com/gnuradio/gnuradio/pull/5505
=> blocks: SigMF Minimal Blocks (backport to maint-3.10)

gr-qtgui/include/gnuradio/qtgui/SpectrumGUIClass.h
(cherry picked from commit a29814440e654b5a90170a0f700188b85d0efe52)
Backport https://github.com/gnuradio/gnuradio/pull/5512
=> qtgui: Initialize _updateTime variable (backport to maint-3.10)

gr-analog/grc/analog_wfm_rcv.block.yml, gr-analog/python/analog/fm_emph.py, gr-analog/python/analog/wfm_rcv.py
---
name: Add deempt_tau to WBFM rx block, to support broadcast in 96% of the world
about:
title: ''
labels: ''
assignees: ''
---
analog: WBFM rx. NBFM and WBFM PLL seems already fixed.
WBFM PLL was done in a66ee6c92c.
Threw together a quick WFM receiver, and it still works.
=> analog: Add deempt_tau to WBFM rx block

CHANGELOG.md, CMakeLists.txt
=> Release candidate v3.10.1.0-rc1

gnuradio-runtime/lib/hier_block2_detail.cc, gnuradio-runtime/lib/hier_block2_detail.h, gr-blocks/lib/CMakeLists.txt, gr-blocks/lib/qa_gr_hier_block2_derived.cc, gr-blocks/python/blocks/qa_hier_block2.py
Backport https://github.com/gnuradio/gnuradio/pull/5488
=> hier_block2: prevent crash/freeze after disconnection (backport to maint-3.9)

gr-qtgui/include/gnuradio/qtgui/SpectrumGUIClass.h
(cherry picked from commit a29814440e654b5a90170a0f700188b85d0efe52)
Backport https://github.com/gnuradio/gnuradio/pull/5512
=> qtgui: Initialize _updateTime variable (backport to maint-3.9)

gr-qtgui/include/gnuradio/qtgui/SpectrumGUIClass.h
(cherry picked from commit a29814440e654b5a90170a0f700188b85d0efe52)
Backport https://github.com/gnuradio/gnuradio/pull/5512
=> qtgui: Initialize _updateTime variable (backport to maint-3.8)

CHANGELOG.md, CMakeLists.txt
No changes since v3.10.1.0-rc1.
=> Release v3.10.1.0

gr-qtgui/python/qtgui/compass.py, gr-qtgui/python/qtgui/dialcontrol.py, gr-qtgui/python/qtgui/dialgauge.py, gr-qtgui/python/qtgui/digitalnumbercontrol.py, gr-qtgui/python/qtgui/ledindicator.py, gr-qtgui/python/qtgui/toggleswitch.py
'
---
QT GUI Compass, Led Indicator, Digital Number Control
fail with Type Error
Try
[show_controls](https://github.com/gnuradio/gnuradio/blob/main/gr-qtgui/examples/show_controls.grc)
[show_controls2](https://github.com/gnuradio/gnuradio/blob/main/gr-qtgui/examples/show_controls2.grc)
compass.py,  ledindicator.py, digitalnumbercontrol.py
Running the mentioned example
=> gr-qtgui: Fix some Type Errors in GUI Widgets

gr-qtgui/include/gnuradio/qtgui/eyedisplayform.h, gr-qtgui/lib/eyedisplayform.cc
---
Fixes #5487
Removes unneeded PopupMenu d_tr_level_act and tr_delay_act
and corresponding functions.
gr-qtgui eye sink
Ran the example in #5487
=> gr-qtgui: Eye Sink remove unnecessary request for trigger value

grc/core/FlowGraph.py, grc/core/schema_checker/flow_graph.py
---
Saving a flowgraph does not save the grc version
as this info is not part of the schema.
This pr adds grc_version to the schema definition and
saves the grc version string when the fg is saved.
Possibly
fixes #5521
All grc files, works with files with and  without grc_version set.
=> grc: store grc version info in metadata

cmake/Modules/GrPybind.cmake, gr-utils/bindtool/scripts/bind_intree_file.py, gr-utils/bindtool/templates/generic_python_cc.mako, gr-utils/blocktool/core/parseheader.py, gr-utils/blocktool/core/parseheader_generic.py, gr-utils/blocktool/tests/test_blocktool.py, gr-utils/modtool/templates/gr-newmod/python/howto/bindings/bind_oot_file.py
Backport #5448 
Backport #5457 
Backport #5465
=> pybind cleanups #5448 #5457 #5465 (backport to maint-3.10)

gr-qtgui/python/qtgui/compass.py, gr-qtgui/python/qtgui/dialcontrol.py, gr-qtgui/python/qtgui/dialgauge.py, gr-qtgui/python/qtgui/digitalnumbercontrol.py, gr-qtgui/python/qtgui/ledindicator.py, gr-qtgui/python/qtgui/toggleswitch.py
Backport https://github.com/gnuradio/gnuradio/pull/5541
=> gr-qtgui: Fix some Type Errors in GUI Widgets (backport to maint-3.10)

gr-qtgui/python/qtgui/compass.py, gr-qtgui/python/qtgui/dialcontrol.py, gr-qtgui/python/qtgui/dialgauge.py, gr-qtgui/python/qtgui/digitalnumbercontrol.py, gr-qtgui/python/qtgui/ledindicator.py, gr-qtgui/python/qtgui/toggleswitch.py
Backport https://github.com/gnuradio/gnuradio/pull/5541
=> gr-qtgui: Fix some Type Errors in GUI Widgets (backport to maint-3.9)

cmake/Modules/GrPybind.cmake, gr-utils/bindtool/scripts/bind_intree_file.py, gr-utils/bindtool/templates/generic_python_cc.mako, gr-utils/modtool/templates/gr-newmod/python/bindings/bind_oot_file.py
Backport #5457 
Backport #5465
=> pybind cleanups #5457 #5465 (backport to maint-3.9)

gr-digital/examples/packet/example_corr_est_and_clock_sync.grc, gr-digital/examples/packet/example_corr_est_and_phase_sync.grc
The examples
https://github.com/gnuradio/gnuradio/blob/main/gr-digital/examples/packet/example_corr_est_and_clock_sync.grc
https://github.com/gnuradio/gnuradio/blob/main/gr-digital/examples/packet/example_corr_est_and_phase_sync.grc
produce now output signals.
This is due to improper threshold settings.
Change the threshold method from absolute to dynamic
Fixes #5528
Running the examples
=> gr-digital/examples: Fix some improper parameter settings

grc/blocks/grc.tree.yml, grc/blocks/json_config.block.yml, grc/blocks/yaml_config.block.yml
Signed-off-by: John Sallay <jasallay@gmail.com>
It is frequently useful to use a config file to set the parameters for a flowgraph.  In GRC, a variable config block can be used, but there are several shortcomings.  Each config parameters in read in separately and requires a different block to be instantiated.  It also requires that a default value is specified, even if there isn't a sensible default.
I added in a few blocks, that, I believe, add to a cleaner user experience and allow for validation of the config file.  A json schema file can be used to ensure that all required fields are present and have valid values.  The config file is available in GRC as a dictionary, which can be used directly in parameters for other blocks.  i.e specify the Sample Rate as config["samp_rate"].
I built …
=> Add in config blocks with validation

gr-pdu/python/pdu/qa_add_system_time.py, gr-pdu/python/pdu/qa_time_delta.py
(cherry picked from commit 541774ccf7777399330fc73e48fc76151a99ff12)
Backport https://github.com/gnuradio/gnuradio/pull/5628
=> pdu: Fix flaky tests (backport to maint-3.10)

gr-qtgui/lib/edit_box_msg_impl.cc, gr-qtgui/python/qtgui/digitalnumbercontrol.py
Backport https://github.com/gnuradio/gnuradio/pull/5592
=> gr-qtgui: edit_box_msg, send message, only if return was pressed (backport to maint-3.10)

gr-qtgui/python/qtgui/range.py.cmakein
Signed-off-by: jb41997 <jb41997@users.noreply.github.com>
(cherry picked from commit beb2fb8156671fcd29a74ed998a0ac5ef400197e)
Backport https://github.com/gnuradio/gnuradio/pull/5640
=> qtgui: defualt style on success validate and text black on fail validate (backport to maint-3.10)

gr-qtgui/lib/edit_box_msg_impl.cc, gr-qtgui/python/qtgui/digitalnumbercontrol.py
Backport https://github.com/gnuradio/gnuradio/pull/5592
=> gr-qtgui: edit_box_msg, send message, only if return was pressed (backport to maint-3.9)

gr-qtgui/python/qtgui/range.py.cmakein
Signed-off-by: jb41997 <jb41997@users.noreply.github.com>
(cherry picked from commit beb2fb8156671fcd29a74ed998a0ac5ef400197e)
Backport https://github.com/gnuradio/gnuradio/pull/5640
=> qtgui: defualt style on success validate and text black on fail validate (backport to maint-3.9)

gr-trellis/python/trellis/bindings/pccc_decoder_blk_python.cc, gr-trellis/python/trellis/bindings/pccc_decoder_combined_blk_python.cc, gr-trellis/python/trellis/bindings/pccc_encoder_python.cc, gr-trellis/python/trellis/bindings/sccc_decoder_blk_python.cc, gr-trellis/python/trellis/bindings/sccc_decoder_combined_blk_python.cc, gr-trellis/python/trellis/bindings/sccc_encoder_python.cc, gr-trellis/python/trellis/bindings/viterbi_combined_python.cc, gr-trellis/python/trellis/qa_trellis.py
Backport #5671 
Backport #5683 
Backport #5707 
Note that 5707 is a rollup of
#5674
#5679
#5680
#5684
#5685
=> Trellis PyBind11 Rollup (backport to maint-3.10)

gr-blocks/include/gnuradio/blocks/file_sink_base.h, gr-blocks/lib/ctrlport_probe_c_impl.h, gr-blocks/lib/file_source_impl.h, gr-blocks/lib/message_strobe_impl.cc, gr-blocks/lib/message_strobe_random_impl.cc, gr-blocks/lib/probe_rate_impl.cc, gr-blocks/lib/probe_rate_impl.h, gr-blocks/lib/qa_set_msg_handler.cc, gr-blocks/lib/wavfile_sink_impl.h, gr-blocks/python/blocks/bindings/file_sink_base_python.cc
(cherry picked from commit d8f809d22c03dc0c4d8c93bcf669651c3032d823)
Backport https://github.com/gnuradio/gnuradio/pull/5653
=> blocks: Remove usage of Boost (backport to maint-3.10)

grc/compiler.py, grc/core/generator/hier_block.py
Backport https://github.com/gnuradio/gnuradio/pull/5547
=> grc: A generated python hier_block is written to the wrong directory (backport to maint-3.10)

gnuradio-runtime/lib/CMakeLists.txt
Fixup CMake linking logic.
---
name: Pull Request for gnuradio main
about: CMake
title: 'build on hurd'
labels: ''
assignees: ''
---
Small CMake logic change. Rather than keep this only in debian/patches.
This patch has been indebian/patches for a while.
=> build on hurd

gr-fec/lib/alist.cc, gr-fec/lib/conv_bit_corr_bb_impl.cc, gr-fec/lib/fec_mtrx_impl.cc, gr-trellis/lib/interleaver.cc, gr-video-sdl/lib/sink_s_impl.cc, gr-video-sdl/lib/sink_uc_impl.cc
In the case of an error, the library should instead return an
appropriate error code to the calling program which can then determine
how to handle the error, including performing any required
clean-up. In C++ the error can be thrown.
---
title: ''
labels: ''
assignees: ''
---
We provide C++ shared libraries for other people's application.
Calling exit() after logging some problem conditions is harsh.
The friendly C++ way is for our library functions to throw and error,
that maybe the main application can then do something more sensible to
the user than stop running.
This has been in debian/patches
=> shared library throw not exit

gnuradio-runtime/lib/CMakeLists.txt
Backport #5728 
---
name: Pull request for gnuradio maint-3.10 branch
about: CMake
title: 'build on hurd'
labels: ''
assignees: ''
---
Small CMake logic change. Rather than keep this only in debian/patches.
This patch has been indebian/patches for a while.
=> build on hurd (backport to maint-3.10)

gr-vocoder/examples/loopback-codec2.grc, gr-vocoder/examples/loopback-gsmfr.grc, gr-vocoder/grc/vocoder_alaw_decode_bs.block.yml, gr-vocoder/grc/vocoder_alaw_encode_sb.block.yml, gr-vocoder/grc/vocoder_codec2_decode_ps.block.yml, gr-vocoder/grc/vocoder_codec2_encode_sp.block.yml, gr-vocoder/grc/vocoder_cvsd_decode.block.yml, gr-vocoder/grc/vocoder_cvsd_decode_bs.block.yml, gr-vocoder/grc/vocoder_cvsd_encode.block.yml, gr-vocoder/grc/vocoder_cvsd_encode_sb.block.yml, gr-vocoder/grc/vocoder_g721_decode_bs.block.yml, gr-vocoder/grc/vocoder_g721_encode_sb.block.yml, gr-vocoder/grc/vocoder_g723_24_decode_bs.block.yml, gr-vocoder/grc/vocoder_g723_24_encode_sb.block.yml, gr-vocoder/grc/vocoder_g723_40_decode_bs.block.yml, gr-vocoder/grc/vocoder_g723_40_encode_sb.block.yml, gr-vocoder/grc/vocoder_gsm_fr_decode_ps.block.yml, gr-vocoder/grc/vocoder_gsm_fr_encode_sp.block.yml, gr-vocoder/grc/vocoder_ulaw_decode_bs.block.yml, gr-vocoder/grc/vocoder_ulaw_encode_sb.block.yml
Backport #5729 
---
name: Pull request for gnuradio maint-3.10 branch
about: gr-vocoder
title: 'Add C++ generation support to gr-vocoder'
labels: ''
assignees: ''
---
Many gnuradio blocks are not ready for gnuradio-companion to generate C++ code.
This adds yaml details to help improve that for gr-vocoder blocks
This patch has been indebian/patches for a while.
=> cppgen: Add C++ generation support to gr-vocoder (backport to maint-3.10)

gr-blocks/grc/xmlrpc_server.block.yml
Signed-off-by: Paul Atreides <maud.dib1984@gmail.com>
---
title: ''
labels: ''
assignees: ''
---
XMLRPC Server block documentation: in example section, assign ServerProxy to variable
incorrect python syntax for example client code
mentioned on IRC 'Docs' channel
XMLRPC Server
no testing, doc section only, confirmed correct number of spaces
- [x ] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [x ] I have squashed my commits to have one significant change per commit. 
- x[ ] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed)
- [x ] My code follows the code style of …
=> Correcting XMLRPC Server Block Doc

gr-uhd/lib/usrp_block_impl.cc, gr-uhd/lib/usrp_block_impl.h, gr-uhd/lib/usrp_sink_impl.cc, gr-uhd/lib/usrp_source_impl.cc
Backport https://github.com/gnuradio/gnuradio/pull/5652
=> uhd: Replace boost::dynamic_bitset with std::vector<bool> (backport to maint-3.10)

gr-qtgui/grc/qtgui_freq_sink_x.block.yml, gr-qtgui/grc/qtgui_sink_x.block.yml, gr-qtgui/grc/qtgui_waterfall_sink_x.block.yml, grc/core/blocks/block.py
Backport https://github.com/gnuradio/gnuradio/pull/5763
=> grc: Additional error messages for assertions (backport to maint-3.10)

gr-pdu/python/pdu/qa_time_delta.py
(cherry picked from commit 4a0642475821f1740d2b116edb8e7a569c5e8ef1)
Backport https://github.com/gnuradio/gnuradio/pull/5764
=> pdu: Increase tolerance in flaky test again (backport to maint-3.10)

gr-qtgui/include/gnuradio/qtgui/form_menus.h, gr-qtgui/lib/const_sink_c_impl.cc, gr-qtgui/lib/eye_sink_c_impl.cc, gr-qtgui/lib/eye_sink_f_impl.cc, gr-qtgui/lib/freq_sink_c_impl.cc, gr-qtgui/lib/freq_sink_f_impl.cc, gr-qtgui/lib/histogram_sink_f_impl.cc, gr-qtgui/lib/sink_c_impl.cc, gr-qtgui/lib/sink_f_impl.cc, gr-qtgui/lib/time_raster_sink_b_impl.cc, gr-qtgui/lib/time_raster_sink_f_impl.cc, gr-qtgui/lib/time_sink_c_impl.cc, gr-qtgui/lib/time_sink_f_impl.cc, gr-qtgui/lib/vector_sink_f_impl.cc, gr-qtgui/lib/waterfall_sink_c_impl.cc, gr-qtgui/lib/waterfall_sink_f_impl.cc
(cherry picked from commit aa1de36b95fbd08893b536f229fb3956d66015a4)
Backport https://github.com/gnuradio/gnuradio/pull/5760
=> qtgui: Remove conditional code targeting Qt 4 (backport to maint-3.10)

gr-blocks/grc/xmlrpc_server.block.yml
Signed-off-by: Paul Atreides <maud.dib1984@gmail.com>
(cherry picked from commit 126f2ffc4de67fdc336f28d57d4e4f4b9b462a40)
Backport https://github.com/gnuradio/gnuradio/pull/5765
=> Correcting XMLRPC Server Block Doc (backport to maint-3.10)

gr-iio/grc/iio_pluto_sink.block.yml
Signed-off-by: Adrian Suciu <adrian.suciu@analog.com>
(cherry picked from commit bb99b710aaaa5e1ac4b94b237c99224a71a439fe)
Backport #5788
=> gr-iio: fix grc pluto sink attenuation callback (backport to maint-3.10)

cmake/Modules/GrPython.cmake
Backport #5739 
Backport #5784
=> cmake: grpython use posix and nt prefix schemes (backport to maint-3.10)

gr-iio/lib/device_sink_impl.h, gr-iio/lib/device_source_impl.h, gr-qtgui/include/gnuradio/qtgui/timeRasterGlobalData.h, gr-qtgui/include/gnuradio/qtgui/waterfallGlobalData.h
=> iio and qtgui: Fix inconsistent override warnings (backport to maint-3.10)

gr-filter/lib/filterbank_vcvcf_impl.cc, gr-filter/python/filter/qa_filterbank.py
(cherry picked from commit 01e9a0a10fb767d94cf75dd7c8e6d41ae3fcc61c)
Backport https://github.com/gnuradio/gnuradio/pull/5753
=> filter: Fix various bugs in Generic Filterbank (backport to maint-3.9)

gr-digital/lib/crc16_async_bb_impl.cc, gr-digital/lib/crc16_async_bb_impl.h, gr-digital/lib/crc32_async_bb_impl.cc
Backport https://github.com/gnuradio/gnuradio/pull/5830
=> digital: Fix CRC checking in Async CRC16 and Async CRC32 blocks (backport to maint-3.10)

gnuradio-runtime/include/gnuradio/high_res_timer.h, gnuradio-runtime/python/gnuradio/gr/bindings/high_res_timer_python.cc
=> Fix Mach-kernel timebase

gnuradio-runtime/lib/pmt/pmt_serialize.cc
This is a continuation of the effort to remove Boost from GNU Radio.
In an effort to speed up PMT serialization (#3320, #3369), `boost::endian` was introduced. It seems that most of the performance gain was from other optimizations, though. Switching back to bit shifts for endianness conversion comes at a small performance cost (~25%) but I think it's worth it to be rid of Boost. If there's a way to improve performance further, I'd be happy to try it.
I tested performance using the Python script provided in #3320. Before:
```
U8 VECTOR
0.14483952522277832
128
U16 VECTOR
0.22285586595535278
128
F32 VECTOR
0.18961408734321594
128
C32 VECTOR
0.1912863850593567
128
```
After:
```
U8 VECTOR
0.1397770643234253
128
U16 VECTOR
0.24227461218833923
128
F32 VECTOR
0.23737838864326477
128
C32 VECTOR …
```
=> runtime: Replace boost::endian with standard C++

grc/core/params/param.py
If a variable consists of an aritmetic expression and is used in another
expression the expression should be put in parentheses
See example in #5735
To avoid redundant parentheses check if the expression contains + or - operator
This is a more general solution than #5735 and does not need changes in yml files and works for python and cpp code generation.
=> grc: Add parentheses on arithmetic expressions

gnuradio-runtime/include/gnuradio/high_res_timer.h, gnuradio-runtime/python/gnuradio/gr/bindings/high_res_timer_python.cc
Signed-off-by: wakass <wakass@users.noreply.github.com>
(cherry picked from commit 3db403b3dcf272eebd85ac2c15934fa3ade12abd)
Backport https://github.com/gnuradio/gnuradio/pull/5910
=> Fix Mach-kernel timebase (backport to maint-3.10)

gnuradio-runtime/include/gnuradio/high_res_timer.h, gnuradio-runtime/python/gnuradio/gr/bindings/high_res_timer_python.cc
Signed-off-by: wakass <wakass@users.noreply.github.com>
(cherry picked from commit 3db403b3dcf272eebd85ac2c15934fa3ade12abd)
Backport https://github.com/gnuradio/gnuradio/pull/5910
=> Fix Mach-kernel timebase (backport to maint-3.9)

.ci_support/linux_64_python3.9.____cpython.yaml, .ci_support/migrations/qt515.yaml, .ci_support/osx_64_python3.9.____cpython.yaml, .ci_support/win_64_python3.9.____cpython.yaml, .packaging/conda_recipe/build.sh, .packaging/conda_recipe/meta.yaml, .packaging/conda_recipe/yum_requirements.txt, .scripts/build_steps.sh
Conda-forge has (finally) upgraded Qt to version 5.15, and this brings a change in the dependency name from `qt` to `qt-main`. This PR updates the recipe to be compatible with the new `qt-main` package and re-renders the conda CI, allowing the use of newer versions of a number of dependencies.
Conda CI
This mirrors changes recently made with the conda-forge gnuradio feedstock, and we won't merge until the CI passes.
=> CI: Update conda recipe for Qt 5.15 and re-render

gr-qtgui/grc/qtgui_waterfall_sink_x.block.yml
When generating cpp code for the waterfall sink (float),
the setting of the Spectrum Width ( Half, Full ) is ignored
and always set to Full
Fixed by generating correct cpp code.
Just set up a flowgraph with float signal source and float waterfall sink.
Select the Spectrum Width and have a look at the running flowgraph
=> gr-qtgui: waterfall sink float Spectrum Width setting fails

gnuradio-runtime/lib/block.cc
fmtlib makes it easier to read the outcome of formatted strings. This is
another place where fmtlib may show its benefits.
---
name: fmt: Switch to fmtlib formatted strings
about: Modernize code base with fmtlib.
title: ''
labels: ''
assignees: ''
---
In the future, it should be possible to find and replace `fmt::format` with `std::format`.
=> fmt: Switch to fmtlib formatted strings

gr-filter/python/filter/pfb.py
Fix from @777arc #5567 
Fixes #4015
=> filter: pfb channelizer demo fix

gr-qtgui/lib/FrequencyDisplayPlot.cc, gr-qtgui/lib/VectorDisplayPlot.cc, gr-qtgui/lib/WaterfallDisplayPlot.cc
---
title: ''
labels: ''
assignees: ''
---
On newer versions of GCC, `cmath` is not included by default and must be explicitly added with `include`.  If it is missing the build will fail because of undefined variables.
Fixes the failure we saw in Homebrew CI on Linux: https://github.com/Homebrew/homebrew-core/pull/105154
This has no runtime effects - it only fixes a compilation error.
A patch with the same fix was run in https://github.com/Homebrew/homebrew-core/pull/105154 and the build now succeeds.
=> add missing includes to fix build with newer versions of GCC

gr-trellis/python/trellis/bindings/metrics_python.cc
The metrics_python.cc file does not contain the correct bindings.
The missing bindings where added manually.
Fixes #5985
Tested with example from #5985
=> gr-trellis: add correct python bindings for metrics

.github/workflows/make-test.yml, gr-zeromq/lib/base_impl.cc, gr-zeromq/lib/pub_msg_sink_impl.cc, gr-zeromq/lib/pub_msg_sink_impl.h, gr-zeromq/lib/pull_msg_source_impl.cc, gr-zeromq/lib/pull_msg_source_impl.h, gr-zeromq/lib/push_msg_sink_impl.cc, gr-zeromq/lib/push_msg_sink_impl.h, gr-zeromq/lib/push_sink_impl.cc, gr-zeromq/lib/rep_msg_sink_impl.cc, gr-zeromq/lib/rep_msg_sink_impl.h, gr-zeromq/lib/rep_sink_impl.cc, gr-zeromq/lib/req_msg_source_impl.cc, gr-zeromq/lib/req_msg_source_impl.h, gr-zeromq/lib/sub_msg_source_impl.cc, gr-zeromq/lib/sub_msg_source_impl.h, gr-zeromq/lib/sub_source_impl.cc, gr-zeromq/lib/zmq_common_impl.h
Adds Ubuntu 22.04 worker into the CI
Will be covered by CI
=> ci: add ubuntu 22.04 worker

bench/cuda/bm_copy.cc, utils/blockbuilder/scripts/filters.py, utils/blockbuilder/templates/blockname.grc.j2
A couple of small fixes 
1) build errors with cuda enabled
2) domains not working because "untyped" was not being treated as valid type and added to lookup
3) enums in grc were not consistently capitalized with the rest
=> 4.0: GRC and enum cleanup

.ci_support/linux_64_python3.9.____cpython.yaml, .ci_support/migrations/qt515.yaml, .ci_support/osx_64_python3.9.____cpython.yaml, .ci_support/win_64_python3.9.____cpython.yaml, .packaging/conda_recipe/build.sh, .packaging/conda_recipe/meta.yaml, .packaging/conda_recipe/yum_requirements.txt, .scripts/build_steps.sh
Backport https://github.com/gnuradio/gnuradio/pull/5951
=> CI: Update conda recipe for Qt 5.15 and re-render (backport to maint-3.10)

.github/workflows/make-test.yml, gr-zeromq/lib/base_impl.cc, gr-zeromq/lib/pub_msg_sink_impl.cc, gr-zeromq/lib/pub_msg_sink_impl.h, gr-zeromq/lib/pull_msg_source_impl.cc, gr-zeromq/lib/pull_msg_source_impl.h, gr-zeromq/lib/push_msg_sink_impl.cc, gr-zeromq/lib/push_msg_sink_impl.h, gr-zeromq/lib/push_sink_impl.cc, gr-zeromq/lib/rep_msg_sink_impl.cc, gr-zeromq/lib/rep_msg_sink_impl.h, gr-zeromq/lib/rep_sink_impl.cc, gr-zeromq/lib/req_msg_source_impl.cc, gr-zeromq/lib/req_msg_source_impl.h, gr-zeromq/lib/sub_msg_source_impl.cc, gr-zeromq/lib/sub_msg_source_impl.h, gr-zeromq/lib/sub_source_impl.cc, gr-zeromq/lib/zmq_common_impl.h
Backport https://github.com/gnuradio/gnuradio/pull/5980
=> ci: add ubuntu 22.04 worker (backport to maint-3.10)

gr-qtgui/lib/FrequencyDisplayPlot.cc, gr-qtgui/lib/VectorDisplayPlot.cc, gr-qtgui/lib/WaterfallDisplayPlot.cc
Signed-off-by: danielnachun <daniel.nachun@gmail.com>
(cherry picked from commit 45652a6ebf53349aa7f67e6da2032a6d272447a0)
Backport https://github.com/gnuradio/gnuradio/pull/6002
=> add missing includes (backport to maint-3.10)

.github/pull_request_template.md
Remove the section at the top and the top level header
=> gh: simplify PR template

gr-qtgui/grc/qtgui_time_sink_x.block.yml
This pr adds a cpp template to the time_sink
(cherry picked from commit d25a59cbb61992237b8d46db85be9c40ed5adf9e)
Backport https://github.com/gnuradio/gnuradio/pull/5885
=> gr-qtgui: time_sink add cpp template (backport to maint-3.10)

gnuradio-runtime/lib/block.cc, gr-analog/include/gnuradio/analog/fastnoise_source.h, gr-analog/include/gnuradio/analog/noise_source.h, gr-analog/python/analog/bindings/fastnoise_source_python.cc, gr-analog/python/analog/bindings/noise_source_python.cc, gr-digital/lib/header_payload_demux_impl.cc
Backport #5990 
Backport #5988 
Backport #6014
=> Various logging and comment fixes 5990 5988 6014 (backport to maint-3.10)

blocklib/fileio/file_source/file_source_cpu.cc, blocklib/zeromq/pull_msg_source/pull_msg_source_cpu.cc, gr/gr.conf.yml, gr/include/gnuradio/logger.h, gr/lib/logger.cc, kernel/lib/fft/fftw_fft.cc, kernel/lib/filter/fft_filter.cc, meson.build
In prep for C++20ification, overhauled the logging header: we should actually be doing perfect forwarding. Don't remember why I didn't do that on main – might need to backport.
#6035 
I hoped this would solve the "spdlog fails with C++20", alas it didn't. However, this is still cleaner, and cleans up the API by removing levels that we were dragging along from 3.7 that are in basically no use.
Lögging.
=> C++20: Fix logging, set std to C++20

gnuradio-runtime/include/gnuradio/block.h, gnuradio-runtime/python/gnuradio/gr/bindings/block_python.cc, gr-blocks/include/gnuradio/blocks/control_loop.h, gr-blocks/python/blocks/bindings/control_loop_python.cc, gr-blocks/python/blocks/qa_python_message_passing.py, gr-digital/examples/snr_estimators.py, gr-digital/include/gnuradio/digital/crc_check.h, gr-digital/lib/clock_tracking_loop.h, gr-digital/lib/interpolating_resampler.cc, gr-digital/python/digital/bindings/crc_check_python.cc, gr-digital/python/digital/soft_dec_lut_gen.py, gr-fec/python/fec/extended_decoder.py, gr-fec/python/fec/extended_tagged_decoder.py, gr-filter/include/gnuradio/filter/fft_filter.h, gr-filter/include/gnuradio/filter/firdes.h, gr-filter/lib/gen_interpolator_taps/diff_objective_fct.c, gr-filter/python/filter/bindings/fft_filter_python.cc, gr-filter/python/filter/bindings/firdes_python.cc, gr-utils/plot_tools/gr_plot_qt, gr-vocoder/examples/loopback-codec2.grc, gr-vocoder/examples/loopback-gsmfr.grc, grc/core/generator/cpp_top_block.py
---
title: ''
labels: ''
assignees: ''
---
Fix various user and non-user facing typos
n/a
n/a
none
=> Fix various typos

gr/include/gnuradio/block.h, gr/lib/block.cc, gr/python/gr/bindings/block_pybind.cc, test/cuda/qa_scheduler_nbt_cuda_copy.cc, utils/modtool/newblock/.gitignore, utils/modtool/newblock/newblock_cpu_t.cc, utils/modtool/newblock/newblock_cpu_t.h, utils/modtool/newmod/blocklib/newmod/test/meson.build, utils/modtool/newmod/meson.build
- Updates to modtool templates
- Building of CUDA benchmarks
- External access to parameters for python blocks
=> 4.0: Changes needed for GRCon Tutorial

utils/blockbuilder/templates/blockname.h.j2, utils/blockbuilder/templates/blockname_pybind.cc.j2, utils/blockbuilder/templates/blockname_pybind_templated.cc.j2, utils/blockbuilder/templates/blockname_pyshell.h.j2, utils/blockbuilder/templates/blockname_pyshell_templated.h.j2, utils/blockbuilder/templates/blockname_templated.h.j2, utils/blockbuilder/templates/macros.j2
Follows from #6132 with some additional safeguards in the code generation to not put python stuff in non python blocks
=> 4.0: Additional python block method wrapping

gr/include/gnuradio/block.h, gr/lib/block.cc, gr/python/gr/bindings/block_pybind.cc, schedulers/nbt/include/gnuradio/schedulers/nbt/scheduler_nbt.h, schedulers/nbt/lib/scheduler_nbt.cc, schedulers/nbt/python/schedulers/nbt/bindings/scheduler_nbt_pybind.cc, test/cuda/qa_scheduler_nbt_cuda_copy.cc, utils/modtool/newblock/.gitignore, utils/modtool/newblock/newblock_cpu_t.cc, utils/modtool/newblock/newblock_cpu_t.h, utils/modtool/newmod/blocklib/newmod/test/meson.build, utils/modtool/newmod/meson.build
An assortment of changes encountered while preparing the latest tutorial
=> 4.0: Updates to modtool, parameter access, scheduler options

gnuradio-runtime/lib/CMakeLists.txt
Some tests use spdlog indirectly, but avoid linkage through the gnuradio::gnuradio-runtime target.
gnuradio-runtime's `qa_runtime` and `_math`
Didn't build before on clang, builds now.
- [-] I have added tests to cover my changes, and all previous tests pass.
=> runtime/qa: link against spdlog when not linking through the runtime library

README.md, grc/scripts/meson.build
gnuradio-companion has permissions rwxr--r-- but should have rwxr-xr-x.
Fixed typo in README
=> dev-4.0 Set grc permissions correctly

.github/workflows/build_and_test.yml, blocklib/soapy/hackrf_sink/hackrf_sink.yml, blocklib/soapy/python/gnuradio/soapy/bindings/block_pybind.cc, blocklib/soapy/sink/sink.yml, blocklib/soapy/sink/sink_cpu.cc, blocklib/soapy/sink/sink_cpu.h, blocklib/soapy/source/source_cpu.cc
Adds soapy sink but without the burst tag handling
=> 4.0: soapy: add sink with hackrf wrapper

gr/include/gnuradio/high_res_timer.h, gr/include/gnuradio/meson.build, kernel/include/gnuradio/kernel/fft/meson.build, kernel/include/gnuradio/kernel/filter/meson.build, kernel/include/gnuradio/kernel/meson.build
Some small changes due to headers not being installed correctly in kernel and high_res_timer.h
=> 4.0: Install some more headers

gr-blocks/include/gnuradio/blocks/blockinterleaving.h, gr-blocks/lib/blockinterleaving.cc
Fixes another missing `#include` that cropped up with building the 3.10.4.0 conda package on Windows, presumably because of using Boost 1.78 compared to the conda CI which uses an older Boost.
Fixed the build for the conda-forge `gnuradio` package on Windows.
=> blocks: Including missing `#include <vector>` in blockinterleaver

.conda-forge.yml, .github/workflows/conda-rerender-ci.yml, .packaging/conda_recipe/README
This provides a Github Action for running conda-smithy to "re-render" (update) the conda CI scripts. To trigger the action, one must start a PR comment with "/rerender". If there are any changes, the action will commit them directly to the PR branch (I think this will work as long as the PR submitter has checked "Allow edits and access to secrets by maintainers" when creating the PR). Overall, this should make it easier for the GNU Radio maintainers to keep the conda CI updated.
I'm open to other ways of triggering this, but I think this is natural way to allow contributors to update the conda CI through an existing PR after discovering it to be necessary (e.g. the CI is failing and a re-render would fix it).
None
CI
The action ran successfully on my fork here: …
=> CI: Add workflow to update conda CI by commenting in PR with "/rerender"

gr-uhd/examples/grc/rfnoc_keep1.grc, gr-uhd/grc/CMakeLists.txt, gr-uhd/grc/uhd.tree.yml, gr-uhd/grc/uhd_rfnoc_keep_one_in_n.block.yml
Note: This should be merged after #6235.
=> uhd: rfnoc: Add bindings and example for keep 1 in N

gr-analog/python/analog/qa_ctcss_squelch.py
As noted in #5973, the qa_ctcss_squelch test fails on i686 with the following errors:
```
FAIL: test_ctcss_squelch_002 (__main__.test_ctcss_squelch)
File "/builddir/gnuradio-3.10.3.0/gr-analog/python/analog/qa_ctcss_squelch.py", line 70, in test_ctcss_squelch_002
self.assertFloatTuplesAlmostEqual(expected_result, result_data, 4)
File "/builddir/gnuradio-3.10.3.0/gnuradio-runtime/python/gnuradio/gr_unittest.py", line 96, in assertFloatTuplesAlmostEqual
self.assertEqual(len(a), len(b))
AssertionError: 39 != 29
FAIL: test_ctcss_squelch_003 …
```
=> analog: Use realistic signals for CTCSS squelch tests

gr-uhd/examples/grc/rfnoc_keep1.grc, gr-uhd/grc/CMakeLists.txt, gr-uhd/grc/uhd.tree.yml, gr-uhd/grc/uhd_rfnoc_keep_one_in_n.block.yml, gr-uhd/grc/uhd_rfnoc_rx_streamer.block.yml, gr-uhd/grc/uhd_rfnoc_tx_streamer.block.yml, gr-uhd/include/gnuradio/uhd/rfnoc_block.h, gr-uhd/lib/rfnoc_block.cc, gr-uhd/python/uhd/bindings/docstrings/rfnoc_block_pydoc_template.h, gr-uhd/python/uhd/bindings/rfnoc_block_python.cc
Backport #6220 
Backport #6242 
Backport #6241 
Backport #6236
=> Backport rfnoc improvements

gr-blocks/python/blocks/qa_moving_average.py, gr-blocks/python/blocks/qa_mute.py, gr-blocks/python/blocks/qa_repack_bits_bb.py, gr-digital/lib/constellation.cc, gr-digital/python/digital/qa_constellation.py, gr-digital/python/digital/qa_ofdm_frame_equalizer_vcvc.py, gr-fec/lib/decode_ccsds_27_fb_impl.cc, gr-fec/lib/decode_ccsds_27_fb_impl.h, gr-fec/lib/viterbi/viterbi.cc, gr-fec/python/fec/qa_ecc_ccsds_27.py, gr-fec/python/fec/qa_fecapi_ldpc.py, gr-fft/python/fft/qa_window.py
Backport #6246 
Backport #6234 
Backport #6247 
Backport #6248 
Backport #6250 
Backport #6249 
Backport #6251 
Backport #6255
=> Backport lots of argilo qa fixes to maint-3.10

.ci_support/linux_64_numpy1.21python3.10.____cpython.yaml, .ci_support/osx_64_numpy1.21python3.10.____cpython.yaml, .ci_support/win_64_numpy1.21python3.10.____cpython.yaml, .github/workflows/conda-build.yml, .packaging/conda_recipe/build.sh, .packaging/conda_recipe/conda_build_config.yaml, .packaging/conda_recipe/meta.yaml, .scripts/build_steps.sh, .scripts/run_osx_build.sh
This updates the dependencies in the conda recipe to remove `libcblas` following #5913, add `pytest` for running grc_tests, and synchronize with the conda-forge recipe. It also re-renders the conda CI scripts to build against newer dependency versions and fix #6227.
Fixes #6227
CI
CI passes
=> CI: conda: Update recipe and re-render

blocklib/analog/lib/meson.build, blocklib/audio/lib/meson.build, blocklib/blocks/lib/meson.build, blocklib/fec/lib/meson.build, blocklib/fft/lib/meson.build, blocklib/fileio/lib/meson.build, blocklib/filter/lib/meson.build, blocklib/math/lib/meson.build, blocklib/soapy/lib/meson.build, blocklib/streamops/lib/meson.build, blocklib/zeromq/lib/meson.build, gr/lib/meson.build, kernel/analog/lib/meson.build, kernel/digital/lib/meson.build, kernel/filter/lib/meson.build, kernel/math/lib/meson.build
Trying to build an OOT fails as the required gnuradio libs,
for instance gnuradio-runtime ,  are not added, as the pkgconfig files do not contain informations about the libs. 
pkgconf --libs gnuradio-runtime
has no results. 
But these informations are needed for linking
This patch adds the library informations to the *.pc files. So pkgconf --libs gnuradio-runtime now gives
-L/usr/local/gnuradio-4.0/lib64 -lgnuradio-runtime
Run
pkgconf --libs gnuradio-runtime
before and after this patch
=> 4.0: Fails to link out of tree module

gr-digital/lib/crc32_async_bb_impl.cc, gr-digital/lib/crc32_bb_impl.cc
Various CRC32 test cases fail on big-endian platforms. This occurs because they expect the CRC to be little-endian, while the blocks write the CRC in machine order.
I think it's justified to expect that these blocks behave the same on all platforms, so I've rewritten them to always use little-endian. This is technically a breaking change on big-endian platforms, but these platforms are very rare. I'd be surprised if anyone depends on the CRC32 blocks producing big-endian output there.
The failing tests are:
```
FAIL: test_crc32 (__main__.qa_crc32_async_bb)
File …
```
=> digital: Use little-endian for CRC32 regardless of platform

utils/modtool/newmod/blocklib/newmod/lib/meson.build, utils/modtool/newmod/meson.build
Trying to build an OOT module fails with
meson.build:70:0: ERROR: Command "/usr/bin/python3 /usr/local/oot4/share/utils/blockbuilder/scripts/gen_meson.py /home/schroer/gnuradiocomponents/gr4-funcube/blocklib --enable_python"
failed with status 2.
The build scripts are found in the gnuradio install location not in the at this time non existing oot location.
This is fixed with this pr.
Further spdlog is a dependency, so the dependency must be referenced.
To use the generated module , a pkgconf file should be generated.
Try to generate and oot module with prefix != gnuradio_install_prefix.
=> dev-4.0: Building modules Out of Tree fails

gr-dtv/grc/dtv_dvbt_bit_inner_deinterleaver.block.yml, gr-dtv/grc/dtv_dvbt_bit_inner_interleaver.block.yml, gr-dtv/lib/dvbt/dvbt_bit_inner_deinterleaver_impl.cc, gr-dtv/lib/dvbt/dvbt_bit_inner_interleaver_impl.cc
Fixes https://github.com/gnuradio/gnuradio/issues/6345
=> gr-dtv: Fix segfaults with DVB-T bit interleavers

blocklib/filter/fir_filter/fir_filter.yml, blocklib/filter/fir_filter/fir_filter_cpu.cc, blocklib/filter/fir_filter/fir_filter_cpu.h, blocklib/filter/fir_filter/qa_fir_filter.py, blocklib/filter/pfb_arb_resampler/pfb_arb_resampler.yml, blocklib/filter/pfb_arb_resampler/pfb_arb_resampler_cpu.cc, blocklib/filter/pfb_arb_resampler/pfb_arb_resampler_cpu.h, blocklib/filter/pfb_arb_resampler/qa_pfb_arb_resampler.py, gr/include/gnuradio/block.h, gr/include/gnuradio/sync_block.h, gr/lib/buffer_management.cc, kernel/filter/include/gnuradio/kernel/filter/meson.build, kernel/filter/include/gnuradio/kernel/filter/optfir.h, kernel/filter/include/gnuradio/kernel/filter/pm_remez.h, kernel/filter/lib/meson.build, kernel/filter/lib/optfir.cc, kernel/filter/lib/pm_remez.cc, kernel/filter/python/kernel/filter/bindings/pm_remez_pybind.cc
Since 4.0 doesn't have `history()` or `forecast()`, this PR introduces a few convenience methods to simplify block development and the contract with the scheduler
- noconsume(), declare_noconsume(): allow blocks to keep track of how many samples they don't plan on consuming
- enforce_constraints(): gets called prior to work (scheduler calls `do_work`) and allows adjustment of the input/output nitems to meet the block requirements (whatever they may be)
Two methods added so the scheduler can know the minimum required output buffer
- `min_required_output_buffer()`: by default just `output_multiple`
- `min_required_upstream_buffer()`: the requirement from a reader based on its output to what the upstream block needs to provide
This also adds in changes to `fir_filter` and `pfb_arb_resampler` …
=> 4.0: History and Forecast lookalikes

gr-fec/include/gnuradio/fec/ldpc_G_matrix.h, gr-fec/lib/ldpc_G_matrix_impl.cc, gr-fec/lib/ldpc_G_matrix_impl.h, gr-fec/lib/ldpc_gen_mtrx_encoder_impl.cc, gr-fec/lib/ldpc_par_mtrx_encoder_impl.cc, gr-fec/python/fec/bindings/docstrings/ldpc_G_matrix_pydoc_template.h, gr-fec/python/fec/bindings/ldpc_G_matrix_python.cc, gr-fec/python/fec/qa_fecapi_ldpc.py
Backport #6254 
Backport #6256 
Backport #6279
=> fec: LDPC Updates (backport to maint-3.10)

gr-analog/lib/ctcss_squelch_ff_impl.cc, gr-analog/python/analog/qa_ctcss_squelch.py
Backport #6257 
Backport #6258
=> analog: CTCSS Squelch test updates

.packaging/conda_recipe/bld.bat, gr-utils/modtool/tests/test_modtool.py, gr-utils/modtool/tools/util_functions.py
Backport https://github.com/gnuradio/gnuradio/pull/6282
=> utils: Allow fallback when readline is not available (backport to maint-3.10)

.packaging/conda_recipe/bld.bat, cmake/Modules/GrTest.cmake, gr-dtv/python/dtv/qa_dtv.py
Backport https://github.com/gnuradio/gnuradio/pull/6276
=> cmake: Fix excess quoting of srcdir environment variable (backport to maint-3.10)

.github/workflows/make-test.yml, .packaging/conda_recipe/build.sh, gr-qtgui/grc/qtgui_msgcheckbox.block.yml, gr-qtgui/grc/qtgui_msgdigitalnumbercontrol.block.yml, gr-qtgui/grc/qtgui_range.block.yml, gr-qtgui/grc/qtgui_togglebutton.block.yml, gr-qtgui/grc/qtgui_toggleswitch.block.yml, gr-qtgui/python/qtgui/__init__.py, gr-qtgui/python/qtgui/distanceradar.py, gr-qtgui/python/qtgui/msgcheckbox.py, gr-qtgui/python/qtgui/range.py.cmakein
Backport https://github.com/gnuradio/gnuradio/pull/6316
Backport https://github.com/gnuradio/gnuradio/pull/6317
Backport https://github.com/gnuradio/gnuradio/pull/6296
Backport https://github.com/gnuradio/gnuradio/pull/6342
Backport https://github.com/gnuradio/gnuradio/pull/6344
=> qtgui: code generation fixes, enable QA (backport to maint-3.10)

.ci_support/linux_64_numpy1.21python3.10.____cpython.yaml, .ci_support/osx_64_numpy1.21python3.10.____cpython.yaml, .ci_support/win_64_numpy1.21python3.10.____cpython.yaml, .github/workflows/conda-build.yml, .packaging/conda_recipe/build.sh, .packaging/conda_recipe/conda_build_config.yaml, .packaging/conda_recipe/meta.yaml, .scripts/build_steps.sh, .scripts/run_osx_build.sh
Backport https://github.com/gnuradio/gnuradio/pull/6332
=> CI: conda: Update recipe and re-render (backport to maint-3.10)

gr-network/lib/udp_sink_impl.cc, gr-network/lib/udp_sink_impl.h, gr-network/lib/udp_source_impl.cc, gr-network/lib/udp_source_impl.h
Backport https://github.com/gnuradio/gnuradio/pull/6312
=> network: Replace boost::circular_buffer with gr::buffer (backport to maint-3.10)

grc/gui/DrawingArea.py, grc/gui/canvas/connection.py
Backport https://github.com/gnuradio/gnuradio/pull/6352
=> grc: Fix cairo assertion failure by not storing reference to context (backport to maint-3.10)

.github/workflows/make-test.yml, gnuradio-runtime/lib/block.cc, gnuradio-runtime/lib/terminate_handler.cc, gr-iio/lib/device_sink_impl.cc
Backport https://github.com/gnuradio/gnuradio/pull/6329
=> Add Debian 32-bit to CI and fix bugs affecting 32-bit systems (backport to maint-3.10)

gr-uhd/grc/uhd_rfnoc_keep_one_in_n.block.yml
Noticed by @drmpeg.
My bad -- I have an RFNoC branch with all sorts of changes, including
this, and there I have this change. Must have mangled the correct commit
when submitting this.
=> uhd: rfnoc: Fix add bindings and example for keep 1 in N

.github/workflows/make-test.yml
=> CI: Update Fedora to 36/37

.github/workflows/make-test.yml
(cherry picked from commit 65554cc044ed76562a7be928b0fa0cebb43c6969)
Backport https://github.com/gnuradio/gnuradio/pull/6382
=> CI: Update Fedora to 36/37 (backport to maint-3.10)

gr-digital/lib/crc32_async_bb_impl.cc, gr-digital/lib/crc32_bb_impl.cc
This fixes the corresponding QA tests, which used to fail on big-endian platforms.
(cherry picked from commit ff590ea0b9c1e641eae67d5a3ffd01cd1e738758)
Backport https://github.com/gnuradio/gnuradio/pull/6314
Changes OTW format, but assessed to be worth the break.
=> digital: Use little-endian for CRC32 regardless of platform (backport to maint-3.10)

gr-dtv/grc/dtv_dvbt_bit_inner_deinterleaver.block.yml, gr-dtv/grc/dtv_dvbt_bit_inner_interleaver.block.yml, gr-dtv/lib/dvbt/dvbt_bit_inner_deinterleaver_impl.cc, gr-dtv/lib/dvbt/dvbt_bit_inner_interleaver_impl.cc
Backport https://github.com/gnuradio/gnuradio/pull/6346
=> gr-dtv: Fix segfaults with DVB-T bit interleavers (backport to maint-3.10)

blocklib/fft/fft/fft.yml, blocklib/streamops/stream_to_vector/qa_stream_to_vector.py, blocklib/streamops/stream_to_vector/stream_to_vector.yml, blocklib/streamops/stream_to_vector/stream_to_vector_cpu.cc, blocklib/streamops/stream_to_vector/stream_to_vector_cpu.h, blocklib/streamops/streams_to_vector/qa_streams_to_vector.py, blocklib/streamops/streams_to_vector/streams_to_vector.yml, blocklib/streamops/streams_to_vector/streams_to_vector_cpu.cc, blocklib/streamops/streams_to_vector/streams_to_vector_cpu.h, gr/include/gnuradio/buffer.h, gr/lib/buffer.cc, gr/lib/graph_executor.cc, gr/lib/thread_wrapper.cc, utils/blockbuilder/scripts/filters.py
adds stream to vector and streams to vector blocks
=> 4.0: streamops: stream_to_vector and streams_to_vector blocks

grc/core/FlowGraph.py
(cherry picked from commit 999a3afe1826ae49d1eb69285c233d96bb0d86c5)
Backport https://github.com/gnuradio/gnuradio/pull/6343
=> grc: Continue processing connections after an invalid one occurs (backport to maint-3.10)

blocklib/audio/alsa_source/alsa_source.yml, blocklib/audio/alsa_source/alsa_source_cpu.cc, blocklib/audio/alsa_source/alsa_source_cpu.h, blocklib/audio/alsa_source/qa_alsa_source.py, blocklib/audio/test/meson.build, blocklib/audio/test/qa_alsa_source.py, meson.build, python/gnuradio/__init__.py
dev-4.0 contains an alsa sink but no alsa source. For tests it's sometimes helpfull, to use an alsa source.
This pr is a port of the alsa source, available in GR3.
Tested with different soundcards.
=> dev-4.0: Add alsa source

gr/lib/graph_executor.cc
A simple flowgraph
analog_sinus_source (float) -> alsa_sink sometimes dies with coredump after playing a short sound.
The debug output is
alsa_sink(1) :debug: read_info alsa_sink(1) - 0 - 4, total: 0 alsa_sink(1) :debug: notify_self = false
alsa_sink(1) :debug: work_returned_ready = false
sig_source(2) :debug: write_info sig_source(2) - 8192 @ 0x7f9e342df000 4, total: 0 alsa_sink(1) :debug: Going into blocking queue
sig_source(2) :debug: do_work (output) for sig_source(2), 8192 sig_source(2) :debug: do_work returned 0
sig_source(2) :debug: pbs[2]: 0
sig_source(2) :debug: post_write sig_source(2) - 8192, total: 0 sig_source(2) :debug: notify_self = true
sig_source(2) :debug: work_returned_ready = true
sig_source(2) :debug: write_info sig_source(2) - 8192 @ 0x7f9e342e7000 4, total: 8192 …
=> graph_executor sometimes fails with SIGSEGV

gr-filter/python/filter/gui/polezero_plot.py
Caught this in packaging 3.10.5.0 for conda-forge, which just so happened to release numpy 1.24 since I tested 3.10.5.0-rc1.
np.float as an alias for float has been deprecated and removed, and np.float_ or equivalently np.float64 is undoubtedly what was wanted here anyway. See the last bullet point of https://numpy.org/devdocs/release/1.24.0-notes.html#expired-deprecations.
=> filter: python: Fix polezero_plot.py compatibility with numpy 1.24

grc/main.py
Replacement PR for #5220.
This fixes the logger prefix which can change depending on how GRC is launched. This also fixes an issue with importing GTK if multiple versions are installed.
Fixes the logger prefix in grc (#4628)
=> grc: fix debug logging and GTK import order

gr-audio/include/gnuradio/audio/osx_impl.h, gr-audio/lib/osx/osx_sink.cc, gr-audio/lib/osx/osx_sink.h, gr-audio/lib/osx/osx_source.cc, gr-audio/lib/osx/osx_source.h
=> audio: Remove support for OSX 10.3 and earlier (backport to maint-3.10)

gr-filter/python/filter/gui/polezero_plot.py
=> filter: python: Fix polezero_plot.py compatibility with numpy 1.24 (backport to maint-3.10)

gr-uhd/grc/gen_uhd_usrp_blocks.py, gr-uhd/lib/usrp_source_impl.cc, gr-uhd/lib/usrp_source_impl.h
=> uhd: add async msgs port to usrp_source block and publish overflows (backport to maint-3.10)

gr-uhd/include/gnuradio/uhd/rfnoc_block.h, gr-uhd/lib/rfnoc_graph_impl.cc, gr-uhd/lib/rfnoc_window_impl.h, gr-zeromq/include/gnuradio/zeromq/pub_sink.h, gr-zeromq/python/zeromq/bindings/pub_sink_python.cc
Backport #6408 
Backport #6417
=> various: warning cleanups (backport to maint-3.10)

gnuradio-runtime/lib/block.cc, gnuradio-runtime/lib/flat_flowgraph.cc, gr-dtv/lib/dvbs2/dvbs2_modulator_bc_impl.cc, gr-fec/python/fec/polar/channel_construction_awgn.py, grc/blocks/snippet.block.yml, grc/core/FlowGraph.py, grc/core/generator/flow_graph.py.mako, grc/main.py
Backport https://github.com/gnuradio/gnuradio/pull/6446
Backport https://github.com/gnuradio/gnuradio/pull/6454
Backport https://github.com/gnuradio/gnuradio/pull/6451
Backport https://github.com/gnuradio/gnuradio/pull/6457
Backport https://github.com/gnuradio/gnuradio/pull/6460
Backport https://github.com/gnuradio/gnuradio/pull/6462
=> various: minor fixes and features (backport to maint-3.10)

gr-uhd/examples/grc/rfnoc_addsub.grc, gr-uhd/grc/CMakeLists.txt, gr-uhd/grc/uhd_rfnoc_addsub.block.yml, gr-uhd/grc/uhd_rfnoc_graph.block.yml
Backport https://github.com/gnuradio/gnuradio/pull/6482
=> rfnoc: new addsub block, fix minor typo (backport to maint-3.10)

grc/gui/FileDialogs.py
Signed-off-by: R-ohit-B-isht <rbtunes0@gmail.com>
Fixes invoking screen capture (crtl+p) multiple times duplicates "All Files" option in the file filter each time it is invoked.
Fixes #6010 
grc/gui/FileDialogs.py line no. 60-63
Yes
=> grc: fix duplicate All Files filter entry in save screenshot dialog

gr-iio/lib/fmcomms2_source_impl.cc
set_gain_mode sets the gain value always to manual instead to the new value
Fixes #6401
PlutoSDR Source
=> gr-iio: set_gain_mode does not set the gain paramter correctly

gnuradio-runtime/lib/vmcircbuf.cc, gnuradio-runtime/lib/vmcircbuf_prefs.cc, gnuradio-runtime/lib/vmcircbuf_prefs.h
- runtime/vmcircbuf_prefs: use sensible include guard name
- runtime/vmcircbuf: use sensible logging, don't use C string handling in C++
=> vmcircbuf logging & string handling & file routines

gr-audio/lib/portaudio/portaudio_impl.cc, gr-audio/lib/portaudio/portaudio_impl.h, gr-audio/lib/portaudio/portaudio_sink.cc, gr-audio/lib/portaudio/portaudio_sink.h, gr-audio/lib/portaudio/portaudio_source.cc, gr-audio/lib/portaudio/portaudio_source.h
- audio: portaudio sink must not use exit() on error
- audio/portaudio: correct logging prio, de-C-stringify
- [-] I have added tests to cover my changes, and all previous tests pass.
=> Portaudio: Correct logging, less hazardous string handling

gnuradio-runtime/lib/top_block_impl.cc
This starts logging when I didn't specify a scheduler explicitly. That's not really all that necessary, given the tremendous amount of 1 scheduler we have in GR 3.x, x>7; but considering we have the logging facilities, and GR 4 will add new scheduling mechanisms, it seemed like a good time to start being able to tell schedulers apart in logs.
On the way, a bit of C-style code had to suffer my modernization.
internal to `top_block_impl`
- [-] I have added tests to cover my changes, and all previous tests pass.
=> runtime: topblock scheduler selection better logging, slight modernization

grc/core/generator/flow_graph.py.mako
In an attempt to make pycodestyle more happy with GRC output
Our Python code actually ignores exceptions that we'd want to know about (not being able to set an icon might be indicative of underlying errors, because not finding it will not raise an exception; and not being able to restore geometry might point to modifications between versions of GUIs); and it does so in a way that pycodestyle complains about.
Let's solve two things at once: Let's actually see these, and let's actually make our code a bit more PEP8. 
Fixes #6508  
GRC Code gen
=> GRC: Remove bare 'except:' from Mako template

gr-filter/grc/filter_pfb_arb_resampler.block.yml
`atten` parameter was not used
Fixes #6519 
pfb arbitrary resampler
loaded it up in grc and can see atten being applied when taps are not specified
=> filter: use atten in grc template for pfb resampler

grc/blocks/options.block.yml, grc/core/generator/flow_graph.py.mako
Reverts gnuradio/gnuradio#6523
The Option block is still a mystery to me. Reverting for now - we can figure out the best way to do this another time.
=> Revert "grc: remove duplicate import, move imports to template code"

gr-filter/lib/gen_interpolator_taps/.gitignore, gr-filter/lib/gen_interpolator_taps/diff_objective_fct.c, gr-filter/lib/gen_interpolator_taps/gen_interp_differentiator_taps.c, gr-filter/lib/gen_interpolator_taps/gen_interpolator_taps.c, gr-filter/lib/gen_interpolator_taps/generate.sh, gr-filter/lib/gen_interpolator_taps/objective_fct.c
also, fix C to actually be standards-compliant
also, a .gitignore for compilation results
We've got some, um, classic FORTRAN in-tree that was/is used to generate interpolator taps.
With these changes, that builds on modern platforms.
Fixes #6521
Effectively, none. (unless you want to be able to reconstruct how the interpolator taps were calculated!)
=> filter: make gen_interpolator_taps run on modern gfortran

gnuradio-runtime/python/gnuradio/gr/hier_block2.py, gnuradio-runtime/python/gnuradio/gr/qa_python_logging.py, gnuradio-runtime/python/gnuradio/gr/top_block.py, grc/core/generator/flow_graph.py.mako
- runtime: hier_block2.py: remove SWIG reference, reflow to 120 line length
- runtime: add python-land loggers to top_block and hier_block2
I added loggers to gr::block wrapped to python, but didn't so for hier_block2, top_block.
This fixes that!
The approach here is slightly different, though: in gr::block / block_gateway, I made sure that the logger obtained in Python is *the very same* logger as the d_logger member of the underlying block. Here, I'm doing the opposite: Python Hier/top blocks are logically "independent enough" from the C++ foundation that it makes sense for the Python code setting things up to have their own loggers. 
Now, while that approach means that no changes to basic_block.h nor hier_block2.h, top_block.h were necessary, it meant that I had to make …
=> Logging for Python Top Blocks, Hier Blocks

gr-qtgui/lib/displayform.cc, gr-qtgui/lib/eyedisplaysform.cc, gr-qtgui/lib/numberdisplayform.cc
(cherry picked from commit 1c094f8f70e7c229c13f809c5f3e1f9422e16a1b)
Backport https://github.com/gnuradio/gnuradio/pull/6474
=> qtgui: fix instrumentation sink save dialog (backport to maint-3.10)

gnuradio-runtime/lib/pagesize.cc
Backport https://github.com/gnuradio/gnuradio/pull/6502
=> runtime: getpagesize for windows (backport to maint-3.10)

gr-audio/lib/portaudio/portaudio_impl.cc, gr-audio/lib/portaudio/portaudio_impl.h, gr-audio/lib/portaudio/portaudio_sink.cc, gr-audio/lib/portaudio/portaudio_sink.h, gr-audio/lib/portaudio/portaudio_source.cc, gr-audio/lib/portaudio/portaudio_source.h
Backport https://github.com/gnuradio/gnuradio/pull/6495
=> Portaudio: Correct logging, less hazardous string handling (backport to maint-3.10)

gnuradio-runtime/lib/top_block_impl.cc
Backport https://github.com/gnuradio/gnuradio/pull/6499
=> runtime: topblock scheduler selection better logging, slight modernization (backport to maint-3.10)

gr-blocks/grc/blocks.tree.yml, gr-blocks/grc/blocks_throttle.block.yml, gr-blocks/grc/blocks_throttle2.block.yml
Minor UI-oriented changes for #5670
=> blocks: update UI for new throttle

gr-filter/grc/filter_pfb_arb_resampler.block.yml
Backport https://github.com/gnuradio/gnuradio/pull/6520
=> filter: use atten in grc template for pfb resampler (backport to maint-3.10)

gr-filter/lib/gen_interpolator_taps/.gitignore, gr-filter/lib/gen_interpolator_taps/diff_objective_fct.c, gr-filter/lib/gen_interpolator_taps/gen_interp_differentiator_taps.c, gr-filter/lib/gen_interpolator_taps/gen_interpolator_taps.c, gr-filter/lib/gen_interpolator_taps/generate.sh, gr-filter/lib/gen_interpolator_taps/objective_fct.c
Backport https://github.com/gnuradio/gnuradio/pull/6522
=> filter: make gen_interpolator_taps run on modern gfortran (backport to maint-3.10)

gr-vocoder/grc/vocoder_codec2_decode_ps.block.yml, gr-vocoder/grc/vocoder_codec2_encode_sp.block.yml, gr-vocoder/grc/vocoder_freedv_rx_ss.block.yml, gr-vocoder/grc/vocoder_freedv_tx_ss.block.yml, gr-vocoder/include/gnuradio/vocoder/codec2.h, gr-vocoder/include/gnuradio/vocoder/freedv_api.h, gr-vocoder/python/vocoder/bindings/codec2_python.cc, gr-vocoder/python/vocoder/bindings/freedv_api_python.cc
Backport https://github.com/gnuradio/gnuradio/pull/6513
=> update codec2 mode enums (backport to maint-3.10)

gr-filter/lib/pfb_arb_resampler.cc, gr-filter/lib/pfb_synthesizer_ccf_impl.cc
=> filter: fix reversed arguments in vector initializer (backport to maint-3.10)

gr-blocks/grc/blocks.tree.yml, gr-blocks/grc/blocks_throttle.block.yml, gr-blocks/grc/blocks_throttle2.block.yml, gr-blocks/grc/blocks_trickling_throttle.block.yml, gr-blocks/include/gnuradio/blocks/throttle.h, gr-blocks/lib/throttle_impl.cc, gr-blocks/lib/throttle_impl.h, gr-blocks/python/blocks/bindings/throttle_python.cc, gr-blocks/python/blocks/qa_throttle.py
Backport https://github.com/gnuradio/gnuradio/pull/5670
Backport https://github.com/gnuradio/gnuradio/pull/6538
=> blocks: trickle throttle (backport to maint-3.10)

gnuradio-runtime/lib/vmcircbuf.cc, gnuradio-runtime/lib/vmcircbuf_prefs.cc, gnuradio-runtime/lib/vmcircbuf_prefs.h
Backport https://github.com/gnuradio/gnuradio/pull/6496
=> vmcircbuf logging & string handling & file routines (backport to maint-3.10)

gnuradio-runtime/gnuradio-runtime.conf.in, gnuradio-runtime/lib/pagesize.cc
Backport https://github.com/gnuradio/gnuradio/pull/6546
=> runtime: change default log level in conf file to info (backport to maint-3.10)

cmake/cmake_uninstall.cmake.in, grc/scripts/freedesktop/CMakeLists.txt, grc/scripts/freedesktop/grc_setup_freedesktop.in
grc_setup_freedesktop should only be installed if -DENABLE_POSTINSTALL=ON
Fixes #6464
Doing a fresh install with -DENABLE_POSTINSTALL=ON and a second one with -DENABLE_POSTINSTALL=OFF
=> grc: grc_setup_freedesktop is installed unconditionally

gnuradio-runtime/python/gnuradio/gr/hier_block2.py, gnuradio-runtime/python/gnuradio/gr/qa_python_logging.py, gnuradio-runtime/python/gnuradio/gr/top_block.py, grc/core/generator/flow_graph.py.mako
Backport https://github.com/gnuradio/gnuradio/pull/6514
=> Logging for Python Top Blocks, Hier Blocks (backport to maint-3.10)

gr-qtgui/lib/HistogramDisplayPlot.cc
Backport https://github.com/gnuradio/gnuradio/pull/6536
=> qtgui: fix Histogram sink bin ranging (backport to maint-3.10)

gr-utils/modtool/templates/templates.py
Backport https://github.com/gnuradio/gnuradio/pull/6562
=> modtool: add kw for interp/decim py blocks (backport to maint-3.10)

gr-fec/lib/async_decoder_impl.cc, gr-fec/lib/async_decoder_impl.h
Backport https://github.com/gnuradio/gnuradio/pull/6537
=> fec: fix some bugs and refactor async_decoder (backport to maint-3.10)

gr-channels/grc/channels_channel_model.block.yml, gr-channels/grc/channels_channel_model2.block.yml, gr-channels/include/gnuradio/channels/channel_model.h, gr-channels/include/gnuradio/channels/channel_model2.h, gr-channels/python/channels/bindings/channel_model2_python.cc, gr-channels/python/channels/bindings/channel_model_python.cc
The default taps for the channel models was 1+1j.  This causes a rotation and scaling of the data.  The default documented behavior is to do nothing.  Update the taps to just 1+0j, which accomplishes this.
Fixes https://github.com/gnuradio/gnuradio/issues/6576
Channel Model and Channel Model 2
I changed the files locally and verified the correct behavior.
=> Change the default taps for channel models.

gr-analog/grc/analog_sig_source_x.block.yml
Hiding unused message ports makes the fg clearer.
Same like #6566
analog_sig_source
Tested with different fg's in grc.
=> analog: sig_source hide message port optionally in grc

gr-blocks/grc/blocks_file_meta_sink.block.yml
Adding a file_meta_sink to a fg fails with
Param - Extra Dict.(extra_dict):
Value "pmt.make_dict()" cannot be evaluated:
name 'pmt' is not defined
as the import statement for pmt is missing.
So you have to add an additional import block to make the fg work.
This pr adds the missing import statement to the template.
analog_file_meta_sink
Add a file meta sink block to the fg and have a lock at the error message in the block
=> blocks: file_meta_sink add missing import statement

cmake/cmake_uninstall.cmake.in, grc/scripts/freedesktop/CMakeLists.txt, grc/scripts/freedesktop/grc_setup_freedesktop.in
Backport https://github.com/gnuradio/gnuradio/pull/6565
=> grc: grc_setup_freedesktop is installed unconditionally (backport to maint-3.10)

gr-zeromq/lib/pull_source_impl.cc, gr-zeromq/lib/req_source_impl.cc, gr-zeromq/lib/sub_source_impl.cc
Backport https://github.com/gnuradio/gnuradio/pull/6579
=> gr-zmq: flush output in ZMQ stream sources (backport to maint-3.10)

gr-uhd/examples/grc/rfnoc_moving_average.grc, gr-uhd/examples/grc/rfnoc_split_stream.grc, gr-uhd/examples/grc/rfnoc_switchboard.grc, gr-uhd/grc/CMakeLists.txt, gr-uhd/grc/uhd_rfnoc_moving_avg.block.yml, gr-uhd/grc/uhd_rfnoc_split_stream.block.yml, gr-uhd/grc/uhd_rfnoc_switchboard.block.yml
Backport #6577 
Backport #6580 
Backport #6581
=> uhd: Add GRC blocks and examples for split stream, switchboard, moving average

gr-channels/grc/channels_channel_model.block.yml, gr-channels/grc/channels_channel_model2.block.yml, gr-channels/include/gnuradio/channels/channel_model.h, gr-channels/include/gnuradio/channels/channel_model2.h, gr-channels/python/channels/bindings/channel_model2_python.cc, gr-channels/python/channels/bindings/channel_model_python.cc
Backport https://github.com/gnuradio/gnuradio/pull/6578
=> Change the default taps for channel models (backport to maint-3.10)

grc/gui/canvas/flowgraph.py
Backport https://github.com/gnuradio/gnuradio/pull/6588
=> grc: Open the source of a hierachical block sometimes produces error messages (backport to maint-3.10)

gr-uhd/examples/grc/rfnoc_vector_iir_split.grc, gr-uhd/grc/CMakeLists.txt, gr-uhd/grc/uhd_rfnoc_vector_iir.block.yml
Add support for the Vector IIR RFNoC block
gr-uhd
Ran included example (Note this requires a bug fix to UHD that is not in the most current version yet for the FFT block):
=> uhd: rfnoc: Add GRC binding and support for Vector IIR block

gr-utils/modtool/templates/templates.py
Two spaces were missing from an indented import statement in the template for Python QA tests. This fixes the formatting
None.
gr_modtool
No testing done.
- ~I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.~ No updates necessary.
=> modtool: fix formatting of python qa template

grc/core/blocks/block.py
just a one line change to make sure node state is consistant
Fixes #5779
make test runs successfully.
=> grc: make node states consistant

grc/gui/Notebook.py
Before change : Generate/Run button when clicked on a new flow-graph fails silently with no warning or error message.
After change : Clicking Generate/Run button on an unsaved GRC flow-graph prompts you to save the file.
Fixes #6185 
Make test ran successfully with no errors.
=> grc: prevent Generate/Run silent fails for unsaved GRC flowgraphs

gr-analog/python/analog/qa_agc.py
At present agc3 tests are performed with a simple sinusoidal wave which makes easy for the agc block to track input and adjust gain.
In this PR i suggest the use of a AM modulated signal with m=0.99 and  mean amplitude =1. This change will likely make the agc struggle. Also this test can be extended to agc and agc2.
Compared to previous tests, delta error values have been decreased to 0.1 to adjust the difficulty of the test properly.
Finally, i noticed that a mean amplitude different to 1 makes the AGC dramatically fail the test and perform horrible.
[ AGC3: needs proper testing #6356](https://github.com/gnuradio/gnuradio/issues/6356)
Affects to the agc3 tests.
I changed different AM modulation parameters and different decay & attack rates, choosing the ones which make the agc perform …
=> Analog: new test for agc3

gr-uhd/examples/grc/CMakeLists.txt, gr-uhd/grc/CMakeLists.txt, gr-uhd/include/gnuradio/uhd/CMakeLists.txt, gr-uhd/lib/CMakeLists.txt, gr-uhd/python/uhd/bindings/CMakeLists.txt
Alphabetize CMakeLists and add examples to installation since I had missed this during block additions
gr-uhd
Did some sanity testing of some examples to make sure the re-order didn't functionally change anything
=> uhd: rfnoc: CMakelists alphabetize and add examples to install

gr-qtgui/include/gnuradio/qtgui/CMakeLists.txt
We tend to keep the lists of installed files in alphabetic order, but we didn't here. That led to duplicates
Fixes #6301
make uninstall
=> qtgui: sort list of installed headers, remove duplicates

gr-vocoder/grc/vocoder_codec2_decode_ps.block.yml, gr-vocoder/grc/vocoder_codec2_encode_sp.block.yml, grc/core/utils/descriptors/evaluated.py
Being the last issue between automated full GRC example test and us: 
gr-vocoder/examples/loopback-codec2.grc fails
This PR fixes that, adds the type of Error to the message displayed in GRC when evaluation of a parameter fails.
Fixes #6630
local
```shell
mkdir build && cd build
cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=$GRPREFIX -GNinja -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER=clang++  -DCMAKE_C_COMPILER=clang -DENABLE_CTRLPORT_THRIFT=Off  -Wno-dev  -DENABLE_GR_CTRLPORT=ON -DENABLE_GNURADIO_RUNTIME=ON -DENABLE_PERFORMANCE_COUNTERS=Off -DCMAKE_CXX_FLAGS=-D_FORTIFY_SOURCE=3 ..
ninja
ninja install > /dev/null
python3 -m pytest ../grc/tests/test_examples.py
```
now runs through!
=> vocoder/codec2: unbreak GRC blocks for codec2 encoder/decoder

grc/gui/Notebook.py
Backport https://github.com/gnuradio/gnuradio/pull/6611
=> grc: prevent Generate/Run silent fails for unsaved GRC flowgraphs (backport to maint-3.10)

gr-analog/python/analog/qa_agc.py
Backport https://github.com/gnuradio/gnuradio/pull/6612
=> analog: New test for agc3 (backport to maint-3.10)

gnuradio-runtime/python/gnuradio/gr/__init__.py, gnuradio-runtime/python/gnuradio/gr/bindings/prefs_python.cc
Backport https://github.com/gnuradio/gnuradio/pull/6622
=> runtime: don't expose prefs.singleton (backport to maint-3.10)

gr-qtgui/include/gnuradio/qtgui/CMakeLists.txt
Backport https://github.com/gnuradio/gnuradio/pull/6623
=> qtgui: sort list of installed headers, remove duplicates (backport to maint-3.10)

gr-analog/grc/analog_agc2_xx.block.yml, gr-analog/grc/analog_agc3_xx.block.yml, gr-analog/grc/analog_agc_xx.block.yml, gr-analog/include/gnuradio/analog/agc2_cc.h, gr-analog/include/gnuradio/analog/agc2_ff.h, gr-analog/include/gnuradio/analog/agc3_cc.h, gr-analog/include/gnuradio/analog/agc_cc.h, gr-analog/include/gnuradio/analog/agc_ff.h, gr-analog/lib/agc2_cc_impl.cc, gr-analog/lib/agc2_cc_impl.h, gr-analog/lib/agc2_ff_impl.cc, gr-analog/lib/agc2_ff_impl.h, gr-analog/lib/agc3_cc_impl.cc, gr-analog/lib/agc3_cc_impl.h, gr-analog/lib/agc_cc_impl.cc, gr-analog/lib/agc_cc_impl.h, gr-analog/lib/agc_ff_impl.cc, gr-analog/lib/agc_ff_impl.h, gr-analog/python/analog/bindings/agc2_cc_python.cc, gr-analog/python/analog/bindings/agc2_ff_python.cc, gr-analog/python/analog/bindings/agc3_cc_python.cc, gr-analog/python/analog/bindings/agc_cc_python.cc, gr-analog/python/analog/bindings/agc_ff_python.cc
https://github.com/gnuradio/gnuradio/pull/6624
=> max_gain parameter added to agc constructors (backport to maint-3.10)

gr-filter/python/filter/design/fir_design.py
Backport https://github.com/gnuradio/gnuradio/pull/6626
=> filter: Update QMessageBox to work in Qt5 (backport to maint-3.10)

gr-vocoder/grc/vocoder_codec2_decode_ps.block.yml, gr-vocoder/grc/vocoder_codec2_encode_sp.block.yml, grc/core/utils/descriptors/evaluated.py
Backport https://github.com/gnuradio/gnuradio/pull/6632
=> vocoder/codec2: unbreak GRC blocks for codec2 encoder/decoder (backport to maint-3.10)

gr-fec/include/gnuradio/fec/alist.h
GCC 13 will error out otherwise.
gr-fec
=> Include cstdint in gr-fec's alist.h

.github/workflows/make-test.yml
Should be putting up a F38/39 builder next, but at the present time, the F36 builder is unlikely to catch any bugs that F37 does not find and eats resources
=> CI: disable Fedora 36 Builder, since 36 is EOL

gr-analog/grc/analog_quadrature_demod_cf.block.yml
The changes introduced in c218dffcbac4e8fe84e0bb0e7794ab174c3a4fbb were erronous. Fixing them by adding the correct method invocation.
Corrects changes from #6674 
gr-analog/analog_quadrature_demod_cf
I've compile tested the changes by generating a c++-export of this flowgraph:
The compilation of the flowgraph worked without errors.
@marcusmueller @willcode Please feel free to undraft and merge, if you can confirm this working on your machines too. Hopefully this time everything went's well.
=> analog_quadrature_demod_cf: fix cpp-generation

gr-uhd/python/uhd/bindings/amsg_source_python.cc, gr-uhd/python/uhd/bindings/uhd_types_python.cc
Backport https://github.com/gnuradio/gnuradio/pull/6651
=> uhd: pybind: use module_local() for types registered by uhd (backport to maint-3.10)

gr-qtgui/lib/QFosphorColorMapper.cc
Fixes #6648
(hopefully)
#6648 highlights that we introduced GCC extension of the C sscanf to the codebase. That `%ms` is handy when dealing with unknown length string data in C: it avoids having to scan for string length first, then `malloc` a buffer, then do the actual `scanf`. But: That problem is a C-exclusive problem. C++ has `std::string`, and `std::stringstream` (though the latter *could* be nicer).
So, we replace the usage of sscanf and raw C strings with `std::string` altogether and hopefully arrive at easier to read code, as well.
- #6648, which this is supposed to fix
- #6515, which introduced the code
- qtgui-internal (specifically, Fosphor-internal)
none, due to hot laptop on hot train
=> qtgui/QFosphorColorMapper: std::sstream+string instead of sscanf("%m")+char*

gr-analog/grc/analog_quadrature_demod_cf.block.yml
Backport #6674
Backport #6686 (fix to above)
=> gr-analog: add cpp code generation for analog_quadrature_demod_cf (backport to maint-3.10)

gr-soapy/grc/soapy_sdrplay_source.block.yml
=> soapy: sdrplay agc and gain fixes (backport to maint-3.10)

gnuradio-runtime/include/gnuradio/logger.h, gnuradio-runtime/lib/qa_logger.cc, gnuradio-runtime/python/gnuradio/gr/bindings/docstrings/logger_pydoc_template.h, gnuradio-runtime/python/gnuradio/gr/bindings/logger_python.cc, gr-blocks/examples/message_debug.grc, gr-blocks/examples/probe_rate_message_debug.grc, gr-blocks/grc/blocks_message_debug.block.yml, gr-blocks/grc/blocks_probe_rate.block.yml, gr-blocks/include/gnuradio/blocks/message_debug.h, gr-blocks/include/gnuradio/blocks/probe_rate.h, gr-blocks/lib/message_debug_impl.cc, gr-blocks/lib/message_debug_impl.h, gr-blocks/lib/probe_rate_impl.cc, gr-blocks/lib/probe_rate_impl.h, gr-blocks/python/blocks/bindings/docstrings/probe_rate_pydoc_template.h, gr-blocks/python/blocks/bindings/message_debug_python.cc, gr-blocks/python/blocks/bindings/probe_rate_python.cc
Rebase of #5997, rebased on top of #6669 and #6670
- #5997 (which this is a rebase of)
- #6669 (which this depends on)
- #6670 (which this also depends on)
=> backport advanced message debug

grc/gui/MainWindow.py
=> grc: Fix unsaved changes lost if prompt dismissed w/ Esc or window-close (backport to maint-3.10)

gr-digital/grc/digital_constellation_decoder_cb.block.yml, gr-digital/grc/digital_constellation_encoder_bc.block.yml, gr-digital/grc/digital_constellation_soft_decoder_cf.block.yml, gr-digital/include/gnuradio/digital/constellation_decoder_cb.h, gr-digital/include/gnuradio/digital/constellation_encoder_bc.h, gr-digital/include/gnuradio/digital/constellation_soft_decoder_cf.h, gr-digital/lib/constellation_decoder_cb_impl.cc, gr-digital/lib/constellation_decoder_cb_impl.h, gr-digital/lib/constellation_encoder_bc_impl.cc, gr-digital/lib/constellation_encoder_bc_impl.h, gr-digital/lib/constellation_soft_decoder_cf_impl.cc, gr-digital/lib/constellation_soft_decoder_cf_impl.h, gr-digital/python/digital/bindings/constellation_decoder_cb_python.cc, gr-digital/python/digital/bindings/constellation_encoder_bc_python.cc, gr-digital/python/digital/bindings/constellation_soft_decoder_cf_python.cc, gr-digital/python/digital/bindings/docstrings/constellation_decoder_cb_pydoc_template.h, gr-digital/python/digital/bindings/docstrings/constellation_encoder_bc_pydoc_template.h, gr-digital/python/digital/bindings/docstrings/constellation_soft_decoder_cf_pydoc_template.h, gr-digital/python/digital/qa_constellation_decoder_cb.py
Backport #6618 
Backport 13f5ad3f8 from #6685
=> constellation encoder/decoder: Add constellation callback (backport to maint-3.10)

gnuradio-runtime/include/gnuradio/thread/thread_group.h, gnuradio-runtime/lib/thread/thread_group.cc
=> runtime: thread_group use set instead of list for set of threads (backport to maint-3.10)

gr-network/lib/tcp_sink_impl.cc, gr-network/lib/udp_sink_impl.cc, gr-network/lib/udp_sink_impl.h, gr-network/lib/udp_source_impl.cc, gr-network/lib/udp_source_impl.h
=> network: Fix various bugs (backport to maint-3.10)

gnuradio-runtime/lib/block.cc, gr-digital/lib/header_payload_demux_impl.cc
=> runtime: do not set max buffer size as side effect of allocation

gr-soapy/grc/soapy_sdrplay_source.block.yml
=> soapy: fix sdrplay biasT_ctrl/agc/gain settings

gr-uhd/lib/rfnoc_rx_streamer_impl.cc
=> gr-uhd/lib: support fmtlib 10

gr-uhd/lib/usrp_source_impl.cc, gr-uhd/lib/usrp_source_impl.h
=> gr-uhd: fix infinite recurse in the case a device is poorly connected

gnuradio-runtime/lib/pmt/pmt_serialize.cc
Currently, building this on GCC13 only works through "wonky" transitive includes; since PMT ideally works out-of-tree at some point, it's worth fixing this.
Also, fixing this might cheaply restore buildability of maint-3.8 with GCC13 ;)
Found while looking at #6762 (thanks, @MakiKyouko)!
None, since impl
- [/] I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.
- [/] I have added tests to cover my changes, and all previous tests pass.
=> runtime: pmt_serialize uses std::int32_t without <cstdint>

grc/gui/Config.py, grc/gui/Dialogs.py
Split off from #6785. See there for more information and discussion.
GRC external Python editor
Tested in conda on Linux and Windows.
- ~[ ] I have added tests to cover my changes, and all previous tests pass.~
=> grc: Save chosen external editor to config file

grc/core/generator/flow_graph.py.mako
We simply do not have any branch with Qt4 support alive
We check whether we have Qt < 5 (which we don't need, we don't build with Qt4 anymore, for quite some time), but we ignore when we try to extract a QSetting that doesn't exist (and then spam the user with a message on stderr)
Fixes #6794
GRC flowgraphs generated with the qtgui option
=> grc/qtgui template: check for nonexisting setting; don't check for Qt4

gr-blocks/grc/blocks_selector.block.yml
The C++ template was including the header for the copy block instead of the selector, probably because of a copy&paste typo.
No related issue.
Selector block in gr-blocks.
No testing done.
- ~I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.~ -> No documentation update necessary.
- ~I have added tests to cover my changes, and all previous tests pass.~ -> There are no tests for GRC templates.
=> blocks: fix selector grc c++ template

gnuradio-runtime/include/gnuradio/logger.h, gnuradio-runtime/python/gnuradio/gr/bindings/logger_python.cc
=> runtime: c++20 friendly logging (backport to maint-3.10)

gnuradio-runtime/include/gnuradio/buffer_single_mapped.h, gnuradio-runtime/include/gnuradio/buffer_type.h, gnuradio-runtime/include/gnuradio/io_signature.h, gnuradio-runtime/lib/buffer_single_mapped.cc, gnuradio-runtime/lib/io_signature.cc, gnuradio-runtime/python/gnuradio/gr/bindings/buffer_type_python.cc, gnuradio-runtime/python/gnuradio/gr/bindings/io_signature_python.cc
=> io_signature: API cleanup (backport to maint-3.10)

gr-blocks/examples/demonstrate_throttle.grc
=> blocks: Add a GRC example for throttle (backport to maint-3.10)

grc/gui/Dialogs.py, grc/gui/ParamWidgets.py, grc/gui/canvas/flowgraph.py
Last week in the matrix chat a user brought up that, when editing a Python Embedded Block, they needed to choose an external editor for every block and with every GRC restart. This and related issues have actually been reported before in #3567 and #6458. It turns out that a typo meant that the selected editor was never saved to the user's config file, and in digging around I also tried to address the other reported issues.
This PR has ~3~2 commits with progressively more invasive changes, and some of these can be backed off if desired:
~1) Fix saving the chosen external editor to the GNU Radio config file.~ Moved to #6786.
2) Add a button so that the editor can be re-chosen (previously, this was only possible by editing the config file). See the "Choose Editor" button now to the right of …
=> Improvements for choosing external Python editor from GRC

grc/core/generator/flow_graph.py.mako
Generated blocks with Generate Option:Hier Block (QT GUI) fail to run as 'from PyQt5 import Qt' is missing.
Fixes #6807
Build a block with generate option Hier Block (QT GUI) and try to run this block from another (qt based) fg.
Fails without this patch, and runs after applying this patch
=> grc: add missing import statement for Hier Block (QT GUI)

.github/workflows/make-test.yml
... keep the 32 bit build on 11 for now; the affected users are probably
conservative, anyways
Debian stable is now 12, we should make our CI support that.
Also yaml linter wasn't happy, happified the yaml linter by commenting out empty properties
gnuradio/gnuradio-docker#38
CI
worksforme! (i.e., I did a build on ci-debian-12-3.10)
=> CI: upgrade debian 11 -> 12

README.md
Made the PYBOMBS description bold to attract attention to the fact that it is no longer recommended
None
=> README.md: make PYBOMBS statement bold

gr-soapy/grc/soapy_rtlsdr_source.block.yml
=> Add buffer size parameter to RTLSDR Source (backport to maint-3.10)

gr-blocks/grc/blocks_selector.block.yml
=> blocks: fix selector grc c++ template (backport to maint-3.10)

gr-qtgui/grc/qtgui_const_sink_x.block.yml
=> qtgui: Use different colours for Constellation Sink inputs (backport to maint-3.10)

README.md
=> make PYBOMBS statement bold (backport to maint-3.10)

gnuradio-runtime/lib/controlport/thrift/rpcpmtconverters_thrift.cc
=> Fix build with fmt-10.1 (backport to maint-3.10)

.github/workflows/make-test.yml
=> CI: upgrade debian 11 -> 12 (backport to maint-3.10)

gr-qtgui/lib/eyedisplayform.cc, gr-qtgui/lib/freqdisplayform.cc, gr-qtgui/lib/timedisplayform.cc
=> qtgui: Set stop button to correct state when opening control panel (backport to maint-3.10)

gr-iio/grc/iio_device_sink.block.yml, gr-iio/grc/iio_device_source.block.yml, gr-iio/lib/device_sink_impl.cc, gr-iio/lib/device_source_impl.cc, gr-iio/lib/iio_priv.h
=> iio: make gr::io_signature for device_source dynamic (backport to maint-3.10)

.readthedocs.yaml
=> docs: Update RTD config to include build.tools (backport to maint-3.10)

gr-digital/examples/packet/formatter_crc.grc, gr-digital/examples/packet/formatter_crc_header_payload_demux.grc, gr-digital/examples/packet/formatter_ofdm.grc, gr-digital/include/gnuradio/digital/header_buffer.h, gr-digital/lib/header_buffer.cc, gr-digital/lib/header_format_crc.cc, gr-digital/lib/header_format_ofdm.cc, gr-digital/lib/qa_header_buffer.cc, gr-digital/python/digital/bindings/header_buffer_python.cc, gr-digital/python/digital/qa_packet_format.py
=> header_format: Fix CRC and OFDM formats (backport to maint-3.10)

gr-digital/grc/digital_symbol_sync_xx.block.yml, gr-digital/include/gnuradio/digital/symbol_sync_cc.h, gr-digital/include/gnuradio/digital/symbol_sync_ff.h, gr-digital/lib/symbol_sync_cc_impl.cc, gr-digital/lib/symbol_sync_cc_impl.h, gr-digital/lib/symbol_sync_ff_impl.cc, gr-digital/lib/symbol_sync_ff_impl.h, gr-digital/python/digital/bindings/docstrings/symbol_sync_cc_pydoc_template.h, gr-digital/python/digital/bindings/docstrings/symbol_sync_ff_pydoc_template.h, gr-digital/python/digital/bindings/symbol_sync_cc_python.cc, gr-digital/python/digital/bindings/symbol_sync_ff_python.cc
=> digital: add sps setter to symbol_sync (backport to maint-3.10)

gr-zeromq/lib/base_impl.cc, gr-zeromq/lib/pub_msg_sink_impl.cc, gr-zeromq/lib/pull_msg_source_impl.cc, gr-zeromq/lib/push_msg_sink_impl.cc, gr-zeromq/lib/rep_msg_sink_impl.cc, gr-zeromq/lib/req_msg_source_impl.cc, gr-zeromq/lib/sub_msg_source_impl.cc
zmq: Improving functionality when needing to interrupt sockets
Mostly housekeeping with ZMQ sockets to better use them in more complex systems.
This allows for better handling in python when sockets need to be interrupted and properly close to prevent hanging.
Addresses #6863 
ZMQ sources/sinks.
Ubuntu 20/22.04 improved functionality within python usage.
=> Tweaking gr-zmq to be more friendly to our use cases.

gr-uhd/docs/uhd.dox, gr-uhd/examples/grc/CMakeLists.txt, gr-uhd/examples/grc/rfnoc_null_source_sink.grc, gr-uhd/examples/grc/rfnoc_radio_loopback.grc, gr-uhd/grc/CMakeLists.txt, gr-uhd/grc/gen_rfnoc_rx_radio_block_yml.py, gr-uhd/grc/uhd_rfnoc_null_src_sink.block.yml, gr-uhd/include/gnuradio/uhd/CMakeLists.txt, gr-uhd/include/gnuradio/uhd/cmd_keys.h, gr-uhd/include/gnuradio/uhd/rfnoc_block.h, gr-uhd/include/gnuradio/uhd/rfnoc_graph.h, gr-uhd/include/gnuradio/uhd/rfnoc_rx_radio.h, gr-uhd/include/gnuradio/uhd/usrp_block.h, gr-uhd/lib/rfnoc_block.cc, gr-uhd/lib/rfnoc_graph_impl.cc, gr-uhd/lib/rfnoc_rx_radio_impl.cc, gr-uhd/lib/rfnoc_rx_radio_impl.h, gr-uhd/lib/usrp_block_impl.cc, gr-uhd/python/uhd/bindings/docstrings/rfnoc_rx_radio_pydoc_template.h, gr-uhd/python/uhd/bindings/rfnoc_rx_radio_python.cc
Backport #6858 
Backport #6868
=> RFNoC updates: Null Source/Sink and loopback (backport to maint-3.10)

gr-blocks/python/blocks/msg_pair_to_var.py
=> Msg Pair To Var: fix attribute error during callback error handling (backport to maint-3.10)

gr-zeromq/lib/base_impl.cc, gr-zeromq/lib/pub_msg_sink_impl.cc, gr-zeromq/lib/pull_msg_source_impl.cc, gr-zeromq/lib/push_msg_sink_impl.cc, gr-zeromq/lib/rep_msg_sink_impl.cc, gr-zeromq/lib/req_msg_source_impl.cc, gr-zeromq/lib/sub_msg_source_impl.cc
=> zmq: Improve the teardown of ZMQ Sources/Sinks (backport to maint-3.10)

gr-qtgui/grc/qtgui_entry.block.yml, gr-qtgui/grc/qtgui_range.block.yml, gr-qtgui/lib/edit_box_msg_impl.cc, gr-qtgui/python/qtgui/range.py.cmakein, gr-uhd/apps/uhd_fft, gr-uhd/apps/uhd_siggen_gui
Backport #6645 
Backport #6867
=> qtgui: Replace QLineEdit::returnPressed() with editingFinished() (backport to maint-3.10)

gr-iio/grc/iio_fmcomms2_sink.block.yml, gr-iio/grc/iio_fmcomms2_source.block.yml
=> iio: Remove extra element from fmcomms2 YML (backport to maint-3.10)

gr-uhd/examples/grc/rfnoc_duc_radio_multichan.grc
In this example `rfnoc_duc_radio_multichan.grc` there used to be some references to blocks that have moved from gr-ettus to gr-uhd obviously, so I removed the red boxes warning about that.
When opening the example there were two red boxes informing about the missing references. While the example could be executed because the missing pieces were found in gr-uhd obviously, it's just a bad user experience.
gr-uhd
I tested the example after the change using a USRP X410.
=> gr-uhd: Remove old references from example

grc/core/generator/flow_graph.py.mako
This only triggered when real-time scheduling could not be enabled
Due to a mistake, we used `gr.logger().warning` instead of `gr.logger.warn`.
Fixes #6923
GRC code gen
none
=> GRC: generated python code use gr.logger.warn instead of ….warning

gr-analog/examples/pll_freqdet_simple.grc
this actively enhances the quality of the example, since changes become
more immediately visible
While working through things, I opened this example to check whether I still understand PLL freqdet. I did, but the example wasn't great UX-wise.
=> analog: PLL frequency detector example: use limited-wait throttle

gr-qtgui/grc/qtgui_msgpushbutton.block.yml, gr-qtgui/python/qtgui/msgpushbutton.py
Add a callback for Message callback
Fixes #6869
qtgui_msgpushbutton
Use a flowgraph containing a QT GUI Chooser to change the message value of a QT GUI Msg Push Button and display the results .
=> gr-qtgui: QT GUI Msg Push Button add callback for Message Value

gr-fec/lib/cc_decoder_impl.cc, gr-fec/lib/cc_decoder_impl.h
Clayton and I were reading the volk decoder kernel, and most of its parameters
are undocumented, so I looked up the usage, and realized this file is horrible.
My sanity.
Checks continue to pass.
=> gr-fec: cc_decoder: untangle C-style, strange argument check

grc/gui/ParamWidgets.py, grc/gui/canvas/param.py
=> grc: Remove param field colorings by type and replace with labels (backport to maint-3.10)

gr-digital/include/gnuradio/digital/header_format_crc.h, gr-digital/include/gnuradio/digital/header_format_ofdm.h, gr-digital/include/gnuradio/digital/packet_header_default.h, gr-digital/python/digital/bindings/header_format_crc_python.cc, gr-digital/python/digital/bindings/header_format_ofdm_python.cc, gr-digital/python/digital/bindings/packet_header_default_python.cc
=> gr-digital every time (backport to maint-3.10)

grc/gui/Application.py
=> grc: Fix way-over-backslashing in file paths (backport to maint-3.10)

gr-uhd/examples/grc/rfnoc_radio_loopback.grc, gr-uhd/grc/rfnoc.domain.yml, grc/core/Connection.py, grc/core/Constants.py, grc/core/FlowGraph.py, grc/core/generator/top_block.py, grc/core/platform.py, grc/core/schema_checker/domain.py, grc/gui/Application.py, grc/gui/PropsDialog.py, grc/gui/canvas/flowgraph.py
This is a bunch of modifications that would allow creating edge/connection properties. These properties are not known by the runtime (4.0 style), only by GRC for rendering.
I think it's most obvious what I'm trying to do if you take a look at `rfnoc.domain.yml`.
How to try:
- Install this branch
- Open an RFNoC flow graph (e.g., rfnoc_radio_loopback.grc). Then right-click on one of the green arrows. You will be able to set a Boolean property of this connection.
- When you render the flow graph, it'll have access to the params.
For RFNoC, I would like the ability to pass arguments to the `connect()` call.
Technically, anything GRC. However, the changes are currently localized to any RFNoC GRC files. Old files get saved and interpreted as before. If someone edits a .grc file that doesn't …
=> GRC: Enable edge/connection properties

grc/core/params/dtypes.py
See #6945
Fixes #6945
- [xI have squashed my commits to have one significant change per commit.
=> grc: backlist gnuradio as valid id

gnuradio-runtime/include/gnuradio/io_signature.h, gnuradio-runtime/include/gnuradio/logger.h, gnuradio-runtime/include/gnuradio/pmt_fmt.h, gnuradio-runtime/lib/io_signature.cc, gnuradio-runtime/lib/pmt_fmt.cc, gnuradio-runtime/python/gnuradio/gr/bindings/io_signature_python.cc, gnuradio-runtime/python/gnuradio/gr/bindings/logger_python.cc, gr-analog/lib/agc3_cc_impl.cc, gr-blocks/lib/blockinterleaving.cc, gr-blocks/lib/keep_m_in_n_impl.cc, gr-blocks/lib/message_debug_impl.cc, gr-blocks/tests/benchmark_common.h, gr-blocks/tests/benchmark_nco.cc, gr-blocks/tests/benchmark_vco.cc, gr-filter/lib/rational_resampler_impl.cc
Otherwise, spdlog/fmt/anything.h might include the internal
fmt/anything.h, although spdlog is set up to use an external fmt.
This is addressed upstream in
https://github.com/gabime/spdlog/issues/2922 .
Just an `#include <spdlog/tweakme.h>` with an explanatory comment on why reordering the include would be a bad idea.
Hopefully:
Fixes #6927
a couple, sadly including public runtime headers
=> spdlog: include spdlog system settings header before including spdlog/fmt/

gr-fec/lib/cc_decoder_impl.cc, gr-fec/lib/cc_decoder_impl.h
Backport #6926 
Backport #6969
=> gr-fec: cc_decoder: untangle C-style, strange argument check (backport to maint-3.10)

gr-audio/lib/windows/windows_source.cc, gr-audio/lib/windows/windows_source.h
Resolves build issue in MSYS2 MinGW64 environment
gr-audio
=> Remove 'friend' from 'read_wavein' callback function

gr-uhd/grc/uhd_rfnoc_rx_streamer.block.yml, gr-uhd/include/gnuradio/uhd/rfnoc_rx_streamer.h, gr-uhd/lib/rfnoc_rx_streamer_impl.cc, gr-uhd/lib/rfnoc_rx_streamer_impl.h, gr-uhd/python/uhd/bindings/rfnoc_rx_streamer_python.cc
=> gr-uhd: RFNoC Rx-Streamer: Add start stream options (backport to maint-3.10)

gr-blocks/tests/benchmark_common.h
compilers seem to optimize away the operations if they can detect constant input, and discarded output. Fixing both issues.
shown in #6800
None
More believable results:
```
+——————————————————————————————————————————————————————————————————+
| fxpt sine          time: 8.9234e-03 s throughput: 2.241e+09 it/s |
| fxpt sin/cos       time: 2.3390e-02 s throughput: 8.551e+08 it/s |
| fxpt sin/cos vec   time: 2.8762e-02 s throughput: 6.954e+08 it/s |
| native sine        time: 1.8936e-01 s throughput: 1.056e+08 it/s |
| native sin/cos vec time: 3.9507e-01 s throughput: 5.062e+07 it/s |
| native sin/cos     time: 4.5111e-01 s throughput: 4.433e+07 it/s |
| basic sin/cos vec  time: 4.6110e-01 s throughput: 4.337e+07 it/s |
+——————————————————————————————————————————————————————————————————+
```
=> blocks: benchmark_vco,nco: random input, non-discarded output

gr-uhd/grc/uhd_fpga_fft.block.yml, grc/core/blocks/_build.py, grc/core/blocks/block.py, grc/core/schema_checker/block.py, grc/gui/PropsDialog.py
GRC: enable setting of documentation URLs, relative or absolute in yaml
This allows OOT module developers to link to online or offline documentation, and allows us to disambiguate in-tree blocks with the same label, as currently, only the label is used to form the URL.
GRC: Optional block field
=> GRC: add Documentation URLs

gr-audio/lib/windows/windows_source.cc, gr-audio/lib/windows/windows_source.h
=> Remove 'friend' from 'read_wavein' callback function (backport to maint-3.10)

gr-filter/python/filter/qa_fir_filter.py
=> filter: Accept rounded output from fir_filter_fsf (backport to maint-3.10)

gr-blocks/include/gnuradio/blocks/rotator.h, gr-blocks/lib/multiply_by_tag_value_cc_impl.cc, gr-blocks/lib/multiply_const_impl.cc, gr-blocks/lib/multiply_matrix_impl.cc, gr-blocks/lib/phase_shift_impl.cc, gr-blocks/python/blocks/bindings/rotator_python.cc, gr-digital/include/gnuradio/digital/adaptive_algorithm_cma.h, gr-digital/include/gnuradio/digital/adaptive_algorithm_lms.h, gr-digital/python/digital/bindings/adaptive_algorithm_cma_python.cc, gr-digital/python/digital/bindings/adaptive_algorithm_lms_python.cc, gr-dtv/lib/dvbt/dvbt_reference_signals_impl.cc, gr-dtv/lib/dvbt2/dvbt2_paprtr_cc_impl.cc, gr-dtv/lib/dvbt2/dvbt2_pilotgenerator_cc_impl.cc
=> Use pointers to pass s32fc arguments to VOLK (backport to maint-3.10)

gr-qtgui/grc/qtgui_msgpushbutton.block.yml, gr-qtgui/python/qtgui/msgpushbutton.py
=> gr-qtgui: QT GUI Msg Push Button add callback for Message Value (backport to maint-3.10)

gnuradio-runtime/include/gnuradio/io_signature.h, gnuradio-runtime/include/gnuradio/logger.h, gnuradio-runtime/include/gnuradio/pmt_fmt.h, gnuradio-runtime/lib/io_signature.cc, gnuradio-runtime/lib/pmt_fmt.cc, gnuradio-runtime/python/gnuradio/gr/bindings/io_signature_python.cc, gnuradio-runtime/python/gnuradio/gr/bindings/logger_python.cc, gr-analog/lib/agc3_cc_impl.cc, gr-blocks/lib/blockinterleaving.cc, gr-blocks/lib/keep_m_in_n_impl.cc, gr-blocks/lib/message_debug_impl.cc, gr-blocks/tests/benchmark_common.h, gr-blocks/tests/benchmark_nco.cc, gr-blocks/tests/benchmark_vco.cc, gr-filter/lib/rational_resampler_impl.cc
=> spdlog: include spdlog system settings header before including spdlog/fmt/ (backport to maint-3.10)

gnuradio-runtime/python/pmt/bindings/pmt_python.cc, gnuradio-runtime/python/pmt/qa_pmt.py
=> pmt: Disallow None for pmt_t arguments in Python (backport to maint-3.10)

gr-analog/examples/pll_freqdet_simple.grc, gr-uhd/examples/grc/rfnoc_duc_radio_multichan.grc
Backport https://github.com/gnuradio/gnuradio/pull/6890
Backport https://github.com/gnuradio/gnuradio/pull/6909
=> Example updates rollup (backport to maint-3.10)

gr-qtgui/grc/qtgui_range.block.yml, gr-qtgui/grc/qtgui_rfnoc_f15_display.block.yml
=> qtgui: Remove unnecessary imports from templates (backport to maint-3.10)

gr-blocks/python/blocks/qa_throttle.py
The `test_limited_chunk_throttling` test often fails on macOS. I ran an experiment (https://github.com/gnuradio/gnuradio/issues/6635#issuecomment-1837552014) and found that the GitHub-hosted runner often takes ~80 ms to wake from a `sleep()`. The test requires less than 100 ms difference in the execution times of two threads, so it isn't surprising that it often fails.
To fix this, I reduced the throttle's rate to 10 sps, so it should produce a batch of samples once per second. A loop runs for two seconds, checking the output size every 100 ms and verifying that it has grown by no more than `chunksize` samples since the previous check. Finally, the output size is checked to verify that at least one chunk was produced.
The updated version of the test should allow timing differences of up …
=> blocks: Fix flaky chunk throttling test

gr-blocks/python/blocks/qa_msg_pair_to_var.py
=> blocks: msq_pair_to_var QA: wait up to 1s (backport to maint-3.10)

cmake/Modules/GrPython.cmake
The CMake function GR_PYTHON_INSTALL utilizes Python to parse the script's shebang. However, on the Windows platform, it opens the script files using the system's default encoding (ASCII/GBK), which leads to encoding errors when the script files contain UTF-8 characters. This commit updates the CMake function to ensure that files are opened using UTF-8 encoding, thereby resolving these encoding issues.
=> fix gr_python_install on windows platform

gr-blocks/python/blocks/qa_throttle.py
=> blocks: Fix flaky chunk throttling test (backport to maint-3.10)

gr-fec/include/gnuradio/fec/rs.h, gr-fec/lib/reed-solomon/ccsds.h, gr-fec/lib/reed-solomon/char.h, gr-fec/lib/reed-solomon/decode_rs_ccsds.c, gr-fec/lib/reed-solomon/encode_rs_ccsds.c, gr-fec/lib/reed-solomon/fixed.h
=> fec: add FEC_API to CCSDS Reed-Solomon functions (backport to maint-3.10)

gr-uhd/grc/uhd_fpga_fft.block.yml, grc/core/blocks/_build.py, grc/core/blocks/block.py, grc/core/schema_checker/block.py, grc/gui/PropsDialog.py
=> GRC: add Documentation URLs (backport to maint-3.10)

cmake/Modules/GrPython.cmake
=> fix gr_python_install (backport to maint-3.10)

grc/core/Connection.py, grc/core/utils/descriptors/_lazy.py
=> grc: Make core.Connection.type not lazy

gr-network/python/network/qa_tcp_sink.py
=> network: Add timeout to prevent qa_tcp_sink from hanging (backport to maint-3.10)

gr-dtv/python/dtv/qa_dtv.py
=> dtv: Read expected data as little-endian (backport to maint-3.10)

grc/core/blocks/block.py
=> grc: make node states consistant (backport to maint-3.10)

gr-fec/lib/polar_encoder.cc
=> fec: Fix input buffer overrun in polar encoder (backport to maint-3.10)

gr-analog/lib/agc3_cc_impl.cc, gr-analog/python/analog/qa_agc.py
=> analog: Pass through max_gain parameter in agc3_cc::make (backport to maint-3.10)

gnuradio-runtime/lib/pmt/pmt.cc
=> pmt: Check length before calling memcmp (backport to maint-3.10)

gr-qtgui/lib/ber_sink_b_impl.cc
=> fec: Fix BPSK AWGN formula (backport to maint-3.10)

grc/core/generator/top_block.py
=> grc: Fix compilation of bus ports (backport to maint-3.10)

gr-blocks/lib/null_source_impl.cc
=> blocks: Fix loop bound in Null Source (backport to maint-3.10)

grc/core/generator/cpp_top_block.py
=> grc: fix C++ gen with busports (backport to maint-3.10)

grc/core/blocks/block.py, grc/gui/Application.py
=> grc: Only bussify blocks that have ports (backport to maint-3.10)

grc/core/Config.py
=> grc: Update copyright date (backport to maint-3.10)

grc/gui_qt/components/window.py
At the moment the closeEvent (clicking the X in the right upper corner) is handled by qt, so no changes in the settings - especially the geometry -- are not written to grc.conf.
Redirecting closeEvent exit_triggered solves this issue.
Setting object names for toolbar objects avoids warnings on close.
=> grcqt: Handle mainwindow closeEvent

gr-filter/lib/fir_filter_with_buffer.cc, gr-filter/lib/qa_fir_filter_with_buffer.cc
=> filter: Fix undefined behaviour in fir_filter_with_buffer (backport to maint-3.10)

gr-digital/lib/pfb_clock_sync_ccf_impl.cc, gr-digital/lib/pfb_clock_sync_ccf_impl.h, gr-digital/lib/pfb_clock_sync_fff_impl.cc, gr-digital/lib/pfb_clock_sync_fff_impl.h
=> digital: Fix early return logic in Polyphase Clock Sync (backport to maint-3.10)

gr-fec/lib/async_decoder_impl.cc, gr-fec/lib/async_encoder_impl.cc, gr-fec/lib/tagged_decoder_impl.cc
=> fec: Round before converting frame lengths to int (backport to maint-3.10)

.conda/recipe/meta.yaml
Add a setuptools dependency in the conda recipe so that tests requiring `pkg_resources` don't fail.
Fixes #7126.
=> ci: conda: Fix missing pkg_resources during modtool test

gr-digital/include/gnuradio/digital/correlate_access_code_bb_ts.h, gr-digital/lib/correlate_access_code_bb_ts_impl.cc, gr-digital/lib/correlate_access_code_bb_ts_impl.h, gr-digital/python/digital/bindings/correlate_access_code_bb_ts_python.cc, gr-digital/python/digital/qa_correlate_access_code_XX_ts.py
Used to be 12 bit mask, but docs and code expect 16 bit.
Also, renamed a private function to be clearer on purpose.
Fixes #6440
only the TSB version of correlate access code
=> digital: correlate_access_code TS version: incorrect mask

.github/workflows/make-test.yml
=> CI: Update Fedora workers to F39/40, enable GLIBCXX_ASSERTIONS

gr-utils/blocktool/core/parseheader.py
modern Python sees the \d in the regex raw string contained in the
comment string, and complains about an unknown escape sequence.
Basically, the same issue as #7036, same fix as #7037
None, actually! This is just a code comment, but on Fedora 40, you get a SyntaxWarning, so that's fixed with this
=> blocktool: raw string for commenting out code to suppress SyntaxWarning

gnuradio-runtime/python/pmt/qa_pmt_to_python.py, gr-blocks/python/blocks/qa_multiply_matrix_xx.py, gr-iio/python/iio/__init__.py, gr-iio/python/iio/qa_iio.py, gr-zeromq/python/zeromq/qa_zeromq_sub.py
=> qa: Fix deprecation warnings in tests (backport to maint-3.10)

gr-digital/include/gnuradio/digital/correlate_access_code_bb_ts.h, gr-digital/lib/correlate_access_code_bb_ts_impl.cc, gr-digital/lib/correlate_access_code_bb_ts_impl.h, gr-digital/python/digital/bindings/correlate_access_code_bb_ts_python.cc, gr-digital/python/digital/qa_correlate_access_code_XX_ts.py
=> digital: correlate_access_code TS version: incorrect mask (backport to maint-3.10)

gr-blocks/lib/peak_detector2_fb_impl.cc
=> blocks: Write debug samples at the correct time in Peak Detector2 (backport to maint-3.10)

gr-blocks/grc/blocks_float_uchar.block.yml, gr-blocks/include/gnuradio/blocks/float_to_uchar.h, gr-blocks/lib/float_array_to_uchar.cc, gr-blocks/lib/float_to_uchar_impl.cc, gr-blocks/lib/float_to_uchar_impl.h, gr-blocks/python/blocks/bindings/docstrings/float_to_uchar_pydoc_template.h, gr-blocks/python/blocks/bindings/float_to_uchar_python.cc, gr-blocks/python/blocks/qa_type_conversions.py, gr-fec/lib/async_decoder_impl.cc, gr-fec/lib/async_decoder_impl.h, gr-fec/python/fec/extended_decoder.py, gr-fec/python/fec/extended_tagged_decoder.py
=> Use Volk kernel volk_32f_s32f_x2_convert_8u (backport to maint-3.10)

gr-filter/python/filter/gui/CustomViewBox.py
=> gr-filter: Fix filter tool CustomViewBox import order to force PyQtGraph to use PyQt5 (backport to maint-3.10)

gnuradio-runtime/apps/gnuradio-config-info.cc, gnuradio-runtime/include/gnuradio/sys_paths.h, gnuradio-runtime/lib/prefs.cc, gnuradio-runtime/lib/sys_paths.cc, gnuradio-runtime/lib/vmcircbuf_mmap_shm_open.cc, gnuradio-runtime/lib/vmcircbuf_mmap_tmpfile.cc, gnuradio-runtime/lib/vmcircbuf_prefs.cc, gnuradio-runtime/python/gnuradio/gr/CMakeLists.txt, gnuradio-runtime/python/gnuradio/gr/bindings/sys_paths_python.cc, gnuradio-runtime/python/gnuradio/gr/qa_prefs.py, gnuradio-runtime/python/gnuradio/gr/qa_sys_paths.py, gr-fft/lib/fft.cc
Backport #7136 
Backport #7181
=> sys_paths: use XDG_CONFIG_HOME if present, new API (backport to maint-3.10)

gr-fec/lib/polar_decoder_common.cc
Standardized fmt::print()
3rd Sub-task of #4765
Yes
=> fec: use fmt instead of printf

README.md
=> README: no need to check out specific branch for Qt GRC

grc/gui_qt/components/flowgraph_view.py
While drawing flowgraphs, panning the canvas is possible only by using the scrollbars (+SHIFT key).
The trackpad panning is there, but not using the mouse.
Hence, implementing the middle mouse button pan here.
Fixes #7178
PR #7179 fixes for GTK gui
flowgraph_view
Did UI test
=> grc (Qt gui): add middle mouse button panning

grc/gui_qt/components/canvas/block.py, grc/gui_qt/components/canvas/connection.py, grc/gui_qt/components/canvas/port.py
Connector arrows face in the wrong direction on input ports on a rotated block.
Fixed by adding necessary transformations.
Fix Minor-Issue #6957
grc-qt/component/canvas
Did UI test
=> grc-qt: fix connector arrowhead direction

gr-utils/blocktool/core/parseheader.py
=> blocktool: raw string for commenting out code to suppress SyntaxWarning (backport to maint-3.10)

.github/workflows/make-test.yml, gr-blocks/python/blocks/qa_throttle.py
Some non-portable code was accidentally introduced in #7136, which broke compilation with MinGW-w64: #7156. Gqrx uses MinGW-w64 for its Windows releases, so I think it would be helpful to add this compiler to CI.
UHD, IIO, and codec2 are not available as pre-built packages, so I left them out for now. It would be possible to build them from source, but this would slow down the CI run.
CI
I ran the test suite with `--repeat until-fail:100` to check that the tests pass reliably. The `qa_throttle` tests often failed because the throttle would let the samples through in a few milliseconds less than the expected time. As far as I can tell, this is because the `sleep_until` implementation in the standard library ultimately uses the [Win32 Sleep …
=> CI: Add MinGW-w64

gnuradio-runtime/lib/vmcircbuf_prefs.cc, gr-fft/lib/fft.cc
=> runtime and fft: use create_directories() instead of iterating (backport to maint-3.10)

gnuradio-runtime/lib/realtime_impl.cc, gnuradio-runtime/lib/vmcircbuf_createfilemapping.cc, gr-audio/lib/windows/windows_sink.cc, gr-audio/lib/windows/windows_sink.h, gr-audio/lib/windows/windows_source.cc
Backport #7223 
Backport #7224 
Backport #7225
=> Fix MinGW build errors (backport to maint-3.10)

gr-trellis/examples/grc/interference_cancellation.grc, gr-trellis/examples/grc/pccc.grc, gr-trellis/examples/grc/sccc.grc, gr-trellis/examples/grc/tcm.grc, gr-trellis/examples/grc/turbo_equalization.grc, gr-trellis/examples/grc/viterbi_equalization.grc
Update and test examples in gr-trellis/examples/grc/
convert from XML to YML format
replace blks2_error_rate with BER block to fix missing block issue
Fixes [#2285](https://github.com/gnuradio/gnuradio/issues/2285) and https://github.com/gnuradio/gnuradio/issues/2529
all examples from gr-trellis/examples/grc/
open, save, and runing test
=> example: update gr-trellis examples

grc/gui_qt/Config.py
=> grc-qt: custom_block_paths set but not used (backport to maint-3.10)

gnuradio-runtime/python/pmt/pmt_to_python.py, gnuradio-runtime/python/pmt/qa_pmt_to_python.py, gr-filter/python/filter/design/filter_design.py
=> Replace scipy/numpy.complex128 with cdouble (backport to maint-3.10)

gr-trellis/examples/grc/interference_cancellation.grc, gr-trellis/examples/grc/pccc.grc, gr-trellis/examples/grc/sccc.grc, gr-trellis/examples/grc/tcm.grc, gr-trellis/examples/grc/turbo_equalization.grc, gr-trellis/examples/grc/viterbi_equalization.grc
=> gr-trellis: port examples from xml and change the deprecated block (backport to maint-3.10)

gr-audio/grc/audio_sink.block.yml, gr-audio/grc/audio_source.block.yml
Audio sink/source is limited up to 48 kHz sample rate in the block option menu. This pr adds 96000 and 192000 to the option menu.
Fixes #7155
Just build a simple flowgraph  signal_source -> alsa_sink and try different sample rates.
=> gr-audio: Extend alsa sink/ source sample rate

gr-utils/modtool/tools/cmakefile_editor.py
Case of, e.g., GR_PYTHON_INSTALL, is not consistent in cmake files. Since these functions are used in limited situations, it is easier and perhaps more backward compatible to loosen the regex than to iron out the use of case in cmake files.
Fixes #7243
modtool
=> modtools: case-insensitive matching for python cmake file add/rm

gr-utils/modtool/templates/gr-newmod/CMakeLists.txt, gr-utils/modtool/tools/cmakefile_editor.py
Backport #7245 
Backport #7246
=> modtool: rollup 2 fixes (backport to maint-3.10)

gr-audio/grc/audio_sink.block.yml, gr-audio/grc/audio_source.block.yml
=> gr-audio: Extend alsa sink/ source sample rate (backport to maint-3.10)

.github/ISSUE_TEMPLATE/config.yml
Spotted an error I made in #7260 seconds too late.
Looks like [this](https://github.com/marcusmueller/github-feature-playground/issues/new/choose) now.
#7260
=> Github: Issue Templates: YAML interpreted # as comment, fixed hyphens

grc/gui_qt/components/canvas/flowgraph.py
This error is a bit tricky to reproduce.
Generate a simple flowgraph
signal source( float ) -> audio sink (float, single input) Save the fg and restart grc.
Modify the audio sink to 2 inputs and try connect the source port to the new sink input port.
Then you get 
File "/usr/local/gnuradio/lib64/python3.12/site-packages/gnuradio/grc/gui_qt/components/canvas/flowgraph.py", line 293, in mousePressEvent
elif selected[0].is_sink and c_item.is_source:
^^^^^^^^^^^^^^^^^^^
AttributeError: 'GUIPort' object has no attribute 'is_sink'
Sometimes you must try several times to connet the ports to get this error.
Sometimes you even get a core dump.
=> grc-qt: AttributeError: 'GUIPort' object has no attribute 'is_sink'

grc/gui_qt/components/block_library.py, grc/gui_qt/components/canvas/flowgraph.py, grc/gui_qt/components/console.py, grc/gui_qt/components/variable_editor.py, grc/gui_qt/components/wiki_tab.py, grc/gui_qt/components/window.py, grc/gui_qt/grc.py, grc/gui_qt/resources/available_preferences.yml, grc/main.py
Backport #7262 
Backport #7256
=> grc: qt update rollup (backport to maint-3.10)

grc/gui_qt/components/window.py
Avoid to open a grc multiple times in grc --qt
In grc  --gtk  you can open a grc file only once, while in grc --qt you can open a grc file 
several times and you edit a fg in different tabs. This may lead to confusion.
So avoid to open a grc multiple times in grc --qt
Try to open an existing fg several times
=> grc-qt: Open grc files only once

grc/gui_qt/components/block_library.py, grc/gui_qt/components/window.py
Fixes https://github.com/gnuradio/gnuradio/issues/7300
Fixes https://github.com/gnuradio/gnuradio/issues/7300
=> grc-qt: Clear block search field on Ctrl+F

grc/gui_qt/components/window.py
At the moment you can save a flowgraph without the extension grc.
This pr adds the extension if missing.
Fixes: #7301
See #7301 
Saving and reopening a fg with and without extension grc
=> grc-qt: Save flowgraph: add extension to filename

grc/gui_qt/components/window.py, grc/gui_qt/grc.py, grc/main.py
Now the list of files specified on the cl for grc is appended to the list of files to be opened on startup.
fixes #7291
=> grc-qt: grc --qt filename.grc doesn't open filename.grc

grc/gui_qt/components/canvas/connection.py, grc/gui_qt/resources/available_preferences.yml
- **GRC: Angular connection (by choice via Preferences)**
- **GRC: Make connection line width preference-configurable**
Closes #5152
- Qt GRC
- Hopefully a selling point for Qt GRC for those who want to go back to the 3.7 days, optically :D
=> GRC: Allow for angular connections

.ci_support/linux_64_numpy1.23python3.11.____cpython.yaml, .ci_support/osx_64_numpy1.23python3.11.____cpython.yaml, .ci_support/win_64_numpy1.23python3.11.____cpython.yaml, .github/workflows/conda-build.yml, .scripts/build_steps.sh, .scripts/run_docker_build.sh, .scripts/run_osx_build.sh, .scripts/run_win_build.bat
This updates some of the dependencies that the conda CI builds against, and keeps pace with the conda-forge ecosystem. I'm also hoping that this will fix the macOS CI, which seems to think it is a doing a cross-compilation ever since some recent conda-forge infrastructure change.
=> CI: conda: Update conda build configuration and scripts

grc/tests/test_qtbot.py
This PR includes two commits, addressing test failures introduced by https://github.com/gnuradio/gnuradio/commit/3df1fe091e538525397b243b5107b84043070e92 (save related tests failed) and https://github.com/gnuradio/gnuradio/commit/2742beb1e1901a344e77b76883f16142d1ef4127 (all tests failed)
Just test_qtbot.py
Tested test_qtbot.py before and after
=> grc-qt: test_qtbot fixes

cmake/Modules/FindQwt.cmake
Should have changed the error message along with the version requirement in #7334.
=> cmake: fix error message for Qwt version

grc/gui/Executor.py, grc/gui_qt/components/block_library.py, grc/gui_qt/components/canvas/connection.py, grc/gui_qt/components/canvas/port.py, grc/gui_qt/components/example_browser.py, grc/gui_qt/components/executor.py, grc/gui_qt/components/oot_browser.py, grc/gui_qt/components/window.py, grc/gui_qt/grc.py, grc/gui_qt/resources/available_preferences.yml, grc/main.py, grc/tests/test_qtbot.py
Backport https://github.com/gnuradio/gnuradio/pull/7277
Backport https://github.com/gnuradio/gnuradio/pull/7278
Backport https://github.com/gnuradio/gnuradio/pull/7287
Backport https://github.com/gnuradio/gnuradio/pull/7290
Backport https://github.com/gnuradio/gnuradio/pull/7292
Backport https://github.com/gnuradio/gnuradio/pull/7294
Backport https://github.com/gnuradio/gnuradio/pull/7312
Backport https://github.com/gnuradio/gnuradio/pull/7314
Backport https://github.com/gnuradio/gnuradio/pull/7315
Backport https://github.com/gnuradio/gnuradio/pull/7319
Backport https://github.com/gnuradio/gnuradio/pull/7325
Backport https://github.com/gnuradio/gnuradio/pull/7329
Backport https://github.com/gnuradio/gnuradio/pull/7333
=> Backport/maint 3.10/grc qt rollup

gr-utils/CMakeLists.txt, gr-utils/modtool/cli/base.py
used for external plugins for modtool, which (AFAIK) never materialized)
This came from an endeavour to reduce dependency on click-plugins through modernized reimplementation (click-plugins has been stale for a few years); however, upon deeper inspection, it was simply never used, as far as I can tell.
people who write external plugins for modtool. To the best of my knowledge (and internet research), there are none.
(there were no tests for the plugins architecture, so no tests needed to be removed)
=> modtool: remove click-plugins dependency

grc/gui/VariableEditor.py
Run grc, add an import block in the variable editor. 
Then edit the value for the import block in the variable editor, for instance enter import math.
Then you get an error
File "/usr/local/gnuradio/lib64/python3.12/site-packages/gnuradio/grc/gui/VariableEditor.py", line 243, in _handle_value_edited_cb
block.params['import'].set_value(new_text)
~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'import'
Edit an import block int the variable editor
=> grc: Variable Editor keyError

gr-blocks/grc/blocks_max_xx.block.yml
Add documentation for max block
https://github.com/gnuradio/gnuradio/issues/7265
Max block
gui test
=> Add documentation for max block

.ci_support/osx_64_numpy1.23python3.11.____cpython.yaml, .ci_support/win_64_numpy1.23python3.11.____cpython.yaml, .conda/recipe/conda_build_config.yaml
The latest Github runner images are slowly dropping support for VS2019, and in particular no longer include the MFC tools for VS2019 resulting in a missing `afxres.h` header during the build. Easiest thing to do is to switch to VS2022 ahead of conda-forge making that switch as standard.
=> ci: conda: Build with VS2022 for Windows

grc/gui_qt/components/window.py
grc --qt has a configuration value default_qt_theme
But this value is not used.
This pr checks if the configured theme is available and correctly sets the theme
=> grc-qt: Use themes

.github/workflows/make-test.yml
We've got test failure reports by Ubuntu 24.04 LTS user, but no CI: Bad situation!
I needed a local container to work on #6477, anyways, so I decided I should do a quick & easy Ubuntu 24.04 container.
PR #7371 removes the EOL F38 builder, so this would become build-time neutral.
CI
Local build & test. Only Qt test failed.
=> CI: Ubuntu 24.04 LTS builder

grc/gui_qt/components/window.py, grc/gui_qt/grc.py, grc/gui_qt/resources/available_preferences.yml
Theme settings is a complex task.
The best way to handle is to leave this task to the OS- tools.
This is done for grc --gtk and should be done for grc --qt , too.
Start grc --qt for different settings of  QT_QPA_PLATFORMTHEME and different iconthemes using qt5ct or the gnome tools
=> grc-qt: Remove Theme and Icontheme  settings

grc/gui_qt/components/window.py, grc/gui_qt/grc.py, grc/gui_qt/resources/available_preferences.yml
=> grc-qt: Remove Theme and Icontheme  settings (backport to maint-3.10)

.github/workflows/make-test.yml
Backport #7371 
Backport #7372
=> CI: update targets (backport to maint-3.10)

grc/gui_qt/components/variable_editor.py, grc/gui_qt/components/window.py
At the moment the text color in some widgets is hardcoded to white. This makes the text invisible in the light mode.
Variable names and values in the variable editor sometimes are hard to read. So now use the palette settings to get the correct colors.
Fixes #7297
Use the example in #7297 
Try Light and Dark theme in preferences
=> grc-qt: set text color in some widgets depending  on light/dark theme

grc/gui_qt/components/canvas/flowgraph.py
Run
grc --qt
File -> new
Add a constant source block and a null sink block
Click the source out port and then the sink in port and you should get connection, but nothing happens. Now clicking again the source out port you get a connection.
File ->	new
Add a constant source block and a null sink block
Click the sink in  port and then the source out port and you immediately  get a connection.
Applying this pr you get immediately a connection when clicking the source out port and then the sink in port.
Run the described examples
=> grc-qt: Can only connect sink in port to source out port

gr-filter/python/filter/gui/polezero_plot.py
Numpy 2.0 is being released soon with some breaking changes. Conda-forge is already working on building against the release candidate to make as many packages available as possible when the release happens, and that has [included GNU Radio](https://github.com/conda-forge/gnuradio-feedstock/pull/271). Just this small change was necessary for the build to pass successfully.
Fixes #7378
=> filter: python: Change float_ to float64 for numpy 2.0 compatibility

CMakeLists.txt, cmake/Modules/GrMinReq.cmake, gr-utils/modtool/templates/gr-newmod/CMakeLists.txt, grc/core/generator/cpp_templates/CMakeLists.txt.mako
… the CMakeLists actually contradicted what we had in GrMinVer.cmake
After discussion with @willcode in #7323, I went to bump the CMake version, just to find it had be bumped already – just not in the right places.
hopefully none! This is the version of CMake we find in Ubuntu 20.04, and should be both realistically what we are actually using, and what can be found on the oldest platforms supported.
=> cmake: Bump minimum required CMake version to what is specified

gr-utils/CMakeLists.txt, gr-utils/bindtool/templates/pydoc_h.mako, gr-utils/modtool/cli/base.py, gr-utils/modtool/core/add.py, gr-utils/modtool/templates/gr-newmod/python/howto/bindings/bind_oot_file.py, gr-utils/modtool/tools/grc_yaml_generator.py, gr-utils/modtool/tools/parser_cc_block.py, gr-utils/modtool/tools/util_functions.py
Backport #6987 
Backport #7177 
Backport #7316 
Backport #7318 
Backport #7354 
Backport #7355
=> modtool rollup (backport to maint-3.10)

gr-blocks/grc/blocks_max_xx.block.yml
=> update documentation for max block (backport to maint-3.10)

gnuradio-runtime/python/gnuradio/gr/bindings/CMakeLists.txt, gnuradio-runtime/python/gnuradio/gr/bindings/python_bindings.cc, gr-blocks/python/blocks/bindings/CMakeLists.txt, gr-blocks/python/blocks/bindings/python_bindings.cc, gr-fft/python/fft/bindings/CMakeLists.txt, gr-fft/python/fft/bindings/python_bindings.cc
=> ctrlport probes: only pybind if ctrlport enabled (backport to maint-3.10)

grc/core/generator/cpp_hier_block.py, grc/core/generator/cpp_templates/flow_graph.hpp.mako, grc/core/generator/cpp_top_block.py
=> GRC: fix C++ hier block generation (backport to maint-3.10)

gr-qtgui/python/qtgui/dialcontrol.py
=> gr-gtqui: Fixed Qt GUI Dial - weird behaviour (backport to maint-3.10)

gr-fft/grc/fft_fft_vxx.block.yml, gr-fft/lib/fft_v_fftw.cc, gr-fft/python/fft/qa_fft.py
=> FFT Window Threadsafety (backport to maint-3.10)

gr-iio/python/iio/bindings/attr_updater_python.cc
=> Fix crash due to broken IIO attribute updater (backport to maint-3.10)

gnuradio-runtime/include/gnuradio/block.h, gnuradio-runtime/python/gnuradio/gr/bindings/block_python.cc, gr-digital/lib/fll_band_edge_cc_impl.cc, gr-digital/lib/fll_band_edge_cc_impl.h, gr-digital/python/digital/qa_fll_band_edge.py
=> FLL bandedge: fix math & thread safety bugs (backport to maint-3.10)

gnuradio-runtime/apps/gnuradio-config-info.cc, gnuradio-runtime/include/gnuradio/sys_paths.h, gnuradio-runtime/lib/sys_paths.cc, gnuradio-runtime/python/gnuradio/gr/bindings/sys_paths_python.cc, gnuradio-runtime/python/gnuradio/gr/qa_sys_paths.py, grc/converter/main.py, grc/core/Config.py, grc/core/Constants.py, grc/core/generator/flow_graph.py.mako, grc/core/platform.py, grc/grc.conf.in, grc/gui/Config.py, grc/gui_qt/Config.py, grc/gui_qt/components/example_browser.py, grc/gui_qt/properties.py, grc/main.py
=> make grc use correct config paths (backport to maint-3.10)

gr-filter/python/filter/gui/polezero_plot.py
=> filter: python: Change float_ to float64 for numpy 2.0 compatibility (backport to maint-3.10)

grc/gui_qt/components/block_library.py, grc/gui_qt/components/canvas/flowgraph.py
#7382 contains some bugs.
See the comments there
This is an better approach to fix these bugs
=> grc-qt: Better solution for #7382

grc/core/generator/flow_graph.py.mako
The geometry of a qt based flowgraph will not be restored as 
the directory for saving and restoring the flowgraph geometry are not the same.
The directory for saving is ~/.config/gnuradio/flowgraphs and for restoring is ~/.config/GNU\ Radio
Run a simple qt based fg  and change it's geometry. After restart the flowgraph should have the changed geometry.
=> grc: python qtgui codegeneration:

grc/core/generator/cpp_templates/flow_graph.cpp.mako, grc/core/generator/cpp_templates/flow_graph.hpp.mako
The generated code loads the geometry of the flowgraph from the wrong diretcory "GNU Radio"
but does not apply these settings.
If you change the geometry of the running flowgraph, these settings are not saved on close.
Setup a fg:
signal_source->throttle->QTGUI Frequency sink
Set output language to c++. Generate and run the fg. Change the geometry. Stop and restart the fg.
=> grc: generating qt - based cpp code is incomplete

grc/core/generator/cpp_templates/flow_graph.cpp.mako, grc/core/generator/cpp_templates/flow_graph.hpp.mako, grc/core/generator/flow_graph.py.mako, grc/gui_qt/components/block_library.py, grc/gui_qt/components/canvas/flowgraph.py, grc/gui_qt/components/variable_editor.py, grc/gui_qt/components/window.py
Backport #7381 
Backport #7382 
Backport #7402 
Backport #7409 
Backport #7411
=> GRC rollup (backport to maint-3.10)

grc/blocks/variable_function_probe.block.yml, grc/core/generator/flow_graph.py.mako, grc/core/generator/top_block.py
=> Python template startup event (backport to maint-3.10)

gr-uhd/CMakeLists.txt, gr-uhd/examples/grc/CMakeLists.txt, gr-uhd/grc/CMakeLists.txt, gr-uhd/python/uhd/CMakeLists.txt, gr-uhd/python/uhd/__init__.py
=> gr-uhd: Do not require PyQt5 for all python functionality (backport to maint-3.10)

grc/gui/Config.py
Exiting 
grc --gtk
fails with
Prefs path:  /grc.conf
[Errno 13] Keine Berechtigung: '/grc.conf'
So the settings like recently opened files or geometry of grc can not be saved.
Just start grc --gtk , open several fg's 
close grc and restart.
=> grc: cannot save general settings

grc/gui/Config.py
=> grc: cannot ave general settings (backport to maint-3.10)

grc/blocks/variable_struct.block.yml.py
=> grc: Struct Variable unaccessible in grc (backport to maint-3.10)

grc/gui/Config.py, grc/gui_qt/Config.py
=> gui_prefs_file does not need to use os.path.join (backport to maint-3.10)

grc/gui_qt/components/dialogs.py
As the ErrorsDialog should only display the errors of the fg, the entries should be readonly and not editable.
Setup a fg that contains errors. Click on the Error Display Box and there click on an item.
You can edit this selected item and edit it. This has no further effect, but it makes no sense to edit these error messags.
So this pr sets the the whole treeview to readonly.
=> grc-qt: Entries in ErrorsDialog are editable

grc/gui_qt/components/block_library.py
Changing the completion mode from InlineCompletion to PopupCompletion for the searchbar of the BlockLib window makes the intermediate results more readable.
Enter some Text in the search field, for instance Range
=> grc-qt: Blocklibrary - change completion mode

gnuradio-runtime/lib/io_signature.cc, gr-blocks/lib/message_debug_impl.cc
fmt::join() was moved into fmt/ranges.h since fmt 11, so let's include the corresponding header in spdlog for using it.
=> blocks,runtime: io_signature: include spdlog/*/ranges.h for using fmt::join()

grc/core/Connection.py, grc/gui/PropsDialog.py, grc/gui_qt/components/block_library.py, grc/gui_qt/components/dialogs.py
Backport #7434 
Backport #7435 
Backport #7437
=> grc: rollup (backport to maint-3.10)

gnuradio-runtime/lib/io_signature.cc, gr-blocks/lib/message_debug_impl.cc
=> blocks,runtime: io_signature: include spdlog/*/ranges.h for using fmt.join() (backport to maint-3.10)

grc/core/FlowGraph.py, grc/gui_qt/components/variable_editor.py
Adding a yaml_config block to an fg fails partially.
grc --gtk only shows an error but displays the block
Loading: "/home/schroer/gnuradiocomponents/bugs/yaml_config.grc" Failed to evaluate variable block yaml_config_0
File "/usr/local/gnuradio/lib64/python3.12/site-packages/gnuradio/grc/core/FlowGraph.py", line 286, in _reload_variables
value = eval(variable_block.value, namespace,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
grc --qt shows an error and segfaults sometimes
Failed to evaluate variable block yaml_config_0
File "/usr/local/gnuradio/lib64/python3.12/site-packages/gnuradio/grc/core/FlowGraph.py", line 286, in _reload_variables
value = eval(variable_block.value, namespace,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File …
=> grc: add yaml_config block fails

grc/gui_qt/components/block_library.py, grc/gui_qt/components/window.py
Reloading the blocklibrary and rebuilding the open fg's is not implemented yet in grc --qt. So on fg's that call a missing hier block,  you have to generate the hier block, stop and restart grc with the fg's.
This pr implements the 'Reload button'.
That is: Rebuilding the blocklibrary, including all blocks found in the .local/state/gnuradio directory and rebuild all opened fg's using the build blocklibrary.
This is the same behaviour as grc --gtk implements.
=> grc-qt: implement missing reload

grc/gui_qt/components/window.py, grc/gui_qt/resources/available_preferences.yml
This pr maintains the list of recently opened files and this list can be used to open one of these files.
In addition an paramter max_recent_files was introduced to determine the maximal length of this list. This parameter can be changed in the preference editor. ( Restart required)
Run grc --qt
Open and close some fg's  and look at
File -> Open recent file
=> grc-qt: Implement 'recent files' list

gr-qtgui/grc/qtgui_sink_x.block.yml, grc/core/generator/cpp_templates/flow_graph.cpp.mako
Sometimes closeEvent is defined several times. In case of building qt cpp code, closeEvent may only be defined once.
This bug was introduced with #7411
Fixes #7500
Fixes #7488
Run the example mentioned in #7500
=> grc: cpp code generation is wrong

grc/core/FlowGraph.py, grc/gui_qt/components/canvas/flowgraph.py, grc/gui_qt/components/window.py
In grc --gtk you can select some blocks and by right clicking on one of the selected blocks, you can generate a skeleton for an hierarchical block.
This option is available in grc --qt, too, but not implemented.
This pr implements the missing function.
=> grc-qt: Implement the missing 'Create hierarchical block' function

gr-filter/grc/filter_band_pass_filter.block.yml, gr-filter/grc/filter_band_reject_filter.block.yml, gr-filter/grc/filter_high_pass_filter.block.yml, gr-filter/grc/filter_hilbert_fc.block.yml, gr-filter/grc/filter_low_pass_filter.block.yml
The templates for cpp code generation for many filters are wrong.
This pr fixes these errors.
In Addition the beta parameter is only displayed in the filter parameter gui, if the window for the filter is Kaiser.
Fixes #7507
Several Filter blocks.
Setup several fg's with different filters
=> grc: fix bugs in cpp templates for many filters

gnuradio-runtime/include/gnuradio/basic_block.h, gnuradio-runtime/python/gnuradio/gr/bindings/basic_block_python.cc
=> Fix a doxygen typo.

grc/gui_qt/components/dialogs.py
Multiline text cannot be saved  ( In comments)
This is fixed now
The return key is connected to the accept button. So you have to reopen the dialog, to do further changes. Now this key only finishes the input on an entry and you can modify this entry again, without reopening.
After changing a parameter the gui is now updated.
For instance open a filter block and change the window parameter from Hamming to Kaiser, than the Beta parameter appears.
Open a highpass filter block.
Change the default window type to kaiser. The Beta parameter should appear.
Go to the "Adanced tab" and try to add a comment and  try to save.
=> grc-qt: some improvements on the PropertyDialog

gnuradio-runtime/lib/pmt/qa_pmt_unv.cc, gr-audio/examples/c++/dial_tone.cc, gr-blocks/lib/annotator_raw_impl.cc, gr-blocks/lib/file_meta_sink_impl.cc, gr-blocks/lib/file_meta_sink_impl.h, gr-blocks/lib/file_meta_source_impl.h, gr-blocks/lib/test_tag_variable_rate_ff_impl.cc, gr-digital/lib/corr_est_cc_impl.h, gr-digital/lib/linear_equalizer_impl.cc, gr-digital/lib/pfb_clock_sync_ccf_impl.cc, gr-digital/lib/pfb_clock_sync_ccf_impl.h, gr-digital/lib/pfb_clock_sync_fff_impl.cc, gr-digital/lib/pfb_clock_sync_fff_impl.h, gr-qtgui/examples/c++/display_qt.cc, gr-qtgui/examples/c++/display_qt.h, gr-uhd/lib/usrp_block_impl.cc
project level: remove `using namespace` of large namespaces; this mostly affects uncritical use of `gr::` and `pmt::`.
The amount of change that was necessary was much smaller than expected.
@argilo's #7524 is a shining example.
compiles.
=> Avoid `using namespace` for all larger namespaces

gr-fec/python/fec/bindings/viterbi_python.cc, gr-uhd/python/uhd/bindings/rfnoc_block_python.cc, gr-uhd/python/uhd/bindings/rfnoc_graph_python.cc, gr-uhd/python/uhd/bindings/rfnoc_rx_streamer_python.cc
During recent merges, hashes weren't updated; this breaks build when the respective python bindings are enabled.
=> bindings: update mismatched hashes

README.md
=> README: update link to the GNU Radio 4 repo

grc/gui_qt/components/window.py
'File Open'  now  starts with directory of the flowgraph file
Same for 'Save as'
Fixes #7590
=> grc-qt: Open starts with directory of the flowgraph file

.github/workflows/conda-build.yml
Conda logs for a single run on Linux are 23 MB (!), which makes them impossible to inspect on the web.
But, a lot of CI failures are found exactly that way, so we should make these logs accessible, if we're already spending so much work and CI time on generating them.
Tried to figure out what went wrong on a CI build, needed to download the log archive, because githubs web UI was helpless.
CI / conda
this PR.
=> CI/conda: convert conda logging groups to github logging groups

gr-network/lib/socket_pdu_impl.cc, gr-network/lib/tcp_sink_impl.cc, gr-network/lib/udp_sink_impl.cc, gr-network/lib/udp_source_impl.cc
Build fails with boost 1.87b1, because of some deprecations that were removed from the API.
The PR might not be perfect/to polish, but at least its here so some other packagers trying to update their boost version can reuse the patches.
From my understanding, the `resolve.resolve` now only supports the 'split' arguments, not the `query` version.
not 100% comfy about the `cbegin()` + dereference use, as:
- im not a c++ hacker
- i know nothing to boost
- i never used gnuradio, so im not fully comfortable with the codebase. i just tried poking at it from a packager POV, trying to update our patched 3.8.2 to 3.10.11. Cf https://marc.info/?t=173235521700002&r=1&w=2
gr-network
Builds fine on OpenBSD, using gnuradio 3.10.11.0 tarball (not built from master/git)
as for runtime testing, none done, …
=> network: fix build with Boost 1.87

gnuradio-runtime/lib/thread/thread.cc, gnuradio-runtime/lib/thread/thread_body_wrapper.cc
#7553 showed that the current, very coarse "we copy all code for 1. Linux, 2. Windows, 3. Mac OS (and all the BSDs, they're the same, right?)" doesn't reflect reality well.
Windows is different between MINGW and MSVC, and not all BSDs are MacOS. So, instead of large redundant blocks, pull the platform decision into the functions, and decide as necessary.
Also, add logging. If the user tried to pin a thread to a CPU and we couldn't do that, we might as well tell them…
Hopefully none functionally; I hope that future porting efforts become easier that way (pretty sure MacOS does support a lot of the functionality that we don't implement on that platform, for example).
ran test suite on Linux.
=> Refactor threads.cc

gr-utils/modtool/cli/CMakeLists.txt, gr-utils/modtool/cli/help.py
This pull request introduces a new `gr_modtool help` command that functions equivalently to `gr_modtool --help`. This addition improves consistency and user experience by integrating the help functionality into the `gr_modtool` CLI in a more intuitive way. The implementation uses the `click` library and the `subprocess` module to execute the existing `gr_modtool --help` command and display its output.
This change resolves issue #7310.
---
Fixes #7310.
---
This change affects the `gr-modtool` CLI utility, specifically by adding a new command (`gr_modtool help`). It does not impact core functionality but enhances the usability of the CLI.
---
- Automated tests were executed during the build process from the modified source code, and all test cases passed successfully.
- Manual testing was …
=>  modtool: added gr_modtool help command that should work exactly like gr_modtool --help

.github/workflows/make-test.yml
Fixes #7605
Now with gnuradio-docker#49 solved, go ahead and remove zsh installation from the build
- [/] I have added tests to cover my changes, and all previous tests pass.
=> CI: remove zsh installation from hash checking run

gr-analog/examples/fm_demod.py, gr-analog/examples/fm_rx.grc, gr-analog/examples/fm_tx.grc, gr-analog/python/analog/wfm_tx.py
Improvements to the examples of FM transmit and receive.
none
gr-analog example (grc and py), plus the wfm_tx hier block.
Testing was done running the examples.
To design the FIR, some specific testing was done:
```python3
import gnuradio.filter as grf
import scipy.signal as sps
import numpy as np 
import matplotlib.pylab as plt
interp_taps= np.array([0.025797341049826308, -0.017086219605472495, -0.011409639989166305, -0.006983299232854528, -0.0035985741010029636, -0.001084750147683033, 0.000714858188143611, 0.0019242846447575248, 0.0026574799127035533, 0.0030017139152705855, 0.003040322168738471, 0.002833791250362273, 0.002444829632348566, 0.001918385806954013, 0.001306359467895133, 0.0006453268613808425, -1.9360508937728516e-05, -0.0006559269686116455, -0.0012240466916086953, …
```
=> Fixes for gr-analog wideband FM examples

.clang-tidy, CMakeLists.txt, gr-utils/blocktool/core/parseheader_generic.py, gr-utils/modtool/CMakeLists.txt, gr-utils/modtool/cli/CMakeLists.txt, gr-utils/modtool/cli/add.py, gr-utils/modtool/cli/base.py, gr-utils/modtool/cli/bind.py, gr-utils/modtool/cli/disable.py, gr-utils/modtool/cli/help.py, gr-utils/modtool/cli/makeyaml.py, gr-utils/modtool/cli/newmod.py, gr-utils/modtool/cli/rename.py, gr-utils/modtool/cli/rm.py, gr-utils/modtool/cli/update.py, gr-utils/modtool/complete_bash.in, gr-utils/modtool/complete_fish.in, gr-utils/modtool/complete_zsh.in, gr-utils/modtool/core/add.py, gr-utils/modtool/tools/util_functions.py, tools/clang_format.py
Backport #7452 
Backport #7468 
Backport #7474 
Backport #7502 
Backport #7525 
Backport #7573
=> tools: rollup (backport to maint-3.10)

gr-blocks/grc/blocks_sigmf_sink_minimal.block.yml, gr-blocks/grc/blocks_sigmf_source_minimal.block.yml
=> blocks: Fix displayed SigMF dataset format strings (backport to maint-3.10)

gr-filter/grc/variable_band_pass_filter_taps.block.yml, gr-filter/grc/variable_band_reject_filter_taps.block.yml, gr-filter/grc/variable_high_pass_filter_taps.block.yml, gr-filter/grc/variable_low_pass_filter_taps.block.yml
=> gr-filter: Fix cpp templates for severl variable filter taps (backport to maint-3.10)

grc/gui_qt/components/variable_editor.py
Clicking the "-" icon on a variable or an import will remove it.
Clicking the "+" icon on the "Variables" or "Imports" tabs creates a new variable or new import accordingly.
Fixes a part of #7615 
The variable editor of the GRC QT gui
Manual testing.
=> GRC: Make "+" and "-" icons work in variable editor as expected

.ci_support/linux_64_numpy1.23python3.11.____cpython.yaml, .ci_support/osx_64_numpy1.23python3.11.____cpython.yaml, .ci_support/win_64_numpy1.23python3.11.____cpython.yaml, .circleci/config.yml, .github/workflows/conda-build.yml, .scripts/build_steps.sh, .scripts/run_osx_build.sh, .scripts/run_win_build.bat
conda CI has been broken. Had to fight a bit with conda smithy.
For posteriority:
```shell
git clone https://github.com/gnuradio/gnuradio /path/to/temporary/gnuradio/repo
podman run --rm -it -v /path/to/temporary/gnuradio/repo:/gnuradio:Z continuum/miniconda3
apt update; apt install -y neovim
git config --global --add safe.directory /gnuradio
git config --global user.email "bob@example.com"
git config --global user.name "bob@example.com"
cd /gnuradio
conda install -y -c conda-forge conda-smithy
conda-smithy rerender --feedstock_config .conda/conda-forge.yml -c
exit
cd /path/to/regular/gnuradio/repo
git checkout -b attempt_to_fix_conda_ci
git pull /path/to/temporary/gnuradio/repo
git commit --amend -s
git cherry-pick {git commit with the logging grouping, which I haven't gotten around to …
```
=> fix the windows and OS X builds (by conda-smithy rerender)

grc/gui_qt/Utils.py, grc/gui_qt/components/window.py, grc/tests/test_qtbot.py
Implements the PDF generation of the fg.
Sets the correct title in the corresponding file dialog. Captures the whole fg for pdf/png/svg even if parts of the fg are invisible. This is the same behavior now as in grc --gtk
Fixes #7609
Checked with several fg's that gnuradio provides as example.
=> grc-qt: Implement PDF screen capture

.ci_support/linux_64_numpy1.23python3.11.____cpython.yaml, .ci_support/osx_64_numpy1.23python3.11.____cpython.yaml, .ci_support/win_64_numpy1.23python3.11.____cpython.yaml, .circleci/config.yml, .github/workflows/conda-build.yml, .github/workflows/make-test.yml, .scripts/build_steps.sh, .scripts/run_osx_build.sh, .scripts/run_win_build.bat, gr-blocks/python/blocks/qa_throttle.py, gr-network/lib/socket_pdu_impl.cc, gr-network/lib/tcp_sink_impl.cc, gr-network/lib/udp_sink_impl.cc, gr-network/lib/udp_source_impl.cc
Make `maint-3.10` CI closer to `main` CI
Backport #7226 
Backport #7464 
Backport #7540 
Backport #7554 (required for Boost in MinGW)
Backport #7555 
Backport #7606 
Backport #7645
=> CI updates (backport to maint-3.10)

gr-soapy/grc/soapy_hackrf_source.block.yml
=> soapy: fix hackrf RF gain value (backport to maint-3.10)

gnuradio-runtime/lib/thread/thread.cc, gnuradio-runtime/lib/thread/thread_body_wrapper.cc
=> Refactor threads.cc (backport to maint-3.10)

gr-blocks/lib/mute_impl.cc, gr-blocks/lib/mute_impl.h, gr-blocks/lib/selector_impl.cc, gr-blocks/python/blocks/qa_mute.py
=> gr-blocks: Add PDU support for Mute and Selector (backport to maint-3.10)

gr-blocks/lib/wavfile_sink_impl.cc, gr-blocks/lib/wavfile_sink_impl.h, gr-blocks/python/blocks/qa_wavfile.py
=> blocks: Reopen wavfile_sink after stop() (backport to maint-3.10)

grc/gui_qt/components/block_library.py, grc/gui_qt/resources/available_preferences.yml
See discussion in #7612
Add a clear button to the searchbar
Fixes #7612 
Search for Add or "Add C" , use key up / down keys
=> grc-qt: Some Improvements for the block library completion

gnuradio-runtime/include/gnuradio/basic_block.h, gnuradio-runtime/python/gnuradio/gr/bindings/basic_block_python.cc, gr-utils/modtool/cli/bind.py, gr-utils/modtool/templates/gr-newmod/python/howto/bindings/bind_oot_file.py
Backport #7519 
Backport #7664
=> Fix typos in modtool and block (backport to maint-3.10)

grc/core/utils/extract_docs.py, grc/gui_qt/Utils.py, grc/gui_qt/components/block_library.py, grc/gui_qt/components/variable_editor.py, grc/gui_qt/components/window.py, grc/gui_qt/resources/available_preferences.yml, grc/tests/test_qtbot.py
Backport #7643 
Backport #7644 
Backport #7649 
Backport #7651
=> GRC Updates (backport to maint-3.10)

gr-analog/python/analog/qa_quadrature_demod.py
=> analog: add end-to-end test for quadrature demod block (backport to maint-3.10)

grc/gui_qt/components/canvas/flowgraph.py, grc/gui_qt/components/window.py
Makes the Cut action undoable. Also, add commit from https://github.com/gnuradio/gnuradio/pull/7613 to prevent redundant move actions.
Fixes #7607
GRC
Manual testing
=> grc-qt: Make Cut action undoable and prevent redundant Move actions

gr-blocks/python/blocks/qa_wavfile.py
=> blocks: Use a fresh flow graph for part 3 of append test (backport to maint-3.10)

grc/gui_qt/components/variable_editor.py, grc/gui_qt/components/window.py
=> grc-qt: Fix properties dialog in variable editor, alternativ solution (maint-3.10)

grc/gui_qt/components/canvas/block.py, grc/gui_qt/components/flowgraph_view.py
Right-clicking in the canvas now brings up a context menu on a selected block. If multiple blocks are selected the context menu is assoziated to the 'first' block in the list. If no block a hint appears.
If the mouse is over a block this block will be selected.
Fixes #7610
=> grc-qt: Right-clicking in the canvas doesn't bring up the context menu

gr-uhd/grc/uhd_fpga_device_bsp.block.yml
=> uhd: Fix radio clocks for X440 / image builder (backport to maint-3.10)

gnuradio-runtime/lib/thread/thread.cc, gr-trellis/include/gnuradio/trellis/interleaver.h, gr-trellis/python/trellis/bindings/interleaver_python.cc
=> spelling (backport to maint-3.10)

gr-blocks/grc/blocks_vector_insert_x.block.yml
Vector Insert: replace 0, 0, 0 default argument with [0, 0, 0]
=> replace 0, 0, 0 default argument with [0, 0, 0] in Vector Insert

gr-blocks/grc/blocks_vector_insert_x.block.yml
Signed-off-by: Jean-Michel Friedt <friedtj@free.fr>
=> Backport #7742

grc/gui_qt/components/canvas/block.py
complexity calculation is broken on GRC Qt
Fixes https://github.com/gnuradio/gnuradio/issues/7602
options block
pytest and manual gui testing on GRC-Qt
The options block now show the flow graph complexity correctly
=> grc-qt: fix broken complexity calculation

grc/gui_qt/components/canvas/block.py
Fixes https://github.com/gnuradio/gnuradio/issues/7594 (Missing Blocks should always show their ID, regardless of global setting)
GRC Qt
Manual testing
=> grc-qt: Always show key for missing blocks

gr-qtgui/lib/eye_sink_c_impl.cc, gr-qtgui/lib/eye_sink_f_impl.cc, gr-qtgui/lib/time_sink_f_impl.cc
=> Backport 7637

grc/gui_qt/components/window.py
Fixes: In GRC Qt, the Close action (unless you press the close button on a specific tab) closes the wrong tab. 
GRC
Manual testing
=> grcqt: Close correct tab on Ctrl+W

gnuradio-runtime/lib/buffer_single_mapped.cc
=> BP 7865 (buffer single mapped: locking)

.github/workflows/make-test.yml
- **CI: Remove Ubuntu 20.04 builder on main**
- **CI: use parallelism as nproc, or as defined**
Builder time is precious; and whatever becomes GNU Radio 3.11 will not be targetting Ubuntu 20.04
Drive-by: adjust concurrency to make things build in as many threads as processors available.
none
github CI
none
=> Don't run CI on Ubuntu 20.04 for main

gnuradio-runtime/include/pmt/pmt.h
Improve docstrings of pmt::list* functinos, see #7892
Closes #7892
Documentation of PMT functions only
NA
=> PMT: Improve pmt::list* documentation
