gr-blocks/grc/blocks_message_strobe_random.block.yml, gr-blocks/include/gnuradio/blocks/message_strobe_random.h, gr-blocks/lib/message_strobe_random_impl.cc, gr-blocks/lib/message_strobe_random_impl.h, gr-blocks/python/blocks/bindings/message_strobe_random_python.cc, gr-zeromq/examples/zmq_msg.grc
(cherry picked from commit bb554fae5f69616b7e7bc047154a57e3b9f39d9f)
Backport https://github.com/gnuradio/gnuradio/pull/5669
=> blocks: Add exponential distribution to Message Strobe Random-Delay (backport to maint-3.9)

grc/scripts/freedesktop/org.gnuradio.grc.metainfo.xml
Backport https://github.com/gnuradio/gnuradio/pull/5615/commits
=> grc: add .desktop suffix to the desktop launchable, other metainfo fixes (backport to maint-3.9)

grc/compiler.py, grc/core/generator/hier_block.py
---
The generated code is written to the directory of the generating grc file
instead to the 'hier_block_lib_dir' directory.
cpp generated code ends up in the correct directory.
This error was introduced with commit af3fbe432fe16efb05f26c24a0fa9724680dc8dd
Take the directory from the config settings ( as before)
Fixes #5531
Tested with different hier blocks
=> grc: A generated python hier_block is written to the wrong directory

gr-blocks/include/gnuradio/blocks/file_sink_base.h, gr-blocks/lib/ctrlport_probe_c_impl.h, gr-blocks/lib/file_source_impl.h, gr-blocks/lib/message_strobe_impl.cc, gr-blocks/lib/message_strobe_random_impl.cc, gr-blocks/lib/probe_rate_impl.cc, gr-blocks/lib/probe_rate_impl.h, gr-blocks/lib/qa_set_msg_handler.cc, gr-blocks/lib/wavfile_sink_impl.h, gr-blocks/python/blocks/bindings/file_sink_base_python.cc
This pull request removes all usage of Boost from gr-blocks except for Boost.Test in test cases.
In a few cases, `boost::mutex` was used in headers but the implementation used it in `gr::thread::scoped_lock`, so I changed those to `gr::thread::mutex` (which can eventually be implemented as `std::mutex`).
In one case `boost::shared_mutex` was used, but shared locking was not actually used, so I replaced it with `gr::thread::mutex`.
* Ctrlport Probe
* File Sink
* File Source
* Message Strobe
* Message Strobe Random-Delay
* Probe Rate
* Wav File Sink
I tested the Message Strobe, Message Strobe Random-Delay, and Probe Rate blocks with the following flow graph:
All work as before.
=> blocks: Remove usage of Boost

gnuradio-runtime/include/gnuradio/io_signature.h, gnuradio-runtime/lib/io_signature.cc, gnuradio-runtime/python/gnuradio/gr/bindings/io_signature_python.cc
By forcing the default buffer type to host_buffer instead of buffer_double_mapped, we can more thoroughly test the single mapped buffers through all the QA.  This should not be enabled by default
None
By default should have no impact, only enabled for testing purposes with a #define
=> runtime: expose mechanism for testing host_buffer

gnuradio-runtime/lib/vmcircbuf_createfilemapping.cc, gnuradio-runtime/lib/vmcircbuf_prefs.cc
When a flow graph is executed for the first time, and `~/.gnuradio` does not exist, the following error messages are printed:
```
vmcircbuf_prefs::get :erro: /home/argilo/.gnuradio/prefs/vmcircbuf_default_factory: No such file or directory
gr::vmcircbuf :error: vmcircbuf_createfilemapping: createfilemapping is not available
```
These are expected situations, so they should not be logged at the error level. Other similar vmcircbuf messages are logged to the debug logger at the info level, so I've done that here as well.
In addition, I changed `createfilemapping` to `CreateFileMapping` to reflect the actual name of the function.
After these changes, no log messages are printed the first time GNU Radio is used, since the debug logger is set to the emerg level by default.
To test, I simply …
=> runtime: Make vmcircbuf logging quieter

gnuradio-runtime/lib/vmcircbuf_createfilemapping.cc, gnuradio-runtime/lib/vmcircbuf_prefs.cc
When a flow graph is executed for the first time, and ~/.gnuradio does
not exist, the following error messages are printed:
vmcircbuf_prefs::get :erro: /home/argilo/.gnuradio/prefs/vmcircbuf_default_factory: No such file or directory
gr::vmcircbuf :error: vmcircbuf_createfilemapping: createfilemapping is not available
These are expected situations, so they should not be logged at the error
level. Other similar vmcircbuf messages are logged to the debug logger
at the info level, so I've done that here as well.
In addition, I changed createfilemapping to CreateFileMapping to reflect
the actual name of the function.
After these changes, no log messages are printed the first time GNU Radio
is used, since the debug logger is set to the emerg level by default.
Signed-off-by: Clayton Smith …
=> runtime: Make vmcircbuf logging quieter (backport to maint-3.10)

gr-blocks/grc/blocks_matrix_interleaver.block.yml
Removed co-author's name from yml doc
(cherry picked from commit 141c0da0349703a483d0c5931d01ed207dcdd3b6)
Backport https://github.com/gnuradio/gnuradio/pull/5550
=> Remove co-author's name from documentation (backport to maint-3.8)

gr-trellis/python/trellis/bindings/pccc_decoder_blk_python.cc, gr-trellis/python/trellis/bindings/pccc_decoder_combined_blk_python.cc, gr-trellis/python/trellis/bindings/pccc_encoder_python.cc, gr-trellis/python/trellis/bindings/sccc_decoder_blk_python.cc, gr-trellis/python/trellis/bindings/sccc_decoder_combined_blk_python.cc, gr-trellis/python/trellis/bindings/sccc_encoder_python.cc, gr-trellis/python/trellis/bindings/viterbi_combined_python.cc, gr-trellis/python/trellis/qa_trellis.py
Backport #5671
Backport #5683
Backport #5707
Note that 5707 is a rollup of
#5674
#5679
#5680
#5684
#5685
=> Trellis PyBind11 Rollup (backport to maint-3.9)

grc/CMakeLists.txt, grc/blocks/CMakeLists.txt
(cherry picked from commit b03529038f172e00c9f1835487d7954702461c85)
Backport https://github.com/gnuradio/gnuradio/pull/5698
#5698 also contains 5e062831f5, having to do with Conda builds. This commit was not included in the backport.
=> GRC: add jsonschema check for JSON/YAML blocks module

grc/CMakeLists.txt
---
name: Pull Request for gnuradio main
about: generating grc.conf
title: 'look for x-terminal-emulator'
labels: ''
assignees: ''
---
When building gnuradio in a clean build environment, which is great for doing
repeatable builds, the CMake logic for generating the grc.conf file
left nothing for the xterm_executable.
This leads to a confusing error the first time a user runs gnuradio-companion.
This patch uses c-terminal-emulator by default. Which is a nice choice in Debian and Ubuntu.
gnuradio-companion
This patch has long been in debian/patches
Recently not included, the result was quickly noticed.
I added foot to the search list. It does the right thing when running
gnuradio-companion under Wayland and the sway window manager, …
=> look for x-terminal-emulator

grc/CMakeLists.txt
Backport #5730
---
name: Pull Request for gnuradio 3.10
about: generating grc.conf
title: 'look for x-terminal-emulator'
labels: ''
assignees: ''
---
When building gnuradio in a clean build environment, which is great for doing
repeatable builds, the CMake logic for generating the grc.conf file
left nothing for the xterm_executable.
This leads to a confusing error the first time a user runs gnuradio-companion.
This patch uses c-terminal-emulator by default. Which is a nice choice in Debian and Ubuntu.
gnuradio-companion
This patch has long been in debian/patches
Recently not included, the result was quickly noticed.
I added foot to the search list. It does the right thing when running
gnuradio-companion under Wayland and the sway …
=> look for x-terminal-emulator (backport to maint-3.10)

gnuradio-runtime/python/gnuradio/ctrlport/gr-perf-monitorx
The gr-perf-monitorx tool currently fails with the following error:
```
gr-perf-monitorx: lost connection (draw_networkx_nodes() got an unexpected keyword argument 'arrows').
```
[`draw_networkx_nodes`](https://networkx.org/documentation/stable/reference/generated/networkx.drawing.nx_pylab.draw_networkx_nodes.html) does not have an `arrows` argument.
The tool runs correctly once the incorrect keyword argument is removed.
* gr-perf-monitorx
I tested as follows:
1. Build GNU Radio with ControlPort support: `-DENABLE_CTRLPORT_THRIFT=True`.
2. Enable the following in gnuradio-runtime.conf:
```
[PerfCounters]
on = True
export = True
[ControlPort]
on = True
edges_list = True
```
3. Run a flow graph
4. Run `gr-perf-monitorx <port>`
=> runtime: Remove invalid keyword argument from draw_networkx_nodes

gr-fft/include/gnuradio/fft/fft.h, gr-fft/lib/ctrlport_probe_psd_impl.cc, gr-fft/lib/ctrlport_probe_psd_impl.h, gr-fft/lib/fft.cc
This pull request removes most of gr-fft's usage of Boost, by replacing it with standard C++.
(All that remains are `boost::interprocess::file_lock` for FFT wisdom locking, and two C++ tests that could be converted to Python if the Python binding for `fft_shift` was completed.)
* FFT planner
* Ctrlport Probe PSD block
To test the FFT planner, I ran Gqrx and switched between various FFT sizes.
I have not tested the Ctrlport Probe PSD block. I'd appreciate help from someone familiar with Ctrlport.
=> fft: Replace Boost with standard C++

gr-blocks/lib/CMakeLists.txt, gr-blocks/lib/probe_signal_impl.h, gr-blocks/lib/probe_signal_v_impl.cc, gr-blocks/lib/probe_signal_v_impl.h, gr-blocks/python/blocks/qa_probe_signal.py
While looking into #4322, I found that the root cause of the issue is that the Probe Signal Vector block is not synchronized: if `level()` is called while the work function is writing to `d_level`, then invalid data will be returned. The same is true of the Probe Signal block. To fix these problems, I did the following:
1. In the Probe Signal block, change `d_level` from `T` to `std::atomic<T>`.
2. In the Probe Signal Vector block, use a mutex to synchronize access to `d_level`.
I also added regression tests which readily fail without these changes, and pass with them.
* Fixes #2206.
* Fixes #4322.
* Probe Signal
* Probe Signal Vector
* Verified that `qa_filterbank` no longer fails, even when its `sleep`s are removed.
* Verified that the new regression tests fail without the code changes, …
=> blocks: Synchronize access to d_level to prevent race conditions

gnuradio-runtime/include/gnuradio/rpcpmtconverters_thrift.h, gnuradio-runtime/include/gnuradio/thread/thread_group.h, gnuradio-runtime/include/pmt/pmt.h, gnuradio-runtime/lib/hier_block2_detail.h, gnuradio-runtime/lib/scheduler.h, gnuradio-runtime/python/gnuradio/gr/bindings/thread/thread_group_python.cc
C++11 allows the default copy constructor and copy-assignment operator to be deleted, meaning that `boost::noncopyable` is no longer required. I've made that change here.
* `rpcpmtconverter::To_PMT`
* `thread_group`
* `hier_block2_detail`
* `scheduler`
I verified that Gqrx runs correctly after these changes. I expect that will test everything except `rpcpmtconverter::To_PMT`.
=> runtime: Replace boost::noncopyable with standard C++

gr-blocks/lib/CMakeLists.txt
(cherry picked from commit afaddfe9d109204fa65485a7d59fe9a8c3399300)
Backport afaddfe9d109204fa65485a7d59fe9a8c3399300 only from https://github.com/gnuradio/gnuradio/pull/5559
=> Cross compiling is skipping c++ tests, don't try to set properties on them (backport to maint-3.9)

gr-filter/python/filter/qa_freq_xlating_fft_filter.py
The `qa_freq_xlating_fft_filter` test frequently fails. For example:
* https://github.com/gnuradio/gnuradio/runs/5821437722?check_suite_focus=true
* https://github.com/gnuradio/gnuradio/runs/5821466413?check_suite_focus=true
This test has been problematic in the past: 1c74a4bb5fb9e13323ed768d24a96169f7d0182c
The test uses `assertComplexTuplesAlmostEqual2` to check the output samples against the expected values:
https://github.com/gnuradio/gnuradio/blob/3349d483a1f7e5db0eea042815d237810373857b/gr-filter/python/filter/qa_freq_xlating_fft_filter.py#L75-L76
For each sample, `assertComplexTuplesAlmostEqual2` checks whether the absolute error is less than `1e-9`, and if not it checks whether the relative error is less than `1.5e-3`. But `1e-9` is smaller than the precision of the floating point …
=> filter: Fix flaky freq xlating filter test

grc/gui/Application.py
Fixes an error on creating hier, which states that "top_block" is missing, thus making the option "Create hier" unusable. Affects gnuradio >= 3.8.
On selecting several blocks, right click "More -> Create Hier", the expected behaviour should be to create a new hier consisting of the selected blocks and to add pads to the hier block. Instead there is an error stating that "top_block" cannot be found.
No issue found.
Affects gnuradio-companion on using the menu "Create hier" as suggested in the wiki https://wiki.gnuradio.org/index.php?title=Hier_Blocks_and_Parameters
The function was tested and seemed to work fine.
=> Fix create hier / missing top_block error

gr-uhd/lib/usrp_block_impl.cc
See https://github.com/gnuradio/gnuradio/issues/5681  
Bug was introduced in https://github.com/gnuradio/gnuradio/commit/9cdfe5141a7aad1cf9c4c81167761cc291913fb0
Fixes https://github.com/gnuradio/gnuradio/issues/5681
UHD
Yes. Compiled UHD and GNUradio with the proposed change cherry picked on top of v3.10.1.1 from source. Function call works as expected.
- ~~I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.~~
- ~~I have added tests to cover my changes, and all previous tests pass.~~
=> Fix: UHD get_gpio_attr throws RuntimeError "Not implemented"

gr-blocks/python/blocks/qa_rotator_cc.py
The `test_phase_inc_update_out_of_range` test in `qa_rotator` sometimes fails. For instance: https://github.com/gnuradio/gnuradio/runs/5772119971?check_suite_focus=true
This is due to a race condition. The test schedules a phase increment for 32,768 samples in the future, waits for some samples to be processed, and then verifies that the phase increment has not yet occurred. But it can happen (and often does happen with the system is under load) that more than 32,768 samples will be processed between these two steps.
https://github.com/gnuradio/gnuradio/blob/3349d483a1f7e5db0eea042815d237810373857b/gr-blocks/python/blocks/qa_rotator_cc.py#L286-L318
To solve the problem, I've added a throttle block to the flow graph, so that it will take 500 ms for 32,768 samples to be processed. This …
=> blocks: Fix flaky qa_rotator test

gr-dtv/lib/dvbt2/dvbt2_framemapper_cc_impl.cc
The `qa_dtv` test sometimes fails in CI, for instance:
* https://github.com/gnuradio/gnuradio/runs/5536495515?check_suite_focus=true
* https://github.com/gnuradio/gnuradio/runs/5435832708?check_suite_focus=true
Valgrind shows that `dvbt2_framemapper_cc_impl::add_l1post` accesses uninitialized memory, and I tracked this down to the fact that the `plp_id_dynamic` member of the `L1Post` struct is not initialized. It appears there is a typo in the constructor, where `plp_id` is initialized twice. I've corrected the second instance to `plp_id_dynamic`, which resolves the valgrind warning.
I also confirmed that this is the source of CI failures: If `plp_id_dynamic` is initialized to 1 instead of 0, then `qa_dtv` fails every time.
QA for DVB-T2 Frame Mapper block.
=> dtv: Fix initialization of L1Post struct

gnuradio-runtime/lib/controlport/thrift/rpcserver_thrift.cc
This change removes a bit more Boost from gnuradio-runtime, replacing `boost::xpressive` with `std::regex`.
* ControlPort
I tested this functionality using the gr-perf-monitorx utility, which uses ControlPort's regular expression functionality: https://github.com/gnuradio/gnuradio/blob/3349d483a1f7e5db0eea042815d237810373857b/gnuradio-runtime/python/gnuradio/ctrlport/gr-perf-monitorx#L484
gr-perf-monitorx was broken, so I fixed that in #5737. Testing instructions can also be found there.
=> runtime: Replace boost::xpressive with std::regex

gr-filter/lib/filterbank_vcvcf_impl.cc, gr-filter/python/filter/qa_filterbank.py
The `qa_pfb_channelizer` sometimes fails in CI. For example: https://github.com/gnuradio/gnuradio/runs/5535718772?check_suite_focus=true
Running the test in valgrind reveals two bugs:
* `filterbank_vcvcf_impl::general_work` reads `d_updated` before it is initialized.
* `filterbank_vcvcf_impl::general_work` passes an unaligned buffer (`working`) into `fir_filter::filter`, which requires its input buffer to be aligned.
The second bug can result in `volk_32fc_32f_dot_prod_32fc_a` reading data from outside the `working` buffer, corrupting the filter calculation. (Out-of-bounds values are multiplied by zero, but this can still result in `NaN`, as seen in the CI failure.)
To fix these problems, I did the following:
* Initialize `d_updated` to false in the constructor.
* Allocate `working` using …
=> filter: Fix various bugs in Generic Filterbank

gr-pdu/python/pdu/qa_add_system_time.py
In #5628 I increased the tolerance in `qa_add_system_time` to resolve flakiness, but failures still occur, e.g. in https://github.com/gnuradio/gnuradio/runs/5773908338?check_suite_focus=true where the time difference was 0.217.
Since the tolerance wasn't high enough, I'm increasing it to 0.5 here.
* #5628
This is a QA-only change to the Add System Time block.
* Verified that the test still passes locally.
=> pdu: Increase tolerance for qa_add_system_time test

gnuradio-runtime/python/gnuradio/gr/qa_uncaught_exception.py
The `qa_uncaught_exception` test sometimes fails in CI, for instance: https://github.com/gnuradio/gnuradio/runs/5827362248?check_suite_focus=true
This happens because the flow graph may take more than 2.5 seconds to execute. (The timeout was previously increased from 0.5 seconds to 2.5 seconds in https://github.com/gnuradio/gnuradio/pull/3029, but it's still not enough.)
Here I've increased the timeout to 10 seconds. This doesn't slow down the test in the success case, since the `join` returns as soon as the flow graph finishes.
* https://github.com/gnuradio/gnuradio/pull/3029
None. This change only affects tests.
Played with the test locally and verified that it fails when the timeout is too low, and that increasing the timeout doesn't slow down the test.
=> runtime: Fix flaky qa_uncaught_exception test

gr-utils/modtool/templates/gr-newmod/.conda/README.md, gr-utils/modtool/templates/gr-newmod/.conda/conda-forge.yml, gr-utils/modtool/templates/gr-newmod/.conda/recipe/bld.bat, gr-utils/modtool/templates/gr-newmod/.conda/recipe/build.sh, gr-utils/modtool/templates/gr-newmod/.conda/recipe/conda_build_config.yaml, gr-utils/modtool/templates/gr-newmod/.conda/recipe/meta.yaml
This recipe will allow building a conda package for OOT modules with little or no modification after the template is rendered. Developers can also use the recipe with conda-smithy to create CI scripts for building and testing their OOT module.
gr_modtool
I tried it out on gr-paint here: https://github.com/ryanvolz/gr-paint/tree/conda. First I ran gr_modtool to create a "new" paint module, and then I copied the `.conda` directory into the existing module. Then I make some modifications to the recipe to add appropriate metadata and an additional runtime dependency. I also needed to modify the tests to correspond to the old, pre-3.10 module structure (i.e. includes and Python modules moved to be under "gnuradio"), but this is only necessary because it was an existing OOT and those changes …
=> utils: modtool: Add a conda recipe to the OOT template

gr-pdu/CMakeLists.txt, gr-pdu/include/gnuradio/pdu/add_system_time.h, gr-pdu/lib/add_system_time_impl.cc, gr-pdu/lib/add_system_time_impl.h, gr-pdu/lib/pdu_to_stream_impl.cc, gr-pdu/lib/tags_to_pdu_impl.cc, gr-pdu/lib/tags_to_pdu_impl.h, gr-pdu/lib/time_delta_impl.cc, gr-pdu/lib/time_delta_impl.h, gr-pdu/python/pdu/bindings/add_system_time_python.cc
gr-pdu uses Boost in only a few places. I've replaced them with standard C++ here.
* `boost::this_thread::sleep` -> `std::this_thread::sleep_for`
* `boost::posix_time::microseconds` -> `std::chrono::microseconds`
* `boost::get_system_time` -> `std::chrono::system_clock::now`
I also got rid of `d_epoch`, since `std::chrono::system_clock` uses the Unix epoch in practice. (This is guaranteed to be the case beginning in C++20.)
* Add System Time
* PDU To Stream
* Tags To PDU
* Time Delta
I have not yet done any testing. I'd appreciate help from someone familiar with gr-pdu.
=> pdu: Replace Boost with standard C++

gr-qtgui/grc/qtgui_freq_sink_x.block.yml, gr-qtgui/grc/qtgui_sink_x.block.yml, gr-qtgui/grc/qtgui_vector_sink_f.block.yml, gr-qtgui/grc/qtgui_waterfall_sink_x.block.yml
freq_sink_x, sink_x, vector_sink_f .... produce error messages like
```
File "/usr/local/gnuradio/lib64/python3.10/site-packages/gnuradio/grc/core/blocks/_templates.py", line 77, in render
return template.render(**namespace)
File "/usr/lib/python3.10/site-packages/mako/template.py", line 473, in render
return runtime._render(self, self.callable_, args, data)
File "/usr/lib/python3.10/site-packages/mako/runtime.py", line 878, in _render
_render_context(
File "/usr/lib/python3.10/site-packages/mako/runtime.py", line 920, in _render_context
_exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
File "/usr/lib/python3.10/site-packages/mako/runtime.py", line 947, in _exec_template
callable_(context, *args, **kwargs)
File "memory:0x7f00a04d3a00", line …
```
=> gr-qtgui: freq_sink and others produce wrong error messages, when GUI Hint is used

gr-qtgui/include/gnuradio/qtgui/form_menus.h, gr-qtgui/lib/const_sink_c_impl.cc, gr-qtgui/lib/eye_sink_c_impl.cc, gr-qtgui/lib/eye_sink_f_impl.cc, gr-qtgui/lib/freq_sink_c_impl.cc, gr-qtgui/lib/freq_sink_f_impl.cc, gr-qtgui/lib/histogram_sink_f_impl.cc, gr-qtgui/lib/sink_c_impl.cc, gr-qtgui/lib/sink_f_impl.cc, gr-qtgui/lib/time_raster_sink_b_impl.cc, gr-qtgui/lib/time_raster_sink_f_impl.cc, gr-qtgui/lib/time_sink_c_impl.cc, gr-qtgui/lib/time_sink_f_impl.cc, gr-qtgui/lib/vector_sink_f_impl.cc, gr-qtgui/lib/waterfall_sink_c_impl.cc, gr-qtgui/lib/waterfall_sink_f_impl.cc
gr-qtgui has some conditionally compiled code that targets Qt 4. This should not be needed anymore, because Qt 5 was released almost a decade ago and all platforms that GNU Radio targets should have Qt 5.
* QT GUI Constellation Sink
* QT GUI Eye Sink
* QT GUI Frequency Sink
* QT GUI Histogram Sink
* QT GUI Number Sink
* QT GUI Sink
* QT GUI Time Raster Sink
* QT GUI Time Sink
* QT GUI Vector Sink
* QT GUI Waterfall Sink
I verified that all the affected sinks still work properly.
=> qtgui: Remove conditional code targeting Qt 4

gr-utils/modtool/templates/gr-newmod/.conda/recipe/meta.yaml
The version for an untagged OOT is based on the date, and previously this included hour and minute. That's too specific and leads to CI-built packages from the same run often having different versions. This can still happen, but stopping at the year, month, and day is much saner. I don't know what I was thinking previously.
Note for backporting: this can be merged with #5673, commit e3efb76617087e778026086287c6e545f6be2c0f.
=> gr_newmod: Make untagged conda package version less specific

gr-digital/grc/digital_crc_append.block.yml, gr-digital/grc/digital_crc_check.block.yml, gr-digital/include/gnuradio/digital/crc_check.h, gr-digital/python/digital/bindings/crc_check_python.cc
I've just noticed a typo in the GRC files for the CRC blocks. I didn't see this typo when I sent #5619. The blocks are already backported to 3.10, so the typo correction should also be backported. The backport to 3.9 is still not merged (it's in #5694) and perhaps this correction can be incorporated into that PR.
CRC Append and CRC Check.
=> digital: fix typo in CRC Append and Check GRC blocks

gr-soapy/lib/block_impl.cc
It was reported that, with the HackRF module, a flowgraph terminated
with a segfault. Most Soapy modules implement deactivateStream(), but
that function is not called from gr-soapy.
Problem reported by Gavin Jacobs on the mailing list.
gr-soapy
=> gr-soapy: deactivate stream before closing

cmake/Modules/GrPython.cmake
Recently in Debian's pthon3.10 the default scheme for sysconfig
changed from 'posix_prefix' to 'posix_local'. GrPython.cmake
expects the 'posix_prefix' behavior. So explicity use it.
---
name: grpython use posix prefix scheme
about: GrPython.cmake
title: ''
labels: ''
assignees: ''
---
Install path changed to /usr/local with python3.10 - even though the desire
is to set the install directories using gnuradio's cmake paths.
Debian bug:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1008854
Not only gnuradio itself - but every OOT project that inherits GrPython.cmake.
Debian builds as part of the python3.10-default transition.
=> grpython use posix prefix scheme

gr-iio/grc/iio_pluto_sink.block.yml
As reported here: https://ez.analog.com/adieducation/university-program/f/q-a/557699/pluto-run-time-error-with-grc-3-10 the gr-iio pluto sink block attenuation callback causes a runtime error in gnuradio-companion when changing it. This is due to incorrect parameters being passed to the callback. Pluto Sink is a specialized fmcomms2 sink which requires a channel id when setting the attenuation.
Signed-off-by: Adrian Suciu <adrian.suciu@analog.com>
=> gr-iio: fix grc block pluto sink attenuation callback

gr-utils/modtool/tools/util_functions.py
When running `gr_modtool bind` or `gr_modtool rm`, a crash occurs because `get_block_names` tries to open the wrong include directory. It does not take into account the new structure introduced in #5265. I've fixed that here.
```
File "/home/argilo/prefix_310/bin/gr_modtool", line 18, in <module>
cli()
File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
return self.main(*args, **kwargs)
File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
rv = self.invoke(ctx)
File "/usr/lib/python3/dist-packages/click/core.py", line 1659, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
return ctx.invoke(self.callback, **ctx.params)
File …
```
=> modtool: Fix gr_modtool bind & rm

cmake/Modules/GrPython.cmake
This restores behavior on Windows to what it was prior to the recent fix to deal with Debian overriding the default scheme (#5739). Other platforms remain as they currently are.
=> cmake: Set "nt" install scheme for Python on Windows

cmake/Modules/GrVersion.cmake
This prevents the hash from being misinterpreted as a number, which MSVC does which will caused failed builds. This is never an issue with GR itself because the plain hash is only used for the version when the repository is untagged, but it can happen with OOTs which also use GrVersion.cmake.
This works by removing the `--always` flag from `git describe` and handling the no-tag case as a separate special case.
I have been unlucky enough to twice now encounter all-numeric short hashes when building untagged OOTs with MSVC, so I can't ignore it.
CMake, untagged OOTs.
I created a freshly-initialized repository with my local gnuradio so that no git tags were present, ran `cmake`, and verified that the version it identified was the letter "g" followed by the short commit hash.
=> cmake: Always prefix git hash used as version with "g"

gr-fft/include/gnuradio/fft/fft.h, gr-fft/lib/ctrlport_probe_psd_impl.cc, gr-fft/lib/ctrlport_probe_psd_impl.h, gr-fft/lib/fft.cc
(cherry picked from commit df7c7fff7d20acb2a068defd01d4555110b2b8a8)
Backport https://github.com/gnuradio/gnuradio/pull/5704
=> fft: Replace Boost with standard C++ (backport to maint-3.10)

gnuradio-runtime/python/gnuradio/ctrlport/gr-perf-monitorx
The gr-perf-monitorx tool currently fails with the following error:
gr-perf-monitorx: lost connection (draw_networkx_nodes() got an
unexpected keyword argument 'arrows').
The tool runs correctly once the incorrect keyword argument is removed.
(cherry picked from commit 16e2221503f7fa2d20cf93e32283be6fb00d7a9d)
Backport https://github.com/gnuradio/gnuradio/pull/5737
=> runtime: Remove invalid keyword argument from draw_networkx_nodes (backport to maint-3.10)

gr-blocks/lib/CMakeLists.txt, gr-blocks/lib/probe_signal_impl.h, gr-blocks/lib/probe_signal_v_impl.cc, gr-blocks/lib/probe_signal_v_impl.h, gr-blocks/python/blocks/qa_probe_signal.py
(cherry picked from commit 775efb182ef3d273c2490e6d208119e3fdef33f8)
Backport https://github.com/gnuradio/gnuradio/pull/5744
=> blocks: Synchronize access to d_level to prevent race conditions (backport to maint-3.10)

grc/gui/Application.py
Signed-off-by: Bjoern Kerler <info@revskills.de>
(cherry picked from commit b89baa29b0fe63cb8691575f9784628bea4a4aec)
Backport https://github.com/gnuradio/gnuradio/pull/5702
=> grc: Fix create hier / missing top_block error (backport to maint-3.10)

gr-uhd/lib/usrp_block_impl.cc
Fixes https://github.com/gnuradio/gnuradio/issues/5681
Bug was introduced in https://github.com/gnuradio/gnuradio/commit/9cdfe5141a7aad1cf9c4c81167761cc291913fb0
Signed-off-by: Philipp Niedermayer <eltos@outlook.de>
(cherry picked from commit c6586f9af80e79c33ec9f4affdf239415151aeae)
Backport https://github.com/gnuradio/gnuradio/pull/5682
=> gr-uhd: Fix NotImplemented Error (backport to maint-3.10)

gnuradio-runtime/include/gnuradio/basic_block.h, gnuradio-runtime/python/gnuradio/gr/bindings/basic_block_python.cc
Various tests involving message passing fail intermittently, for example `qa_packet_headerparser_b`. One or more messages fail to arrive at the `message_debug` block when the flow graph stops processing samples. This occurs due to a race condition in `tpb_thread_body`.
The [main loop of `tpb_thread_body`](https://github.com/gnuradio/gnuradio/blob/3349d483a1f7e5db0eea042815d237810373857b/gnuradio-runtime/lib/tpb_thread_body.cc#L70-L152) iterates over the message queues in an undefined order, reading pending messages from each. One of these queues is the special "system" queue; if a "done" message arrives on this queue, then the corresponding handler sets `d_finished` to true, which will later cause the main loop to exit:
https://github.com/gnuradio/gnuradio/blob/3349d483a1f7e5db0eea042815d2 …
=> runtime: Process system messages before others

gnuradio-runtime/python/gnuradio/gr_unittest.py
the assertSequenceEqualGR method gets around a python unittest bug that hangs when the sequences aren't equal.  This method that was introduced in #5028 works around that.  In the printing of the results though it does assume integer values on the lists - which is removed here
some QA tests
CI should be sufficient
=> qa: remove formatting in assertSequenceEqualGR

gr-dtv/lib/dvbt2/dvbt2_framemapper_cc_impl.cc
Valgrind reports that `poly_pack` reads uninitialized memory, leading to undefined behaviour. This happens because it rounds the length up to the next multiple of 32 before reading the polynomial coefficients. Initializing the coefficients to zero solves the problem.
```
==1539339== Conditional jump or move depends on uninitialised value(s)
==1539339==    at 0x4C3174CE: poly_pack (dvbt2_framemapper_cc_impl.cc:994)
==1539339==    by 0x4C3174CE: gr::dtv::dvbt2_framemapper_cc_impl::bch_poly_build_tables() (dvbt2_framemapper_cc_impl.cc:1032)
==1539339==    by 0x4C31AC60: gr::dtv::dvbt2_framemapper_cc_impl::dvbt2_framemapper_cc_impl(gr::dtv::dvb_framesize_t, gr::dtv::dvb_code_rate_t, gr::dtv::dvb_constellation_t, gr::dtv::dvbt2_rotation_t, int, int, gr::dtv::dvbt2_extended_carrier_t, …
```
=> dtv: Fix use of uninitialized memory

gr-dtv/lib/dvbt2/dvbt2_framemapper_cc_impl.cc
This fixes undefined behaviour (left shift of a negative number) reported by gcc's Undefined Behaviour Sanitizer.
* DVB-T2 Frame Mapper
* Verified that `qa_dtv` still passes after this change, and that the undefined behaviour warning is gone.
=> dtv: Use unsigned integer for CRC calculation

gr-iio/lib/device_sink_impl.h, gr-iio/lib/device_source_impl.h
CI build logs show 39 warnings due to missing `override` specifiers in gr-iio. I've fixed those here.
* IIO Device Sink
* IIO Device Source
=> iio: Fix inconsistent override warnings

gr-qtgui/include/gnuradio/qtgui/timeRasterGlobalData.h, gr-qtgui/include/gnuradio/qtgui/waterfallGlobalData.h
CI build logs show 23 warnings due to missing `override` specifiers in gr-qtgui. I've fixed those here.
Various QTGUI blocks.
=> qtgui: Fix inconsistent override warnings

gr-blocks/python/blocks/qa_rotator_cc.py
The test_phase_inc_update_out_of_range test in qa_rotator sometimes fails. For
instance: https://github.com/gnuradio/gnuradio/runs/5772119971?check_suite_focus=true
This is due to a race condition. The test schedules a phase increment for 32,768
samples in the future, waits for some samples to be processed, and then verifies
that the phase increment has not yet occurred. But it can happen (and often does
happen with the system is under load) that more than 32,768 samples will be
processed between these two steps.
To solve the problem, I've added a throttle block to the flow graph, so that it will
take 500 ms for 32,768 samples to be processed. This should be more than enough time
for the test to progress from the while (self.rotator_cc.nitems_written(0) == 0)
step to the …
=> blocks: Fix flaky qa_rotator test (backport to maint-3.10)

gr-dtv/lib/dvbt2/dvbt2_framemapper_cc_impl.cc
(cherry picked from commit dcd794f80223ecfacff8a7229b5e205005f26858)
Backporthttps://github.com/gnuradio/gnuradio/pull/5750
=> dtv: Fix initialization of L1Post struct (backport to maint-3.10)

gnuradio-runtime/lib/controlport/thrift/rpcserver_thrift.cc
(cherry picked from commit 8ccb8e65a8f232dc0b251bc63c562b2e09c49165)
Backport https://github.com/gnuradio/gnuradio/pull/5738
=> runtime: Replace boost::xpressive with std::regex (backport to maint-3.10)

gr-digital/include/gnuradio/digital/crc16_async_bb.h, gr-digital/include/gnuradio/digital/crc32_async_bb.h, gr-digital/include/gnuradio/digital/header_format_crc.h, gr-digital/include/gnuradio/digital/packet_header_default.h, gr-digital/lib/crc16_async_bb_impl.cc, gr-digital/lib/crc16_async_bb_impl.h, gr-digital/lib/crc32_async_bb_impl.cc, gr-digital/lib/crc32_async_bb_impl.h, gr-digital/lib/crc32_bb_impl.cc, gr-digital/lib/crc32_bb_impl.h, gr-digital/lib/header_format_crc.cc, gr-digital/lib/packet_header_default.cc, gr-digital/python/digital/bindings/crc16_async_bb_python.cc, gr-digital/python/digital/bindings/crc32_async_bb_python.cc, gr-digital/python/digital/bindings/header_format_crc_python.cc, gr-digital/python/digital/bindings/packet_header_default_python.cc, gr-digital/python/digital/qa_crc16_async_bb.py, gr-digital/python/digital/qa_crc32_async_bb.py
In #5619 a generic CRC class was added. Existing blocks that use Boost.CRC can switch over to this implementation, thereby eliminating a Boost dependency.
* #5619
* Async CRC16
* Async CRC32
* Stream CRC32
* Packet Header Generator
* Packet Header Parser
There are five places where the CRC implementation was replaced:
1. `crc32_bb`: Here I verified that `qa_crc32_bb.py` fails if I corrupt the CRC parameters.
2. `crc16_async_bb`: This block had no tests. I added a basic test, and verified that it passes before & after my changes.
3. `crc32_async_bb`: This block had no tests. I added a basic test, and verified that it passes before & after my changes.
4. `packet_header_default`: Here I verified that `qa_packet_headerparser_b.py` and `qa_pacrket_headergenerater_bb.py` fail if I corrupt the …
=> digital: Replace boost::crc with built-in CRC implementation

gnuradio-runtime/python/gnuradio/gr/qa_uncaught_exception.py
(cherry picked from commit 7eced84a812fac4b4ed2aea421694f63e9f3c91b)
Backport https://github.com/gnuradio/gnuradio/pull/5746
=> runtime: Fix flaky qa_uncaught_exception test (backport to maint-3.10)

gr-pdu/CMakeLists.txt, gr-pdu/include/gnuradio/pdu/add_system_time.h, gr-pdu/lib/add_system_time_impl.cc, gr-pdu/lib/add_system_time_impl.h, gr-pdu/lib/pdu_to_stream_impl.cc, gr-pdu/lib/tags_to_pdu_impl.cc, gr-pdu/lib/tags_to_pdu_impl.h, gr-pdu/lib/time_delta_impl.cc, gr-pdu/lib/time_delta_impl.h, gr-pdu/python/pdu/bindings/add_system_time_python.cc
(cherry picked from commit 977de6599bdf14be3a620f9859f5d692b2f17559)
Backport https://github.com/gnuradio/gnuradio/pull/5651
=> pdu: Replace Boost with standard C++ (backport to maint-3.10)

gr-qtgui/grc/qtgui_freq_sink_x.block.yml, gr-qtgui/grc/qtgui_sink_x.block.yml, gr-qtgui/grc/qtgui_vector_sink_f.block.yml, gr-qtgui/grc/qtgui_waterfall_sink_x.block.yml
freq_sink_x, sink_x, vector_sink_f .... produce error messages like
File "/usr/local/gnuradio/lib64/python3.10/site-packages/gnuradio/grc/core/blocks/_templates.py", line 77, in render
return template.render(**namespace)
File "/usr/lib/python3.10/site-packages/mako/template.py", line 473, in render
return runtime._render(self, self.callable_, args, data)
File "/usr/lib/python3.10/site-packages/mako/runtime.py", line 878, in _render
_render_context(
File "/usr/lib/python3.10/site-packages/mako/runtime.py", line 920, in _render_context
_exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
File "/usr/lib/python3.10/site-packages/mako/runtime.py", line 947, in _exec_template
callable_(context, *args, **kwargs)
File "memory:0x7f00a04d3a00", line 115, …
=> gr-qtgui: freq_sink and others produce wrong error messages, when GUI Hint is used (backport to maint-3.10)

gr-utils/modtool/templates/gr-newmod/.conda/README.md, gr-utils/modtool/templates/gr-newmod/.conda/conda-forge.yml, gr-utils/modtool/templates/gr-newmod/.conda/recipe/bld.bat, gr-utils/modtool/templates/gr-newmod/.conda/recipe/build.sh, gr-utils/modtool/templates/gr-newmod/.conda/recipe/conda_build_config.yaml, gr-utils/modtool/templates/gr-newmod/.conda/recipe/meta.yaml
This recipe will allow building a conda package for OOT modules with
little or no modification after the template is rendered. Developers can
also use the recipe with conda-smithy to create CI scripts for building
and testing their OOT module.
(cherry picked from commit e3efb76617087e778026086287c6e545f6be2c0f)
Backport https://github.com/gnuradio/gnuradio/pull/5673
=> utils: modtool: Add a conda recipe to the OOT template (backport to maint-3.10)

gr-utils/modtool/templates/gr-newmod/.conda/recipe/meta.yaml
The version for an untagged OOT is based on the date, and previously
this included hour and minute. That's too specific and leads to CI-built
packages from the same run often having different versions. This can
still happen, but stopping at the year, month, and day is much saner. I
don't know what I was thinking previously.
(cherry picked from commit c6d094d79e420c34f7726b893691fdb43eab7360)
Backport https://github.com/gnuradio/gnuradio/pull/5769
=> gr_newmod: Make untagged conda package version less specific (backport to maint-3.10)

gr-digital/grc/digital_crc_append.block.yml, gr-digital/grc/digital_crc_check.block.yml, gr-digital/include/gnuradio/digital/crc_check.h, gr-digital/python/digital/bindings/crc_check_python.cc
Fix typos in GRC blocks and in header files comments.
Signed-off-by: Daniel Estévez <daniel@destevez.net>
(cherry picked from commit c1876785dfd711e2725d685eafd59813e223be81)
Backport https://github.com/gnuradio/gnuradio/pull/5771
=> digital: fix typos CRC Append and Check blocks (backport to maint-3.10)

gr-utils/modtool/templates/gr-newmod/python/howto/bindings/CMakeLists.txt
(cherry picked from commit bebe83801569225a710f10285664e5a3a1bf41ea)
Backport https://github.com/gnuradio/gnuradio/pull/5768
=> gr_newmod: Fix copying python bindings to test dir on Windows (backport to maint-3.10)

gr-soapy/lib/block_impl.cc
It was reported that, with the HackRF module, a flowgraph terminated
with a segfault. Most Soapy modules implement deactivateStream(), but
that function is not called from gr-soapy.
(cherry picked from commit 5fa60c7c10e63192968a7a5daacf6a9fdb9e6d47)
Backport https://github.com/gnuradio/gnuradio/pull/5772
=> gr-soapy: deactivate stream before closing (backport to maint-3.10)

gr-filter/python/filter/qa_filterbank.py
The `qa_filterbank` test occasionally fails, and from the error message it's apparent that on these occasions `outdata2` contains the same values as `outdata`. This suggests that the while loop that waits for the new filter taps to kick in is exiting too soon. I suspect this occurs because it compares complex floating point values for exact equality. I've changed this to check for approximate equality instead.
* Fixes #5831
Tests for the Generic Filterbank block.
I verified that the test still passes after this change.
Unfortunately I have not been able to reproduce the failure locally, so it's difficult to know for certain whether this will correct the flaky test. If no failures occur for a few months, we'll know this was successful.
=> filter: Fix flaky qa_filterbank test

gnuradio-runtime/include/gnuradio/fxpt.h, gnuradio-runtime/python/gnuradio/gr/bindings/fxpt_python.cc
When running QA tests, gcc's Undefined Behaviour Sanitizer reports signed integer overflows in fxpt.h. I've fixed them by explicitly casting the input to an unsigned integer prior to the addition step.
```
/home/argilo/prefix_311/src/gnuradio/gnuradio-runtime/lib/../include/gnuradio/fxpt.h:67:25: runtime error: signed integer overflow: 1074904320 + 1073741824 cannot be represented in type 'int'
/home/argilo/prefix_311/src/gnuradio/gnuradio-runtime/lib/../include/gnuradio/fxpt.h:81:16: runtime error: signed integer overflow: 1074904320 + 1073741824 cannot be represented in type 'int'
```
* Runtime: fixed point `cos` and `sincos` calculations.
Verified that the `math_qa_fxpt`, `math_qa_fxpt_nco`, and `math_qa_fxpt_vco` still pass, but no longer produce undefined behaviour warnings.
=> runtime: Fix signed integer overflows

gr-digital/lib/crc32_bb_impl.cc
gcc's Undefined Behaviour Sanitizer reports load of a misaligned address. Replacing the offending code with a memcmp fixes the issue.
* Stream CRC32
Verified that `qa_crc32_bb_test` still passes, but without the misaligned address warning.
=> digital: Fix load of misaligned address

gr-qtgui/lib/waterfall_sink_c_impl.cc, gr-qtgui/lib/waterfall_sink_f_impl.cc
This fixes a couple unused variable warnings that @drmpeg noticed:
```
/home/ubuntu/xfer/gnuradio/gr-qtgui/lib/waterfall_sink_c_[impl.cc:483](http://impl.cc:483/):21: warning: variable 'i' set but not used [-Wunused-but-set-variable]
for (size_t i = 0; j < d_nrows; i += stride) {
/home/ubuntu/xfer/gnuradio/gr-qtgui/lib/waterfall_sink_f_[impl.cc:485](http://impl.cc:485/):21: warning: variable 'i' set but not used [-Wunused-but-set-variable]
for (size_t i = 0; j < d_nrows; i += stride) {
```
* QT GUI Waterfall Sink
I verified that the Waterfall Sink still works as expected.
=> qtgui: Remove unused variable from Waterfall Sink

gr-dtv/lib/dvbt2/dvbt2_framemapper_cc_impl.cc
In #5804 I accidentally caused a compiler warning:
```
warning: suggest braces around initialization of subobject [-Wmissing-braces]
```
This change fixes the warning while still initializing the polyout array to zero.
* #5804
* DVB-T2 Frame Mapper
I verified that `qa_dtv` still passes and does not produce any valgrind warnings.
=> dtv: Fix compiler warning

gr-digital/lib/crc16_async_bb_impl.cc, gr-digital/lib/crc16_async_bb_impl.h, gr-digital/lib/crc32_async_bb_impl.cc
The Async CRC16 and Async CRC32 blocks can perform misaligned loads, as was the case in #5807.
In addition, the Async CRC16 check fails randomly because it reads four bytes from memory instead of two, causing #5818.
I've fixed both problems by using `memcmp` (with the correct number of bytes) to perform the CRC comparison.
I also removed the unnecessary `crc16_async_bb_impl::process_crc` method to make the implementations of Async CRC16 and CRC32 nearly identical.
* Fixes #5818.
* Async CRC16
* Async CRC32
I verified that the `qa_crc16_async_bb` and `qa_crc32_async_bb` tests still pass with these changes in place.
=> digital: Fix CRC checking in Async CRC16 and Async CRC32 blocks

gr-blocks/grc/blocks_wavfile_sink.block.yml, gr-blocks/include/gnuradio/blocks/wavfile.h, gr-blocks/include/gnuradio/blocks/wavfile_sink.h, gr-blocks/lib/CMakeLists.txt, gr-blocks/lib/wavfile_sink_impl.cc, gr-blocks/python/blocks/bindings/wavfile_python.cc, gr-blocks/python/blocks/bindings/wavfile_sink_python.cc
libsndfile added support for Ogg Opus in version 1.0.29. This pull request makes it accessible through the Wav File Sink block.
* Fixes #3254.
* Wav File Sink
I verified that both Opus and Vorbis output work after this change, and that an exception is raised when Opus is not available.
=> blocks: Add support for Ogg Opus if libsndfile is >= 1.0.29

gnuradio-runtime/include/gnuradio/rpcregisterhelpers.h, gnuradio-runtime/python/gnuradio/gr/bindings/rpcregisterhelpers_python.cc, gr-blocks/lib/qa_rotator.cc, gr-soapy/lib/sink_impl.cc, gr-soapy/lib/source_impl.cc
CI build logs show 63 warnings for unused parameters in `rpcregisterhelpers.h`. Adding `[[maybe_unused]]` should silence the warnings.
I also replaced `__GR_ATTR_UNUSED` with C++17's `[[maybe_unused]]` elsewhere in GNU Radio. I left the macro in place, since removing it would be an API change.
=> runtime: Silence unused parameter warnings

gr-utils/modtool/tools/util_functions.py
When running gr_modtool bind, a crash occurs because get_block_names
tries to open the wrong include directory. It does not take into account
the new structure introduced in #5265. I've fixed that here.
(cherry picked from commit d4f943191dc7780ad102e19f39efb5136e8726e1)
Backport https://github.com/gnuradio/gnuradio/pull/5787
=> modtool: Fix gr_modtool bind (backport to maint-3.10)

cmake/Modules/GrVersion.cmake
This prevents the hash from being misinterpreted as a number, which MSVC
does which will caused failed builds. This is never an issue with GR
itself because the plain hash is only used for the version when the
repository is untagged, but it can happen with OOTs which also use
GrVersion.cmake.
This works by removing the `--always` flag from `git describe` and
handling the no-tag case as a separate special case.
I have been unlucky enough to twice now encounter all-numeric short
hashes when building untagged OOTs with MSVC, so I can't ignore it.
(cherry picked from commit fa8953de2ae67990ccb052af08affac073e106ae)
Backport https://github.com/gnuradio/gnuradio/pull/5770
=> cmake: Always prefix git hash used as version with "g" (backport to maint-3.10)

gnuradio-runtime/python/gnuradio/gr_unittest.py
(cherry picked from commit 0ec72b4eaba56f1a1a72fa8262c8fae1ea412308)
Backport https://github.com/gnuradio/gnuradio/pull/5803
=> qa: remove formatting in assertSequenceEqualGR (backport to maint-3.10)

gnuradio-runtime/include/gnuradio/basic_block.h, gnuradio-runtime/python/gnuradio/gr/bindings/basic_block_python.cc
This avoids a race condition which causes messages to be skipped while
the flow graph finishes execution.
(cherry picked from commit df75146e158c92fd2750af16bbec9848ca6d5b33)
Backport https://github.com/gnuradio/gnuradio/pull/5754
=> runtime: Process system messages before others (backport to maint-3.10)

gr-utils/bindtool/core/generator.py, gr-utils/bindtool/templates/generic_python_cc.mako, gr-utils/bindtool/templates/pydoc_h.mako
Format *_c_pydoc_template.h and *_python.cc using clang-format
to make the generated files clang_format compliant.
It's better to use clang-format than to modify the mako templates.
Using clang-format directly you have nothing to do when changing the formatting
rules but only run the binding process again, but you must not change the mako templates.
As with https://github.com/gnuradio/gnuradio/commit/956f332e410331fde426e1485589d905cdf80fb1
pywidget() was replaced qwidget() generic_python_cc.mako had to be modified, to generate the correct
binding code.
(cherry picked from commit 794a6114a11c28fb4529105fdcd62acd853b733c)
Backport …
=> gr-utils: make the pydoc_h.mako more clang compliant (backport to maint-3.10)

gr-dtv/lib/dvbt2/dvbt2_framemapper_cc_impl.cc
Valgrind reports that poly_pack reads uninitialized memory, leading to
undefined behaviour. This happens because it rounds the length up to
the next multiple of 32 before reading the polynomial coefficients.
Initializing the coefficients to zero solves the problem.
(cherry picked from commit f41f254a31b18295852efff2a92e4fae94d6dd0a)
Backport https://github.com/gnuradio/gnuradio/pull/5804
=> dtv: Fix use of uninitialized memory (backport to maint-3.10)

gr-dtv/lib/dvbt2/dvbt2_framemapper_cc_impl.cc
This fixes undefined behaviour (left shift of a negative number)
reported by gcc's Undefined Behaviour Sanitizer.
(cherry picked from commit 3326c5614c73016d815f4c82a8176bad3468178f)
Backport https://github.com/gnuradio/gnuradio/pull/5805
=> dtv: Use unsigned integer for CRC calculation (backport to maint-3.10)

grc/CMakeLists.txt
(cherry picked from commit e2e7998a216ac6699e624f35aff8be1405035576)
Backport https://github.com/gnuradio/gnuradio/pull/5730
=> grc: look for x-terminal-emulator (backport to maint-3.9)

gr-fec/lib/alist.cc, gr-fec/lib/conv_bit_corr_bb_impl.cc, gr-fec/lib/fec_mtrx_impl.cc, gr-trellis/lib/interleaver.cc, gr-video-sdl/lib/sink_s_impl.cc, gr-video-sdl/lib/sink_uc_impl.cc
In the case of an error, the library should instead return an
appropriate error code to the calling program which can then determine
how to handle the error, including performing any required
clean-up. In C++ the error can be thrown.
(cherry picked from commit 15a38a474ed2e1f9b0f59fadd93e253fec5cd5f9)
Backport https://github.com/gnuradio/gnuradio/pull/5731
=> fec/trellis/video-sdl: shared library throw not exit (backport to maint-3.9)

gnuradio-runtime/python/gnuradio/ctrlport/gr-perf-monitorx
The gr-perf-monitorx tool currently fails with the following error:
gr-perf-monitorx: lost connection (draw_networkx_nodes() got an
unexpected keyword argument 'arrows').
The tool runs correctly once the incorrect keyword argument is removed.
(cherry picked from commit 16e2221503f7fa2d20cf93e32283be6fb00d7a9d)
Backport https://github.com/gnuradio/gnuradio/pull/5737
=> runtime: Remove invalid keyword argument from draw_networkx_nodes (backport to maint-3.9)

gr-blocks/lib/CMakeLists.txt, gr-blocks/lib/probe_signal_impl.h, gr-blocks/lib/probe_signal_v_impl.cc, gr-blocks/lib/probe_signal_v_impl.h, gr-blocks/python/blocks/qa_probe_signal.py
(cherry picked from commit 775efb182ef3d273c2490e6d208119e3fdef33f8)
Backport https://github.com/gnuradio/gnuradio/pull/5744
=> blocks: Synchronize access to d_level to prevent race conditions (backport to maint-3.9)

gr-filter/python/filter/qa_freq_xlating_fft_filter.py
(cherry picked from commit 2046bce50bb0f45c008718e2c8f8ec493a6e0b6b)
Backport https://github.com/gnuradio/gnuradio/pull/5745
=> filter: Fix flaky freq xlating filter test (backport to maint-3.9)

grc/gui/Application.py
Signed-off-by: Bjoern Kerler <info@revskills.de>
(cherry picked from commit b89baa29b0fe63cb8691575f9784628bea4a4aec)
Backport https://github.com/gnuradio/gnuradio/pull/5702
=> grc: Fix create hier / missing top_block error (backport to maint-3.9)

gr-uhd/lib/usrp_block_impl.cc
Fixes https://github.com/gnuradio/gnuradio/issues/5681
Bug was introduced in https://github.com/gnuradio/gnuradio/commit/9cdfe5141a7aad1cf9c4c81167761cc291913fb0
Signed-off-by: Philipp Niedermayer <eltos@outlook.de>
(cherry picked from commit c6586f9af80e79c33ec9f4affdf239415151aeae)
Backport https://github.com/gnuradio/gnuradio/pull/5682
=> gr-uhd: Fix NotImplemented Error (backport to maint-3.9)

gr-blocks/python/blocks/qa_rotator_cc.py
The test_phase_inc_update_out_of_range test in qa_rotator sometimes fails. For
instance: https://github.com/gnuradio/gnuradio/runs/5772119971?check_suite_focus=true
This is due to a race condition. The test schedules a phase increment for 32,768
samples in the future, waits for some samples to be processed, and then verifies
that the phase increment has not yet occurred. But it can happen (and often does
happen with the system is under load) that more than 32,768 samples will be
processed between these two steps.
To solve the problem, I've added a throttle block to the flow graph, so that it will
take 500 ms for 32,768 samples to be processed. This should be more than enough time
for the test to progress from the while (self.rotator_cc.nitems_written(0) == 0)
step to the …
=> blocks: Fix flaky qa_rotator test (backport to maint-3.9)

gr-dtv/lib/dvbt2/dvbt2_framemapper_cc_impl.cc
(cherry picked from commit dcd794f80223ecfacff8a7229b5e205005f26858)
Backport https://github.com/gnuradio/gnuradio/pull/5750
=> dtv: Fix initialization of L1Post struct (backport to maint-3.9)

gnuradio-runtime/python/gnuradio/gr/qa_uncaught_exception.py
(cherry picked from commit 7eced84a812fac4b4ed2aea421694f63e9f3c91b)
Backport https://github.com/gnuradio/gnuradio/pull/5746
=> runtime: Fix flaky qa_uncaught_exception test (backport to maint-3.9)

gr-qtgui/grc/qtgui_freq_sink_x.block.yml, gr-qtgui/grc/qtgui_sink_x.block.yml, gr-qtgui/grc/qtgui_vector_sink_f.block.yml, gr-qtgui/grc/qtgui_waterfall_sink_x.block.yml
freq_sink_x, sink_x, vector_sink_f .... produce error messages like
File "/usr/local/gnuradio/lib64/python3.10/site-packages/gnuradio/grc/core/blocks/_templates.py", line 77, in render
return template.render(**namespace)
File "/usr/lib/python3.10/site-packages/mako/template.py", line 473, in render
return runtime._render(self, self.callable_, args, data)
File "/usr/lib/python3.10/site-packages/mako/runtime.py", line 878, in _render
_render_context(
File "/usr/lib/python3.10/site-packages/mako/runtime.py", line 920, in _render_context
_exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
File "/usr/lib/python3.10/site-packages/mako/runtime.py", line 947, in _exec_template
callable_(context, *args, **kwargs)
File "memory:0x7f00a04d3a00", line 115, …
=> gr-qtgui: freq_sink and others produce wrong error messages, when GUI Hint is used (backport to maint-3.9)

gnuradio-runtime/lib/block.cc
If Minoutbuf is set to a value other than 0 in the "Advanced" tab of a block, then the following logging error occurs:
```
[*** LOG ERROR #0001 ***] [2022-05-18 16:38:00] [source] {invalid type specifier}
```
This happens because `unique_id()` is an integer, but `{:s}` was incorrectly specified in the format string.
This bug was introduced in #5599.
Any block that uses a non-default minimum output buffer size.
After changing the format specifier to `{:d}`, all is well:
```
source :info: set_min_output_buffer on block source(1) to 1024
```
=> runtime: Fix broken log format string in set_min_output_buffer

gnuradio-runtime/include/gnuradio/rpcbufferedget.h
rpcbufferedget uses Boost mutexes & condition variables in a few places. Those can easily be replaced with their standard C++ equivalents.
rpcbufferedget, which is used by ControlPort probes.
None yet.
=> runtime: Replace Boost with standard C++ in rpcbufferedget

gnuradio-runtime/include/gnuradio/thread/thread_group.h, gnuradio-runtime/lib/thread/thread_group.cc
`boost::function0` is used in one place in gnuradio-runtime; I've replaced it with `std::function` here.
Thread groups, which are used by the thread-per-block scheduler.
I verified that flow graphs still execute after this change.
=> runtime: Replace boost::function0 with std::function

gnuradio-runtime/include/gnuradio/rpcpmtconverters_thrift.h, gnuradio-runtime/include/gnuradio/rpcserver_thrift.h, gnuradio-runtime/include/gnuradio/thrift_application_base.h, gnuradio-runtime/lib/controlport/thrift/rpcpmtconverters_thrift.cc, gnuradio-runtime/lib/controlport/thrift/rpcserver_thrift.cc
Here I've replaced almost all of the Boost used by ControlPort's Thrift middleware and replaced it with standard C++. The only thing I didn't touch was one instance of `boost::asio::ip::host_name()`; I don't know how to do that in a cross-platform way, so I left it for now.
ControlPort
I built GNU Radio with ControlPort and Performance Counters enabled, edited `gnuradio-runtime.conf` to enable both, ran a flow graph, and ran `gr-perf-monitorx` to make sure it's still possible to monitor performance using ControlPort.
=> runtime: Replace Boost with standard C++ in Apache Thrift code

gr-digital/include/gnuradio/digital/crc16_async_bb.h, gr-digital/include/gnuradio/digital/crc32_async_bb.h, gr-digital/include/gnuradio/digital/header_format_crc.h, gr-digital/include/gnuradio/digital/packet_header_default.h, gr-digital/lib/crc16_async_bb_impl.cc, gr-digital/lib/crc16_async_bb_impl.h, gr-digital/lib/crc32_async_bb_impl.cc, gr-digital/lib/crc32_async_bb_impl.h, gr-digital/lib/crc32_bb_impl.cc, gr-digital/lib/crc32_bb_impl.h, gr-digital/lib/header_format_crc.cc, gr-digital/lib/packet_header_default.cc, gr-digital/python/digital/bindings/crc16_async_bb_python.cc, gr-digital/python/digital/bindings/crc32_async_bb_python.cc, gr-digital/python/digital/bindings/header_format_crc_python.cc, gr-digital/python/digital/bindings/packet_header_default_python.cc, gr-digital/python/digital/qa_crc16_async_bb.py, gr-digital/python/digital/qa_crc32_async_bb.py
(cherry picked from commit 3e49226732c9f2c5e2737b122d4385989a0360ee)
Backport https://github.com/gnuradio/gnuradio/pull/5700
=> digital: Replace boost::crc with built-in CRC implementation (backport to maint-3.10)

gnuradio-runtime/include/gnuradio/fxpt.h, gnuradio-runtime/python/gnuradio/gr/bindings/fxpt_python.cc
When running QA tests, gcc's Undefined Behaviour Sanitizer reports
signed integer overflows in fxpt.h. I've fixed them by explicitly
casting the input to an unsigned integer prior to the addition step.
(cherry picked from commit eebf0778cf6d1c4957f43a1548919c999fad6998)
Backport https://github.com/gnuradio/gnuradio/pull/5806
=> runtime: Fix signed integer overflows (backport to maint-3.10)

gr-digital/lib/crc32_bb_impl.cc
gcc's Undefined Behaviour Sanitizer reports load of a misaligned
address. Replacing the offending code with a memcmp fixes the issue.
(cherry picked from commit a20f0dd4b5587aeafbf907087d5d0afd04513d9b)
Backport https://github.com/gnuradio/gnuradio/pull/5807
=> digital: Fix load of misaligned address (backport to maint-3.10)

gr-dtv/lib/dvbt2/dvbt2_framemapper_cc_impl.cc
In #5804 I accidentally caused a compiler warning:
warning: suggest braces around initialization of subobject [-Wmissing-braces]
This change fixes the warning while still initializing the polyout
array to zero.
(cherry picked from commit 28c4b2b09abea94bca1ffedb6a4d9ecf254b7193)
Backport https://github.com/gnuradio/gnuradio/pull/5816
=> dtv: Fix compiler warning (backport to maint-3.10)

gr-qtgui/lib/waterfall_sink_c_impl.cc, gr-qtgui/lib/waterfall_sink_f_impl.cc
(cherry picked from commit 1eeff3df12006a7c90f18cd2542ab9c8fa60088d)
Backport https://github.com/gnuradio/gnuradio/pull/5828
=> qtgui: Remove unused variable from Waterfall Sink (backport to maint-3.10)

gr-blocks/grc/blocks_wavfile_sink.block.yml, gr-blocks/include/gnuradio/blocks/wavfile.h, gr-blocks/include/gnuradio/blocks/wavfile_sink.h, gr-blocks/lib/CMakeLists.txt, gr-blocks/lib/wavfile_sink_impl.cc, gr-blocks/python/blocks/bindings/wavfile_python.cc, gr-blocks/python/blocks/bindings/wavfile_sink_python.cc
(cherry picked from commit eaeb3789401137fa3d7f3a30fdf782f07b331cb1)
Backport https://github.com/gnuradio/gnuradio/pull/5829
=> blocks: Add support for Ogg Opus if libsndfile is >= 1.0.29 (backport to maint-3.10)

gr-filter/python/filter/qa_filterbank.py
The qa_filterbank test occasionally fails, and from the error message
it's apparent that on these occasions outdata2 contains the same values
as outdata. This suggests that the while loop that waits for the new
filter taps to kick in is exiting too soon. I suspect this occurs
because it compares floating point values for exact equality. I've
changed this to check for approximate equality instead.
(cherry picked from commit 390fe9fb82891d1c3a7976a570440b0c3970a9a7)
Backport https://github.com/gnuradio/gnuradio/pull/5833
=> filter: Fix flaky qa_filterbank test (backport to maint-3.10)

gnuradio-runtime/include/gnuradio/basic_block.h, gnuradio-runtime/python/gnuradio/gr/bindings/basic_block_python.cc
This avoids a race condition which causes messages to be skipped while
the flow graph finishes execution.
(cherry picked from commit df75146e158c92fd2750af16bbec9848ca6d5b33)
Backport https://github.com/gnuradio/gnuradio/pull/5754
=> runtime: Process system messages before others (backport to maint-3.9)

.github/workflows/make-test.yml, cmake/Modules/GrPython.cmake
CI: Add Fedora 36, remove Fedora 34.
In addition, Fedora 36 and Ubuntu 22.04 have changed the Python install
scheme to put modules under <prefix>/local. Our default install location
of /usr/local results in files being install under /usr/local/local. The
change to GrPython.cmake puts default installs back in /usr/local.
(Suggested by dl1ksv).
CI.
=> CI: Add Fedora 36, remove Fedora 34, second try

gnuradio-runtime/include/gnuradio/thread/thread_group.h, gnuradio-runtime/lib/thread/thread_group.cc
This is a continuation of the Boost removal work. `boost::shared_mutex` can be replaced with the `std` equivalent, which is available starting in C++17.
* Thread-per-block scheduler
I verified that Gqrx still works correctly with these changes in place.
=> runtime: Replace boost::shared_mutex with standard C++

gnuradio-runtime/include/pmt/pmt_pool.h, gnuradio-runtime/lib/pmt/pmt.cc
PMT uses Boost mutexes & condition variables in a few places. Those can easily be replaced with their standard C++ equivalents.
Polymorphic Types
None yet.
=> runtime: Replace PMT's Boost mutexes with standard C++

gnuradio-runtime/include/gnuradio/high_res_timer.h, gnuradio-runtime/python/gnuradio/gr/bindings/high_res_timer_python.cc
GNU Radio's high resolution timer uses `boost::posix_time` in a few places. I've replaced those with `std::chrono`.
* Performance counters
* QT GUI sinks
To force the generic timer implementation to be used, I commented out the lines that check for the various platforms (`#if defined(linux)` etc.) to force `GNURADIO_HRT_USE_GENERIC_CLOCK` to be defined.
I checked the behaviour of the high resolution timer using the following Python code:
```
from gnuradio import gr
gr.high_res_timer_now()
gr.high_res_timer_now_perfmon()
gr.high_res_timer_tps()
gr.high_res_timer_epoch()
```
Also, I built GNU Radio with ControlPort and performance counters enabled (`-DENABLE_CTRLPORT_THRIFT=ON -DENABLE_PERFORMANCE_COUNTERS=ON`) and verified that I could still monitor the performance of a running flow graph …
=> runtime: Replace Boost with standard C++ in high resolution timer

.github/workflows/make-test.yml, cmake/Modules/GrPython.cmake
In addition, Fedora 36 and Ubuntu 22.04 have changed the Python install
scheme to put modules under <prefix>/local. Our default install location
of /usr/local results in files being install under /usr/local/local. The
change to GrPython.cmake puts default installs back in /usr/local.
(Suggested by dl1ksv).
(cherry picked from commit 6ff02a5289770ae1da7c5f7b243d0708331b8695)
Backport https://github.com/gnuradio/gnuradio/pull/5905
=> CI: Add Fedora 36, remove Fedora 34 (backport to maint-3.10)

.github/workflows/make-test.yml
Backport https://github.com/gnuradio/gnuradio/pull/5905, minus cmake changes.
=> CI: Add Fedora 36, remove Fedora 34

gnuradio-runtime/lib/hier_block2_detail.cc, gnuradio-runtime/lib/vmcircbuf.cc, gnuradio-runtime/python/gnuradio/gr/bindings/logger_python.cc, gr-blocks/lib/file_descriptor_sink_impl.cc, gr-blocks/lib/tagged_file_sink_impl.cc, gr-digital/lib/fll_band_edge_cc_impl.cc, gr-filter/lib/pm_remez.cc, gr-network/lib/socket_pdu_impl.cc, gr-uhd/lib/rfnoc_rx_streamer_impl.cc
In a few instances, the format string does not match the types of the arguments. In other cases, the format string is not constant. I fixed both problems here, and verified that C++20 type checking is happy with the updated format strings.
* Hierarchical blocks
* Circular buffers
* Python bindings to the logger
* File Descriptor Sink
* Tagged File Sink
* FLL Band-Edge
* Parks-McClellan FIR filter design using Remez algorithm
* Socket PDU
* RFNoC Rx Streamer
* Verified that compilation succeeds with C++20 fmt type checking.
* Tested Python logging methods (e.g. `gr.logger("foo").info("bar { baz")`)
=> Fix various broken fmt strings

gr-blocks/python/blocks/qa_type_conversions.py
than INT_MAX to INT_MAX.
This adds a test case for float_to_int clipping an input value greater than MAX_INT. It is a regression test for a bug in volk_32f_s32f_convert_32i for which the current work-around is to not use that VOLK kernel.
=> Add a test case for float_to_int clipping input values slightly greater

gnuradio-runtime/lib/CMakeLists.txt
gnuradio-runtime no longer depends on Boost::system or Boost::regex, so it should be safe to remove these from target_link_libraries.
* gnuradio-runtime cmake build
I verified that GNU Radio still builds correctly on Ubuntu 22.04, the test suite passes, and Gqrx runs normally.
=> runtime: Remove Boost::system and Boost::regex dependencies

gr-analog/grc/analog_fastnoise_source_x.block.yml, gr-filter/grc/filter_fir_filter_xxx.block.yml, gr-filter/grc/variable_band_pass_filter_taps.block.yml, gr-filter/grc/variable_band_reject_filter_taps.block.yml, gr-filter/grc/variable_high_pass_filter_taps.block.yml, gr-filter/grc/variable_low_pass_filter_taps.block.yml, gr-filter/grc/variable_rrc_filter_taps.block.yml, gr-qtgui/grc/qtgui_freq_sink_x.block.yml
Fix cpp_templates in some filter_tap blocks and other blocks used  in the [filter taps example](https://github.com/gnuradio/gnuradio/blob/main/gr-filter/examples/filter_taps.grc)
Set cpp flag in low/high_pass_filter_taps block
Replace firdes. by filter::firdes:: in all *_filter_taps blocks
Switch to correct include file in filter_fir_filter_xxx block
Enabling enable_legend and setting spectrum width in qtgui_freq_sink_x block
To test use the [filter tap example](https://github.com/gnuradio/gnuradio/blob/main/gr-filter/examples/filter_taps.grc)
Set the output language to C++
Disable the len_taps block. This block is not needed for the flowgraph and prevents generating c++ code
Compare the output of the python and c++ generated flowgraph
=> c++ generation: Fix some template errors

gnuradio-runtime/include/gnuradio/buffer_type.h, gnuradio-runtime/python/gnuradio/gr/bindings/buffer_type_python.cc, gr-analog/lib/noise_source_impl.cc, gr-analog/lib/noise_source_impl.h
C++20 is stricter about template syntax, and does not allow redundant template parameter lists in constructors and destructors. I've fixed the two instances that occur in GNU Radio, and verified that compiling in C++20 mode succeeds.
* `buffer_type` class, used in buffer implementations
* Noise Source
I verified that flow graphs still execute, and that the Noise Source block still works.
=> Fix constructor & destructor template syntax

gr-blocks/grc/blocks_file_sink.block.yml, gr-qtgui/grc/qtgui_freq_sink_x.block.yml, gr-qtgui/grc/qtgui_waterfall_sink_x.block.yml
In some yaml files the cpp templates build wrong strings. They use 'value' instead of "value"
This is fixed here for three files.
=> cpp templates in yaml files: Fix some template errors

gr-blocks/lib/rotator_cc_impl.cc, gr-blocks/python/blocks/qa_rotator_cc.py
This PR fixes a bug on the `rotator_cc` handling of phase increment updates via control message (message port). The rotator block has an optional message port for controlling its operating phase increment (or angular frequency), which I added back in #2984, and which I use in the [`gr-dvbs2rx` project](https://github.com/igorauad/gr-dvbs2rx), see, e.g.,  [dvbs2-rx#L797](https://github.com/igorauad/gr-dvbs2rx/blob/master/apps/dvbs2-rx#L797). However, the implementation has a bug when multiple updates are scheduled for close sample indexes processed in the same work call.
The main fix is on this line:
```diff
-            d_r.rotateN(out, in, items_before_update);
+            d_r.rotateN(
+                out + nprocessed_items, in + nprocessed_items, items_before_update);
```
The previous …
=> blocks: Fix rotator_cc scheduled phase inc updates

gnuradio-runtime/lib/block.cc
(cherry picked from commit ef3ea5cd0121e850d4f81e1b2d05e779928e5eb7)
Backport https://github.com/gnuradio/gnuradio/pull/5858
=> runtime: Fix broken log format string in set_min_output_buffer (backport to maint-3.10)

gr-utils/modtool/templates/gr-newmod/python/bindings/CMakeLists.txt
(cherry picked from commit bebe83801569225a710f10285664e5a3a1bf41ea)
Backport https://github.com/gnuradio/gnuradio/pull/5768.
Note that it's `test_modules/gnuradio/howto` in 3.10, but `test_modules/howto` in 3.9.
=> gr_newmod: Fix copying python bindings to test dir on Windows (backport to maint-3.9)

gr-dtv/lib/dvbt2/dvbt2_framemapper_cc_impl.cc
This fixes undefined behaviour (left shift of a negative number)
reported by gcc's Undefined Behaviour Sanitizer.
(cherry picked from commit 3326c5614c73016d815f4c82a8176bad3468178f)
Backport https://github.com/gnuradio/gnuradio/pull/5805
=> dtv: Use unsigned integer for CRC calculation (backport to maint-3.9)

gnuradio-runtime/include/gnuradio/fxpt.h, gnuradio-runtime/python/gnuradio/gr/bindings/fxpt_python.cc
When running QA tests, gcc's Undefined Behaviour Sanitizer reports
signed integer overflows in fxpt.h. I've fixed them by explicitly
casting the input to an unsigned integer prior to the addition step.
(cherry picked from commit eebf0778cf6d1c4957f43a1548919c999fad6998)
Backport https://github.com/gnuradio/gnuradio/pull/5806
=> runtime: Fix signed integer overflows (backport to maint-3.9)

gr-digital/lib/crc32_bb_impl.cc
gcc's Undefined Behaviour Sanitizer reports load of a misaligned
address. Replacing the offending code with a memcmp fixes the issue.
(cherry picked from commit a20f0dd4b5587aeafbf907087d5d0afd04513d9b)
Backport https://github.com/gnuradio/gnuradio/pull/5807
=> digital: Fix load of misaligned address (backport to maint-3.9)

gr-digital/lib/crc16_async_bb_impl.cc, gr-digital/lib/crc32_async_bb_impl.cc
Original-author: Clayton Smith <argilo@gmail.com>
Partial backport of #5830
=> digital: Fix CRC checking in Async CRC16 and Async CRC32 blocks (backport to maint-3.9)

gr-soapy/grc/soapy_hackrf_sink.block.yml, gr-soapy/grc/soapy_hackrf_source.block.yml
Before:
After:
* Soapy HackRF Source
* Soapy HackRF Sink
I verified that the labels appear correctly, and the blocks still work as before.
=> soapy: Fix typos in HackRF VGA Gain labels

gnuradio-runtime/python/gnuradio/ctrlport/gr-perf-monitorx
Backport https://github.com/gnuradio/gnuradio/pull/5849
=> Import PyQt5 before matplotlib, and only catch Thrift transport exceptions (backport to maint-3.10)

gnuradio-runtime/lib/hier_block2_detail.cc, gnuradio-runtime/lib/vmcircbuf.cc, gnuradio-runtime/python/gnuradio/gr/bindings/logger_python.cc, gr-blocks/lib/file_descriptor_sink_impl.cc, gr-blocks/lib/tagged_file_sink_impl.cc, gr-digital/lib/fll_band_edge_cc_impl.cc, gr-filter/lib/pm_remez.cc, gr-network/lib/socket_pdu_impl.cc, gr-uhd/lib/rfnoc_rx_streamer_impl.cc
In a few instances, the format string does not match the types of the
arguments. In other cases, the format string is not constant. I fixed
both problems here, and verified that C++20 type checking is happy
with the updated format strings.
(cherry picked from commit bed4dba514bb9dbd48defbb744debb77c6710202)
Backport https://github.com/gnuradio/gnuradio/pull/5859
=> Fix various broken fmt strings (backport to maint-3.10)

gnuradio-runtime/include/gnuradio/buffer_type.h, gnuradio-runtime/python/gnuradio/gr/bindings/buffer_type_python.cc, gr-analog/lib/noise_source_impl.cc, gr-analog/lib/noise_source_impl.h
C++20 is stricter about template syntax, and does not allow redundant
template parameter lists in constructors and destructors. I've fixed
the two instances that occur in GNU Radio, and verified that compiling
in C++20 mode succeeds.
(cherry picked from commit 89a07f0085e0553d2d8f3439551b18e1f3fb10d0)
Backport https://github.com/gnuradio/gnuradio/pull/5862
=> Fix constructor & destructor template syntax (backport to maint-3.10)

gr-blocks/lib/rotator_cc_impl.cc, gr-blocks/python/blocks/qa_rotator_cc.py
The previous implementation was applying the rotation to the wrong
indexes when multiple scheduled phase increment updates were processed
in the same work call. This patch fixes the input/output buffer indexes
on the `rotateN()` call and covers the multi-update scenario on QA. The
previous QA implementation was not covering this bug because the
multi-update test case was only checking the tags produced on each phase
increment update and not whether the actual IQ output was correct.
(cherry picked from commit c1d882f49ab54666f5e232bbef670d729587a84b)
Backport https://github.com/gnuradio/gnuradio/pull/5887
=> blocks: Fix rotator_cc scheduled phase inc updates (backport to maint-3.10)

gr-analog/grc/analog_fastnoise_source_x.block.yml, gr-filter/grc/filter_fir_filter_xxx.block.yml, gr-filter/grc/variable_band_pass_filter_taps.block.yml, gr-filter/grc/variable_band_reject_filter_taps.block.yml, gr-filter/grc/variable_high_pass_filter_taps.block.yml, gr-filter/grc/variable_low_pass_filter_taps.block.yml, gr-filter/grc/variable_rrc_filter_taps.block.yml, gr-qtgui/grc/qtgui_freq_sink_x.block.yml
Set cpp flag in low/high_pass_filter_taps block
Replase firdes. by filter::firdes:: in all *_filter_taps blocks
Switch to correct include file in filter_fir_filter_xxx block
Enabling enable_legend and setting spectrum width in qtgui_freq_sink_x block
Testing with gr-filter/examples/filter_taps.grc
(cherry picked from commit 740cc6b04f6e9d9618fd067820858f29e167a268)
Backport https://github.com/gnuradio/gnuradio/pull/5889
=> c++ generation: Fix some template errors (backport to maint-3.10)

grc/core/params/param.py
* grc: Add parentheses on arithmetic expressions
If a variable consists of an aritmetic expression an is used in another
expression the expression should be put in parentheses
* Extend operator checking to * /
(cherry picked from commit 9a478c44cd66134b3a52e29be4fae7cd7828f917)
Backport https://github.com/gnuradio/gnuradio/pull/5856
=> grc: Add parentheses on arithmetic expressions (backport to maint-3.10)

gr-soapy/grc/soapy_hackrf_sink.block.yml, gr-soapy/grc/soapy_hackrf_source.block.yml
(cherry picked from commit 424df10acc063a7647bc5c67a3273c456154363d)
Backport https://github.com/gnuradio/gnuradio/pull/5918
=> soapy: Fix typos in HackRF VGA Gain labels (backport to maint-3.10)

gnuradio-runtime/python/gnuradio/ctrlport/gr-perf-monitorx
Backport https://github.com/gnuradio/gnuradio/pull/5849
=> Import PyQt5 before matplotlib, and only catch Thrift transport exceptions (backport to maint-3.9)

gr-blocks/lib/rotator_cc_impl.cc, gr-blocks/python/blocks/qa_rotator_cc.py
The previous implementation was applying the rotation to the wrong
indexes when multiple scheduled phase increment updates were processed
in the same work call. This patch fixes the input/output buffer indexes
on the `rotateN()` call and covers the multi-update scenario on QA. The
previous QA implementation was not covering this bug because the
multi-update test case was only checking the tags produced on each phase
increment update and not whether the actual IQ output was correct.
(cherry picked from commit c1d882f49ab54666f5e232bbef670d729587a84b)
Backport https://github.com/gnuradio/gnuradio/pull/5887
=> blocks: Fix rotator_cc scheduled phase inc updates (backport to maint-3.9)

gr-wavelet/lib/CMakeLists.txt
The gr-wavelet module has gnuradio-blocks in its `target_link_libraries` even though it doesn't use this module. Removing it will prevent extraneous libraries from being linked.
CMake build for the gr-wavelet module.
Using ldd, I verified that libgnuradio-pdu.so is no longer linked to extraneous libraries such as libFLAC and libvorbis. I also verified that the test suite still passes, and that Gqrx runs normally.
=> wavelet: Remove unused dependency

gr-pdu/lib/CMakeLists.txt
The gr-pdu module has gnuradio-blocks and gnuradio-filter in its `target_link_libraries` even though it doesn't use these modules. Removing them will prevent extraneous libraries from being linked.
CMake build for the gr-pdu module.
Using ldd, I verified that libgnuradio-pdu.so is no longer linked to extraneous libraries such as libFLAC and libvorbis. I also verified that the test suite still passes, and that Gqrx runs normally.
=> pdu: Remove unused dependencies

gr-pdu/lib/CMakeLists.txt
It appears this workaround was copied from the gr-wavelet module, but it's not needed here because gr-pdu doesn't depend on GSL. Removing it reduces the number of libraries that gr-pdu links to.
* gr-pdu cmake build
None. If CI is happy, this should be good.
=> pdu: Remove --no-as-needed linker option

.github/workflows/make-test.yml
New feature in GCC12, helping find reliance on coincidental initialization
---
The hopes here are that we'll find places were we accidentally rely on memory being initialized to 0.
Build-wide
None, if all unit tests continue to work, we feel happy.
=> CI: make F36 builder (gcc12) use 0xFE as memory init pattern

grc/gui/Utils.py
Since cairo.ImageSurface is pixel-based, it only accepts integer dimensions.
No need to round up – proper rounding and padding make this quite safe.
Sometimes, taking a PNG screenshot fails. This fixes it.
Closes #5995
GRC
Tested doing some screenshots that triggered the behaviour in #5995.
=> GRC/Screenshots: create ImageSurface with int dimensions

gnuradio-runtime/python/gnuradio/gr/bindings/thrift_application_base_python.cc, gr-iio/python/iio/bindings/fmcomms5_sink_python.cc, gr-iio/python/iio/bindings/fmcomms5_source_python.cc
- runtime/thrift: update binding headers
- iio/fmcomms2_{sink,source}: update binding headers
Closes #5992
- runtime/ctrlport/thrift
- iio/fmcomms5{sink,source}
n/a, but signed
=> Fix Pybind hashes in Thrift bindings, fmcomms5

grc/core/params/dtypes.py, grc/core/params/param.py
Wrong values in the GUI HINT field are correctly handled in the gui
but lead to useless error messages in the terminal window
For instance take a QT GUI SINK and enter 
0,0,0,1 
in the GUI HINT field. Then you get an error message like
Param - GUI Hint(gui_hint):
Invalid GUI Hint entered: (0, 0, 0, 1) (positive row/column span required).
and in the terminal window 
File "/usr/local/gnuradio/lib64/python3.10/site-packages/gnuradio/grc/core/blocks/_templates.py", line 77, in render
return template.render(**namespace)
File "/usr/lib/python3.10/site-packages/mako/template.py", line 473, in render
return runtime._render(self, self.callable_, args, data)
File "/usr/lib/python3.10/site-packages/mako/runtime.py", line 878, in _render
_render_context(
File …
=> gr-qtgui: gui_hint avoid useless error messages

meson.build
fmt and spdlog provide pkg-config files, and these work and compile perfectly fine. Meson can try finding with both pkg-config and cmake, if it is allowed to, which means that dependency lookup now works on systems where cmake is not installed.
Note this is not immediately useful, since later on a cmake subproject is explicitly used, but that can be fixed in the future to make cmake no longer required for a successful full configure.
Even when using cmake for dependency lookup, the modules kwarg is not needed. Both dependencies export a single cmake target, so Meson can figure out the correct one to use without trouble.
=> meson: do not require cmake when finding dependencies

meson.build, subprojects/.gitignore, subprojects/CLI11.wrap, subprojects/cli11.wrap, subprojects/json.wrap, subprojects/nlohmann_json.wrap
Updates suggested by @eli-schwartz in #6012 to use the already supported wrap files for cli11 and nlohmann_json as found with `meson wrap install ...`
meson build files
=> 4.0: meson: use supported wrap files cli11/nlohmann_json

gr-digital/lib/header_payload_demux_impl.cc
The warning message text for negative payload lengths was the same as
the message for too large payload lengths, and was incorrect.
Rewrites the warning message in the case the payload length is negative.
None AFAIK
Digital, header/payload demux block.
None
=> digital: fix warning message in header/payload demux

gr-analog/include/gnuradio/analog/noise_source.h, gr-analog/lib/fastnoise_source_impl.cc, gr-analog/lib/noise_source_impl.cc, gr-analog/lib/noise_source_impl.h, gr-analog/python/analog/bindings/fastnoise_source_python.cc, gr-analog/python/analog/bindings/noise_source_python.cc, gr-analog/python/analog/qa_fastnoise.py, gr-analog/python/analog/qa_noise.py, gr-trellis/python/trellis/qa_trellis.py
Type of `seed` in noise_source was inconsistent with fastnoise_source
and with the random number generator classes. This makes everything
consistent.
Signed-off-by: Brett Gottula <bgottula@gmail.com>
---
title: ''
labels: ''
assignees: ''
---
Type of `seed` in noise_source was inconsistent with fastnoise_source
and with the random number generator classes. This makes everything
consistent.
Addresses part of #5959
analog/noise_source
None, but willing to if the automated test coverage is not sufficient.
=> analog: Change noise_source seed type to uint64_t

gr-iio/lib/fmcomms2_sink_impl.cc
Fix scalar value in fmcomms2 sink to match the IIO format le:S16/16>>0
TX output power is aprox 25 dB lower (for the given example) when using ADALM Pluto with gnuradio 3.10 (compared to 3.8 results).
There is an error when converting data from float to int.
The data is scaled to 12 bits instead of 12 bits left shifted by 4 (16 bits where the 4 LSBs don't matter).
This caused the shifting of 4 most significant bits to the right, essentially losing 4 MSBs where most of the power is (about 90% power).
Reported and tested here: https://ez.analog.com/adieducation/university-program/f/q-a/560641/pluto-grc-3-10-sink-block-has-low-output-power .
The fmcomms2 sink, part of the gr-iio module.
Testing reported in the issue mentioned above.
=> iio: Fix sink scalar value to match format le:S16/16.

cmake/Modules/GrPython.cmake
In 6ff02a5289, we changed the method of determining the installation
directory to work with Fedora 36 and Ubuntu 22.04. For custom prefixes,
this did not end up working on Ubuntu 22.04.
#5905 (previous PR, which was not sufficient)
cmake
=> GrPython.cmake: update method for determining installation directory

gr-qtgui/grc/qtgui_range.block.yml, gr-qtgui/python/qtgui/__init__.py, gr-qtgui/python/qtgui/range.py.cmakein
Previously, the Qt range widget did not support output ports -- contrary to several other Qt widgets (such as the dial control), which does.
This PR brings the widget types into conformance and lets messages be used to convey data entered by the user.
None filed.
The Qt range block is modified. In theory, performance impact should be minimal.
Instantiated a flowgraph with a range block, with another GUI widget following its output via variable updates, and a message sink block following outputs over the message port. Validated that both consumers retrieve updates, thus that the traditional callback mechanism was not impacted. Modified the message name, and checked that the value passed to the message debug sink was updated accordingly.
Also directly invoked `python -m …
=> qtgui: Add output message ports to range widgets

gr-utils/modtool/tools/parser_cc_block.py
Previously, parsing signatures would fail if the io_signature call was
not prefixed with gr::, which is not necessary if currently in the gr
namespace anyway. This error may be encountered when copying gnuradio
source files into a new module, which don't use the gr:: prefix.
(Or at least, that's how I encountered this issue)
Fixes #5800.
Affects gr-utils/modtool
Fails to parse:
```c++
: gr::sync_block("test",
io_signature::make(1, 1, sizeof(input_type) * 64),
io_signature::make(0, 0, 0))
```
After modifying the program, it parses correctly, and groups are parsed as expected.
=> modtool: parse io signatures without gr:: prefix

.github/workflows/make-test.yml
(cherry picked from commit bdd49943b6eda1004d5bf20e294639ee047ab40a)
Backport https://github.com/gnuradio/gnuradio/pull/6055
=> ci: add E275 to ignored error list (backport to maint-3.9)

.github/workflows/make-test.yml
(cherry picked from commit bdd49943b6eda1004d5bf20e294639ee047ab40a)
Backport https://github.com/gnuradio/gnuradio/pull/6055
=> ci: add E275 to ignored error list (backport to maint-3.10)

cmake/Modules/GrPython.cmake
In 6ff02a5289, we changed the method of determining the installation
directory to work with Fedora 36 and Ubuntu 22.04. For custom prefixes,
this did not end up working on Ubuntu 22.04.
(cherry picked from commit 307c0859b4b52e50cd4236a8ff2c10c3674e1dc0)
Backport https://github.com/gnuradio/gnuradio/pull/5979
=> GrPython.cmake: update method for determining installation directory (backport to maint-3.10)

blocklib/analog/fm_deemph/fm_deemph.yml, blocklib/analog/quadrature_demod/quadrature_demod.yml, blocklib/audio/alsa_sink/alsa_sink.yml, blocklib/math/complex_to_mag/complex_to_mag.yml, blocklib/math/complex_to_mag_squared/complex_to_mag_squared.yml, blocklib/math/conjugate/conjugate.yml, blocklib/streamops/interleaved_short_to_complex/interleaved_short_to_complex.yml, utils/blockbuilder/templates/blockname.grc.j2
In previous commits, the templated blocks were given standard type names
such as cf32 and rf32.  However the fixed type ports were still at the
c++ names.  This makes those consistent
Some cleanup related to #6043 
A handful of blocks that have fixed (not untyped) ports such as `complex_to_mag`
Loaded the blocks up in grc
=> 4.0: Continuation of standardized port types

gr-pdu/lib/CMakeLists.txt
The gr-pdu module has gnuradio-blocks and gnuradio-filter in its
target_link_libraries even though it doesn't use these modules. Removing
them will prevent extraneous libraries from being linked.
(cherry picked from commit e36f2fab5f1fccfbc15a496e2beaecf7db9143ec)
Backport https://github.com/gnuradio/gnuradio/pull/5914
=> pdu: Remove unused dependencies (backport to maint-3.10)

gr-wavelet/lib/CMakeLists.txt
The gr-wavelet module has gnuradio-blocks in its target_link_libraries
even though it doesn't use this module. Removing it will prevent
extraneous libraries from being linked.
(cherry picked from commit fef862b6c2e43531a715ce433d84e85e86cf76d9)
Backport https://github.com/gnuradio/gnuradio/pull/5915
=> wavelet: Remove unused dependency (backport to maint-3.10)

gr-qtgui/include/gnuradio/qtgui/spectrumdisplayform.h
(cherry picked from commit d6b730f4b3a494ec6a845a04e30de04de56d86d1)
Backport https://github.com/gnuradio/gnuradio/pull/5952
=> qtgui: Add missing <deque> include to spectrumdisplayform.h (backport to maint-3.10)

utils/blockbuilder/templates/blockname_pybind.cc.j2
When the yml files includes enums, we need the namespace in the pybind file to have the proper scope for the enum types
This was already done for templated blocks, so this adds the same feature for non-templated ones
=> 4.0: Add using namespace for enums in pybind

.github/workflows/build_and_test.yml
Some libs in Ubuntu 20.04 create some issues going to c++20 - namely modern fmtlib.  Rather than work around these, just set our min supported distro to ubuntu 22.04
#6050 
just ci
ci only changes
=> 4.0: ci: remove Ubuntu 20.04 worker

gr/include/gnuradio/meson.build
Just a couple of missing headers needed by OOTs potentially
=> 4.0: meson: missing include headers for install

gr-qtgui/grc/qtgui_waterfall_sink_x.block.yml
When generating cpp code for the waterfall sink (float),
the setting of the Spectrum Width ( Half, Full ) is ignored
and always set to Full
(cherry picked from commit 49d0618398dc810e45fe2f1566dae6cbb60e97dc)
Backport https://github.com/gnuradio/gnuradio/pull/5962
=> gr-qtgui: waterfall sink float Spectrum Width setting fails (backport to maint-3.10)

gr-pdu/lib/CMakeLists.txt
It appears this workaround was copied from the gr-wavelet module,
but it's not needed here because gr-pdu doesn't depend on GSL.
Removing it reduces the number of libraries that gr-pdu links to.
(cherry picked from commit 5d2e3ab5e59a0ff0f6d3a7c7b349847f095c2be1)
Backport https://github.com/gnuradio/gnuradio/pull/5912
=> pdu: Remove --no-as-needed linker option (backport to maint-3.10)

gnuradio-runtime/python/gnuradio/gr/bindings/thrift_application_base_python.cc, gr-iio/python/iio/bindings/fmcomms5_sink_python.cc, gr-iio/python/iio/bindings/fmcomms5_source_python.cc
Backport https://github.com/gnuradio/gnuradio/pull/5998
=> Fix Pybind hashes in Thrift bindings, fmcomms5 (backport to maint-3.10)

grc/gui/Utils.py
Since cairo.ImageSurface is pixel-based, it only accepts integer dimensions.
No need to round up – proper rounding and padding make this quite safe.
(cherry picked from commit 07716fbc81140cf39ece0872aedc50fc667fbaf6)
Backport https://github.com/gnuradio/gnuradio/pull/6004
=> GRC/Screenshots: create ImageSurface with int dimensions (backport to maint-3.10)

gr-filter/python/filter/pfb.py
(cherry picked from commit a2a0da69b62cbd05cf0e350b16f5cb7beb0c80dc)
Backport https://github.com/gnuradio/gnuradio/pull/6001
=> filter: pfb channelizer demo fix (backport to maint-3.10)

grc/core/params/dtypes.py, grc/core/params/param.py
Wrong values in the GUI HINT field are correctly handled in the gui
but lead to useless error messages in the terminal window
(cherry picked from commit b10d6e0eb989b85ed0ebcacf3695bc4d1dea2404)
Backport https://github.com/gnuradio/gnuradio/pull/5907
=> grc: gui_hint avoid useless error messages (backport to maint-3.10)

gr-blocks/examples/mic_to_OPUS.grc
(cherry picked from commit 6a91ceb1b433aace1656c27e9af00e74a2013c84)
Backport https://github.com/gnuradio/gnuradio/pull/5969
=> blocks: add example for wavfile sink (backport to maint-3.10)

gr-trellis/python/trellis/bindings/metrics_python.cc
Fixes #5985
(cherry picked from commit 76d8fb1d2858a78ba0a949079d19908a326eef8e)
Backport https://github.com/gnuradio/gnuradio/pull/6022
=> gr-trellis: add correct python bindings for metrics (backport to maint-3.10)

gr-iio/lib/fmcomms2_sink_impl.cc
Signed-off-by: AlexandraTrifan <Alexandra.Trifan@analog.com>
(cherry picked from commit 831fb91fbd23f808fbe0fc9bcadc7c5ec7ea3dc5)
Backport https://github.com/gnuradio/gnuradio/pull/6024
=> iio/fmcomms2_sink.cc: Fix scalar value to match format le:S16/16>>0 (backport to maint-3.10)

gr-qtgui/grc/qtgui_range.block.yml, gr-qtgui/python/qtgui/__init__.py, gr-qtgui/python/qtgui/range.py.cmakein
* qtgui: Add output message ports to range widgets
Signed-off-by: Charles Duffy <charles@dyfis.net>
* qtgui: move gui_hint below showports
Co-authored-by: Josh Morman <jmorman@gnuradio.org>
(cherry picked from commit 0427b2a6781a08cc57d82b27fbdd9a2300a34919)
Backport https://github.com/gnuradio/gnuradio/pull/5566
=> qtgui: Add output message ports to range widgets (backport to maint-3.10)

blocklib/analog/random_source/random_source.yml, utils/blockbuilder/scripts/process_folder.py, utils/blockbuilder/templates/blockname.meson.build.j2, utils/modtool/newblock/newblock_t.yml, utils/modtool/newmod/.gitignore, utils/modtool/newmod/blocklib/newmod/lib/meson.build, utils/modtool/newmod/meson.build, utils/modtool/newmod/subprojects/.gitignore, utils/modtool/newmod/subprojects/nlohmann_json.wrap
Block should have a top level yaml file but be able to not have any implementation other than grc
Fixes #6036 
Random source block in grc
=> 4.0 GRC only blocks via yaml file

gr-filter/lib/rational_resampler_impl.cc
Provide the invalid value of `fractional_bandwidth` within the error
message alongside the accepted range to ease with debugging.
This change should simplify debugging of flowgraphs when using the
the Rational Resampler block with an invalid `fractional_bandwidth`
parameter.
Up until now the error message did not provide the invalid value itself.
N/A inside gnuradio.
Downstream issue this might help with: [satnogs-flowgraphs#30](https://gitlab.com/librespacefoundation/satnogs/satnogs-flowgraphs/-/issues/30)
* gr-filter: Rational Resampler Block
None yet.
=> filter: Improve "invalid fractional bandwidth" error message

docs/doxygen/Doxyfile.in
Update STRIP_FROM_INC_PATH and EXCLUDE so that build paths
are not part of the generated documentation.
The Debian tool lintian noticed build paths being captured in the Doxygen
generated HTML files.
This would make the builds unreproducible .
Doxygen settings strip the build directory from the generated output,
but new gnuradio source directories gr-iio, gr-network, and gr-soapy
have not been added to the Doxygen config file.
Preparing gnuradio 3.10.3.0-3 for Debian with this patch, and
lintian no longer complains about HTML files in gnuradio-doc.
=> doxygen reproducible paths

bench/bm_copy.cc, bench/bm_nop.cc, gr/gr.conf.yml, gr/include/gnuradio/buffer.h, gr/include/gnuradio/buffer_sm.h, gr/include/gnuradio/meson.build, gr/include/gnuradio/sync_block.h, gr/lib/buffer_sm.cc, gr/lib/runtime.cc, gr/lib/runtime_monitor.cc, schedulers/nbt/include/gnuradio/schedulers/nbt/meson.build, schedulers/nbt/include/gnuradio/schedulers/nbt/scheduler_nbt.h, schedulers/nbt/include/gnuradio/schedulers/nbt/scheduler_nbt_options.h, schedulers/nbt/include/gnuradio/schedulers/nbt/thread_wrapper.h, schedulers/nbt/lib/graph_executor.cc, schedulers/nbt/lib/scheduler_nbt.cc, schedulers/nbt/lib/thread_wrapper.cc, schedulers/nbt/meson.build, schedulers/nbt/nbt.scheduler.conf.yml, schedulers/nbt/python/schedulers/nbt/bindings/scheduler_nbt_pybind.cc, test/qa_block_grouping.cc, test/qa_scheduler_nbt.cc
There were some issues in the scheduler handling single mapped buffers, especially when the block has output_multiple()
cuda or other buffer_sm based blocks that use output_multiple
Have some tests in my OOT - don't have a test block to do this directly
=> 4.0: Fixes for single mapped buffers

gr-blocks/grc/blocks_copy.block.yml
Copy Block won't compile in GRC's CPPGEN (block YAML had python syntax in CPP template)
@haakov helped me with the changes
Copy Block when compiling flowgraph with CPPGEN
Fresh clone of ```main```, edited gr-blocks/grc/blocks_copy.block.yml, rebuilt. Simple flowgraph compiles with no issues.
- [x ] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [ x] I have squashed my commits to have one significant change per commit. 
- [ x] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed)
- [ x] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md).
=> fix copy block cpp template

gr/include/gnuradio/meson.build, gr/lib/buffer_management.cc, schedulers/nbt/include/gnuradio/schedulers/nbt/thread_wrapper.h, schedulers/nbt/lib/scheduler_nbt.cc, test/qa_scheduler_nbt.cc, utils/blockbuilder/schema/gnuradio-block.json, utils/blockbuilder/templates/blockname.h.j2, utils/blockbuilder/templates/blockname_pybind.cc.j2, utils/blockbuilder/templates/blockname_pybind_templated.cc.j2, utils/blockbuilder/templates/blockname_templated.h.j2, utils/blockbuilder/templates/macros.j2
A few small fixes encountered on 4.0
1) fix some compiler warnings
2) remove some unused code
3) add back the `inherits` field to the block yml
This inherits field allows a block to have an additional interface, such as a domain specific block that inherits from a class that allows a callback to be set.
=> 4.0: some assorted small fixes

gr-blocks/lib/file_source_impl.cc
d_items_remaining was not being updated during seek, so end/repeat
of playback would not happen at the correct time.
File Source
Problem found and tested using Gqrx playback.
=> file source: update d_items_remaining on seek

gnuradio-runtime/include/gnuradio/block.h, gnuradio-runtime/python/gnuradio/gr/bindings/block_python.cc, gr-blocks/include/gnuradio/blocks/control_loop.h, gr-blocks/python/blocks/bindings/control_loop_python.cc, gr-blocks/python/blocks/qa_python_message_passing.py, gr-digital/examples/snr_estimators.py, gr-digital/include/gnuradio/digital/crc_check.h, gr-digital/lib/clock_tracking_loop.h, gr-digital/lib/interpolating_resampler.cc, gr-digital/python/digital/bindings/crc_check_python.cc, gr-digital/python/digital/soft_dec_lut_gen.py, gr-fec/python/fec/extended_decoder.py, gr-fec/python/fec/extended_tagged_decoder.py, gr-filter/include/gnuradio/filter/fft_filter.h, gr-filter/include/gnuradio/filter/firdes.h, gr-filter/lib/gen_interpolator_taps/diff_objective_fct.c, gr-filter/python/filter/bindings/fft_filter_python.cc, gr-filter/python/filter/bindings/firdes_python.cc, gr-utils/plot_tools/gr_plot_qt, gr-vocoder/examples/loopback-codec2.grc, gr-vocoder/examples/loopback-gsmfr.grc, grc/core/generator/cpp_top_block.py
* Fix various typos
Found via `codespell -q 3 -L ans,busses,circularly,fo,hist,impres,inh,inout,ist,ith,merchantibility,nd,nin,numer,ro,shif,sinc,uint -S ./volk,CHANGELOG.md,./docs/RELEASE-NOTES*,/home/beast/Projects/repos/gnuradio/.packaging/debian/changelog,/home/beast/Projects/repos/gnuradio/.packaging/fedora/gnuradio.spec`
Signed-off-by: luz paz <luzpaz@github.com>
* Update the hash in the corresponding pybind11 bind file
Signed-off-by: luz paz <luzpaz@github.com>
Signed-off-by: luz paz <luzpaz@github.com>
(cherry picked from commit 6c34c6bb795639a7f85ed74421ef1316999da4b8)
Backport https://github.com/gnuradio/gnuradio/pull/6051
=> global: fix various typos (backport to maint-3.10)

docs/doxygen/Doxyfile.in
Update STRIP_FROM_INC_PATH and EXCLUDE so that build paths
are not part of the generated documentation.
(cherry picked from commit fc98a991ee4ffbf678a71bc96a6ccff1f3dc001a)
Backport https://github.com/gnuradio/gnuradio/pull/6081
=> doxygen reproducible paths (backport to maint-3.10)

gr-filter/lib/rational_resampler_impl.cc
Provide the invalid value alongside the accepted range to ease with
debugging.
Signed-off-by: Fabian P. Schmidt <kerel@mailbox.org>
(cherry picked from commit a52d1805772e297593e4d94c4edc6a69e9cfc344)
Backport https://github.com/gnuradio/gnuradio/pull/6069
=> filter: Improve "invalid fractional bandwidth" error message (backport to maint-3.10)

gr-utils/modtool/tools/parser_cc_block.py
Previously, parsing signatures would fail if the io_signature call was
not prefixed with gr::, which is not necessary if currently in the gr
namespace anyway. This error may be encountered when copying gnuradio
source files into a new module, which don't use the gr:: prefix. This
patch addresses #5800.
Signed-off-by: esrh <esrh@gatech.edu>
(cherry picked from commit ba14ada01fefc052240dd21b6170a10b24e7b8eb)
Backport https://github.com/gnuradio/gnuradio/pull/6007
=> modtool: parse io signatures without gr:: prefix (backport to maint-3.10)

gr-trellis/python/trellis/bindings/metrics_python.cc
Fixes #5985
(cherry picked from commit 76d8fb1d2858a78ba0a949079d19908a326eef8e)
Backport https://github.com/gnuradio/gnuradio/pull/6022
=> gr-trellis: add correct python bindings for metrics (backport to maint-3.9)

grc/core/params/dtypes.py, grc/core/params/param.py
Wrong values in the GUI HINT field are correctly handled in the gui
but lead to useless error messages in the terminal window
(cherry picked from commit b10d6e0eb989b85ed0ebcacf3695bc4d1dea2404)
Backport https://github.com/gnuradio/gnuradio/pull/5907
=> grc: gui_hint avoid useless error messages (backport to maint-3.9)

gr-filter/python/filter/pfb.py
(cherry picked from commit a2a0da69b62cbd05cf0e350b16f5cb7beb0c80dc)
Backport https://github.com/gnuradio/gnuradio/pull/6001
=> filter: pfb channelizer demo fix (backport to maint-3.9)

grc/gui/Utils.py
Since cairo.ImageSurface is pixel-based, it only accepts integer dimensions.
No need to round up – proper rounding and padding make this quite safe.
(cherry picked from commit 07716fbc81140cf39ece0872aedc50fc667fbaf6)
Backport https://github.com/gnuradio/gnuradio/pull/6004
=> GRC/Screenshots: create ImageSurface with int dimensions (backport to maint-3.9)

gr-qtgui/include/gnuradio/qtgui/spectrumdisplayform.h
(cherry picked from commit d6b730f4b3a494ec6a845a04e30de04de56d86d1)
Backport https://github.com/gnuradio/gnuradio/pull/5952
=> qtgui: Add missing <deque> include to spectrumdisplayform.h (backport to maint-3.9)

gr-digital/lib/constellation_encoder_bc_impl.cc, gr-fft/lib/fft_v_fftw.cc
In 30643f01609e915296023adc37123e27e2c86d3f all the calls to
get_initial_sptr were replaced by make_block_sptr. However, there
are a few places where get_initial_sptr still remains. This replaces
the reminaing get_initial_sptr calls.
Signed-off-by: Daniel Estévez <daniel@destevez.net>
(cherry picked from commit e7b6e78bfd0b9edc8915a6386be0219151ade6e5)
Backport https://github.com/gnuradio/gnuradio/pull/5906
=> Replace calls to get_initial_sptr with make_block_sptr (backport to maint-3.9)

gr-blocks/lib/file_source_impl.cc
d_items_remaining was not being updated during seek, so end/repeat
of playback would not happen at the correct time.
(cherry picked from commit e063a8ac02b9aa6ee503718c32bf6730d091f098)
Backport https://github.com/gnuradio/gnuradio/pull/6114
=> file source: update d_items_remaining on seek (backport to maint-3.9)

utils/modtool/newmod/meson.build
Small change for modtool in OOTs to enable minimal changes for numpy blocks
=> 4.0: modtool: alias py3 to py3_inst

grc/CMakeLists.txt
xfce4-terminal is the terminal emulator for xfce users.  Support for
gnome and kde specific terminal emulators are already here, so please
accept this as well.
Signed-off-by: Rick Farina (Zero_Chaos) <zerochaos@gentoo.org>
=> grc: add xfce4-terminal to the grc auto-detector for XTERM_EXE

blocklib/filter/python/filter/meson.build, blocklib/math/python/math/meson.build, gr/python/gr/bindings/meson.build, kernel/python/kernel/digital/bindings/meson.build, kernel/python/kernel/fft/bindings/meson.build, kernel/python/kernel/filter/bindings/meson.build, kernel/python/kernel/math/bindings/meson.build, meson.build, schedulers/nbt/python/schedulers/nbt/bindings/meson.build, utils/blockbuilder/templates/module_python.meson.build.j2
On some systems (e.g. openSuse and nixOS) python packages are split between different install directories. This leads to include errors where includes like `#include <numpy/arrayobject.h>` cannot be resolved.
This PR fixes this by determining the numpy include path in the main meson.build file and adding it manually to all the relevant meson files as well as the j2 template for the autogenerated block files.
The approach is inspired by the numpy documentation for using numpy from meson [1].
We have tested these changes to build on nixOS unstable and openSUSE, but I do not have an ubuntu or fedora machine which seem to be the platforms that were tested to work before. I do not see why this should break builds there, though and I'll trust in the CI.
I'm also new to meson, but I have some …
=> GR 4.0: Add numpy include path to python bindings meson files

gr-qtgui/grc/qtgui_range.block.yml, gr-qtgui/python/qtgui/range.py.cmakein
- in the GRC yml file the widget was incorrectly stored in the variable
- in the py.cmakein file a variable was misspelled and caused errors
Signed-off-by: Miklos Maroti <mmaroti@gmail.com>
=> fix two QtRangeWidget bugs:

utils/modtool/newblock/newblock.yml, utils/modtool/newmod/meson.build
Addresses the default type of a parameter in the yaml, as well as the newly introduced numpy_incdir
=> 4.0: Minor Modtool updates

gr-iio/lib/fmcomms2_source_impl.cc
The RX2 in-phase was returning the same samples as RX1 in-phase
The index in function fmcomms2_source_impl() needs to be incremented by 2
Fix submitted by Nicolas Florio (github: nicolasflorio1)
Replaces https://github.com/gnuradio/gnuradio/pull/6137
=> iio: return correct samples for second channel

gr-digital/grc/digital_crc16_async_bb.block.yml, gr-digital/grc/digital_crc32_async_bb.block.yml, gr-digital/include/gnuradio/digital/crc16_async_bb.h, gr-digital/include/gnuradio/digital/crc32_async_bb.h, gr-digital/python/digital/bindings/crc16_async_bb_python.cc, gr-digital/python/digital/bindings/crc32_async_bb_python.cc
These are functionally superseded by the generic crc_append and crc_check
blocks and will be removed in a future release
The general CRC block supersedes these specific crc16 and crc32 blocks, and can be wrapped in a yml file for these special cases
https://github.com/gnuradio/gnuradio/pull/6096
crc16 and crc32 async blocks
=> digital: deprecate crc32/16_async blocks

.github/workflows/build_and_test.yml
This adds openSUSE tumbleweed as a CI worker
Will fail now due to some known issues with numpy
=> 4.0: ci: add OpenSUSE Tumbleweed to targets

gr-uhd/python/uhd/bindings/usrp_block_python.cc
`uhd_find_devices` would be the default shell function to discover available USRPs. PyUHD provides a function `uhd.find("")` that does the job. Besides, in `gr-uhd/python/uhd/__init__.py` there is a definition of `find_devices`. However, this function is broken at the moment because it tries to use a `find_devices_raw` function from the gr-uhd pybind11 interface that is not available. With this commit, we may be able to fix `find_devices` as well.
The actual change is just copied from UHD `host/lib/device_python.cpp`. Alternative solutions would include a new function in C++ and a pybind11 wrapper.
gr-uhd pybind11 interface
```python
from gnuradio import uhd
devices = uhd.find("")
```
yields a list of `gnuradio.uhd.uhd_python.device_addr_t` objects.
=> uhd: Add uhd.find to the pybind11 interface

blocklib/blocks/vector_sink/vector_sink_cpu.h, blocklib/soapy/rtlsdr_source/rtlsdr_source.yml, blocklib/streamops/load/load.yml, gr/include/gnuradio/constants.h, gr/include/gnuradio/meson.build, gr/include/gnuradio/parameter.h, gr/include/gnuradio/registry.h, gr/lib/block.cc, gr/lib/constants.cc.in, gr/lib/meson.build, gr/lib/registry.cc, test/meson.build, test/qa_reflection.cc, utils/blockbuilder/schema/gnuradio-block.json, utils/blockbuilder/scripts/filters.py, utils/blockbuilder/scripts/process_folder.py, utils/blockbuilder/templates/blockname.cc.j2, utils/blockbuilder/templates/blockname_templated.cc.j2, utils/blockbuilder/templates/macros.j2
Rebase of #6018 
Create a GR registry that maintains knowledge about what modules,
blocks, etc. are available, and has the ability to return generic block
constructors.
Basic usage would be
```
auto list = gr::registry::modules()
// "math" should be in list
list = gr::registry::blocks("math");
// "vector_source_f" should be in list
auto f = gr::registry::factory("math","vector_source_f")
auto blk = f(.... map of string/pmt)
```
Right now, this is all done through auto code generation, with the need being 
`.yml` --> headers, then headers should include reflection capability
This adds a generic factory to each block that can be invoked with `std::map<std::string, pmtf::pmt>' - which is a list of all the parameters in the block.  Since some parameters are not part of the constructor, these …
=> 4.0: Basic reflection capability

gnuradio-runtime/lib/flat_flowgraph.cc, gnuradio-runtime/lib/flowgraph.cc, gnuradio-runtime/lib/hier_block2_detail.cc, gr-analog/lib/sig_source_impl.cc, gr-uhd/lib/usrp_block_impl.cc
libfmt-9.0.0 disabled automatic std::ostream insertion operator (operator<<) discovery when fmt/ostream.h is included to prevent ODR violations. It require explicit tagging of ARG types.
Tried the following:
fmt::streamed and fmt::ostream_formatter not compatible with older versions, FMT_DEPRECATED_OSTREAM will be removed in the next major release so can't use.
With the help of @mormj, fixed this issue by not passing pointers of types not supported by libfmt into the logging functions.
Bug: https://bugs.gentoo.org/858659
Closes: https://github.com/gnuradio/gnuradio/issues/6052
Signed-off-by: Huang Rui <vowstar@gmail.com>
(cherry picked from commit 0019f292f526242a12c88489b56b63aa57f14ffb)
Backport …
=> global: Fix build failures with libfmt-9.0.0 in logger (backport to maint-3.10)

gr-qtgui/grc/qtgui_range.block.yml, gr-qtgui/python/qtgui/range.py.cmakein
- in the GRC yml file the widget was incorrectly stored in the variable
- in the py.cmakein file a variable was misspelled and caused errors
Signed-off-by: Miklos Maroti <mmaroti@gmail.com>
Signed-off-by: Miklos Maroti <mmaroti@gmail.com>
(cherry picked from commit 94d6ed9f18e234c8fae67713fdb8428f88b5bda7)
Backport https://github.com/gnuradio/gnuradio/pull/6144
=> qtgui: fix two QtRangeWidget bugs (backport to maint-3.10)

gnuradio-runtime/lib/CMakeLists.txt
Some tests use spdlog indirectly, but avoid linkage through the gnuradio::gnuradio-runtime target.
(cherry picked from commit 860e8dacd44cafbcb69365f3929766a3b2c31b39)
Backport https://github.com/gnuradio/gnuradio/pull/6139
=> runtime/qa: link against spdlog when not linking through the runtime library (backport to maint-3.10)

gr-digital/grc/digital_crc16_async_bb.block.yml, gr-digital/grc/digital_crc32_async_bb.block.yml, gr-digital/include/gnuradio/digital/crc16_async_bb.h, gr-digital/include/gnuradio/digital/crc32_async_bb.h, gr-digital/python/digital/bindings/crc16_async_bb_python.cc, gr-digital/python/digital/bindings/crc32_async_bb_python.cc
These are functionally superceded by the generic crc_append and crc_check blocks and will be removed in a future release
(cherry picked from commit c1b88ff2670f88311fc2e9e3a37f0781987fe698)
Backport https://github.com/gnuradio/gnuradio/pull/6128
=> digital: deprecate crc32/16_async blocks (backport to maint-3.10)

gr-iio/lib/fmcomms2_source_impl.cc
The RX2 in-phase was returning the same samples as RX1 in-phase The index in function fmcomms2_source_impl() needs to be incremented by 2
Fix submitted by Nicolas Florio (github: nicolasflorio1)
(cherry picked from commit 02cc2623a152698e578a1c1f0d64c9cddb136d8d)
Backport https://github.com/gnuradio/gnuradio/pull/6142
=> iio: return correct samples for second channel (backport to maint-3.10)

gr-uhd/python/uhd/bindings/usrp_block_python.cc
`uhd_find_devices` would be the default shell function to discover available USRPs. PyUHD provides a function `uhd.find("")` that does the job. Besides, in `gr-uhd/python/uhd/__init__.py` there is a definition of `find_devices`. However, this function is broken at the moment because it tries to use a `find_devices_raw` function from the gr-uhd pybind11 interface that is not available. With this commit, we may be able to fix `find_devices` as well.
The actual change is just copied from UHD `host/lib/device_python.cpp`. Alternative solutions would include a new function in C++ and a pybind11 wrapper.
Signed-off-by: Johannes Demel <demel@ant.uni-bremen.de>
(cherry picked from commit 9c64b6df0bffe1fd87965e6766e7ae762e5e9117)
Backport …
=> uhd: Add uhd.find to the pybind11 interface (backport to maint-3.10)

grc/CMakeLists.txt
xfce4-terminal is the terminal emulator for xfce users urxvt is a commonly used terminal emulator preferred by many over xterm Support for gnome and kde specific terminal emulators are already here, so please accept this as well.
Signed-off-by: Rick Farina (Zero_Chaos) <zerochaos@gentoo.org>
Signed-off-by: Rick Farina (Zero_Chaos) <zerochaos@gentoo.org>
(cherry picked from commit 67ef0469a0dabb3e1d876b4ac7d79b505a26873d)
Backport https://github.com/gnuradio/gnuradio/pull/6134
=> grc: add more terminals to the auto-detector (backport to maint-3.9)

gr-uhd/python/uhd/bindings/usrp_block_python.cc
`uhd_find_devices` would be the default shell function to discover available USRPs. PyUHD provides a function `uhd.find("")` that does the job. Besides, in `gr-uhd/python/uhd/__init__.py` there is a definition of `find_devices`. However, this function is broken at the moment because it tries to use a `find_devices_raw` function from the gr-uhd pybind11 interface that is not available. With this commit, we may be able to fix `find_devices` as well.
The actual change is just copied from UHD `host/lib/device_python.cpp`. Alternative solutions would include a new function in C++ and a pybind11 wrapper.
Signed-off-by: Johannes Demel <demel@ant.uni-bremen.de>
(cherry picked from commit 9c64b6df0bffe1fd87965e6766e7ae762e5e9117)
Backport …
=> uhd: Add uhd.find to the pybind11 interface (backport to maint-3.9)

.packaging/conda_recipe/meta.yaml, gr-utils/modtool/templates/gr-newmod/.conda/recipe/meta.yaml
Conda builds recently failed when run for the `v3.10.4.0-rc1` tag. This happened because the conda recipe parses the git tag to extract a version for the package, and it fails on any tag with a "-" in it. Moreover, the conda package versioning has been non-ideal for a little while, because it didn't strip the "v" from the beginning of the tag nor any "git" identifiers from the end of the tag. Fixing these within conda itself would take a while to be useful here, so a workaround is necessary.
Conda CI, conda recipe in OOT template.
I checked that the package version produced by these CI runs conforms to expectations.
=> conda: Make git tag parsing for package version more robust

gr-qtgui/lib/TimeRasterDisplayPlot.cc
Add missing `#include <stdexcept>` in qtgui `TimeRasterDisplayPlot` so that `std::runtime_error` is declared. This oversight was revealed in a conda Windows build using Boost 1.78.
qtgui
Fixes compilation against Boost 1.78 on Windows
=> qtgui: Add missing `#include <stdexcept>` for `std::runtime_error`.

utils/modtool/newmod/meson.build
One missing piece of the gen_meson script was passing whether python should be enabled for the module
=> 4.0: modtool: pass gr_enable_python to gen_meson script

gr/lib/buffer.cc
Since we keep track of total_read and total_written, we can see that when read_index == write_index whether this is wraparound or empty. This will allow slightly larger buffers to be handed to the work functions
=> 4.0: gr: allow buffer read catch up to write

gr-utils/blocktool/core/parseheader_generic.py
When pygccxml is not installed, the intention is that the user gets a basic functionality with parsing of the block implementation that gets automatically pybinded.  However, this doesn't appear to work at the moment because to have access to base class methods, the generated bindings need to list the base class.  
Prior to this fix, the following error occurs during flowgraph run when pygccxml is not installed and `gr_modtool bind` is called on a block:
```
ValueError: Unable to coerce endpoints: 'gnuradio.asdf.asdf_python.foo_general' object has no attribute 'to_basic_block'
```
This fix adds the minimally necessary gr::block and gr::basic_block to the inheritance chain
OOT modules using gr_modtool only when pygccxml is not installed
Used modtool to add and bind blocks, then test in GRC
=> pybind11: when no pygccxml, inherit gr::block

utils/blockbuilder/templates/blockname.grc.j2
On grc startup some errors like
audio_alsa_sink.block.yml  block: error: Value type 'NoneType' for 'outputs' not in valid types
are reported.
This pr avoids empty 'outputs:' statements.
Start grc without and after applying this patch.
=> dev-4.0:  suppress empty 'outputs:' statements in yml code

blocklib/analog/random_source/random_source.yml, blocklib/soapy/hackrf_sink/hackrf_sink.yml, blocklib/soapy/hackrf_source/hackrf_source.yml, blocklib/soapy/limesdr_source/limesdr_source.yml, blocklib/soapy/rtlsdr_source/rtlsdr_source.yml
Starting grc reports some errors like
analog_random_source.block.yml           block: error: Value type 'NoneType' for 'flags' not in valid types
soapy_hackrf_sink.block.yml              block: error: Value type 'NoneType' for 'flags' not in valid types
soapy_hackrf_source.block.yml            block: error: Value type 'NoneType' for 'flags' not in valid types
soapy_limesdr_source.block.yml           block: error: Value type 'NoneType' for 'flags' not in valid types
soapy_rtlsdr_source.block.yml            block: error: Value type 'NoneType' for 'flags' not in valid types
This pr adds the missing parameter to the *.yml source files.
Start grc without and with this patch.
=> dev-4.0: In some grc blocks the flags parameter is missing

blocklib/analog/lib/meson.build, blocklib/audio/lib/meson.build, blocklib/blocks/include/gnuradio/blocks/meson.build, blocklib/blocks/lib/meson.build, blocklib/fec/lib/meson.build, blocklib/fft/lib/meson.build, blocklib/fileio/lib/meson.build, blocklib/filter/lib/meson.build, blocklib/math/lib/meson.build, blocklib/soapy/lib/meson.build, blocklib/streamops/lib/meson.build, blocklib/zeromq/lib/meson.build
This way modules can be referenced out of tree - it was done this way for some but not all modules
=> 4.0: meson: move pkgconfig/cmake to lib dir for all modules

gr/include/gnuradio/buffer.h, gr/include/gnuradio/buffer_cpu_host.h, gr/include/gnuradio/buffer_sm.h, gr/include/gnuradio/custom_lock.h, gr/lib/buffer.cc, gr/lib/buffer_cpu_host.cc, gr/lib/buffer_sm.cc, gr/lib/meson.build, gr/meson.build, gr/test/meson.build, gr/test/qa_host_buffer.cc, schedulers/nbt/include/gnuradio/schedulers/nbt/scheduler_nbt.h, schedulers/nbt/include/gnuradio/schedulers/nbt/scheduler_nbt_options.h, schedulers/nbt/lib/graph_executor.cc, schedulers/nbt/lib/scheduler_nbt.cc
This brings the rest of the code changes in from 3.10 custom buffers
The logic is throughout the entire scheduler and buffer objects
Added a QA test
=> 4.0: Fix Single Mapped Buffer logic

gr-digital/lib/chunks_to_symbols_impl.cc, gr-digital/python/digital/qa_chunks_to_symbols.py
The Chunks to Symbols block overruns the input and output buffers when the dimension is greater than 1, because it miscalculates the number of input items. I've fixed that here.
Fixes #6210.
* Chunks to Symbols
I tested with a simple flowgraph:
I also added a new QA test which exercises the block with dimension 100. This demonstrates a segmentation fault on the main branch, whereas the test succeeds on the fix-c2s-dimension branch.
=> digital: Fix buffer overrun in Chunks to Symbols block

gr-blocks/python/blocks/qa_message_debug.py, gr-blocks/python/blocks/qa_message_strobe.py
The qa_message_strobe and qa_message_debug tests are flaky, because they depend on the execution times of two independent threads. Often, the second `msg_debug.num_messages()` measurement would only see 16 strobe messages, when it was expecting 17-23:
https://github.com/gnuradio/gnuradio/actions/runs/2839113118/jobs/4493232245
https://github.com/gnuradio/gnuradio/actions/runs/3083734659/jobs/4985030886
https://github.com/argilo/gnuradio/actions/runs/3201882761/jobs/5230289623
To solve the problem, I've made two changes:
* Push back the measurement times by 50ms, to 1050ms and 2050ms after the start of the flowgraph execution. This allows sufficient time for the 10th and 20th strobes to arrive before they are counted. (As originally written, the tests would always miss these strobes, even …
=> blocks: Fix flaky message_strobe and mesage_debug tests

gr-blocks/grc/blocks_delay.block.yml, gr-blocks/grc/blocks_exponentiate_const_cci.block.yml
@reald noticed that the parameters of the Delay and Exponentiate Const Int blocks fail to update at runtime if a floating point value is given. The QT GUI Range block defaults to floating point, making it likely to encounter this issue.
Updates fail with the following error:
```
File "/home/argilo/prefix_311/lib/python3.10/site-packages/gnuradio/qtgui/range.py", line 204, in changed
self.notifyChanged(self.rangeType(val))
File "/home/argilo/prefix_311/lib/python3.10/site-packages/gnuradio/qtgui/range.py", line 308, in sliderChanged
self.notifyChanged(self.rangeType(value))
File "/home/argilo/prefix_311/lib/python3.10/site-packages/gnuradio/qtgui/range.py", line 140, in notifyChanged
self.__slot(value)
File "/home/argilo/prefix_311/src/gnuradio/dealy.py", …
```
=> blocks: Convert argument to int in Python callbacks

gr-zeromq/grc/zeromq_pub_sink.block.yml, gr-zeromq/include/gnuradio/zeromq/pub_sink.h, gr-zeromq/lib/pub_sink_impl.cc, gr-zeromq/lib/pub_sink_impl.h, gr-zeromq/python/zeromq/bindings/pub_sink_python.cc
Signed-off-by: Sam <sam@whitings.org>
When using the high watermark option in the zeroMQ PUB/SUB blocks, another relevant parameter is left default which silently drops samples when the high watermark is reached. This PR adds a parameter to allow a user to change this behavior to "block" which would result in backpressure. 
More can be read about the default ZMQ behavior at http://api.zeromq.org/4-2:zmq-setsockopt looking for "ZMQ_XPUB_NODROP".
Fixes #6192 
ZeroMQ PUB and SUB streaming blocks now have additional option to allow using the high watermark in drop/block modes.
I have not been able to write a deterministic QA test that proves this fix works. The fix has only really been validated by running examples flowgraphs as shown in the related issue. The changes are consistent with …
=> zmq: add option to block/drop samples when high watermark reached

utils/blockbuilder/templates/blockname.meson.build.j2, utils/modtool/newblock/qa_newblock.py
This puts a default qa file in the block directory and links it into the module testing
Fixes #6200 
OOT blocks, though it can also be used in tree
created a new OOT, made a block, and it passed QA (no changes needed)
=> 4.0: modtool: put default qa test in the block dir

blocklib/soapy/.gitignore, blocklib/soapy/python/gnuradio/soapy/bindings/meson.build, blocklib/soapy/test/test_soapy.py
The test soapy application would not run - this brings the base bindings into the python_bindings file.
=> 4.0: soapy: fix up the bindings

gr-soapy/lib/block_impl.cc, gr-soapy/lib/block_impl.h, gr-soapy/lib/source_impl.cc, gr-soapy/lib/source_impl.h
Tag the output stream with the frequency, sample rate and hardware time. Following gr-uhd's rx_freq, rx_rate and rx_time tags.
Closes #6106
Signed-off-by: Roman Vaughan <nzsmartie@gmail.com>
(cherry picked from commit 3eea1057c53842476f809a62499ee6b8dc080d82)
Backport https://github.com/gnuradio/gnuradio/pull/6117
=> gr-soapy: Add gr-uhd tags to source blocks (backport to maint-3.10)

.packaging/conda_recipe/meta.yaml, gr-utils/modtool/templates/gr-newmod/.conda/recipe/meta.yaml
(cherry picked from commit 71c067caae01f77f2c16d9c15f7e19361f58bc04)
Backport https://github.com/gnuradio/gnuradio/pull/6165
=> conda: Make git tag parsing for package version more robust (backport to maint-3.10)

gr-fec/lib/CMakeLists.txt
Signed-off-by: Vasil Velichkov <vvvelichkov@gmail.com>
(cherry picked from commit ecc6fb86b61f75fb6811c226750cc0350b29f2ff)
Backport https://github.com/gnuradio/gnuradio/pull/6172
=> gr-fec: Remove GSL from public link interface (backport to maint-3.10)

gr-qtgui/lib/TimeRasterDisplayPlot.cc
Revealed in Windows build using Boost 1.78.
(cherry picked from commit 51ac1534dc6ef59bd5640c5e3f845a1e6c6d1855)
Backport https://github.com/gnuradio/gnuradio/pull/6176
=> qtgui: Add missing `#include <stdexcept>` for `std::runtime_error` (backport to maint-3.10)

gr-blocks/include/gnuradio/blocks/blockinterleaving.h, gr-blocks/lib/blockinterleaving.cc
(cherry picked from commit 463c3477549b26b32d9b73eef30044e97c4eee64)
Backport https://github.com/gnuradio/gnuradio/pull/6179
=> blocks: Including missing <vector> in blockinterleaver (backport to maint-3.10)

gr/include/gnuradio/meson.build
was accidentally left off from the list of installed header files
=> 4.0: gr: install custom_lock header

utils/blockbuilder/scripts/filters.py
Trying to load an ALSA_SINK in grc fails with
File "/usr/local/gnuradio/lib64/python3.10/site-packages/gnuradio/grc/gui/MainWindow.py", line 156, in _add_block_to_current_flow_graph
self.current_flow_graph.add_new_block(key)
File "/usr/local/gnuradio/lib64/python3.10/site-packages/gnuradio/grc/gui/canvas/flowgraph.py", line 165, in add_new_block
block = self.new_block(key)
File "/usr/local/gnuradio/lib64/python3.10/site-packages/gnuradio/grc/core/FlowGraph.py", line 328, in new_block
block = self.parent_platform.make_block(self, block_id, **kwargs)
File "/usr/local/gnuradio/lib64/python3.10/site-packages/gnuradio/grc/core/platform.py", line 432, in make_block
return cls(parent, **kwargs)
File "/usr/local/gnuradio/lib64/python3.10/site-packages/gnuradio/gr …
=> dev-4.0: grc fails to use alsa_sink block

gr-blocks/include/gnuradio/blocks/blockinterleaving.h
build fails with errors like this:
```
gnuradio/gr-blocks/lib/../include/gnuradio/blocks/blockinterleaving.h:25:36: error: ‘size_t’ was not declared in this scope
```
This failure is due to the miss of **cstddef** include
This PR adds this include in this file to fix this error
*gr-blocks blockinterleaving* 
Building and CI passing should be sufficient
=> blocks/blockinterleaving.h: add missing cstddef header (required for size_t)

gr-digital/lib/crc16_async_bb_impl.cc, gr-digital/python/digital/qa_crc16_async_bb.py
Signed-off-by: Michael Roe <michael-roe@users.noreply.github.com>
Fixes issues #6086
The CRC had the endianness of the host computer -- typically little endian -- rather than network (big) endian.
Modules affected: gr-digital/lib/crc16_async_bb_impl.cc, qa_crc16_async_bb
Tests carried out: "make test" with the new qa_crc16_async_bb
=> Fix CRC16 endianness

gr-wavelet/lib/CMakeLists.txt
This option causes a lot of extraneous libraries to be linked. It may no longer be needed.
It was added as a workaround in https://github.com/gnuradio/gnuradio/commit/c0b3ce38db0eaaca05fe2f45827fcf6c9184b72b.
I'm opening this draft pull request to see whether CI passes without it.
=> wavelet: Remove --no-as-needed linker option

gr-uhd/lib/rfnoc_graph_impl.cc
- Adds loggers
- Logs RFNoC connections made
This is part of the effort to improve RFNoC support in GNU Radio.
RFNoC graphs.
I ran this as part of testing new block controllers.
=> uhd: rfnoc_graph: Added logging

gr-uhd/lib/rfnoc_block_generic_impl.h, gr-uhd/lib/rfnoc_ddc_impl.h, gr-uhd/lib/rfnoc_duc_impl.h, gr-uhd/lib/rfnoc_rx_radio_impl.h, gr-uhd/lib/rfnoc_rx_streamer_impl.h, gr-uhd/lib/rfnoc_tx_radio_impl.h, gr-uhd/lib/rfnoc_tx_streamer_impl.h
The RFNoC block impls had some missing overrides.
=> uhd: Fix consistent override warnings

gr-uhd/include/gnuradio/uhd/rfnoc_block.h, gr-uhd/lib/rfnoc_block.cc
This adds the set_/get_property APIs into rfnoc_block and uses it in the
constructor to provide user settings.
Tested as part of adding new RFNoC block controllers.
=> uhd: rfnoc: Fix property setting on rfnoc_block

gr-uhd/grc/uhd_rfnoc_rx_streamer.block.yml, gr-uhd/grc/uhd_rfnoc_tx_streamer.block.yml
```
0dd955cbc (Martin Braun, 6 days ago)
uhd: rfnoc: Enable vlen and types for streamers
- RX and TX streamers can now set vector lengths
- The RX streamer GRC binding gets a 'byte' type
0e42fe349 (Martin Braun, 6 days ago)
uhd: rfnoc: Allow streamers to consume stream_args
The GRC bindings for the TX/RX streamers now allow setting stream args.
```
The streamers were not able to handle all the RFNoC blocks without this
change:
- Adding vector lengths is important for when RFNoC blocks go straight
into another GR block that expects vectors, e.g., blocks consuming FFT
output.
- The 'byte' type is necessary to allow data coming from the fosphor
block, which produces 8-bit integer data
- The stream args are necessary to pass additional parameters to UHD
streamers, e.g., for raw UDP, or for …
=> uhd: rfnoc: Improve settings for streamers

gr-uhd/include/gnuradio/uhd/rfnoc_block.h, gr-uhd/python/uhd/bindings/docstrings/rfnoc_block_pydoc_template.h, gr-uhd/python/uhd/bindings/rfnoc_block_python.cc
```
Changes:
53f049110 (Martin Braun, 27 hours ago)
uhd: rfnoc: Bind set/get_property APIs
This adds gr::uhd::rfnoc_block::set_property and get_property to the Python
API.
The tricky bit is that these are templated functions. The Python versions
therefore receive an optional, fourth argument 'type_hint' which loosely
corresponds to the template argument in C++.
If there is no type hint, we try and guess the correct type based on what
came in from Python. However, that can be ambiguous (e.g., Python's integer
could be an int, size_t, long long, uint32_t or whatever in C++). For these
cases, we allow a string-based representation of the type.
fc94efecc (Martin Braun, 4 days ago)
uhd: rfnoc: Add set_properties to rfnoc_block
This exposes …
```
=> uhd: rfnoc: Add property APIs

gr-qtgui/CMakeLists.txt, gr-qtgui/lib/CMakeLists.txt
This adds two changes to the qtgui CMake:
- The structure of lib/CMakeLists.txt now matches that of other
in-tree modules. This is so that in the future, we can have optional
sources, e.g. if we make QtOpenGL an optional dependency, and want to
add blocks based on its existence.
- We find the Qt5 package with QtWidgets as a COMPONENT, rather than
directly for Qt5Widgets. This allows adding OPTIONAL_COMPONENTS later
on.
built yo
=> qtgui: cmake: Align CMake structure with other modules

gnuradio-runtime/python/gnuradio/gr/gateway.py
Original version of _py_io_signature.port_types()_ method concatenates tuple with a list - and that fails in modern Python. This PR makes sure everything in that operation is a tuple, so it works correctly.
Fixes #6243
From what I see, respective part of original code was unusable and always failed (though, perhaps it worked in Python 2? I'm not sure about that...). This patch should have no effect on current blocks or flowgraphs which were running correctly without the patch applied.
With a patch applied, when py_io_signature is used in a way described in #6243, flowgraph now runs correctly instead of throwing `TypeError: can only concatenate tuple (not "list") to tuple` Python exception. Verified to work with a custom OOT block locally.
=> runtime: fix type replication in py_io_signature

gr-blocks/grc/blocks_delay.block.yml, gr-blocks/grc/blocks_exponentiate_const_cci.block.yml
(cherry picked from commit 339cdaaaa6f3f41c84a97ecf0e17718c738d1d05)
Backport https://github.com/gnuradio/gnuradio/pull/6224
=> blocks: Convert argument to int in Python callbacks (backport to maint-3.10)

gr-fec/lib/decode_ccsds_27_fb_impl.cc, gr-fec/lib/decode_ccsds_27_fb_impl.h, gr-fec/lib/viterbi/viterbi.cc, gr-fec/python/fec/qa_ecc_ccsds_27.py
The Decode CCSDS 27 block fails after processing approximately 4.2 million input bits. This happens because Viterbi path metric calculations are done using signed 32-bit integers, even though they are stored in signed 64-bit integers. Switching the calculations to signed 64-bit integers resolves the issue.
Fixes #5851.
* Viterbi decoder
I ran @daniestevez's test script (https://destevez.net/2017/07/degradation-bug-in-gnu-radio-decode-ccsds-27/) and also added a QA test which fails without this change and passes with it.
=> fec: Prevent integer overflow in path metric calculations

gr-blocks/python/blocks/qa_moving_average.py
As noted in #5973, `qa_moving_average` fails on i686 with the following error:
```
FAIL: test_vector_complex (__main__.test_moving_average)
File "/builddir/gnuradio-3.10.3.0/gr-blocks/python/blocks/qa_moving_average.py", line 150, in test_vector_complex
self.assertEqual(dut_data, ref_data)
AssertionError: Lists differ: [(705[443 chars].3553466796875+406.9476318359375j), (208.45861[1463 chars]25j)] != [(705[443 chars].35531616210938+406.9476318359375j), (208.4586[1474 chars]75j)]
First differing element 11:
(207.3553466796875+406.9476318359375j)
(207.35531616210938+406.9476318359375j)
Diff is 4376 characters long. …
```
=> blocks: Allow for floating point error in moving average test

gr-fft/python/fft/qa_window.py
As noted in #5973, `qa_window` fails on i686 with the following error:
```
FAIL: test_normwin (__main__.test_window)
Verify window normalization
File "/builddir/gnuradio-3.10.3.0/gr-fft/python/fft/qa_window.py", line 38, in test_normwin
self.assertAlmostEqual(power, 1.0)
AssertionError: 0.9999999411865508 != 1.0 within 7 places (5.8813449221872816e-08 difference)
```
This happens because the tolerance is too tight; `assertAlmostEqual` defaults to 7 decimal places, but the window calculations are done with single precision floats, which are only …
=> fft: Increase tolerance in qa_window test

gr-digital/lib/constellation.cc, gr-digital/python/digital/qa_constellation.py
As noted in #5973, `qa_constellation` fails on i686 with the following errors:
```
FAIL: test_soft_qam16_calc (__main__.test_constellation)
File "/builddir/gnuradio-3.10.3.0/gr-digital/python/digital/qa_constellation.py", line 379, in test_soft_qam16_calc
self.assertFloatTuplesAlmostEqual(y_cpp_raw_calc, y_cpp_table, 0)
File "/builddir/gnuradio-3.10.3.0/gnuradio-runtime/python/gnuradio/gr_unittest.py", line 96, in assertFloatTuplesAlmostEqual
self.assertEqual(len(a), len(b))
AssertionError: 17 != 25
FAIL: test_soft_qpsk_calc …
```
=> digital: Fix constellation soft decision LUT generation & tests

gr-blocks/python/blocks/qa_repack_bits_bb.py
There are two copies of the `test_002_three` test in qa_repack_bits_bb.py. It looks like the second copy was a copy-paste error made while adding MSB tests in ccebbe0a028158df250aae02c1dd893dd1551dda.
Here I have removed the duplicate test.
Removing this test should have no effect, since it overwrites an identical test.
=> blocks: Remove duplicate test case

gr-blocks/python/blocks/qa_mute.py
The `mute_cc(True)` test in qa_mute.py has a typo in its name. Because it has the same name as the test above, it overwrites that test and prevents it from executing.
Here I've corrected the typo.
QA tests for the Mute block.
I verified that all four tests execute after making this change. (Before the change, only 3 tests ran.)
=> blocks: Fix typo in test name

gr-digital/python/digital/qa_ofdm_frame_equalizer_vcvc.py
qa_ofdm_frame_equalizer_vcvc.py has two tests named `test_002_static_wo_tags`. The second overwrites the first, preventing it from executing. The duplicate name was introduced in bb01988e75d50d82cbb44c1a49c86c1d08f05665, but that was a large merge commit so I'm not sure exactly what the test was meant to do. But it's different from the other test, so I think both should be kept. I've simply renamed the second test here.
**Edit:** I also removed a duplicate variable definition that @willcode noticed.
QA tests for the OFDM Frame Equalizer block.
I verified that all 8 tests pass. (Prior to this change, only 7 out of 8 tests executed.)
=> digital: Rename test to avoid duplicate name

gr-fec/lib/ldpc_gen_mtrx_encoder_impl.cc, gr-fec/lib/ldpc_par_mtrx_encoder_impl.cc
As noted in #989 and #5973, `qa_fecapi_ldpc` fails on i686 systems. This happens because the output size of the LDPC encoder is miscalculated. The frame size is multiplied by the code rate in floating point, and the result is cast to an integer without rounding. As a result, the output size may be one too small.
Fixes #989.
* LDPC Generator Matrix
* LDPC Parity Check Matrix
I verified that the QA tests pass on i686 and x86_64.
=> fec: Fix LDPC output size calculation

gr-fec/python/fec/qa_fecapi_ldpc.py
qa_fecapi_ldpc.py has two identical copies of the `test_parallelism2_00` test. The tests have been identical since they were created in bbaa0294e50f2aab02b6413f7e2f17a23fca81b2, so I suspect this is a copy & paste error. I've deleted the second test here.
QA for LDPC blocks.
=> fec: Remove duplicate test from qa_fecapi_ldpc

gr-fec/lib/ldpc_G_matrix_impl.cc, gr-fec/lib/ldpc_G_matrix_impl.h, gr-fec/python/fec/qa_fecapi_ldpc.py
The `qa_fecapi_ldpc` test file has two different tests named `test_parallelism0_03`. The second one shadows the first, preventing it from executing. (This has been the case since the tests were created in ee6b68433b815c3bb66b44f8a6c12709059cf65a.)
After renaming the two tests, the first test segfaults. This happens because `ldpc_G_matrix_impl::~ldpc_G_matrix_impl` attempts to free `d_H_obj`, which was never allocated. In fact, this member variable is completely unused, so it can simply be removed. After removing it, both QA tests pass.
* LDPC Generator Matrix
* LDPC Bit Flip Decoder
All I've done is verify that the LDPC tests pass after this change. The `test_parallelism0_03_gen` test exercises both the generator matrix and the bit flip decoder.
=> fec: Fix LDPC G matrix implementation & tests

gr-zeromq/grc/zeromq_pub_sink.block.yml, gr-zeromq/include/gnuradio/zeromq/pub_sink.h, gr-zeromq/lib/pub_sink_impl.cc, gr-zeromq/lib/pub_sink_impl.h, gr-zeromq/python/zeromq/bindings/pub_sink_python.cc
Signed-off-by: Sam <sam@whitings.org>
Co-authored-by: Sam <shwhiti@sandia.gov>
(cherry picked from commit c49548c2e079fa3b50efbd8d1699b5089d523438)
Backport https://github.com/gnuradio/gnuradio/pull/6193
=> zmq: add option to block or drop samples when high watermark is reached (backport to maint-3.10)

gr-filter/include/gnuradio/filter/hilbert_fc.h, gr-filter/python/filter/bindings/hilbert_fc_python.cc
This patch improves the description of an analytic signal and its relation with hilbert transform given in [hilbert_fc.h](https://github.com/gnuradio/gnuradio/blob/main/gr-filter/include/gnuradio/filter/hilbert_fc.h).
cc @mbr0wn 
Fixes https://github.com/gnuradio/gnuradio/issues/5437
Supersedes #6177 
The change is related to the hilbert transformer block. There shouldn't be a change in performance whatsoever.
Documentation-related change, so no testing is required.
=> docs: Improve documentation in hilbert_fc.h

gr-blocks/include/gnuradio/blocks/blockinterleaving.h
Signed-off-by: Gwenhael Goavec-Merou <gwenhael.goavec-merou@trabucayre.com>
(cherry picked from commit 719db87a6cf33c4b7b0c2b80ee3b36e0839a06a1)
Backport https://github.com/gnuradio/gnuradio/pull/6188
=> blocks/blockinterleaving.h: add missing cstddef header (backport to maint-3.10)

gr-wavelet/lib/CMakeLists.txt
This option causes a lot of extraneous libraries to be linked. It may no longer be needed.
(cherry picked from commit bd7238e3a326d5d75ce5ccc9330c52b622247dc8)
Backport https://github.com/gnuradio/gnuradio/pull/5913
=> wavelet: Remove --no-as-needed linker option (backport to maint-3.10)

gr-uhd/lib/rfnoc_graph_impl.cc
- Adds loggers
- Logs RFNoC connections made
(cherry picked from commit 5e0372b1a165cc83b6bdb761d1db6350975ccecf)
Backport https://github.com/gnuradio/gnuradio/pull/6218
=> uhd: rfnoc_graph: Added logging (backport to maint-3.10)

gr-uhd/lib/rfnoc_block_generic_impl.h, gr-uhd/lib/rfnoc_ddc_impl.h, gr-uhd/lib/rfnoc_duc_impl.h, gr-uhd/lib/rfnoc_rx_radio_impl.h, gr-uhd/lib/rfnoc_rx_streamer_impl.h, gr-uhd/lib/rfnoc_tx_radio_impl.h, gr-uhd/lib/rfnoc_tx_streamer_impl.h
The RFNoC block impls had some missing overrides.
(cherry picked from commit b22cddf8ab6cb1243a13be9b5180bb84545a9299)
Backport https://github.com/gnuradio/gnuradio/pull/6219
=> uhd: Fix consistent override warnings (backport to maint-3.10)

gr-digital/lib/crc16_async_bb_impl.cc, gr-digital/python/digital/qa_crc16_async_bb.py
Changing byte ordering for CRC16 is technically a break in backward compatibility. However, we do not believe this block is being used in a way that it would matter at the moment.
Signed-off-by: Michael Roe <michael-roe@users.noreply.github.com>
Co-authored-by: Michael Roe <michael-roe@users.noreply.github.com>
(cherry picked from commit 6e03c5699109f93a7e13ccfb7c391e913f2fc3d4)
Backport https://github.com/gnuradio/gnuradio/pull/6096
=> digital: Fix CRC16 endianness (backport to maint-3.10)

gr-blocks/lib/CMakeLists.txt, gr-blocks/lib/probe_signal_impl.cc, gr-blocks/lib/probe_signal_impl.h
@balister noticed that `test_003_race_condition_regression_test` (added in #5744) fails on ARM:
```
File "/usr/lib/gnuradio/ptest/gr-blocks/python/blocks/qa_probe_[signal.py](http://signal.py/)", line 64, in test_003_race_condition_regression_test
self.assertIn(output, [1 + 2j, 3 + 4j])
AssertionError: (1+4j) not found in [(1+2j), (3+4j)]
```
It's apparent from the error message that the probe level is not being updated atomically, so the I value from one sample and the Q value from another are mixed together. I suspect the problem is that `std::atomic` is not supported on all platforms.
The vector version of the Probe Signal block uses a mutex (since `std::atomic` cannot be used with vectors) and the corresponding test always passes on ARM. We can fix …
=> blocks: Use mutex instead of std::atomic for probe synchronization

gr-uhd/python/uhd/bindings/python_bindings.cc
Without this declaration, function calls that require a time_spec_t
argument must be provided with such an argument, even if there is
a default argument.
For example, in the RFNoC DDC block, we couldn't call set_freq() as
such:
```python
ddc_block.set_freq(0.0, 0)
```
It would produce the following error:
```
TypeError: set_freq(): incompatible function arguments. The following
argument types are supported:
1. (self: gnuradio.uhd.uhd_python.rfnoc_ddc,
freq: float,
chan: int,
time: gnuradio.uhd.uhd_python.time_spec_t = 0.0) -> float
```
Even though the argument `time` is optional, the default value of 0.0 is
not able to satisfy the requirements. By adding the
`py::implicitly_convertible` call, we declare float convertible to time
spec, and the call above can proceed.
Any of the examples …
=> uhd: Declare float to time_spec_t implicitly convertible

.packaging/conda_recipe/bld.bat, .packaging/conda_recipe/build.sh, gr-blocks/python/blocks/qa_throttle.py
In https://github.com/gnuradio/gnuradio/pull/3149 I added tests for the Throttle block. I noticed that these tests are skipped in Conda builds (OSX & Windows), and the logs show that they do occasionally fail due to execution of the flow graph taking approximately 450 ms. (Conda builds appear to be more sensitive to timing issues because the test suite is executed in parallel.) Here I've increased the tolerance to 600 ms, which I hope will be enough to make the tests reliable. I've also removed `qa_throttle` from the list of skipped tests in Conda builds.
Tests for the Throttle block.
I verified that the tests still pass reliably on my machine, even when adding CPU stress (with `stress -c 16`).
=> blocks: Increase tolerance in qa_throttle tests

gr-network/lib/CMakeLists.txt, gr-network/lib/asio/asio.hpp, gr-network/lib/socket_pdu_impl.cc, gr-network/lib/socket_pdu_impl.h, gr-network/lib/tcp_connection.cc, gr-network/lib/tcp_connection.h, gr-network/lib/tcp_sink_impl.cc, gr-network/lib/tcp_sink_impl.h, gr-network/lib/udp_sink_impl.cc, gr-network/lib/udp_sink_impl.h, gr-network/lib/udp_source_impl.cc, gr-network/lib/udp_source_impl.h
This makes boost::asio look identical to non-Boost asio within our
block definitions.
Signed-off-by: japm48 <japm48gh@gmail.com>
Co-authored-by: Martin Braun <martin.braun@ettus.com>
This is an attempt to merge part of
https://github.com/gnuradio/gnuradio/pull/5957.
That PR by @japm48 is in general a very good PR, but we're currently
unsure if we even want to go all the way removing boost::asio, given
that we are having issues removing other Boost components, like Boost
threading.
However, this PR pulls in all the code changes first, without actually
moving to non-Boost ASIO, which we can still merge later. What this
gives us, however, is the ability to more easily port gr-network to
non-Boost ASIO at a later time.
- Built locally
- Ran QA tests
- Ran some simple gr-network examples
=> network: Move boost::asio namespace to asio

.packaging/conda_recipe/bld.bat, .packaging/conda_recipe/build.sh
Conda builds skip many CI tests. Some of the tests do still fail, but others now pass reliably because bugs have been fixed. Here I've cleaned up the list of skipped tests:
* `qa_cpp_py_binding`, `qa_cpp_py_binding_set`, `qa_ctrlport_probes` → not executed because ControlPort is not enabled
* `qa_rotator_cc` → fixed in https://github.com/gnuradio/gnuradio/pull/5755
* `qa_tcp_server_sink` → removed in https://github.com/gnuradio/gnuradio/pull/4463
* `test_modtool` → only fails on Windows
* `qa_add_system_time` → fixed in https://github.com/gnuradio/gnuradio/pull/5749
CI tests in Conda builds
I had a look over recent Conda builds to see which tests are still failing. None of these tests failed in the past five runs.
=> CI: trim the list of skipped tests in Conda builds

gr-fec/include/gnuradio/fec/ldpc_G_matrix.h, gr-fec/lib/ldpc_G_matrix_impl.cc, gr-fec/lib/ldpc_G_matrix_impl.h, gr-fec/python/fec/bindings/docstrings/ldpc_G_matrix_pydoc_template.h, gr-fec/python/fec/bindings/ldpc_G_matrix_python.cc
While working on #6276, I noticed that the `test_parallelism0_03_gen` test in qa_fecapi_ldpc.py crashes on Windows. This is due to two bugs:
* `ldpc_G_matrix::n` and `ldpc_G_matrix::k` are missing Python bindings
* a smart pointer to a matrix doesn't have its deleter set
I've fixed those bugs here.
LDPC G matrix
I verified that the `qa_fecapi_ldpc` tests pass.
Here's a test run (on my fork) with both #6276 and this PR, and `qa_fecapi_ldpc` re-enabled on Windows: https://github.com/argilo/gnuradio/actions/runs/3303639617
=> fec: Fix ldpc_G_matrix bugs

.packaging/conda_recipe/bld.bat, gr-blocks/python/blocks/qa_file_descriptor_source_sink.py, gr-blocks/python/blocks/qa_file_sink.py, gr-blocks/python/blocks/qa_file_source.py
Several file-related tests fail on Windows with "Permission denied" errors:
```
ERROR: test_file_descriptor (__main__.test_file_descriptor_source_sink)
File "%SRC_DIR%\gr-blocks\python\blocks\qa_file_descriptor_source_sink.py", line 33, in test_file_descriptor
fhandle0 = open(temp.name, "wb")
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\tmpmfjxx9mx'
ERROR: test_file_sink (__main__.test_file_sink) …
```
=> blocks: Fix file tests to work on Windows

.packaging/conda_recipe/bld.bat, gr-utils/modtool/tests/test_modtool.py, gr-utils/modtool/tools/util_functions.py
As indicated by the `test_modtool` test, `gr_modtool` does not work on Windows because Python's readline module is not available on that platform. We can avoid the problem by making `SequenceCompleter` a no-op when readline is missing. Since this approach doesn't add any new dependencies, it is safe to backport.
Fixes #6280.
gr_modtool
I verified that readline functionality still works on Linux, and that gr_modtool works on Windows. I also intentionally modified the `import readline` line to `import readlinezz` to verify that the fallback works as expected.
=> utils: Allow fallback when readline is not available

gnuradio-runtime/lib/controlport/thrift/rpcpmtconverters_thrift.cc
Implicit cast in an error/log message did not work with newer versions of fmt (v9 on SUSE). Use `pmt::write_string()` instead.
Fixes #6278
Runtime
=> runtime: make logging in rpcpmtconverters_thift work with fmt v9

utils/blockbuilder/templates/blockname.cc.j2
Make sure setters and getters use std::vector<dtype> if they are declared with "container: vector".
Signed-off-by: Frank Osterfeld <frank.osterfeld@kdab.com>
This fixes the generated code when removing the template parameter from https://github.com/fair-acc/gr-digitizers/blob/gr40-port/blocklib/digitizers/chi_square_fit/chi_square_fit.yml
The templated block template (hah) has the correct signatures, this just applying the same to the nontemplated template.
https://github.com/fair-acc/gr-digitizers/blob/gr40-port/blocklib/digitizers/chi_square_fit/chi_square_fit.yml works, I don't think there are tests for the code generation itself (other than that it has to work building the included blocks), so I haven't added any.
- [-] I have updated [the …
=> Fix generated vector setter/getter signatures in non-templated blocks

gr-filter/python/filter/qa_fft_filter.py
The method to generate taps in qa_fft_filter was always returning 0 due to `float(int(..))`
qa for fft filter
Should pass QA as before
=> filter: use non-zero taps for fft filter qa

gnuradio-runtime/lib/pmt/pmt_serialize.cc, gnuradio-runtime/python/pmt/qa_pmt.py
#3320 made some changes to the PMT serialization format:
* Prior to the change, 32-bit complex vectors were serialized as (real, imag) big-endian doubles
* After the change (which went into the 3.9.0.0 release), 32-bit complex vectors were serialized as:
* (imag, real) big-endian floats on little-endian systems
* (real, imag) big-endian floats on big-endian systems
The platform-dependent behaviour causes the corresponding absolute serialization test (added in #3425) to fail on big-endian systems because it expects the (imag, real) ordering:
```
FAIL: test23_absolute_serialization_float_uvecs (__main__.test_pmt) …
```
=> runtime: Fix PMT serialization of C32 vectors

.github/workflows/make-test.yml
GitHub Actions has a default timeout of 360 minutes. The formatting and Doxygen jobs only take about two minutes each, so we should lower the timeout to ensure that these jobs fail in a timely manner if a hang occurs.
https://github.com/gnuradio/gnuradio/pull/6275#issuecomment-1295194054
None; this is a CI-only change.
None.
=> CI: Lower timeouts on formatting & Doxygen jobs

gr-blocks/python/blocks/qa_wavfile.py
Although the [documentation](https://docs.python.org/3/library/wave.html#wave.Wave_read.readframes) doesn't mention it, Python's `Wave_read.readframes()` function returns samples in machine order. This can be seen in the source code:
https://github.com/python/cpython/blob/c5f3f296f4c9ec5a294dedc805be69929fe169cc/Lib/wave.py#L364-L365
A git blame shows that the behaviour has been the same for at least the last 25 years.
This means that samples should be unpacked in machine order, rather than little-endian. Making this change fixes the following test failure on big-endian systems:
```
FAIL: test_003_checkwav_append_copy (__main__.test_wavefile) …
```
=> blocks: Read WAV file frames correctly in qa_wavfile

.packaging/conda_recipe/bld.bat, cmake/Modules/GrTest.cmake, gr-dtv/python/dtv/qa_dtv.py
All tests that use the `srcdir` environment variable to refer to files from the GNU Radio source directory currently fail on Windows, with errors like the following:
```
ERROR: test_003_checkwav_append_copy (__main__.test_wavefile)
File "%SRC_DIR%\gr-blocks\python\blocks\qa_wavfile.py", line 89, in test_003_checkwav_append_copy
copyfile(infile, outfile)
File "%PREFIX%\lib\shutil.py", line 264, in copyfile
with open(src, 'rb') as fsrc:
OSError: [Errno 22] Invalid argument: '"C:\\Miniconda3\\conda-bld\\gnuradio-dev_1666264729221\\work\\gr-blocks\\python\\blocks"\\test_16bit_1chunk_normal.wav' …
```
=> cmake: Fix excess quoting of srcdir environment variable

.github/workflows/make-test.yml
metainfo_test was disabled in #5178 due to a certificate validation error. As noted in the pull request, this change was meant to be temporary.
I'm opening this pull request to revert that change and see whether CI now passes. 
Fixes #5132.
CI testing on Ubuntu 20.04 only.
=> CI: Re-enable metainfo_test on Ubuntu 20.04

.packaging/conda_recipe/build.sh, gr-blocks/python/blocks/qa_message_debug.py, gr-blocks/python/blocks/qa_message_strobe.py
I recently increased the tolerances for the qa_message_debug and qa_message_strobe tests in #6225. However, I later noticed that these tests still fail on almost every run of Conda OSX CI. (OSX seems to be the most heavily loaded CI platform. Failures of qa_message_debug & qa_message_strobe are currently ignored there.)
In the most recent 10 runs, I observed `msg_debug.num_messages()` readings as low as 4 on the second call, and as low as 12 on the third call. Here I've increased the tolerances to allow for values as extreme as those, plus a margin of two. I also removed these tests from the list of tests for which failures are ignored.
QA tests for the Message Debug & Message Strobe blocks.
I verified that these tests still pass on my machine.
=> blocks: Increase tolerance in message_strobe and message_debug tests

.github/workflows/make-test.yml, .packaging/conda_recipe/build.sh
The `qa_qtgui` tests are skipped in CI. From the Conda Linux build logs, it can be seen that the error is:
```
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
Available platform plugins are: eglfs, minimal, minimalegl, offscreen, vnc, webgl, xcb.
```
This error can be avoided by switching to the "offscreen" plugin (which should be suitable for the headless CI environment).
Qt GUI tests in CI.
=> CI: Re-enable qa_qtgui tests

gr-qtgui/CMakeLists.txt, gr-qtgui/lib/CMakeLists.txt
This adds two changes to the qtgui CMake:
- The structure of lib/CMakeLists.txt now matches that of other in-tree modules. This is so that in the future, we can have optional sources, e.g. if we make QtOpenGL an optional dependency, and want to add blocks based on its existence.
- We find the Qt5 package with QtWidgets as a COMPONENT, rather than directly for Qt5Widgets. This allows adding OPTIONAL_COMPONENTS later on.
(cherry picked from commit 75bdf99946e98880b9d29f5e883768fbb9c2f022)
Backport https://github.com/gnuradio/gnuradio/pull/6221
=> qtgui: cmake: Align CMake structure with other modules (backport to maint-3.10)

gr-qtgui/grc/qtgui_msgcheckbox.block.yml, gr-qtgui/grc/qtgui_msgdigitalnumbercontrol.block.yml, gr-qtgui/python/qtgui/msgcheckbox.py
After finishing #6316 I noticed a couple other blocks with broken code generation.
QT GUI Msg CheckBox generates invalid syntax:
```
File "/home/argilo/git/bso2022/ultrasonic/tx.py", line 89
_left_on_toggle_button = qtgui.MsgCheckBox(self.set_left_on, ''foo'', self._left_on_choices, False, 1, 1,"'value'".replace("'",""))
^^^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
```
Also, when the Boolean type is selected, the value is not coerced to boolean (as it is in the Toggle Button & Toggle Switch blocks).
Finally, the QT GUI Digital Number Control uses `.replace("'","")` to munge a string; this is no longer needed, and by removing it the generated code is correct even if the name happens to contain a double quote.
* QT GUI Msg Checkbox
* QT GUI Digital Number Control
Made …
=> qtgui: Fix code generation for Msg CheckBox & Digital Number Control

grc/meson.build
trivial fix for failing `meson setup build --prefix=/usr --libdir=lib64`
<none>
it builds when specifying `/usr` as prefix
=> meson: fixed typo in meson.build for prefix == '/usr'

gr-network/lib/udp_sink_impl.cc, gr-network/lib/udp_sink_impl.h, gr-network/lib/udp_source_impl.cc, gr-network/lib/udp_source_impl.h
This is a continuation of the effort to remove unnecessary Boost from GNU radio. The UDP Source and UDP Sink blocks use `boost::circular_buffer` to buffer data, but this can be replaced with ~~`std::queue`. The only change that's needed is to check the queue size before each `push()` to check whether the oldest element needs to be discarded.~~ `gr::buffer`. This also allows the local buffers and associated `memcpy` calls to be eliminated.
* UDP Source
* UDP Sink
So far I've only verified that the tests still pass. I'll take the blocks for a spin soon.
=> network: Replace boost::circular_buffer with gr::buffer

gr-qtgui/grc/qtgui_togglebutton.block.yml, gr-qtgui/grc/qtgui_toggleswitch.block.yml
The QT GUI Toggle Button and Toggle Switch blocks generate invalid Python code if the Type is set to Float or String:
```
File "/home/argilo/git/bso2022/ultrasonic/tx.py", line 193, in <module>
main()
File "/home/argilo/git/bso2022/ultrasonic/tx.py", line 171, in main
tb = top_block_cls()
File "/home/argilo/git/bso2022/ultrasonic/tx.py", line 98, in __init__
if real == bool:
NameError: name 'real' is not defined
```
```
File "/home/argilo/git/bso2022/ultrasonic/tx.py", line 193, in <module>
main()
File "/home/argilo/git/bso2022/ultrasonic/tx.py", line 171, in main
tb = top_block_cls()
File "/home/argilo/git/bso2022/ultrasonic/tx.py", line 98, in __init__
if string == bool:
NameError: name 'string' is not defined
```
In …
=> qtgui: Fix code generation for Toggle Button & Toggle Switch

gr-digital/lib/header_buffer.cc
The `add_field16`, `add_field32`, and `add_field64` functions have undefined behaviour because they copy the machine representation of multi-byte integers directly into the output buffer. As a result, they do not produce the correct output on big-endian systems. Switching to bit shifts will ensure consistent operation across platforms.
The errors on big-endian systems are as follows:
```
/home/argilo/gnuradio/gr-digital/lib/qa_header_format.cc(71): fatal error: in "test_default_format": critical check 0xAA == (int)h0 has failed [170 != 0]
/home/argilo/gnuradio/gr-digital/lib/qa_header_format.cc(154): fatal error: in "test_counter_format": critical check 0xAA == (int)h0 has failed [170 != 0]
/home/argilo/gnuradio/gr-digital/lib/qa_header_buffer.cc(48): fatal error: in "test_add16": …
```
=> digital: Make the add_field functions portable

cmake/Modules/GrPython.cmake
CMake sometimes fails with:
```
| CMake Error at cmake/Modules/GrPython.cmake:197 (add_custom_target):
|   add_custom_target cannot create target "pygen_gr_digital_examples_c8263"
|   because another target with the same name already exists.  The existing
|   target is a custom target created in source directory
|   "/home/buildbot/worker/lyon-worker/build-master-qemu-next/build/build/tmp-glibc/work/cortexa57-oe-linux/gnuradio/3.10.3.0+gitAUTOINC+3f9c56abc8-r0/git/gr-digital/examples".
|   See documentation for policy CMP0002 for more details.
| Call Stack (most recent call first):
|   cmake/Modules/GrPython.cmake:391 (gr_unique_target)
|   gr-digital/examples/CMakeLists.txt:30 (gr_python_install)
```
This is because the code that generates unique target names for examples does so by …
=> cmake: Ensure that target names are unique

gr-blocks/python/blocks/qa_throttle.py
Even after the tolerance increase in #6272, `qa_throttle` is still failing on Windows:
https://github.com/gnuradio/gnuradio/actions/runs/3357519882/jobs/5563380391
https://github.com/gnuradio/gnuradio/actions/runs/3360756897/jobs/5570335077
Let's bump it up again to stop the test failures.
* https://github.com/gnuradio/gnuradio/pull/6272#issuecomment-1296459000
Tests for the Throttle block.
=> blocks: Increase number of samples and tolerance in qa_throttle

gr-pdu/python/pdu/qa_time_delta.py
The tolerance for this test was increased in #5764, but that was not enough. Another test failure occurred on Windows:
https://github.com/gnuradio/gnuradio/actions/runs/3364269344/jobs/5578423969
* #5764
CI tests for the Time Delta block.
I verified that the test still passes on my machine, even when stressed with `stress -c 128`.
=> pdu: Increase tolerance in flaky test again

.github/workflows/make-test.yml, gnuradio-runtime/lib/block.cc, gnuradio-runtime/lib/terminate_handler.cc, gr-iio/lib/device_sink_impl.cc
Running CI on a 32-bit system should help catch more bugs, like the ones identified in #5973.
On top of the bugs reported there, there were also some new compiler warnings which I've fixed here:
* `terminate_handler.cc` used incorrect format specifiers; I've switched to streaming to avoid the need for format specifiers
* `block.cc` made a signed-to-unsigned integer comparison
* `device_sink_impl.cc` made a signed-to-unsigned integer comparison
It was necessary to switch to an order release of actions/checkout, because later versions depend on Node, and the version supplied by GitHub Actions does not work inside 32-bit containers.
Replaces #5976.
* stack trace printing the runtime's terminate handler
* `gr_block`, specifically the `allocate_detail` method
* IIO Device Sink block
So far …
=> Add Debian 32-bit to CI and fix bugs affecting 32-bit systems

.packaging/conda_recipe/build.sh, gr-blocks/python/blocks/qa_blocks_hier_block2.py
Two tests are skipped unnecessarily on OSX:
* `qa_fecapi_cc_buffer_overflow` is skipped because `qa_fecapi_cc` is a substring of its test name. Tightening the test regex fixes this.
* `qa_hier_block2` in gnuradio-runtime is skipped because it shares the same name as a test in gr-blocks. I've renamed the gr-blocks test to avoid the conflict.
After this change, we should be down to 10 skipped tests on OSX instead of 12.
CI tests.
Once the CI test runs are complete, we can verify that the correct number of tests executed.
=> CI: Avoid unnecessary test skips on OSX

gnuradio-runtime/python/gnuradio/gr_unittest.py, gnuradio-runtime/python/pmt/qa_pmt_to_python.py, gr-blocks/python/blocks/qa_file_metadata.py, gr-blocks/python/blocks/qa_file_source.py, gr-blocks/python/blocks/qa_multiply_matrix_xx.py, gr-blocks/python/blocks/qa_stream_demux.py, gr-blocks/python/blocks/qa_stream_mux.py, gr-blocks/python/blocks/qa_vector_insert.py, gr-digital/python/digital/qa_constellation_receiver.py, gr-digital/python/digital/qa_lfsr.py, gr-digital/python/digital/qa_ofdm_chanest_vcvc.py, gr-digital/python/digital/qa_ofdm_sync_sc_cfb.py, gr-digital/python/digital/qa_pfb_clock_sync.py, gr-digital/python/digital/qa_scrambler.py, gr-pdu/python/pdu/qa_tags_to_pdu.py, gr-pdu/python/pdu/qa_take_skip_to_pdu.py, gr-utils/blocktool/tests/test_blocktool.py
While looking into #5948, I noticed that the error message (`AssertionError: False is not true`) is unhelpful; `assertTrue` hides the details about the numbers that were compared.
Here I've changed that assertion to use `assertGreater` and also fixed many other instances where `assertTrue` or `assertFalse` were used where other alternatives would give more useful diagnostic information.
QA tests for various modules.
I verified that all the tests pass on my machine. (We'll see how things go in CI as well.) I also intentionally caused a few of the assertions to fail, to verify that the error messages are more helpful.
=> QA: Make assertions more specific

gr-blocks/lib/wavfile_sink_impl.cc, gr-blocks/lib/wavfile_source_impl.cc
The wavfile_sink and wavfile_source prints misleading error messages when eg. the existing WAV file is broken.
Description for `errno` error is printed and errors reported directly by `libsndfile` are ignored. The reason to use `errno` is likely because of `libsndfile` returns unhelpful error messages when the error is at the system IO level. This patch combines both approaches to get the best results.
I have manually tested (on my project):
* to create file in nonexisting directory
* to open non-wav file as wav
Bot returned expected error description.
=> gr-blocks: print correct error message for soundfile sf_open

gr-qtgui/grc/qtgui_range.block.yml, gr-qtgui/python/qtgui/__init__.py, gr-qtgui/python/qtgui/range.py.cmakein
In #5566, a message output port was added to the QT GUI Range widget. This caused two new bugs:
First, if the Range variable was used in the same expression as another variable, and that other variable was changed before the Range slider was first moved, then an exception would occur:
```
File "/home/argilo/prefix_311/lib/python3.10/site-packages/gnuradio/qtgui/range.py", line 204, in changed
self.notifyChanged(self.rangeType(val))
File "/home/argilo/prefix_311/lib/python3.10/site-packages/gnuradio/qtgui/range.py", line 308, in sliderChanged
self.notifyChanged(self.rangeType(value))
File "/home/argilo/prefix_311/lib/python3.10/site-packages/gnuradio/qtgui/range.py", line 140, in notifyChanged
self.__slot(value)
File "/home/argilo/epy_test.py", line 193, …
```
=> qtgui: Revert changes to Range widget

.packaging/conda_recipe/bld.bat, gr-analog/lib/agc3_cc_impl.cc, gr-analog/lib/agc3_cc_impl.h, gr-analog/python/analog/qa_agc.py
* Windows implementation had several bugs
* inverted "is this the first items" logic
* inverted "1/magnitude finite" logic
* allocations/deallocations every work()
* specifying alignment of std::vector header doesn't align data
* non-windows / GNU implementation had bug
* Variable-length arrays in C++ are GCC extension
* both versions had several bugs, both hard and perf
* thread-safety of setters of floating point numbers
* first-run work code's numerical output values depend on workload
size (but we're in output_multiple mode, so easy to fix)
* counter-productive cache thrashing to improve vectorization at the
expense of having VLA/runtime allocation
* unnecessary division in comparison
* AGC3 test on windows was disabled, which hid the above bugs
By removing one unnecessary hot-loop …
=> analog: fix agc3 on windows, logical bugs

gr-qtgui/python/qtgui/distanceradar.py
Unlike some other QT GUI widgets, the Distance Radar widget has no minimum size. As a result, it can be rendered with a height or width of zero, which causes the following exception:
```
File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_qt.py", line 455, in _draw_idle
self.draw()
File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_agg.py", line 436, in draw
self.figure.draw(self.renderer)
File "/usr/lib/python3/dist-packages/matplotlib/artist.py", line 73, in draw_wrapper
result = draw(artist, renderer, *args, **kwargs)
File "/usr/lib/python3/dist-packages/matplotlib/artist.py", line 50, in draw_wrapper
return draw(artist, renderer)
File "/usr/lib/python3/dist-packages/matplotlib/figure.py", line 2796, in draw
artists = …
```
=> qtgui: Set a minimum size for the Distance Radar widget

gr/include/gnuradio/tag.h, test/qa_tags.cc
This is a follow-up of #6252 and #6253 and provides the following SigMF-inspired definitions and some additional helper methods in `class tag_t` to be used in the context of processing stream tags, e.g.:
```cpp
using namespace gr;
tag_t testTag;
testTag.insert_or_assign(tag::SAMPLE_RATE(4.0f));
//testTag.insert_or_assign(tag::SAMPLE_RATE(5.0)); // type-mismatch -> won't compile
EXPECT_EQ(testTag.at(tag::SAMPLE_RATE), 4.0f);
EXPECT_EQ(tag::SAMPLE_RATE.shortKey(), "sample_rate");
EXPECT_TRUE(testTag.get(tag::SAMPLE_RATE).has_value()); // future: allows for monadic expressions
EXPECT_FALSE(testTag.get(tag::SIGNAL_NAME).has_value());
```
These tags are definitions only and the specific naming be changed if necessary.
These definitions should be replaced by `inlinse constexpr` once PMTF …
=> adding default stream-tag definitions to GR 4.0

gnuradio-runtime/apps/CMakeLists.txt, gnuradio-runtime/lib/CMakeLists.txt, gnuradio-runtime/lib/pmt/CMakeLists.txt, gr-analog/lib/CMakeLists.txt, gr-audio/lib/CMakeLists.txt, gr-blocks/lib/CMakeLists.txt, gr-channels/lib/CMakeLists.txt, gr-dtv/lib/CMakeLists.txt, gr-fec/python/fec/bindings/CMakeLists.txt, gr-fft/lib/CMakeLists.txt, gr-filter/lib/CMakeLists.txt, gr-iio/lib/CMakeLists.txt, gr-qtgui/lib/CMakeLists.txt, gr-uhd/examples/c++/CMakeLists.txt, gr-uhd/lib/CMakeLists.txt, gr-video-sdl/lib/CMakeLists.txt, gr-vocoder/lib/CMakeLists.txt, gr-wavelet/lib/CMakeLists.txt, gr-zeromq/lib/CMakeLists.txt, grc/core/generator/cpp_templates/CMakeLists.txt.mako
Declaring a library as `PUBLIC` in `target_link_libraries` tells downstream linkers of the target to also need to link to the `PUBLIC` libraries. This is necessary when the headers of those libraries are required by the public headers of the target library. There were some instances where linked libraries were declared `PUBLIC` but were not required to use the public headers, so they have been switched to `PRIVATE` declarations. This will allow OOT modules to reduce their linking and dependencies in some cases.
This could use some scrutiny from people more familiar with the various modules that are affected. I made these changes based purely on searching for every `target_link_libraries` call and then searching the public headers to see if the linked libraries were `#include`d somewhere. …
=> cmake: Switch suitable `PUBLIC` `target_link_libraries` to `PRIVATE`

gr-blocks/lib/CMakeLists.txt, gr-blocks/lib/probe_signal_impl.cc, gr-blocks/lib/probe_signal_impl.h
It appears that std::atomic does not work on all platforms. Switching to the mutex approach already sued by the vector version of this block avoids the problem.
(cherry picked from commit 08b3d35a776d5b83dd3373efe1e9c290a090b8a6)
Backport https://github.com/gnuradio/gnuradio/pull/6259
=> blocks: Use mutex instead of std::atomic for probe synchronization (backport to maint-3.10)

grc/gui/DrawingArea.py, grc/gui/canvas/connection.py
The connection flowgraph element previously kept a reference to the cairo context passed to the draw function in order to be able to use cairo's `in_stroke` function to determine if the mouse cursor was on the path of the curved connection line. As it turns out, this is dangerous because GTK is constantly destroying and creating new cairo contexts and surfaces.
This avoids keeping a reference to the cairo context by initializing a local cairo context with the connection class for the sole purpose of storing the curved path and calculating `in_stroke`. The local context and surface can be very basic because not much is needed for `in_stroke`, and the context can persist and just have its path replaced when it needs to be updated.
On Windows, resizing the GRC window (and particularly the …
=> grc: Fix cairo assertion failure by not storing reference to context

gr-uhd/examples/grc/rfnoc_duc_radio.grc, gr-uhd/grc/uhd_rfnoc_duc.block.yml, gr-uhd/grc/uhd_rfnoc_rx_streamer.block.yml, gr-uhd/grc/uhd_rfnoc_tx_streamer.block.yml, gr-uhd/include/gnuradio/uhd/rfnoc_graph.h, gr-uhd/lib/rfnoc_block.cc, gr-uhd/lib/rfnoc_graph_impl.cc, gr-uhd/python/uhd/bindings/docstrings/rfnoc_graph_pydoc_template.h, gr-uhd/python/uhd/bindings/rfnoc_graph_python.cc
```
Changes:
9caed287b (Martin Braun, 26 minutes ago)
uhd: rfnoc streamers: Allow specifying adapter IDs
Includes the following changes:
- Add a set_streamer_adapter_id() API call to rfnoc_graph. This sets an
adapter ID for later calls to connect().
- Amend the GRC bindings for the RX and TX streamers to allow specifying
the adapter ID. It will call rfnoc_graph::set_streamer_adapter_id() to
do so in the autogenerated Python code.
039fc47a9 (Martin Braun, 78 seconds ago)
uhd: rfnoc: Improve error message when block not found
When an RFNoC block is requested but not found, it now prints the exact 
block it was looking for in the exception string.
4e115903b (Martin Braun, 2 minutes ago) …
```
=> uhd: rfnoc streamers: Allow specifying adapter IDs

gr-uhd/grc/uhd_rfnoc_graph.block.yml
In GRC, there was an issue where you could select a clock/time source
for the RFNoC graph, but it was never passed on to the graph object.
This fixes the issue such that the correct device args are generated.
Default graph object:
I can now change the clock/time source as such:
If I do, it will look like this:
If I do that, the autogenerated Python now looks like this:
```py
##################################################
##################################################
self.rfnoc_graph = uhd_rfnoc_graph = uhd.rfnoc_graph(uhd.device_addr("type=x300,clock_source=external,time_source=external")))
self.samp_rate = samp_rate = 1e6
self.gain = gain = 0
self.freq = freq = 1e9
```
Using device args to control time/clock source is valid for all RFNoC devices, so calling `set_sync_source()` …
=> uhd: rfnoc: Generate correct Python when using clock/time source

gnuradio-runtime/lib/pmt/pmt_serialize.cc, gnuradio-runtime/python/pmt/qa_pmt.py
Prior to this change, C32 vectors were inadvertently serialized as (imag, real) on little-endian platforms and (real, imag) on big-endian platforms.
(cherry picked from commit 5ea0a3a63bad149829069419f0affa27ce31c141)
Backport https://github.com/gnuradio/gnuradio/pull/6307
=> runtime: Fix PMT serialization of C32 vectors (backport to maint-3.10)

gnuradio-runtime/lib/controlport/thrift/rpcpmtconverters_thrift.cc
(cherry picked from commit 2e09660c8b0b96df470c583a6febb00463d6b921)
Backport https://github.com/gnuradio/gnuradio/pull/6288
=> runtime: make logging in rpcpmtconverters_thift work with fmt v9 (backport to maint-3.10)

gr-uhd/python/uhd/bindings/python_bindings.cc
Without this declaration, function calls that require a time_spec_t argument must be provided with such an argument, even if there is a default argument.
For example, in the RFNoC DDC block, we couldn't call set_freq() as such:
```python
ddc_block.set_freq(0.0, 0)
```
It would produce the following error:
```
TypeError: set_freq(): incompatible function arguments. The following
argument types are supported:
1. (self: gnuradio.uhd.uhd_python.rfnoc_ddc,
freq: float,
chan: int,
time: gnuradio.uhd.uhd_python.time_spec_t = 0.0) -> float
```
Even though the argument `time` is optional, the default value of 0.0 is not able to satisfy the requirements. By adding the `py::implicitly_convertible` call, we declare float convertible to time spec, and the call above can proceed.
Signed-off-by: Martin …
=> uhd: Declare float to time_spec_t implicitly convertible (backport to maint-3.10)

gr-network/lib/CMakeLists.txt, gr-network/lib/asio/asio.hpp, gr-network/lib/socket_pdu_impl.cc, gr-network/lib/socket_pdu_impl.h, gr-network/lib/tcp_connection.cc, gr-network/lib/tcp_connection.h, gr-network/lib/tcp_sink_impl.cc, gr-network/lib/tcp_sink_impl.h, gr-network/lib/udp_sink_impl.cc, gr-network/lib/udp_sink_impl.h, gr-network/lib/udp_source_impl.cc, gr-network/lib/udp_source_impl.h
This makes boost::asio look identical to non-Boost asio within our block definitions.
Signed-off-by: japm48 <japm48gh@gmail.com>
Co-authored-by: Martin Braun <martin.braun@ettus.com>
(cherry picked from commit e12214590586fce4de040e1d49f7bef749141101)
Backport https://github.com/gnuradio/gnuradio/pull/6260
=> network: Move boost::asio namespace to asio (backport to maint-3.10)

.github/workflows/make-test.yml
GitHub Actions has a default timeout of 360 minutes. The formatting and Doxygen jobs only take about two minutes each, so we should lower the timeout to ensure that these jobs fail in a timely manner if a hang occurs.
(cherry picked from commit 81987d0a9fae566494ed74673c125dff4db9d752)
Backport https://github.com/gnuradio/gnuradio/pull/6311
=> CI: Lower timeouts on formatting & Doxygen jobs (backport to maint-3.10)

gnuradio-runtime/python/gnuradio/gr_unittest.py, gnuradio-runtime/python/pmt/qa_pmt_to_python.py, gr-blocks/python/blocks/qa_file_metadata.py, gr-blocks/python/blocks/qa_file_source.py, gr-blocks/python/blocks/qa_multiply_matrix_xx.py, gr-blocks/python/blocks/qa_stream_demux.py, gr-blocks/python/blocks/qa_stream_mux.py, gr-blocks/python/blocks/qa_vector_insert.py, gr-digital/python/digital/qa_constellation_receiver.py, gr-digital/python/digital/qa_lfsr.py, gr-digital/python/digital/qa_ofdm_chanest_vcvc.py, gr-digital/python/digital/qa_ofdm_sync_sc_cfb.py, gr-digital/python/digital/qa_pfb_clock_sync.py, gr-digital/python/digital/qa_scrambler.py, gr-pdu/python/pdu/qa_tags_to_pdu.py, gr-pdu/python/pdu/qa_take_skip_to_pdu.py, gr-utils/blocktool/tests/test_blocktool.py
This will result in more detailed error messages, making it easier to diagnose test failures.
(cherry picked from commit 331f081c12e0b62123b8ac3c205e0686de7144ee)
Backport https://github.com/gnuradio/gnuradio/pull/6335
=> QA: Make assertions more specific (backport to maint-3.10)

gr-digital/lib/header_buffer.cc
The add_field16, add_field32, and add_field64 functions have undefined behaviour because they copy the machine representation of multi-byte integers directly into the output buffer. As a result, they do not produce the correct output on big-endian systems. Switching to bit shifts will ensure consistent operation across platforms.
(cherry picked from commit 6b222cac12df55f4eaf7df2f320f4e2e8f81d8b9)
Backport #6308
=> digital: Make the add_field functions portable (backport to maint-3.10)

cmake/Modules/GrPython.cmake
The current 20-bit hash is prone to collisions. Using the full hash avoids that problem.
(cherry picked from commit f46e521a4119f55bf6a27e5b5f8915e55dc3b769)
Backport https://github.com/gnuradio/gnuradio/pull/6318
=> cmake: Ensure that target names are unique (backport to maint-3.10)

.github/workflows/make-test.yml, gr-blocks/lib/CMakeLists.txt
The following warning occurs when building `file_source_impl.cc`:
```
[ 29%] Building CXX object gr-blocks/lib/CMakeFiles/gnuradio-blocks.dir/file_source_impl.cc.o
cc1plus: warning: /build/gr-blocks/lib/CMakeFiles/gnuradio-blocks.dir/cmake_pch.hxx.gch: not used because `_FILE_OFFSET_BITS' is defined [-Winvalid-pch]
```
This can be fixed by disabling precompiled headers for this file.
File Source
I verified that it's still possible to open a 5 GB file on 32-bit Linux.
=> blocks: Fix invalid PCH warning

gr-blocks/lib/wavfile_sink_impl.cc, gr-blocks/lib/wavfile_source_impl.cc
Signed-off-by: Jiří Pinkava <j-pi@seznam.cz>
(cherry picked from commit c11667ef6ebbe528289f528bb303d4668732e942)
Backport https://github.com/gnuradio/gnuradio/pull/6209
=> gr-blocks: print correct error message for soundfile sf_open (backport to maint-3.10)

.github/workflows/make-test.yml, .github/workflows/pkg-debian.yml, .github/workflows/pkg-fedora.yml, gnuradio-runtime/include/gnuradio/rpcserver_thrift.h
Fedora builds have several warnings due to `std::unary_function`, which was deprecated in C++11 and removed in C++17. As was done in #4159, I've replaced those with `std::function`.
The warnings are:
```
[ 21%] Building CXX object gnuradio-runtime/lib/CMakeFiles/gnuradio-runtime.dir/controlport/thrift/rpcserver_thrift.cc.o
In file included from /__w/gnuradio/gnuradio/gnuradio-runtime/lib/controlport/thrift/rpcserver_thrift.cc:12:
/__w/gnuradio/gnuradio/gnuradio-runtime/lib/../include/gnuradio/rpcserver_thrift.h:114:32: warning: 'template<class _Arg, class _Result> struct std::unary_function' is deprecated [-Wdeprecated-declarations]
114 |     struct set_f : public std::unary_function<T, void> {
|                                ^~~~~~~~~~~~~~
In file included from …
```
=> runtime: Fix deprecation warnings

grc/core/FlowGraph.py
While working on #6342, I noticed the following bug:
When opening a GRC file, if any invalid connection is present, then all subsequent valid connections will fail to be loaded. This occurs because the loop that processes connections exits on the first error.
For example, the following flowgraph was generated in GNU Radio 3.10.4.0, which has a message output in the QT GUI Range block. When attempting to load it in another version of GNU Radio which lacks this port, all of the connections vanish:
It appears that this bug was introduced in GNU Radio 3.8, in the following commit: dbf58fa349002d94c26883b130ed8864ead79ea6
Moving the `try` back inside the loop allows the valid connections to be loaded again:
It would seem that the motivation behind dbf58fa349002d94c26883b130ed8864ead79ea6 was …
=> grc: Continue processing connections after an invalid one occurs

gr-uhd/python/uhd/bindings/python_bindings.cc, gr-uhd/python/uhd/bindings/usrp_block_python.cc
This Python function was accidentally broken when converting from SWIG
to Pybind11. In 9c64b6d, uhd.find() was created as a replacement, but
that leaves uhd.find_devices() in a broken state.
This performes two changes:
- The binding for uhd.find() is moved into python_bindings.cc from
usrp_block_python.cc.
- The Python version of find_devices() now correctly uses uhd.find()
under the hood.
- The SWIG version differentiated between Python- and C++-versions of
device_addr_t and remapped that, which we can skip with Pybind11
Fixes https://github.com/gnuradio/gnuradio/issues/6313
Tested locally with USRPs attached.
```py
from gnuradio import uhd
x = uhd.find_devices("")
print(x)
```
=> uhd: Re-enable uhd.find_devices()

grc/grc.yml.in, grc/gui/Config.py, grc/meson.build, meson.build, meson_options.txt
OOT's build out of tree are not found by grc.
To find these blocks a path entry either in
etc/gnuradio/conf.d/grc.yml ( global setting )
or in ~/.gnuradio/config.yml(user specific ) is necessary.
At the moment the hint points to config.conf wich is only valid for 3.0.
In addition I added an configuration option to set the OOT block path during installation. An empty string keeps the old behaviour.
Applied this fix and had a look at 
etc/gnuradio/conf.d/grc.yml
=> config files: fix misleading config hints

.packaging/conda_recipe/bld.bat, gr-analog/lib/agc3_cc_impl.cc, gr-analog/lib/agc3_cc_impl.h, gr-analog/python/analog/qa_agc.py
* Windows implementation had several bugs
* inverted "is this the first items" logic
* inverted "1/magnitude finite" logic
* allocations/deallocations every work()
* specifying alignment of std::vector header doesn't align data
* non-windows / GNU implementation had bug
* Variable-length arrays in C++ are GCC extension
* both versions had several bugs, both hard and perf
* thread-safety of setters of floating point numbers
* first-run work code's numerical output values depend on workload size (but we're in output_multiple mode, so easy to fix)
* counter-productive cache thrashing to improve vectorization at the expense of having VLA/runtime allocation
* unnecessary division in comparison
* AGC3 test on windows was disabled, which hid the above bugs
By removing one unnecessary hot-loop …
=> analog: fix agc3 on windows, logical bugs (backport to maint-3.10)

gnuradio-runtime/apps/CMakeLists.txt, gnuradio-runtime/lib/CMakeLists.txt, gnuradio-runtime/lib/pmt/CMakeLists.txt, gr-analog/lib/CMakeLists.txt, gr-audio/lib/CMakeLists.txt, gr-blocks/lib/CMakeLists.txt, gr-channels/lib/CMakeLists.txt, gr-dtv/lib/CMakeLists.txt, gr-fec/python/fec/bindings/CMakeLists.txt, gr-fft/lib/CMakeLists.txt, gr-filter/lib/CMakeLists.txt, gr-iio/lib/CMakeLists.txt, gr-qtgui/lib/CMakeLists.txt, gr-uhd/examples/c++/CMakeLists.txt, gr-uhd/lib/CMakeLists.txt, gr-video-sdl/lib/CMakeLists.txt, gr-vocoder/lib/CMakeLists.txt, gr-wavelet/lib/CMakeLists.txt, gr-zeromq/lib/CMakeLists.txt, grc/core/generator/cpp_templates/CMakeLists.txt.mako
Declaring a library as PUBLIC in target_link_libraries tells downstream linkers of the target to also need to link to the PUBLIC libraries. This is necessary when the headers of those libraries are required by the public headers of the target library. There were some instances where linked libraries were declared PUBLIC but were not required to use the public headers, so they have been switched to PRIVATE declarations. This will allow OOT modules to reduce their linking and dependencies in some cases.
(cherry picked from commit 501da230e07bee7cb78abd6a76fdca5a155419fa)
Backport https://github.com/gnuradio/gnuradio/pull/6178
=> cmake: Switch suitable PUBLIC target_link_libraries to PRIVATE (backport to maint-3.10)

utils/modtool/newmod/meson.build
GR 4.0 already uses C++20, this fixes it's use also for the modtool and OOT modules. 
See also issue #6400.
OOT builds using GR 4.0
see CI/CD checks.
N.B. does not include OOT module creation (yet).
=> 4.0: fixed modtool using C++17 -> C++20

gr-uhd/python/uhd/bindings/python_bindings.cc, gr-uhd/python/uhd/bindings/usrp_block_python.cc
This Python function was accidentally broken when converting from SWIG to Pybind11. In 9c64b6d, uhd.find() was created as a replacement, but that leaves uhd.find_devices() in a broken state.
This performes two changes:
- The binding for uhd.find() is moved into python_bindings.cc from usrp_block_python.cc.
- The Python version of find_devices() now correctly uses uhd.find() under the hood.
- The SWIG version differentiated between Python- and C++-versions of device_addr_t and remapped that, which we can skip with Pybind11
(cherry picked from commit ab2ee30facad90255ddd2a4ac5850c322b408c87)
Backport https://github.com/gnuradio/gnuradio/pull/6353
=> uhd: Re-enable uhd.find_devices() (backport to maint-3.10)

.github/workflows/make-test.yml, .github/workflows/pkg-debian.yml, .github/workflows/pkg-fedora.yml, gnuradio-runtime/include/gnuradio/rpcserver_thrift.h, gr-blocks/lib/CMakeLists.txt
Backport https://github.com/gnuradio/gnuradio/pull/6366
Backport https://github.com/gnuradio/gnuradio/pull/6365
Backported these together since they both remove compiler flags for CI.
=> Fix invalid pch and deprecation warnings (backport to maint-3.10)

gr-audio/include/gnuradio/audio/osx_impl.h, gr-audio/lib/osx/osx_sink.cc, gr-audio/lib/osx/osx_sink.h, gr-audio/lib/osx/osx_source.cc, gr-audio/lib/osx/osx_source.h
A change in OSX's audio API prompted the addition of some conditionally compiled code in 28d1a3fab5e2ccb593df9cd3a05b3911be326d9e. The new API was added in OSX 10.4 (released in 2005) and the old API was removed in OSX 10.7 (released in 2011). Enough time has passed that I think we should remove support for the old API.
* Audio Source (OSX)
* Audio Sink (OSX)
None yet.
=> audio: Remove support for OSX 10.3 and earlier

subprojects/pmt.wrap
Set pmt git pointer in meson.wrap to just prior to variant version, as that hasn't been updated yet
https://github.com/gnuradio/pmt/pull/68
anything with a pmt
CI should be sufficient
=> 4.0: meson: set pmt pointer pre-variant pmt

gr-uhd/lib/rfnoc_graph_impl.cc, gr-uhd/lib/rfnoc_window_impl.h
OSX CI shows several warnings about inconsistent use of the `override` specifier. Here I've added the missing specifiers.
```
[1530/1760] Building CXX object gr-uhd/lib/CMakeFiles/gnuradio-uhd.dir/rfnoc_window_impl.cc.o
In file included from $SRC_DIR/gr-uhd/lib/rfnoc_window_impl.cc:13:
$SRC_DIR/gr-uhd/lib/rfnoc_window_impl.h:25:10: warning: 'set_coefficients' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
void set_coefficients(const std::vector<float>& coeffs, const size_t chan);
^
$SRC_DIR/gr-uhd/lib/../include/gnuradio/uhd/rfnoc_window.h:43:18: note: overridden virtual function is here
virtual void set_coefficients(const std::vector<float>& coeffs,
^
In file included from $SRC_DIR/gr-uhd/lib/rfnoc_window_impl.cc:13: …
```
=> uhd: Fix inconsistent override warnings

gnuradio-runtime/include/gnuradio/io_signature.h, gnuradio-runtime/lib/io_signature.cc, gnuradio-runtime/python/gnuradio/gr/bindings/io_signature_python.cc
(cherry picked from commit 2bab99dbb0698d30212f5c272d78b93f95aec047)
Backport https://github.com/gnuradio/gnuradio/pull/5647
Note: this is test code that is turned on using `#define FORCE_SINGLE_MAPPED`. No impact when turned off, so backporting to keep the branches sync'd.
=> runtime: expose mechanism for testing host_buffer (backport to maint-3.10)

gnuradio-runtime/lib/controlport/thrift/gnuradio.thrift
Conda Linux builds show the following warning:
`[WARNING:$SRC_DIR/gnuradio-runtime/lib/controlport/thrift/gnuradio.thrift:35] The "byte" type is a compatibility alias for "i8". Use "i8" to emphasize the signedness of this type.`
The `i8` type was added in Thrift 0.10.0 (released in 2017) and the `byte` type was deprecated at the same time. Since GNU Radio 3.10 requires recent dependencies, I think it's reasonable to require Thrift >= 0.10.0. Ubuntu 20.04 has Thrift 0.13.0.
ControlPort
None yet.
=> runtime: Fix Thrift deprecation warning

gr-digital/lib/ofdm_frame_equalizer_vcvc_impl.cc
Changes gr::digital::ofdm_frame_equalizer_vcvc block to pass the tags to the equalizer that it aggregates. The gr::digital::ofdm_equalizer_base interface allows passing the tags vector to equalize() but in current implementation the default argument is used (empty vector).
Fixes #6422
gr::digital::ofdm_frame_equalizer_vcvc
- run tests locally (v3.10.1.1)
- tested with a custom equalizer that uses the tags in an OOT (v3.10.1.1)
=> digital: Pass tags vector to OFDM equalizer

docs/usage-manual/(exported from wiki) Polymorphic Types (PMTs).txt, gnuradio-runtime/include/pmt/pmt.h, gnuradio-runtime/lib/block_registry.cc, gnuradio-runtime/lib/pmt/pmt.cc, gnuradio-runtime/lib/pmt/pmt_int.h, gnuradio-runtime/lib/pmt/qa_pmt_prims.cc, gnuradio-runtime/python/pmt/__init__.py, gr-digital/include/gnuradio/digital/constellation.h, gr-digital/lib/constellation_receiver_cb_impl.cc, gr-digital/python/digital/bindings/constellation_python.cc
C++17 provides `std::any`, and we had c++17 as a requirement in the runtime long enough to push that down to OOTs (GR 3.10 was a bit soon for that)
The main thing that stopped this in 3.10 was pygccml < 2.0 did not support std:;any
https://github.com/gnuradio/gnuradio/issues/5891
https://github.com/gnuradio/gnuradio/pull/5218
https://github.com/gnuradio/gnuradio/pull/5311
Anything using PMTs
=> global: replace boost::any with std::any

gr-uhd/grc/gen_uhd_usrp_blocks.py, gr-uhd/lib/usrp_source_impl.cc, gr-uhd/lib/usrp_source_impl.h
Signed-off-by: ph1t0 <fito@ektocomms.space>
Overflows occurs when the host does not consume data fast enough. 
It is very useful to have and explicit message (not only a log) from the `usrp_source` block every time an overflow occurs. 
This feature allows the user to properly handle the event.
gr-uhd's usrp_source block.
I've compiled and installed gnuradio main branch with the changes proposed. 
Then I've executed the following piece of code:
```python
#!/usr/bin/env python3
from gnuradio import blocks, gr, uhd
class OverflowTest(gr.top_block):
def __init__(self):
gr.top_block.__init__(self, self.__class__.__name__, catch_exceptions=True)
self.sample_rate = 1e6
self.uhd_source = uhd.usrp_source("", uhd.stream_args(cpu_format="fc32", channels=range(1))) …
```
=> uhd: add async msgs port to usrp_source block and publish overflows

grc/blocks/snippet.block.yml, grc/core/generator/flow_graph.py.mako
There are situations where snippets need to be inserted before block initialization, such as when 
a block constructor makes contact with an external server, it might be handy to initialize the server
or check whether it is ready prior to calling the flowgraph init function that calls the block constructor
The problem with the current construct is snippets can only be injected after the flowgraph is initialized,
since they use `self` as a reference to the flowgraph object.  There is probably a better way to do this
but the easy solution is to pass `None` as what will become self, and snippets that are inserted before
main are not able to make calls to `self`
Notes:
1. Main Before Init is placed second on the list, so Main After Init is the default
I'm wondering if it would be more useful …
=> grc: snippets before init is called

gr-fec/python/fec/polar/channel_construction_awgn.py
Type in `upper_convolve` was generating /0 error, and doesn't look like the intended code. Note that I don't know anything about polar codes!
Fixes #5430 
None
=> fec: fix typo in upper_convolve()

utils/blockbuilder/templates/blockname.cc.j2, utils/modtool/newmod/meson.build
Couple of things that were missed in the merge of the variant based PMT
Fixes #6453
related to: https://github.com/gnuradio/gnuradio/pull/6398
non-templated blocks with automatically generated getter functions using enums
Tested on OOT module with enum parameter
=> 4.0: Couple of pmtv lib merge cleanups

grc/core/FlowGraph.py
See related [issue](https://github.com/gnuradio/gnuradio/issues/6444)
An empty snippet prior to this PR will cause an invalid rendered flowgraph 
Fixes #6444 
GRC files with snippets
empty and non-empty snippet. 
- [N/A] I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.
=> grc: add a pass if snippet is empty

gr-digital/lib/ofdm_frame_equalizer_vcvc_impl.cc
Change gr::digital::ofdm_frame_equalizer_vcvc block to pass the tags to the equalizer that it aggregates. The gr::digital::ofdm_equalizer_base interface allows passing the tags vector to equalize() but in current implementation the default argument is used (empty vector).
Backport https://github.com/gnuradio/gnuradio/pull/6424
=> digital: Pass tags vector to OFDM equalizer (backport to maint-3.10)

gnuradio-runtime/lib/block.cc, gnuradio-runtime/lib/flat_flowgraph.cc
Make block buffer size customizable using the environment variable `GR_CONF_DEFAULT_BUFFER_SIZE`
Affects maximum allowable buffer size for all blocks.
I was testing a fft filter with a lot of taps (>100) which required a huge buffer size, and gnuradio complained. Changing the environment variable `GR_CONF_DEFAULT_BUFFER_SIZE` in previous versions of gnuradio made this possible, and now it is possible again after this change.
=> runtime: (Re)make block buffer size customizable

gr-iio/lib/CMakeLists.txt
In #6178, a number of unnecessary public linkages were removed, but this one was needed.
Fixes #6481
iio
=> iio: cmake: revert libad9361 linkage back to public

gr-uhd/examples/grc/rfnoc_addsub.grc, gr-uhd/grc/CMakeLists.txt, gr-uhd/grc/uhd_rfnoc_addsub.block.yml, gr-uhd/grc/uhd_rfnoc_graph.block.yml
Add support for the Add-Subtract Block for rfnoc
Adds support for addsub block
Fixes typo in graph block, I see there is another PR that has that fix, but it appears stale: https://github.com/gnuradio/gnuradio/pull/6461
Ran example on n300 with fpga including the add-sub block, the example is a simple two waveforms in, take the addition and subtraction, and then display both signals alongside the original signals. I confirmed on the output graphs that the resultant signals are indeed added or subtracted:
=> rfnoc: new addsub block, fix minor typo

gr-network/lib/udp_source_impl.cc
bytes_read, the result of asio::ip::udp::socket::receive_from(), was an int, but the function returns size_t. This resulted in an overflow of the int and a subsequent comparison.
Since the int result of buffer space_available() should never be negative, it is safe to cast the result to size_t. If that result is ever changed to something larger than size_t, this could cause trouble, but that seems unlikely.
Fixes #6485 
UDP Source
Ran random data into `mbuffer | nc` to the source's UDP port at various rates and verified data showed up on GUI sinks. This crashed or produced bad data before the change, and works after the change.
=> network: change type of bytes_read UDP Source

gr-network/lib/udp_source_impl.cc
bytes_read, the result of asio::ip::udp::socket::receive_from(), was an int, but the function returns size_t. This resulted in an overflow of the int and a subsequent comparison.
Since the int result of buffer space_available() should never be negative, it is safe to cast the result to size_t. If that result is ever changed to something larger than size_t, this could cause trouble, but that seems unlikely.
(cherry picked from commit e1a7a9a5e9201ef54cc2cf0275a8e32a49d7dc22)
Backport #6488
=> network: change type of bytes_read UDP Source (backport to maint-3.10)

gr-soapy/lib/source_impl.cc, gr-soapy/lib/source_impl.h
https://github.com/gnuradio/gnuradio/commit/3eea1057c53842476f809a62499ee6b8dc080d82 causes the gr-soapy block to add the rx_freq tag when set_frequency() is called with a name parameter.
However, gr-soapy source's cmd port handler calls set_frequency() without name, so add_tag_ is not set and the rx_freq tag is not added. This patch causes rx_freq to be added for both versions of set_frequency().
Signed-off-by: Josh Bailey <josh@vandervecken.com>
=> soapy: freq message on gr-soapy source block cmd port adds rx_freq tag

gr-fec/lib/tagged_decoder_impl.cc
This fixes a bug in the calculation of the frame size used by the tagged decoder that affects the CC decoder in terminated mode.
Currently, tagged_decoder calls the `set_frame_size()` method of the decoder with a size computed as the input size multiplied by the rate.
In the cc_decoder, the frame_size parameter of the `set_frame_size()` method is used to calculate and set `d_veclen`. The value of `d_veclen` is used to determine how many forward steps (butterflies) the Viterbi algorithm should be run. The number of input items that are read in `d_veclen` forward steps is `d_veclen * d_rate` (note that `d_rate` is actually the inverse of the rate; typically, `d_rate == 2`). Therefore, the size of the input buffer should be as large as this value, and in most cases it should be equal, …
=> fec: fix tagged decoder frame size for CC_TERMINATED

grc/gui/Dialogs.py
Signed-off-by: R-ohit-B-isht <rbtunes0@gmail.com>
In default Ubuntu configurations the GTK dialogs are forcibly locked to the center of their parent window. This means that if someone opens the properties on an Embedded Python Block, clicks "Open in Editor", and then clicks anywhere else other than the Choose Editor dialog it can end up hidden behind the Embedded Python Block properties dialog. This results it it being impossible to close the dialog, or even GRC, as all interactions with the lower layers are prevented while the Choose Editor dialog is open.
Fixes #5151
grc/gui/Dialogs.py line-179,180
Yes
=> grc: fix Choose Editor menu needs to stay above parent dialog #5151

gr-pdu/CMakeLists.txt
Not required:
e36f2fab5 ("pdu: Remove unused dependencies", 2022-06-01)
Signed-off-by: Chris Mayo <aklhfex@gmail.com>
Build 3.10.5.0 with this patch.
=> pdu: Don't enable blocks and filter

gr-qtgui/lib/displayform.cc, gr-qtgui/lib/eyedisplaysform.cc, gr-qtgui/lib/numberdisplayform.cc
When middle click in a QT Instrumentation sink plot (Time or Frequency) is pressed and select save a save file dialog appear. We can give the file a name and navigate to the desired directory. The problem is that there is no save button, but a disabled open button instead. 
Added a save  option in place of open.
Fixes #5991 
gr-qtgui/lib/displayform.cc - Line 303-324
gr-qtgui/lib/eyedisplaysform.cc - Line 339-360
gr-qtgui/lib/numberdisplayform.cc - Line 185-207
Yes
=> qtgui: fix instrumentation sink save dialog

gr-digital/python/digital/gfsk.py
Remove print statement that used a non-existant `self._mu`. There are other places that could use cleanup, e.g., the argument parsing and the existance of a default for this value. This is the mimimal fix to get rid of the error reported in #6517.
Fixes #6517 
GFSK Mod
=> digital: remove reference to nonexistant self._mu in gfsk.py

gnuradio-runtime/lib/pagesize.cc
Windows users shouldn't be faced with an error when determining the page size – adressing that.
- removed unused prefs include
- moved pagesize determination into separate function, to reduce the ugliness of the #ifdefs
- More specific logging
Fixes #6500
runtime
Here's the catch – the usual ctest suite runs through fine, but I don't have a Windows machine to test this with.
=> runtime: getpagesize for windows

grc/blocks/options.block.yml, grc/core/generator/flow_graph.py.mako
In ada1f1c168 "from PyQt5 import Qt" was moved from individual yml files to the Python flowgraph template. This line also existed in the GRC Options block yml, resulting in the line being emitted twice.
This commit removes that duplicate code, and also moves several imports not related to options from the Options block to the template.
Built-in Option block, Python flowgraph mako template
=> grc: remove duplicate import, move imports to template code

gr-vocoder/grc/vocoder_codec2_decode_ps.block.yml, gr-vocoder/grc/vocoder_codec2_encode_sp.block.yml, gr-vocoder/grc/vocoder_freedv_rx_ss.block.yml, gr-vocoder/grc/vocoder_freedv_tx_ss.block.yml, gr-vocoder/include/gnuradio/vocoder/codec2.h, gr-vocoder/include/gnuradio/vocoder/freedv_api.h, gr-vocoder/python/vocoder/bindings/codec2_python.cc, gr-vocoder/python/vocoder/bindings/freedv_api_python.cc
Use newer modes from Codec2 and FreeDV as enums.
For a while the FreeDV and Codec2 blocks in gnuradio-companion do
not list all available modes. This updates the list.
This adds Codec2 and FreeDV mode enum names for use in C++,
Python and grc for newer modes found in libcodec2 when building
gr-vocoder.
Also, this sets the mode parameters using the enum dtype - so that there is
no longer chatter about unsupported options when starting gnuradio-companion.
gr-vocoder: Codec2 and FreeDV blocks get a more complete list of modes
available in libcodec2.
This patch is prepared in response to a user, and hopefully will get
in to Debian Bookworm.
These changes work for me when tested locally.
=> update codec2 mode enums

gr-blocks/grc/blocks.tree.yml, gr-blocks/grc/blocks_throttle.block.yml, gr-blocks/grc/blocks_trickling_throttle.block.yml, gr-blocks/include/gnuradio/blocks/throttle.h, gr-blocks/lib/throttle_impl.cc, gr-blocks/lib/throttle_impl.h, gr-blocks/python/blocks/bindings/throttle_python.cc, gr-blocks/python/blocks/qa_throttle.py
This should reduce the amount of chunkiness of signal  processing if used.
Users can now use throttle and get regular, because smaller, item chunks even if (sample rate) << buffer size.
This works now, without the user waiting half an hour for the first message debug output:
To avoid surprise, this is an optional argument defaulting to previous behaviour (i.e., API and ABI compatible and backportable).
gr::blocks::throttle
Added a test with an infinite sample source, a throttle at a rate of 50, and a max chunk size of 10, stopping the flowgraph after 0.5 s; without the chunkification, this should lead to an output of buffer_size / 2 items after waiting for buffer_size/2/50 (s, so typically 4096 samples  after 40s or so), with, this should lead to 20 or 30 items.
=> Trickle throttle

gr-soapy/lib/source_impl.cc, gr-soapy/lib/source_impl.h
https://github.com/gnuradio/gnuradio/commit/3eea1057c53842476f809a62499ee6b8dc080d82 causes the gr-soapy block to add the rx_freq tag when set_frequency() is called with a name parameter.
However, gr-soapy source's cmd port handler calls set_frequency() without name, so add_tag_ is not set and the rx_freq tag is not added. This patch causes rx_freq to be added for both versions of set_frequency().
(cherry picked from commit 106e66f5bcb76c6995bc4a86d7a9cbeb9ae2a5cb)
Backport https://github.com/gnuradio/gnuradio/pull/6492
=> soapy: allow freq message on gr-soapy source block cmd port to add rx_freq tag (backport to maint-3.10)

gr-fec/lib/tagged_decoder_impl.cc
This fixes a bug in the calculation of the frame size used by the tagged decoder that affects the CC decoder in terminated mode.
Currently, tagged_decoder calls the set_frame_size() method of the decoder with a size computed as the input size multiplied by the rate.
In the cc_decoder, the frame_size parameter of the set_frame_size() method is used to calculate and set d_veclen. The value of d_veclen is used to determine how many forward steps (butterflies) the Viterbi algorithm should be run. The number of input items that are read in d_veclen forward steps is d_veclen * d_rate (note that d_rate is actually the inverse of the rate; typically, d_rate == 2). Therefore, the size of the input buffer should be as large as this value, and in most cases it should be equal, because we want the …
=> fec: fix tagged decoder frame size for CC_TERMINATED (backport to maint-3.10)

grc/gui/FileDialogs.py
(cherry picked from commit 515560b3ed7573635b7b0c4a2637b40e18a6d89b)
Backport https://github.com/gnuradio/gnuradio/pull/6479
=> grc: Fix Duplicate All_files filter entry in save screenshot dialog (backport to maint-3.10)

grc/gui/Dialogs.py
(cherry picked from commit aae66983ebf84bd751186a3f3d56d2ae82c39d7f)
Backport https://github.com/gnuradio/gnuradio/pull/6491
=> grc: fix Choose Editor menu needs to stay above parent dialog (backport to maint-3.10)

gr-iio/lib/fmcomms2_source_impl.cc
set_gain_mode sets the gain value always to manual instead to the new value
(cherry picked from commit 46df5d775dd7e684ca64a6cbe159b7de21d21c48)
Backport Fixes #6401
=> gr-iio: set_gain_mode does not set the gain paramter correctly (backport to maint-3.10)

gnuradio-runtime/gnuradio-runtime.conf.in, gnuradio-runtime/lib/pagesize.cc
The default log level in the code was previously changed to "info" but an installed conf file overrode it to be "debug". Also change the pagesize notice to debug instead of info.
Discussion in #6544 
Runtime
=> runtime: change default log level in conf file to info

grc/core/generator/flow_graph.py.mako
Backport https://github.com/gnuradio/gnuradio/pull/6509
=> GRC: Remove bare 'except:' from Mako template (backport to maint-3.10)

gr-pdu/CMakeLists.txt
Backport https://github.com/gnuradio/gnuradio/pull/6450
=> pdu: Don't enable blocks and filter (backport to maint-3.10)

gr-qtgui/lib/HistogramDisplayPlot.cc
when the data range is very small, the leftmost bin can be too narrow, which can cause some data points to fall outside of the histogram.
Fixes #6494 
gr-qtgui/lib/HistogramDisplayPlot.cc: line no. 192-198
=> qtgui: fix QT GUI Histogram Sink produces implausible results #6494

gr-filter/lib/pfb_arb_resampler.cc, gr-filter/lib/pfb_synthesizer_ccf_impl.cc
This bug was creating a zero-length vector which was being passed to fir_filter_with_buffer_ccf. A zero-length vector makes no sense for that block, and on systems with certain debug settings an out-of-range copy (of zero length) was detected, causing a crash.
Fixes #6547 
PFB Synthesizer
Was unable to cause the reported crash on any systems I have.
Placing breakpoints in `set_taps()` showed that the correct vector was being passed after the change.
=> filter: fix reversed arguments in vector initializer

gr-qtgui/grc/qtgui_eye_sink_x.block.yml, gr-qtgui/grc/qtgui_freq_sink_x.block.yml, gr-qtgui/grc/qtgui_sink_x.block.yml, gr-qtgui/grc/qtgui_time_sink_x.block.yml, gr-qtgui/grc/qtgui_time_sink_x.block.yml.py, gr-qtgui/grc/qtgui_waterfall_sink_x.block.yml
Removed unused imported firdes modules that seem to be copied in from the python yaml template genarator file.
Fixes https://github.com/gnuradio/gnuradio/issues/6507
gr-qtgui/grc/qtgui_eye_sink_x.block.yml
gr-qtgui/grc/qtgui_freq_sink_x.block.yml
gr-qtgui/grc/qtgui_sink_x.block.yml
gr-qtgui/grc/qtgui_time_sink_x.block.yml
gr-qtgui/grc/qtgui_waterfall_sink_x.block.yml
gr-qtgui/grc/qtgui_time_sink_x.block.yml.py
Tested all yaml files in validator to ensure no syntax errors and also reviewed all the files to make sure the libraries that were removed were not being used.
=> qtgui: removed imported firdes from yml files

gr-utils/modtool/templates/templates.py
The default templates when doing an interp or decim python block left out the necessary keyword for the interp/decim argument
Also, there was an indent error with the block implementation code
=> modtool: add keywords for interp/decim py blocks

gr-fec/lib/async_decoder_impl.cc, gr-fec/lib/async_decoder_impl.h
This fixes a few bugs and shortcomings in `async_decoder` and refactors it to reduce code duplication by merging the `decode_unpacked()` and `decoded_packed()` functions into a single `decode()` function.
The problems solved are the following:
- `decode_packed()` wasn't considering the `diff` (Viterbi tail) properly, unlike `decode_unpacked()`. This caused undefined behaviour when working in packed output mode with the Viterbi decoder in terminated mode. Occasionally this would cause bit errors in the last bits of a packet. See #6445 for a very similar problem affecting `tagged_decoder`.
- `decode_packed()` didn't support multiple blocks for fixed-size decoders (unlike `decode_unpacked()`).
- In both `decode_unpacked()` and `decode_packed()`, the input conversion to `uint8_t` could …
=> fec: fix some bugs and refactor async_decoder

gr-qtgui/grc/qtgui_eye_sink_x.block.yml, gr-qtgui/grc/qtgui_freq_sink_x.block.yml, gr-qtgui/grc/qtgui_sink_x.block.yml, gr-qtgui/grc/qtgui_time_sink_x.block.yml, gr-qtgui/grc/qtgui_time_sink_x.block.yml.py, gr-qtgui/grc/qtgui_waterfall_sink_x.block.yml
Backport https://github.com/gnuradio/gnuradio/pull/6524
=> gtgui: removed imported firdes from yml and pytemplate (backport to maint-3.10)

gr-blocks/grc/blocks_delay.block.yml
Give the delay block the ability to hide the `dly` message port in grc
Ideally, a block with single in, single out and hidden message port should be able to be bypassed, but that is a separate issue
after:
delay block
Tried in GRC
=> blocks: delay hide message port optionally in grc

gr-zeromq/lib/pull_source_impl.cc, gr-zeromq/lib/req_source_impl.cc, gr-zeromq/lib/sub_source_impl.cc
This modifies the policy that the ZMQ stream sources (ZMQ PULL Source, ZMQ REQ Source and ZMQ SUB Source) use to decide when to wait for a new ZMQ message or when to return immediately from work().
Currently, the work() function either:
* Already has enough data from a previous message to fill all the output buffer, and so it returns without waiting for more messages.
* If there is not enough data to fill all the output buffer, then the buffer is partially filled with all the data available and the function waits to receive a new ZMQ message (using it to try to fill the rest of the buffer).
This policy has the following drawback: if the timeout parameter is set to a large value (or -1, which means wait forever), then if the end of a message does not fill the output buffer completely, the …
=> gr-zmq: flush output in ZMQ stream sources

gr-uhd/examples/grc/rfnoc_split_stream.grc, gr-uhd/grc/CMakeLists.txt, gr-uhd/grc/uhd_rfnoc_split_stream.block.yml
Adds support for split stream block.
gr-uhd
Ran attached example with fix in most recent UHD, one is known, but has side effects (see and the other is a simple fix I am putting up for PR. This gnuradio implementation isn't involved in the bug, I tested and this works as is with UHD-4.0. This block itself would also work without using the fft block in the most recent UHD, but just splitting the CHDR stream without doing something on one split isn't much of an example since the stream could just be split after the streamer off of the FPGA.
=> uhd: rfnoc: Add GRC binding and example for split-stream block

gr-fec/lib/async_decoder_impl.cc, gr-fec/python/fec/_qa_helper_async.py, gr-fec/python/fec/qa_fecapi_cc.py, gr-fec/python/fec/qa_fecapi_dummy.py, gr-fec/python/fec/qa_fecapi_ldpc.py, gr-fec/python/fec/qa_fecapi_repetition.py
The `async_decoder` was broken in 4e50c99ab38f816d56145133ce6b7cc68e164e90. The reason was a mistake when rewriting the PR to address comments. In the case where the decoder input needs to be converted to `uchar`, `nitems_out` rather than `nbits_in` was wrongly used as the length of the data to be converted. Effectively, we are passing only the first half of the input to a rate=1/2 decoder such as the CC decoder.
Since there are no tests of the async_decoder that would have caught the bug, this adds some tests. A new `_qa_helper_async` `top_block` similar to `_qa_helper` is added. This is used in an additional test case in the `qa_fecapi_* `tests to run the `async_encoder` and `async_decoder` with all the different FECAPI encoders/decoders.
The Async Decoder FECAPI block. This also adds …
=> fec: fix regression in async_decoder and add tests

grc/gui/canvas/flowgraph.py
1. Open a fg that contains a hierachical block
2. Select the hierachical block
3. Open the source of the selected hierachical block from the grc menu
gives the following error in the terminal
Loading: "/home/schroer/gnuradiocomponents/gr-noaa/examples/doppler_test.grc"
>>> Done
Loading: "/home/schroer/gnuradiocomponents/gr-funcube/examples/decodeapt.grc"
>>> Done
File "/usr/local/gnuradio/lib64/python3.11/site-packages/gnuradio/grc/gui/Application.py", line 782, in _handle_action
for b in flow_graph.selected_blocks():
File "/usr/local/gnuradio/lib64/python3.11/site-packages/gnuradio/grc/gui/canvas/flowgraph.py", line 673, in <genexpr>
return (e for e in self.selected_elements if e.is_block)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: …
=> grc: Error Open the source of a hierachical block

gr-uhd/grc/CMakeLists.txt, gr-uhd/grc/uhd.tree.yml, gr-uhd/grc/uhd_rfnoc_fft.block.yml, gr-uhd/grc/uhd_rfnoc_fosphor.block.yml, gr-uhd/lib/rfnoc_rx_streamer_impl.cc
These commits enable the addition of the fosphor block support for rfnoc. 
The main commit is adding the actual Fosphor block support. 
One minor commit because the rx_streamer, when connected to the fosphor block, was not erroring on flush(), and that was a requirement for continued execution. I added a timeout to get around this, as flush() is only called when stopping execution of the block.
The other minor commit adds properties to the FFT block to allow for full fosphor support.
Example output using example from PR #6515 
Adds support for Fosphor block, adds properties to the FFT block
I ran the example added with a known source, and I confirmed that the fosphor display showed the expected frequency.
=> uhd: rfnoc: Add Fosphor block support

gr-uhd/grc/uhd_rfnoc_graph.block.yml
literal_eval() was used in the RFNoC graph GRC binding to sanitize
inputs. However, it was throwing an exception on drag and drop because
it requires a string containing a literal (e.g. string) rather than
just a string itself,
This was only an issue on drag/drop as the block code later does this transformation itself, but not before the first var_make()
However, the literal_eval() is not actually necessary, since the objects
passed in are of type TemplateArg, not just
string-or-something-that-evaluates-to-string, and thus we can use
facilities from TemplateArg to properly escape the values before usage.
Supersedes https://github.com/gnuradio/gnuradio/pull/6598
RFNoC graphs in GRC
Did some RFNoC graphs in GRC
=> uhd: rfnoc: fix literal_eval error

gr-blocks/include/gnuradio/blocks/selector.h, gr-blocks/lib/selector_impl.cc, gr-blocks/lib/selector_impl.h, gr-blocks/python/blocks/bindings/selector_python.cc
- introduce new sync consumption mode that consumes the same from all
inputs
- default to mode where as much as possible is consumed from active, and
at most that from inactive inputs
Since the old mode of operation was buggy, it can't be available. Also,
a dump-as-quickly-as-possible mode will be very surprising.
@Notou noticed that selector consumes `noutput_items` from all inputs – regardless of item availability.
`consume_each` does no sanity checks. Hilarity ensues.
Selector.
This might unbreak other applications that inexplicably only worked with throttles or similar crutches.
I haven't been able to come up with good tests.
=> blocks: selector: don't blindly consume same amount from all inputs

gr-utils/modtool/templates/gr-newmod/CMakeLists.txt
This fixes the gr_modtool newmod template so that a user-defined `CMAKE_INSTALL_PREFIX` will not be overriden when a `PYBOMBS_ENV` is defined.
Previously, if `PYBOMBS_ENV` was set, the `CMAKE_INSTALL_PREFIX` would be overridden to `PYBOMBS_ENV` no matter what. With this change letting CMake know that it is a CACHE variable, it only sets the default value and still allows the user to override `CMAKE_INSTALL_PREFIX` from the command line.
gr_modtool newmod template
I ran across this when building a conda package for `gr-lora_sdr`, which had followed the style of the template to do the same thing and accidentally override `CMAKE_INSTALL_PREFIX` when a `CONDA_PREFIX` was defined in the environment. Changing to CACHE variables fixed it.
- ~[ ] I have updated [the …
=> modtool: cmake: Don't override user-defined CMAKE_INSTALL_PREFIX

gr-uhd/examples/grc/rfnoc_logpwr_split.grc, gr-uhd/grc/CMakeLists.txt, gr-uhd/grc/uhd_rfnoc_logpwr.block.yml, gr-uhd/grc/uhd_rfnoc_rx_streamer.block.yml
Add support for the log-power RFNoC block, also expands the types for the rx_streamer to include s16 since that is the output type of the log power block
gr-uhd
Ran included example
=> uhd: rfnoc: Add bindings log-power RFNoC block, expand rx streamer types

gr-analog/grc/analog_agc2_xx.block.yml, gr-analog/grc/analog_agc3_xx.block.yml, gr-analog/grc/analog_agc_xx.block.yml, gr-analog/include/gnuradio/analog/agc2_cc.h, gr-analog/include/gnuradio/analog/agc2_ff.h, gr-analog/include/gnuradio/analog/agc3_cc.h, gr-analog/include/gnuradio/analog/agc_cc.h, gr-analog/include/gnuradio/analog/agc_ff.h, gr-analog/lib/agc2_cc_impl.cc, gr-analog/lib/agc2_cc_impl.h, gr-analog/lib/agc2_ff_impl.cc, gr-analog/lib/agc2_ff_impl.h, gr-analog/lib/agc3_cc_impl.cc, gr-analog/lib/agc3_cc_impl.h, gr-analog/lib/agc_cc_impl.cc, gr-analog/lib/agc_cc_impl.h, gr-analog/lib/agc_ff_impl.cc, gr-analog/lib/agc_ff_impl.h, gr-analog/python/analog/bindings/agc2_cc_python.cc, gr-analog/python/analog/bindings/agc2_ff_python.cc, gr-analog/python/analog/bindings/agc3_cc_python.cc, gr-analog/python/analog/bindings/agc_cc_python.cc, gr-analog/python/analog/bindings/agc_ff_python.cc
Max_gain parameter has been added to AGC constructors & make functions.
[#6613](https://github.com/gnuradio/gnuradio/issues/6613)
Analog AGC, AGC2 & AGC3 blocks.
I have manually tested the modified blocks without getting any warning or error, also checking that max_gain value is assigned properly.
=> Analog: max_gain parameter added to AGC constructors

gr-filter/python/filter/optfir.py
Formerly, it would just magically fail, when remezord returned impossible filter specs like n=0.
In #6621, @argilo noticed how `gr_filter_design` lacks handling for non-`RuntimeError` errors.
In the same move, he unearthed the fact that the opt lpf/bpf/hpf design
routines just pass band edges unchecked to `remezord`, which then fails to find
a suitable filter order if the specifications are nonsensical. Which then gets
reported as the error that a filter with order <2 can't be designed – although
the user never asked for that.
Filter design routines, `gr_filter_design`.
**Backportability:** yep, new exceptions, changes API technically. But since it just fails … better, I think this is safe to backport; this just never worked.
Added new tests for these exceptions
=> filter: fir_design needs to check band edge specifications

gr-filter/python/filter/design/filter_design.py, gr-filter/python/filter/gui/CustomViewBox.py
If an axis is dragged in one of Filter Design Tool's plots, the following exception occurs:
```
/usr/lib/python3/dist-packages/pyqtgraph/GraphicsScene/GraphicsScene.py:340: RuntimeWarning: Error sending drag event:
File "/home/argilo/prefix_311/bin/gr_filter_design", line 15, in <module>
filter_design.main(sys.argv)
File "/home/argilo/prefix_311/lib/python3.10/site-packages/gnuradio/filter/filter_design.py", line 2392, in main
app.exec_()
File "/usr/lib/python3/dist-packages/pyqtgraph/widgets/GraphicsView.py", line 362, in mouseMoveEvent
super().mouseMoveEvent(ev)
File "/usr/lib/python3/dist-packages/pyqtgraph/GraphicsScene/GraphicsScene.py", line 215, in mouseMoveEvent
if self.sendDragEvent(ev, init=init):
File …
```
=> filter: Fix exception when dragging plot axes in Filter Design Tool

gr-filter/python/filter/gui/banditems.py
The following exception occurs when dragging the mouse over the "Band Diagram" plot in the Filter Design Tool:
```
File "/home/argilo/prefix_311/lib/python3.10/site-packages/gnuradio/filter/banditems.py", line 48, in itemChange
newpos = value.toPointF()
AttributeError: 'QPointF' object has no attribute 'toPointF'. Did you mean: 'toPoint'?
```
It is apparent from the error message that `value` is already a `QPointF`, so it can be copied by using the copy constructor.
Filter Design Tool (gr_filter_design)
I generated some filters, then opened the "Band Diagram" tab and dragged the mouse over the diagram. With the fix in place, it becomes possible to adjust the stop band attenuation using the mouse.
The feature itself seems to be buggy (attenuation is not …
=> filter: Fix exception when dragging in Band Diagram plot

gr-uhd/python/uhd/bindings/rfnoc_block_python.cc, gr-uhd/python/uhd/bindings/rfnoc_fir_filter_python.cc
During a binding-hotfix (`gr-utils/bindtool/scripts/binding-hash-hotfixer.zsh  */python/**/bindings/*.cc`) run these files came up as modified
gr-uhd RFNoC blocks affected
**None whatsoever**; it seems these files don't get built on my machine, otherwise my CMake would have complained.
Either way, they should have consistent hashes.
=> UHD: fix rfnoc binding hashes

gr-qtgui/grc/qtgui_entry.block.yml, gr-qtgui/lib/edit_box_msg_impl.cc, gr-qtgui/python/qtgui/range.py.cmakein, gr-uhd/apps/uhd_fft, gr-uhd/apps/uhd_siggen_gui
This affects the QT GUI Entry, Message Edit Box, and Range widgets which use QLineEdit for text entry. Previously, these text edit boxes would not trigger the callback to update the variable unless Return/Enter was pressed. With this change, the variable is updated both in that case and also when the field loses focus, e.g. by clicking somewhere else on the display. See
https://doc.qt.io/qtforpython-5/PySide2/QtWidgets/QLineEdit.html#detailed-description for a description of the two signals.
I'm not sure if `returnPressed` was chosen intentionally to avoid the behavior of `editingFinished`, but I at least find the `editingFinished` behavior to be what I'd expect. There's no visual indication that Return/Enter is needed to set the corresponding variable, so it is natural to enter some …
=> qtgui: Replace `QLineEdit::returnPressed()` with `editingFinished()`

gr-blocks/lib/throttle_impl.cc
https://github.com/gnuradio/gnuradio/pull/5670 removed the line of code that resets the sample / item count in `throttle_impl::start()`: https://github.com/gnuradio/gnuradio/pull/5670#discussion_r1181567087. This causes a long delay when the throttle restarts after being stopped. Here I've added it back.
Fixes https://github.com/gqrx-sdr/gqrx/issues/1234.
Throttle
I verified that pausing & restarting playback of I/Q files in Gqrx works without delay after this change.
=> blocks: Reset item count when starting throttle

gr-blocks/lib/throttle_impl.cc
Backport https://github.com/gnuradio/gnuradio/pull/6647
=> blocks: Reset item count when starting throttle (backport to maint-3.10)

gr-utils/modtool/templates/gr-newmod/CMakeLists.txt
Backport https://github.com/gnuradio/gnuradio/pull/6619
=> modtool: cmake: Don't override user-defined CMAKE_INSTALL_PREFIX (backport to maint-3.10)

gnuradio-runtime/include/pmt/pmt.h, gnuradio-runtime/include/pmt/pmt_sugar.h, gnuradio-runtime/lib/pmt/pmt.cc, gnuradio-runtime/lib/pmt/pmt_int.h, gnuradio-runtime/python/pmt/bindings/pmt_sugar_python.cc
PMT dicts are notoriously annoying to generate; with this it gets easier:
```c++
using pmt::mp;
using pmt::pmt_t;
auto dict = dict_from_mapping(std::map<pmt_t, pmt_t>{{mp(foo), mp(12)}, {mp(bar), mp(baz)}});
```
To make the whole generation of symbols less of a copyfest, make symbol
interfaces use `string_view` instead of `const string&`; this allows usage
of PMT symbols without having an owning string.  Goal is to remove
unnecessary copies and allocations for temporary strings.
(while we're at it, remove an unused config.h inclusion)
PMT, and thus all block authors that want to emit dictionaries
https://github.com/gnuradio/gnuradio/blob/66d98ba2adf1c3edc777399b19c07b0bc8b2df64/gr-blocks/lib/probe_rate_impl.cc#L79-L81
=> PMT: add string and map/vector<pair<>> interface

gnuradio-runtime/include/pmt/pmt.h
As promised, a backport of #5994 which doesn't touch the PMT API by converting from `const std::string&` to `std::string_view`.
- #5994 (this is a backport)
- #6670  (backports #5996, which depends on the above)
- #6671 (backports #5997, which depends on both)
=> Backport PMT: modern interfaces for dicts 

gr-blocks/grc/blocks_probe_rate.block.yml, gr-blocks/include/gnuradio/blocks/probe_rate.h, gr-blocks/lib/probe_rate_impl.cc, gr-blocks/lib/probe_rate_impl.h, gr-blocks/python/blocks/bindings/docstrings/probe_rate_pydoc_template.h, gr-blocks/python/blocks/bindings/probe_rate_python.cc
I needed a better probe_rate block to distinguish between multiple probe rates in one flow graph. So: added a name parameter which is added to the emitted dictionary
Depends on  #5994 
The old format was kept around if name is set to an empty string; this is thus a self-contained change.
Would love to have done more testing, alas, needs work on message_debug first.
- yes. (block docs)
- Adding an example flowgraph to the extended message_debug PR (which hence will depend on this)
- wiki documentation: Will add example flowgraph picture; explain parameter
=> Better Probe Rate

gr-uhd/include/gnuradio/uhd/rfnoc_replay.h, gr-uhd/lib/rfnoc_replay_impl.cc, gr-uhd/lib/rfnoc_replay_impl.h, gr-uhd/python/uhd/bindings/docstrings/rfnoc_replay_pydoc_template.h, gr-uhd/python/uhd/bindings/rfnoc_replay_python.cc
Rename stop for replay block to stop_playback
Also adds some other items to pybind that looks like were missed on initial add
Fixes fedora 38 CI
gr-uhd rfnoc replay block
Sanity checked that simple replay example still worked
=> uhd: rename replay stop

gr-filter/include/gnuradio/filter/pm_remez.h, gr-filter/lib/pm_remez.cc, gr-filter/python/filter/bindings/pm_remez_python.cc, gr-filter/python/filter/design/filter_design.py, gr-filter/python/filter/design/fir_design.py, gr-filter/python/filter/gui/CustomViewBox.py, gr-filter/python/filter/gui/banditems.py, gr-filter/python/filter/optfir.py, gr-filter/python/filter/pfb.py, gr-filter/python/filter/qa_pm_remez.py
Backport #6621 #6629 #6639 #6640 
There is a change in exceptions `pm_remez()`:
> throws std::invalid_argument if args are invalid and std::runtime_error if calculation fails to converge
where previously only `std::runtime_error` was thrown.
Given that so many checks were missing and the risk of bad results, it seems like a good idea to backport this behavior change.
=> filter: designer rework and fixes (backport to maint-3.10)

gr-uhd/include/gnuradio/uhd/rfnoc_replay.h, gr-uhd/lib/rfnoc_replay_impl.cc, gr-uhd/lib/rfnoc_replay_impl.h, gr-uhd/python/uhd/bindings/docstrings/rfnoc_replay_pydoc_template.h, gr-uhd/python/uhd/bindings/rfnoc_replay_python.cc
Backport #6679 quickly since it fails Fedora 38 CI..
=> uhd: rename replay stop (backport to maint-3.10)

.github/workflows/make-test.yml
Backport #6672 #6677 
Note that we are still not using memory fill in CI for maint-3.10, only in main.
=> ci: Remove Fedora 36, add Fedora 38 (backport to maint-3.10)

gr-soapy/grc/soapy_rtlsdr_source.block.yml
Enable select of bias tee via "bias" param.
Restore previous gain when AGC is disabled.
Every so slightly addresses #6604 
Soapy RTLSDR Source
=> soapy: rtlsdr bias tee and restore gain after agc

gr-soapy/grc/soapy_sdrplay_source.block.yml
SDRPlay gains are actually attenuations
- grdb: gain reduction of 20 to 59 dB
- lna state: model-specific attenuation steps for LNA
LNA state is independent of AGC. Gain reduction is N/A when AGC is on.
SoapySDR attempts to do automatic distributions of gains if setGain() is called without a gain name. This is what gr-soapy was trying to do and it resulted in invalid gain values.
AGC has a setpoint, which was not being set. This is probably why a crash was happening when AGC was set.
This change:
- Adds the AGC setpoint
- Separates gain and lna state
- Makes gain positive instead of the previous negative range
- LNA state is still an attenuation with device-specific stages
- Sets gain when agc is turned off (not done by driver)
- Defers setting IFGR gain when agc is on, to avoid warnings …
=> soapy: sdrplay agc and gain fixes

gnuradio-runtime/include/gnuradio/logger.h, gnuradio-runtime/lib/qa_logger.cc, gnuradio-runtime/python/gnuradio/gr/bindings/docstrings/logger_pydoc_template.h, gnuradio-runtime/python/gnuradio/gr/bindings/logger_python.cc, gr-blocks/examples/message_debug.grc, gr-blocks/examples/probe_rate_message_debug.grc, gr-blocks/grc/blocks_message_debug.block.yml, gr-blocks/include/gnuradio/blocks/message_debug.h, gr-blocks/lib/message_debug_impl.cc, gr-blocks/lib/message_debug_impl.h, gr-blocks/python/blocks/bindings/message_debug_python.cc
Wanted to work with the probe rate block, ended up having trouble using the output
Decided this thing should be able to log to our logging system instead of the very verbose printf that it does
Allowed people to set log levels.
Updated wiki page staging: https://wiki.gnuradio.org/index.php?title=User:MarcusMueller/Message_Debug
Depends on #5996 
Since the original inputs remain unchanged, this is a self-contained change.
Only connection testing
=> Message Debug: Add log output

gr-soapy/grc/soapy_airspyhf_source.block.yml
AirspyHF has specific sample rates. Add them as options.
Also, make gain visible in params dialog even if agc is on, to help with wiring UI elements.
Soapy AirspyHF Source
=> soapy: add discrete rates for AirspyHF, always show gain in params

.github/workflows/make-test.yml, gnuradio-runtime/lib/flat_flowgraph.cc, gr-digital/lib/constellation_decoder_cb_impl.h, gr-digital/lib/constellation_encoder_bc_impl.h, gr-digital/lib/constellation_soft_decoder_cf_impl.h, gr-qtgui/lib/fosphor_display_impl.cc, gr-qtgui/lib/fosphor_display_impl.h
We have a lot of different platforms for test builds; but on Linux we really just test building with one compiler, GCC.
This converts the 0xFE-initializing F38 GCC builder to a (non-special-initalizing) F38 clang++ builder.
I guess this would uncover warnings introduced by new code a bit earlier, potentially 
Nöne.
CI
This test build
=> CI: F38 as clang build

gnuradio-runtime/include/gnuradio/thread/thread_group.h, gnuradio-runtime/lib/thread/thread_group.cc
Currently, `thread_group` is using `std::list` to keep a set of thread unique ptrs, which is both inefficient computationally and complicated code-wise.
Fixes a missed `#include <mutex>`, which was hidden by precompiled headers (or so it seems!) on the way.
Internal to `thread_group`; API doesn't change
=> runtime: thread_group use set instead of list for set of threads

gr-network/lib/tcp_sink_impl.cc, gr-network/lib/udp_sink_impl.cc, gr-network/lib/udp_sink_impl.h, gr-network/lib/udp_source_impl.cc, gr-network/lib/udp_source_impl.h
This fixes the following bugs:
* `udp_sink_impl::stop` leaks `d_udpsocket` (80 bytes on my system)
* `udp_sink_impl::stop` reads uninitialized `d_udpsocket` (and often crashes) if the block was not previously started
* `udp_source_impl::stop` leaks `d_udpsocket` (80 bytes on my system)
* `udp_source_impl::stop` reads uninitialized `d_udpsocket` (and often crashes) if the block was not previously started
* `tcp_sink_impl::connect` reads uninitialized `d_is_ipv6` if the block is in server mode
* `tcp_sink_impl::stop` crashes in server mode because it fails to join `d_listener_thread`
* UDP Sink
* UDP Source
* TCP Sink
To test the blocks, I used valgrind (`valgrind --leak-check=full --show-leak-kinds=definite python3`), and ran the following Python code:
```python
from gnuradio import …
```
=> network: Fix various bugs

gr-fec/include/gnuradio/fec/alist.h
=> fec: include cstdint in gr-fec's alist.h (backport to maint-3.10)

gr-soapy/grc/soapy_rtlsdr_source.block.yml
=> soapy: rtlsdr bias tee and restore gain after agc (backport to maint-3.10)

gr-blocks/grc/blocks_probe_rate.block.yml, gr-blocks/include/gnuradio/blocks/probe_rate.h, gr-blocks/lib/probe_rate_impl.cc, gr-blocks/lib/probe_rate_impl.h, gr-blocks/python/blocks/bindings/docstrings/probe_rate_pydoc_template.h, gr-blocks/python/blocks/bindings/probe_rate_python.cc
backport of #5996, rebased on top of #5994 's backport, #6669
=> Backport better probe rate

.github/workflows/make-test.yml, gnuradio-runtime/lib/flat_flowgraph.cc
Backport #6685 
Commits not included:
- 13f5ad3f8 was backported in #6710 
- 153b5dcbe will be part of the backport of #6515
=> CI: F38 as clang build (backport to maint-3.10)

gr-soapy/grc/soapy_sdrplay_source.block.yml
When using Soapy SDRPLay Source alone without any variables using RSP1 (clone) there are errors:
* `biasT_ctrl` setting is unknown
* `self.agc` does not exist
* `self.gain` does not exist
Original fixes https://github.com/gnuradio/gnuradio/pull/6665 seem to require extra variables / parameters in the flowgraph.
Soapy SDRPlay Source
Using gnuradio 3.10.6
1. Run a top block with nothing but Soapy SDRPlay Source and Null Sink
2. Create a custom hier block with nothing but Soapy SDRPlay Source and a Pad Sink
3. Run a top block with nothing but the previous hier block and Null Sink
=> soapy: fix sdrplay biasT_ctrl/agc/gain settings

gr-uhd/lib/rfnoc_rx_streamer_impl.cc
In rfnoc_rx_streamer_impl::work , d_metadata.error_code has type uhd::rx_metadata_t::error_code_t , which is just enum.
But with fmtlib 10, fmt::format won't accept enum by default. So just cast this variable error_code to int to make fmtlib-10 accept this.
Closes #6735 .
=> gr-uhd/lib: support fmtlib 10

gr-soapy/grc/soapy_rtlsdr_source.block.yml
Fix variable names, which just happened to work if a control with the same name already existed. This is the same type of fix Tommi made recently for SDRPlay.
=> soapy: fix variable naming in RTL grc

gr-soapy/grc/soapy_rtlsdr_source.block.yml
Check with soapy driver whether biastee is a valid setting, instead of relying on a black field as a default.
Protect bias and agc calls from blank fields. GRC allows a blank for bool. In the templates, this is an actual blank, not an empty string, so it can cause errors.
This is an improvement to #6738.
Soapy RTLSDR Source
=> soapy: more robust handling of bias and agc settings in rtlsdr yml

gr-soapy/grc/soapy_rtlsdr_source.block.yml
=> soapy: fix variable naming in RTL grc, more robust handling of agc and bias

gr-uhd/lib/usrp_source_impl.cc, gr-uhd/lib/usrp_source_impl.h
When using a usrp on a shaky ethernet connection, the device might repeatedly report overflow errors which caused an infinite recursion in the work function. This is problematic since this will prevent the gnuradio flowgraph from being stopped since this block will always be busy.
I added a variable for number of retries until quitting, but it has a hard coded value of 10. I didn't want to complicate the interface and make this value changeable from the outside since it doesn't seem likely that tuning this value could cause any benefits.
I also took the liberty to change the recursive mutex to a normal mutex. The mutex is used in only three functions:
1. work
2. start
3. stop
And none of them call each other anymore, so this should be safe.
=> gr-uhd: fix infinite recursion in the case a device is poorly connected

gnuradio-runtime/include/gnuradio/logger.h, gnuradio-runtime/python/gnuradio/gr/bindings/logger_python.cc
when compiling in c++20 mode, fmt checks at compile time that the format string is constant expression. this is not the case with spdlog::string_view, and we get the error: ‘msg’ is not a constant expression so instead use spdlog::format_string_t (which actually defaults to string_view when using older compilers that don't support it)
=> runtime: c++20 friendly logging

gnuradio-runtime/include/gnuradio/buffer_single_mapped.h, gnuradio-runtime/include/gnuradio/buffer_type.h, gnuradio-runtime/include/gnuradio/io_signature.h, gnuradio-runtime/lib/buffer_single_mapped.cc, gnuradio-runtime/lib/io_signature.cc, gnuradio-runtime/python/gnuradio/gr/bindings/buffer_type_python.cc, gnuradio-runtime/python/gnuradio/gr/bindings/io_signature_python.cc
`io_signature` is around the oldest code we have in the API, and its `make` variants make little sense.
Clean these up, deprecate the current API; and then, if consensus for that can be found, remove "bad" `makeX`s from main.
Fixes #6758 
#6758 illustrated needs for better inspectabilty, and more sensible types, in `io_signature`.
Tree-wide
=> io_signature: API cleanup

gr-blocks/examples/demonstrate_throttle.grc
Also used on the Throttle wiki page:
----
In the below flowgraph, the upper Signal Source is feeding into a Throttle block, which limits the rate at which it passes samples to 50,000 samples per second.
We use the "Limit" parameter to bound the maximum time that happens between a chunk of items being emitted by the Throttle block. We set that time to 1/50 of a second. (And that gives us 1/50 s · 50,000 Samples/s = 1000 Samples per chunk, at most.)
The lower Signal Source is not feeding into something that slows it down to a defined rate.
To test the rates at which samples pass through, we attach Probe Rate blocks, and give them distinct names. We use Message Debug to print these rates.
We observe this:
- As we can see in the upper "Throttled" figure, the passing of samples of a defined …
=> blocks: Add a GRC example for throttle

gr-fec/include/gnuradio/fec/alist.h
Restores buildability with GCC13; cstdlib no longer includes cstdint
GCC13 breaks the maint-3.9 build (OK; it was broken before, but…)
found looking at #6762 
- [-] I have added tests to cover my changes, and all previous tests pass.
=> fec: alist.h: use cstdint instead of cstdlib for std::int??_t

.github/workflows/make-test.yml
E721 enforces the use of "is"/"is not" vs "==" in type comparison. There are 150 instances that were recently flagged by CI.
Reverse this change after #6770 is addressed.
Many/CI
=> CI: disable Python check E721 until fixes can be made

gr-iio/lib/device_source_impl.cc, gr-iio/lib/fmcomms2_source_impl.cc, gr-iio/lib/fmcomms2_source_impl.h
fmcomms2_source creates a thread that monitors overflows. this thread is created on construction, and destroyed when the source is stopped. if an fmcomms2_source is constructed, but never started, the overflow thread will be stuck in an infinite loop. also if the fmcomms2_source is started and stopped multiple times, the overflow thread will be destroyed after the first stop.
this solution creates the thread on each start, and destroys it on each stop.
I could've been more efficient by adding a "paused" state, but I think that this is simpler.
=> gr-iio: fix deadlock when destroying fmcomms2_source that didn't start

gr-qtgui/lib/freq_sink_c_impl.cc, gr-qtgui/lib/freq_sink_c_impl.h, gr-qtgui/lib/freq_sink_f_impl.cc, gr-qtgui/lib/freq_sink_f_impl.h
The refresh rate of the QT GUI Time Sink can be painfully slow when the input sample rate is low. This was a side effect of #5442, which set the block's output multiple to `MAX_FFT_SIZE` = 32768 in the block's constructor, presumably to ensure that the scheduler allocates a large enough buffer to accommodate FFT size changes made in the GUI at runtime:
https://github.com/gnuradio/gnuradio/blob/0966207dbc5cc0077f7ee6cde0aaa95f7c7a8d99/gr-qtgui/lib/freq_sink_c_impl.cc#L128
If the FFT size is changed at runtime, the refresh rate speeds up because the output multiple is adjusted to the current FFT size:
https://github.com/gnuradio/gnuradio/blob/0966207dbc5cc0077f7ee6cde0aaa95f7c7a8d99/gr-qtgui/lib/freq_sink_c_impl.cc#L415
By doing the same in the `start()` method, the block will have the …
=> Set the frequency sink's output multiple on start

gr-soapy/grc/soapy_rtlsdr_source.block.yml
Currently, there is no way to set the Buffer Size (`bufflen`) parameter of an RTLSDR source from within GNU Radio Companion. The default value (262144 bytes / 131072 samples) can be excessively large, particularly when operating at low sample rates. For instance, at 240000 sps the buffer is 546 ms long. This causes high latency and very slow update rates for GUI sinks.
Here I've added a USB Buffer Size parameter which allows this value to be adjusted.
* Soapy RTLSDR Source
I tested using a flowgraph with an RTLSDR source connected to a Time Sink & Frequency Sink. With the sample rate set to 240000, the display becomes much more responsive when the buffer size is decreased to 16384.
=> Add buffer size parameter to RTLSDR Source

gr/include/gnuradio/nodeid_generator.h
This fixes compile errors on F38/gcc13.
=> gr: Add cstdint include to nodeid_generator

.readthedocs.yaml
This specifies build.os, which was previously relying on the default value. According to RTD documentation, this key is required and its abscence was causing warnings.
=> docs: Update RTD config

gnuradio-runtime/lib/pmt/pmt_serialize.cc
=> runtime: pmt_serialize uses std::int32_t without <cstdint> (backport to maint-3.10)

gr-iio/lib/device_source_impl.cc, gr-iio/lib/fmcomms2_source_impl.cc, gr-iio/lib/fmcomms2_source_impl.h
=> gr-iio: fix deadlock when destroying fmcomms2_source that didn't start (backport to maint-3.10)

gnuradio-runtime/lib/controlport/thrift/rpcpmtconverters_thrift.cc
fmt doesn't format enums implicitly any more, causing the build to fail. Calling `to_string` fixes it.
Fixes #6774
=> Fix build with fmt-10.1

gr-qtgui/grc/qtgui_const_sink_x.block.yml
The QT GUI Constellation Sink uses the red colour for inputs 2 through 10, making them indistinguishable. Here I've changed the default input colours to match the other sinks. I also changed the capitalization of "dark blue" for consistency with the other sinks.
* QT GUI Constellation Sink
=> qtgui: Use different colours for Constellation Sink inputs

gnuradio-runtime/include/gnuradio/CMakeLists.txt, gnuradio-runtime/include/gnuradio/pmt_fmt.h, gnuradio-runtime/lib/CMakeLists.txt, gnuradio-runtime/lib/pmt_fmt.cc, gr-blocks/include/gnuradio/blocks/repeat.h, gr-blocks/lib/repeat_impl.cc, gr-blocks/lib/repeat_impl.h, gr-blocks/python/blocks/bindings/repeat_python.cc, gr-blocks/python/blocks/qa_repeat.py
Repeat is a block that's commonly runtime-reconfigured. However, if the new interpolation is larger than the one specified at instantiation, this can lead to unsatisfiable output buffer requirements.
This change makes it so that the block is not a `sync_interpolator` anymore, but simply keeps track of how many times the last item still has to be repeated.
On the way there:
- Changed block type from `sync_interpolator` to `block`
- Hence, implemented a correct `forecast`
- Constructor and interpolation setter check for interpolation >= 1
- `general_work`: aforementioned handling of partial repeats
- `qa_repeat`: original QA was totally insufficient and ignored most
corner cases. Also, checking code was very slow.
- Add the PMT formatter for fmt/spdlog that's necessary for setter logging …
=> Repeat: itemwise, solve buffer allocation issue

gr-qtgui/lib/eyedisplayform.cc, gr-qtgui/lib/freqdisplayform.cc, gr-qtgui/lib/timedisplayform.cc
In the Eye, Frequency, and Time sinks, if the display is stopped (middle click --> Stop) and then the control panel is opened (middle click --> Control Panel), the state of the Start/Stop button in the control panel is inverted. ("Stop" is displayed when the display is already stopped, and "Start" is displayed if it is restarted.)
To fix this, I've added code to set the control panel's Start/Stop button to the correct state when it is opened.
* QT GUI Eye Sink
* QT GUI Frequency Sink
* QT GUI Time Sink
I used the following flow graph for testing:
While running the flow graph, I tried various sequences of the following operations:
* middle click --> Start/Stop
* middle click --> Control Panel
* click Start/Stop in the control panel
The control panel's Start/Stop button behaved correctly in …
=> qtgui: Set stop button to correct state when opening control panel

gnuradio-runtime/include/gnuradio/attributes.h, gr-dtv/lib/dvbt/dvbt_ofdm_sym_acquisition_impl.cc, gr-dtv/lib/dvbt/dvbt_ofdm_sym_acquisition_impl.h
VLA (Variable-Length Arrays) are a C (pre-C23) feature that only works
for some C++ compilers out of goodwill – in C++, an object's type is
known at compile time, and `int[3]` and `int[4]` are two different
types.
They do nothing special that std::vector couldn't do as well, and
there's only one usage within GNU Radio that should actually have used
allocation in the constructor, and a field. So, changed it that way.
=> runtime: Remove VLA macro, usage

gr-qtgui/lib/matrix_sink_impl.cc
Update to #6718 for compatibility with Qt 5.12 (Ubuntu 20.04)
=> qtgui: Matrix Sink - use QVector initializer supported by Qt 5.12

gr-iio/grc/iio_device_sink.block.yml, gr-iio/grc/iio_device_source.block.yml, gr-iio/lib/device_sink_impl.cc, gr-iio/lib/device_source_impl.cc, gr-iio/lib/iio_priv.h
This modification enables using devices that have arbitrary channel size or channels with different sizes across the same device
Internally we found that when using gr-iio blocks with devices that do not have 16 bit channels, the data received is malformed.
This is due to the signature being hardcoded to multiple "short" channels. The solution consists in querying IIO for the channel format and setting the gr::io_signature at block consturction.
The output type added to the blocks in the gnuradio-companion is there to prevent the companion from erroring when connecting blocks to the device_source/device_sink that are not short. The output type in the companion has no real effect on building the block.  There is still a problem in the companion with devices that have heterogenous outputs …
=> iio: make gr::io_signature for device_source dynamic

gr-blocks/lib/repeat_impl.cc, gr-blocks/lib/repeat_impl.h, gr-blocks/python/blocks/qa_repeat.py
The repeat block was refactored as a general block in #6813 (it was a sync_interpolator before). However, tag propagation was missing from the refactor. Manual tag propagation needs to be done if the block is a general block, because the automatic tag propagation preserves the offset of tags, which is not what we want for the repeat block.
Incidentally, before the refactor tag propagation was also somehow broken for interpolation changes at runtime. After an interpolation change, tags would disappear in the output for some time, or appear in the wrong place.
The tag propagation behaviour introduced by this block is the most natural one. Tags from each input item are copied to the first repetition of such input item in the output.
Additionally, two QA tests for tag propagation have been …
=> blocks: fix repeat block tag propagation

gnuradio-runtime/include/gnuradio/attributes.h, gr-dtv/lib/dvbt/dvbt_ofdm_sym_acquisition_impl.cc, gr-dtv/lib/dvbt/dvbt_ofdm_sym_acquisition_impl.h
=> runtime: Remove VLA macro, usage (backport to maint-3.10)

gr-filter/python/filter/pfb.py
=> filter: fix typo in return value in pfb.py (backport to maint-3.10)

gr-network/lib/udp_source_impl.cc
The calculation for set_output_multiple() in did not take vectors into account correctly. Use of vectors is still tricky, as the vector size needs to divide into the payload size evenly. Incorrect values result in corrupted data.
Fixes #6826
UDP Source
Sample GRCs provided with issue.
=> network: improved UDP Source vectorization

grc/gui_qt/Utils.py, grc/gui_qt/components/block_library.py, grc/gui_qt/components/canvas/block.py, grc/gui_qt/components/flowgraph.py, grc/gui_qt/components/window.py, grc/gui_qt/grc.py, grc/tests/test_qtbot.py
This PR adds the ability to double-click on a block to add it to a flowgraph. With this, it simplifies many of the qt-specific tests, focusing on making them standalone, and easier to read.
None
GRC (Qt)
The `tests/test_qtbot.py` tests were run and passed, and individual testing was done to ensure double click works
=> grcqt: Add double click to add block and simplify tests

gnuradio-runtime/lib/vmcircbuf_mmap_shm_open.cc, gnuradio-runtime/lib/vmcircbuf_mmap_tmpfile.cc
It was recently reported that Gqrx crashes on FreeBSD:
https://github.com/gqrx-sdr/gqrx/issues/1275
After some digging, I found that the crash occurs because `vmcircbuf_mmap_shm_open::vmcircbuf_mmap_shm_open` allocates a discontiguous double-mapped buffer. This happens because the `mmap` system call is free to ignore the supplied `addr` argument (which is only a suggestion) and choose its own address for the mapping.
This can be fixed by using the `MAP_FIXED` flag, which tells `mmap` that the `addr` argument must be used as-is.
The `vmcircbuf_mmap_tmpfile` implementation has an explicit contiguity check (which simply throws an exception if the returned buffer is discontiguous). With the addition of the `MAP_FIXED` flag, I don't think this check is necessary.
* …
=> runtime: Use MAP_FIXED flag to ensure buffer halves are contiguous

gr-digital/examples/packet/formatter_crc.grc, gr-digital/examples/packet/formatter_crc_header_payload_demux.grc, gr-digital/examples/packet/formatter_ofdm.grc, gr-digital/include/gnuradio/digital/header_buffer.h, gr-digital/lib/header_buffer.cc, gr-digital/lib/header_format_crc.cc, gr-digital/lib/header_format_ofdm.cc, gr-digital/lib/qa_header_buffer.cc, gr-digital/python/digital/bindings/header_buffer_python.cc, gr-digital/python/digital/qa_packet_format.py
As described in #6550 and #6575, the `header_format_crc` and `header_format_ofdm` classes don't operate on a header with the documented format. This comes from the fact that the `header_buffer` api does not allow parsing with least significant bit first.
It also prevents the scrambling feature of `header_format_ofdm` from working (I guess that's why it has been commented out for years).
So I added a LSB first option to the extract field functions of the `header_buffer`, putting it last and false by default to keep compatibility. I also templated the function to reduce code duplication.
I modified `header_format_crc` to use this LSB option, and reactivated the scrambling feature of `header_format_ofdm`.
I believe this could be back-ported at least to 3.10, if not to 3.9.
* Fixes #6550
* …
=> Header format: Fix CRC and OFDM formats, header_buffer refactoring

gnuradio-runtime/include/gnuradio/CMakeLists.txt, gnuradio-runtime/include/gnuradio/pmt_fmt.h, gnuradio-runtime/lib/CMakeLists.txt, gnuradio-runtime/lib/pmt_fmt.cc, gr-blocks/include/gnuradio/blocks/repeat.h, gr-blocks/lib/repeat_impl.cc, gr-blocks/lib/repeat_impl.h, gr-blocks/python/blocks/bindings/repeat_python.cc, gr-blocks/python/blocks/qa_repeat.py
Backport #6813 
Backport #6832 
API Note: Repeat was previously a `gr::sync_interpolator` and is now a `gr::block`. It is unlikely that users derive their own blocks from this block, the API change is low risk.
=> Repeat: itemwise, solve buffer allocation issue (backport to maint-3.10)

.readthedocs.yaml
This fixes the following RTD error message:
Problem in your project's configuration. Invalid configuration option
"build.tools": At least one item should be provided in 'tools' or
'commands'
=> docs: Update RTD config to include build.tools

gr-digital/grc/digital_symbol_sync_xx.block.yml, gr-digital/include/gnuradio/digital/symbol_sync_cc.h, gr-digital/include/gnuradio/digital/symbol_sync_ff.h, gr-digital/lib/symbol_sync_cc_impl.cc, gr-digital/lib/symbol_sync_cc_impl.h, gr-digital/lib/symbol_sync_ff_impl.cc, gr-digital/lib/symbol_sync_ff_impl.h, gr-digital/python/digital/bindings/docstrings/symbol_sync_cc_pydoc_template.h, gr-digital/python/digital/bindings/docstrings/symbol_sync_ff_pydoc_template.h, gr-digital/python/digital/bindings/symbol_sync_cc_python.cc, gr-digital/python/digital/bindings/symbol_sync_ff_python.cc
This adds a method to update the samples/symbol of the symbol_sync block at runtime. When the set_sps() method is called, it resets all the internal symbol synchronization loop status and ajusts values for the new samples/symbol, so synchronization is lost and the loop needs to lock again. This is reasonable, because the set_sps() method can only be called asynchronously with respect to symbol rate changes in the input sample stream. A more advanced runtime change could use tags to update the samples/symbol at a specific point without losing loop lock, but this commit does not cover this use case.
No related issue.
The Symbol Sync block.
Testing has been done with the following flowgraph, which generates a square-pulse BPSK signal with an integer sps, runs Symbol Sync on it, and allows …
=> digital: add sps setter to symbol_sync

gr-uhd/examples/grc/CMakeLists.txt, gr-uhd/examples/grc/rfnoc_null_source_sink.grc, gr-uhd/grc/CMakeLists.txt, gr-uhd/grc/uhd_rfnoc_null_src_sink.block.yml
gr-uhd is missing a GRC block for the RFNoC block NullSrcSink. For context, this RFNoC block provides a null source/sink and loopback capability. This addition adds a GRC block to allow the use of this RFNoC block in GRC. In the options for the block, you can toggle Source or Sink to change the associated use of the block.
This addition also adds an example flowgraph as seen below:
This work was performed here at the NASA Jet Propulsion Laboratory, I am required to post the following:
Affiliation: Jet Propulsion Laboratory, California Institute of Technology
Contact Information: Zach Rohde <zachary.s.rohde@jpl.nasa.gov>
Funding Acknowledgment: The research was carried out at the Jet Propulsion Laboratory, California Institute of Technology, under a contract with the National Aeronautics …
=> gr-uhd: add a GRC block for the RFNoC NullSrcSink block

gr-blocks/python/blocks/msg_pair_to_var.py
Fixes `Attribute Error: function has no attribute "name"`
=> Msg Pair To Var: fix attribute error during callback error handling

gr-qtgui/grc/qtgui_entry.block.yml, gr-qtgui/grc/qtgui_range.block.yml, gr-qtgui/lib/edit_box_msg_impl.cc
This is a follow-up to #6645 which addresses comments that have arisen since that was merged. Namely:
1. Using `returnPressed` for the Message Edit Box is the preferred behavior, so reverts the prior change and restores that behavior as intended with #5592.
2. Since there are reasonable use cases for either signal with the QT GUI Entry, this provides a GRC option that allows the user to select the update trigger to be either `returnPressed` or `editingFinished`.
3. The range widget's use of `editingFinished` only arises with the `eng` and `eng_slider` variants, and for those the `editingFinished` behavior makes sense. However, in reviewing this, I discovered that neither of those variants has been exposed in GRC since they were introduced in #3163, so this PR includes a commit to make …
=> qtgui: Refine use of `QLineEdit::returnPressed()` or `editingFinished()` for text entry

gnuradio-runtime/lib/vmcircbuf_mmap_shm_open.cc, gnuradio-runtime/lib/vmcircbuf_mmap_tmpfile.cc
=> runtime: Use MAP_FIXED flag to ensure buffer halves are contiguous (backport to maint-3.10)

.clang-tidy
=> .clang-tidy: remove ... that snuck/sneaked into the file (backport to maint-3.10)

gr-blocks/python/blocks/sigmf_sink_minimal.py
SigMF metadata files produces by the SigMF Sink (Minimal) block do not include a trailing newline, making them a bit inconvenient to work with in the terminal. I think it makes sense to include one, as sigmf-python does:
https://github.com/sigmf/sigmf-python/blob/c5aa8f30dcfa08596ffa70744422b6e4a95c4300/sigmf/sigmffile.py#L545
* SigFM Sink (Minimal)
I ran the following flowgraph:
This produced the following metadata file:
```
{
"global": {
"core:datatype": "cf32_le",
"core:sample_rate": 32000.0,
"core:version": "1.0.0",
"core:hw": "ghi",
"core:author": "abc",
"core:description": "def"
},
"captures": [
{
"core:sample_start": 0,
"core:frequency": 100.0
}
],
"annotations": []
}
```
=> blocks: Include a trailing newline in SigMF metadata

gr-blocks/python/blocks/sigmf_sink_minimal.py
=> blocks: Include a trailing newline in SigMF metadata (backport to maint-3.10)

gr-iio/grc/iio_fmcomms2_sink.block.yml, gr-iio/grc/iio_fmcomms2_source.block.yml
A quick fix to https://github.com/gnuradio/gnuradio/issues/6895
I don't think this fully solves the issues with the IO signature of the Pluto blocks though. But I noticed this while debugging that issue. I need to sign this commit, but posting this for visibility given the 3.10 RC1
=> iio: Remove extra element from fmcomms2 YML

gr-qtgui/lib/fosphor_display_impl.cc, gr-qtgui/lib/fosphor_display_impl.h
Running the tests for the fosphor_display widget sometimes leads to an std::bad _alloc error.
The reason is a wrong call to QApplication. The first argument argc must be greater than 0. See qt documentation or see comments for example in freq_sink_c_impl.h.
https://github.com/gnuradio/gnuradio/blob/fe42f6a4aacca65010939afe41910e7d55e68063/gr-qtgui/lib/freq_sink_c_impl.h#L54-L57
#6515 and #6828
fosphor_display
You can test it wit a simple python script
from gnuradio import qtgui
from PyQt5 import QtGui 
from PyQt5.QtWidgets import QWidget
a=qtgui.fosphor_display(256,64,512)
print('Success fosphor_display')
b=qtgui.FosphorGlSink(1, 16, 64, 64, 1.0, 0.1, 0.99, 16.0, 1024.0)
print('Success GLSink')
Running this code several times  you'll get sometimes a bad_alloc. After this patch the …
=> fosphor display widget: Fix std::bad_alloc

gr-iio/grc/iio_fmcomms2_sink.block.yml, gr-iio/grc/iio_fmcomms2_source.block.yml
Reverts gnuradio/gnuradio#6896
Dynamic I/O type is not supported by the framework. Reverting along with #6857
=> Revert "iio: Remove extra element from fmcomms2 YML"

grc/gui/ParamWidgets.py, grc/gui/PropsDialog.py, grc/gui/canvas/param.py
Many folks have complained about the garish color scheme used to denote types of parameters in the block parameters dialog. The meaning is not especially clear, and the colors do not adapt to different color schemes well. Instead, this PR adds the field's datatype as a label at the end of the parameter (see below) and removes coloring.
(apologies for the change count...I will try to remember to turn off Black when working on PRs in the future 😖)
#2687 
GRC
pytest was run in `grc/` and all tests passed
=> grc: Remove param field colorings by type and replace with labels

gr-digital/include/gnuradio/digital/header_format_crc.h, gr-digital/include/gnuradio/digital/header_format_ofdm.h, gr-digital/include/gnuradio/digital/packet_header_default.h, gr-digital/python/digital/bindings/header_format_crc_python.cc, gr-digital/python/digital/bindings/header_format_ofdm_python.cc, gr-digital/python/digital/bindings/packet_header_default_python.cc
spellcheck fix with HASH updates
Debian's lintian tool suggests replacing "everytime" with "every time"
This usage only appears under gr-digital in header files comments.
This patch is applied in debian packaging for gnuradio 3.10.8.0-rc1
The build works - so the HASH values match.
The lintian finding goes away.
As this patch applies to the maint-3.10 branch as well, please consider
including it before tagging the next 3.10.8.0 release.
=> gr-digital every time

grc/gui/ParamWidgets.py
Previous PR (#6888) missed a few type labels to ignore, making them a bit noisy. This PR updates that list
PR #6888 
GRC
Old tests succeed
- [ x] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
=> grc: Update ignored param type labels

CHANGELOG.md, CMakeLists.txt
Since v3.10.8.0-rc1
- Require `zmq.hpp` (cppzmq) version with `context_t.shutdown()` defined. If `shutdown` is not defined, the `gr-zeromq` is disabled.
=> v3.10.8.0-rc2

grc/gui/Application.py
aka https://xkcd.com/1638/ :smile: 
Each time File -> Open Recent is used on Windows, the number of backslashes in the filename doubles.
This happens because a `GLib.Variant` object is passed through `str()`, which produces a quoted (and escaped) string. The quotes are then removed, but the escaping remains. The underlying string can instead be accessed using the `get_string()` method.
The same broken pattern exists in two other places, so I fixed those as well.
GNU Radio Companion
I verified that opening recent files works correctly (both through the menu and toolbar) on Linux and Windows. I also verified that creating new files still works (both through the menu and toolbar).
=> grc: Fix way-over-backslashing in file paths

grc/core/Messages.py
GRC usually formats filenames by putting double quotes around them, but when a flow graph is generated, the filename is formatted as a Python string, including escaping. On Windows, backslashes become double backslashes, making the filename harder to read. Here I've changed the messages to format the filename the same as elsewhere.
GNU Radio Companion
I verified that the filename is displayed in double-quoted form:
```
Generating: "C:\Users\Clayton\Documents\test.grc"
```
=> grc: Consistently format filenames in messages

gr-uhd/grc/uhd_rfnoc_rx_streamer.block.yml, gr-uhd/include/gnuradio/uhd/rfnoc_rx_streamer.h, gr-uhd/lib/rfnoc_rx_streamer_impl.cc, gr-uhd/lib/rfnoc_rx_streamer_impl.h, gr-uhd/python/uhd/bindings/rfnoc_rx_streamer_python.cc
Exposes the start_stream_cmd option and the time_spec field to GNU Radio. This is used by the start-stream command of RFNoC to initiate streaming.  
The default values keep the present behaviour
| Block | Defaults | Delayed start stream
|-|-|-|
|![grafik](https://github.com/gnuradio/gnuradio/assets/19860638/4e9afe62-54ba-44a2-9445-3be8ab2a9a39)|![grafik](https://github.com/gnuradio/gnuradio/assets/19860638/e1412122-22d8-437b-9096-daf1f2d9f986)|![grafik](https://github.com/gnuradio/gnuradio/assets/19860638/0c6d3c30-66e2-4cf9-a55a-8252e1909f78)
For RFNoC loopback flow graphs which require data from the host, and without the time_spec option, one cannot guarantee that the host is ready to provide samples by the time the RFNoC graph is started. The time_spec allows to set a delay which can …
=> gr-uhd: RFNoC Rx-Streamer: Add start stream options

grc/core/io/yaml.py, grc/core/platform.py
This significantly speeds up creation of the block cache, where libyaml is built in to Python yaml. The cache is almost unnecessary.
The previous code noted whether `yaml.__with_libyaml__` was defined, but did not actually use the C loader.
GRC
Ran both branches, noted speed.
=> grc: use yaml.CSafeLoader for performance if available

grc/core/Constants.py, grc/core/platform.py
```
242c8ebf6 (Martin Braun, 9 minutes ago)
grc: Check flow graph format version
The constant FLOW_GRAPH_FILE_FORMAT_VERSION is now used as a check while 
opening flow graphs. If a flow graph is opened which exceeds the 
FLOW_GRAPH_FILE_FORMAT_VERSION known to this version of GRC, then the 
assumption is that the .grc file was created with a later version of GRC, 
and can't be opened in this version of GRC. In this case, the loading is 
aborted.
42ba2ccb7 (Martin Braun, 9 minutes ago)
grc: Remove superfluous import
```
GRC file management.
Attempt to open a flow graph that's from the future:
Old FG:
(it still opens)
=> grc: Check flow graph format version

.github/ISSUE_TEMPLATE/bug_report.yml
User should be trying the new QT GRC, but they couldn't tag issues as related to that themselves.
This allows them to choose the branch.
=> Github: add feature-grc-qt as branch option for issue templates

gnuradio-runtime/python/pmt/bindings/pmt_python.cc, gnuradio-runtime/python/pmt/qa_pmt.py
By default, pybind allows `None` to be passed in for `std::shared_ptr` arguments:
https://pybind11.readthedocs.io/en/stable/advanced/functions.html#allow-prohibiting-none-arguments
`pmt_t` happens to be a `std::shared_ptr`, so `None` can be passed into various PMT functions. But nearly all of the underlying C++ functions crash when the input is a null pointer:
```
$ python3
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pmt
>>> pmt.is_bool(None)
Segmentation fault (core dumped)
```
In GNU Radio 3.8 this wasn't an issue, because Swig didn't allow `None`:
```
$ python3
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for …
```
=> pmt: Disallow None for pmt_t arguments in Python

gr-fec/lib/cc_decoder_impl.cc
Changes requirement for "k=2" to "k=7"
Noted in https://github.com/gnuradio/gnuradio/pull/6926 comments
Fixes #6938
CC Decoder
=> fec: fix incorrect runtime error message

cmake/Modules/GrMinReq.cmake
Even 3.7 is EOL at this point, so we may bump again. 3.7 allows the usage of certain type checking features.
Required for suggestions for #6964.
[Python release status](https://devguide.python.org/versions)
=> Python: minimum version 3.7.2, was 3.6.5

.github/workflows/make-test.yml, tox.ini
I've been a bit annoyed by the fact that my neovim + pylsp would not complain about the same formatting as the CI.
Adding this instructs the pycodestyle as used by pylsp to adopt the same style.
None directly, hopefully future Python quality
=> project: add tox.ini, so that editors use the same formatting as github CI

gr-blocks/python/blocks/msg_pair_to_var.py, gr-blocks/python/blocks/qa_msg_pair_to_var.py
This also adds the missing unit test.
The block was logging using gr.log.warn. It should have been logging using its own logger!
also, no unit tests makes me sad.
#6799 looked at the block, and so I looked at the block, and was met with the above issues
/
=> blocks: msg_pair_to_var: Log with block logger, not gr.log

cmake/Modules/GrMinReq.cmake
=> Python: minimum version 3.7.2, was 3.6.5 (backport to maint-3.10)

.github/workflows/make-test.yml, tox.ini
=> project: add tox.ini, so that editors use the same formatting as github CI (backport to maint-3.10)

gr-filter/python/filter/qa_fir_filter.py
VOLK recently accepted https://github.com/gnuradio/volk/pull/709, which fixes truncate-toward-zero distortion in `volk_32f_x2_dot_prod_16i`. Unfortunately, this causes test failures:
```
FAIL: test_fir_filter_fsf_001 (__main__.test_filter)
File "/home/argilo/prefix_311/src/gnuradio/gr-filter/python/filter/qa_fir_filter.py", line 173, in test_fir_filter_fsf_001
self.assertComplexTuplesAlmostEqual(expected_data, result_data, 5)
File "/home/argilo/prefix_311/src/gnuradio/gnuradio-runtime/python/gnuradio/gr_unittest.py", line 73, in assertComplexTuplesAlmostEqual
return all([
File …
```
=> filter: Accept rounded output from fir_filter_fsf

gr-qtgui/grc/qtgui_range.block.yml, gr-qtgui/grc/qtgui_rfnoc_f15_display.block.yml
When a QT GUI Range block is added to the canvas in GRC, there is a noticeable delay, which does not occur for other blocks. This happens because `from gnuradio.qtgui import Range, RangeWidget` causes a large number of shared libraries to be loaded. The import is unnecessary, because the flow graph template already imports `gnuradio.qtgui`:
https://github.com/gnuradio/gnuradio/blob/53de3dd32a9fc9ba1fa4e834487749340a6859a3/grc/core/generator/flow_graph.py.mako#L24-L30
The import can also cause a crash on Windows, as noted in #6914.
Note: The QT GUI RFNoC Fosphor Display (Byte Vector) block has the same bug, ~~but I'll fix that in a separate PR to make backporting simpler. (The block is not present in GNU Radio 3.10.)~~ **Update: The QT GUI RFNoC Fosphor Display (Byte Vector) block was in …
=> qtgui: Remove unnecessary imports from templates

gr-blocks/python/blocks/qa_msg_pair_to_var.py
Also, fix minor stylistic and include issues
`test_calling` was effectively only leaving 5 ms for thread wakeup, message delivery and python function calling; that was very flaky in high-load CI environments.
Fixes #6981
CI
Will test in CI.
=> blocks: msq_pair_to_var QA: wait up to 1 s.

gr-fec/include/gnuradio/fec/rs.h, gr-fec/lib/reed-solomon/ccsds.h, gr-fec/lib/reed-solomon/char.h, gr-fec/lib/reed-solomon/decode_rs_ccsds.c, gr-fec/lib/reed-solomon/encode_rs_ccsds.c, gr-fec/lib/reed-solomon/fixed.h
This solves #4454. The `(en|de)code_rs_(char|8)` functions are marked as FEC_API so that they can be used by OOT modules. The `(en|de)code_rs_ccsds` functions should also be marked as FEC_API.
This is related to #3821. When building with MSVC, the compiler gives an error if FEC_API is attached to a function definition. It should be attached to function declarations only.
I have done some clean up to mark all this functions as FEC_API consistently. They are declared with FEC_API in   `include/gnuradio/fec/rs.h`, but the implementation was not including this file, so I have included it now in all the relevant places. This allows to remove some redundant declarations from char.h and fixed.h.
I have also added include guards in include/gnuradio/fec/rs.h. The .h files in reed-solomon/ don't …
=> fec: add FEC_API to CCSDS Reed-Solomon functions

gr-blocks/include/gnuradio/blocks/rotator.h, gr-blocks/lib/multiply_by_tag_value_cc_impl.cc, gr-blocks/lib/multiply_const_impl.cc, gr-blocks/lib/multiply_matrix_impl.cc, gr-blocks/lib/phase_shift_impl.cc, gr-blocks/python/blocks/bindings/rotator_python.cc, gr-digital/include/gnuradio/digital/adaptive_algorithm_cma.h, gr-digital/include/gnuradio/digital/adaptive_algorithm_lms.h, gr-digital/python/digital/bindings/adaptive_algorithm_cma_python.cc, gr-digital/python/digital/bindings/adaptive_algorithm_lms_python.cc, gr-dtv/lib/dvbt/dvbt_reference_signals_impl.cc, gr-dtv/lib/dvbt2/dvbt2_paprtr_cc_impl.cc, gr-dtv/lib/dvbt2/dvbt2_pilotgenerator_cc_impl.cc
**Note:** This draft PR depends on https://github.com/gnuradio/volk/pull/695 being merged, and VOLK 3.1.0 being released. This PR is ready for review now, but I'll leave it as a draft until VOLK 3.1.0 is out.
Passing `lv_32fc_t` arguments by value results in Undefined Behaviour, as explained in https://github.com/gnuradio/volk/issues/442. To avoid this, we use VOLK 3.1.0's updated API, where `lv_32fc_t` arguments are passed in using pointers.
Three of the affected `volk_32fc_s32fc_multiply_32fc` calls (all in gr-dtv) did not actually use a complex scalar, so I switched those calls to `volk_32f_s32f_multiply_32f` instead.
Fixes #6300.
Fixes https://github.com/gqrx-sdr/gqrx/issues/781.
VOLK issue: https://github.com/gnuradio/volk/issues/442
VOLK PR: https://github.com/gnuradio/volk/pull/695 …
=> Use pointers to pass s32fc arguments to VOLK

gr-blocks/python/blocks/msg_pair_to_var.py, gr-blocks/python/blocks/qa_msg_pair_to_var.py
=> blocks: msg_pair_to_var: Log with block logger, not gr.log (backport to maint-3.10)

grc/core/Connection.py, grc/core/utils/descriptors/_lazy.py
This fixes an issue where virtual blocks can not correctly update their type when connected to message sources/sinks.
Well, it fixes the example in #7013.
Aah, this reminds me of the good old SWIG days, where I would modify .i files without knowing what I'm doing. This is what this feels like, except this time, thought I was pretty decent at Python.
@haakov @sdh11 @skoslowski  if you wouldn't mind taking a look at this. What did I do here? Is this really a fix?
Update: OK, I see now what's going on. Well, mostly. `lazy_property` sets a value once, the first time it's read. Something in the edge-prop PR causes the `domain` attribute of a port to get set before everything is resolved, which is latched into the 'lazy property'.
I don't think `lazy_property` is necessary here, it seems a bit …
=> grc: Make core.Connection.type not lazy

gr-network/python/network/qa_tcp_sink.py
On the sparc64 architecture, GNU Radio's circular buffers seem to be completely broken. (I'll open an issue for this, and have a look later to see if I can track down the root cause.) This causes most tests to fail. But `qa_tcp_sink` hangs, forcing the Debian build server to wait for 10 hours:
```
Start 261: qa_tcp_sink
E: Build killed with signal TERM after 600 minutes of inactivity
```
QA test for TCP Sink.
I verified that the test still passes, and that it exits after 30 seconds if I comment out the final `self.tb.start()` and `self.tb.stop()` lines to induce a hang.
=> network: Add timeout to prevent qa_tcp_sink from hanging

gr-dtv/python/dtv/qa_dtv.py
The `qa_dtv` test compares the output of a DTV flowgraph with expected data stored in `vv009-4kfft.cfile`. The data in that file is little-endian, but it is loaded using the machine's endianness. This results in test failures on big-endian architectures. To fix this, I've changed the code to load this file as little-endian.
Fixes #7015.
QA test for gr-dtv.
I ran the updated test on x86_64 and s390x, and it now passes on both architectures.
=> dtv: Read expected data as little-endian

gnuradio-runtime/gnuradio-runtime.conf.in
As noticed by @argilo in #6673, this was a mistake. We shouldn't be using a log level string not defined in logger.cc.
logging!
=> runtime: config.in used undefined log level

gr-fec/lib/async_decoder_impl.cc, gr-fec/lib/async_encoder_impl.cc, gr-fec/lib/tagged_decoder_impl.cc
The `test_async_00` test in `qa_fecapi_repetition.py` consistently fails on Debian i386. The root cause is that the FEC Async Decoder block calculates the output frame length using floating-point arithmetic, then converts the result to an integer without rounding. Floating-point error causes the result to be slightly less than 240, which is truncated to 239, shaving one bit/byte off the end of each frame. Adding `std::lround` fixes the problem.
The FEC Async Encoder and FEC Tagged Decoder blocks have similar errors, so I've fixed those as well.
Fixes #7022.
* FEC Async Decoder
* FEC Async Encoder
* FEC Tagged Decoder
I ran the test suite to verify that the tests pass reliably on both x86_64 and i386.
=> fec: Round before converting frame lengths to int

gr-analog/lib/agc3_cc_impl.cc
While experimenting with using `host_buffer` as a fallback for `buffer_double_mapped`, I noticed that `qa_agc` fails because `agc3_cc` overruns its input and output buffers: https://github.com/gnuradio/gnuradio/issues/7021#issuecomment-1871212351. This happens because its work function expects `noutput_items` to be a multiple of `iir_update_decim`, but its call to `set_output_multiple` is immediately overwritten by a call to `set_alignment`, which overwrites the output multiple with `volk_get_alignment() / sizeof(gr_complex)` (which could be 1, 2, 4, or 8, depending on the machine type). If `iir_update_decim` does not divide this number, then buffer overruns occur because the `work` function processes `ceil(noutput_items / iir_update_decim) * iir_update_decim` items.
* AGC3
I ran `qa_agc` …
=> analog: Fix buffer overruns in AGC3

gnuradio-runtime/include/gnuradio/fxpt_nco.h, gnuradio-runtime/include/gnuradio/fxpt_vco.h, gnuradio-runtime/lib/math/qa_fxpt_nco.cc, gnuradio-runtime/python/gnuradio/gr/bindings/fxpt_nco_python.cc, gnuradio-runtime/python/gnuradio/gr/bindings/fxpt_vco_python.cc
As noted in #7047, several functions in `gr::fxpt_nco` and `gr::fxpt_vco` invoke Undefined Behaviour because they allow arithmetic overflows to occur on signed integers. The arithmetic is intended to be modular (since the integers represent phase angles), so we can achieve the same result without Undefined Behaviour by casting the integers to unsigned before performing the arithmetic.
Fixes #7047.
* `fxpt_nco` class
* `fxpt_vco` class
* VCO block
* VCO (complex) block
I verified that the VCO and VCO (complex) blocks still work correctly after the changes, and that GCC's Undefined Behaviour Sanitizer no longer reports signed integer overflows while these blocks run.
I also noticed that the broken `fxpt_nco` functions were untested, so I extended the `t0` test case to exercise them in a way …
=> runtime: Fix signed integer overflow in fixed-point NCO and VCO

gnuradio-runtime/lib/pmt/pmt.cc
If GNU Radio is built with GCC's Undefined Behaviour Sanitizer, then the following error appears when running qa_pdu_split:
```
/home/argilo/prefix_311/src/gnuradio/gnuradio-runtime/lib/pmt/pmt.cc:889:19: runtime error: null pointer passed as argument 1, which is declared to never be null
/home/argilo/prefix_311/src/gnuradio/gnuradio-runtime/lib/pmt/pmt.cc:889:19: runtime error: null pointer passed as argument 2, which is declared to never be null
```
The line that triggers this is the following:
https://github.com/gnuradio/gnuradio/blob/86af478a88cf0521b023ad2c924c74ea38d9adcf/gr-pdu/python/pdu/qa_pdu_split.py#L96
We can avoid Undefined Behaviour by short-circuiting the `memcmp` if `len_x` is zero.
`pmt::equal`
I verified that the test passes without UBSAN warnings after the change.
=> pmt: Check length before calling memcmp

gnuradio-runtime/python/pmt/qa_pmt_to_python.py, gr-blocks/python/blocks/qa_multiply_matrix_xx.py, gr-iio/python/iio/__init__.py, gr-iio/python/iio/qa_iio.py, gr-zeromq/python/zeromq/qa_zeromq_sub.py
While running the test suite (with `ctest -V`), several deprecation warnings can be seen:
qa_pmt_to_python:
```
/usr/lib/python3.10/unittest/case.py:549: DeprecationWarning: `alltrue` is deprecated as of NumPy 1.25.0, and will be removed in NumPy 2.0. Please use `all` instead
```
qa_multiply_matrix_xx:
```
/home/argilo/prefix_311/src/gnuradio/gr-blocks/python/blocks/qa_multiply_matrix_xx.py:55: PendingDeprecationWarning: the matrix subclass is not the recommended way to represent matrices or deal with linear algebra (see https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html). Please adjust your code to use regular ndarray.
X_in = numpy.matrix(X_in)
/home/argilo/prefix_311/src/gnuradio/gr-blocks/python/blocks/qa_multiply_matrix_xx.py:56: PendingDeprecationWarning: the matrix …
```
=> qa: Fix deprecation warnings in tests

gr-fec/lib/polar_encoder.cc
I made some experimental changes to the block executor to detect buffer overruns, and found that the polar encoder overruns its input buffer by one byte when running in packed mode. The `insert_packed_frozen_bits_and_reverse` method increments the bit number at the end of each loop iteration, then reads the next byte if the bit number is a multiple of 8. This occurs on the last iteration of the loop, causing an extra byte to be read that will never be used.
To solve the problem, I moved byte loading up to the start of the loop, so that a byte is only loaded if one of its bits will actually be used.
* POLAR Encoder
I verified that the polar encoder tests still pass, and that my modified block executor no longer triggers a buffer overrun.
=> fec: Fix input buffer overrun in polar encoder

gr-analog/lib/agc3_cc_impl.cc, gr-analog/python/analog/qa_agc.py
In #6624 a `max_gain` parameter was added to AGC3, but `agc3_cc::make` doesn't pass it through to the block constructor. Here I've added the pass-through, and also added a test which verifies that the values make it through.
Fixes #6955.
* AGC3
I verified that the test fails without the change, and passes with it.
=> analog: Pass through max_gain parameter in agc3_cc::make

gr-qtgui/lib/ber_sink_b_impl.cc
The QT GUI Bercurve Sink displays BER curves for its inputs, as well as a reference curve showing the BER of BPSK in an AWGN channel. The formula for this reference curve was accidentally broken in 9ae5d4cd3da84ce7e5a0c2abe7fec1ff8d229ae8, when `boost::math::erfc` was replaced with `std::erf` (which should have been `std::erfc`).
* QT GUI Bercurve Sink
The `gr-fec/examples/ber_curve_gen.grc` example is currently broken, but can be fixed with the following workarounds:
* https://github.com/gnuradio/gnuradio/issues/5627#issuecomment-1060608139
* Revert https://github.com/gnuradio/gnuradio/pull/6889
I also modified the example to remove the "Dummy" curve, which would otherwise obscure the BPSK AWGN curve.
Before:
After:
=> fec: Fix BPSK AWGN formula

grc/core/generator/top_block.py
This removes a superfluous call to `Connection.__init__()` in the top block generator which uses itself as a parent, instead of the original flowgraph as elsewhere in the same file. 0fd504e5 changed the Connection object such that passing in a parent that is not an Element is no longer valid.
Fixes #7059 
GRC + Bus Ports
Used the same FG from #7059 to test both crash and fix. Also, just by looking at the code, this seems like a safe change as the `connection` object was used nowhere.
=> grc: Fix compilation of bus ports

gnuradio-runtime/gnuradio-runtime.conf.in
=> runtime: config.in used undefined log level (backport to maint-3.10)

gr-blocks/lib/null_source_impl.cc
In 92b01e30373e6ed36d1067e2bcba661d2253f34a, the Null Source was extended to support multiple outputs. But its `work` function iterates over inputs instead of outputs, so it doesn't write any output. It only gets away with this because double-mapped buffers are initialized to zero. But as noted in https://github.com/gnuradio/gnuradio/issues/7041#issuecomment-1881100761, this is not true of all buffer implementations, so Null Sink should write zeroes to its outputs.
Fixes #7041.
* Null Source
I added a log message inside the `work` loop to verify that `memset` was being invoked.
=> blocks: Fix loop bound in Null Source

grc/core/generator/cpp_top_block.py
Remove unneeded (and failing) access of `fg.parent_platform` for connections.
Split out from #7072 for quick merge.
=> grc: fix C++ gen with busports

grc/core/Config.py
The copyright date displayed in GRC was last updated in 2021 (#4451) so we're due for an update.
GRC "Help -> About"
=> grc: Update copyright date

grc/core/blocks/block.py, grc/gui/Application.py
The "More -> Toggle Source Bus" and "More -> Toggle Sink Bus" options in GRC's context menu are enabled whenever any blocks are selected, regardless whether those blocks actually have any source or sink ports. Selecting "Toggle Source Bus" for a block that doesn't have any source ports will create a useless bus of length zero, and the same for "Toggle Sink Bus".
To fix this, I've changed the context menu so that "Toggle Source Bus" is only enabled if at least one of the selected blocks has a source port, and "Toggle Sink Bus" is only enabled if at least one of the selected blocks has a sink port.
Since not all of the selected blocks will necessarily have the required ports, I also changed `Block.bussify` to check whether the current block has at least one port of the required type before …
=> grc: Only bussify blocks that have ports

cmake/Modules/GrPython.cmake
Without this, Python 3.12 warns about a SyntaxWarning, because it
doesn't know of an escape sequence '\W'.
Unlike incorrectly speculated in #7036, this has nothing to do with the regex engine – it's a string literal warning!
We can disable replacement of escape sequences (and things that look like escape sequences) by using a Python raw string `r'…'` literal.
Fixes #7036
none, because the warning nonwithstanding, Python just leaves unknown escape sequences alone.
Builds as before, warnings on Fedora rawhide (pre-40) now gone
=> cmake/GrPython: cmake converts \\ to \ already, so use py raw string

gr-blocks/lib/peak_detector2_fb_impl.cc
I made some experimental changes to the block executor to detect buffer overruns, and found that Peak Detector2 sometimes produces an extra sample on its "debug" output port without reporting it to the scheduler.
Peak Detector2 has an optional debug output which can be used to view the internal estimated mean (`d_avg`). When a peak is detected at sample `i` in the main loop, the `work` function exits early and reports to the scheduler that it has produced `i` samples (i.e. `optr[0]` through `optr[i-1]` and `sigout[0]` through `sigout[i-1]`). However, it writes all the way up to `sigout[i]` on the debug output, producing a total of `i+1` samples.
When the scheduler then invokes the `work` function a second time and the `d_found == true` loop is executed, the block skips writing `sigout[0]` …
=> blocks: Write debug samples at the correct time in Peak Detector2

gr-blocks/grc/blocks_float_uchar.block.yml, gr-blocks/include/gnuradio/blocks/float_to_uchar.h, gr-blocks/lib/float_array_to_uchar.cc, gr-blocks/lib/float_to_uchar_impl.cc, gr-blocks/lib/float_to_uchar_impl.h, gr-blocks/python/blocks/bindings/docstrings/float_to_uchar_pydoc_template.h, gr-blocks/python/blocks/bindings/float_to_uchar_python.cc, gr-blocks/python/blocks/qa_type_conversions.py, gr-fec/lib/async_decoder_impl.cc, gr-fec/lib/async_decoder_impl.h, gr-fec/python/fec/extended_decoder.py, gr-fec/python/fec/extended_tagged_decoder.py
The kernel `volk_32f_s32f_x2_convert_8u()` has been added to Volk 3.1. This PR contains 3 commits that take advantage of this kernel, maintaining backwards compatibility by providing ad-hoc alternatives with earlier Volk versions. The changes are:
1. The kernel is now used in gr-fec async_decoder if possible. This was marked as a TODO.
2. vlen, scale and bias parameters have been added to gr-blocks float_to_uchar. This makes float_to_uchar more similar to float_to_char. Since the Volk conversion kernel supports scale and bias, it is used when possible.
3. In gr-fec extended_decoder and extended_tagged_decoder, the scale and bias parameters of float_to_uchar are used instead of adding separate multiply_const and add_const blocks.
Commit 3 requires commit 2, and commit 1 is independent of …
=> Use Volk kernel volk_32f_s32f_x2_convert_8u

gr-utils/modtool/cli/bind.py, gr-utils/modtool/cli/disable.py, gr-utils/modtool/cli/makeyaml.py, gr-utils/modtool/cli/rename.py, gr-utils/modtool/cli/rm.py, gr-utils/modtool/core/base.py, gr-utils/modtool/core/rename.py
[`get_block_candidates`](https://github.com/gnuradio/gnuradio/blob/6404f371abb97f282aa1aa270837ffa9f0ddce84/gr-utils/modtool/core/base.py#L25-L39) function is used in `gr_modtool` to detect blocks in the OOT module. However, the current implementation only detects C++ blocks, because the pattern for Python files does not check the directory recursively.
Also, the `rename` subcommand does not check for non-C++ blocks and throws an exception if there are no C++ implementation files for the selected block.
This PR presents the following fixes:
Fixes #7008
gr_modtool
=> gr_modtool: fix non-C++ block detection and manipulation

gr-filter/include/gnuradio/filter/fft_filter.h, gr-filter/lib/fft_filter.cc, gr-filter/python/filter/bindings/fft_filter_python.cc
The doc strings describes the fft filter algorithm as overlap-and-save, but according to gr-filter/lib/fft_filter.cc on line 132, 264, 398 it's overlap-and-add.
fixes #5741
The fft filter header files has misleading information about how the FFT filter is working. Header file says it's overlap-save, but in the .cc file it describes overlap-add as far as I understood.
Fixes #5741
gr-filter
Static code check, compilation of gnuradio
=> Feature/fix fft_filter.h doc string

grc/gui_qt/Utils.py, grc/gui_qt/base.py, grc/gui_qt/components/block_library.py, grc/gui_qt/components/canvas/block.py, grc/gui_qt/components/canvas/flowgraph.py, grc/gui_qt/components/console.py, grc/gui_qt/components/example_browser.py, grc/gui_qt/components/flowgraph_view.py, grc/gui_qt/components/oot_browser.py, grc/gui_qt/components/preferences.py, grc/gui_qt/components/undoable_actions.py, grc/gui_qt/components/variable_editor.py, grc/gui_qt/components/wiki_tab.py, grc/gui_qt/components/window.py
grc has the comman line option --log, which can be set to debug. Doing so enables the debug log in Application.py but not in the depending classes.
For debugging the output of the called classes  would be important,too.
In gtk-grc we have  similar problem. See #4628.
I ported the solution proposed in #4628 to the gui_qt part and it works well for these classes.
#4628
=> grcqt: Improve logging

grc/gui_qt/components/window.py
'Save as' does not affect the tab text. After this change the tab text is changed to the new filename.
'New' creates a new tab and sets the focus to the newly created tab
=> grc-qt: Set tabtext on save as

.github/workflows/make-test.yml
=> CI: Update Fedora workers to F39/40, enable GLIBCXX_ASSERTIONS (backport to maint-3.10)

gnuradio-runtime/python/pmt/bindings/pmt_python.cc, gnuradio-runtime/python/pmt/qa_pmt.py
- PMT: there's no std::any in Python, don't pybind make_any, any_ref, _set
- PMT: don_t wrap C++ pmt_t(pmt_t) functor-consumping PMT map to Python
- PMT: don_t wrap C++ iostreams, std::streambufs to Python
C++ std::any has no correspondent type Python, so we shouldn't wrap it
Same for iostreams, streambuffers, and C functions of std::shared_ptr<pmt_base> to shared_ptr<pmt_base>
Fixes #6967
PMT wrappings that never worked were removed
Actually, tests were removed, namely those that check for type errors for the removed wrappers.
=> PMT: remove wrapping of C++-specific types

grc/gui_qt/components/window.py, grc/gui_qt/resources/available_preferences.yml
The xterm_executable variable was part of Config.py and was removed with #https://github.com/gnuradio/gnuradio/commit/e10de5c71d473a29cb296348165eab2edf3c9c1e.
Replaces #7142
=> grcqt: add missing xterm_executable to qsettings

gr-utils/modtool/templates/gr-newmod/CMakeLists.txt, gr-utils/modtool/templates/gr-newmod/examples/CMakeLists.txt
This PR changes two things about gr_modtool's newmod templates:
1. Change the top-level CMakeLists.txt so that OOT install MANIFEST.md to `$PREFIX/share/gnuradio/manifests/abcdef/MANIFEST-1.2.3git.md` (in gr-abcdef's case), so that [GRC Qt's OOT](https://github.com/gnuradio/gnuradio/issues/7123) browser can find them.
2. Install examples to `$PREFIX/share/gnuradio/examples/abcdef/` such that [GRC Qt's example browser](https://github.com/gnuradio/gnuradio/issues/7117) can find them. (Disclaimer: OOT developers will probably have to add the examples manually, unless we want to glob)
Note: This PR is meant as a suggestion, and I'm very open for other ideas :)
=> modtool: (CMake) Install manifest and examples

gnuradio-runtime/apps/gnuradio-config-info.cc, gnuradio-runtime/include/gnuradio/sys_paths.h, gnuradio-runtime/lib/prefs.cc, gnuradio-runtime/lib/sys_paths.cc, gnuradio-runtime/lib/vmcircbuf_mmap_shm_open.cc, gnuradio-runtime/lib/vmcircbuf_mmap_tmpfile.cc, gnuradio-runtime/lib/vmcircbuf_prefs.cc, gnuradio-runtime/python/gnuradio/gr/CMakeLists.txt, gnuradio-runtime/python/gnuradio/gr/bindings/sys_paths_python.cc, gnuradio-runtime/python/gnuradio/gr/qa_prefs.py, gnuradio-runtime/python/gnuradio/gr/qa_sys_paths.py, gr-fft/lib/fft.cc
- Introduced `gr::paths::` namespace to keep the different path getters
together
- new `cache()` getter, because FFTW wisdom should not clutter the
home directory, but is also not portable state nor portable config
(compare
[`XDG_CACHE_HOME`](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html))
- new path getters return `std::filesystem::path` instead of C string
- deprecated old getters, which now just call the new getters underneath
- Python wrappers
- added a unit test for the paths (was untested so far)
- added prefs path unit test for checking reaction to changing
environment variables (prefs was completely untested)
- Fixed `vmcircbuf_prefs`, fftw wisdom that assumed existence of paths
- Replace deprecated API from in-tree usage
- As some configuration …
=> sys_paths: use XDG_CONFIG_HOME if present, new API

gr-qtgui/grc/qtgui_sink_x.block.yml
Remove num_inputs from Qt GUI Sink block yml file as the sink does not allow multiple inputs and doesn't have num_inputs defined, causing an error when opening a flowgraph that contains the Qt GUI Sink block.
https://github.com/gnuradio/gnuradio/issues/7157
Qt GUI Sink
Error is not seen again after reopening the .grc
Trying to assign a second input to Qt GUI Sink now returns the expected error `Domain "stream" can have only one upstream block`
=> qtgui: remove num_inputs from qtgui_sink_x.block.yml

cmake/Modules/GrPython.cmake
=> cmake/GrPython: cmake converts \\ to \ already, so use py raw string (backport to maint-3.10)

cmake/Modules/GrPython.cmake
=> cmake: Stop installing byte-compiled Python modules (backport to maint-3.10)

grc/core/generator/cpp_hier_block.py, grc/core/generator/cpp_templates/flow_graph.hpp.mako, grc/core/generator/cpp_top_block.py
This PR fixes two issues I found when generating C++ hier blocks with `grcc`:
1. The `--output` argument had no effect on location of generated files; they were always put in the `$HOME/.grc_gnuradio` directory.
2. The generated `make` function (that creates a shared pointer) was not using any parameters as arguments; that resulted in a compile error, because the generated class constructor was using these parameters as arguments.
Note: new `make` function template does not use default values for arguments yet.
GRC generation / `grcc`
Minimal example: [cpp_hier.grc](https://github.com/gnuradio/gnuradio/files/14021893/cpp_hier.grc.txt);  
Command used: `grcc cpp_hier.grc -o ./output_dir`
=> GRC: fix C++ hier block generation

gr-digital/include/gnuradio/digital/constellation_soft_decoder_cf.h, gr-digital/python/digital/bindings/constellation_soft_decoder_cf_python.cc, gr-soapy/include/gnuradio/soapy/sink.h, gr-soapy/include/gnuradio/soapy/source.h, gr-soapy/python/soapy/bindings/sink_python.cc, gr-soapy/python/soapy/bindings/source_python.cc
Fix remaining Doxygen warnings.
None
Documentation
Build is now clean.
- [ x] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [ x] I have squashed my commits to have one significant change per commit. 
- [ x] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed)
- [ x] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md).
=> docs: More Doxygen cleanup.

gnuradio-runtime/python/pmt/bindings/pmt_python.cc, gnuradio-runtime/python/pmt/qa_pmt.py
=> PMT: remove wrapping of C++-specific types (backport to maint-3.10)

gr-qtgui/grc/qtgui_sink_x.block.yml
=> qtgui: remove num_inputs from qtgui_sink_x.block.yml (backport to maint-3.10)

gr-filter/include/gnuradio/filter/fft_filter.h, gr-filter/lib/fft_filter.cc, gr-filter/python/filter/bindings/fft_filter_python.cc
=> gr-filter: fix misinformation in doc string for fft_filter.h (backport to maint-3.10)

grc/gui_qt/components/window.py
If a recently used grc file was deleted, grc does not start anymore.
```
File "/usr/local/gnuradio/lib64/python3.11/site-packages/gnuradio/grc/gui_qt/components/window.py", line 166, in __init__
self.open_triggered(file)
File "/usr/local/gnuradio/lib64/python3.11/site-packages/gnuradio/grc/gui_qt/components/window.py", line 940, in open_triggered
initial_state = self.platform.parse_flow_graph(filename)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/gnuradio/lib64/python3.11/site-packages/gnuradio/grc/core/platform.py", line 337, in parse_flow_graph
with open(filename, encoding='utf-8') as fp:
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "<frozen codecs>", line 918, in open
FileNotFoundError: [Errno 2] Datei oder Verzeichnis nicht gefunden: '/tmp/missingtest.grc'
```
=> grcqt: avoid FileNotFoundError on grc startup

grc/gui_qt/components/canvas/block.py
Use modulo 360 for block rotation in Qt GRC
Fixes #7200
=> grc-qt: Keep block rotation in [0.0, 360)

gnuradio-runtime/lib/tpb_thread_body.cc
Hopefully makes debugging flowgraphs that drop messages easier.
Print the dropping port and name of the block when dropping messages.
Closes #5960 
(which we hoped would be picked up by beginners, but the adoption rate of `good
first issue`s by people actually willing to be a net benefit is quite low, it
seems. We have had a few great, but most just ghost us the moment we tell them
we expect them to compile software when contributing to a C++ project; smhw…)
runtime
=> runtime: print block names on message discard

grc/gui_qt/components/canvas/block.py, grc/gui_qt/components/canvas/port.py
Blocks rotated 180 degrees are visually upside-down, the same for the ports label.
This is fixed by checking whether the parent block is 180 degrees rotated and thus adjusting the painter to draw text.
Fix #7203
Minor-Issue of #6957 
grc-qt/component/canvas
Did UI test
=> grc-qt: fix  Blocks rotated 180° are upside down

grc/gui_qt/components/canvas/port.py
The PR  #7206 fixes the upside issue and port labels in blocks with only one sink (in) port. 
Unexpectedly, for multiple sinks (in) ports, the port labels are not aligned properly.
Check the left image (before) and right (after) of this PR's commits.
#7203
gui_qt/components/canvas
Did UI Test
=> grc-qt: fix sink ports labels alignment after 180 rotation

gnuradio-runtime/lib/tpb_thread_body.cc
=> runtime: print block names on message buffer overflow discard (backport to maint-3.10)

gr-fec/lib/polar_decoder_common.cc
=> fec/polar decoder: replaced cout/printf with fmt::print (backport to maint-3.10)

gnuradio-runtime/lib/vmcircbuf_prefs.cc, gr-fft/lib/fft.cc
Iterating while creating subdirs in a path was causing problems for MinGW, an is not necessary. Replace with `create_directories()`.
Also use the same fopen() parameters with or without _MSC_VER.
Fixes #7156
- runtime vmcircbuf config
- fft
=> runtime and fft: use create_directories() instead of iterating

gnuradio-runtime/lib/vmcircbuf_createfilemapping.cc
MinGW reports several warnings while building `vmcircbuf_createfilemapping.cc`:
```
D:/a/_temp/gnuradio/gnuradio-runtime/lib/vmcircbuf_createfilemapping.cc: In constructor 'gr::vmcircbuf_createfilemapping::vmcircbuf_createfilemapping(size_t)':
D:/a/_temp/gnuradio/gnuradio-runtime/lib/vmcircbuf_createfilemapping.cc:91:16: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
91 |         werror("gr::vmcircbuf_mmap_createfilemapping: VirtualAlloc", GetLastError());
|                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
D:/a/_temp/gnuradio/gnuradio-runtime/lib/vmcircbuf_createfilemapping.cc:97:16: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
97 |         werror("gr::vmcircbuf_mmap_createfilemapping: …
```
=> runtime: Fix compiler warnings

gr-audio/lib/windows/windows_sink.cc, gr-audio/lib/windows/windows_sink.h, gr-audio/lib/windows/windows_source.cc
MinGW reports several warnings while building `windows_source.cc` and `windows_sink.cc`:
```
[312/403] Building CXX object gr-audio/lib/CMakeFiles/gnuradio-audio.dir/windows/windows_source.cc.obj
D:/a/_temp/gnuradio/gr-audio/lib/windows/windows_source.cc: In member function 'virtual int gr::audio::windows_source::work(int, gr_vector_const_void_star&, gr_vector_void_star&)':
D:/a/_temp/gnuradio/gr-audio/lib/windows/windows_source.cc:170:35: warning: comparison of integer expressions of different signedness: 'int' and 'DWORD' {aka 'long unsigned int'} [-Wsign-compare]
170 |                 for (int j = 0; j < buffer_length; j++) {
|                                 ~~^~~~~~~~~~~~~~~
D:/a/_temp/gnuradio/gr-audio/lib/windows/windows_source.cc:179:35: warning: comparison of integer expressions …
```
=> audio: Fix compiler warnings

gnuradio-runtime/lib/realtime_impl.cc
MinGW reports the following warning in `realtime_impl.cc`:
```
D:/a/_temp/gnuradio/gnuradio-runtime/lib/realtime_impl.cc:40:12: warning: 'int gr::realtime::rescale_virtual_pri(int, int, int)' defined but not used [-Wunused-function]
40 | static int rescale_virtual_pri(int virtual_pri, int min_real_pri, int max_real_pri)
|            ^~~~~~~~~~~~~~~~~~~
```
This happens because the `#if` condition that determines whether `rescale_virtual_pri` is compiled does not match the subsequent `#if` / `#elseif` conditions that determine whether it is used. When building with MinGW, both Windows threads and POSIX threads are available, exposing the mismatch.
Here I've fixed the first `#if` condition to match.
Realtime scheduling
I verified that the compiler warnings are gone.
Before: …
=> runtime: Fix conditional compilation of rescale_virtual_pri

gnuradio-runtime/python/pmt/pmt_to_python.py, gnuradio-runtime/python/pmt/qa_pmt_to_python.py, gr-filter/python/filter/design/filter_design.py
Use the canonical cdouble instead of the platform-depended complex128 in the filter designer and pmt-to-python code.
The same should be done for complex64 (csingle). This is used more widely in the code, and is also used as a string, so we can address it separately.
Fixes #7227 
Filter designer tool. Also pmt-to-python.
=> Replace scipy/numpy.complex128 with cdouble

gr-utils/modtool/tools/util_functions.py
For OOT modules create with API Post-3.8, when using GR v3.10, will fail to find blocks using regex due to an invalid file path.  This is due to the header files moving from `/include/modname/...` to `/include/gnuradio/modname`.
This pr modifies the `get_block_names` function to search the  folder which has not changed between API Post-3.8 and Post-3.10.
Fixes #7169
- gr-modtool
Tested various functions in gr_modtool:
- newmod
- add
- bind
- rm 
Specifically the functions that call `get_block_names` are `bind` and `rm`
These were tested on modules created using API Post-3.8 (GR v3.9) and using API Post-3.10 (GR v3.10).  
The program works as expected in all of these cases for both API versions. The bind command with no arguments properly parses the existing blocks and generates the …
=> gr-modtool: Handle regex in get_block_names for OOT API Post-3.8

grc/gui_qt/Config.py
Preferences contains a custom_block_paths setting. But this setting is not used to find a block.
Set the custom_block_paths in preferences. Restart grc and have a look at grc.log to see the block_paths.
=> grc-qt: custom_block_paths set but not used

gr-utils/modtool/templates/gr-newmod/CMakeLists.txt
The manifest format generated by modtools has changed to YAML but the CMakeLists.txt file was still looking for a md file.
Fixes #7242 
modtool
=> modtool: update CMakeLists.txt template to use new yml vs md format

gr-audio/grc/audio_sink.block.yml
Fix a typo in #7244. Was fixed already in backport #7248.
=> gr-audio: yml file has a comma where there should be a space

grc/gui_qt/components/block_library.py, grc/gui_qt/components/console.py, grc/gui_qt/components/variable_editor.py, grc/gui_qt/components/wiki_tab.py, grc/gui_qt/components/window.py, grc/gui_qt/grc.py, grc/gui_qt/resources/available_preferences.yml, grc/main.py
In View-> Panels four panels can be enabled and disabled. But these settings are not saved and restored.
This is done now
Run grc --qt
View-> Panels
Disable some panels and restart
=> grc_qt: save panel settings

gr-utils/modtool/templates/templates.py
Removes the colon in the default block yaml parameter label.  
The presence of this colon causes the default generated block to throw an obscure error: "FlowGraph Error: mapping values are not allowed in this context"
With the colon removed, the FIX ME message renders correctly. Note that the colon itself is unnecessary, since grc renders parameter labels with a colon after it automatically. If you quote the label, then grc shows "FIX ME::".
Default behavior:
```
gr_modtool add test
<compile the block>
<open grc>
```
And you get `FlowGraph Error: mapping values are not allowed in this context` and the block fails to appear.
After removing the colon it works fine.
=> gr_modtool: remove colon in block yaml label

grc/gui_qt/components/canvas/connection.py, grc/tests/test_qtbot.py
Fix AttributeError while deleting connection with double click
Fixes https://github.com/gnuradio/gnuradio/issues/7269
`grc/gui_qt/components/canvas/connection.py`
- Manual gui test
- Automated gui testing with `pytest grc/tests/test_qtbot.py`
=> fix double click connection to delete for qt gui

gnuradio-runtime/apps/gnuradio-config-info.cc
=> runtime/gnuradio-config-info: print unquoted path for userconfdir (backport to maint-3.10)

gnuradio-runtime/python/gnuradio/gr/bindings/CMakeLists.txt, gnuradio-runtime/python/gnuradio/gr/bindings/python_bindings.cc, gr-blocks/python/blocks/bindings/CMakeLists.txt, gr-blocks/python/blocks/bindings/python_bindings.cc, gr-fft/python/fft/bindings/CMakeLists.txt, gr-fft/python/fft/bindings/python_bindings.cc
Previously, the python bindings would be built even if ctrlport was disabled, which leads to missing symbols at python module load time
@balister reported test failures in his (presumably OE) build, https://matrix.to/#/!UHlAIKBoAIYHCdpjhE:gnuradio.org/$5y-GtVnb-osx1HDJbaylVVuEf_guIxbiQHrul3zHlNc?via=gnuradio.org&via=t2bot.io&via=matrix.org
```
Python 3.10.13 (main, Aug 24 2023, 12:59:26) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from gnuradio import gr
File "/usr/lib/python3.10/site-packages/gnuradio/gr/__init__.py", line 26, in <module>
from .gr_python import *
ImportError: /usr/lib/python3.10/site-packages/gnuradio/gr/gr_python.cpython-310-aarch64 …
```
=> ctrlport probes: only pybind if ctrlport enabled

grc/gui_qt/components/example_browser.py, grc/gui_qt/components/oot_browser.py
Don't error or stop when a manifest directory or example directory is missing.
In the case of a missing manifest directory, this currently happens with the conda package because the build doesn't install any files into that directory and so conda skips including an empty directory in the package.
In the case of a missing example directory, the current behavior just stops processing example directories when one specified doesn't exist. That includes valid directories that may appear later in the list! This change simply skips the missing directory and continues to process what remains in the list. A missing directory can easily occur if the one specified in the config file is invalid or empty.
grc-qt
I added these patches into my latest conda-forge package and confirmed that they fix an …
=> grc-qt: Make more robust for to missing manifest dir and example paths

grc/gui/Executor.py, grc/gui_qt/components/executor.py
The joined argument string is only useful for logging; some terminal
emulators seem to accept it (which probably means they pass their one
argument to a shell), others fail (gnome-terminal, alacritty, …).
By splitting the arguments, this should work on all terminal emulators.
Closes #7289
GRC GTK & Qt
Tested against xterm and alacritty, the former still works, the latter
now works.
=> GRC: when passing arguments to terminal emulator: individually

grc/gui_qt/components/window.py
If you try closing GRC Qt while an unsaved flowgraph is open, the "Save flowgraph?" dialog appears. This is the correct behaviour, but the Cancel button doesn't stop the exit process if the close event originated from the window manager (pressing the X in the top right corner, for example). 
Closing GRC Qt with Ctrl+Q and Mod+Q
=> grc-qt: Don't close GRC if the user cancels the exiting action

grc/gui_qt/components/canvas/port.py, grc/gui_qt/components/window.py
See https://github.com/gnuradio/gnuradio/issues/7295. Ports of missing blocks are instantiated after the actual block: https://github.com/gnuradio/gnuradio/blob/72e21b54c44c360d511371420e74be4a6b2bfda6/grc/core/FlowGraph.py#L494
Missing blocks that do not have connections are not affected. 
https://github.com/gnuradio/gnuradio/issues/7295
GRC Qt ports
=> grc-qt: Don't throw error when missing blocks have connections

gr-qtgui/python/qtgui/dialcontrol.py
In issue #5107 the Qt GUI dial default seems to be the exact value returned, if the default value is interpreted as the initial knob position, the returned value does not account for the scale factor - until the knob is moved.
Check the issue for more explaination
This PR will fix #5107 
Only the QT GUI Dial is affected. There is no effect on the performance. 
I built and ran the example provided by the issue
previous results are explained in detail here:
https://github.com/gnuradio/gnuradio/issues/5107#issuecomment-932992531
New results:
https://github.com/gnuradio/gnuradio/assets/118675709/9f595841-ce4f-4cae-a21c-1cfd16786aeb
testing case file: 
[qt_gui_dialweirdness.grc.zip](https://github.com/gnuradio/gnuradio/files/7274174/qt_gui_dial_weirdness.grc.zip)
=> gr-gtqui: Fixed Qt GUI Dial - weird behaviour

grc/tests/test_qtbot.py
Fix failed testcase on test_qtbot.py
grc/tests/test_qtbot.py
Before:
After:
command: `pytest grc/tests/test_qtbot.py`
=> fix failed testcase on test_rotate_block

gr-blocks/lib/blockinterleaving.cc, gr-blocks/python/blocks/qa_blockinterleaver_xx.py
This was noticed because of what is probably a stdlib bug that warns
about the result of `[[nodiscard]] std::unique` being discarded.
(`std::unique` has no business being `nodiscard`, imho.)
Looked at the code, it does a sort on a permutation vector just to check
whether it's unique and covers $\{0, …, N-1\}$, and then finally, it does
another sort to construct the deinterleaver taps.
Since this is mathematically simple, the deinterleaver tap at position i
simply being the interleaver position of i, and vice versa, the check
for uniqueness and the deinterleaver construction can be done in one
fell swoop. No sorting required!
Made the tests seeded, so that we don't get flaky tests when the random
generator asked to permute $(0, …, 15)$ happens to emit the first $K$
sorted, i.e., $(0, 1, …, …
=> blocks/blockinterleaving: rework permutation check to suppress warning

gr-iio/python/iio/bindings/attr_updater_python.cc
Fix crash due to broken IIO attribute updater
Flowgraph crashes if IIO attribute is supposed to be updated because callback set_value doesn't exist.
This fixes https://ez.analog.com/linux-software-drivers/f/q-a/558818/adrv9009-rx-to-tx
gr-iio
Tested in flowgraph, no crash
=> Fix crash due to broken IIO attribute updater

grc/gui_qt/components/canvas/connection.py, grc/gui_qt/components/window.py
Fixes #7284
In addition:
If on startup grc loads an invalid flowgraph, the fg is shown as valid, that is the error button is disabled.
If there are several tabs ar open that contain a mixture of valid and invalid fg's the error button is not adopted to the status of the selected tab.
This pr calculates  the status of the buttons individually for each tab depending on it's fg.
Fixes #7284
Build a simple fg, save it, delete a connection. Save the fg again.
Restart grc --qt 
The fg should  display an error as a connection is missing.
Open several tabs with an mixture of  correct and incorrect fg's and switch between the different tabs.
Watch the status of the 'errors' button
=> grc-qt: Fixing incorrect error display

gr-utils/modtool/cli/base.py
Relevant, since pkg_resources has been deprecated.
Used only for click_plugins, which has not been actively maintained
since 2019.
Fixes #7129
modtool only
ran gr_modtool, still lists all commands.
=> modtool: replace pkg_resources with import.metadata when available

cmake/Modules/GrCompilerSettings.cmake, gnuradio-runtime/lib/pmt/pmt.cc, gr-channels/lib/sincostable.h, gr-digital/include/gnuradio/digital/ofdm_carrier_allocator_cvc.h, gr-digital/lib/ofdm_carrier_allocator_cvc_impl.h, gr-digital/python/digital/bindings/ofdm_carrier_allocator_cvc_python.cc, gr-fec/include/gnuradio/fec/polar_common.h, gr-fec/include/gnuradio/fec/polar_decoder_common.h, gr-fec/lib/polar_decoder_common.cc, gr-fec/lib/scl_list.h, gr-fec/python/fec/bindings/polar_common_python.cc, gr-fec/python/fec/bindings/polar_decoder_common_python.cc, gr-qtgui/include/gnuradio/qtgui/DisplayPlot.h, gr-qtgui/include/gnuradio/qtgui/EyeDisplayPlot.h, gr-qtgui/include/gnuradio/qtgui/FrequencyDisplayPlot.h, gr-qtgui/include/gnuradio/qtgui/TimeDomainDisplayPlot.h, gr-qtgui/include/gnuradio/qtgui/VectorDisplayPlot.h, gr-qtgui/lib/DisplayPlot.cc, gr-qtgui/lib/EyeDisplayPlot.cc, gr-qtgui/lib/FrequencyDisplayPlot.cc, gr-qtgui/lib/TimeDomainDisplayPlot.cc, gr-qtgui/lib/VectorDisplayPlot.cc
Don't const-qualify POD return types; doing so is ignored and may lead to user confusion. This fixes `-Wignored-qualifiers` warnings.
Also, turn on `-Wignored-qualifiers` by default to try to stave off regressions.
None (code generation is unchanged).
Compiled locally with `-Werror=ignored-qualifiers` on Fedora 39.
=> Remove ignored qualifiers

gr-utils/modtool/templates/gr-newmod/python/howto/bindings/bind_oot_file.py
Empty argument leads to ('',) being propagated through to a -D"" argument for castxml.  Which then interprets the next argument as the define, which typically fails because defines can't include - in their name.
Fixes #6986
Hand tested.
No automated testing for this area of code.
Very isolated change, no flow on impact expected.
=> gr-modtool: Handle missing/empty string defines argument

gr-utils/modtool/tools/util_functions.py
When in commit 1e276f165ea7fd482102ca10a80076c61ad5ac07 unnecessary line
breaks were removed, appending to the C++ QA sources list in the
lib/CMakeLists.txt, failed, and thus, adding of C++ unit testing broke
the build.
The quick fix would have been to add the line breaks back to the
template. However, this cannot change existing OOTs; thus, the parsing
function needed to be amended to allow for working with existing OOTs.
Fixes #7131
modtool
https://gist.github.com/marcusmueller/9280bc7482d4cb616d2e303c8afcf430
Runs through; need to add fully automated unit tests once that's possible.
=> modtool: appending to CMake lists should respect closing `)`

gr-blocks/lib/blockinterleaving.cc, gr-blocks/python/blocks/qa_blockinterleaver_xx.py
=> blocks/blockinterleaving: rework permutation check to suppress warning (backport to maint-3.10)

gr-utils/modtool/cli/base.py
The return type incompatibly changed; need to account for breakage on older platforms.
In order to not let 3.10 and main code base diverge, here's the `main` targetting PR to the `maint-3.10` targetting #7342. 
Followup to #7317 
#7342
=> modtool: make importlib.metadata.entrypoints usage robust

gr-utils/modtool/cli/base.py
Backport #7317 
Backport #7346 
- **modtool: replace pkg_resources with import.metadata when available**
- **modtool: make importlib.metadata.entrypoints usage robust**
=> modtool: robustify entry points (backport to maint-3.10)

grc/gui_qt/components/variable_editor.py, grc/gui_qt/components/window.py, grc/gui_qt/grc.py
The Variable editor in grc-qt is an incomplete port of the Variable editor in grc --gtk
But as all the functionsof the editor like  add/delete/enable/disable block are already coded int the Mainwindow it's sufficient to map this functions from the editor by signal and slot mechanism to the correspondend functions in the Mainwindow.
Fixes #7305
Fixes #7306
Fixes #7307
Setup several fg's and edit the variables within the variable editor
=> grc-qt: Variable editor: fix several bugs

.ci_support/osx_64_numpy1.23python3.11.____cpython.yaml, .ci_support/win_64_numpy1.23python3.11.____cpython.yaml, .conda/recipe/conda_build_config.yaml
=> ci: conda: Build with VS2022 for Windows (backport to maint-3.10)

grc/gui_qt/components/window.py
QFileDialog defaults to an "open" dialog, which doesn't work for saving files (unless you want to overwrite an existing file). Change to use "save" mode for Save As and Save Copy dialogs.
GRC-Qt
=> grc-qt: AcceptSave mode for save dialog instead of AcceptOpen

grc/gui_qt/components/variable_editor.py
There are two types of variable blocks:
-  with key == variable
-  with key != variable
At the moment some blocks with key != variable force a KeyError.
File "/usr/local/gnuradio/lib64/python3.12/site-packages/gnuradio/grc/gui_qt/components/variable_editor.py", line 100, in set_scene
self.update_gui(self.scene.core.blocks)
File "/usr/local/gnuradio/lib64/python3.12/site-packages/gnuradio/grc/gui_qt/components/variable_editor.py", line 175, in update_gui
self._rebuild()
File "/usr/local/gnuradio/lib64/python3.12/site-packages/gnuradio/grc/gui_qt/components/variable_editor.py", line 165, in _rebuild
variable_.setText(1, block.params['value'].get_value())
~~~~~~~~~~~~^^^^^^^^^
KeyError: 'value'
Run grc --qt
Load the example example_corr_est_and_clock_sync.grc from digital/packet
=> grc-qt: Fix another KeyError in variable_editor

gr-utils/modtool/tools/grc_yaml_generator.py, gr-utils/modtool/tools/parser_cc_block.py
Fix the case where the comments (which are present in gr-newmod) in iosignatures break YAML gen
Fixes #5222
(At least for reasonable cases. Comments with nested comment symbols, or strings containing C comments, might lead to interesting results. But these are not likely to occur.
gr-modtool
https://gist.github.com/marcusmueller/f03ff708e0975c82dc80c06156c1ae3b
(can't do automatic tests before we fix modtool to run non-interactively)
=> modtool: Remove comments from C++ iosignatures

.github/workflows/make-test.yml
Fedora 38 is end-of-life. We should be adding Ubuntu 24.04 LTS as CI platform, so this is a removal in order to free up Github CPU minutes for that platform.
CI
=> CI: disable EOL F38 build

gr-utils/bindtool/templates/pydoc_h.mako, gr-utils/modtool/core/add.py
Due to an expectation mismatch between addition of binding code and pydoc code, noblock OOT python bindings did not compile.
Also required that modtool's add functionality only adds `make` bindings to actual blocks that have them.
Fixes #6960
modtool/OOTs
=> modtool fix noblock codegen

gr-fft/grc/fft_fft_vxx.block.yml, gr-fft/lib/fft_v_fftw.cc, gr-fft/python/fft/qa_fft.py
I add locks around window setting/usage.
As a drive-by improvement, let's not use floor, ceil to implement (inherent) integer division semantics.
Fixes #7144
FFT
=> FFT Window Threadsafety

gnuradio-runtime/apps/gnuradio-config-info.cc, gnuradio-runtime/include/gnuradio/sys_paths.h, gnuradio-runtime/lib/sys_paths.cc, gnuradio-runtime/python/gnuradio/gr/bindings/sys_paths_python.cc, gnuradio-runtime/python/gnuradio/gr/qa_sys_paths.py, grc/converter/main.py, grc/core/Config.py, grc/core/Constants.py, grc/core/generator/flow_graph.py.mako, grc/core/platform.py, grc/grc.conf.in, grc/gui/Config.py, grc/gui_qt/Config.py, grc/gui_qt/components/example_browser.py, grc/gui_qt/properties.py, grc/main.py
- **runtime/paths: add persistent() for persistent application data**
- **GRC: GR config & persistent state location instead of ~/.gnuradio || ~/.grc_gnuradio**
As discussed in [GRC Development](https://matrix.to/#/!BMFENoeifGOSJaeGco:gnuradio.org/$BblQe5QpHvTswR1Ypi42C1ZJ33i6xwfViBwH2KhBKkg?via=gnuradio.org&via=matrix.org&via=ei8fdb.org),
it would be the right thing if GRC configuration ends up in the same tree as
GNU Radio itself stores configuration. (And we're now doing `XDG_CONFIG_HOME`,
unless that doesn't exist, but the legacy `.gnuradio` does.)
Same for generated hier blocks: they should live in a standard persistent state
directory. And for caches from the example browser and block lib, use the
appropriate cache dir.
Luckily, GNU Radio offers these paths by now; `gr.paths` is …
=> make grc use correct config paths

gnuradio-runtime/include/gnuradio/block.h, gnuradio-runtime/python/gnuradio/gr/bindings/block_python.cc, gr-digital/lib/fll_band_edge_cc_impl.cc, gr-digital/lib/fll_band_edge_cc_impl.h, gr-digital/python/digital/qa_fll_band_edge.py
- digital: FLL band edge QA with noisy signal
- digital: FLL band edge: fix power calculation and thread safety
Closes #6466
Found the normalization bug and the numerical accuracy TODO while doing that
FLL bandedge
Added a test to demonstrate it now actually works oin noisy weather
=> FLL bandedge: fix math & thread safety bugs

grc/blocks/variable_function_probe.block.yml, grc/core/generator/flow_graph.py.mako, grc/core/generator/top_block.py
Add a `self.flowgraph_started` event to the Python Mako code and set it after the top block `start()` is called. This lets anything else that should not run until after everything is initiazed wait on the event.
The code generator does not know that certain blocks (e.g., function probe) depend on other blocks, and especially their accessors, to be available at the time a block may start its own thread. This caused a race between access in a thread spawned by code from a yml template and existance of the `self.` object.
Change the Function Probe Python template code to wait on the event before accessing variables, in case they don't exist yet.
Supercedes #7361
Fixes #7360
GRC code generation, Function Probe
=> Python template startup event

gr-uhd/CMakeLists.txt, gr-uhd/examples/grc/CMakeLists.txt, gr-uhd/grc/CMakeLists.txt, gr-uhd/python/uhd/CMakeLists.txt, gr-uhd/python/uhd/__init__.py
The push-button helper for the replay block uses PyQt5, however using gr-uhd in python as a whole should not be gated by PyQt5 being installed.
During some recent development, we ran into an error requiring PyQt5 being installed because the added replay block message button helper now added in an import for PyQt5, however everything else in gr-uhd doesn't require this python module.
To work around this, I added a try-except to ignore the module import error. Then I also removed the installation of the replay block message button related items in the cmake files, so that a user doesn't see functionality that they cannot use.
gr-uhd
Testing importing gnuradio.uhd no longer errors if PyQt5 is not installed, and checked that the related items are not installed (i.e. .py file, grc example, …
=> gr-uhd: Do not require PyQt5 for all python functionality

gr-utils/blocktool/core/parseheader.py, gr-utils/blocktool/core/parseheader_generic.py
There seems to be a bug where on some platforms, GCC fails because it finds the
_GLIBCXX_OPERATOR_DELETE and considers it a "non-usual deallocation function".
Even if that is inherent to C++17. Anyways, in
https://github.com/gnuradio/gnuradio/issues/6477 user boatbod convinces us that
adding -fsized_deallocations helps this. Neither we nor the GCC mailing lists
are perfectly sure why that is, but it does help. Since this is just for binding,
none of the thus-generated code ends up anywhere, which reduces the
headaches of introducing any random compiler flags.
Closes #6477
binding only, as these flags are *only* used for that and nowhere in our actual chain
none, as we're currently not set up for running such tests (other PRs need to go first)
=> modtool/bind: GCC12/13 on Ubuntu needs a flag for binding

grc/main.py
We want to make a directory to to contain the file grc.conf, newpath is the full pathname with the file included.  Make the directory without using newpath as it creates the directory $HOME/.config/gnuradio/grc.conf.
This pr contains a proposed small change for #7350.
Signed-off-by: Chris Gorman <chrisjohgorman@gmail.com>
When gnuradio-companion is run, it attempts to create the directory $HOME/.config/gnuradio/grc.conf.  There is no problem with this if the file is currently in place, but if there is no file in place it creates the directory and gnuradio can't source grc.conf.  This change fixes the problem and only creates the directory $HOME/.config/gnuradio if it doesn't exist.  There may be a further need to do this for the other case in get_config_file_path. 
```
except ImportError: …
```
=> Remove the filename from os.makedirs(newpath) in get_config_file_path

CMakeLists.txt, cmake/Modules/GrMinReq.cmake, gr-utils/modtool/templates/gr-newmod/CMakeLists.txt, grc/core/generator/cpp_templates/CMakeLists.txt.mako
=> cmake: Bump minimum required CMake version to what is specified (backport to maint-3.10)

gr-utils/blocktool/core/parseheader.py, gr-utils/blocktool/core/parseheader_generic.py
=> modtool/bind: GCC12/13 on Ubuntu needs a flag for binding (backport to maint-3.10)

grc/main.py
=> GRC: config directory creation shouldn't create dir named as config file (backport to maint-3.10)

grc/gui/Config.py, grc/gui_qt/Config.py
When os.path.join is used, it appends an extra directory to the config file path.  For grc the config file is $HOME/.config/gnuradio/grc.conf/grc.conf and for grc qt the file is $HOME/.config/gnuradio/grc.conf/grc_qt.conf.
This patch proposes to change this and remove the grc.conf directory from the path.  This would make the grc config file $HOME/.config/gnuradio/grc.conf and the grc qt config file $HOME/.config/gnuradio/grc_qt.conf.
All that is needed to accomplish this is to remove the use of os.path.join to generate the gui_prefs_file.
The above change removes the use of os.path.join(get_config_file_path(), 'grc.conf') to set the variable gui_prefs_file in both grc and grc_qt.
This change is required because current method adds an extra grc.conf directory to the config file path.
This …
=> gui_prefs_file does not need to use os.path.join

grc/core/Connection.py, grc/gui/PropsDialog.py
Without this fix, GRC tries to populate a full block-property dialog when opening a property dialog on connections. This improves the checking for the right attributes to correctly identify connections, and removes the following spurious output when opening property dialogs on connections:
```
File "..../grc/gui/PropsDialog.py", line 210, in update_gui
self._update_docs_page()
File "..../grc/gui/PropsDialog.py", line 219, in _update_docs_page
in_tree = self._block.category and self._block.category[0] == "Core"
AttributeError: 'Connection' object has no attribute 'category'
```
Opening a dialog before the fix:
After the fix:
AFAICT, only edges with properties.
See pics above.
=> grc: Improve check for connection in properties dialog

grc/core/ports/port.py
Fixes the following issue: Create a port with automatic type deduction which is *not* in the streaming domain (e.g., create an RFNoC RX streamer block with no changes to settings from the default).
GRC will attempt to guess the dtype of this port (e.g., if it is connected to another block that does sc16, it will now also be sc16). However, due to the order in which objects are evaluated, the first time this is attempted is before the connection objects are generated, which means the auto-type deduction will fail the first time it is attempted.
The issue is, on failure, we re-set the port domain to 'stream' unconditionally. If the port domain was anything else (e.g., as above, 'rfnoc') then it will temporarily disable any domain-specific settings until the connection object is created, …
=> grc: Don't overwrite port domain on auto-type deduction

grc/tests/test_qtbot.py
Fixes: #7448
As the behaviour of the blocklib window was modified, the corresponding tests must be modified , too. The first idea is to insert a KeyDown sequence in the add_block_from_query. But that did'nt work for me. The KeyDown sequence was not executed. The workaround is to use the press function rom pyautogui. To work properly some delays must be inserted.
Fixes #7448
Run
pytest grc/tests/test_qtbot.py
without errors
=> grc-qt: Fix failing tests

tools/clang_format.py
The old clang_format.py script searches for clang-format 7, but the version that the github CI uses is 14
Fixes #7063
tools
Verified that error stops when ran on a docker container running the same ubuntu version as the github ubuntu CI (22.04)
=> tools: update clang_format script to search for clang-format 14

grc/core/FlowGraph.py, grc/gui/Application.py, grc/gui_qt/components/window.py
**grc --gtk**
If you disable a block in flowgraph not all depending blocks are marked as invalid. Reenabling the disabled  block marks the fg as invalid. You have to open and close a block to mark the fg as valid.
**grc -qt**
Disableing and reenabling work without errors.
But disableing and Undo'ing leaves a fg invalid.
This issue is fixed by this pr.
Fixes #7367
**Start grc --gtk**
Load example_corr_est_and_and_clock_sync.grc from digital/packet
Select the Constellation object hdr_const
disable this block
enable this block again
The Correlator Estimator block gets invalid.
**Start grc --qt**
Load example_corr_est_and_and_clock_sync.grc from digital/packet
Select the Constellation object hdr_const
disable this block
press Ctrl+Z
The Correlator Estimator block remains invalid
=> grc: Attribute error

.github/workflows/make-test.yml
Saves us the whole pip install step. Less complexity is nice.
We removed the click-plugins dependency a while back. (never got used)
The mingw64 builder (seems to only exist on main) still installs them; no need to, so let's remove that.
Hopefully, none, but complexity of our CI script
n/a
=> github CI: Mingw64: don't install click-plugins; no longer used

gr-blocks/grc/blocks_sigmf_sink_minimal.block.yml, gr-blocks/grc/blocks_sigmf_source_minimal.block.yml
The SigMF dataset format strings shown in the SigMF Source & Sink (Minimal) blocks are incorrect. Here I've changed them in accordance with the specification (https://sigmf.org/#sigmf-dataset-format).
* SigMF Source (Minimal)
* SigMF Sink (Minimal)
I verified that the correct names appear in the drop-down menus, and that existing flow graphs still function after the change.
=> blocks: Fix displayed SigMF dataset format strings

CMakeLists.txt, gr-utils/modtool/CMakeLists.txt, gr-utils/modtool/cli/add.py, gr-utils/modtool/cli/base.py, gr-utils/modtool/cli/bind.py, gr-utils/modtool/cli/disable.py, gr-utils/modtool/cli/makeyaml.py, gr-utils/modtool/cli/newmod.py, gr-utils/modtool/cli/rename.py, gr-utils/modtool/cli/rm.py, gr-utils/modtool/cli/update.py, gr-utils/modtool/complete_bash.in, gr-utils/modtool/complete_fish.in, gr-utils/modtool/complete_zsh.in, gr-utils/modtool/core/add.py
Adds shell (tab) completions for `gr_modtool` using capabilities of Click ([docs](https://click.palletsprojects.com/en/8.1.x/shell-completion)).
Fixes #5206
gr_modtool
=> modtool: Add shell completions

grc/core/FlowGraph.py, grc/gui_qt/components/dialogs.py, grc/gui_qt/components/window.py
While grc --gtk maps the dtype file_open, file_save to a filedialog, that can be used to select a file, grc --qt maps this type to a string. So the value has to be known and can't be selected by an dialog.
This is changed by this pr.
In addition the editor displays error messages at the bottom corresponding to this block, if they exist. This is already done in grc --gtk.
PropsDialog
Just add a yaml_config block or  some File blocks.
=> grc-qt: Some improvements to the block parameter editor

grc/gui_qt/components/dialogs.py
If a block is disabled the error messages are misleading.
So display the block related error messages in the property editor
only for enabled blocks
=> grc-qt: Display block related error message only if the block is enabled 

grc/gui_qt/components/window.py
If the block is an hier block, the block source can be loaded by 
right clicking -> more -> Open hierarchical block
on the hier block.
Selecting multiple blocks works , too.
=> grc-qt: Implement open hier source

gr-digital/python/digital/qa_correlate_access_code_XX_ts.py
The following test code, which was added in #7125, now fails on the MinGW-w64 build:
https://github.com/gnuradio/gnuradio/blob/30a0aa916b227d7409238f7451f10e9786403955/gr-digital/python/digital/qa_correlate_access_code_XX_ts.py#L76-L78
```
ERROR: test_payload_lengths (__main__.test_correlate_access_code_XX_ts.test_payload_lengths)
File "D:/a/gnuradio/gnuradio/gr-digital/python/digital/qa_correlate_access_code_XX_ts.py", line 104, in test_payload_lengths
self._variable_payload_t(length)
File "D:/a/gnuradio/gnuradio/gr-digital/python/digital/qa_correlate_access_code_XX_ts.py", line 77, in _variable_payload_t …
```
=> digital: Fix NumPy 2 compatibility

gr-utils/blocktool/core/parseheader_generic.py
Module `modtool.cli` imports `ModToolAdd`, among other modules. `ModToolAdd` uses `BindingGenerator`, which uses `GenericHeaderParser`. However, `GenericHeaderParser` imports `ModToolException` from `modtool.cli`, and that creates a circular import scenario. Using `BlockToolException` instead of `modtool.cli.ModToolException` in `GenericHeaderParser._parse_cc_h` avoids importing `modtool.cli`.
https://github.com/gnuradio/gnuradio/pull/7474#issuecomment-2315803861
blocktool
- [`blocktool/tests/test_blocktool.py`](https://github.com/gnuradio/gnuradio/blob/30a0aa916b227d7409238f7451f10e9786403955/gr-utils/blocktool/tests/test_blocktool.py)
- Conda CI
=> blocktool: Resolve circular import

grc/core/generator/top_block.py, grc/main.py
Oversight on my side: new statedir is used for saving hier-blocks, but not for reading them
main version of maint-3.10 #7454
GRC
Manual
=> grc: use state directory in generated python

grc/core/generator/top_block.py
Running a flowgraph may fail  with
File "/home/schroer/gnuradiocomponents/Test/./callhier.py", line 24, in get_state_directory
log.warn(f"Found persistent state path '{newpath}', but file does not exist. " +
^^^
NameError: name 'log' is not defined
During handling of the above exception, another exception occurred:
File "/home/schroer/gnuradiocomponents/Test/./callhier.py", line 47, in <module>
sys.path.append(os.environ.get('GRC_HIER_PATH', get_state_directory()))
^^^^^^^^^^^^^^^^^^^^^
File "/home/schroer/gnuradiocomponents/Test/./callhier.py", line 33, in get_state_directory
log.warn("Could not retrieve GNU Radio persistent state directory from GNU Radio." +
^^^
NameError: name 'log' is not defined
This depends on …
=> grc: follow up to #7455

gr-blocks/python/blocks/qa_wavfile.py
In #7497 I added a new test (`test_read_wav_1024`) which fails on Windows.
According to the [documentation for `NamedTemporaryFile`](https://docs.python.org/3/library/tempfile.html), the temporary file cannot be opened a second time on Windows unless `delete=False` is used. (Elsewhere in GNU Radio's test suite, this approach is used.) Since the file is not automatically deleted, I've also added an `os.unlink()` call to clean up the temporary file.
Tests for Wav File Source.
Once the test suite runs, we'll see whether the failing test passes across all platforms.
=> blocks: Fix test_read_wav_1024 on Windows

grc/main.py
As noted in https://github.com/gnuradio/gnuradio/pull/7455#discussion_r1694352183, the fallback code paths in `get_config_file_path` and `get_state_directory` that execute when `gr::paths` does not exist reference a non-existent variable (`newpath`), which triggers an exception. The correct variable name in both cases is `xdgcand`.
GNU Radio Companion
I exercised the fallback code paths by changing `from gnuradio.gr import paths` to `from gnuradio.gr import xxxxx`, and verified that exceptions occur before the changes, and warning messages appear correctly afterwards.
=> grc: Fix warning message in fallback case

grc/gui_qt/components/dialogs.py
If a block contains many parameters, the PropsDialog is hard to read.
So this pr makes the parameter section scrollable.
As an example take a QT GUI Frequency sink block.
=> grc-qt: Improve readability of the PropsDialog

gr-utils/modtool/tools/util_functions.py
Under windows this fixes a problem with python modifying `__init__.py` improperly and I believe this will occur under linux as well.
Without this change `__init.py__` gets populated as follows.  (Without the `from .{_blockname} import {_blockname}` lines.)
```
#
#
'''
This is the GNU Radio CUSTOMMODULE module. Place your Python package
description here (python/__init__.py).
'''
import os
try:
from .customModule_python import *
except ModuleNotFoundError:
pass
#
```
This affects the `gr_modtool` tool, specifically the add python code function.
I stepped through the code with pdb under msys2 with gnuradio-3.10.11.0.  I have not tested this under linux, but believe the error will occur there too.  I would also like to ensure that this doesn't negatively impact cpp code generation as I have …
=> gr_modtool: util_functions.py add newline to variable modified_last

gr-blocks/tests/benchmark_common.h, gr-digital/lib/decision_feedback_equalizer_impl.cc, gr-digital/lib/linear_equalizer_impl.cc
`using namespace std;` is discouraged, because it can lead to namespace conflicts when updating to a newer version of the standard C++ library. Here I have removed the handful of usages that were in GNU Radio.
* Decision Feedback Equalizer
* Linear Equalizer
* Benchmarking code for NCO & VCO
None yet.
=> Avoid "using namespace std*"

.clang-tidy
routine test of clang-tidy revealed the .clang-tidy file can't be parsed.
none 
nope.
=> clang-tidy: remove unavailable option

grc/tests/test_qtbot.py
Meanwhile the Qt.Key_Enter is not always mapped to accept. So in some cases an extra Qt.Key_Enter has to be inserted.
The fg_path variable must be taken as string otherwise we get errors like:
CALL ERROR: Exceptions caught in Qt event loop:
________________________________________________________________________________ Traceback (most recent call last):
File "/home/schroer/gnuradiocomponents/gnuradio-volker/grc/gui_qt/components/window.py", line 1028, in save_triggered
self.save_as_triggered()
File "/home/schroer/gnuradiocomponents/gnuradio-volker/grc/gui_qt/components/window.py", line 1054, in save_as_triggered
self.add_recent_file(filename)
File "/home/schroer/gnuradiocomponents/gnuradio-volker/grc/gui_qt/components/window.py", line 1549, in add_recent_file …
=> grc-qt: Fix errors in qt related tests

.github/workflows/make-test.yml
We occasionally allow check-in of headers without the corresponding python bindings being updated. 
#7539
#5356 and a few more
=> CI: Check hashes

gnuradio-runtime/lib/thread/thread.cc
working on updating our aging gnuradio port from 3.8.2 to 3.10.11, upstreaming the patches we have that make sense..
gnuradio-runtime
zero runtime testing, patch builds in the context of the 3.10.11 release.
i've called out SDR users on OpenBSD to test the port update.
=> runtime: fix OpenBSD doesn't have prctl()

gr-blocks/include/gnuradio/blocks/wavfile_sink.h, gr-blocks/lib/wavfile_sink_impl.cc, gr-blocks/lib/wavfile_sink_impl.h, gr-blocks/python/blocks/bindings/wavfile_sink_python.cc
The current wavfile_sink block API has getter and
setter functions for the sample bit size. However, the setter function's
value is ignored because the sample size is fully determined 
by the file format and subformat. Additionally, the code is inconsistent, 
as the getter returns bytes instead of bits, and there is a risk 
of using uninitialized memory.
This update removes unnecessary operations and
resolves the inconsistency between bits and bytes.
This is preparation before solving 
https://github.com/gnuradio/gnuradio/issues/7456 
wawfile_sink
make test
=> blocks: Fix useless sample size functions in wavfile_sink.

README.md
(before change) images look stretched
=> Fix image ratio in readme

gr-blocks/lib/wavfile_sink_impl.cc, gr-blocks/lib/wavfile_sink_impl.h, gr-blocks/python/blocks/qa_wavfile.py
The flowgraph uses the stop() method of a block 
to indicate that it has been locked for
configuration. I believe the correct behavior for
file-based sinks is to write all data and headers
to disk, flush the file buffers, but avoid closing the file 
(see also #2590).
This behavior is implemented in the
file_sink. Since the file_sink is very simple and
does not require updating headers, flushing the
file is sufficient.
On the other hand, wavfile_sink can write to
several file formats, some of which include
headers. The implementation relies on libsndfile,
which provides a flush function. However, the
source code indicates that this function does not
update headers before flushing.
The current implementation of wavfile_sink calls
the close() method within the stop() method to
ensure the …
=> blocks: Reopen wavfile_sink after stop().

gr-soapy/grc/soapy_hackrf_source.block.yml
The RF gain was erroneously quoted to be 14 dB but in fact this is around 11 dB.
**Source:** https://hackrf.readthedocs.io/en/latest/faq.html#what-gain-controls-are-provided-by-hackrf
Soapy HackRF Source
- [ X] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [X ] I have squashed my commits to have one significant change per commit. 
- [ X] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed)
- [X ] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md).
=> soapy: fix hackrf RF gain value

.github/workflows/conda-build.yml
Github will be shutting down upload-artifacts v3 in January, 2025.
See here: https://github.com/actions/upload-artifact?tab=readme-ov-file#actionsupload-artifact
=> github ci: conda: Update upload-artifacts

gr-blocks/lib/mute_impl.cc, gr-blocks/lib/mute_impl.h, gr-blocks/lib/selector_impl.cc, gr-blocks/python/blocks/qa_mute.py
Changed the message handlers of the mute and selector blocks so they can receive pdu messages.
Also added a qa test for floats for the mute block and simplified the work function of the mute block
in an attempt to make it more readable.
Fixes #5099 
The _set-mute_ port of the mute block and the _en_ port of the selector block now 
can receive both raw PMT values and PDUs as messages.
The work function of the mute block was simplified as the old version was not easy to read,
specifically the code that handled forwarding the input values.
Manual
=> gr-blocks: Add PDU support to mute and selector blocks

gnuradio-runtime/lib/pmt/qa_pmt_unv.cc, gr-audio/examples/c++/dial_tone.cc, gr-blocks/lib/annotator_raw_impl.cc, gr-blocks/lib/file_meta_sink_impl.cc, gr-blocks/lib/file_meta_sink_impl.h, gr-blocks/lib/file_meta_source_impl.h, gr-blocks/lib/test_tag_variable_rate_ff_impl.cc, gr-blocks/tests/benchmark_common.h, gr-digital/lib/corr_est_cc_impl.h, gr-digital/lib/decision_feedback_equalizer_impl.cc, gr-digital/lib/linear_equalizer_impl.cc, gr-digital/lib/pfb_clock_sync_ccf_impl.cc, gr-digital/lib/pfb_clock_sync_ccf_impl.h, gr-digital/lib/pfb_clock_sync_fff_impl.cc, gr-digital/lib/pfb_clock_sync_fff_impl.h, gr-qtgui/examples/c++/display_qt.cc, gr-qtgui/examples/c++/display_qt.h, gr-uhd/lib/usrp_block_impl.cc
Backport #6969 (needed for merge conflict)
Backport #7524
Backport #7526
The first PR was originally left (a year ago) out due to issues with certain compilers.
=> Avoid using namespace for std all larger namespaces (backport to maint-3.10)

gnuradio-runtime/lib/thread/thread.cc
=> runtime: fix OpenBSD doesn't have prctl() (backport to maint-3.10)

gr-analog/python/analog/qa_quadrature_demod.py
Add unit test for the quadrature demod block to verify that it can decode frequency modulated signals.
Fixes #2020
analog.quadrature_demod_cf
Ran "make test" before and after changes to ensure all tests pass
=> analog: add end-to-end test for quadrature demod block

gnuradio-runtime/include/gnuradio/tags.h, gnuradio-runtime/lib/CMakeLists.txt, gnuradio-runtime/lib/tag_fmt.cc, gnuradio-runtime/python/gnuradio/gr/bindings/tags_python.cc
enables direct logging of tags
Logging tags should be easy. Now it is!
```c++
d_logger->warn("Saw unforeseen tag: {}", tag);
```
=> runtime: add formatter for tag_t

gnuradio-runtime/include/gnuradio/block.h, gnuradio-runtime/include/gnuradio/tagged_stream_block.h, gnuradio-runtime/lib/block_executor.cc, gnuradio-runtime/lib/tagged_stream_block.cc, gnuradio-runtime/python/gnuradio/gr/bindings/block_python.cc, gnuradio-runtime/python/gnuradio/gr/bindings/tagged_stream_block_python.cc, gr-blocks/lib/tagged_stream_mux_impl.cc, gr-digital/lib/packet_headergenerator_bb_impl.cc, gr-digital/python/digital/qa_ofdm_txrx.py
Before, the TSB superclass used to modify the contents input buffer tags
vector, adding itself to the list of blocks whom to not show the tag on
tags with the length tag key.
Now, instead of doing that, it simply "filters" what TSBs see by
(non-virtually) overriding get_tags_in_{range,window}.
This removes a contention point, avoids adding complex data to the
oft-copied blocks, and removes the usage of the deprecated
`block::remove_item_tag`. It was the last consumer of that function, so
that can now be retired.
Fixes a small problem with `qa_ofdm_txrx` (1040.0 is not exactly the
same as 1040), and correctly copies tags from in- to output in
`digital::packet_headergenerator_bb_impl`.
Closes #7627
TSBs
Full test suite, covering same functionality, which lead to the fixing of …
=> Tagged Stream Block: don't remove item tags from input, don't show them internally instead

gnuradio-runtime/include/gnuradio/block.h, gnuradio-runtime/include/gnuradio/block_detail.h, gnuradio-runtime/include/gnuradio/buffer.h, gnuradio-runtime/include/gnuradio/buffer_reader.h, gnuradio-runtime/include/gnuradio/tags.h, gnuradio-runtime/lib/block.cc, gnuradio-runtime/lib/block_detail.cc, gnuradio-runtime/lib/block_executor.cc, gnuradio-runtime/lib/buffer.cc, gnuradio-runtime/lib/buffer_reader.cc, gnuradio-runtime/python/gnuradio/gr/bindings/block_detail_python.cc, gnuradio-runtime/python/gnuradio/gr/bindings/block_python.cc, gnuradio-runtime/python/gnuradio/gr/bindings/buffer_python.cc, gnuradio-runtime/python/gnuradio/gr/bindings/buffer_reader_python.cc, gnuradio-runtime/python/gnuradio/gr/bindings/docstrings/block_detail_pydoc_template.h, gnuradio-runtime/python/gnuradio/gr/bindings/docstrings/buffer_pydoc_template.h, gnuradio-runtime/python/gnuradio/gr/bindings/tags_python.cc
With TSBs no longer marking tags as deleted in their input buffer, we
can drop the "Will be removed in 3.8"-deprecated
`block::remove_item_tag`.
With that gone, nothing can put blocks on the "am I deleted for this
particular block?" vector of tags. Hence, the functions called from
`block::get_tags_in_range`, `block_detail::…`, and
`buffer_reader::get_tags_in_range` no longer need to check whether a
block is on that list. Hence, remove that check, and the "who is
asking?" `id` argument.
These were all long-deprecated or internal/detail API anyways, so we're
not breaking compatibility.
It'd be more than desirable to remove the deletion list from `tag_t`,
but that's an API breakage (though I **really** hope nobody was using
that public field of the struct), and should be done in a separate …
=> Get rid of block::remove_item_tag and related infrastructure, checks

gr-qtgui/lib/eye_sink_c_impl.cc, gr-qtgui/lib/eye_sink_f_impl.cc, gr-qtgui/lib/time_sink_f_impl.cc
See title.
I take issue with a header called `something_detail.h` being included outside `something` and its QA.
My pride.
builds.
=> qtgui: don't include block detail! You're not even using that.

gnuradio-runtime/include/gnuradio/tags.h, gnuradio-runtime/lib/CMakeLists.txt, gnuradio-runtime/lib/qa_tags.cc, gnuradio-runtime/python/gnuradio/gr/bindings/tags_python.cc
with the work done to wean tagged stream blocks off `remove_item_tag`, we can now remove the `marked_deleted` member.
Depends on 
- #7639
- #7640
Tags; tags being among the most-handled objects, shaving up some 24-30 B for an unused `std::vector` member should actually be nice for cache locality when walking through the tag tree in gr::buffer (pending moving from a `std::multimap` to a `std::multiset` with the foreign-key `<container>::lower_bound` functionality).
=> tag_t: clean up marked_deleted

gnuradio-runtime/lib/qa_tags.cc
Due to a terrible mistake on my end, I used C++20 aggregate initialization with *designated* initializers. Can't do that in C++17 with MSVC !
should build on MSVC now, let's watch the CI
=> runtime: fix qa_tags using C++ too modern for MSVC

gnuradio-runtime/include/gnuradio/block.h, gnuradio-runtime/include/gnuradio/block_detail.h, gnuradio-runtime/include/gnuradio/buffer_reader.h, gnuradio-runtime/lib/block.cc, gnuradio-runtime/lib/block_detail.cc, gnuradio-runtime/lib/buffer_reader.cc, gnuradio-runtime/python/gnuradio/gr/bindings/block_gateway.h, gnuradio-runtime/python/gnuradio/gr/bindings/block_gateway_python.cc, gnuradio-runtime/python/gnuradio/gr/bindings/block_python.cc, gnuradio-runtime/python/gnuradio/gr/bindings/buffer_reader_python.cc, gnuradio-runtime/python/gnuradio/gr/bindings/tagged_stream_block_python.cc, gnuradio-runtime/python/gnuradio/gr/qa_tag_utils.py
All to common is a scheme where a consumer of tags needs to do this
dance:
```c++
std::vector<gr::tag_t> tags;
get_tags_in_range(tags, 0, start, end, d_phase_est_key);
if(!tags.empty) {
float phase = pmt::to_float(tags[0].value);
if(phase >= -M_PI && phase < M_PI) {
d_phase = phase;
}
}
```
but no more with `get_first_tag_in_range`!
```c++
auto tag = get_first_tag_in_range(0, start, end, d_phase_est_key);
if(tag) {
float phase = pmt::to_float(tag.value.value);
if(phase >= -M_PI && phase < M_PI) {
d_phase = phase;
}
}
```
But wait! It gets even better! You can *filter with a predicate*:
```c++
auto tag = get_first_tag_in_range(0,
start,
end,
[this](const gr::tag_t& tag) {
if(tag.key != d_phase_est_key)
return false;
float phase = pmt::to_float(
tag.value.value);
return phase >= -M_PI
&& …
```
=> runtime: block gets get_first_tag_in_range(…, predicate) and …, tag)

cmake/Modules/GrVersion.cmake, gnuradio-runtime/include/gnuradio/CMakeLists.txt, gnuradio-runtime/include/gnuradio/version.h.in
As discussed in #Development, it seems a common and desirable thing to have a version preprocessor statement.
Short survey of /usr/include suggests that gnuradio/version.h is a good name.
Needed this to be able to future-remove features in the source code. 
none, unless you want to use it
=> runtime: add configure-time version.h[.in] with GR_VERSION_{MAJOR,API,MINOR,MAINT}

gnuradio-runtime/include/gnuradio/block.h, gnuradio-runtime/include/gnuradio/block_detail.h, gnuradio-runtime/lib/block_detail.cc, gnuradio-runtime/python/gnuradio/gr/bindings/block_python.cc, gr-digital/lib/symbol_sync_cc_impl.cc, gr-digital/lib/symbol_sync_ff_impl.cc
`block::get_tags_in_range` fills the passed vector in a sorted manner. That became the case after we replaced the deque implementation with a `std::multimap<uint64_t offset, tag_t tag>` somewhen after GRCon'14.
`gr-uhd` definitely already depends on that, and a lot of other places do, as well. So, we should document this behaviour.
Also, we should remove the remaining places where we still sorted the vector.
Closes #7621
Only documentation
=> Document that tags are already sorted, don't sort them

gr-uhd/lib/rfnoc_replay_impl.cc
Previously, the stop command was not taking into account the command port, so any stop commands would only stop playback on port 0 of the replay block.
In my original implementation, the command port was left off when sending the stop command, so every stop command stopped port 0.
gr-uhd
Tested with an X310. Performed play, stop, and record on both port 0 and 1 of the replay block.
=> gr-uhd: use command port for stop function

CMakeLists.txt
For some reason, clang warns about this specific command line option when there's no complex operation affected by it in the compilation unit. Get rid of that.
Removes a couple hundred meaningless compiler warnings on clang on F41.
continues to compile
=> cmake: suppressed clang++ warnings that -fcx-limited-range wasn't used

grc/gui_qt/components/block_library.py
With #7644 on option was introduced to display the lib in collapsed or expanded state. But due to a bug only the first category was expanded. This is fixed now.
The search field was not cleared, if you selected a block by key_down and then pressing return.
This is fixed now, too.
Without and with option selected
=> grc-qt: block library follow up to #7644

gnuradio-runtime/lib/pmt/pmt_serialize.cc
'pubseekoff' method was used probably with intention to move the std::streambuff's internal position into the right place. However this was already done by 'sgetn' method. With both calls: to 'sgetn' and to 'pubseekoff', the internal position of the 'sb' streambuff ended up being wrong.
Fixes #7672
Affects all blocks that use pmt::deserialize(...) function. I.e. these blocks from gr-zeromq:
- pull_msg_source,
- req_msg_source,
- sub_msg_source.
The test source is provided in issue #7672.
- [ x] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [x ] I have squashed my commits to have one significant change per commit. 
- [x ] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.m …
=> PMT: Remove detrimental calls to 'pubseekoff' from de-serialization

gr-filter/grc/filter_pfb_channelizer_hier.block.yml
Fixes #7484 by checking both the number of channels being produced AND the output map (if provided) to determine the actual number of output ports that the block will produce at runtime.
Full description is in issue #7484
This issue (and patch) only affects GNURadio Companion.
I used the example flow graph in issue #7484 to both reproduce the issue and to verify the fix.
=> grc: Fix issue #7484 (channelizer output count incorrect in some situations).

CMakeLists.txt
=> cmake: suppressed clang++ warnings that -fcx-limited-range wasn't used (backport to maint-3.10)

gr-uhd/examples/grc/uhd_siggen_gui.grc
The example was in a totally broken state. This restores functionality, and makes it look like a subset of the uhd_siggen_gui command line application, which was originally created from this .grc file (albeit with many, many improvements along the line)
Here's the flow graph:
Closes https://github.com/gnuradio/gnuradio/issues/7498.
Just this specific gr-uhd example.
Here you can see `uhd_fft` and this example in tandem: The two-tone is nicely causing RF trouble as it should.
=> uhd: Fix uhd_siggen_gui.grc example

gr-blocks/python/blocks/qa_wavfile.py
As noted in #7685, `test_003_checkwav_append_copy` is flaky because it accidentally runs two Wav File Sinks in parallel, which can stomp on each other. Starting from a fresh flow graph in part 3 of the test solves the problem.
Fixes #7685.
Tests for Wav File Source & Wav File Sink.
I ran `qa_wavfile.py` in a loop (`while gr-blocks/python/blocks/qa_wavfile_test.sh; do :; done`) in parallel with `stress -c 32`. Prior to this change, `test_003_checkwav_append_copy` readily fails, and afterwards it runs without fail.
=> blocks: Use a fresh flow graph for part 3 of append test

gr-uhd/lib/rfnoc_graph_impl.cc
gr-uhd contained a bug where back-edges were not being properly propagated into UHD (meaning, the setting was not being set in the corresponding UHD call).
In addition, we add a warning when attempting to define an edge to a streamer node as a back-edge. Because these edges are never the cause of a loop, the underlying UHD API does not allow tagging these as back-edges. If someone attempts to declare a streamer-edge as a back-edge, we will now emit a warning on the logger interface.
Fixes https://github.com/gnuradio/gnuradio/issues/7353.
RFNoC applications with loops.
I used `rfnoc_radio_loopback.grc` to first reproduce the error, and then test this fix. Both were straightforward. This works best on an X410 or X440, for some reason the default X310 configuration won't let you do a …
=> uhd: Fix connecting back-edges

grc/gui_qt/components/variable_editor.py, grc/gui_qt/components/window.py
Add the property dialog to the variable_editor contextmenu
Partially fixes #7615
The missing context sensitivity should be handled  in an other pr.
Add the property dialog to the variable_editor contextmenu
This is an alternative solution for #7690
The missing context sensitivity should be handled  in an other pr.
Partially fixes #7615
Just open an existing fg and right click in the variable editor and open properties
=> grc-qt: Fix properties dialog in variable editor, alternativ solution

gr-uhd/grc/uhd_fpga_split_stream.block.yml
In the image builder version, the split_stream block erroneously defined a ce_clk input. However, the split-stream block operates at rfnoc_clk and thus does not require this input.
This is the bad input:
Only affects trying to build FPGA bitfiles for RFNoC devices out of GRC using the split stream block.
Building bitfiles now works.
=> uhd: rfnoc: Remove ce_clk input from split_stream

gr-uhd/grc/uhd_fpga_addsub.block.yml, gr-uhd/grc/uhd_fpga_chdr_dma_ta.block.yml, gr-uhd/grc/uhd_fpga_ddc.block.yml, gr-uhd/grc/uhd_fpga_device_bsp.block.yml, gr-uhd/grc/uhd_fpga_device_none.block.yml, gr-uhd/grc/uhd_fpga_duc.block.yml, gr-uhd/grc/uhd_fpga_eth_ta.block.yml, gr-uhd/grc/uhd_fpga_fosphor.block.yml, gr-uhd/grc/uhd_fpga_keep_one_in_n.block.yml, gr-uhd/grc/uhd_fpga_null_src_sink.block.yml, gr-uhd/grc/uhd_fpga_radio.block.yml, gr-uhd/grc/uhd_fpga_replay.block.yml, gr-uhd/grc/uhd_fpga_sep.block.yml, gr-uhd/grc/uhd_fpga_siggen.block.yml, gr-uhd/grc/uhd_fpga_split_stream.block.yml, gr-uhd/grc/uhd_fpga_switchboard.block.yml
The image builder GRC bindings all have a 'type' parameter, which is hidden, and is used by `rfnoc_image_builder` to identify the block type. It was defined as an enum, to limit (and document) the available options.
However, in GRC, when you push the down or up keys on the keyboard while selecting a block, you change the first parameter that is an enum. For example, if you selected the terminator block and push down, it changes the 'type' to 'block', which confuses `rfnoc_image_builder`.
The "fix" is to simply make all of these 'type' parameters strings.
To understand the bug, if you're interested, try this:
- Open x310_image_core.grc from gr-uhd (in GTK-GRC)
- Select one of the "No connect" blocks
- Push down-arrow
- Save
- Look at the diff of `x310_image_core.grc`. You have now changed …
=> uhd: rfnoc: Remove enum block type from image builder blocks

gnuradio-runtime/lib/pmt/pmt_serialize.cc
=> PMT: Remove detrimental calls to 'pubseekoff' from de-serialization (backport to maint-3.10)

gr-uhd/grc/uhd_fpga_device_bsp.block.yml
When designing RFNoC bitfiles for X440, the radio clock ports need to be differently named (X440 has clocks `radio0` and `radio1`, X410 only has a `radio` clock).
No open issue on Github, but if you want to build a bitfile for X440, it should look like this (which is fixed by this PR):
Instead, it shows the same `radio_clk` port as if it were an X410.
Only people building RFNoC bitfiles through GRC for X440.
See picture above.
=> uhd: Fix radio clocks for X440 / image builder

gr-digital/lib/timing_error_detector.h
Fixes #7752
- [ X ] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [ X ] I have squashed my commits to have one significant change per commit. 
- [ X ] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md).
- [ N/A ] I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.
- [ N/A ] I have added tests to cover my changes, and all previous tests pass.
=> gr-digital: fix early_late ted computation depth to match actual depth

gr-uhd/lib/usrp_source_impl.cc
Generally, if the USRP source block's centre frequency is altered, then the output stream is tagged with the current frequency. However, at present if the center frequency is altered via message passing, then these tags are not generated. This PR fixes this functionality by using the `set_center_freq` member function. This performs the same functionality as the original code with the addition of properly setting the `_tag_now` flag.
Fixes #7725 
The "USRP Source block". It changes the behaviour **only** around the generation of stream tags when the frequency is retuned via message passing.
I tested the change by building GNU Radio from source using my forked repo, which implemented the fix. I created a basic flowgraph, which allows you to send messages manually and check a tag was …
=> uhd: Generate tags when frequency changed from message port.

.github/workflows/make-test.yml, gr-uhd/grc/CMakeLists.txt, tools/check_installation_duplicates.bash
three files appeard twice in gr-uhd/grc/CMakeLists.txt and hence got "doubly installed".
Which is not a problem until you make uninstall or such.
Generally, recommendation should probably be to sort file lists and check for duplicates, but this just honestly seems to have slipped through the cracks. Happens!
installation
added a github check. not something a human should need to think about too much.
=> remove duplicately installed files

gnuradio-runtime/include/gnuradio/buffer_reader_sm.h, gr-blocks/lib/ctrlport_probe2_b_impl.h, gr-blocks/lib/ctrlport_probe2_c_impl.h, gr-blocks/lib/ctrlport_probe2_f_impl.h, gr-blocks/lib/ctrlport_probe2_i_impl.h, gr-blocks/lib/ctrlport_probe2_s_impl.h, gr-blocks/lib/ctrlport_probe_c_impl.h, gr-digital/lib/crc_append_impl.h, gr-digital/lib/crc_check_impl.h, gr-digital/lib/descrambler_bb_impl.h, gr-digital/lib/glfsr_source_b_impl.h, gr-digital/lib/glfsr_source_f_impl.h, gr-digital/lib/scrambler_bb_impl.h, gr-fft/lib/ctrlport_probe_psd_impl.h, gr-qtgui/include/gnuradio/qtgui/timeRasterGlobalData.h, gr-qtgui/include/gnuradio/qtgui/waterfallGlobalData.h, gr-qtgui/lib/matrix_display.h, gr-qtgui/lib/matrix_display_signal.h, gr-qtgui/lib/matrix_sink_impl.h, gr-soapy/lib/block_impl.h
as found through applying clang-tidy (see #7760),
```shell
clang-tidy -p /path/to/build --fix \
$( grep modernize-use-override /path/to/clang-tidy.log | sed 's/^\([^:]*\):.*/\1/' | sort -u)
```
Code quality / style consistency
still compiles, tests still pass. This should not be a functional change
=> whole-tree: consistently use 'override'

grc/core/Messages.py
This fixes a rare corner case seen in unit tests, where multiple tests interfere with one another.
During the execution of unit tests for the pluggable workflow PR, this sometimes happened. I couldn't quite track it down, but when you run multiple GRC-related tasks in quick succession in a unit test, the output messenger would fail to open-and-close the file descriptor.
=> grc: Accept failures in message sending

grc/converter/flow_graph.py
Old XML-based GRC files don't necessarily provide output_language, but they only supported Python anyway, so we auto-populate that field.
For example, `grc/tests/resources/test_compiler.grc ` does not specify a language, only the `generate_options`. I had an intermediate state of the GRC pluggable workflow where knowing the language was required, but I do think this is a safe change regardless.
I was seeing some failures in GRC unit tests related to this. They don't occur on master, but this change is sensible and useful by itself.
Only XML import of old flow graphs.
I've run GRC tests more than I care while working on the pluggable workflows.
=> grc: xml converter: Supply default output_language

.clang-tidy
New checks! Actually found bugs with the RAII checker.
Clang-tidy evolves, and there's new checks. Added a few helpful ones. #7759, for example, is something that was raised this way.
=> clang-tidy: update .clang-tidy file

grc/core/generator/cpp_hier_block.py, grc/core/generator/cpp_top_block.py, grc/core/generator/hier_block.py, grc/core/generator/top_block.py, grc/gui/Application.py, grc/gui_qt/components/window.py
When generating a flow graph, we make the generator aware if it's being called directly, or implied by "execute". This can be useful for future workflows.
In the RFNoC workflow that I built, the "generate" step is pretty expensive. Because calling "execute" always implies calling "generate", it's good to know where that came from. You can see more info by looking at the RFNoC workflow in #7548.
This change by itself doesn't actually change anything, it just lays down groundwork.
The RFNoC workflow is a good test case, but the other tests and GRC functions still work with this as before.
=> grc: Make generate aware of execution

gr-fec/python/fec/bindings/generic_decoder_python.cc, gr-fec/python/fec/bindings/generic_encoder_python.cc
This allows to use all FEC encoders and decoders by just creating corresponding encoder and decoder objects in Python and without creating a flowgraph
Adds additional methods to the Python class, to call the generic_work functions with numpy buffers. 
fec/generic_encoder fec/generic_decoder
I'd like to add some test, but first I'd like to see the opinion on having this kind of change in-tree.
=> fec: Add encode and decode functions to generic encoder bindings

gr-uhd/examples/grc/rfnoc_images/x310_image_core.grc, gr-uhd/grc/CMakeLists.txt, gr-uhd/grc/rfnoc_image_builder.workflow.yml, gr-uhd/python/uhd/CMakeLists.txt, gr-uhd/python/uhd/grc_workflows.py, grc/gui_qt/components/executor.py
Note: This PR is dependent in #7548! This adds the RFNoC build-bitfile workflow.
Allows users to build RFNoC bitfiles directly from GRC, without having to manually call into the `rfnoc_image_builder`.
See #7548 for a bunch of pictures.
In the language drop-down menu in GRC, it will add a new option, visible to anyone.
See #7548.
=> uhd: Add RFNoC GRC workflow

gr-blocks/lib/patterned_interleaver_impl.cc, gr-blocks/lib/patterned_interleaver_impl.h
We were doing a lot of unnecessary copies, and that with avoidable reallocations, every call to work. Fixed that.
In the second commit, also moved thread-unsafe members out of public view, and implementation detail to _impl.cc
(first commit can be backported, second can't)
blocks / patterned interleaver
no new tests
=> Drive-by: improve patterned interleaver

tools/run-clang-tidy-check.zsh
This was in my git stash: My tool to run a single check on the whole tree.
=> tools: add tool to run a single clang-tidy check

gr-utils/modtool/templates/gr-newmod/python/howto/bindings/bind_oot_file.py
Without this fix, whenever bind_oot_file.py is called (e.g., through CMake because something changed), a new <modulename>_python.cc file is generated. During the re-generation, the include path in this file is corrupted. After running `gr_modtool newmod foo`, and creating a block (`gr_modtool add bar`), the file gr-foo/python/bindings/bar_python.cc contains this line:
```cpp
#include <gnuradio/foo/bar.h>
```
Afterwards, this line is modified to:
```cpp
#include <foo/bar.h>
```
I could not find an issue. We had a complaint for `gr-rfnoc_gain`, which is part of our RFNoC OOT example.
Re-binding.
I tested this on `gr-rfnoc_gain`, which is available here: https://github.com/EttusResearch/uhd/tree/master/host/examples/rfnoc-gain/gr-rfnoc_gain
This is what I did:
- Build the OOT
- Modify …
=> bindtool: Always append gnuradio/ in bindings include path

gr-utils/modtool/core/add.py
This PR fixes a swapped description for the source and sink blocks when using `gr_modtool add`.
None.
Only the output of modtool is affected, no actual code is changed.
Running `gr_modtool add`.
=> modtool: Fix swapped sink and source descriptions

gr-blocks/lib/annotator_raw_impl.cc, gr-blocks/lib/annotator_raw_impl.h, gr-blocks/python/blocks/qa_annotator_raw.py
`annotator_raw` used a vector as queue for randomly inserted tags (i.e., things were re-sorted all the time). Changed that.
Worse, honestly, is that it had no test coverage. Changed that, too.
Closes #7624
I thought #7624 was a good beginner's issue to fix, especially with how much work I put into describing the necessary changes. It seems it wasn't, really. Sigh.
annotator_raw
added new unit test that also covers the temporal aspects
=> blocks/annotator_raw: use set instead of vector to avoid sorting

gnuradio-runtime/python/gnuradio/gr/CMakeLists.txt, gr-blocks/python/blocks/qa_annotator_raw.py
- **blocks/annotator_raw: QA sporadically fails on overtasked mac QA**
- **runtime/qa_get_first_tag_in_range: Don't test until underlying deadlock solved**
The QA has been failing on windows builds and occassionally on Mac builds. This is bad. Let's not run known-to-be-broken QA on main.
Read #7771 for details on deadlocking
We now contain the `get_first_tag_in_range` API on main, with no unit test. So, don't use that API until we fix it.
This PR's CI should run through.
=> Make QA pass qa_annotator_raw and _get_first_tag_in_range again

gr-filter/include/gnuradio/filter/CMakeLists.txt
This PR adds back the missing mmse_fir_interpolator header file being used by mmse_fir_interpolator_ff and mmse_fir_interpolator_cc header files.
Trying to compile oot modules using mmse_fir_interpolator keep failing due to missing mmse_fir_interpolator.h file in gnuradio/filter folder.
Example:
```
In file included from /home/bjk/gnuradio/src/modules/gr-bluetooth/lib/../include/bluetooth/multi_block.h:30,
from /home/bjk/gnuradio/src/modules/gr-bluetooth/lib/multi_block.cc:31:
/home/bjk/gnuradio/include/gnuradio/filter/mmse_fir_interpolator_ff.h:16:10: fatal error: gnuradio/filter/mmse_fir_interpolator.h: File or directory not found
16 | #include <gnuradio/filter/mmse_fir_interpolator.h>
|          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
Several oot projects …
=> gr_filter: Add missing mmse_fir_interpolator.h to filter include directory on install

grc/gui_qt/components/window.py
Despite using qtpy, the signature for opening files on PyQt5 and PySide2 is different. Luckily, the order of arguments is the same, so by not using keyword arguments, we can make this call cross-compatible.
On PyQt5, the third argument is called 'directory', and on PySide2, it's called 'dir'.
I didn't open a bug for this, but if you have PyQt5 and not PySide2 (which apparently is the default on Ubuntu 22.04), then you will see this when trying to open a file with the Qt version:
```
File "[...]/python3.10/site-packages/gnuradio/grc/gui_qt/components/window.py", line 982, in open_triggered
filename = self.open()
File "[...]/python3.10/site-packages/gnuradio/grc/gui_qt/components/window.py", line 893, in open            filename, filtr = Open(
TypeError: getOpenFileName(parent: QWidget = …
```
=> grc: Fix GRC-Qt file open dialog on PyQt5

cmake/Modules/GrPybind.cmake, gnuradio-runtime/include/gnuradio/rpcregisterhelpers.h, gnuradio-runtime/python/gnuradio/gr/bindings/rpcregisterhelpers_python.cc
By definition, pybind has to bind even deprecated functions (until we
actually remove them).
So, erroring out when we do that is not an option.
Backport of #7747
=> pybind/building: don't error on deprecated symbols (backport to 3.10)

gr-filter/include/gnuradio/filter/CMakeLists.txt
Backport of #7842 
Signed-off-by: info@revskills.de <info@revskills.de>
=> Add missing mmse_fir_interpolator.h to CMake (maint-3.10)

gr-utils/modtool/templates/gr-newmod/python/howto/bindings/bind_oot_file.py
Backport of #7814 
Without this fix, whenever bind_oot_file.py is called (e.g., through
CMake because something changed), a new <modulename>_python.cc file is
generated. During the re-generation, the include path in this file is
corrupted. After running `gr_modtool newmod foo`, and creating a block
(`gr_modtool add bar`), the file gr-foo/python/bindings/bar_python.cc
contains this line:
```cpp
#include <gnuradio/foo/bar.h>
```
Afterwards, this line is modified to:
```cpp
#include <foo/bar.h>
```
=> BP 7814 (binding prepend path)

gr-blocks/python/blocks/qa_annotator_raw.py
Backport of the relevant part of #7853 
----
Increase overall processing time to increase tolerances
Puh, this is really not a tight race to win, and the macOS builder still
manages to lose it.
=> blocks/annotator_raw: QA sporadically fails on overtasked mac QA (maint-3.10)

gnuradio-runtime/lib/buffer_single_mapped.cc
In `buffer_single_mapped`, we make a small mistake where we create a scoped lock as a temporary object.
#7760
Hopefully, none? Realistically, it fixes a bug.
Tests continue to pass. I just wonder know whether *acquiring* the lock was what was sufficient, not holding it.
=> buffer_single_mapped: locking needs a named object

.github/workflows/make-test.yml
It's that time of year when I get around to updating my CI builder. Same for GNU Radio, I guess.
Helpful understanding esp. #7757 on modern platforms
=> CI: Fedora 42 builder, cycle Fedora versions

gr-blocks/python/blocks/qa_annotator_raw.py
It seems the qa_annotator_raw test really needs to be run with lots of tolerances, as there's no guarantee that sleep(0.4) is close to 400 ms of sleep. (I.e., in practice, the test failed, because the insertion happened more than 500ms, i.e., 100 ms too late.)
=> annotator_raw: give Mac a lot of time. It needs it.

gr-audio/docs/audio.dox, gr-audio/lib/audio_registry.cc, gr-audio/lib/audio_registry.h
I made a mistake 4 years ago that gave the "windows" sink a different
priority than the source. That led to great user confusion.
Make sure that doesn't happen again. Instead, keep priorities in a
central map.
Remove the internal and unused registry functions that just create a struct manually instead of using the aggregate initialization method / default constructor.
Fixes #7784
inner workings of gr-audio. Should un-shamble windows.
works on my machine. We don't have CI coverage, that's another bug (#2539)
=> audio: unify priorities between sink and source architectures

gr-utils/modtool/cli/add.py, gr-utils/modtool/core/add.py, gr-utils/modtool/templates/templates.py, gr-utils/modtool/tools/code_generator.py
This extends gr_modtool to also generate C++ block controllers for RFNoC blocks:
gr_modtool add -t rfnoc_block
...will create such a block controller. C++ RFNoC blocks allow control of RFNoC blocks from GNU Radio, even though GNU Radio does not control the streaming through such blocks.
I tested this on `gr-rfnoc_gain`, and tried to recreate the same code that was manually created (and is heavily vetted).
=> modtool: Add support for rfnoc_block

gr-digital/include/gnuradio/digital/ofdm_sync_sc_cfb.h
- Fix formatting that makes it harder for Doxygen to operate
- Improve comment on use_even_carriers
While reviewing #7837, I had  to re-read this and thought it needed some touching up.
=> digital: Improve Doxy header for ofdm_sync_sc_cfb

gr-digital/python/digital/bindings/ofdm_sync_sc_cfb_python.cc
We had a bit of an oops (https://github.com/gnuradio/gnuradio/actions/runs/15774247818/job/44464991973) on main. this fixes the hash.
=> digital: fix binding hash

gr-digital/python/digital/ofdm_txrx.py
The OFDM Loopback example doesn't work with even carriers in Sync Word 1 (used in the IEEE 802.15.4 SUN PHY), because [OFDM Receiver](https://wiki.gnuradio.org/index.php/OFDM_Receiver) doesn't set the **use_even_carriers** parameter in its call to the Schmidl & Cox synchronizer.
Without this fix OFDM Receiver can't synchronize if **Sync Word 1** (the STF in 802.15.4) uses even carriers. This fix detects whether even or odd carriers are used, complains if both are and sets the **use_even_carriers** parameter in the call to the Schmidl & Cox synchronizer accordingly.
Corrected version of [7825](https://github.com/gnuradio/gnuradio/pull/7825)
- gr-digital/python/digital/ofdm_txrx.py
Tested with all IEEE 802.15.4 SUN PHY ODFM Options (1-4).
=> OFDM Receiver: add support for even carriers in STF

gr-uhd/grc/CMakeLists.txt, gr-uhd/grc/uhd.tree.yml, gr-uhd/grc/uhd_fpga_fir_filter.block.yml
Adds the FIR Filter to the RFNoC Image Builder
This only affects the FIR Filter RFNoC block on the RFNoC Image Builder side. 
Added the block to the Image and Build it with without getting an Error.
=> uhd: Add FIR filter block support to RFNoC image builder

gr-uhd/examples/grc/rfnoc_fosphor.grc
The example is changed to set the spp value of the radio block to the desired FFT size, so that FFT blocks of all generations can handle the data.
Otherwise, 'rfnoc rx streamer: warning : Received fractional vector! Expect signal fagmentation.' would occur.
Supersedes https://github.com/gnuradio/gnuradio/pull/7885
One example in gr-uhd.
=> uhd: Fix rfnoc_fosphor.grc by setting radio block args

cmake/Modules/GnuradioConfig.cmake.in, cmake/Modules/GrBoost.cmake
When testing upcoming Boost 1.89.0 in Homebrew (https://github.com/Homebrew/homebrew-core/pull/233031), GNU Radio build failed due to Boost.System changes.
Boost.System has been header-only since Boost 1.69 and will be dropping the compatibility stub library in Boost 1.89 (boostorg/system@7a495bb). Since GNU Radio uses Boost >= 1.69, the easy fix is to drop `system`
from the `COMPONENTS` as recommended by upstream: `https://github.com/boostorg/system/issues/132#issuecomment-3146378680`
https://github.com/gnuradio/gnuradio/blob/721e477cdb4ed22214ed886d6063cff2dac7d0b5/cmake/Modules/GrMinReq.cmake#L13
N/A
CMake / build
Checked successful local compilation with Boost 1.89.0.beta1. Built on macOS 15 arm64 in Homebrew environment.
=> cmake: fix build with Boost 1.89.0

grc/gui/canvas/colors.py
The previous yellow color for bypassed blocks was often confused by new users with the orange for deprecated blocks or red for errored blocks.
This commit changes the color to a more neutral and distinct Light Steel Blue (#b0c4de) for better UI clarity.
Fixes #7914
This change resolves a UI clarity issue where the yellow color for bypassed blocks was easily confused with the orange/red used for deprecated or errored states.
The bypassed color is updated to a neutral and distinct Light Steel Blue (`#b0c4de`). The implementation also introduces the `BLOCK_BYPASSED_COLOR` constant, aligning the variable name with its usage in the GRC block rendering code. This ensures the UI can correctly apply the new color.
Fixes #7914
This change affects the GNU Radio Companion (GRC) user interface, …
=> GRC: Change bypassed block color to blue-gray

cmake/Modules/GnuradioConfig.cmake.in, cmake/Modules/GrBoost.cmake
Boost.System has been header-only since Boost 1.69 and will be dropping
the compatibility stub library in Boost 1.89 (boostorg/system@7a495bb).
Since GNU Radio uses Boost >= 1.69, the easy fix is to drop `system`
from the `COMPONENTS` as recommended by upstream:
`https://github.com/boostorg/system/issues/132#issuecomment-3146378680`
Signed-off-by: Michael Cho <michael@michaelcho.dev>
=> bp #7904: fix build with Boost 1.89

gr-uhd/CMakeLists.txt
If we do a GNU Radio 3.11, I want to limit the available UHD versions. Going to UHD 4 would have been nice for me, but I think some people will want to stay on UHD 3 for some reason and there's plenty of gr-uhd that works just fine with that.
=> uhd: Bump minimum UHD version to 3.15

gr-qtgui/examples/qtgui_numeric_entry.grc, gr-qtgui/grc/qtgui.tree.yml, gr-qtgui/grc/qtgui_numeric_entry.block.yml, gr-qtgui/python/qtgui/CMakeLists.txt, gr-qtgui/python/qtgui/__init__.py, gr-qtgui/python/qtgui/numeric_entry.py
The numeric entry widget combines the useful features of Range and Entry widgets and adds support for unit handling, numeric expressions in any common format and lower/upper bounds.
Examples (unit Hz):
"0.1" -> 0.1 Hz
"1e3" -> 1000 Hz
"5*2-3" -> 7 Hz
"8 kHz" -> 8000 Hz
"30m" -> 0.03 Hz
When the entry is focussed, the user can use the UP/DOWN keys to in-/decrement the value by the specified increment, and the PageUp/PageDown for ten times the increment.
The label color is used to indicate the status:
blue = editing but value not yet applied
red = invalid input
black = value applied
If the variable is changed from some other place in the flowgraph via the top block's "set_xxx()" callback, or if one of the boundaries (min/max value) changes, this is reflected on the UI
The precision defines …
=> gr-qtgui: Add numeric entry widget
